### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by andrei923** [SkriptLang/Skript#1128]
[02:08:18 WARN]: [Skript] Task #7 for Skript v2.2-dev33 generated an exception
java.lang.NoSuchMethodError: net.md_5.bungee.api.chat.BaseComponent.setInsertion(Ljava/lang/String;)V
        at ch.njol.skript.util.chat.BungeeConverter.convert(BungeeConverter.java:45) ~[?:?]
        at ch.njol.skript.util.chat.BungeeConverter.convert(BungeeConverter.java:60) ~[?:?]
        at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:88) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:55) ~[?:?]
        at ch.njol.skript.events.EvtScript.register(EvtScript.java:61) ~[?:?]
        at ch.njol.skript.ScriptLoader$3.call(ScriptLoader.java:675) ~[?:?]
        at ch.njol.skript.ScriptLoader$3.call(ScriptLoader.java:1) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:694) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:289) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:319) ~[?:?]
        at ch.njol.skript.Skript$2.run(Skript.java:444) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by UzumakiYT** [comment]
`on load:
	send "&a&l< &7&l-------------------------------------------- &a&l>" to console
	send "" to console
	send "{@prefix} &aLoading &ev.{@plugin-version}&a..." to console
	send "{@prefix} &e%size of {sg.arenas::*}% &agames loaded!" to console
	send "{@prefix} &a&lPlugin loaded!" to console
	send "" to console
	send "&a&l< &7&l-------------------------------------------- &a&l>" to console
	loop all players:
		if {sg.player.%uuid of loop-player%.playing} = "InGame" or "InGameSPEC":
			send "{@prefix} &7RESTART" to loop-value
			sg_leave(loop-player)		
	loop {sg.arenas::*}:	
		sg_resetarena(loop-value)	
		wait 1 seconds			
			

on unload:
	send "&a&l< &7&l-------------------------------------------- &a&l>" to console
	send "" to console
	send "{@prefix} &aDisabling &ev.{@plugin-version}&a..." to console
	send "{@prefix} &ev.{@plugin-version} &adisabled!" to console
	send "" to console
	send "&a&l< &7&l-------------------------------------------- &a&l>" to console
	stop`

**Comment by Pikachu920** [comment]
for anyone looking at this issue, the solution is to use the latest 1.8 paperspigot or install the bungee chat api separately

**Comment by UzumakiYT** [comment]
@Pikachu920 i can't find bungee chat api

**Comment by Nicofisi** [comment]
Then just use paperspigot, it's simply a better version of spigot

**Comment by UzumakiYT** [comment]
ok, thanks for help Pikachu920 and Nicofisi.
