### ISSUE TITLE
There is an error with a skript and two addons

### ISSUE THREAD

**Issue by OngMong** [SkriptLang/Skript#1183]
I can't start my skript for using GUI menu skript,
Because there is some error messages when I start bukkit with this.

Below is that error message

[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! [Skript] Severe Error:
[17:07:33 ERROR]: #!#! Could not load menu.sk
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! Something went horribly wrong with Skript.
[17:07:33 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:07:33 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[17:07:33 ERROR]: #!#! Here is full list of them:
[17:07:33 ERROR]: #!#! InvSK SkQuery
[17:07:33 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[17:07:33 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[17:07:33 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[17:07:33 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[17:07:33 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[17:07:33 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[17:07:33 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! Stack trace:
[17:07:33 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for lambda
[17:07:33 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1790)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1757)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1505)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:495)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:812)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1521)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1478)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1517)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1478)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1478)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:919)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:488)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:571)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:289)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:319)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:778)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:161)
[17:07:33 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:07:33 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:07:33 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[17:07:33 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[17:07:33 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[17:07:33 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! Version Information:
[17:07:33 ERROR]: #!#!   Skript: 2.2-dev34 (latest)
[17:07:33 ERROR]: #!#!   Bukkit: 1.9-R0.1-SNAPSHOT
[17:07:33 ERROR]: #!#!   Minecraft: 1.9
[17:07:33 ERROR]: #!#!   Java: 1.8.0_161 (Java HotSpot(TM) 64-Bit Server VM 25.161-b12)
[17:07:33 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! Server platform: Spigot
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! Current node: open chest with 3 rows named "&f[ &6&lMenu &f]" to player (menu.sk, line 3)
[17:07:33 ERROR]: #!#! Current item: null
[17:07:33 ERROR]: #!#! Thread: Server thread
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! Language: english
[17:07:33 ERROR]: #!#! Link parse mode: DISABLED
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! End of Error.
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! [Skript] Severe Error:
[17:07:33 ERROR]: #!#! Could not load welcome.sk
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! Something went horribly wrong with Skript.
[17:07:33 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:07:33 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[17:07:33 ERROR]: #!#! Here is full list of them:
[17:07:33 ERROR]: #!#! InvSK SkQuery
[17:07:33 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[17:07:33 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[17:07:33 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[17:07:33 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[17:07:33 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[17:07:33 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[17:07:33 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! Stack trace:
[17:07:33 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for lambda
[17:07:33 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1790)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1757)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1505)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:495)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:812)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1521)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1451)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1478)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:919)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:612)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:289)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:319)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:778)
[17:07:33 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:161)
[17:07:33 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:07:33 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:07:33 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[17:07:33 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[17:07:33 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[17:07:33 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[17:07:33 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! Version Information:
[17:07:33 ERROR]: #!#!   Skript: 2.2-dev34 (latest)
[17:07:33 ERROR]: #!#!   Bukkit: 1.9-R0.1-SNAPSHOT
[17:07:33 ERROR]: #!#!   Minecraft: 1.9
[17:07:33 ERROR]: #!#!   Java: 1.8.0_161 (Java HotSpot(TM) 64-Bit Server VM 25.161-b12)
[17:07:33 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! Server platform: Spigot
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! Current node: wait 1 seconds (welcome.sk, line 7)
[17:07:33 ERROR]: #!#! Current item: null
[17:07:33 ERROR]: #!#! Thread: Server thread
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! Language: english
[17:07:33 ERROR]: #!#! Link parse mode: DISABLED
[17:07:33 ERROR]: #!#!
[17:07:33 ERROR]: #!#! End of Error.
[17:07:33 ERROR]: #!#!

Plz help me..

**Comment by Nicofisi** [comment]
What did you change when it *started* happening? Added an addon? Changed something in a script? Changed what?

**Comment by bensku** [comment]
Broken and/or incompatible addons are most likely cause. Have you contacted their developers?

**Comment by TheLimeGlass** [comment]
For 1.9+ you need to use an update version of SkQuery. I have made a fix for this in my fork of SkQuery https://forums.skunity.com/resources/unofficial-skquery-fork-1-6-1-12.68/

This issue can be closed as I have fixed and seen this issue.

**Comment by OngMong** [comment]
@TheLimeGlass
Thank you. I'll try it
