### ISSUE TITLE
SkriptAPIException: UnparsedLiterals must be converted before use

### ISSUE THREAD

**Issue by kh498** [SkriptLang/Skript#1223]
When executing `send "%random element of (true and true)%"` from console (with the effect command token) an exception is thrown
```
[13:14:36 INFO]: executing 'send "%random element of (true and true)%"'
[13:14:36 ERROR]: #!#!
[13:14:36 ERROR]: #!#! [Skript] Severe Error:
[13:14:36 ERROR]: #!#! Unexpected error while executing effect command 'send "%random element of (true and true)%"' by 'CONSOLE'
[13:14:36 ERROR]: #!#!
[13:14:36 ERROR]: #!#! Something went horribly wrong with Skript.
[13:14:36 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:14:36 ERROR]: #!#! You should report it at https://github.com/bensku/Skript/issues. Please copy paste this report there (or use paste service).
[13:14:36 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[13:14:36 ERROR]: #!#!
[13:14:36 ERROR]: #!#! Stack trace:
[13:14:36 ERROR]: #!#! ch.njol.skript.SkriptAPIException: UnparsedLiterals must be converted before use
[13:14:36 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.invalidAccessException(UnparsedLiteral.java:273)
[13:14:36 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getAll(UnparsedLiteral.java:283)
[13:14:36 ERROR]: #!#!     at ch.njol.skript.lang.ExpressionList.getAll(ExpressionList.java:116)
[13:14:36 ERROR]: #!#!     at ch.njol.skript.lang.ExpressionList.getArray(ExpressionList.java:99)
[13:14:36 ERROR]: #!#!     at ch.njol.skript.expressions.ExprElement.get(ExprElement.java:82)
[13:14:36 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:104)
[13:14:36 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:440)
[13:14:36 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getSingle(VariableString.java:599)
[13:14:36 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getSingle(VariableString.java:1)
[13:14:36 ERROR]: #!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:90)
[13:14:36 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[13:14:36 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:281)
[13:14:36 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:180)
[13:14:36 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35)
[13:14:36 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[13:14:36 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:14:36 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515)
[13:14:36 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500)
[13:14:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:460)
[13:14:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:428)
[13:14:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[13:14:36 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[13:14:36 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[13:14:36 ERROR]: #!#!
[13:14:36 ERROR]: #!#! Version Information:
[13:14:36 ERROR]: #!#!   Skript: 2.2-dev35b (latest)
[13:14:36 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[13:14:36 ERROR]: #!#!   Minecraft: 1.12.2
[13:14:36 ERROR]: #!#!   Java: 1.8.0_171 (Java HotSpot(TM) 64-Bit Server VM 25.171-b11)
[13:14:36 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:14:36 ERROR]: #!#!
[13:14:36 ERROR]: #!#! Server platform: Paper
[13:14:36 ERROR]: #!#!
[13:14:36 ERROR]: #!#! Current node: null
[13:14:36 ERROR]: #!#! Current item: null
[13:14:36 ERROR]: #!#!
[13:14:36 ERROR]: #!#! Thread: Server thread
[13:14:36 ERROR]: #!#!
[13:14:36 ERROR]: #!#! Language: english
[13:14:36 ERROR]: #!#! Link parse mode: DISABLED
[13:14:36 ERROR]: #!#!
[13:14:36 ERROR]: #!#! End of Error.
[13:14:36 ERROR]: #!#!
[13:14:36 INFO]: An internal error occurred while executing this effect. Please refer to the server log for details
```

**Comment by bensku** [comment]
Is this a new issue?

**Comment by Blueyescat** [comment]
Can't understand this expression: random element of (true and true)
Can't understand this expression: random element of (true and true)

Is this actually a fix?

**Comment by kh498** [comment]
I guess it's no longer a feature...
Is there another way of doing this?
