### ISSUE TITLE
PlayerUtils NPE

### ISSUE THREAD

**Issue by Elguerrero11** [SkriptLang/Skript#1252]
In console the task spam me:
```
[21:29:18] [Server thread/WARN]: [Skript] Task #604 for Skript v2.2-dev35b generated an exception
java.lang.NullPointerException: null
	at ch.njol.skript.bukkitutil.PlayerUtils$1.run(PlayerUtils.java:67) ~[Skript(7).jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[21:29:18] [Server thread/WARN]: java.lang.NullPointerException
[21:29:18] [Server thread/WARN]: 	at ch.njol.skript.bukkitutil.PlayerUtils$1.run(PlayerUtils.java:67)
[21:29:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[21:29:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[21:29:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[21:29:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:29:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[21:29:18] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[21:29:18] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[21:29:18] [Server thread/WARN]: java.lang.NullPointerException
```

**Comment by TheBentoBox** [comment]
Probably not a big deal but something could likely use more sanity checks.

**Comment by bensku** [comment]
This is likely related to usage of /reload. Please comment if that was not the case.

**Comment by Elguerrero11** [comment]
Ok thanks by all,anyway i will not use more skript at the moment but thanks by all,and sorry if i answer later,i dont use so much GitHub,have a nice day
