### ISSUE TITLE
TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception while loading

### ISSUE THREAD

**Issue by lucasdidur** [SkriptLang/Skript#1336]
[10:38:34] [Server thread/ERROR]: #!#! 
[10:38:35] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[10:38:35] [Server thread/ERROR]: #!#! TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception while loading
[10:38:35] [Server thread/ERROR]: #!#! 
[10:38:35] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[10:38:35] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[10:38:35] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[10:38:35] [Server thread/ERROR]: #!#! Following plugins are probably related to this error in some way:
[10:38:35] [Server thread/ERROR]: #!#! TuSKe (github.com/Tuke-Nuke/TuSKe) 
[10:38:35] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[10:38:35] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[10:38:35] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[10:38:35] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[10:38:35] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[10:38:35] [Server thread/ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[10:38:35] [Server thread/ERROR]: #!#! 
[10:38:35] [Server thread/ERROR]: #!#! Stack trace:
[10:38:35] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[10:38:35] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
[10:38:35] [Server thread/ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[10:38:35] [Server thread/ERROR]: #!#!     at java.lang.Class.forName(Class.java:348)
[10:38:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[10:38:35] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.TuSKe.onEnable(TuSKe.java:100)
[10:38:35] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:38:35] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[10:38:35] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:38:35] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[10:38:35] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[10:38:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[10:38:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[10:38:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[10:38:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293)
[10:38:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[10:38:35] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[10:38:35] [Server thread/ERROR]: #!#! 
[10:38:35] [Server thread/ERROR]: #!#! Version Information:
[10:38:35] [Server thread/ERROR]: #!#!   Skript: 2.2-dev36
[10:38:35] [Server thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[10:38:35] [Server thread/ERROR]: #!#!   Minecraft: 1.12.2
[10:38:35] [Server thread/ERROR]: #!#!   Java: 1.8.0_161 (Java HotSpot(TM) 64-Bit Server VM 25.161-b12)
[10:38:35] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.4.0-72-generic
[10:38:35] [Server thread/ERROR]: #!#! 
[10:38:35] [Server thread/ERROR]: #!#! Server platform: Paper
[10:38:35] [Server thread/ERROR]: #!#! 
[10:38:35] [Server thread/ERROR]: #!#! Current node: null
[10:38:35] [Server thread/ERROR]: #!#! Current item: null
[10:38:35] [Server thread/ERROR]: #!#! 
[10:38:35] [Server thread/ERROR]: #!#! Thread: Server thread
[10:38:35] [Server thread/ERROR]: #!#! 
[10:38:35] [Server thread/ERROR]: #!#! Language: english
[10:38:35] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[10:38:35] [Server thread/ERROR]: #!#! 
[10:38:35] [Server thread/ERROR]: #!#! End of Error.
[10:38:35] [Server thread/ERROR]: #!#!

**Comment by Blueyescat** [comment]
read the update note <https://github.com/SkriptLang/Skript/releases/tag/dev35b>

**Comment by lucasdidur** [comment]
I did not understand.

**Comment by Blueyescat** [comment]
Click on the link.

**Comment by lucasdidur** [comment]
I clicked, and then ...
