### ISSUE TITLE
Can't reloading skripts

### ISSUE THREAD

**Issue by Raph9213** [SkriptLang/Skript#1340]
Hello,
In my server i can't reload skripts.

My error is:

[18:37:43] [Server thread/ERROR]: #!#! 
[18:37:43] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[18:37:43] [Server thread/ERROR]: #!#! Exception occurred in Skript's main command
[18:37:43] [Server thread/ERROR]: #!#! Used command: /sk reload booster
[18:37:43] [Server thread/ERROR]: #!#! 
[18:37:43] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[18:37:43] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[18:37:43] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[18:37:43] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[18:37:43] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[18:37:43] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[18:37:43] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[18:37:43] [Server thread/ERROR]: #!#! 
[18:37:43] [Server thread/ERROR]: #!#! Stack trace:
[18:37:43] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[18:37:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.clearFunctions(Functions.java:269)
[18:37:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.removeTriggers(SkriptEventHandler.java:240)
[18:37:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript_(ScriptLoader.java:712)
[18:37:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:705)
[18:37:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:183)
[18:37:43] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:37:43] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:37:43] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:646)
[18:37:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349)
[18:37:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184)
[18:37:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:37:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:37:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[18:37:43] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:37:43] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:37:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
[18:37:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726)
[18:37:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[18:37:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[18:37:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[18:37:43] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[18:37:43] [Server thread/ERROR]: #!#! 
[18:37:43] [Server thread/ERROR]: #!#! Version Information:
[18:37:43] [Server thread/ERROR]: #!#!   Skript: 2.2-dev27
[18:37:43] [Server thread/ERROR]: #!#!   Bukkit: 1.9.4-R0.1-SNAPSHOT
[18:37:43] [Server thread/ERROR]: #!#!   Minecraft: 1.9.4
[18:37:43] [Server thread/ERROR]: #!#!   Java: 1.8.0_72 (Java HotSpot(TM) 64-Bit Server VM 25.72-b15)
[18:37:43] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.9.0-0.bpo.5-amd64
[18:37:43] [Server thread/ERROR]: #!#! 
[18:37:43] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[18:37:43] [Server thread/ERROR]: #!#! 
[18:37:43] [Server thread/ERROR]: #!#! Current node: null
[18:37:43] [Server thread/ERROR]: #!#! Current item: null
[18:37:43] [Server thread/ERROR]: #!#! 
[18:37:43] [Server thread/ERROR]: #!#! Thread: Server thread
[18:37:43] [Server thread/ERROR]: #!#! 
[18:37:43] [Server thread/ERROR]: #!#! End of Error.
[18:37:43] [Server thread/ERROR]: #!#! 

I just tap /sk reload booster

Wky i have this error ?

:)

**Comment by TheBentoBox** [comment]
Update your Skript to the latest version, we don't accept issues from people using out-of-date versions.
