### ISSUE TITLE
Sort expression not handling UnparsedLiterals properly

### ISSUE THREAD

**Issue by kuba2003tv** [SkriptLang/Skript#1360]
[21:27:23 ERROR]: #!#!
[21:27:23 ERROR]: #!#! [Skript] Severe Error:
[21:27:23 ERROR]: #!#!
[21:27:23 ERROR]: #!#! Something went horribly wrong with Skript.
[21:27:23 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[21:27:23 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[21:27:23 ERROR]: #!#! Here is full list of them:
[21:27:23 ERROR]: #!#! skRayFall (http://sk.rayfall.net/) skript-ping SkriptJSON SkIris skDragon skUtilities (https://tim740.github.io/) SkQuery MundoSK (https://forums.skunity.com/resources/mundosk.69/) Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) SharpSK
[21:27:23 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[21:27:23 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[21:27:23 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[21:27:23 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[21:27:23 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[21:27:23 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[21:27:23 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[21:27:23 ERROR]: #!#!
[21:27:23 ERROR]: #!#! Stack trace:
[21:27:23 ERROR]: #!#! ch.njol.skript.SkriptAPIException: UnparsedLiterals must be converted before use
[21:27:23 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.invalidAccessException(UnparsedLiteral.java:273)
[21:27:23 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getAll(UnparsedLiteral.java:283)
[21:27:23 ERROR]: #!#!     at ch.njol.skript.expressions.ExprSortedList.get(ExprSortedList.java:67)
[21:27:23 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[21:27:23 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:440)
[21:27:23 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getSingle(VariableString.java:599)
[21:27:23 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getSingle(VariableString.java:1)
[21:27:23 ERROR]: #!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:90)
[21:27:23 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[21:27:23 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[21:27:23 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[21:27:23 ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:101)
[21:27:23 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[21:27:23 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[21:27:23 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:839)
[21:27:23 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[21:27:23 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773)
[21:27:23 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[21:27:23 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[21:27:23 ERROR]: #!#!
[21:27:23 ERROR]: #!#! Version Information:
[21:27:23 ERROR]: #!#!   Skript: 2.2-dev36 (latest)
[21:27:23 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[21:27:23 ERROR]: #!#!   Minecraft: 1.12.2
[21:27:23 ERROR]: #!#!   Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
[21:27:23 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[21:27:23 ERROR]: #!#!
[21:27:23 ERROR]: #!#! Server platform: Paper
[21:27:23 ERROR]: #!#!
[21:27:23 ERROR]: #!#! Current node: null
[21:27:23 ERROR]: #!#! Current item: send "%{score_konec::*}%sorted list%" to event-player/console
[21:27:23 ERROR]: #!#! Current trigger: command /topkills (simple event) (top.sk, line -1)
[21:27:23 ERROR]: #!#!
[21:27:23 ERROR]: #!#! Thread: Server thread
[21:27:23 ERROR]: #!#!
[21:27:23 ERROR]: #!#! Language: english
[21:27:23 ERROR]: #!#! Link parse mode: DISABLED
[21:27:23 ERROR]: #!#!
[21:27:23 ERROR]: #!#! End of Error.
[21:27:23 ERROR]: #!#!

**Comment by jaylawl** [comment]
```21:27:23 ERROR: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
21:27:23 ERROR: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
21:27:23 ERROR: #!#! In that case, you will be given instruction on how should you report it.
21:27:23 ERROR: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
21:27:23 ERROR: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
21:27:23 ERROR: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)```

^ Please read what's in the log you posted

**Comment by kuba2003tv** [comment]
@jaylawl 

After removing the plugins the problem continues to occur...
Sorry my english is very bad, i using Google Translator 😭.

[21:44:13 ERROR]: #!#!
[21:44:13 ERROR]: #!#! [Skript] Severe Error:
[21:44:13 ERROR]: #!#!
[21:44:13 ERROR]: #!#! Something went horribly wrong with Skript.
[21:44:13 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[21:44:13 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[21:44:13 ERROR]: #!#! Here is full list of them:
[21:44:13 ERROR]: #!#! SkIris
[21:44:13 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[21:44:13 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[21:44:13 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[21:44:13 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[21:44:13 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[21:44:13 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[21:44:13 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[21:44:13 ERROR]: #!#!
[21:44:13 ERROR]: #!#! Stack trace:
[21:44:13 ERROR]: #!#! ch.njol.skript.SkriptAPIException: UnparsedLiterals must be converted before use
[21:44:13 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.invalidAccessException(UnparsedLiteral.java:273)
[21:44:13 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getAll(UnparsedLiteral.java:283)
[21:44:13 ERROR]: #!#!     at ch.njol.skript.expressions.ExprSortedList.get(ExprSortedList.java:67)
[21:44:13 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[21:44:13 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:440)
[21:44:13 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getSingle(VariableString.java:599)
[21:44:13 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getSingle(VariableString.java:1)
[21:44:13 ERROR]: #!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:90)
[21:44:13 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[21:44:13 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[21:44:13 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[21:44:13 ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:101)
[21:44:13 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[21:44:13 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[21:44:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:839)
[21:44:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[21:44:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773)
[21:44:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[21:44:13 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[21:44:13 ERROR]: #!#!
[21:44:13 ERROR]: #!#! Version Information:
[21:44:13 ERROR]: #!#!   Skript: 2.2-dev36 (latest)
[21:44:13 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[21:44:13 ERROR]: #!#!   Minecraft: 1.12.2
[21:44:13 ERROR]: #!#!   Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
[21:44:13 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[21:44:13 ERROR]: #!#!
[21:44:13 ERROR]: #!#! Server platform: Paper
[21:44:13 ERROR]: #!#!
[21:44:13 ERROR]: #!#! Current node: null
[21:44:13 ERROR]: #!#! Current item: send "%{score_konec::*}%sorted list%" to event-player/console
[21:44:13 ERROR]: #!#! Current trigger: command /topkills (simple event) (gowno.sk, line -1)
[21:44:13 ERROR]: #!#!
[21:44:13 ERROR]: #!#! Thread: Server thread
[21:44:13 ERROR]: #!#!
[21:44:13 ERROR]: #!#! Language: english
[21:44:13 ERROR]: #!#! Link parse mode: DISABLED
[21:44:13 ERROR]: #!#!
[21:44:13 ERROR]: #!#! End of Error.
[21:44:13 ERROR]: #!#!
>

**Comment by Snow-Pyon** [comment]
You're using the expression wrongly, it should be used like this:
```vb
send "%sorted {score_konec::*}%"
```

That said, this kind of errors should be properly handled, pretty easy with the new LiteralUtils class.

**Comment by Snow-Pyon** [comment]
Fixed for the next release (https://github.com/SkriptLang/Skript/commit/e5211400c6ca34a84c6dab140bdde9416a75ba04)
