### ISSUE TITLE
1.12.2 Internal error occurred crash

### ISSUE THREAD

**Issue by natsoup** [SkriptLang/Skript#1381]
[00:45:01 INFO]: Natsoupp issued server command: /skript
[00:45:01 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'skript' in plugin Skript v2.2-dev36 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[craftbukkit.jar:git-Bukkit-57ab4cf]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit.jar:git-Bukkit-57ab4cf]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:628) ~[craftbukkit.jar:git-Bukkit-57ab4cf]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1338) [craftbukkit.jar:git-Bukkit-57ab4cf]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1198) [craftbukkit.jar:git-Bukkit-57ab4cf]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit.jar:git-Bukkit-57ab4cf]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit.jar:git-Bukkit-57ab4cf]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-57ab4cf]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_172]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_172]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Bukkit-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696) [craftbukkit.jar:git-Bukkit-57ab4cf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit.jar:git-Bukkit-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit.jar:git-Bukkit-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit.jar:git-Bukkit-57ab4cf]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
>

**Comment by Snow-Pyon** [comment]
Skript isn't compatible with CraftBukkit, use Spigot or Paper.
