### ISSUE TITLE
2.2-dev37 with TuSKe problem

### ISSUE THREAD

**Issue by aCatWithRedEyes** [SkriptLang/Skript#1383]
TuSKe throws this error on dev37, no problem on dev36

```md
#!#! 
#!#! [Skript] Severe Error:
#!#! 
#!#! Something went horribly wrong with Skript.
#!#! This issue is NOT your fault! You probably can't fix it yourself, either.
#!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
#!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
#!#! Other versions might work, but since you're getting this error message something is NOT working,
#!#! nor it will work, unless you switch to supported platform.
#!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
#!#! 
#!#! Stack trace:
#!#! java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.WeakHashMap
#!#!     at com.github.tukenuke.tuske.util.VariableUtil.<init>(VariableUtil.java:24)
#!#!     at com.github.tukenuke.tuske.util.VariableUtil.getInstance(VariableUtil.java:17)
#!#!     at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.execute(EffFormatGUI.java:141)
#!#!     at com.github.tukenuke.tuske.util.EffectSection.check(EffectSection.java:54)
#!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
#!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:52)
#!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
#!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:109)
#!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
#!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
#!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
#!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
#!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
#!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
#!#!     at java.lang.Thread.run(Unknown Source)
#!#! 
#!#! Version Information:
#!#!   Skript: 2.2-dev37 (latest)
#!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
#!#!   Minecraft: 1.8.8
#!#!   Java: 1.8.0_171 (Java HotSpot(TM) 64-Bit Server VM 25.171-b11)
#!#!   OS: Windows Server 2012 R2 amd64 6.3
#!#! 
#!#! Server platform: Paper
#!#!
```

**Comment by Nicofisi** [comment]
Looks like TuSKe needs to be updated, sorry!

**Comment by bensku** [comment]
Solution for TuSKe developer would be to cast to Map instead of HashMap. Both WeakHashMap and HashMap implement it.
