### ISSUE TITLE
Minecraft 1.13 Skript Error

### ISSUE THREAD

**Issue by QuapiL1** [SkriptLang/Skript#1409]
#1398 

On start of a 1.13 Minecraft Server it gives me this error:
(Gave me the same on Spigot and Paper)

[00:57:15 ERROR]: #!#! Stack trace:
[00:57:15 ERROR]: #!#! java.lang.NoSuchMethodError: org.bukkit.Effect.getName()Ljava/lang/String;
[00:57:15 ERROR]: #!#!     at ch.njol.skript.util.VisualEffect$Type.<init>(VisualEffect.java:197)
[00:57:15 ERROR]: #!#!     at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:64)
[00:57:15 ERROR]: #!#!     at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:270)
[00:57:15 ERROR]: #!#!     at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:891)
[00:57:15 ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:324)
[00:57:15 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:57:15 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[00:57:15 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[00:57:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:431)
[00:57:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:345)
[00:57:15 ERROR]: #!#!     at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:589)
[00:57:15 ERROR]: #!#!     at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:551)
[00:57:15 ERROR]: #!#!     at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:428)
[00:57:15 ERROR]: #!#!     at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:305)
[00:57:15 ERROR]: #!#!     at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764)
[00:57:15 ERROR]: #!#!     at java.base/java.lang.Thread.run(Unknown Source)

**Comment by TheBentoBox** [comment]
We don't support 1.13 yet. #1395.
