### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by fuxwa** [SkriptLang/Skript#1427]
what's wrong with it?
[22:17:53] [Skript variable save thread/ERROR]: #!#! [Skript] Severe Error:
[22:17:53] [Skript variable save thread/ERROR]: #!#! Exception in thread Skript variable save thread
[22:17:53] [Skript variable save thread/ERROR]: #!#! 
[22:17:53] [Skript variable save thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[22:17:53] [Skript variable save thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[22:17:53] [Skript variable save thread/ERROR]: #!#! and check whether this error has already been reported.
[22:17:53] [Skript variable save thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[22:17:53] [Skript variable save thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[22:17:53] [Skript variable save thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[22:17:53] [Skript variable save thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[22:17:53] [Skript variable save thread/ERROR]: #!#! 
[22:17:53] [Skript variable save thread/ERROR]: #!#! Stack trace:
[22:17:53] [Skript variable save thread/ERROR]: #!#! java.util.ConcurrentModificationException
[22:17:53] [Skript variable save thread/ERROR]: #!#! at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
[22:17:53] [Skript variable save thread/ERROR]: #!#! at java.util.LinkedList$ListItr.next(Unknown Source)
[22:17:53] [Skript variable save thread/ERROR]: #!#! at ch.njol.skript.log.SkriptLogger.log(SkriptLogger.java:172)
[22:17:53] [Skript variable save thread/ERROR]: #!#! at ch.njol.skript.log.SkriptLogger.log(SkriptLogger.java:164)
[22:17:53] [Skript variable save thread/ERROR]: #!#! at ch.njol.skript.Skript.warning(Skript.java:1176)
[22:17:53] [Skript variable save thread/ERROR]: #!#! at ch.njol.skript.variables.VariablesStorage.save(VariablesStorage.java:248)
[22:17:53] [Skript variable save thread/ERROR]: #!#! at ch.njol.skript.variables.Variables$2.run(Variables.java:456)
[22:17:53] [Skript variable save thread/ERROR]: #!#! at java.lang.Thread.run(Unknown Source)
[22:17:53] [Skript variable save thread/ERROR]: #!#! 
[22:17:53] [Skript variable save thread/ERROR]: #!#! Version Information:
[22:17:53] [Skript variable save thread/ERROR]: #!#! Skript: 2.2-dev29
[22:17:53] [Skript variable save thread/ERROR]: #!#! Bukkit: 1.12-R0.1-SNAPSHOT
[22:17:53] [Skript variable save thread/ERROR]: #!#! Minecraft: 1.12
[22:17:53] [Skript variable save thread/ERROR]: #!#! Java: 1.8.0_181 (Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
[22:17:53] [Skript variable save thread/ERROR]: #!#! OS: Windows Server 2008 R2 amd64 6.1
[22:17:53] [Skript variable save thread/ERROR]: #!#! 
[22:17:53] [Skript variable save thread/ERROR]: #!#! Running CraftBukkit: false
[22:17:53] [Skript variable save thread/ERROR]: #!#! 
[22:17:53] [Skript variable save thread/ERROR]: #!#! Current node: set {_uuid} to "%uuid of {_Player}%" (SUPERGUILDS_main.sk, line 4)
[22:17:53] [Skript variable save thread/ERROR]: #!#! Current item: null
[22:17:53] [Skript variable save thread/ERROR]: #!#! 
[22:17:53] [Skript variable save thread/ERROR]: #!#! Thread: Skript variable save thread
[22:17:53] [Skript variable save thread/ERROR]: #!#! 
[22:17:53] [Skript variable save thread/ERROR]: #!#! End of Error.

**Comment by TheBentoBox** [comment]
You're not using the latest version of Skript. We only accept bug reports from people using the latest version, which can be found [here](https://github.com/SkriptLang/Skript/releases).
