### ISSUE TITLE
CRITICAL: Problem saving variables

### ISSUE THREAD

**Issue by GermanMinerDE** [SkriptLang/Skript#1435]
Hey guys,

I have an issue with literally no error code or something I can show you.
We are a big server with approx. 400 different users per day and have an issue since yesterday, that seems not to be fixed by us.

After starting the server, the variables are loaded and it can be written fine. After some hours of playing and saving, the server makes 2 daily restarts for performance and safety (ex.: saving the data) - now the problem is, that the servers is hanging up on server stop with "Disabling Skript...", which takes minutes, hours, the whole day. Simply: It does not stop.

The real bigger problem with that is, that the server stops saving the variables at some time and does not save then (not in MySQL and not in SQLLite, tested both.) and after I kill the process, all data is wasted.

There are no "cannot write..." or "at sufficient speed" messages in the console (but turned on in the config).

Are there some recommendation how to prevent it?

Using Spigot 1.12.2
Skript Bensku dev33

Is there a newer version of Skript, where such things might be fixed? I didn't found something in the release notes and don't want to test all the used addons and possibly all programmed functions for nothing at the end.

Here is the config:

databases:
        
   
    
    MS_SKRIPT_9:
        type: MySQL
        pattern: backpack\..*
        
        host: localhost
        port: 3306
        user: -------------
        password: -------------
        database: MS_SKRIPT_1
        table: Rucksack
        
        monitor changes: false
        monitor interval: 180 seconds
        
    MS_SKRIPT_8:
        type: MySQL
        pattern: sicherungen\..*
        
        host: localhost
        port: 3306
        user: -------------
        password: -------------
        database: MS_SKRIPT_1
        table: Sicherungen
        
        monitor changes: false
        monitor interval: 180 seconds
        
        
    MS_SKRIPT_7:
        type: MySQL
        pattern: (gmcar::.*|gmcar\..*|fahrzeuge\..*|car\..*|nospeedinfo\..*|fuehrerschein\..*|blitzer\..*|mietcars::.*|tankstelle\..*|autohaus\..*)
        
        host: localhost
        port: 3306
        user: -------------
        password: -------------
        database: MS_SKRIPT_1
        table: Fahrzeuge_Verkehr
        
        monitor changes: false
        monitor interval: 180 seconds
        
        
    MS_SKRIPT_6:
        type: MySQL
        pattern: (onTime\..*|ontime\..*|voteevent\..*|rewards\..*|novotewerbung\..*)
        
        host: localhost
        port: 3306
        user: -------------
        password: -------------
        database: MS_SKRIPT_1
        table: OnTime
        
        monitor changes: false
        monitor interval: 180 seconds
        
        
    MS_SKRIPT_5:
        type: MySQL
        pattern: (firmen::.*|firma\..*|kontoauszug\..*|firmen\..*|biz\..*)
        
        host: localhost
        port: 3306
        user: -------------
        password: -------------
        database: MS_SKRIPT_1
        table: FirmaBIZ
        
        monitor changes: false
        monitor interval: 180 seconds
        
        
    MS_SKRIPT_4:
        type: MySQL
        pattern: bsystem\.konto::.*?::auszug::.*
        
        host: localhost
        port: 3306
        user: -------------
        password: -------------
        database: MS_SKRIPT_1
        table: BankSystem_Auszuege
        
        monitor changes: false
        monitor interval: 180 seconds
    
    
    MS_SKRIPT_3:
        type: MySQL
        pattern: (bsystem::.*|bsystem\..*)
        
        host: localhost
        port: 3306
        user: -------------
        password: -------------
        database: MS_SKRIPT_1
        table: BankSystem
        
        monitor changes: false
        monitor interval: 180 seconds
        
        
    MS_SKRIPT_2:
        type: MySQL
        pattern: headdatabase\..*
        
        host: localhost
        port: 3306
        user: -------------
        password: -------------
        database: MS_SKRIPT_1
        table: HeadDatabase
        
        monitor changes: false
        monitor interval: 180 seconds
        
        
        
    MS_SKRIPT_1:
        type: MySQL
        pattern: (?!-).*
        
        host: localhost
        port: 3306
        user: -------------
        password: -------------
        database: MS_SKRIPT_1
        table: Restdaten
        
        monitor changes: false
        monitor interval: 180 seconds

**Comment by GermanMinerDE** [comment]
I've found an error that occurs, when one of my SQLLite-DBs (I used them before I tested MySQL today) stops saving:


[20:09:36] [Skript variable save thread/ERROR]: #!#! 
[20:09:36] [Skript variable save thread/ERROR]: #!#! [Skript] Severe Error:
[20:09:36] [Skript variable save thread/ERROR]: #!#! Exception in thread Skript variable save thread
[20:09:36] [Skript variable save thread/ERROR]: #!#! 
[20:09:36] [Skript variable save thread/ERROR]: #!#! Something went horribly wrong with Skript.
[20:09:36] [Skript variable save thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:09:36] [Skript variable save thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:09:36] [Skript variable save thread/ERROR]: #!#! Here is full list of them:
[20:09:36] [Skript variable save thread/ERROR]: #!#! skRayFall (http://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) SkAction GMAddon (www.GermanMiner.de) WolvSK MundoSK (https://forums.skunity.com/resources/mundosk.69/) Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) SkUniversal SharpSK ExertSK skript-mirror skDragon SkStuff skUtilities (https://tim740.github.io/) ExtrasSK SkQuery Ersatz Umbaska PirateSK 
[20:09:36] [Skript variable save thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:09:36] [Skript variable save thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:09:36] [Skript variable save thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:09:36] [Skript variable save thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:09:36] [Skript variable save thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:09:36] [Skript variable save thread/ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[20:09:36] [Skript variable save thread/ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[20:09:36] [Skript variable save thread/ERROR]: #!#! 
[20:09:36] [Skript variable save thread/ERROR]: #!#! Stack trace:
[20:09:36] [Skript variable save thread/ERROR]: #!#! java.lang.NullPointerException
[20:09:36] [Skript variable save thread/ERROR]: #!#!     at ch.njol.skript.log.SkriptLogger.log(SkriptLogger.java:173)
[20:09:36] [Skript variable save thread/ERROR]: #!#!     at ch.njol.skript.log.SkriptLogger.log(SkriptLogger.java:164)
[20:09:36] [Skript variable save thread/ERROR]: #!#!     at ch.njol.skript.Skript.warning(Skript.java:1190)
[20:09:36] [Skript variable save thread/ERROR]: #!#!     at ch.njol.skript.variables.VariablesStorage.save(VariablesStorage.java:248)
[20:09:36] [Skript variable save thread/ERROR]: #!#!     at ch.njol.skript.variables.Variables$2.run(Variables.java:467)
[20:09:36] [Skript variable save thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[20:09:36] [Skript variable save thread/ERROR]: #!#! 
[20:09:36] [Skript variable save thread/ERROR]: #!#! Version Information:
[20:09:36] [Skript variable save thread/ERROR]: #!#!   Skript: 2.2-dev33
[20:09:36] [Skript variable save thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[20:09:36] [Skript variable save thread/ERROR]: #!#!   Minecraft: 1.12.2
[20:09:36] [Skript variable save thread/ERROR]: #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
[20:09:36] [Skript variable save thread/ERROR]: #!#!   OS: Windows Server 2016 amd64 10.0
[20:09:36] [Skript variable save thread/ERROR]: #!#! 
[20:09:36] [Skript variable save thread/ERROR]: #!#! Running CraftBukkit: false
[20:09:36] [Skript variable save thread/ERROR]: #!#! Running Spigot (or compatible): true
[20:09:36] [Skript variable save thread/ERROR]: #!#! Running Paper (or compatible): false
[20:09:36] [Skript variable save thread/ERROR]: #!#! 
[20:09:36] [Skript variable save thread/ERROR]: #!#! Current node: null
[20:09:36] [Skript variable save thread/ERROR]: #!#! Current item: null
[20:09:36] [Skript variable save thread/ERROR]: #!#! Thread: Skript variable save thread
[20:09:36] [Skript variable save thread/ERROR]: #!#! 
[20:09:36] [Skript variable save thread/ERROR]: #!#! Language: english
[20:09:36] [Skript variable save thread/ERROR]: #!#! Link parse mode: STRICT
[20:09:36] [Skript variable save thread/ERROR]: #!#! 
[20:09:36] [Skript variable save thread/ERROR]: #!#! End of Error.
[20:09:36] [Skript variable save thread/ERROR]: #!#!

**Comment by Nicofisi** [comment]
The MySQL support in Skript has been horribly broken for a long time - please don't use it at all for now

**Comment by GermanMinerDE** [comment]
Hey @Nicofisi - I read about that.
For me it works after intensive testing on another machine.

But the problem is THE SAME with SQLLite! The files stop changing after the error came in the console and on restart it's hanging up. I only tested out MySQL because of the problem mit SQLLite.

**Comment by AlexLew95** [comment]
before reporting a bug, remember to update your skript version, some bugs may have been fixed between your version and the last one ;)

**Comment by GermanMinerDE** [comment]
I will test it with a newer version - but I think it'll happen again.

**Comment by GermanMinerDE** [comment]
Hey, I think, it won't help. Otherwise I can't start with a newer version Skript, because it simply hangs up loading a specific script without any errors (and don't does it with my actual version).

But again, here is the error again, after this appeared in the console, the server stopped saving variables. It happens at a random time, does not matter if it's MySQL oder SQL Lite.


[14:40:49] [Server thread/INFO]: Given Blindness (ID 15) * 0 to DasArvid for 4 seconds
[14:40:49] [Server thread/INFO]: TheNeonFighter issued server command: /h
[14:40:49] [Server thread/INFO]: TheNeonFighter [b583bb83-36f6-4bc9-8f93-21008fb22609]: /h
[14:40:50] [Server thread/INFO]: Nessi192 [a079bb9e-9847-4b2f-b11b-eaae12dc735c]: /f  hat er das so gemacht oder du?
[14:40:50] [Skript variable save thread/ERROR]: #!#! 
[14:40:50] [Skript variable save thread/ERROR]: #!#! [Skript] Severe Error:
[14:40:50] [Skript variable save thread/ERROR]: #!#! Exception in thread Skript variable save thread
[14:40:50] [Skript variable save thread/ERROR]: #!#! 
[14:40:50] [Skript variable save thread/ERROR]: #!#! Something went horribly wrong with Skript.
[14:40:50] [Skript variable save thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:40:50] [Skript variable save thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[14:40:50] [Skript variable save thread/ERROR]: #!#! Here is full list of them:
[14:40:50] [Skript variable save thread/ERROR]: #!#! skRayFall (http://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) SkAction GMAddon (www.GermanMiner.de) WolvSK MundoSK (https://forums.skunity.com/resources/mundosk.69/) Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) SkUniversal SharpSK ExertSK skript-mirror skDragon SkStuff skUtilities (https://tim740.github.io/) ExtrasSK SkQuery Ersatz Umbaska PirateSK 
[14:40:50] [Skript variable save thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[14:40:50] [Skript variable save thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[14:40:50] [Skript variable save thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[14:40:50] [Skript variable save thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[14:40:50] [Skript variable save thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[14:40:50] [Skript variable save thread/ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[14:40:50] [Skript variable save thread/ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[14:40:50] [Skript variable save thread/ERROR]: #!#! 
[14:40:50] [Skript variable save thread/ERROR]: #!#! Stack trace:
[14:40:50] [Skript variable save thread/ERROR]: #!#!   warning: no/empty exception given, dumping current stack trace instead
[14:40:50] [Skript variable save thread/ERROR]: #!#! java.lang.Exception: java.lang.NullPointerException
[14:40:50] [Skript variable save thread/ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1353)
[14:40:50] [Skript variable save thread/ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1226)
[14:40:50] [Skript variable save thread/ERROR]: #!#!     at ch.njol.skript.Skript$1.uncaughtException(Skript.java:899)
[14:40:50] [Skript variable save thread/ERROR]: #!#!     at java.lang.Thread.dispatchUncaughtException(Thread.java:1959)
[14:40:50] [Skript variable save thread/ERROR]: #!#! Caused by: java.lang.NullPointerException
[14:40:50] [Skript variable save thread/ERROR]: #!#! 
[14:40:50] [Skript variable save thread/ERROR]: #!#! Version Information:
[14:40:50] [Skript variable save thread/ERROR]: #!#!   Skript: 2.2-dev33
[14:40:50] [Skript variable save thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[14:40:50] [Skript variable save thread/ERROR]: #!#!   Minecraft: 1.12.2
[14:40:50] [Skript variable save thread/ERROR]: #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
[14:40:50] [Skript variable save thread/ERROR]: #!#!   OS: Windows Server 2016 amd64 10.0
[14:40:50] [Skript variable save thread/ERROR]: #!#! 
[14:40:50] [Skript variable save thread/ERROR]: #!#! Running CraftBukkit: false
[14:40:50] [Skript variable save thread/ERROR]: #!#! Running Spigot (or compatible): true
[14:40:50] [Skript variable save thread/ERROR]: #!#! Running Paper (or compatible): false
[14:40:50] [Skript variable save thread/ERROR]: #!#! 
[14:40:50] [Skript variable save thread/ERROR]: #!#! Current node: null
[14:40:50] [Skript variable save thread/ERROR]: #!#! Current item: null
[14:40:50] [Skript variable save thread/ERROR]: #!#! Thread: Skript variable save thread
[14:40:50] [Skript variable save thread/ERROR]: #!#! 
[14:40:50] [Skript variable save thread/ERROR]: #!#! Language: english
[14:40:50] [Skript variable save thread/ERROR]: #!#! Link parse mode: STRICT
[14:40:50] [Skript variable save thread/ERROR]: #!#! 
[14:40:50] [Skript variable save thread/ERROR]: #!#! End of Error.
[14:40:50] [Skript variable save thread/ERROR]: #!#!

**Comment by bensku** [comment]
Please follow instructions given in the message and try if this occurs without addons.

**Comment by GermanMinerDE** [comment]
Hi @bensku ,

think it is not possible to test on a big server. Without the addons server won't be useable...
And on a test machine with no-one online - I think - it wouldn't happen.

We were in a beta phase for more than 1 year with approx. 5-10 users and never this error occurred with all the addons being there (but not so much players).


I don't want to be selfish, but I am little bit "limited" testing this.

**Comment by GermanMinerDE** [comment]
Hey again @bensku ,

can you tell me, what might be better:
- Put all variables in one database table OR
- Split them in multiple with the pattern ?

approx. 500k variables

**Comment by bensku** [comment]
I'm not sure which is better, honestly. In any case, I do not recommend using MySQL or SQLite databases for now. They are not entirely stable. Besides that... 500k variables is a *lot* for Skript's current variable system. It might slow things down quite a lot.

That should not cause anything like the issue you are experiencing, though. The first error you posted seems to indicate that something has added <code>null</code> as a log handler. That something might be one of your addons. Right now, with 1.13 update in progress, I sadly do not have time to investigate any further.

**Comment by Nicofisi** [comment]
>The first error you posted seems to indicate that something has added null as a log handler. That something might be one of your addons. 

Yep, that must be an addon, since Skript doesn't even add variables anywhere as handlers, it only ever directly does `SkriptLogger.startLogHandler(new Something())`, and that's the only method that adds handlers to the handler list:
![image](https://user-images.githubusercontent.com/12614053/43662385-0dda326c-9766-11e8-9667-a46f664178c0.png)

...unless of course in Skript 2.2-dev33 something else was at this line

**Comment by GermanMinerDE** [comment]
@Nicofisi Hey,

yeah I got some of "log handlers"-messages in the console:

`[23:30:13] [Server thread/ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:169)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]`

Can you explain in short, what an "Log Handler" means?
Is there a better method to figure out, where this comes from except disabling every Add-on?

P.S.: The Log Handler messages were there before for months, but the error occurred only now.
