### ISSUE TITLE
VariableStorage issue while disabling

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#1442]
```
[17:28:04] [Server thread/ERROR]: Error occurred while disabling Skript v2.2-dev37c (Is it up to date?)
java.lang.NoClassDefFoundError: ch/njol/skript/util/FileUtils
	at ch.njol.skript.variables.FlatFileStorage.saveVariables(FlatFileStorage.java:390) ~[?:?]
	at ch.njol.skript.variables.FlatFileStorage.close(FlatFileStorage.java:341) ~[?:?]
	at ch.njol.skript.Skript.onDisable(Skript.java:817) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:349) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:465) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at org.spigotmc.RestartCommand.restart(RestartCommand.java:81) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at org.spigotmc.RestartCommand.restart(RestartCommand.java:40) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:758) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.ClassNotFoundException: ch.njol.skript.util.FileUtils
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
	... 17 more
```
Skript version: dev-37c
Spigot: 1.12.2 (Last known 1.12.2)
Cause: just restarting.

**Comment by Nicofisi** [comment]
Two most likely possible causes:
* you didn't 100% copy the jar with Skript, some parts of it are missing
* you changed Skript's jar file while the server was running (probably this one)

The other cause could be that the release jar is broken which I highly disbelieve since you're the only person reporting this issue, and if it was then it would occur every time for everyone

**Comment by bensku** [comment]
It *could* also be some arcane classloading issue. Not very likely, though.
