### ISSUE TITLE
Error with skript

### ISSUE THREAD

**Issue by iPrah** [SkriptLang/Skript#1462]
I have this problem with skript 2.2 dev37c on spigot 1.12.2 with no addons
```
[02:01:48 ERROR]: #!#!
[02:01:48 ERROR]: #!#! [Skript] Severe Error:
[02:01:48 ERROR]: #!#! Could not load server.sk
[02:01:48 ERROR]: #!#!
[02:01:48 ERROR]: #!#! Something went horribly wrong with Skript.
[02:01:48 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[02:01:48 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[02:01:48 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[02:01:48 ERROR]: #!#!
[02:01:48 ERROR]: #!#! Stack trace:
[02:01:48 ERROR]: #!#! java.lang.NullPointerException
[02:01:48 ERROR]: #!#!     at ch.njol.skript.bukkitutil.BiomeMappings.parse(BiomeMappings.java:44)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.util.BiomeUtils.parse(BiomeUtils.java:36)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.classes.data.BukkitClasses$20.parse(BukkitClasses.java:1015)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.classes.data.BukkitClasses$20.parse(BukkitClasses.java:1)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:422)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:451)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:95)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:84)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:179)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:130)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:253)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:81)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1052)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:496)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:623)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:391)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:403)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:436)
[02:01:48 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:181)
[02:01:48 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[02:01:48 ERROR]: #!#!     at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95)
[02:01:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[02:01:48 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[02:01:48 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[02:01:48 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[02:01:48 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[02:01:48 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[02:01:48 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[02:01:48 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[02:01:48 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[02:01:48 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[02:01:48 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[02:01:48 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[02:01:48 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[02:01:48 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[02:01:48 ERROR]: #!#!
[02:01:48 ERROR]: #!#! Version Information:
[02:01:48 ERROR]: #!#!   Skript: 2.2-dev37c (latest)
[02:01:48 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[02:01:48 ERROR]: #!#!   Minecraft: 1.12.2
[02:01:48 ERROR]: #!#!   Java: 1.8.0_181 (Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
[02:01:48 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[02:01:48 ERROR]: #!#!
[02:01:48 ERROR]: #!#! Server platform: Spigot
[02:01:48 ERROR]: #!#!
[02:01:48 ERROR]: #!#! Current node: if arg-1 is not set: (server.sk, line 6)
[02:01:48 ERROR]: #!#! Current item: null
[02:01:48 ERROR]: #!#!
[02:01:48 ERROR]: #!#! Thread: Server thread
[02:01:48 ERROR]: #!#!
[02:01:48 ERROR]: #!#! Language: english
[02:01:48 ERROR]: #!#! Link parse mode: DISABLED
[02:01:48 ERROR]: #!#!
[02:01:48 ERROR]: #!#! End of Error.
[02:01:48 ERROR]: #!#!
```

**Comment by jaylawl** [comment]
Your error mentions:
```
[02:01:48 ERROR]: #!#! [Skript] Severe Error:
[02:01:48 ERROR]: #!#! Could not load server.sk
```
Please also post the file "server.sk"

**Comment by bensku** [comment]
Could be a corrupted Skript jar or other plugins interfering with classloading. Please try downloading latest release again and if it doesn't work, disabling other plugins.

**Comment by supertassu** [comment]
> other plugins interfering with classloading. 

```
at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95)
```

**Comment by Snow-Pyon** [comment]
PerWorldPlugins is known to not be compatible with Skript (for whatever reason, I personally don't know the methods it uses to allow world-specific plugins).
