### ISSUE TITLE
Skript ExprOffTool error

### ISSUE THREAD

**Issue by Duetro** [SkriptLang/Skript#1470]
Hey, could someone help me with this error?

Code:
```
on place:
    if name of (player's tool) is "&b&lKopierer":
        set {_kopierer} to true
        set {_item} to player's tool
    else if name of (player's offhand tool) is "&b&lKopierer":
        set {_kopierer} to true
        set {_item} to player's offhand tool

... 
```

Error:
```
[18:22:33] [Server thread/ERROR]: #!#! 
[18:22:33] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[18:22:33] [Server thread/ERROR]: #!#! 
[18:22:33] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[18:22:33] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[18:22:33] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[18:22:33] [Server thread/ERROR]: #!#! Here is full list of them:
[18:22:33] [Server thread/ERROR]: #!#! skRayFall (http://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) SkAction MundoSK (https://forums.skunity.com/resources/mundosk.69/) Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) SkUniversal SharpSK ExertSK WebAddon skript-mirror skDragon SkStuff skUtilities (https://tim740.github.io/) ExtrasSK SkQuery Umbaska 
[18:22:33] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[18:22:33] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[18:22:33] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[18:22:33] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[18:22:33] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[18:22:33] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[18:22:33] [Server thread/ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[18:22:33] [Server thread/ERROR]: #!#! 
[18:22:33] [Server thread/ERROR]: #!#! Stack trace:
[18:22:33] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.log.SkriptLogger.log(SkriptLogger.java:173)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.log.SkriptLogger.log(SkriptLogger.java:164)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.info(Skript.java:1211)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprOffTool$1.get(ExprOffTool.java:71)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprOffTool$1.get(ExprOffTool.java:1)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.Getter.convert(Getter.java:50)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:342)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:333)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:104)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprOffTool.get(ExprOffTool.java:60)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprTool.get(ExprTool.java:1)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:161)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:258)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:52)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[18:22:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110)
[18:22:33] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:22:33] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[18:22:33] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[18:22:33] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:186)
[18:22:33] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerBucketEmptyEvent(CraftEventFactory.java:159)
[18:22:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.ItemBucket.a(ItemBucket.java:130)
[18:22:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.ItemBucket.a(ItemBucket.java:76)
[18:22:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.ItemStack.a(ItemStack.java:293)
[18:22:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:403)
[18:22:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1004)
[18:22:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
[18:22:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
[18:22:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[18:22:33] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:22:33] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:22:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[18:22:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[18:22:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[18:22:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[18:22:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[18:22:33] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[18:22:33] [Server thread/ERROR]: #!#! 
[18:22:33] [Server thread/ERROR]: #!#! Version Information:
[18:22:33] [Server thread/ERROR]: #!#!   Skript: 2.2-dev37c
[18:22:33] [Server thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[18:22:33] [Server thread/ERROR]: #!#!   Minecraft: 1.12.2
[18:22:33] [Server thread/ERROR]: #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
[18:22:33] [Server thread/ERROR]: #!#!   OS: Windows Server 2016 amd64 10.0
[18:22:33] [Server thread/ERROR]: #!#! 
[18:22:33] [Server thread/ERROR]: #!#! Server platform: Spigot
[18:22:33] [Server thread/ERROR]: #!#! 
[18:22:33] [Server thread/ERROR]: #!#! Current node: null
[18:22:33] [Server thread/ERROR]: #!#! Current item: the name of the tool of the player is equal to "§b§lKopierer" (comparator: ch.njol.skript.classes.data.DefaultComparators$15@2194d5a4)
[18:22:33] [Server thread/ERROR]: #!#! Current trigger: place (break/place/burn/fade/form of <none>) (kopierer.sk, line 167)
[18:22:33] [Server thread/ERROR]: #!#! 
[18:22:33] [Server thread/ERROR]: #!#! Thread: Server thread
[18:22:33] [Server thread/ERROR]: #!#! 
[18:22:33] [Server thread/ERROR]: #!#! Language: english
[18:22:33] [Server thread/ERROR]: #!#! Link parse mode: STRICT
[18:22:33] [Server thread/ERROR]: #!#! 
[18:22:33] [Server thread/ERROR]: #!#! End of Error.
[18:22:33] [Server thread/ERROR]: #!#! 
```

**Comment by Nicofisi** [comment]
Looks like @bensku left some debug lines here.. 2 years ago. No idea how it became unnoticed for that long :eyes: 
https://github.com/SkriptLang/Skript/blob/098ec9c45050b831234e2c624c2d1c818d3a2889/src/main/java/ch/njol/skript/expressions/ExprOffTool.java#L71

Not sure about the exception though

**Comment by Blueyescat** [comment]
@Duetro The code works fine for me using Paper 1.12.2 and Skript 2.2-dev37c.

**Comment by TheBentoBox** [comment]
Can anyone else confirm this?
