### ISSUE TITLE
I'm not entirely sure what it is...

### ISSUE THREAD

**Issue by mpschorr** [SkriptLang/Skript#1501]
[16:24:24 ERROR]: #!#! 
[16:24:24 ERROR]: #!#! [Skript] Severe Error:
[16:24:24 ERROR]: #!#! 
[16:24:24 ERROR]: #!#! Something went horribly wrong with Skript.
[16:24:24 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:24:24 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[16:24:24 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[16:24:24 ERROR]: #!#! 
[16:24:24 ERROR]: #!#! Stack trace:
[16:24:24 ERROR]: #!#! java.lang.NoSuchMethodError: org.bukkit.Effect.getName()Ljava/lang/String;
[16:24:24 ERROR]: #!#!     at ch.njol.skript.util.VisualEffect$Type.<init>(VisualEffect.java:197)
[16:24:24 ERROR]: #!#!     at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:64)
[16:24:24 ERROR]: #!#!     at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:270)
[16:24:24 ERROR]: #!#!     at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:891)
[16:24:24 ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:324)
[16:24:24 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:24:24 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[16:24:24 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[16:24:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:427)
[16:24:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:341)
[16:24:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:800)
[16:24:24 ERROR]: #!#!     at org.bukkit.Bukkit.reload(Bukkit.java:528)
[16:24:24 ERROR]: #!#!     at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[16:24:24 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:24:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:695)
[16:24:24 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1644)
[16:24:24 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1479)
[16:24:24 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:24:24 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[16:24:24 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[16:24:24 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:24:24 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:24:24 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[16:24:24 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[16:24:24 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411)
[16:24:24 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[16:24:24 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[16:24:24 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[16:24:24 ERROR]: #!#! 
[16:24:24 ERROR]: #!#! Version Information:
[16:24:24 ERROR]: #!#!   Skript: 2.2-dev37c
[16:24:24 ERROR]: #!#!   Bukkit: 1.13.1-R0.1-SNAPSHOT
[16:24:24 ERROR]: #!#!   Minecraft: 1.13.1
[16:24:24 ERROR]: #!#!   Java: 1.8.0_172 (Java HotSpot(TM) 64-Bit Server VM 25.172-b11)
[16:24:24 ERROR]: #!#!   OS: Linux amd64 4.15.0-30-generic
[16:24:24 ERROR]: #!#! 
[16:24:24 ERROR]: #!#! Server platform: Spigot
[16:24:24 ERROR]: #!#! 
[16:24:24 ERROR]: #!#! Current node: null
[16:24:24 ERROR]: #!#! Current item: null
[16:24:24 ERROR]: #!#! 
[16:24:24 ERROR]: #!#! Thread: Server thread
[16:24:24 ERROR]: #!#! 
[16:24:24 ERROR]: #!#! Language: english
[16:24:24 ERROR]: #!#! Link parse mode: DISABLED
[16:24:24 ERROR]: #!#! 
[16:24:24 ERROR]: #!#! End of Error.
[16:24:24 ERROR]: #!#!

**Comment by mpschorr** [comment]
This happened while reloading my server

**Comment by Nicofisi** [comment]
We don't support 1.13 yet - #1395

**Comment by ShaneBeee** [comment]
@mpschorr Skript also doesn't support /reload
