### ISSUE TITLE
! [Skript] Severe Error java.lang.ArrayIndexOutOfBoundsException: 51452

### ISSUE THREAD

**Issue by mckite** [SkriptLang/Skript#1534]
[11:41:50 ERROR]: #!#!
[11:41:50 ERROR]: #!#! [Skript] Severe Error:
[11:41:50 ERROR]: #!#!
[11:41:50 ERROR]: #!#! Something went horribly wrong with Skript.
[11:41:50 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:41:50 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[11:41:50 ERROR]: #!#! Here is full list of them:
[11:41:50 ERROR]: #!#! skRayFall (http://sk.rayfall.net/) InvSK GomSK SkQuery Skellett (https://forums.skunity.com/resou
rces/skellett-the-addon-with-a-beast-name.24/) WildSkript (http://www.dzikoysk.net/)
[11:41:50 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[11:41:50 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[11:41:50 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript iss
ue.
[11:41:50 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[11:41:50 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of tha
t plugin.
[11:41:50 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[11:41:50 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[11:41:50 ERROR]: #!#!
[11:41:50 ERROR]: #!#! Stack trace:
[11:41:50 ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: 51452
[11:41:50 ERROR]: #!#!     at ch.njol.skript.util.chat.ChatMessages.parse(ChatMessages.java:283)
[11:41:50 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getMessageComponents(VariableString.java:498)
[11:41:50 ERROR]: #!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:87)
[11:41:50 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[11:41:50 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[11:41:50 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[11:41:50 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[11:41:50 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:294)
[11:41:50 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[11:41:50 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:257)
[11:41:50 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:172)
[11:41:50 ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor381.invoke(Unknown Source)
[11:41:50 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:41:50 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[11:41:50 ERROR]: #!#!     at com.massivecraft.massivelag.inject.MassiveLagEventExecutor.execute(MassiveLagEventExecutor
.java:69)
[11:41:50 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[11:41:50 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[11:41:50 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[11:41:50 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389)
[11:41:50 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[11:41:50 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11:41:50 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[11:41:50 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[11:41:50 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[11:41:50 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[11:41:50 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[11:41:50 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[11:41:50 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[11:41:50 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[11:41:50 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[11:41:50 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[11:41:50 ERROR]: #!#!
[11:41:50 ERROR]: #!#! Version Information:
[11:41:50 ERROR]: #!#!   Skript: 2.2-dev37c
[11:41:50 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[11:41:50 ERROR]: #!#!   Minecraft: 1.12.2
[11:41:50 ERROR]: #!#!   Java: 1.8.0_181 (Java HotSpot(TM) 64-Bit Server VM 25.181-b13)

[11:41:50 ERROR]: #!#!
[11:41:50 ERROR]: #!#! Server platform: Spigot
[11:41:50 ERROR]: #!#!
[11:41:50 ERROR]: #!#! Current node: null
[11:41:50 ERROR]: #!#! Current item: send "§f[§4경고§f] &주제를 입력해 주십시오." to event-player/console
[11:41:50 ERROR]: #!#! Current trigger: command /퀴즈 (simple event) (퀴즈.sk, line -1)
[11:41:50 ERROR]: #!#!
[11:41:50 ERROR]: #!#! Thread: Server thread
[11:41:50 ERROR]: #!#!
[11:41:50 ERROR]: #!#! Language: english
[11:41:50 ERROR]: #!#! Link parse mode: DISABLED
[11:41:50 ERROR]: #!#!
[11:41:50 ERROR]: #!#! End of Error.
[11:41:50 ERROR]: #!#!
[11:42:04 INFO]:
 I am using the skript 2.2dev 37c

Due to lastest 1.12 versio. Is not work on 1.12.2 ("Latest 1.12 version of Skript wants you to update to the version of Skript that doesnt support 1.12 #1523")

**Comment by bensku** [comment]
Probably Unicode support issue.

**Comment by Blueyescat** [comment]
As I tested any of these characters after a **`&`** causes  this.

**Comment by bensku** [comment]
Support for invalid color characters did not extend to Unicode. Was easy to fix, luckily.
