### ISSUE TITLE
Support for WorldGuard beta builds [1.13]

### ISSUE THREAD

**Issue by GiraffeCubed** [SkriptLang/Skript#1537]
**PaperSpigot**: 1.13.1, build 248
**Skript**: 2.3-alpha3
**Worldguard**: 7.0.0

Console gets spammed with these worldguard region errors whilst any player is online.
Error occurs without scripts, addons, or any other plugins (except FastAsyncWorldEdit, which is required)

[08:53:51] [Server thread/WARN]: [Skript] Task #106 for Skript v2.3-alpha3 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
	at ch.njol.skript.hooks.regions.WorldGuardHook.getRegionsAt_i(WorldGuardHook.java:250) ~[?:?]
	at ch.njol.skript.hooks.regions.RegionsPlugin.getRegionsAt(RegionsPlugin.java:92) ~[?:?]
	at ch.njol.skript.hooks.regions.expressions.ExprRegionsAt.get(ExprRegionsAt.java:83) ~[?:?]
	at ch.njol.skript.hooks.regions.expressions.ExprRegionsAt.get(ExprRegionsAt.java:1) ~[?:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[?:?]
	at ch.njol.skript.lang.VariableString.toString(VariableString.java:440) ~[?:?]
	at ch.njol.skript.lang.VariableString.getAll(VariableString.java:609) ~[?:?]
	at ch.njol.skript.lang.VariableString.check(VariableString.java:624) ~[?:?]
	at ch.njol.skript.conditions.CondContains.check(CondContains.java:101) ~[?:?]
	at ch.njol.skript.lang.Condition.run(Condition.java:56) ~[?:?]
	at ch.njol.skript.lang.Conditional.walk(Conditional.java:51) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:55) ~[?:?]
	at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:96) ~[?:?]
	at ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:110) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.1.jar:git-Paper-248]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.1.jar:git-Paper-248]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1004) ~[patched_1.13.1.jar:git-Paper-248]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428) ~[patched_1.13.1.jar:git-Paper-248]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.1.jar:git-Paper-248]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:838) ~[patched_1.13.1.jar:git-Paper-248]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]

**Comment by bensku** [comment]
Where did you get your WorldGuard? Only official BukkitDev versions are supported at the moment.

**Comment by Blueyescat** [comment]
Should be http://builds.enginehub.org/job/worldguard/last-successful?branch=master

These should be supported too for 1.13 but waiting a stable version should be better.

**Comment by GiraffeCubed** [comment]
I'm using the WorldGuard version directly from the FAWE website, just as Blueeyescat. https://empcraft.com/fawe/download/

It occurs with nothing on the server but FAWE and Worldguard from empcraft, and Skript without addons.

**Comment by bensku** [comment]
That is not official version, so Skript does not support it. Might add support at some point in future, but for now you *cannot* use these WorldGuard builds with Skript.

**Comment by DracarysPro** [comment]
A bukkitdev version got released. https://dev.bukkit.org/projects/worldguard/files/2621118

**Comment by DracarysPro** [comment]
A bukkitdev version got released. https://dev.bukkit.org/projects/worldguard/files/2621118

**Comment by TheBentoBox** [comment]
Going to move this up to high priority now that a 1.13 version of WG is properly released as a non-beta. There are numerous issues when using older versions of WorldGuard or WorldEdit on 1.13 so we really should support the updated working version ASAP.

**Comment by Drc-DEV** [comment]
They specified the changes in the API in this blog post, if it is of any help: https://blog.me4502.com/updating-worldguard-to-minecraft-113.html

**Comment by bensku** [comment]
WorldGuard 7 is not available in their Maven repository, or it is under some strange name. Building with Jitpack fails, because WorldEdit 7 is not available in said repo either.

@me4502 Sorry to bother you, but we kinda need the Maven builds for WorldGuard. Currently Skript supports only WorldGuard 6 or earlier, but those versions don't work well on 1.13. Skript does not currently have its own Maven repository (we just use Jitpack), so it is tricky to work with anything that is not a Maven artifact.

**Comment by me4502** [comment]
Yeah, a lot of people are really needing it. Currently nothing can be uploaded to the maven repo, so I need to get a copy of the current files from sk89q, host it myself, and then redirect DNS. I’ll send him a message to hopefully get the process started.

**Comment by bensku** [comment]
Thanks for fast response and good luck!

**Comment by Drc-DEV** [comment]
Any news on this?

**Comment by me4502** [comment]
The maven DNS has been migrated, so it's now correctly pointing at one with WG7/WE7
