### ISSUE TITLE
When try to set block above an air block places torch instead.

### ISSUE THREAD

**Issue by srtoys** [SkriptLang/Skript#1539]
Whenever you try to place a solid block above an air block where a non air block exists already
a torch is placed instead of the block and the following error is produced:

13:49:28] [Server thread/ERROR]: #!#! 
[13:49:28] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[13:49:28] [Server thread/ERROR]: #!#! 
[13:49:28] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[13:49:28] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:49:28] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[13:49:28] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[13:49:28] [Server thread/ERROR]: #!#! 
[13:49:28] [Server thread/ERROR]: #!#! Stack trace:
[13:49:28] [Server thread/ERROR]: #!#! java.lang.IllegalStateException: Could not convert enum class net.minecraft.server.v1_13_R2.EnumDirection->SELF
[13:49:28] [Server thread/ERROR]: #!#!     at com.google.common.base.Preconditions.checkState(Preconditions.java:721)
[13:49:28] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.block.data.CraftBlockData.toNMS(CraftBlockData.java:201)
[13:49:28] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.block.data.CraftBlockData.set(CraftBlockData.java:93)
[13:49:28] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.block.impl.CraftTorchWall.setFacing(CraftTorchWall.java:27)
[13:49:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.bukkitutil.block.NewBlockCompat$NewBlockSetter.setBlock(NewBlockCompat.java:139)
[13:49:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.BlockUtils.set(BlockUtils.java:59)
[13:49:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.aliases.ItemType.setBlock(ItemType.java:379)
[13:49:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultChangers$6.change(DefaultChangers.java:286)
[13:49:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultChangers$6.change(DefaultChangers.java:1)
[13:49:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.ConvertedExpression.change(ConvertedExpression.java:141)
[13:49:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.WrapperExpression.change(WrapperExpression.java:124)
[13:49:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:271)
[13:49:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[13:49:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[13:49:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[13:49:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[13:49:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:151)
[13:49:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
[13:49:28] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:49:28] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[13:49:28] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[13:49:28] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238)
[13:49:28] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:205)
[13:49:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:109)
[13:49:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1165)
[13:49:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40)
[13:49:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10)
[13:49:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[13:49:28] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[13:49:28] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[13:49:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[13:49:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[13:49:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411)
[13:49:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[13:49:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[13:49:28] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[13:49:28] [Server thread/ERROR]: #!#! 
[13:49:28] [Server thread/ERROR]: #!#! Version Information:
[13:49:28] [Server thread/ERROR]: #!#!   Skript: 2.3-alpha3 (latest)
[13:49:28] [Server thread/ERROR]: #!#!   Bukkit: 1.13.1-R0.1-SNAPSHOT
[13:49:28] [Server thread/ERROR]: #!#!   Minecraft: 1.13.1
[13:49:28] [Server thread/ERROR]: #!#!   Java: 1.8.0_171 (Java HotSpot(TM) 64-Bit Server VM 25.171-b11)
[13:49:28] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:49:28] [Server thread/ERROR]: #!#! 
[13:49:28] [Server thread/ERROR]: #!#! Server platform: Spigot
[13:49:28] [Server thread/ERROR]: #!#! 
[13:49:28] [Server thread/ERROR]: #!#! Current node: null
[13:49:28] [Server thread/ERROR]: #!#! Current item: set the block ([[long:1]] meter(s) west {_location}(as org.bukkit.Location) >> ch.njol.skript.expressions.ExprBlock$1@31e03fce: org.bukkit.Location->org.bukkit.block.Block) to [[itemtype:dirt block]]
[13:49:28] [Server thread/ERROR]: #!#! Current trigger: left click on furnace holding blaze rod (click on [[itemtype:lit furnace or northward unlit furnace]] holding [[itemtype:blaze rod]]) (autominer-v1.12-1.13.1.sk, line 612)
[13:49:28] [Server thread/ERROR]: #!#! 
[13:49:28] [Server thread/ERROR]: #!#! Thread: Server thread
[13:49:28] [Server thread/ERROR]: #!#! 
[13:49:28] [Server thread/ERROR]: #!#! Language: english
[13:49:28] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[13:49:28] [Server thread/ERROR]: #!#! 
[13:49:28] [Server thread/ERROR]: #!#! End of Error.
[13:49:28] [Server thread/ERROR]: #!#!

**Comment by ShaneBeee** [comment]
I can vouch for this. I was trying to set a block to air, and then spawn a falling block and like you said, a torch is put there!

**Comment by ShaneBeee** [comment]
I have tested this after bensku fixed it... confirmed it is fixed :)
