### ISSUE TITLE
Crashes in 2.3-alpha4

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1557]
```
[22:11:59] [Server thread/ERROR]: #!#! 
[22:11:59] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[22:11:59] [Server thread/ERROR]: #!#! 
[22:11:59] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[22:11:59] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:11:59] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[22:11:59] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[22:11:59] [Server thread/ERROR]: #!#! 
[22:11:59] [Server thread/ERROR]: #!#! Stack trace:
[22:11:59] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: Cannot get new data of Modern Material
[22:11:59] [Server thread/ERROR]: #!#!     at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[22:11:59] [Server thread/ERROR]: #!#!     at org.bukkit.Material.getNewData(Material.java:2033)
[22:11:59] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEnderman.getCarriedMaterial(CraftEnderman.java:22)
[22:11:59] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.EndermanData.init(EndermanData.java:60)
[22:11:59] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.EndermanData.init(EndermanData.java:1)
[22:11:59] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.EntityData.getData(EntityData.java:507)
[22:11:59] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.EntityData.fromEntity(EntityData.java:527)
[22:11:59] [Server thread/ERROR]: #!#!     at ch.njol.skript.events.EvtClick$2.check(EvtClick.java:240)
[22:11:59] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:173)
[22:11:59] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleLiteral.check(SimpleLiteral.java:173)
[22:11:59] [Server thread/ERROR]: #!#!     at ch.njol.skript.events.EvtClick.check(EvtClick.java:236)
[22:11:59] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146)
[22:11:59] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110)
[22:11:59] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:11:59] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[22:11:59] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[22:11:59] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1826)
[22:11:59] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69)
[22:11:59] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13)
[22:11:59] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[22:11:59] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:11:59] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:11:59] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[22:11:59] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[22:11:59] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411)
[22:11:59] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[22:11:59] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[22:11:59] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[22:11:59] [Server thread/ERROR]: #!#! 
[22:11:59] [Server thread/ERROR]: #!#! Version Information:
[22:11:59] [Server thread/ERROR]: #!#!   Skript: 2.3-alpha4 (latest)
[22:11:59] [Server thread/ERROR]: #!#!   Bukkit: 1.13.1-R0.1-SNAPSHOT
[22:11:59] [Server thread/ERROR]: #!#!   Minecraft: 1.13.1
[22:11:59] [Server thread/ERROR]: #!#!   Java: 1.8.0_66 (Java HotSpot(TM) 64-Bit Server VM 25.66-b17)
[22:11:59] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.16.0-4-amd64
[22:11:59] [Server thread/ERROR]: #!#! 
[22:11:59] [Server thread/ERROR]: #!#! Server platform: Spigot
[22:11:59] [Server thread/ERROR]: #!#! 
[22:11:59] [Server thread/ERROR]: #!#! Current node: null
[22:11:59] [Server thread/ERROR]: #!#! Current item: null
[22:11:59] [Server thread/ERROR]: #!#! 
[22:11:59] [Server thread/ERROR]: #!#! Thread: Server thread
[22:11:59] [Server thread/ERROR]: #!#! 
[22:11:59] [Server thread/ERROR]: #!#! Language: english
[22:11:59] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[22:11:59] [Server thread/ERROR]: #!#! 
[22:11:59] [Server thread/ERROR]: #!#! End of Error.
[22:11:59] [Server thread/ERROR]: #!#! 
[22:11:59] [Server thread/ERROR]: Could not pass event PlayerInteractEntityEvent to Skript v2.3-alpha4
ch.njol.skript.util.EmptyStacktraceException: null
```

**Comment by TheBentoBox** [comment]
Probably just that the Enderman data class hasn’t been updated to respect the updated block ID system.

**Comment by TheBentoBox** [comment]
Gonna put stuff that’s presumably broken due to the new aliases/ID system at medium prio for now.
