### ISSUE TITLE
Server Stop Severe Error

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1558]
Hey... so I tested with alpha 4 and got this error when I stop my server.

Info:
- Brand new server with newest spigot 1.13.1 (built right around the time i'm posting this)
- No plugins other than Skript
- Fresh new world

```
[20:48:45 INFO]: Stopping the server
[20:48:45 INFO]: Stopping server
[20:48:45 INFO]: [Skript] Disabling Skript v2.3-alpha4
[20:48:45 ERROR]: #!#! 
[20:48:45 ERROR]: #!#! [Skript] Severe Error:
[20:48:45 ERROR]: #!#! An error occurred while shutting down.
[20:48:45 ERROR]: #!#! This might or might not cause any issues.
[20:48:45 ERROR]: #!#! 
[20:48:45 ERROR]: #!#! Something went horribly wrong with Skript.
[20:48:45 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:48:45 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[20:48:45 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[20:48:45 ERROR]: #!#! 
[20:48:45 ERROR]: #!#! Stack trace:
[20:48:45 ERROR]: #!#! java.lang.IllegalMonitorStateException: attempt to unlock read lock, not locked by current thread
[20:48:45 ERROR]: #!#!     at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.unmatchedUnlockException(ReentrantReadWriteLock.java:444)
[20:48:45 ERROR]: #!#!     at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryReleaseShared(ReentrantReadWriteLock.java:428)
[20:48:45 ERROR]: #!#!     at java.util.concurrent.locks.AbstractQueuedSynchronizer.releaseShared(AbstractQueuedSynchronizer.java:1341)
[20:48:45 ERROR]: #!#!     at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.unlock(ReentrantReadWriteLock.java:881)
[20:48:45 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.saveVariables(FlatFileStorage.java:416)
[20:48:45 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.close(FlatFileStorage.java:346)
[20:48:45 ERROR]: #!#!     at ch.njol.skript.Skript.onDisable(Skript.java:920)
[20:48:45 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[20:48:45 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:363)
[20:48:45 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422)
[20:48:45 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415)
[20:48:45 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:362)
[20:48:45 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:625)
[20:48:45 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:770)
[20:48:45 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[20:48:45 ERROR]: #!#! 
[20:48:45 ERROR]: #!#! Version Information:
[20:48:45 ERROR]: #!#!   Skript: 2.3-alpha4 (latest)
[20:48:45 ERROR]: #!#!   Bukkit: 1.13.1-R0.1-SNAPSHOT
[20:48:45 ERROR]: #!#!   Minecraft: 1.13.1
[20:48:45 ERROR]: #!#!   Java: 1.8.0_181 (Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
[20:48:45 ERROR]: #!#!   OS: Mac OS X x86_64 10.14
[20:48:45 ERROR]: #!#! 
[20:48:45 ERROR]: #!#! Server platform: Spigot
[20:48:45 ERROR]: #!#! 
[20:48:45 ERROR]: #!#! Current node: databases: (config.sk, line 195)
[20:48:45 ERROR]: #!#! Current item: null
[20:48:45 ERROR]: #!#! 
[20:48:45 ERROR]: #!#! Thread: Server thread
[20:48:45 ERROR]: #!#! 
[20:48:45 ERROR]: #!#! Language: english
[20:48:45 ERROR]: #!#! Link parse mode: DISABLED
[20:48:45 ERROR]: #!#! 
[20:48:45 ERROR]: #!#! End of Error.
[20:48:45 ERROR]: #!#! 
[20:48:45 INFO]: Saving players
[20:48:45 INFO]: Saving worlds
[20:48:45 INFO]: Saving chunks for level 'world'/minecraft:overworld
>logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by TheBentoBox** [comment]
I can confirm this as I saw it as well but it was late last night so I hadn't opened/checked for an issue. No idea the priority of this because I can't tell if it's a harmless error or not but it's potentially very high prio since it may be causing variables to not save since it looks to be due to the recent changes for non-blocking variable writing.

**Comment by iOshawott** [comment]
I got something like that:
```
[22:04:35] [Server thread/ERROR]: #!#! 
[22:04:35] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[22:04:35] [Server thread/ERROR]: #!#! 
[22:04:35] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[22:04:35] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:04:35] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[22:04:35] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[22:04:35] [Server thread/ERROR]: #!#! 
[22:04:35] [Server thread/ERROR]: #!#! Stack trace:
[22:04:35] [Server thread/ERROR]: #!#! java.lang.IllegalMonitorStateException: attempt to unlock read lock, not locked by current thread
[22:04:35] [Server thread/ERROR]: #!#!     at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.unmatchedUnlockException(ReentrantReadWriteLock.java:444)
[22:04:35] [Server thread/ERROR]: #!#!     at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryReleaseShared(ReentrantReadWriteLock.java:428)
[22:04:35] [Server thread/ERROR]: #!#!     at java.util.concurrent.locks.AbstractQueuedSynchronizer.releaseShared(AbstractQueuedSynchronizer.java:1341)
[22:04:35] [Server thread/ERROR]: #!#!     at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.unlock(ReentrantReadWriteLock.java:881)
[22:04:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.Variables.getVariable(Variables.java:325)
[22:04:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Variable.getRaw(Variable.java:253)
[22:04:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Variable.get(Variable.java:262)
[22:04:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Variable.getConverted(Variable.java:407)
[22:04:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Variable.getAll(Variable.java:631)
[22:04:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Variable.check(Variable.java:653)
[22:04:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:258)
[22:04:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
[22:04:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:51)
[22:04:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[22:04:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[22:04:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[22:04:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110)
[22:04:35] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:04:35] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[22:04:35] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[22:04:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292)
[22:04:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:218)
[22:04:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1179)
[22:04:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40)
[22:04:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10)
[22:04:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[22:04:35] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:04:35] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:04:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[22:04:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[22:04:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[22:04:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[22:04:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[22:04:35] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[22:04:35] [Server thread/ERROR]: #!#! 
[22:04:35] [Server thread/ERROR]: #!#! Version Information:
[22:04:35] [Server thread/ERROR]: #!#!   Skript: 2.3-alpha4 (latest)
[22:04:35] [Server thread/ERROR]: #!#!   Bukkit: 1.13.1-R0.1-SNAPSHOT
[22:04:35] [Server thread/ERROR]: #!#!   Minecraft: 1.13.1
[22:04:35] [Server thread/ERROR]: #!#!   Java: 1.8.0_66 (Java HotSpot(TM) 64-Bit Server VM 25.66-b17)
[22:04:35] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.16.0-4-amd64
[22:04:35] [Server thread/ERROR]: #!#! 
[22:04:35] [Server thread/ERROR]: #!#! Server platform: Spigot
[22:04:35] [Server thread/ERROR]: #!#! 
[22:04:35] [Server thread/ERROR]: #!#! Current node: null
[22:04:35] [Server thread/ERROR]: #!#! Current item: {gornikp::%the player%}(as java.lang.Object) is greater than {_z}(as java.lang.Object) (comparator: null)
[22:04:35] [Server thread/ERROR]: #!#! Current trigger: break of stone (break/place/burn/fade/form of stone block) (prace.sk, line 275)
[22:04:35] [Server thread/ERROR]: #!#! 
[22:04:35] [Server thread/ERROR]: #!#! Thread: Server thread
[22:04:35] [Server thread/ERROR]: #!#! 
[22:04:35] [Server thread/ERROR]: #!#! Language: english
[22:04:35] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[22:04:35] [Server thread/ERROR]: #!#! 
[22:04:35] [Server thread/ERROR]: #!#! End of Error.
[22:04:35] [Server thread/ERROR]: #!#! 

```
there's something horribly wrong with variables
