### ISSUE TITLE
Aliases problem in skript

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1559]
```
command /test:
    trigger:
        if player have 3 acacia log:
            ...
```
"can't understand this condition: 'player have 3 acacia log'"
```
command /test:
    trigger:
        if player have 3 oak log:
            ...
```
succesfully reloaded

So - acacia log doesn't works , oak log works.
I checked with %player's tool% and it says that is acacia log so it should work ; d

**Comment by TheBentoBox** [comment]
Is this with the latest version (2.3-alpha4, with the new aliases)?

**Comment by iOshawott** [comment]
alpha-4 

next problem with using new aliases like "freshly planted wheat plant" or "fully grown wheat plant" [aliases from %event-block%]
```
[14:44:17] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[14:44:17] [Server thread/ERROR]: #!#! 
[14:44:17] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[14:44:17] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:44:17] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[14:44:17] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[14:44:17] [Server thread/ERROR]: #!#! 
[14:44:17] [Server thread/ERROR]: #!#! Stack trace:
[14:44:17] [Server thread/ERROR]: #!#! java.lang.UnsupportedOperationException: update 1.13
[14:44:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.DelayedChangeBlock.setBlockData(DelayedChangeBlock.java:327)
[14:44:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.bukkitutil.block.NewBlockCompat$NewBlockSetter.setBlock(NewBlockCompat.java:239)
[14:44:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.BlockUtils.set(BlockUtils.java:59)
[14:44:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.aliases.ItemType.setBlock(ItemType.java:379)
[14:44:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultChangers$6.change(DefaultChangers.java:286)
[14:44:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultChangers$6.change(DefaultChangers.java:1)
[14:44:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.Changer$ChangerUtils.change(Changer.java:70)
[14:44:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.EventValueExpression.change(EventValueExpression.java:191)
[14:44:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.WrapperExpression.change(WrapperExpression.java:124)
[14:44:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:272)
[14:44:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[14:44:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[14:44:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[14:44:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[14:44:17] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76)
[14:44:17] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[14:44:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893)
[14:44:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411)
[14:44:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[14:44:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[14:44:17] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[14:44:17] [Server thread/ERROR]: #!#! 
[14:44:17] [Server thread/ERROR]: #!#! Version Information:
[14:44:17] [Server thread/ERROR]: #!#!   Skript: 2.3-alpha4 (latest)
[14:44:17] [Server thread/ERROR]: #!#!   Bukkit: 1.13.1-R0.1-SNAPSHOT
[14:44:17] [Server thread/ERROR]: #!#!   Minecraft: 1.13.1
[14:44:17] [Server thread/ERROR]: #!#!   Java: 1.8.0_66 (Java HotSpot(TM) 64-Bit Server VM 25.66-b17)
[14:44:17] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.16.0-4-amd64
[14:44:17] [Server thread/ERROR]: #!#! 
[14:44:17] [Server thread/ERROR]: #!#! Server platform: Spigot
[14:44:17] [Server thread/ERROR]: #!#! 
[14:44:17] [Server thread/ERROR]: #!#! Current node: null
[14:44:17] [Server thread/ERROR]: #!#! Current item: set the block to [[itemtype:freshly planted wheat plant]]
[14:44:17] [Server thread/ERROR]: #!#! Current trigger: break of fully grown wheat plant (break/place/burn/fade/form of fully grown wheat plant) (wq1.sk, line 582)
[14:44:17] [Server thread/ERROR]: #!#! 
[14:44:17] [Server thread/ERROR]: #!#! Thread: Server thread
[14:44:17] [Server thread/ERROR]: #!#! 
[14:44:17] [Server thread/ERROR]: #!#! Language: english
[14:44:17] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[14:44:17] [Server thread/ERROR]: #!#! 
[14:44:17] [Server thread/ERROR]: #!#! End of Error.
[14:44:17] [Server thread/ERROR]: #!#! 
```

**Comment by TheBentoBox** [comment]
Weird, I don't know if that's an alias-side or code-side issue but those should both be valid aliases.

**Comment by ShaneBeee** [comment]
@iOshawott  its because you dont have triggers in your commands.
When I put in EXACTLY what you wrote (but adding something after the condition) i get this:
```
[09:51:07 ERROR]: Required entry 'trigger' is missing in 'command /test' (test.sk, starting at line 18) (test.sk, line 18: command /test:')
[09:51:07 ERROR]: Unexpected entry 'if player have 3 acacia log'. Check whether it's spelled correctly or remove it. (test.sk, line 19: if player have 3 acacia log:')
```

I just tried:
```
command /test:
	trigger:
		if player have 3 acacia log:
			send "YOU HAVE WOOD" to player
```
And it works perfectly fine
I also tried:
```
command /test:
	trigger:
		if player have 3 oak log:
			send "YOU HAVE WOOD" to player
```
Also worked perfectly fine.

**Comment by TheBentoBox** [comment]
@ShaneBeee Good catch, I didn't pay enough attention to the code, just looking at the error since they said it was `can't understand this condition`.

Still seems like there may be an issue with the wheat, though I'd like to see the code that's causing the wheat error @iOshawott

**Comment by iOshawott** [comment]
@ShaneBeee I used triggers just I doesn't works : d

**Comment by ShaneBeee** [comment]
@iOshawott  Are you using any addons?
Try remove addons if you are using them.

Also if you are using triggers you should put them in the code you are sending on here. Its hard for the dev team to test/replicate your problem if you are putting different code than you are using.

I just tested both, and they work perfectly fine!

**Comment by iOshawott** [comment]
@TheBentoBox  @ShaneBeee  It doesn't works in this script if you are that much about triggers ....
```
on rightclick on player:
	if name of event-entity is "&eDrwal":
		if {drwal::%player%} is not set:
			if {gornik::%player%} is greater than 6:
				if player have 1 paper named "&aWejściówka Na Szkolenie" with lore "&eDrwal":
					execute console command "szkol drwal %player% 0"
					send "&eDrwal&a: &bRozpoczynamy szkolenie!" to player
					wait 3 seconds
					add 1 oak log to player's inventory
					add 2 stick to player's inventory
					send "&eDrwal&a: &bOtrzymałeś ode mnie ważne przedmioty. Za ich pomocą scraftujesz drewnianą siekierkę" to player
					wait 3 seconds
					send "&eDrwal&a: &bBędziesz potrzebował desek, możesz je otrzymać umieszczając blok drewna w craftingu" to player
					wait 4 seconds
					send "&eDrwal&a: &bBy zrobić siekierkę proszę w craftingu ułóż w craftingu rzeczy w taki sposób:" to player
					send " " to player
					send " xx" to player
					send " Yx" to player
					send " Y " to player
					send " " to player
					send "x - deska" to player
					send "Y - patyk" to player
					wait 3 seconds
					send "&eDrwal&a: &bPowodzenia! Scraftuj teraz drewnianą siekierkę" to player
					execute console command "szkol drwal %player% 1"
				else:
					send "&eDrwal&a: &bPotrzebujesz szkolenia? /szkolenie" to player
			else:
				send "&eDrwal&a: &bPotrzebujesz 7 lvl górnika by się u mnie szkolić" to player
			stop
		if {qd::%player%} is not set:
			set {qd::%player%} to "0.10"
			send "&eDrwal&a: &bWitaj, widzę że jesteś początkującym graczem i dopiero zaczynasz rozgrywkę" to player
			wait 2 seconds
			send "&eDrwal&a: &bMogę dać Ci siekierę początkującego drwala za jedyne 32 drewna dębowego" to player
			stop
		if {qd::%player%} is "0.10":
			if player have 32 oak log:
				remove 32 oak log from player's inventory
				add 1 diamond axe of unbreaking 2 named "&e&lKilof Początkującego Drwala" to player's inventory
				send "&cPssst! Postęp swoich zadań możesz sprawdzić pod /questy" to player
				send "&eDrwal&a: &bDziękuję Ci za pomoc!" to player
				set {qd::%player%} to "0.20"
			else:
				send "&eDrwal&a: &bNagroda jest tego warta, uwierz, przynieś to drewno" to player
				send "&cPssst! Postęp swoich zadań możesz sprawdzić pod /questy" to player
			stop
		if {qd::%player%} is "0.20":
			set {qd::%player%} to "0.21"
			send "&eDrwal&a: &bZobaczmy czy potrafisz też ścinać inne rodzaje drewna!" to player
			wait 2 seconds
			send "&eDrwal&a: &bZetnij proszę i przynieś 64 drewna brzozowego" to player
			stop
		if {qd::%player%} is "0.21":
			if player have 64 birch log:
				remove 64 birch log from player's inventory
				add 1 iron ingot of efficiency 1 named "&cBooster Drwala 1" with lore "&aPrzyspiesza pracę" to player's inventory
				send "&cPssst! Postęp swoich zadań możesz sprawdzić pod /questy" to player
				send "&eDrwal&a: &bDziękuję Ci za pomoc!" to player
				set {qd::%player%} to "0.30"
			else:
				send "&eDrwal&a: &bCo? Z brzozą już nie tak prosto? Hehe, musisz się jeszcze wiele nauczyć" to player
				send "&cPssst! Postęp swoich zadań możesz sprawdzić pod /questy" to player
			stop
		if {qd::%player%} is "0.30":
			set {qd::%player%} to "0.31"
			send "&eDrwal&a: &bMoże się domyśliłeś i przygotowałeś, jeżeli tak to nawet i lepiej. Zdobądź dla mnie 64 drewna akacjowego" to player
			stop
		if {qd::%player%} is "0.31":
			send "&cBłąd! $25$ <- przekaż ten błąd administracji"
#			if player have 64 acacia log:
#				remove 64 acacia log from player's inventory
#				add 1 iron ingot of efficiency 2 named "&cBooster Drwala 2" with lore "&aPrzyspiesza pracę" to player's inventory
#				send "&cPssst! Postęp swoich zadań możesz sprawdzić pod /questy" to player
#				send "&eDrwal&a: &bŚpiewająco! Nawet wiedziałeś które to drewno! Ale teraz będzie hardcore. Jeteś gotów?" to player
#				set {qd::%player%} to "0.40"
#			else:
#				send "&eDrwal&a: &bAkacje rosną w Sosnowcu" to player
#				send "&cPssst! Postęp swoich zadań możesz sprawdzić pod /questy" to player
#			stop
		if {qd::%player%} is "0.40":
			set {qd::%player%} to "0.41"
			send "&eDrwal&a: &bNo to jak jesteś gotów to teraz 64 drewna junglowego! Po odbiór nagrody przygotuj miejsce w eq!" to player
			stop
```
-->			if player have 64 acacia log:
-->				remove 64 acacia log from player's inventory


I'm not using addons

**Comment by ShaneBeee** [comment]
For testing sake, I tried the following
```
on rightclick on wall sign:
	if player has 64 acacia log:
		remove 64 acacia log from inventory of player
```
When I clicked on the wall sign, 64 acacia logs were removed from my inventory

**Comment by iOshawott** [comment]
Well, I reinstalled skript third time and now it works.

**Comment by TheBentoBox** [comment]
That's #1543 

Since your other issues are resolved I'm closing this
