### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by Anoniempje1234** [SkriptLang/Skript#1576]
Can't use:
log "%text%" in "%file%"
Example:
log "%player% has found diamonds!" in "diamonds.txt"

Can you fix that, please?

**Comment by Nicofisi** [comment]
What do you mean by `can't use`? Script load error, console error, nothing happens?

**Comment by Anoniempje1234** [comment]
I use:

```
on break:
	event-block is diamond ore
	log "Diamond is broken: %location of event-block%" in "broken.txt"
```
When I reload the skript, I see in the console:

```
[14:52:07 INFO]: [Skript] Reloading test.sk...
[14:52:07 ERROR]: #!#!
[14:52:07 ERROR]: #!#! [Skript] Severe Error:
[14:52:07 ERROR]: #!#! Could not load test.sk
[14:52:07 ERROR]: #!#!
[14:52:07 ERROR]: #!#! Something went horribly wrong with Skript.
[14:52:07 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:52:07 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[14:52:07 ERROR]: #!#! Here is full list of them:
[14:52:07 ERROR]: #!#! skRayFall (http://sk.rayfall.net/) SkQuery
[14:52:07 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[14:52:07 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[14:52:07 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[14:52:07 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[14:52:07 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[14:52:07 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[14:52:07 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[14:52:07 ERROR]: #!#!
[14:52:07 ERROR]: #!#! Stack trace:
[14:52:07 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for lambda
[14:52:07 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1809)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1776)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1524)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:222)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:500)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:819)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1540)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1497)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1470)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:222)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:322)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:632)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:241)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:145)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:498)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:819)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1540)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:222)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:976)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1063)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:663)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:390)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:402)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:435)
[14:52:07 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:181)
[14:52:07 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:52:07 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[14:52:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699)
[14:52:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:684)
[14:52:07 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:459)
[14:52:07 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418)
[14:52:07 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[14:52:07 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[14:52:07 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[14:52:07 ERROR]: #!#!
[14:52:07 ERROR]: #!#! Version Information:
[14:52:07 ERROR]: #!#!   Skript: 2.3-alpha4 (latest)
[14:52:07 ERROR]: #!#!   Bukkit: 1.13.1-R0.1-SNAPSHOT
[14:52:07 ERROR]: #!#!   Minecraft: 1.13.1
[14:52:07 ERROR]: #!#!   Java: 1.8.0_161 (Java HotSpot(TM) 64-Bit Server VM 25.161-b12)
[14:52:07 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[14:52:07 ERROR]: #!#!
[14:52:07 ERROR]: #!#! Server platform: Spigot
[14:52:07 ERROR]: #!#!
[14:52:07 ERROR]: #!#! Current node: log "Diamond is broken at location %location of event-block%" in "Broken.txt" (test2.sk, line 14)
[14:52:07 ERROR]: #!#! Current item: null
[14:52:07 ERROR]: #!#!
[14:52:07 ERROR]: #!#! Thread: Server thread
[14:52:07 ERROR]: #!#!
[14:52:07 ERROR]: #!#! Language: english
[14:52:07 ERROR]: #!#! Link parse mode: DISABLED
[14:52:07 ERROR]: #!#!
[14:52:07 ERROR]: #!#! End of Error.
[14:52:07 ERROR]: #!#!
[14:52:07 INFO]: [Skript] Successfully reloaded test.sk.
```
When I use this:

```

on break:
	event-block is diamond ore
	log "Diamond is broken!" in "broken.txt"
```
than isn't there an error.
I use the addons skRayfall and SkQuery.

**Comment by Pikachu920** [comment]
that's caused by skquery not registering the lambda type

**Comment by Blueyescat** [comment]
@Anoniempje1234 use LimeGlass' skQuery fork: https://forums.skunity.com/resources/unofficial-skquery-fork-1-6-1-12.68/
