### ISSUE TITLE
TuSKe's GUI Manager is not working

### ISSUE THREAD

**Issue by MadPanCake** [SkriptLang/Skript#1577]
So I tried to use TuSKe's cool GUI Manager, but after I add an effect to the item in the GUI, it doesn't want to open GUI anymore, instead it throws a pesky error.
My Skript is latest stable release, my TuSKe is latest release too, I've also got Skelett, sqLibrary, skQuery and skRayFall.
(problematic part of) My code:
```
on right click on crafting table:
	if player is sneaking:
		cancel event
		execute console command "menu craftingmenu %player%"

command /menu [<text>] [<player>]:
	executable by: console
	trigger:
		if arg 2 is set:
			if arg 1 is "craftingmenu":
				create a gui with id "crafting.%player-arg%" with virtual chest and shape {_crafting.shape::*}:
					make gui slot "2" with dirt:
						wait 1 tick
```
 
Error in console:
```
[21:02:39 INFO]: MadPanCake issued server command: /sk reload testy
[21:02:46 ERROR]: #!#!
[21:02:46 ERROR]: #!#! [Skript] Severe Error:
[21:02:46 ERROR]: #!#!
[21:02:46 ERROR]: #!#! Something went horribly wrong with Skript.
[21:02:46 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[21:02:46 ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[21:02:46 ERROR]: #!#! You may download new version of Skript at https://github.com/SkriptLang/Skript/releases
[21:02:46 ERROR]: #!#! You will be given instructions how to report this error if it persists with latest Skript.
[21:02:46 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[21:02:46 ERROR]: #!#!
[21:02:46 ERROR]: #!#! Stack trace:
[21:02:46 ERROR]: #!#! java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.WeakHashMap
[21:02:46 ERROR]: #!#!     at com.github.tukenuke.tuske.util.VariableUtil.<init>(VariableUtil.java:24)
[21:02:46 ERROR]: #!#!     at com.github.tukenuke.tuske.util.VariableUtil.getInstance(VariableUtil.java:17)
[21:02:46 ERROR]: #!#!     at com.github.tukenuke.tuske.sections.gui.EffMakeGUI.execute(EffMakeGUI.java:77)
[21:02:46 ERROR]: #!#!     at com.github.tukenuke.tuske.util.EffectSection.check(EffectSection.java:54)
[21:02:46 ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
[21:02:46 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:52)
[21:02:46 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[21:02:46 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[21:02:46 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:294)
[21:02:46 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[21:02:46 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:196)
[21:02:46 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:02:46 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:02:46 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641)
[21:02:46 ERROR]: #!#!     at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574)
[21:02:46 ERROR]: #!#!     at ch.njol.skript.Skript.dispatchCommand(Skript.java:1166)
[21:02:46 ERROR]: #!#!     at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:84)
[21:02:46 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[21:02:46 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[21:02:46 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[21:02:46 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[21:02:46 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[21:02:46 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110)
[21:02:46 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:02:46 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[21:02:46 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[21:02:46 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234)
[21:02:46 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458)
[21:02:46 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:944)
[21:02:46 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[21:02:46 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[21:02:46 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:02:46 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:02:46 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[21:02:46 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[21:02:46 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
[21:02:46 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[21:02:46 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[21:02:46 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[21:02:46 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[21:02:46 ERROR]: #!#!
[21:02:46 ERROR]: #!#! Version Information:
[21:02:46 ERROR]: #!#!   Skript: 2.2-dev37c (OUTDATED)
[21:02:46 ERROR]: #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
[21:02:46 ERROR]: #!#!   Minecraft: 1.12
[21:02:46 ERROR]: #!#!   Java: 1.8.0_171 (Java HotSpot(TM) 64-Bit Server VM 25.171-b11)
[21:02:46 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[21:02:46 ERROR]: #!#!
[21:02:46 ERROR]: #!#! Server platform: Spigot
[21:02:46 ERROR]: #!#!
[21:02:46 ERROR]: #!#! Current node: null
[21:02:46 ERROR]: #!#! Current item: make  a gui slot "2" of gui with [[itemstack:dirt]]
[21:02:46 ERROR]: #!#! Current trigger: command /menu (simple event) (testy.sk, line -1)
[21:02:46 ERROR]: #!#!
[21:02:46 ERROR]: #!#! Thread: Server thread
[21:02:46 ERROR]: #!#!
[21:02:46 ERROR]: #!#! Language: english
[21:02:46 ERROR]: #!#! Link parse mode: DISABLED
[21:02:46 ERROR]: #!#!
[21:02:46 ERROR]: #!#! End of Error.
[21:02:46 ERROR]: #!#!
[21:02:46 INFO]: An internal error occurred while attempting to perform this command.
```

**Comment by ShaneBeee** [comment]
This page is for reporting issues with Skript, not the addons themselves
