### ISSUE TITLE
on right click on ender chest: seems not to be working 2.3-beta1 1.13

### ISSUE THREAD

**Issue by dowen01** [SkriptLang/Skript#1601]
on right click on ender chest:
						cancel event

Its loads without errors but does not work, am I just being silly? (sorry if so)

Can't wait to get onto 1.13 :) thanks for all the hard work

**Comment by Nicofisi** [comment]
Could someone please confirm this?

**Comment by Blueyescat** [comment]
Works fine for me with Paper 1.13.1

**Comment by dowen01** [comment]
Same with
```
on right click on chest:
cancel event
```

but
```
on right click:
cancel event
```
Works, I must being really silly right?

**Comment by dowen01** [comment]
Will fire up 1.13.1 bare with

**Comment by Blueyescat** [comment]
That means the plugin couldn't load, try to delete Skript/materials.json and restart, if still happens send your latest.log file or every error in console.

**Comment by dowen01** [comment]
deleting plugins/Skript/materials.json helped to the "/skript help"

But taking a closer look at the log I found this (should have looked closer at this first my bad)

[13:50:45] [Server thread/INFO]: [Skript] Enabling Skript v2.3-beta1
[13:50:45] [Server thread/ERROR]: [Skript] It seems that this server platform (CraftBukkit) does not work with Skript.
[13:50:45] [Server thread/ERROR]: [Skript] However, you have chosen to ignore this. Skript will probably still not work.
[13:50:53] [Server thread/INFO]: [Skript] Loaded 71325 aliases in 7566ms
[13:50:53] [Server thread/ERROR]: Error occurred while enabling Skript v2.3-beta1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/entity/Player$Spigot
	at ch.njol.skript.expressions.ExprPing.<clinit>(ExprPing.java:44) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
	at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:392) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit.jar:git-Bukkit-e3d7b2f]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:331) [craftbukkit.jar:git-Bukkit-e3d7b2f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit.jar:git-Bukkit-e3d7b2f]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:418) [craftbukkit.jar:git-Bukkit-e3d7b2f]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:344) [craftbukkit.jar:git-Bukkit-e3d7b2f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:575) [craftbukkit.jar:git-Bukkit-e3d7b2f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:537) [craftbukkit.jar:git-Bukkit-e3d7b2f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:415) [craftbukkit.jar:git-Bukkit-e3d7b2f]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:270) [craftbukkit.jar:git-Bukkit-e3d7b2f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:680) [craftbukkit.jar:git-Bukkit-e3d7b2f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Player$Spigot
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[craftbukkit.jar:git-Bukkit-e3d7b2f]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:76) ~[craftbukkit.jar:git-Bukkit-e3d7b2f]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	... 16 more

**Comment by Blueyescat** [comment]
Yes, don't use CraftBukkit at all. Use Spigot or Paper (recommended).

**Comment by dowen01** [comment]
Works like a charm (I have so much to do now lol)
I have nothing against Spigot or Paper they were just not as much of a thing when I started my server back in 2011 (god I have been at this a while now lol)


Any thoughts on why they're better?

**Comment by Nicofisi** [comment]
PaperSpigot uses Spigot's code, but changes it in some places and adds some things; as a result you you get a server engine which loads chunks on multiple threads by default, has way more configuration options (paper.yml) and is faster in other aspects in general too :)

Good to hear you've solved it anyway! A minor note for the future, afaik we only support the latest "patch" version of each MC version, so 1.9.4, 1.10.2, 1.11.2, 1.12,2, 1.13.1 at the moment

**Comment by dowen01** [comment]
Thanks for all the help guys :)
"only support the latest "patch" version of each MC" YAY! sorry was not aware of that!
Thanks again
