### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by loprip147** [SkriptLang/Skript#1611]
when start server ~ is show me this error
worldguard version: 6.2.2
spigot version: 1.12.2 build1648

[Skript] Task #17 for Skript v2.3-beta1 generated an exception
java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
        at ch.njol.skript.hooks.regions.WorldGuardHook.getRegion_i(WorldGuardHook.java:215) ~[?:?]
        at ch.njol.skript.hooks.regions.RegionsPlugin.getRegion(RegionsPlugin.java:103) ~[?:?]
        at ch.njol.skript.hooks.regions.classes.Region$1.parse(Region.java:82) ~[?:?]
        at ch.njol.skript.hooks.regions.classes.Region$1.parse(Region.java:1) ~[?:?]
        at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:421) ~[?:?]
        at ch.njol.skript.registrations.Classes.parse(Classes.java:450) ~[?:?]
        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:95) ~[?:?]
        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:84) ~[?:?]
        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) ~[?:?]
        at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:165) ~[?:?]
        at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:124) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179) ~[?:?]
        at ch.njol.skript.lang.Condition.parse(Condition.java:81) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1052) ~[?:?]
        at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54) ~[?:?]
        at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1071) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:671) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:392) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:404) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:334) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:364) ~[?:?]
        at ch.njol.skript.Skript$2.run(Skript.java:508) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        ... 31 more

**Comment by Nicofisi** [comment]
What was the whole line of the code? 

Do you have WorldGuard on your server? Do you use the WorldGuard hook anywhere in Skript?

**Comment by TheBentoBox** [comment]
You need to update your WorldGuard, the beta releases currently only support WorldGuard 7.

**Comment by loprip147** [comment]
Code is 
if "%damage cause%" is "sweep attack":

but i writed 
if "%damage cause" is "sweep attack"

less 1 %, than show error...
after added,working fine

**Comment by loprip147** [comment]
no used worldguard in skript

**Comment by Blueyescat** [comment]
You can't use WG 7 on 1.12 btw

**Comment by Nicofisi** [comment]
Unless the WorldGuard devs don't plan to ever support 1.12, the fix is gonna have to be on their side (they need to fix 1.12 support, instead of us re-adding support for outdated WorldGuard versions)

**Comment by bensku** [comment]
The fact that one Skript version supports multiple Minecraft versions does not mean that we support hooks to many versions of other plugins too. That is too much work; I suggest using a world protection plugin that didn't break their API when updating to 1.13.
