### ISSUE TITLE
Lore not work (1.13.2)

### ISSUE THREAD

**Issue by UzumakiYT** [SkriptLang/Skript#1621]
```
command test [<text>]:
	trigger:
		give 1 of stone named "test" with lore "1" to player
		#Throws error(s).
		give 1 of stone named "test" to player 
		#work, no error(s).
		give 1 of stone with lore "test" to player
		#Throws error(s).
```
```
[10:37:40 ERROR]: Could not pass event PlayerCommandPreprocessEvent to Skript v2.3-beta1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1638) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: ch.njol.skript.aliases.ItemType.getItemMeta()Ljava/lang/Object;
        at com.github.leafsk.leaf.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:34) ~[?:?]
        at com.github.leafsk.leaf.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:1) ~[?:?]
        at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75) ~[?:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[?:?]
        at ch.njol.skript.effects.EffChange.execute(EffChange.java:278) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:57) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:242) ~[?:?]
        at ch.njol.skript.command.Commands.handleCommand(Commands.java:257) ~[?:?]
        at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:172) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        ... 16 more
[10:37:40 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'test' in plugin Skript v2.3-beta1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: ch.njol.skript.aliases.ItemType.getItemMeta()Ljava/lang/Object;
        at com.github.leafsk.leaf.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:34) ~[?:?]
        at com.github.leafsk.leaf.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:1) ~[?:?]
        at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75) ~[?:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[?:?]
        at ch.njol.skript.effects.EffChange.execute(EffChange.java:278) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:57) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:242) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:193) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-a1ba5fe-b4230a9]
        ... 15 more
```
Skript 2.3-beta1
spigot 1.13.2

**Comment by ham1255** [comment]
Well. lore does work for me?
I installed 1.13.2 spigot eight now with beta 1 and its works like when I was on 1.13.1-

**Comment by UzumakiYT** [comment]
ups, my bad.

**Comment by TheBentoBox** [comment]
Just for clarity, the stack trace shows LeafSK (which appears to be your own add-on?) as the source of the error. You (or the author of one the add-ons you're apparently sourcing) isn't interacting with Skript's updated aliases system correctly when creating a lored item stack.
