### ISSUE TITLE
Beta1 not working on older MC versions

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#1627]
So I was testing this on Spigot versions 1.9 and 1.10 and it doesn't seem to run, I get the following error
```
[18:00:46 ERROR]: Error occurred while enabling Skript v2.3-beta1 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at ch.njol.skript.SkriptCommand.<clinit>(SkriptCommand.java:78) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:379) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at ch.njol.skript.util.Color.<clinit>(Color.java:81) ~[?:?]
	... 13 more
```
I was going to try do some testing with my pull request but it seems it won't run :(

**Comment by JRoy** [comment]
To save devs from digging through the code: This appears to be issue of bukkit's DyeColor class and 1.13 changes.  

https://github.com/SkriptLang/Skript/blob/449a8d104fccede66d6acd8a35836e266cf9b194/src/main/java/ch/njol/skript/util/Color.java#L78-L83

**Comment by bensku** [comment]
That specific issue was fixed be @Snow-Pyon. I'm quite sure there are more issues with at least 1.9.

**Comment by UzumakiYT** [comment]
```
[13:07:09 INFO]: [Skript] Enabling Skript v2.3-beta2
[13:07:09 WARN]: [Skript] Material mappings for 1.9.4 are not available.
[13:07:09 WARN]: [Skript] Depending on your server software, some aliases may not work.
[13:07:09 ERROR]: Error occurred while enabling Skript v2.3-beta2 (Is it up to date?)
java.lang.ExceptionInInitializerError
        at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:146) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:370) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:361) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:321) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 385
        at ch.njol.skript.aliases.MaterialRegistry.<init>(MaterialRegistry.java:50) ~[?:?]
        at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:100) ~[?:?]
        ... 13 more
```
