### ISSUE TITLE
play sound "BLOCK_WOODEN_BUTTON_CLICK_ON" at player's location with volume 3 and pitch 4

### ISSUE THREAD

**Issue by UnknwonPerson** [SkriptLang/Skript#1640]
[23:25:56] [Server thread/ERROR]: #!#! 
[23:25:56] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[23:25:56] [Server thread/ERROR]: #!#! 
[23:25:56] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[23:25:56] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[23:25:56] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[23:25:56] [Server thread/ERROR]: #!#! Here is full list of them:
[23:25:56] [Server thread/ERROR]: #!#! MundoSK (https://forums.skunity.com/resources/mundosk.69/) SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) 
[23:25:56] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[23:25:56] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[23:25:56] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[23:25:56] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[23:25:56] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[23:25:56] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[23:25:56] [Server thread/ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[23:25:56] [Server thread/ERROR]: #!#! 
[23:25:56] [Server thread/ERROR]: #!#! Stack trace:
[23:25:56] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[23:25:56] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.Effects.EffPlaySound.execute(EffPlaySound.java:52)
[23:25:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[23:25:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[23:25:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[23:25:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[23:25:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285)
[23:25:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:242)
[23:25:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:257)
[23:25:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:172)
[23:25:56] [Server thread/ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
[23:25:56] [Server thread/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:25:56] [Server thread/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[23:25:56] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[23:25:56] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[23:25:56] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[23:25:56] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[23:25:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1638)
[23:25:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481)
[23:25:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:25:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:25:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[23:25:56] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[23:25:56] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[23:25:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[23:25:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[23:25:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[23:25:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[23:25:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[23:25:56] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[23:25:56] [Server thread/ERROR]: #!#! 
[23:25:56] [Server thread/ERROR]: #!#! Version Information:
[23:25:56] [Server thread/ERROR]: #!#!   Skript: 2.3-beta1 (latest)
[23:25:56] [Server thread/ERROR]: #!#!   Bukkit: 1.13.1-R0.1-SNAPSHOT
[23:25:56] [Server thread/ERROR]: #!#!   Minecraft: 1.13.1
[23:25:56] [Server thread/ERROR]: #!#!   Java: 1.8.0_191 (Java HotSpot(TM) 64-Bit Server VM 25.191-b12)
[23:25:56] [Server thread/ERROR]: #!#!   OS: Windows 7 amd64 6.1
[23:25:56] [Server thread/ERROR]: #!#! 
[23:25:56] [Server thread/ERROR]: #!#! Server platform: Spigot
[23:25:56] [Server thread/ERROR]: #!#! 
[23:25:56] [Server thread/ERROR]: #!#! Current node: null
[23:25:56] [Server thread/ERROR]: #!#! Current item: play [(skellett|better)] [sound] (1?%-sound%|2?%-string%) at %locations% (with|at|and) volume %number% (and|with|at) pitch %number%
[23:25:56] [Server thread/ERROR]: #!#! Current trigger: command /test1 (simple event) (server.sk, line -1)
[23:25:56] [Server thread/ERROR]: #!#! 
[23:25:56] [Server thread/ERROR]: #!#! Thread: Server thread
[23:25:56] [Server thread/ERROR]: #!#! 
[23:25:56] [Server thread/ERROR]: #!#! Language: english
[23:25:56] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[23:25:56] [Server thread/ERROR]: #!#! 
[23:25:56] [Server thread/ERROR]: #!#! End of Error.
[23:25:56] [Server thread/ERROR]: #!#!

**Comment by Efnilite** [comment]
This is an error regarding Skellett, so post it in Skellett's issue section :)
https://github.com/TheLimeGlass/Skellett/issues

**Comment by Blueyescat** [comment]
You are using Skellett's play sound effect. Skript's effect is here https://skriptlang.github.io/Skript/effects.html#EffPlaySound

```vb
play sound "BLOCK_WOODEN_BUTTON_CLICK_ON" with volume 3 and pitch 4 for all players
```

You can use Minecraft sound names too.
