### ISSUE TITLE
Block breaking broken.

### ISSUE THREAD

**Issue by nikkedoy98** [SkriptLang/Skript#1662]
As you can see. It isn't passing event.

```
[15:21:39 ERROR]: Could not pass event BlockBreakEvent to Skript v2.3-beta2
java.lang.NoSuchMethodError: com.sk89q.worldedit.bukkit.BukkitAdapter.asBlockVector(Lorg/bukkit/Location;)Lcom/sk89q/worldedit/math/BlockVector3;
at ch.njol.skript.hooks.regions.WorldGuardHook.getRegionsAt_i(WorldGuardHook.java:200) ~[?:?]
at ch.njol.skript.hooks.regions.RegionsPlugin.getRegionsAt(RegionsPlugin.java:92) ~[?:?]
at ch.njol.skript.hooks.regions.expressions.ExprRegionsAt.get(ExprRegionsAt.java:83) ~[?:?]
at ch.njol.skript.hooks.regions.expressions.ExprRegionsAt.get(ExprRegionsAt.java:1) ~[?:?]
at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[?:?]
at ch.njol.skript.lang.VariableString.toString(VariableString.java:453) ~[?:?]
at ch.njol.skript.lang.VariableString.getAll(VariableString.java:622) ~[?:?]
at ch.njol.skript.lang.VariableString.check(VariableString.java:632) ~[?:?]
at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:253) ~[?:?]
at ch.njol.skript.lang.Condition.run(Condition.java:56) ~[?:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
at ch.njol.skript.lang.Trigger.execute(Trigger.java:57) ~[?:?]
at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152) ~[?:?]
at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-425]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-425]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-425]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:299) ~[patched_1.13.2.jar:git-Paper-425]
at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:129) ~[patched_1.13.2.jar:git-Paper-425]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1246) ~[patched_1.13.2.jar:git-Paper-425]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-425]
at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-425]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-425]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-425]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-425]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-425]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-425]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-425]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by TheBentoBox** [comment]
Is this consistent every time you break a block or only under certain scenarios?

**Comment by nikkedoy98** [comment]
Yup. Looks like it's not working at all.

**Comment by TheBentoBox** [comment]
What's your WorldGuard version? The version dependency was updated in beta2 so you may need a more recent release.

**Comment by nikkedoy98** [comment]
Maybe that will resolve this problem.

**Comment by Nicofisi** [comment]
Note that you need WorldGuard 7.x

**Comment by nikkedoy98** [comment]
Yup. It works now!

**Comment by TheBentoBox** [comment]
Good to hear 🌈

**Comment by Fabrimat** [comment]
I have WorldGuard 7.0.0-SNAPSHOT;0dc5781 on Spigot 1.13.1 and I get this error

**Comment by Nicofisi** [comment]
Still, please send your stacktrace

**Comment by Fabrimat** [comment]
#1672

**Comment by Nicofisi** [comment]
No idea whether it's needed (or the class is shaded) but do you have WorldEdit too? If not, could you try with it?

**Comment by Fabrimat** [comment]
I have FAWE 18.10.26-94d5028-2069

**Comment by Nicofisi** [comment]
Would be best to test with the latest builds of the official WE http://builds.enginehub.org/job/worldedit?branch=master

**Comment by Fabrimat** [comment]
Yeah probably the problem is FAWE, I'll report to them.
