### ISSUE TITLE
Inventory clicking event on border left and right

### ISSUE THREAD

**Issue by Sodies** [SkriptLang/Skript#1687]
### Description
I'm  having an issue with spam error in console. But the code works and everything works fine ingame. It's just whenever the player click the window border left and right it spams an error to the console

### Steps to Reproduce
`on inventory click:
	If inventory type of clicked inventory is "CRAFT":
		open crafting table to player`
While having this code in the skript folder. It will spams error when you click left or right window border.

### Errors / Screenshots
[02:43:40 ERROR]: #!#!
[02:43:40 ERROR]: #!#! [Skript] Severe Error:
[02:43:40 ERROR]: #!#!
[02:43:40 ERROR]: #!#! Something went horribly wrong with Skript.
[02:43:40 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[02:43:40 ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[02:43:40 ERROR]: #!#! You may download new version of Skript at https://github.com/bensku/Skript/releases
[02:43:40 ERROR]: #!#! You will be given instructions how to report this error if it persists with latest Skript.
[02:43:40 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[02:43:40 ERROR]: #!#!
[02:43:40 ERROR]: #!#! Stack trace:
[02:43:40 ERROR]: #!#! java.lang.NullPointerException
[02:43:40 ERROR]: #!#!     at com.gmail.thelimeglass.Expressions.ExprInventoryType.get(ExprInventoryType.java:45)
[02:43:40 ERROR]: #!#!     at com.gmail.thelimeglass.Expressions.ExprInventoryType.get(ExprInventoryType.java:1)
[02:43:40 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:161)
[02:43:40 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:258)
[02:43:40 ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
[02:43:40 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:51)
[02:43:40 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[02:43:40 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[02:43:40 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:151)
[02:43:40 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
[02:43:40 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[02:43:40 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[02:43:40 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[02:43:40 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
[02:43:40 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[02:43:40 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[02:43:40 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[02:43:40 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[02:43:40 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[02:43:40 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[02:43:40 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[02:43:40 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[02:43:40 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[02:43:40 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[02:43:40 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[02:43:40 ERROR]: #!#!
[02:43:40 ERROR]: #!#! Version Information:
[02:43:40 ERROR]: #!#!   Skript: 2.2-dev36 (OUTDATED)
[02:43:40 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[02:43:40 ERROR]: #!#!   Minecraft: 1.12.2
[02:43:40 ERROR]: #!#!   Java: 1.8.0_191 (Java HotSpot(TM) 64-Bit Server VM 25.191-b12)
[02:43:40 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[02:43:40 ERROR]: #!#!
[02:43:40 ERROR]: #!#! Server platform: Spigot
[02:43:40 ERROR]: #!#!
[02:43:40 ERROR]: #!#! Current node: null
[02:43:40 ERROR]: #!#! Current item: Inventory type is equal to "CRAFT" (comparator: ch.njol.skript.classes.data.DefaultComparators$15@7512182c)
[02:43:40 ERROR]: #!#! Current trigger: inventory click (simple event) (system.sk, line 676)
[02:43:40 ERROR]: #!#!
[02:43:40 ERROR]: #!#! Thread: Server thread
[02:43:40 ERROR]: #!#!
[02:43:40 ERROR]: #!#! Language: english
[02:43:40 ERROR]: #!#! Link parse mode: DISABLED
[02:43:40 ERROR]: #!#!
[02:43:40 ERROR]: #!#! End of Error.

### Server Information
1.12.2
bensku skript dev36

**Comment by bensku** [comment]
Follow the instructions in error and test again. Does this happen with latest Skript?

**Comment by Sodies** [comment]
> Follow the instructions in error and test again. Does this happen with latest Skript?
> 
> Edit: Oh. Addon issue, in any case. Report to addon author.

Any idea what addon cause this error?

**Comment by TheBentoBox** [comment]
Looks like Skellett? I see Lime's name in the stack trace. I'd try comparing the inventory type to `crafting table inventory` instead of `"CRAFT"`.
