### ISSUE TITLE
severe error

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1689]
I saw an error in console
[22:24:48] [Server thread/ERROR]: #!#! 
[22:24:48] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[22:24:48] [Server thread/ERROR]: #!#! 
[22:24:48] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[22:24:48] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:24:48] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[22:24:48] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[22:24:48] [Server thread/ERROR]: #!#! 
[22:24:48] [Server thread/ERROR]: #!#! Stack trace:
[22:24:48] [Server thread/ERROR]: #!#! java.lang.ClassCastException: org.bukkit.event.hanging.HangingBreakEvent cannot be cast to org.bukkit.event.hanging.HangingBreakByEntityEvent
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.BukkitEventValues$67.get(BukkitEventValues.java:1)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.EventValues$2.get(EventValues.java:193)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.EventValues$2.get(EventValues.java:1)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.EventValueExpression.getValue(EventValueExpression.java:104)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.EventValueExpression.get(EventValueExpression.java:90)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:112)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:1)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:441)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Variable.getRaw(Variable.java:255)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Variable.get(Variable.java:267)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Variable.getConverted(Variable.java:412)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Variable.getAll(Variable.java:641)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondIsSet.check(CondIsSet.java:75)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondIsSet.check(CondIsSet.java:81)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:51)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[22:24:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110)
[22:24:48] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[22:24:48] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:24:48] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[22:24:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.EntityHanging.move(EntityHanging.java:201)
[22:24:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.TileEntityPiston.f(SourceFile:171)
[22:24:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.TileEntityPiston.Y_(SourceFile:338)
[22:24:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1477)
[22:24:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:614)
[22:24:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1104)
[22:24:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[22:24:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[22:24:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[22:24:48] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[22:24:48] [Server thread/ERROR]: #!#! 
[22:24:48] [Server thread/ERROR]: #!#! Version Information:
[22:24:48] [Server thread/ERROR]: #!#!   Skript: 2.3-beta2 (latest)
[22:24:48] [Server thread/ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[22:24:48] [Server thread/ERROR]: #!#!   Minecraft: 1.13.2
[22:24:48] [Server thread/ERROR]: #!#!   Java: 1.8.0_66 (Java HotSpot(TM) 64-Bit Server VM 25.66-b17)
[22:24:48] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.16.0-1-amd64
[22:24:48] [Server thread/ERROR]: #!#! 
[22:24:48] [Server thread/ERROR]: #!#! Server platform: Paper
[22:24:48] [Server thread/ERROR]: #!#! 
[22:24:48] [Server thread/ERROR]: #!#! Current node: null
[22:24:48] [Server thread/ERROR]: #!#! Current item: {verify::%the player%}(as java.lang.Object) isn't set
[22:24:48] [Server thread/ERROR]: #!#! Current trigger: break (break/place/burn/fade/form of <none>) (antyzlodziej.sk, line 5)
[22:24:48] [Server thread/ERROR]: #!#! 
[22:24:48] [Server thread/ERROR]: #!#! Thread: Server thread
[22:24:48] [Server thread/ERROR]: #!#! 
[22:24:48] [Server thread/ERROR]: #!#! Language: english
[22:24:48] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[22:24:48] [Server thread/ERROR]: #!#! 
[22:24:48] [Server thread/ERROR]: #!#! End of Error.
[22:24:48] [Server thread/ERROR]: #!#! 

Idk why it happened, but works quite good anyway.
Code about error
```
on break:
	if {info} is set:
		player have permission "admin" or "mod"
		cancel event
		delete {info}
		send "%event-block%"
	if {verify::%player%} is not set:
		if event-block is chest:
			cancel event
			execute console command "ban %player% &4Brak weryfikacji &6ub oshawott.pl/vip"
```

**Comment by ham1255** [comment]
yes
i have same when using
```
on place:
 if player have permission "admin.perm":
  cancel event
```
