### ISSUE TITLE
Error with "with lore"

### ISSUE THREAD

**Issue by Zzheyd** [SkriptLang/Skript#1691]
Hi, i can't use 

> Command /freatest:
	trigger:
		open virtual chest with 1 rows named "test lore" to player
		wait 1 tick
		format gui slot 4 of player with bowl named "test" with lore "&atest of lore||&etest too" to run:
			give bowl named "test" with lore "&atest of lore||&etest too" to 

> player

In game on command /freatest, open chest ok, but, no item and this error : 

> WARN 15/11/2018 19:40:47
> 19:40:47[Skript]: Task #1564376 for Skript v2.3-beta2 generated an exception
> Console 15/11/2018 19:40:47
> 19:40:47java.lang.NoSuchMethodError: ch.njol.skript.aliases.ItemType.getItemMeta()Ljava/lang/Object;
> at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:29) ~[?:?]
> at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:1) ~[?:?]
> at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75) ~[?:?]
> at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[?:?]
> at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:60) ~[?:?]
> at ch.njol.skript.lang.util.ConvertedExpression.getSingle(ConvertedExpression.java:150) ~[?:?]
> at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.execute(EffFormatGUI.java:117) ~[?:?]
> at com.github.tukenuke.tuske.util.EffectSection.check(EffectSection.java:54) ~[?:?]
> at ch.njol.skript.lang.Condition.run(Condition.java:56) ~[?:?]
> at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
> at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
> at ch.njol.skript.effects.Delay$1.run(Delay.java:109) ~[?:?]
> at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[Paper-latest.jar:git-Paper-442]
> at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[Paper-latest.jar:git-Paper-442]
> at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[Paper-latest.jar:git-Paper-442]
> at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[Paper-latest.jar:git-Paper-442]
> at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[Paper-latest.jar:git-Paper-442]
> at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[Paper-latest.jar:git-Paper-442]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

My skript's version: 2.3-beta2
My server's version: 1.13.2 (latest version of paper spigot)

**Comment by nikkedoy98** [comment]
Problem is with SkQuery, because skript nowadays has own "with lore".

Switch to TuSKe or wait SkQuery to update.

Peace.

**Comment by nikkedoy98** [comment]
Take SkQuery out and use TuSKe 1.8.3 (No fork).

It works fine for me.

**Comment by Zzheyd** [comment]
Hum i see thx, but can't make new line ? with || in lore ?

**Comment by Efnilite** [comment]
Syntax changed:
`with lore "line1||line2"` to
`with lore "line1" and "line2"`
