### ISSUE TITLE
My server won't start anymore (Skript Variable issues) since updating to latest version

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#1697]
Skript version: Skript] Enabling Skript v2.3-beta2
PaperSpigot version: 1.12.2

Console error on startup:
https://hastebin.com/waqezopuso.md

The message appears again and again in the console:
Loaded 280 variables so far...
But it does not continue...

**Comment by bensku** [comment]
It is probably a bug in code that updates old variables to new item format.

**Comment by bloggy** [comment]
And how to fix it?

**Comment by bensku** [comment]
It appears that music discs are causing trouble when saved to variable database.

**Comment by TheBentoBox** [comment]
@bensku This could be related to IDs because, before 1.13 when numeric IDs still existed, music discs occupied IDs 2256 - 2267. Don't ask me why they used such large numbers, but that's how they always were. The out of bounds exception is for something accessing index 2256 which is within that range. 

Is there anywhere in the code that instantiates an array where the index is meant to represent an item ID, and it's being instantiated to a size like 1000 or something? Pretty sure I remember seeing arrays instantiated to 1000 length somewhere in the aliases or variable code but not sure if any of it was used in relation to item IDs.

**Comment by bensku** [comment]
Id mappings that could be used exist in Skript repository. However, they're for some reason missing the music discs... That needs to be fixef before code using them is actually useful.

Currently, Skript just takes Material enum values. That was never meant to be a permanent solution.

**Comment by bloggy** [comment]
Hi there,
I just tried to start my server again (this time with another, younger version of my variables database file). And I get more errors, I thought they could be useful for you to see what's going on:
https://hastebin.com/horederuno.sql

**Comment by TheLimeGlass** [comment]
The issue looks the same as the first.

Also posting this here since hastebin will expire 
```
hread/ERROR]: #!#! Stack trace:
[08:03:36] [Server thread/ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: 2263
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.aliases.ItemType.deserialize(ItemType.java:1032)
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.YggdrasilSerializer.deserialize(YggdrasilSerializer.java:44)
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.YggdrasilSerializer.deserialize(YggdrasilSerializer.java:1)
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilInputStream.readObject(YggdrasilInputStream.java:203)
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilInputStream.readObject(YggdrasilInputStream.java:139)
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.deserialize(Classes.java:759)
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.deserialize(Classes.java:740)
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.DatabaseStorage$5.call(DatabaseStorage.java:647)
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.DatabaseStorage$5.call(DatabaseStorage.java:1)
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.Task.callSync(Task.java:167)
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.Task.callSync(Task.java:151)
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.DatabaseStorage.loadVariables(DatabaseStorage.java:619)
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.DatabaseStorage.load_i(DatabaseStorage.java:237)
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.VariablesStorage.load(VariablesStorage.java:165)
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.Variables.load(Variables.java:193)
[08:03:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:496)
[08:03:36] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63)
[08:03:36] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[08:03:36] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008)
[08:03:36] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[08:03:36] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[08:03:36] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[08:03:36] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[08:03:36] [Server thread/ERROR]: #!#! 
[08:03:36] [Server thread/ERROR]: #!#! Version Information:
[08:03:36] [Server thread/ERROR]: #!#!   Skript: 2.3-beta1
[08:03:36] [Server thread/ERROR]: #!#!   Bukkit: 1.13.1-R0.1-SNAPSHOT
[08:03:36] [Server thread/ERROR]: #!#!   Minecraft: 1.13.1
[08:03:36] [Server thread/ERROR]: #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
[08:03:36] [Server thread/ERROR]: #!#!   OS: Windows 8.1 amd64 6.3
[08:03:36] [Server thread/ERROR]: #!#! 
[08:03:36] [Server thread/ERROR]: #!#! Server platform: Paper
[08:03:36] [Server thread/ERROR]: #!#! 
[08:03:36] [Server thread/ERROR]: #!#! Current node: null
[08:03:36] [Server thread/ERROR]: #!#! Current item: null
[08:03:36] [Server thread/ERROR]: #!#! 
[08:03:36] [Server thread/ERROR]: #!#! Thread: Server thread
[08:03:36] [Server thread/ERROR]: #!#! 
[08:03:36] [Server thread/ERROR]: #!#! Language: english
[08:03:36] [Server thread/ERROR]: #!#! Link parse mode: STRICT
[08:03:36] [Server thread/ERROR]: #!#! 
[08:03:36] [Server thread/ERROR]: #!#! End of Error.
```

**Comment by bloggy** [comment]
It also happens with the latest skript version.

**Comment by bensku** [comment]
Fix is probably coming before next stable release. It is not higher priority than that because few people save items to variables.

**Comment by bensku** [comment]
People just don't store them, I think.
