### ISSUE TITLE
Exception in thread Skript database ... Something went horribly wrong ...

### ISSUE THREAD

**Issue by leejosepho** [SkriptLang/Skript#1704]
Running paperclip-460.jar (1.13.2)

I believe the following is new for me, but I do not know when it started.

[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! 
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! [Skript] Severe Error:
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! Exception in thread Skript database 'database 1' monitor thread
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! 
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! Something went horribly wrong with Skript.
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! 
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! Stack trace:
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! java.lang.IllegalArgumentException: Task must be Runnable or Consumer
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#!     at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:512)
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.callSyncMethod(CraftScheduler.java:233)
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#!     at ch.njol.skript.util.Task.callSync(Task.java:172)
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#!     at ch.njol.skript.util.Task.callSync(Task.java:151)
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#!     at ch.njol.skript.variables.DatabaseStorage.loadVariables(DatabaseStorage.java:619)
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#!     at ch.njol.skript.variables.DatabaseStorage.checkDatabase(DatabaseStorage.java:568)
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#!     at ch.njol.skript.variables.DatabaseStorage$3.run(DatabaseStorage.java:356)
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! 
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! Version Information:
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#!   Skript: 2.3-beta2
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#!   Minecraft: 1.13.2
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#!   Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#!   OS: Linux amd64 3.2.0-4-amd64
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! 
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! Server platform: Paper
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! 
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! Current node: null
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! Current item: null
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! 
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! Thread: Skript database 'database 1' monitor thread
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! 
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! Language: english
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! Link parse mode: STRICT
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! 
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#! End of Error.
[11:33:50] [Skript database 'database 1' monitor thread/ERROR]: #!#!

**Comment by bensku** [comment]
What kind of database you're using for variable storage?

**Comment by leejosepho** [comment]
# ==== Variables ====

databases:

	database 1:
		type: MySQL

	# MySQL Database:
		host: 104.128.52.226
		port: 3306
		user: myusername
		password: mypassword
		database: mydatabase
		table: SkriptVars
		monitor changes: true
		monitor interval: 20 seconds

**Comment by bensku** [comment]
Looks like this was a Spigot bug that has since been fixed: https://hub.spigotmc.org/jira/browse/SPIGOT-4500.
