### ISSUE TITLE
Server Error with newest Skript version

### ISSUE THREAD

**Issue by KleeSup** [SkriptLang/Skript#1705]
Skript says I must download a new Version of Skript but now I get this error with the new Version in the console:

Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard

        at ch.njol.skript.hooks.regions.WorldGuardHook.getRegion_i(WorldGuardHook.java:211) ~[?:?]

        at ch.njol.skript.hooks.regions.RegionsPlugin.getRegion(RegionsPlugin.java:103) ~[?:?]

        at ch.njol.skript.hooks.regions.classes.Region$1.parse(Region.java:82) ~[?:?]

        at ch.njol.skript.hooks.regions.classes.Region$1.parse(Region.java:1) ~[?:?]

        at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:421) ~[?:?]

        at ch.njol.skript.registrations.Classes.parse(Classes.java:450) ~[?:?]

        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:95) ~[?:?]

        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:84) ~[?:?]

        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) ~[?:?]

        at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:165) ~[?:?]

        at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:124) ~[?:?]

        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252) ~[?:?]

        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179) ~[?:?]

        at ch.njol.skript.lang.Condition.parse(Condition.java:81) ~[?:?]

        at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1064) ~[?:?]

        at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54) ~[?:?]

        at ch.njol.skript.lang.Conditional$1.<init>(Conditional.java:72) ~[?:?]

        at ch.njol.skript.lang.Conditional.loadElseClause(Conditional.java:72) ~[?:?]

        at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1044) ~[?:?]

        at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54) ~[?:?]

        at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44) ~[?:?]

        at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1071) ~[?:?]

        at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54) ~[?:?]

        at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44) ~[?:?]

        at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1071) ~[?:?]

        at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:50) ~[?:?]

        at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:143) ~[?:?]

        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:643) ~[?:?]

        at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:392) ~[?:?]

        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:404) ~[?:?]

        at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:334) ~[?:?]

        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:364) ~[?:?]

        at ch.njol.skript.Skript.reload(Skript.java:865) ~[?:?]

        at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:154) ~[?:?]

        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-3d850ec-809c399]

All my Skripts are now disabled and the /sk command Drops Errors!!!
Can anyone help me please?!?!

**Comment by ShaneBeee** [comment]
Downgrade your skript back to dec37c
This is because 2.3beta builds require world guard 7

**Comment by KleeSup** [comment]
Yes but if I Do this Skript says I must Upgrade it and then Skript was disabled. What can I Do? Sorry for my bad English

**Comment by iOshawott** [comment]
Don't use latest skript od you don't need to. Downgrade Your skript to dev37c

**Comment by Efnilite** [comment]
> Yes but if I Do this Skript says I must Upgrade it and then Skript was disabled. What can I Do? Sorry for my bad English

Skript doesn't say you MUST upgrade, it just says that there's a new version available. Just ignore it and you'll be fine 👍

**Comment by bensku** [comment]
See #1523 for details about updater. Updating it is planned, but won't help with this issue.

Some improvements for WorldGuard support are coming in next release, but WorldGuard 6 is unlikely to be supported.
