### ISSUE TITLE
Head/skull error

### ISSUE THREAD

**Issue by andrei923** [SkriptLang/Skript#1715]
### Steps to Reproduce

```
command head:
	trigger:
		give player's skull to player
```

### Errors / Screenshots
```

[12:45:51 ERROR]: #!#!
[12:45:51 ERROR]: #!#! [Skript] Severe Error:
[12:45:51 ERROR]: #!#!
[12:45:51 ERROR]: #!#! Something went horribly wrong with Skript.
[12:45:51 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[12:45:51 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[12:45:51 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[12:45:51 ERROR]: #!#!
[12:45:51 ERROR]: #!#! Stack trace:
[12:45:51 ERROR]: #!#! java.lang.UnsupportedOperationException: 1.13 update
[12:45:51 ERROR]: #!#!     at ch.njol.skript.expressions.ExprSkull.convert(ExprSkull.java:104)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.expressions.ExprSkull.convert(ExprSkull.java:1)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:342)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:333)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:104)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.expressions.base.SimplePropertyExpression.get(SimplePropertyExpression.java:55)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:278)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:286)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:243)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:257)
[12:45:51 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:172)
[12:45:51 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:45:51 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:45:51 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:45:51 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
[12:45:51 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[12:45:51 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:45:51 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[12:45:51 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[12:45:51 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1640)
[12:45:51 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483)
[12:45:51 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:45:51 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12:45:51 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[12:45:51 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:45:51 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:45:51 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[12:45:51 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[12:45:51 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[12:45:51 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[12:45:51 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[12:45:51 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[12:45:51 ERROR]: #!#!
[12:45:51 ERROR]: #!#! Version Information:
[12:45:51 ERROR]: #!#!   Skript: 2.3-beta3
[12:45:51 ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[12:45:51 ERROR]: #!#!   Minecraft: 1.13.2
[12:45:51 ERROR]: #!#!   Java: 1.8.0_191 (Java HotSpot(TM) 64-Bit Server VM 25.191-b12)
[12:45:51 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[12:45:51 ERROR]: #!#!
[12:45:51 ERROR]: #!#! Server platform: Spigot
[12:45:51 ERROR]: #!#!
[12:45:51 ERROR]: #!#! Current node: null
[12:45:51 ERROR]: #!#! Current item: add the skull of the player to the player
[12:45:51 ERROR]: #!#! Current trigger: command /head (simple event) (test.sk, line -1)
[12:45:51 ERROR]: #!#!
[12:45:51 ERROR]: #!#! Thread: Server thread
[12:45:51 ERROR]: #!#!
[12:45:51 ERROR]: #!#! Language: english
[12:45:51 ERROR]: #!#! Link parse mode: DISABLED
[12:45:51 ERROR]: #!#!
[12:45:51 ERROR]: #!#! End of Error.
[12:45:51 ERROR]: #!#!

```
### Server Information
* **Server version/platform:**       spigot 1.13.2
* **Skript version:**                2.3- Beta2/Beta3

**Comment by weberlepecheur** [comment]
Custom skull/head was disabled since 2.3 when I check the commit for ExprSkull.java
