### ISSUE TITLE
PLugin don't works. - bukkit 1.12

### ISSUE THREAD

**Issue by tarzinio** [SkriptLang/Skript#1716]
### Errors / Screenshots

I do not have a plugin. It does not respond to any of the commands, for example / sk reload <skript>. Nothing is displayed in the chat.

https://zapodaj.net/images/48524b694c9c8.png

 
### Server Information
* **Server version/platform:** Bukkit (on minecraft version 1.12)

**Comment by TheBentoBox** [comment]
We need to see what errors the plugin is giving you when the server starts up to be able to help

**Comment by tarzinio** [comment]
There are no errors in the console. Does the plugin have any logs? I will send them.

**Comment by Efnilite** [comment]
Can you give your Skript version? `/ver Skript` btw

**Comment by TheBentoBox** [comment]
Yes, there will be error logs in the console on startup if the plugin isn't working. What version of Skript do you have installed?

**Comment by tarzinio** [comment]
version: 2.3-beta4. Where can I find a file with logs (errors)

**Comment by TheBentoBox** [comment]
In your server's logs directory, or in the console when your server starts up.

**Comment by Padlick01** [comment]
I have the same problem. There are no errors, no entries from Skript in the logs. Just nothing. It fully works as it should in the 1.13, but 1.12 doesn't.

**Comment by tarzinio** [comment]
This is the last file.

`[07:59:32] [Server thread/INFO]: Starting minecraft server version 1.12
[07:59:32] [Server thread/INFO]: Loading properties
[07:59:32] [Server thread/INFO]: Default game type: SURVIVAL
[07:59:32] [Server thread/INFO]: Generating keypair
[07:59:32] [Server thread/INFO]: Starting Minecraft server on *:25565
[07:59:32] [Server thread/INFO]: Using epoll channel type
[07:59:33] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[07:59:33] [Server thread/INFO]: [PermissionsEx] Loading PermissionsEx v1.23.4
[07:59:33] [Server thread/WARN]: [PermissionsEx] This server is in offline mode. Unless this server is configured to integrate with a supported proxy (see http://dft.ba/-8ous), UUIDs *may not be stable*!
[07:59:33] [Server thread/INFO]: [ClearLag] Loading ClearLag v2.9.7
[07:59:33] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1.9;caf0ad9
[07:59:33] [Server thread/INFO]: [EasySetSpawn] Loading EasySetSpawn v3.2
[07:59:33] [Server thread/INFO]: [LockChest] Loading LockChest v1.5
[07:59:33] [Server thread/INFO]: [ServerMinimap] Loading ServerMinimap v0.7.15
[07:59:33] [Server thread/INFO]: [CS-CoreLib] Loading CS-CoreLib vv1.5.18
[07:59:33] [Server thread/INFO]: [Skript] Loading Skript v2.3-beta4
[07:59:33] [Server thread/INFO]: [Slimefun] Loading Slimefun v4.1.14
[07:59:33] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.4.0
[07:59:34] [Server thread/INFO]: [Orebfuscator4] Loading Orebfuscator4 v4.3.3
[07:59:34] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.4.0
[07:59:34] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[07:59:34] [Server thread/INFO]: [Orebfuscator4] Enabling Orebfuscator4 v4.3.3
[07:59:34] [Server thread/INFO]: [OFC] World type 'Default' has been read.
[07:59:34] [Server thread/INFO]: [OFC] World type 'Normal' has been read.
[07:59:34] [Server thread/INFO]: [OFC] World type 'TheEnd' has been read.
[07:59:34] [Server thread/INFO]: [OFC] World type 'Nether' has been read.
[07:59:34] [Server thread/INFO]: [OFC] Proximity Hider is Enabled
[07:59:34] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[07:59:34] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[07:59:34] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[07:59:34] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[07:59:34] [Server thread/INFO]: Preparing level "world"
[07:59:35] [Server thread/INFO]: Preparing start region for level 0 (Seed: -7881503311507746506)
[07:59:36] [Server thread/INFO]: Preparing spawn area: 0%
[07:59:37] [Server thread/INFO]: Preparing spawn area: 26%
[07:59:38] [Server thread/INFO]: Preparing spawn area: 66%
[07:59:39] [Server thread/INFO]: Preparing start region for level 1 (Seed: -7881503311507746506)
[07:59:40] [Server thread/INFO]: Preparing spawn area: 61%
[07:59:40] [Server thread/INFO]: Preparing start region for level 2 (Seed: -7881503311507746506)
[07:59:41] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.4
[07:59:41] [Server thread/INFO]: [PermissionsEx] Initializing file backend
[07:59:41] [Server thread/INFO]: [PermissionsEx] Permissions file successfully reloaded
[07:59:41] [Server thread/INFO]: [ClearLag] Enabling ClearLag v2.9.7
[07:59:41] [Server thread/INFO]: [ClearLag] Loading modules...
[07:59:41] [Server thread/INFO]: [ClearLag] Modules enabed, loading config values
[07:59:41] [Server thread/INFO]: [ClearLag] Modules have been loaded!
[07:59:41] [Server thread/INFO]: [ClearLag] Clearlag is now enabled!
[07:59:41] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.9;caf0ad9
[07:59:41] [Thread-8/INFO]: [ClearLag] Checking for updates compatible with your bukkit version [1.12]...
[07:59:43] [Server thread/INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
[07:59:43] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R1 as the Bukkit adapter
[07:59:43] [Server thread/INFO]: [EasySetSpawn] Enabling EasySetSpawn v3.2
[07:59:43] [Server thread/INFO]: [EasySetSpawn] EasySetSpawn enabled!
[07:59:43] [Server thread/INFO]: [LockChest] Enabling LockChest v1.5
[07:59:43] [Server thread/INFO]: [LockChest] Using config-1.5.yml as main config file
[07:59:43] [Server thread/INFO]: [LockChest] Detected Bukkit Version: 1.12
[07:59:43] [Server thread/INFO]: [LockChest] Getting Tags ready...
[07:59:43] [Server thread/INFO]: [LockChest] Tags are ready!
[07:59:43] [Server thread/INFO]: [LockChest] Set up language file successfully!
[07:59:43] [Server thread/INFO]: [LockChest] Language set to English by obstem7 successfully!
[07:59:43] [Server thread/INFO]: [LockChest] LockChest v.1.5 has been enabled!
[07:59:43] [Server thread/INFO]: [ServerMinimap] Enabling ServerMinimap v0.7.15
[07:59:43] [Server thread/INFO]: [ServerMinimap] Created Minimap with ID 0. Use /give <name> MAP 1 0 to get the map as item. (Vanilla command)
[07:59:43] [Server thread/INFO]: [ServerMinimap] Alternative command: /minimap (Plugin command)
[07:59:43] [Server thread/INFO]: [CS-CoreLib] Enabling CS-CoreLib vv1.5.18
[07:59:44] [Server thread/INFO]: [Skript] Enabling Skript v2.3-beta4
[07:59:44] [Thread-8/INFO]: [ClearLag] No updates found!
[07:59:44] [Server thread/ERROR]: [Skript] It seems that this server platform (CraftBukkit) does not work with Skript.
[07:59:44] [Server thread/ERROR]: [Skript] To prevent potentially unsafe behaviour, Skript has been disabled.
[07:59:44] [Server thread/ERROR]: [Skript] You may re-enable it by adding a configuration option 'allow unsafe platforms: true'
[07:59:44] [Server thread/ERROR]: [Skript] Note that it is unlikely that Skript works correctly even if you do so.
[07:59:44] [Server thread/ERROR]: [Skript] A better idea would be to install Paper or Spigot in place of your current server.
[07:59:44] [Server thread/INFO]: [Slimefun] Enabling Slimefun v4.1.14
[07:59:44] [Server thread/INFO]: [Slimefun] Loading Files...
[07:59:44] [Server thread/INFO]: [Slimefun] Loading Config...
[07:59:44] [Server thread/INFO]: [Slimefun] Loading Items...
[07:59:46] [Server thread/INFO]: [Slimefun] Loading Researches...
[07:59:46] [Server thread/INFO]: [Slimefun] Loading World Generators...
[07:59:46] [Server thread/INFO]: [Slimefun - GEO] Registering Ore Gen: Oil
[07:59:46] [Server thread/INFO]: [Slimefun - GEO] Registering Ore Gen: Nether Ice
[07:59:46] [Server thread/INFO]: [Slimefun] Successfully hooked into WorldEdit!
[07:59:46] [Server thread/INFO]: [Slimefun] Finished!
[07:59:46] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[07:59:46] [Server thread/INFO]: Done (12.146s)! For help, type "help" or "?"
[07:59:46] [Server thread/INFO]: [0;33;1m###################### - Slimefun - ######################[m
[07:59:46] [Server thread/INFO]: [0;33;1mSuccessfully loaded 465 Items (225 Researches)[m
[07:59:46] [Server thread/INFO]: [0;33;1m( 465 Items from Slimefun, 0 Items from Addons )[m
[07:59:46] [Server thread/INFO]: [0;33;1m##########################################################[m
[07:59:47] [Server thread/INFO]: [Slimefun] Loading Blocks for World "world"
[07:59:47] [Server thread/INFO]: [Slimefun] This may take a long time...
[07:59:47] [Server thread/INFO]: [Slimefun] Loading Blocks... 100% (FINISHED - 0ms)
[07:59:47] [Server thread/INFO]: [Slimefun] Loaded a total of 0 Blocks for World "world"
[07:59:47] [Server thread/INFO]: [Slimefun] Loading Blocks for World "world_nether"
[07:59:47] [Server thread/INFO]: [Slimefun] This may take a long time...
[07:59:47] [Server thread/INFO]: [Slimefun] Loading Blocks... 100% (FINISHED - 0ms)
[07:59:47] [Server thread/INFO]: [Slimefun] Loaded a total of 0 Blocks for World "world_nether"
[07:59:47] [Server thread/INFO]: [Slimefun] Loading Blocks for World "world_the_end"
[07:59:47] [Server thread/INFO]: [Slimefun] This may take a long time...
[07:59:47] [Server thread/INFO]: [Slimefun] Loading Blocks... 100% (FINISHED - 0ms)
[07:59:47] [Server thread/INFO]: [Slimefun] Loaded a total of 0 Blocks for World "world_the_end"
[07:59:48] [Thread-12/INFO]: [CS-CoreLib - Updater] Slimefun is outdated!
[07:59:48] [Thread-11/INFO]: [CS-CoreLib - Updater] CS-CoreLib is up to date!
[07:59:48] [Thread-12/INFO]: [CS-CoreLib - Updater] Downloading Slimefun v4.1.15
[07:59:52] [Server thread/INFO]: https://media.forgecdn.net/files/2558/769/Slimefun+v4.1.15.jar
[07:59:52] [Server thread/WARN]:  
[07:59:52] [Server thread/WARN]: #################### - ERROR - ####################
[07:59:52] [Server thread/WARN]: Could not auto-update Slimefun
[07:59:52] [Server thread/WARN]: #################### - ERROR - ####################
[07:59:52] [Server thread/WARN]:  
[07:59:52] [Server thread/WARN]: java.io.FileNotFoundException: plugins/update/Slimefun+v4.1.14.jar (No such file or directory)
[07:59:52] [Server thread/WARN]: 	at java.io.FileOutputStream.open0(Native Method)
[07:59:52] [Server thread/WARN]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[07:59:52] [Server thread/WARN]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[07:59:52] [Server thread/WARN]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[07:59:52] [Server thread/WARN]: 	at me.mrCookieSlime.CSCoreLibPlugin.updater.Updater$UpdaterTask$1.run(Updater.java:165)
[07:59:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:53)
[07:59:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[07:59:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:689)
[07:59:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:370)
[07:59:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:650)
[07:59:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:554)
[07:59:52] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[07:59:52] [Server thread/WARN]:  
[07:59:52] [Server thread/WARN]: #################### - UPDATE - ####################
[07:59:52] [Server thread/WARN]: Slimefun was successfully updated (4.1.14 -> 4.1.15)
[07:59:52] [Server thread/WARN]: Please restart your Server in order to use the new Version
[07:59:52] [Server thread/WARN]:  
[07:59:51] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4047ms behind, skipping 80 tick(s)
`

**Comment by HYPExMon5ter** [comment]
Well, first of all, you’re using bukkit, Skript doesn’t support bukkit. Use spigot or paperspigot (I’d recommend paper), also, the latest Skript version is for 1.13 currently, downgrade to dev37c

**Comment by tarzinio** [comment]
After all, the plugin is this engine. 
scr.hu/8pwa/yltcp

**Comment by tarzinio** [comment]
OK.
Now I have in the logs:

```
[08:43:40] [Server thread/ERROR]: [Skript] It seems that this server platform (CraftBukkit) does not work with Skript.
[08:43:40] [Server thread/ERROR]: [Skript] To prevent potentially unsafe behaviour, Skript has been disabled.
[08:43:40] [Server thread/ERROR]: [Skript] You may re-enable it by adding a configuration option 'allow unsafe platforms: true'
[08:43:40] [Server thread/ERROR]: [Skript] Note that it is unlikely that Skript works correctly even if you do so.
[08:43:40] [Server thread/ERROR]: [Skript] A better idea would be to install Paper or Spigot in place of your current server.
```

Will install the newest version and see again.

**Comment by tarzinio** [comment]
I have the latest version. ( releases 537b53c ).

@HYPExMon5ter -  the dev37c version is much older.

**Comment by Snow-Pyon** [comment]
Skript doesn't work with Craftbukkit, use Paper (recommended, https://papermc.io/downloads) or Spigot (Gotta build it with BuildTools).

**Comment by HYPExMon5ter** [comment]
Oh okay, I thought anything below 1.13 was still a wip lol, sorry about that @bensku
