### ISSUE TITLE
Skript Severe Error

### ISSUE THREAD

**Issue by DeepNetworks** [SkriptLang/Skript#1724]
I know my Skript is not latest version. but I have a lot of scripts 
And I can't update my Skript right now.. it take time.
(they're not compatible with latest Skript version)

### Description

It says 'Severe Error' and makes a lot of lag
### Steps to Reproduce

I can't find it
### Expected Behavior

I can't find it
### Errors / Screenshots

[13:46:41] [Server thread/ERROR]: #!#!
[13:46:41] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[13:46:41] [Server thread/ERROR]: #!#!
[13:46:41] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[13:46:41] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:46:41] [Server thread/ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[13:46:41] [Server thread/ERROR]: #!#! You may download new version of Skript at https://github.com/SkriptLang/Skript/releases
[13:46:41] [Server thread/ERROR]: #!#! You will be given instructions how to report this error if it persists with latest Skript.
[13:46:41] [Server thread/ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[13:46:41] [Server thread/ERROR]: #!#!
[13:46:41] [Server thread/ERROR]: #!#! Stack trace:
[13:46:41] [Server thread/ERROR]: #!#! java.lang.IndexOutOfBoundsException: Index: 0
[13:46:41] [Server thread/ERROR]: #!#!     at java.util.Collections$EmptyList.get(Collections.java:4454)
[13:46:41] [Server thread/ERROR]: #!#!     at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:101)
[13:46:41] [Server thread/ERROR]: #!#!     at net.fusionlord.bukkit.skmcmmo.experssions.GetSkillLevel.get(GetSkillLevel.java:24)
[13:46:41] [Server thread/ERROR]: #!#!     at net.fusionlord.bukkit.skmcmmo.experssions.GetSkillLevel.get(GetSkillLevel.java:14)
[13:46:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:161)
[13:46:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:258)
[13:46:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
[13:46:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:52)
[13:46:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[13:46:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[13:46:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[13:46:41] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110)
[13:46:41] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[13:46:41] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:46:41] [Server thread/ERROR]: #!#!     at com.heirteir.perworldpluginspremium.registeredlisteners.BukkitRegisteredListener.callEvent(BukkitReg
isteredListener.java:35)
[13:46:41] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:46:41] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:46:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[13:46:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[13:46:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[13:46:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[13:46:41] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[13:46:41] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[13:46:41] [Server thread/ERROR]: #!#!
[13:46:41] [Server thread/ERROR]: #!#! Version Information:
[13:46:41] [Server thread/ERROR]: #!#!   Skript: 2.2-dev37c (OUTDATED)
[13:46:41] [Server thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[13:46:41] [Server thread/ERROR]: #!#!   Minecraft: 1.12.2
[13:46:41] [Server thread/ERROR]: #!#!   Java: 1.8.0_181 (OpenJDK 64-Bit Server VM 25.181-b13)
[13:46:41] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.10.0-862.14.4.el7.x86_64
[13:46:41] [Server thread/ERROR]: #!#!
[13:46:41] [Server thread/ERROR]: #!#! Server platform: Paper
[13:46:41] [Server thread/ERROR]: #!#!
[13:46:41] [Server thread/ERROR]: #!#! Current node: null
[13:46:41] [Server thread/ERROR]: #!#! Current item: Get a player's Fishing level. is greater than or equal to [[long:1800]] (comparator: ch.njol.skript.classes.data.DefaultComparators$1@1802528a)
[13:46:41] [Server thread/ERROR]: #!#! Current trigger: Fishing (simple event) (sa1r_fishing.sk, line 122)
[13:46:41] [Server thread/ERROR]: #!#!
[13:46:41] [Server thread/ERROR]: #!#! Thread: Server thread
[13:46:41] [Server thread/ERROR]: #!#!
[13:46:41] [Server thread/ERROR]: #!#! Language: english
[13:46:41] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[13:46:41] [Server thread/ERROR]: #!#!
[13:46:41] [Server thread/ERROR]: #!#! End of Error.
[13:46:41] [Server thread/ERROR]: #!#!

**Comment by Blueyescat** [comment]
This is a problem with the skMcMMO addon you are using, and it is a dead addon so you can't get support. You can use [SharpSK](https://github.com/Sharpjaws/SharpSK/releases) instead: https://docs.skunity.com/syntax/expressions/mcMMO%20Skill%20level%20of%20Player%20
```vb
if fishing level of player is greater than or equal to 1800:
```
