### ISSUE TITLE
Found an error in 1.13.2

### ISSUE THREAD

**Issue by axemwa** [SkriptLang/Skript#1740]
### Errors / Screenshots
Found a bunch of warns in latest plugin version and mc 1.13.2

The errors - https://pastebin.com/hT9cVuti

### Server Information
* **Server version/platform:** Paper-475 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
* **Skript version:**                Skript version 2.2-dev37c

**Comment by axemwa** [comment]
Another error
`[03:21:01] [Server thread/ERROR]: Error occurred while enabling Skript-Paper v1.1.0 (Is it up to date?)
java.lang.NullPointerException: null
	at ch.njol.skript.Skript.registerAddon(Skript.java:969) ~[?:?]
	at tk.shanebee.skriptpaper.SkriptPaper.onEnable(SkriptPaper.java:22) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-475]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-475]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-475]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-475]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-475]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]`

**Comment by Snow-Pyon** [comment]
You're using an old version of Skript and that last stack trace doesn't come from Skript, it is from an addon (skript-paper).

**Comment by axemwa** [comment]
Oh whoops someone directed my to the wrong version (https://github.com/SkriptLang/Skript/releases/tag/dev37c), thanks
