### ISSUE TITLE
[Skript] Severe Error: Could not load AnimatedWorld.sk

### ISSUE THREAD

**Issue by dhgameryt** [SkriptLang/Skript#1751]
[Skript] Severe Error:
 Could not load AnimatedWorld.sk
 
 Something went horribly wrong with Skript.
 This issue is NOT your fault! You probably can't fix it yourself, either.
 You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
 This ensures that your issue is noticed and will be fixed as soon as possible.
 
 Stack trace:
 java.lang.NullPointerException
     at ch.njol.skript.hooks.economy.classes.Money.parse(Money.java:160)
     at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:57)
     at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:1)
     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:421)
     at ch.njol.skript.registrations.Classes.parse(Classes.java:460)
     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:365)
     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:638)
     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:628)
     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:995)
     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:50)
     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:143)
     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:634)
     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:390)
     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:402)
     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:332)
     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:362)
     at ch.njol.skript.Skript.reloadScripts(Skript.java:869)
     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:158)
     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732)
     at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1799)
     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1602)
     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
     at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109)
     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016)
     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
     at java.lang.Thread.run(Thread.java:748)
 
 Version Information:
   Skript: 2.3-beta4 (latest)
   Bukkit: 1.13.2-R0.1-SNAPSHOT
   Minecraft: 1.13.2
   Java: 1.8.0_191 (OpenJDK 64-Bit Server VM 25.191-b12)
   OS: Linux amd64 4.19.4-1.el7.elrepo.x86_64
 
 Server platform: Paper
 
 Current node: loop blocks within {create.pos1.%{_t}%} to {create.pos2.%{_t}%}: (AnimatedWorld.sk, line 34)
 Current item: null
 
 Thread: Server thread
 
 Language: english
 Link parse mode: DISABLED
 
 End of Error.

**Comment by Blueyescat** [comment]
What economy plugin are you using?

**Comment by dhgameryt** [comment]
Saneeconomy and Vault last release

**Comment by bensku** [comment]
Looks like a bug in Vault and/or SaneEconomy, but I "fixed" it anyway.
