### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Duartteno** [SkriptLang/Skript#1756]
```
"Craft Scheduler Thread - 1322" #4957 prio=5 os_prio=0 tid=0x00007f1244018000 nid=0x5973 runnable [0x00007f12666e5000]
   java.lang.Thread.State: RUNNABLE
	at java.util.WeakHashMap.get(WeakHashMap.java:403)
	at ch.njol.skript.variables.Variables.setVariable(Variables.java:352)
	at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:84)
	at ch.njol.skript.lang.function.Function.execute(Function.java:119)
	at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:204)
	at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:53)
	at ch.njol.skript.lang.Effect.run(Effect.java:52)
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
	at com.pie.tlatoani.Miscellaneous.Thread.ScopeAsync.lambda$go$0(ScopeAsync.java:46)
	at com.pie.tlatoani.Miscellaneous.Thread.ScopeAsync$$Lambda$719/1192793111.run(Unknown Source)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bensku** [comment]
You didn't post Skript version. Luckily, from stack trace I can see it is outdated (use of WeakHashMap). Use latest Skript when reporting issues.
