### ISSUE TITLE
Facing of block causes Severe Error

### ISSUE THREAD

**Issue by AsDsDD** [SkriptLang/Skript#1792]
### Description
The facing expressions seems to be broken. I can't get it to work.

### Expected Behavior
The code returning facing of the block.

### Errors / Screenshots

> [12:12:54 ERROR]: #!#!
[12:12:54 ERROR]: #!#! [Skript] Severe Error:
[12:12:54 ERROR]: #!#!
[12:12:54 ERROR]: #!#! Something went horribly wrong with Skript.
[12:12:54 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[12:12:54 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[12:12:54 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[12:12:54 ERROR]: #!#!
[12:12:54 ERROR]: #!#! Stack trace:
[12:12:54 ERROR]: #!#! java.lang.IllegalArgumentException: Cannot get new data of Modern Material
[12:12:54 ERROR]: #!#!     at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[12:12:54 ERROR]: #!#!     at org.bukkit.Material.getNewData(Material.java:3103)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.expressions.ExprFacing.convert(ExprFacing.java:70)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.expressions.ExprFacing.convert(ExprFacing.java:1)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:342)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:333)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:104)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.expressions.base.SimplePropertyExpression.get(SimplePropertyExpression.java:55)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:453)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:617)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:1)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:66)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:280)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:213)
[12:12:54 ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:1)
[12:12:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftFuture.run(CraftFuture.java:85)
[12:12:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448)
[12:12:54 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1002)
[12:12:54 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[12:12:54 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:937)
[12:12:54 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:835)
[12:12:54 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[12:12:54 ERROR]: #!#!
[12:12:54 ERROR]: #!#! Version Information:
[12:12:54 ERROR]: #!#!   Skript: 2.3-beta7 (latest)
[12:12:54 ERROR]: #!#!     Flavor: skriptlang-github
[12:12:54 ERROR]: #!#!     Timestamp: 2018-12-31
[12:12:54 ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[12:12:54 ERROR]: #!#!   Minecraft: 1.13.2
[12:12:54 ERROR]: #!#!   Java: 1.8.0_181 (Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
[12:12:54 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[12:12:54 ERROR]: #!#!
[12:12:54 ERROR]: #!#! Server platform: Paper
[12:12:54 ERROR]: #!#!
[12:12:54 ERROR]: #!#! Current node: null
[12:12:54 ERROR]: #!#! Current item: broadcast "%the facing of the targeted block of event-player%"
[12:12:54 ERROR]: #!#!
[12:12:54 ERROR]: #!#! Thread: Server thread
[12:12:54 ERROR]: #!#!
[12:12:54 ERROR]: #!#! Language: english
[12:12:54 ERROR]: #!#! Link parse mode: DISABLED
[12:12:54 ERROR]: #!#!
[12:12:54 ERROR]: #!#! End of Error.
[12:12:54 ERROR]: #!#!

![2019-01-04_12 12 55](https://user-images.githubusercontent.com/19997813/50683701-a894db80-101b-11e9-9426-1b19a5f0e5cd.png)
### Server Information
* **Server version/platform:** git-Paper-492 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
* **Skript version:** 2.3-beta7

**Comment by AsDsDD** [comment]
The facing expression now works but setting the facing still doesn't. Throws this in the console
`[20:33:48 ERROR]: #!#!
[20:33:48 ERROR]: #!#! [Skript] Severe Error:
[20:33:48 ERROR]: #!#!
[20:33:48 ERROR]: #!#! Something went horribly wrong with Skript.
[20:33:48 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:33:48 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:33:48 ERROR]: #!#! Here is full list of them:
[20:33:48 ERROR]: #!#! skRayFall (https://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) SK-NBeeT (https://github.com/ShaneBeee/Sk-NBeeT) skDragon skUtilities (https://tim740.github.io/) skript-yaml MundoSK (https://forums.skunity.com/resources/mundosk.69/) SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/)
[20:33:48 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:33:48 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:33:48 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:33:48 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:33:48 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:33:48 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:33:48 ERROR]: #!#!
[20:33:48 ERROR]: #!#! Stack trace:
[20:33:48 ERROR]: #!#! java.lang.IllegalArgumentException: Cannot get new data of Modern Material
[20:33:48 ERROR]: #!#! at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[20:33:48 ERROR]: #!#! at org.bukkit.Material.getNewData(Material.java:3103)
[20:33:48 ERROR]: #!#! at ch.njol.skript.expressions.ExprFacing.change(ExprFacing.java:122)
[20:33:48 ERROR]: #!#! at ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[20:33:48 ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
[20:33:48 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:33:48 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[20:33:48 ERROR]: #!#! at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:280)
[20:33:48 ERROR]: #!#! at ch.njol.skript.command.Commands$3$1.call(Commands.java:213)
[20:33:48 ERROR]: #!#! at ch.njol.skript.command.Commands$3$1.call(Commands.java:1)
[20:33:48 ERROR]: #!#! at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftFuture.run(CraftFuture.java:85)
[20:33:48 ERROR]: #!#! at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448)
[20:33:48 ERROR]: #!#! at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1002)
[20:33:48 ERROR]: #!#! at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[20:33:48 ERROR]: #!#! at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:937)
[20:33:48 ERROR]: #!#! at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:835)
[20:33:48 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
[20:33:48 ERROR]: #!#!
[20:33:48 ERROR]: #!#! Version Information:
[20:33:48 ERROR]: #!#! Skript: 2.3 (latest)
[20:33:48 ERROR]: #!#! Flavor: skriptlang-github
[20:33:48 ERROR]: #!#! Date: 2019-01-04
[20:33:48 ERROR]: #!#! Bukkit: 1.13.2-R0.1-SNAPSHOT
[20:33:48 ERROR]: #!#! Minecraft: 1.13.2
[20:33:48 ERROR]: #!#! Java: 1.8.0_171 (OpenJDK 64-Bit Server VM 25.171-b11)
[20:33:48 ERROR]: #!#! OS: Linux amd64 4.4.0-116-generic
[20:33:48 ERROR]: #!#!
[20:33:48 ERROR]: #!#! Server platform: Paper
[20:33:48 ERROR]: #!#!
[20:33:48 ERROR]: #!#! Current node: null
[20:33:48 ERROR]: #!#! Current item: set the facing of the targeted block of event-player to west
[20:33:48 ERROR]: #!#!
[20:33:48 ERROR]: #!#! Thread: Server thread
[20:33:48 ERROR]: #!#!
[20:33:48 ERROR]: #!#! Language: english
[20:33:48 ERROR]: #!#! Link parse mode: STRICT
[20:33:48 ERROR]: #!#!
[20:33:48 ERROR]: #!#! End of Error.
[20:33:48 ERROR]: #!#!`

**Comment by bensku** [comment]
Fixed that, too.
