### ISSUE TITLE
Error Skript 

### ISSUE THREAD

**Issue by Spinogl** [SkriptLang/Skript#1797]
I'm French, so i'm sorry if I talk special x)

### Description
There is an error in the consol of my serveur. "This issue is NOT your fault! You probably can't fix it yourself, either."

### Errors / Screenshots
Error in the console : 

[09:58:33 ERROR]: #!#!
[09:58:33 ERROR]: #!#! [Skript] Severe Error:
[09:58:33 ERROR]: #!#! Could not load JumpHelp.sk
[09:58:33 ERROR]: #!#!
[09:58:33 ERROR]: #!#! Something went horribly wrong with Skript.
[09:58:33 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[09:58:33 ERROR]: #!#! You should report it at https://github.com/bensku/Skript/issues. Please copy paste this report there (or use paste service).
[09:58:33 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[09:58:33 ERROR]: #!#!
[09:58:33 ERROR]: #!#! Stack trace:
[09:58:33 ERROR]: #!#! java.lang.IllegalStateException: No match found
[09:58:33 ERROR]: #!#! at java.util.regex.Matcher.group(Matcher.java:536)
[09:58:33 ERROR]: #!#! at ch.njol.skript.command.Commands.loadCommand(Commands.java:353)
[09:58:33 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:571)
[09:58:33 ERROR]: #!#! at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347)
[09:58:33 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)
[09:58:33 ERROR]: #!#! at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:289)
[09:58:33 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:319)
[09:58:33 ERROR]: #!#! at ch.njol.skript.Skript$2.run(Skript.java:446)
[09:58:33 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[09:58:33 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[09:58:33 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[09:58:33 ERROR]: #!#! at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[09:58:33 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[09:58:33 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[09:58:33 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
[09:58:33 ERROR]: #!#!
[09:58:33 ERROR]: #!#! Version Information:
[09:58:33 ERROR]: #!#! Skript: 2.2-dev32c
[09:58:33 ERROR]: #!#! Bukkit: 1.12.2-R0.1-SNAPSHOT
[09:58:33 ERROR]: #!#! Minecraft: 1.12.2
[09:58:33 ERROR]: #!#! Java: 1.8.0_192 (Java HotSpot(TM) 64-Bit Server VM 25.192-b12)
[09:58:33 ERROR]: #!#! OS: Linux amd64 4.9.0-8-amd64
[09:58:33 ERROR]: #!#!
[09:58:33 ERROR]: #!#! Running CraftBukkit: false
[09:58:33 ERROR]: #!#! Running Spigot (or compatible): true
[09:58:33 ERROR]: #!#! Running Paper (or compatible): true
[09:58:33 ERROR]: #!#!
[09:58:33 ERROR]: #!#! Current node: command /JumpHelp : (JumpHelp.sk, line 1)
[09:58:33 ERROR]: #!#! Current item: null
[09:58:33 ERROR]: #!#! Thread: Server thread
[09:58:33 ERROR]: #!#!
[09:58:33 ERROR]: #!#! Language: english
[09:58:33 ERROR]: #!#! Link parse mode: DISABLED
[09:58:33 ERROR]: #!#!
[09:58:33 ERROR]: #!#! End of Error.
[09:58:33 ERROR]: #!#!

Config : 
command /JumpHelp :
    description: Affiche un message donnant de nombreuses informations sur le jump
    permission: JumpHelp.Skript.Command
    executable by: players
    trigger:
        message "&7&l[&6&lHelpJump&7&l] >> Termine le jump vous apporte de nombreux avantages. Parmis ceux-ci, vous avez un nouveau kit (/kit Jumper) qui contient des slimes blocs, un arc punch 2, des potions de saut ameliores... La commande [Insert] ainsi que la commande [Insert]"

**Comment by Snow-Pyon** [comment]
Remove the space after the command and before the colon, if it happens to be that, I thought I've fixed this bug a while back but doesn't seem to be the case anymore.

**Comment by bensku** [comment]
OP is running ancient Skript version, that's why it is not working. This can probably be solved by updating to latest release.
