### ISSUE TITLE
Problem with TuSKe's GUI Manager in 2.3.1

### ISSUE THREAD

**Issue by bilektugrul** [SkriptLang/Skript#1802]
### Description
[This code](https://paste.ubuntu.com/p/yG8jJRGwt9) was working before upgrading to the latest version (2.3beta5 - 2.3.1) but now don't working.
### Errors / Screenshots
https://paste.ubuntu.com/p/Xjq9JqbmDS/

### Server Information
* **Server version/platform:**      PaperSpigot 1.13.2
* **Skript version:**                2.3.1

**Comment by bensku** [comment]
We can't help you with addon issues here. Please contact the addon developer.

It is possible that this is a Skript bug, but I people who are not addon developers can rarely provide enough technical details. I have no idea how TuSKe's GUI system works.

**Comment by Blueyescat** [comment]
Looks related to Skript

```md
executing 'set {a} to 5'
executing 'set {item} to stone'
executing 'set {name} to "test"'
executing 'send "%{a} of {item} named {name}%"'

#!#! java.lang.ClassCastException: org.bukkit.inventory.ItemStack cannot be cast to ch.njol.skript.aliases.ItemType
#!#!     at ch.njol.skript.expressions.ExprNamed$1.get(ExprNamed.java:81)
#!#!     at ch.njol.skript.util.Getter.convert(Getter.java:50)
#!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:342)
#!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:333)
#!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:104)
#!#!     at ch.njol.skript.expressions.ExprNamed.get(ExprNamed.java:75)
#!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75)
#!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
#!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:453)
#!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:617)
#!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:1)
#!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:90)
#!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
#!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
#!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
#!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:280)
#!#!     at ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:179)
...
```
