### ISSUE TITLE
Skript weather/world error

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#1803]
Spigot 1.13.2 latest git-Spigot-19c3c5a-5932f8a
Skript 2.3.1 from https://github.com/bensku/Skript/releases-- not "selfbuilt-unknown"

Script (unchanged) worked with previous Skript beta and release versions, up to and including 2.3.  Script reloads without error. Relevant code:
```
	set {_TARGET_WORLD} to "world_yellowdog"
	event-world is not {_TARGET_WORLD}
...
	set {_TARGET_WEATHER} to weather in {_TARGET_WORLD}
```
Error:
```
[09:07:15 ERROR]: #!#! 
[09:07:15 ERROR]: #!#! [Skript] Severe Error:
[09:07:15 ERROR]: #!#! 
[09:07:15 ERROR]: #!#! Something went horribly wrong with Skript.
[09:07:15 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[09:07:15 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[09:07:15 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[09:07:15 ERROR]: #!#! 
[09:07:15 ERROR]: #!#! Stack trace:
[09:07:15 ERROR]: #!#! java.lang.NullPointerException
[09:07:15 ERROR]: #!#!     at ch.njol.skript.lang.Variable.change(Variable.java:478)
[09:07:15 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[09:07:15 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[09:07:15 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[09:07:15 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[09:07:15 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[09:07:15 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[09:07:15 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110)
[09:07:15 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[09:07:15 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[09:07:15 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[09:07:15 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.WorldData.setThundering(WorldData.java:493)
[09:07:15 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.World.w(World.java:1837)
[09:07:15 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.WorldServer.w(WorldServer.java:1092)
[09:07:15 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.World.doTick(World.java:1793)
[09:07:15 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:239)
[09:07:15 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:952)
[09:07:15 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[09:07:15 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[09:07:15 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[09:07:15 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[09:07:15 ERROR]: #!#! 
[09:07:15 ERROR]: #!#! Version Information:
[09:07:15 ERROR]: #!#!   Skript: 2.3.1
[09:07:15 ERROR]: #!#!     Flavor: selfbuilt-unknown
[09:07:15 ERROR]: #!#!     Date: unknown
[09:07:15 ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[09:07:15 ERROR]: #!#!   Minecraft: 1.13.2
[09:07:15 ERROR]: #!#!   Java: 11.0.1 (OpenJDK 64-Bit Server VM 11.0.1+13)
[09:07:15 ERROR]: #!#!   OS: Linux amd64 3.10.0-957.1.3.el7.x86_64
[09:07:15 ERROR]: #!#! 
[09:07:15 ERROR]: #!#! Server platform: Spigot
[09:07:15 ERROR]: #!#! 
[09:07:15 ERROR]: #!#! Current node: null
[09:07:15 ERROR]: #!#! Current item: set {_TARGET_WEATHER}(as java.lang.Object) to the weather in {_TARGET_WORLD}(as org.bukkit.World)
[09:07:15 ERROR]: #!#! Current trigger: weather change (weather change) (start-acid-rain.sk, line 17)
[09:07:15 ERROR]: #!#! 
[09:07:15 ERROR]: #!#! Thread: Server thread
[09:07:15 ERROR]: #!#! 
[09:07:15 ERROR]: #!#! Language: english
[09:07:15 ERROR]: #!#! Link parse mode: DISABLED
[09:07:15 ERROR]: #!#! 
[09:07:15 ERROR]: #!#! End of Error.
```

**Comment by bensku** [comment]
Try redownloading 2.3.1. We had a bit mess with hotfixes, and according to stack trace, you have the wrong build. Sorry for trouble!

**Comment by SlimeDog** [comment]
Much better with Skript 2.3.1-993ef25. Thanks.
