### ISSUE TITLE
1.11.2 LOGS

### ISSUE THREAD

**Issue by TUCAOEVER** [SkriptLang/Skript#1810]
[Skript] Task #14 for Skript v2.3.1 generated an exception
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.WHITE_GLAZED_TERRACOTTA
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_181]
	at org.bukkit.Material.valueOf(Material.java:1) ~[1.11.2.jar:git-Paper-1104]
	at ch.njol.skript.bukkitutil.BukkitUnsafe.initIdMappings(BukkitUnsafe.java:212) ~[Skript.jar:?]
	at ch.njol.skript.bukkitutil.BukkitUnsafe.getMaterialFromId(BukkitUnsafe.java:224) ~[Skript.jar:?]
	at ch.njol.skript.aliases.ItemType.deserialize(ItemType.java:1031) ~[Skript.jar:?]
	at ch.njol.skript.classes.YggdrasilSerializer.deserialize(YggdrasilSerializer.java:44) ~[Skript.jar:?]
	at ch.njol.skript.classes.YggdrasilSerializer.deserialize(YggdrasilSerializer.java:1) ~[Skript.jar:?]
	at ch.njol.yggdrasil.YggdrasilInputStream.readObject(YggdrasilInputStream.java:203) ~[Skript.jar:?]
	at ch.njol.yggdrasil.YggdrasilInputStream.readObject(YggdrasilInputStream.java:139) ~[Skript.jar:?]
	at ch.njol.skript.registrations.Classes.deserialize(Classes.java:759) ~[Skript.jar:?]
	at ch.njol.skript.registrations.Classes.deserialize(Classes.java:748) ~[Skript.jar:?]
	at ch.njol.skript.variables.FlatFileStorage.load_i(FlatFileStorage.java:137) ~[Skript.jar:?]
	at ch.njol.skript.variables.VariablesStorage.load(VariablesStorage.java:165) ~[Skript.jar:?]
	at ch.njol.skript.variables.Variables.load(Variables.java:193) ~[Skript.jar:?]
	at ch.njol.skript.Skript$2.run(Skript.java:514) ~[Skript.jar:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829) [1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [1.11.2.jar:git-Paper-1104]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
### Server Information
* **Server version/platform:**       
* **Skript version:**

**Comment by TheBentoBox** [comment]
Looks to me like you were trying to load a variable which contains white glazed terracotta but you were on a 1.11.2 server so it couldn't load because the block doesn't exist in that version.

**Comment by Nicofisi** [comment]
Looks exactly like that @TheBentoBox, yeah ^

@TUCAOEVER you need to stop your server and either delete the file with variables altogether, or find the line with the terracota in that file, and delete that line *(or these lines)*
