### ISSUE TITLE
No enum constant org.bukkit.Material.ACACIA_BOAT

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#1815]
### Description
I am having a `No enum constant org.bukkit.Material.ACACIA_BOAT` error when loading Skript (before any addon loads) in a Linux machine (not sure about which distro) . I cannot, however, replicate it in my Windows computer using the exactly same version (Paper 1.12.2 1595).

### Errors / Screenshots
```
 [21:28:43 ERROR]: Error occurred while enabling Skript v2.3.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:157) ~[?:?]
at ch.njol.skript.Skript.onEnable(Skript.java:396) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1595]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1595]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1595]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1595]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1595]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1595]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1595]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1595]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1595]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1595]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.ACACIA_BOAT
at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_192]
at org.bukkit.Material.valueOf(Material.java:71) ~[patched_1.12.2.jar:git-Paper-1595]
at ch.njol.skript.aliases.MaterialRegistry.load(MaterialRegistry.java:61) ~[?:?]
at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:104) ~[?:?]
... 13 more
```

### Server Information
* **Server version/platform:** Paper 1.12.2 1595
* **Skript version:** 2.3.1

### Additional Context
There is no material called ACACIA_BOAT in materials folder for 1.12, 1.11, 1.10 or 1.9.
I have no idea where Skript is getting that from.

**Comment by Pikachu920** [comment]
For the googlers:

the solution was deleting materials.json and restarting the server so it regenerates

**Comment by bensku** [comment]
Also: do not downgrade your Skript folder. Material mappings and/or variables might break.

**Comment by filasik** [comment]
> For the googlers:
> 
> the solution was deleting materials.json and restarting the server so it regenerates

Where you deleted it?

**Comment by AyhamAl-Ali** [comment]
> > For the googlers:
> > the solution was deleting materials.json and restarting the server so it regenerates
> 
> Where you deleted it?

In skript's folder `plugins/Skript/` you will find `materials.json` just delete it and restart
