### ISSUE TITLE
Aliases Crashing

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#1820]
### Steps to Reproduce
Started 1.13.2 server, changed it to 1.12.2, error.

### Errors / Screenshots
```
[Server thread/ERROR]: Error occurred while enabling Skript v2.3.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:157) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:396) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1595]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1595]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1595]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1595]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1595]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.ACACIA_BOAT
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_161]
	at org.bukkit.Material.valueOf(Material.java:71) ~[patched_1.12.2.jar:git-Paper-1595]
	at ch.njol.skript.aliases.MaterialRegistry.load(MaterialRegistry.java:61) ~[?:?]
	at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:104) ~[?:?]
	... 13 more
```

### Server Information
* **Server version/platform:** Paper 1.12 and 1.13
* **Skript version:** 2.3.1

**Comment by Blueyescat** [comment]
Happens when you downgrade and gets resolved when you delete the materials.json file, bensku would say you shouldn't downgrade from 1.13 🙂 lol

**Comment by Nicofisi** [comment]
What @Blueyescat said, #1815

**Comment by Nicofisi** [comment]
Also you aren't supposed to downgrade the Minecraft version of a server at all since for example the worlds wouldn't work either :eyes:

**Comment by Blueyescat** [comment]
Hmm are you really ignoring that error? Yes downgrading from 1.13 corrupts the worlds, but what about other versions? Even the world corruption is not related to Skript.

bensku in https://github.com/SkriptLang/Skript/issues/1815
> Also: do not downgrade your Skript folder. Material mappings and/or variables might break.

What is downgrading Skript folder, why variables would break when you downgrade the Minecraft version, and the problem is already the materials.json file.

**Comment by TheLimeGlass** [comment]
Well how about deleting the old aliases when the version is 1.12. It's a really simple fix, just put a version tag on the aliases and if it's not the version delete it and reset it.

**Comment by bensku** [comment]
That would break items saved in variables. Material mappings are there to provide static number ids for all materials, and they *can* be upgraded without changing existing ids.

A better error message woule be good to have, though.

**Comment by Blueyescat** [comment]
So you say downgrading MC version is not supported by Skript?

**Comment by bensku** [comment]
Yes
