### ISSUE TITLE
Issues with GUIs

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#1857]
`[18:33:03] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to Skript v2.3.2
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.13.2.jar:git-Paper-509]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1788) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1604) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-509]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-509]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: ch.njol.skript.aliases.ItemType.getItemMeta()Ljava/lang/Object;
	at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:29) ~[?:?]
	at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:1) ~[?:?]
	at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75) ~[?:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[?:?]
	at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:60) ~[?:?]
	at ch.njol.skript.lang.util.ConvertedExpression.getSingle(ConvertedExpression.java:151) ~[?:?]
	at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.execute(EffFormatGUI.java:117) ~[?:?]
	at com.github.tukenuke.tuske.util.EffectSection.check(EffectSection.java:54) ~[?:?]
	at ch.njol.skript.lang.Condition.run(Condition.java:56) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:57) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:286) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:243) ~[?:?]
	at ch.njol.skript.command.Commands.handleCommand(Commands.java:254) ~[?:?]
	at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:169) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.13.2.jar:git-Paper-509]
	... 16 more
[18:33:03] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'stadt' in plugin Skript v2.3.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1796) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1604) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-509]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-509]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: ch.njol.skript.aliases.ItemType.getItemMeta()Ljava/lang/Object;
	at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:29) ~[?:?]
	at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:1) ~[?:?]
	at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75) ~[?:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[?:?]
	at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:60) ~[?:?]
	at ch.njol.skript.lang.util.ConvertedExpression.getSingle(ConvertedExpression.java:151) ~[?:?]
	at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.execute(EffFormatGUI.java:117) ~[?:?]
	at com.github.tukenuke.tuske.util.EffectSection.check(EffectSection.java:54) ~[?:?]
	at ch.njol.skript.lang.Condition.run(Condition.java:56) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:57) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:286) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:243) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:194) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-509]
	... 15 more`

This happens when I open a gui to a player with this code:

```
				open virtual chest inventory with 1 row named "&4SICHER?" to player
				format gui slot 3 of player with apple named "&4JA!" with lore "&5Aktion ausführen" to close then execute player command "mytestcommand"	
```
Same error with this code:

```
skellett open "CHEST" with 2 rows named "&6TEST" to player
make a gui slot 3 of player with REDSTONE with name "&4JA!" with lore "&5Aktion ausführen!" to close then run player command "/testcommand"
```

I made sure that I have the latest available versions of Skellett, TuSke, Skript

**Comment by Blueyescat** [comment]
Update skQuery and read [release notes of 2.3.1](https://github.com/SkriptLang/Skript/releases/tag/2.3.1) (use 2.3.2)

**Comment by bloggy** [comment]
Thank you @Blueyescat 
Updating to latest skQuery seems to fix this issue.
I am still unsure which is the best and most stable way of working with GUIs. Which GUI effects should we use? Does Skript offer full GUI support, yet?

**Comment by Blueyescat** [comment]
TuSKe is the best, easy and works fine. But yes you can use the inventory click event of Skript and make them manually. Close the issue please 🙂
