### ISSUE TITLE
[Skript] Checking for updates failed. Do you have internet connection

### ISSUE THREAD

**Issue by rokzartz** [SkriptLang/Skript#1913]
i got an error ` [Skript] Checking for updates failed. Do you have Internet con
nection?`
(i have internet connection)
Can you fix it ?

`[16:41:25 ERROR]: [Skript] Checking for updates failed. Do you have Internet con
nection?
[16:41:25 WARN]: java.util.concurrent.CompletionException: org.bukkit.plugin.Ill
egalPluginAccessException: Plugin attempted to register task while disabled
[16:41:25 WARN]:        at java.base/java.util.concurrent.CompletableFuture.enco
deThrowable(Unknown Source)
[16:41:25 WARN]:        at java.base/java.util.concurrent.CompletableFuture.comp
leteThrowable(Unknown Source)
[16:41:25 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniA
ccept.tryFire(Unknown Source)
[16:41:25 WARN]:        at java.base/java.util.concurrent.CompletableFuture.post
Complete(Unknown Source)
[16:41:25 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Asyn
cSupply.run(Unknown Source)
[16:41:25 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Asyn
cSupply.exec(Unknown Source)
[16:41:25 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(Un
known Source)
[16:41:25 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker
(Unknown Source)
[16:41:25 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.r
un(Unknown Source)
[16:41:25 WARN]: Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plug
in attempted to register task while disabled
[16:41:25 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftSchedul
er.validate(CraftScheduler.java:398)
[16:41:25 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftSchedul
er.runTaskTimerAsynchronously(CraftScheduler.java:141)
[16:41:25 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftSchedul
er.runTaskLaterAsynchronously(CraftScheduler.java:115)
[16:41:25 WARN]:        at ch.njol.skript.util.Task.schedule(Task.java:77)
[16:41:25 WARN]:        at ch.njol.skript.util.Task.<init>(Task.java:63)
[16:41:25 WARN]:        at ch.njol.skript.update.Updater$1.<init>(Updater.java:1
45)
[16:41:25 WARN]:        at ch.njol.skript.update.Updater.lambda$0(Updater.java:1
45)
[16:41:25 WARN]:        ... 7 more`

### Server Information
* **Server version/platform: `1.8.8/bukkit`**       
* **Skript version: `2.3`**

**Comment by ShaneBeee** [comment]
The Skript 2.3.x series only works on 1.9.4+

**Comment by bensku** [comment]
1.8 is not supported, and Skript probably fails to start up. After that, for some reason, it still tries to launch the updater.
