### ISSUE TITLE
cmd with play sound on Console makes error.

### ISSUE THREAD

**Issue by mckite** [SkriptLang/Skript#1914]
### Description
Run a CMD made by Skript and have a  play sound fuction  on Console makes errrors.

That error not happens on Skript 2.2

### Steps to Reproduce

Run the cmd wich made by Skript with "play sound" and on COnsole

### Expected Behavior

run the cmd which open the GUI on the console.

### Errors / Screenshots

[14:57:28 ERROR]: #!#!
[14:57:28 ERROR]: #!#! [Skript] Severe Error:
[14:57:28 ERROR]: #!#!
[14:57:28 ERROR]: #!#! Something went horribly wrong with Skript.
[14:57:28 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it y
ourself, either.
[14:57:28 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skr
ipt/issues. Please copy paste this report there (or use paste service).
[14:57:28 ERROR]: #!#! This ensures that your issue is noticed and will be fixed
 as soon as possible.
[14:57:28 ERROR]: #!#!
[14:57:28 ERROR]: #!#! Stack trace:
[14:57:28 ERROR]: #!#! java.lang.NullPointerException
[14:57:28 ERROR]: #!#!     at ch.njol.skript.effects.EffPlaySound.execute(EffPla
ySound.java:115)
[14:57:28 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[14:57:28 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.j
ava:61)
[14:57:28 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.j
ava:89)
[14:57:28 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:5
7)
[14:57:28 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(Scri
ptCommand.java:298)
[14:57:28 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(Scrip
tCommand.java:255)
[14:57:28 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.onCommand(Scr
iptCommand.java:200)
[14:57:28 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCom
mand.java:44)
[14:57:28 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(Simpl
eCommandMap.java:151)
[14:57:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispat
chCommand(CraftServer.java:685)
[14:57:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispat
chServerCommand(CraftServer.java:648)
[14:57:28 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(D
edicatedServer.java:463)
[14:57:28 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(De
dicatedServer.java:424)
[14:57:28 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(Mi
necraftServer.java:774)
[14:57:28 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(
MinecraftServer.java:666)
[14:57:28 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[14:57:28 ERROR]: #!#!
[14:57:28 ERROR]: #!#! Version Information:
[14:57:28 ERROR]: #!#!   Skript: 2.3.5
[14:57:28 ERROR]: #!#!     Flavor: skriptlang-github
[14:57:28 ERROR]: #!#!     Date: 2019-02-09
[14:57:28 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[14:57:28 ERROR]: #!#!   Minecraft: 1.12.2
[14:57:28 ERROR]: #!#!   Java: 1.8.0_201 (Java HotSpot(TM) 64-Bit Server VM 25.2
01-b09)
[14:57:28 ERROR]: #!#!   OS: Windows Server 2012 R2 amd64 6.3
[14:57:28 ERROR]: #!#!
[14:57:28 ERROR]: #!#! Server platform: Paper
[14:57:28 ERROR]: #!#!
[14:57:28 ERROR]: #!#! Current node: null
[14:57:28 ERROR]: #!#! Current item: play sound
[14:57:28 ERROR]: #!#! Current trigger: command /계급 (simple event) (계급.sk, l
ine -1)
[14:57:28 ERROR]: #!#!
[14:57:28 ERROR]: #!#! Thread: Server thread
[14:57:28 ERROR]: #!#!
[14:57:28 ERROR]: #!#! Language: english
[14:57:28 ERROR]: #!#! Link parse mode: DISABLED
[14:57:28 ERROR]: #!#!
[14:57:28 ERROR]: #!#! End of Error.
[14:57:28 ERROR]: #!#!
[14:57:28 INFO]: An internal error occurred while attempting to perform this com
mand.
>

### Server Information
* **Server version/platform:**     1.12.2
* **Skript version:**                2.3.5

**Comment by bensku** [comment]
We need a test script that causes this issue and works without addons.

**Comment by Blueyescat** [comment]
Looks like EffPlaySound doesn't have proper null checks

**Comment by mckite** [comment]
command /계급 [<text>]:
	#executable by: player
	trigger:
		open chest inventory with 5 row named "&f[ &b&lKite &6&l서버 &5&l계급 &f]" to player
		loop 45 times:
			set slot (loop-number)-1 of current inventory to white stained glass pane named "&f[ &b빈칸 &f]"
		set slot 11 of current inventory to cobblestone named "&f[ &e&l유저 &f] " with lore "&a 초기 유저계급 " and "&6 땅 1개 구매 가능 " and " &e/sethome 20개 설정가능 " and " &e플라이 구매 가능"
		set slot 13 of current inventory to Iron Block named "&f[ &e&l중류층 &a구매 &f] " with lore "&c 비용: &a100만원" and "&e 땅 2개 구매 가능 " and " &e/sethome 35개 설정가능 " and "&6 ""&a/엔더상자&6"" 명령어 사용 가능 " and " &e플라이 구매 가능"
		set slot 15 of current inventory to Gold Block named "&f[ &a&l중상류층 &e구매 &f] " with lore "&c 비용: &a800만원" and "&a 땅 5개 구매 가능 " and " &e/sethome 50개 설정가능 " and "&6 땅 바이옴 변경 가능 " and " &e플라이 구매 가능 and 30분짜리 구매 가능"
		set slot 30 of current inventory to Emerald Block named "&f[ &9&l상류층 &a구매 &f] " with lore "&c 비용: &a2500만원" and "&b 땅 8개 구매 가능 " and " &e/sethome 75개 설정가능 " and " &e플라이 구매 가능 and 40분짜리 구매 가능"
		set slot 32 of current inventory to Diamond Block named "&f[ &c&l재&e&l벌 &a구매 &f] " with lore "&c 비용: &a7500만원" and "&5 땅 15개 구매 가능 " and " &e/sethome 100개 설정가능 " and " &e플라이 구매 가능 and 60분짜리 구매 가능"
		set slot 22 of current inventory to Nether star named "&f[ &b&l카이트시스템 &f]  " with lore "&c안내: &a개인 칭호가 있는 경우, 개인칭호가 유지됩니다."
		play sound "BLOCK_NOTE_PLING" with volume 1 at player
on inventory click:
	if name of current inventory contains "&f[ &b&lKite &6&l서버 &5&l계급 &f]":
		cancel event
	if name of click item contains "&f[ &e&l중류층 &a구매 &f] ":
		player command "/중류층등업"
		play sound "ENTITY_CHICKEN_EGG" with volume 1 at player 
	if name of click item contains "&f[ &a&l중상류층 &e구매 &f] ":
		play sound "ENTITY_CHICKEN_EGG" with volume 1 at player 
		player command "/중상류층등업"
	if name of click item contains "&f[ &9&l상류층 &a구매 &f] ":
		play sound "ENTITY_CHICKEN_EGG" with volume 1 at player 
		player command "/상류층등업"
	if name of click item contains "&f[ &c&l재&e&l벌 &a구매 &f] ":
		play sound "ENTITY_CHICKEN_EGG" with volume 1 at player 
		player command "/재벌등업"

**Comment by mckite** [comment]
> We need a test script that causes this issue and works without addons.

play sound "BLOCK_NOTE_PLING" with volume 1 at player

**Comment by Blueyescat** [comment]
Nope, that code doesn't cause the error for me and works, tried with Skript 2.3.5 on 1.12.2 and 1.13.2.

**Comment by mckite** [comment]
I confirmed again that makes errors.

command /test :
	usage: /test
	trigger:
		play sound "BLOCK_NOTE_PLING" with volume 1 at player

Run cmd "test" on Console,
the error occures

Stack trace:
**java.lang.NullPointerException**
    at ch.njol.skript.effects.EffPlaySound.execute(EffPlaySound.java:115)
    at ch.njol.skript.lang.Effect.run(Effect.java:52)
    at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
    at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
    at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
    at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:298)
    at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255)
    at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:200)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)

**Comment by bensku** [comment]
BLOCK_NOTE_PLING makes Minecraft 1.13 complain about a disallowed sound name, but other than that, it works. Cannot reproduce this issue.

**Comment by mckite** [comment]
> BLOCK_NOTE_PLING makes Minecraft 1.13 complain about a disallowed sound name, but other than that, it works. Cannot reproduce this issue.

It can reproduce always time on spigot 1.13 and 1.12,2 

In game CMD is working correctly, but run this  CMD on Console makes error

 #!#!
 #!#! [Skript] Severe Error:
 #!#!
 #!#! Something went horribly wrong with Skript.
 #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
 #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report ther
 #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
 #!#!
 #!#! Stack trace:
 #!#! java.lang.NullPointerException
 #!#!     at ch.njol.skript.effects.EffPlaySound.execute(EffPlaySound.java:113)
 #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
 #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
 #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
 #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
 #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:298)
 #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255)
 #!#!     at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:200)
 #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
 #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
 #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704)
 #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:689)
 #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:459)
 #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418)
 #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
 #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
 #!#!     at java.lang.Thread.run(Unknown Source)
 #!#!
 #!#! Version Information:
 #!#!   Skript: 2.3.5 (latest)
 #!#!     Flavor: skriptlang-github
 #!#!     Date: 2019-02-09
 #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
 #!#!   Minecraft: 1.13.2
 #!#!   Java: 1.8.0_202 (Java HotSpot(TM) 64-Bit Server VM 25.202-b08)
 #!#!   OS: Windows 10 amd64 10.0
 #!#!
 #!#! Server platform: Spigot
 #!#!
 #!#! Current node: null
 #!#! Current item: play sound
 #!#! Current trigger: command /test (simple event) (op.sk, line -1)
 #!#!
 #!#! Thread: Server thread
 #!#!
 #!#! Language: english
 #!#! Link parse mode: STRICT
 #!#!
 #!#! End of Error.
 #!#!

**Comment by mckite** [comment]
> BLOCK_NOTE_PLING makes Minecraft 1.13 complain about a disallowed sound name, but other than that, it works. Cannot reproduce this issue.

Did you try it on Console? In game cmd works without any problems.

Which scripts did you tried?

**Comment by Blueyescat** [comment]
Yes that is acceptable, `player` will be undefined when you use the command in console and as i said EffPlaySound doesn't have proper null checks.
