### ISSUE TITLE
Sound null pointer

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#1921]
### Description
Null pointer when the location is not set.

### Steps to Reproduce
```
command /sound <number> <text>:
	trigger:
		play sound argument-2 with pitch argument-1 at target block
```
When the target block is not set, aka looking in the sky.

### Errors / Screenshots
```
[06:50:04] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[06:50:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffPlaySound.execute(EffPlaySound.java:113)
[06:50:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[06:50:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[06:50:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[06:50:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[06:50:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:298)
[06:50:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255)
[06:50:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:254)
[06:50:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:169)
[06:50:04] [Server thread/ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35)
[06:50:04] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[06:50:04] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[06:50:04] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[06:50:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1791)
[06:50:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1602)
[06:50:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[06:50:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[06:50:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
[06:50:04] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[06:50:04] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[06:50:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109)
[06:50:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016)
[06:50:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[06:50:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[06:50:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[06:50:04] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[06:50:04] [Server thread/ERROR]: #!#! 
[06:50:04] [Server thread/ERROR]: #!#! Version Information:
[06:50:04] [Server thread/ERROR]: #!#!   Skript: 2.3.5
[06:50:04] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[06:50:04] [Server thread/ERROR]: #!#!     Date: 2019-02-09
[06:50:04] [Server thread/ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[06:50:04] [Server thread/ERROR]: #!#!   Minecraft: 1.13.2
[06:50:04] [Server thread/ERROR]: #!#!   Java: 1.8.0_161 (Java HotSpot(TM) 64-Bit Server VM 25.161-b12)
[06:50:04] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[06:50:04] [Server thread/ERROR]: #!#! 
[06:50:04] [Server thread/ERROR]: #!#! Server platform: Paper
[06:50:04] [Server thread/ERROR]: #!#! 
[06:50:04] [Server thread/ERROR]: #!#! Current node: null
[06:50:04] [Server thread/ERROR]: #!#! Current item: play sound
[06:50:04] [Server thread/ERROR]: #!#! Current trigger: command /sound (simple event) (test.sk, line -1)
```
Two things, one why does the error say line -1?
And the syntax should be adjusted to allow for 
```
play sound %string% [with volume %-number%] [(and|with) pitch %-number%] for %players%
```
Which would just play the sound for the players at their location.

**Comment by mckite** [comment]
I also have similer issue.
https://github.com/SkriptLang/Skript/issues/1914

**Comment by bensku** [comment]
It is the exact same issue.
