### ISSUE TITLE
Error on registering recipe: Deprecated method

### ISSUE THREAD

**Issue by Blackyvk** [SkriptLang/Skript#1922]
### Description
On plugin load

### Steps to Reproduce
Create a script and register a new recipe On load

### Expected Behavior
No errors 

### Errors / Screenshots
```
[18:45:36] [Server thread/WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[18:45:36] [Server thread/WARN]: 	at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:28)
[18:45:36] [Server thread/WARN]: 	at com.w00tmast3r.skquery.elements.effects.EffNewRecipe.execute(EffNewRecipe.java:55)
[18:45:36] [Server thread/WARN]: 	at ch.njol.skript.lang.Effect.run(Effect.java:52)
[18:45:36] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[18:45:36] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[18:45:36] [Server thread/WARN]: 	at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[18:45:36] [Server thread/WARN]: 	at ch.njol.skript.events.EvtScript.register(EvtScript.java:61)
[18:45:36] [Server thread/WARN]: 	at ch.njol.skript.ScriptLoader$3.call(ScriptLoader.java:757)
[18:45:36] [Server thread/WARN]: 	at ch.njol.skript.ScriptLoader$3.call(ScriptLoader.java:1)
[18:45:36] [Server thread/WARN]: 	at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:776)
[18:45:36] [Server thread/WARN]: 	at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:409)
[18:45:36] [Server thread/WARN]: 	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:428)
[18:45:36] [Server thread/WARN]: 	at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:350)
[18:45:36] [Server thread/WARN]: 	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:380)
[18:45:36] [Server thread/WARN]: 	at ch.njol.skript.Skript$2.run(Skript.java:527)
[18:45:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[18:45:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[18:45:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003)
[18:45:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[18:45:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[18:45:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[18:45:36] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

### Server Information
* **Server version/platform: **       Paperspigot 1.13.2 -544
* **Skript version:**                2.3.5

**Comment by ShaneBeee** [comment]
This isn't a Skript issue, since Skript doesn't have a syntax for creating recipes.
