### ISSUE TITLE
I have this error when skript start

### ISSUE THREAD

**Issue by DevilishDante** [SkriptLang/Skript#1937]
### Description
Good evening, when skript parse script, i have this error
```
[19:47:25 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[19:47:25 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[19:47:25 ERROR]: #!#!
[19:47:25 ERROR]: #!#! Stack trace:
[19:47:25 ERROR]: #!#! java.util.NoSuchElementException
[19:47:25 ERROR]: #!#!     at java.util.LinkedList.removeFirst(LinkedList.java:270)
[19:47:25 ERROR]: #!#!     at java.util.LinkedList.pop(LinkedList.java:801)
[19:47:25 ERROR]: #!#!     at ch.njol.skript.log.HandlerList.remove(HandlerList.java:40)
[19:47:25 ERROR]: #!#!     at ch.njol.skript.log.SkriptLogger.removeHandler(SkriptLogger.java:111)
[19:47:25 ERROR]: #!#!     at ch.njol.skript.log.LogHandler.stop(LogHandler.java:43)
[19:47:25 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1501)
[19:47:25 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1254)
[19:47:25 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1230)
[19:47:25 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:684)
[19:47:25 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:409)
[19:47:25 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:428)
[19:47:25 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:350)
[19:47:25 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:380)
[19:47:25 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:527)
[19:47:25 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[19:47:25 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[19:47:25 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[19:47:25 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[19:47:25 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[19:47:25 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[19:47:25 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[19:47:25 ERROR]: #!#!
[19:47:25 ERROR]: #!#! Version Information:
[19:47:25 ERROR]: #!#!   Skript: 2.3.6 (latest)
[19:47:25 ERROR]: #!#!     Flavor: skriptlang-github
[19:47:25 ERROR]: #!#!     Date: 2019-03-03
[19:47:25 ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[19:47:25 ERROR]: #!#!   Minecraft: 1.13.2
[19:47:25 ERROR]: #!#!   Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
[19:47:25 ERROR]: #!#!   OS: Linux amd64 4.9.58-xxxx-std-ipv6-64
[19:47:25 ERROR]: #!#!
[19:47:25 ERROR]: #!#! Server platform: Spigot
[19:47:25 ERROR]: #!#!
[19:47:25 ERROR]: #!#! Current node: on join: (AutoMessage.sk, line 37)
[19:47:25 ERROR]: #!#! Current item: null
[19:47:25 ERROR]: #!#!
[19:47:25 ERROR]: #!#! Thread: Server thread
[19:47:25 ERROR]: #!#!
[19:47:25 ERROR]: #!#! Language: english
[19:47:25 ERROR]: #!#! Link parse mode: DISABLED
[19:47:25 ERROR]: #!#!
[19:47:25 ERROR]: #!#! End of Error.
[19:47:25 ERROR]: #!#!
```

### Steps to Reproduce
Just insert a random event on the first script 

### Server Information
* **Server version/platform:**  CraftBukkit version git-Spigot-f56e2e7-9dc5658 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
* **Skript version:**                Lastest 2.3.6

### Additional Context
Thanks to read me

**Comment by ShaneBeee** [comment]
I recommend posting the code you are using that is causing this error.

**Comment by DevilishDante** [comment]
hello @ShaneBeee  i have this error with` every 11 minutes` or with this code:

```on join:
	wait 15 seconds
	set action bar of player to {@ac1}
	wait 3 seconds
	set action bar of player to ""
	wait 3 seconds
	set action bar of player to {@ac2} 
	wait 3 seconds
	set action bar of player to ""
	wait 3 seconds
	set action bar of player to {@ac3} 
	wait 3 seconds
	set action bar of player to ""
	wait 3 seconds
	set action bar of player to {@ac4}```

or again;

```on join:
	broadcast "lolololol"```

with this error:

```[04:00:17 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[04:00:17 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[04:00:17 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[04:00:17 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[04:00:17 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[04:00:17 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[04:00:17 ERROR]: #!#!
[04:00:17 ERROR]: #!#! Stack trace:
[04:00:17 ERROR]: #!#! java.util.NoSuchElementException
[04:00:17 ERROR]: #!#!     at java.util.LinkedList.removeFirst(LinkedList.java:270)
[04:00:17 ERROR]: #!#!     at java.util.LinkedList.pop(LinkedList.java:801)
[04:00:17 ERROR]: #!#!     at ch.njol.skript.log.HandlerList.remove(HandlerList.java:40)
[04:00:17 ERROR]: #!#!     at ch.njol.skript.log.SkriptLogger.removeHandler(SkriptLogger.java:111)
[04:00:17 ERROR]: #!#!     at ch.njol.skript.log.LogHandler.stop(LogHandler.java:43)
[04:00:17 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1501)
[04:00:17 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1254)
[04:00:17 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1230)
[04:00:17 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:684)
[04:00:17 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:409)
[04:00:17 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:428)
[04:00:17 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:350)
[04:00:17 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:380)
[04:00:17 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:527)
[04:00:17 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[04:00:17 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[04:00:17 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[04:00:17 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[04:00:17 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[04:00:17 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[04:00:17 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[04:00:17 ERROR]: #!#!
[04:00:17 ERROR]: #!#! Version Information:
[04:00:17 ERROR]: #!#!   Skript: 2.3.6 (latest)
[04:00:17 ERROR]: #!#!     Flavor: skriptlang-github
[04:00:17 ERROR]: #!#!     Date: 2019-03-03
[04:00:17 ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[04:00:17 ERROR]: #!#!   Minecraft: 1.13.2
[04:00:17 ERROR]: #!#!   Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
[04:00:17 ERROR]: #!#!   OS: Linux amd64 4.9.58-xxxx-std-ipv6-64
[04:00:17 ERROR]: #!#!
[04:00:17 ERROR]: #!#! Server platform: Spigot
[04:00:17 ERROR]: #!#!
[04:00:17 ERROR]: #!#! Current node: on join: (AutoMessage.sk, line 36)
[04:00:17 ERROR]: #!#! Current item: null
[04:00:17 ERROR]: #!#!
[04:00:17 ERROR]: #!#! Thread: Server thread
[04:00:17 ERROR]: #!#!
[04:00:17 ERROR]: #!#! Language: english
[04:00:17 ERROR]: #!#! Link parse mode: DISABLED
[04:00:17 ERROR]: #!#!
[04:00:17 ERROR]: #!#! End of Error.
[04:00:17 ERROR]: #!#!
```

**Comment by ShaneBeee** [comment]
Im not sure which addon you are using for action bars, but I recommend using Skript's built in [**ActionBar**](http://skriptlang.github.io/Skript/effects.html#EffActionBar) effect

As for the on join part, Im not sure what to tell ya there. I have no issues using on Join, my guess is you might be using an outdated addon. That seems to be the root of a lot of these issues. Some older/broken addons cause regular Skript syntaxes to break sometimes.

**Comment by bensku** [comment]
Follow the instructions and test without addons, please.
