### ISSUE TITLE
Error With variables

### ISSUE THREAD

**Issue by GTSkill** [SkriptLang/Skript#1946]
### Steps to Reproduce
command /shopfinalsellgrind <string>:
	trigger:
		wait 1 tick
		set {name} to yml value "%arg 1%.name" of file "plugins/Skript/finalbuygrind.yml"
		set {price} to yml value "%arg 1%.price" of file "plugins/Skript/finalbuygrind.yml"
		send {name}
		if Player's inventory contains 1 of {name}:
			remove 1 of {name} from player
			give player cobblestone named "OooF"
			send "Ooofed"

### Errors / Screenshots
[10:18:19 ERROR]: #!#! Stack trace:
[10:18:19 ERROR]: #!#! java.lang.ClassCastException: java.lang.String cannot be cast to ch.njol.skript.entity.EntityType
[10:18:19 ERROR]: #!#!     at ch.njol.skript.expressions.ExprXOf$1.convert(ExprXOf.java:89)
[10:18:19 ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:342)
[10:18:19 ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:333)
[10:18:19 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:104)
[10:18:19 ERROR]: #!#!     at ch.njol.skript.expressions.ExprXOf.get(ExprXOf.java:73)
[10:18:19 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75)
[10:18:19 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:161)
[10:18:19 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:156)
[10:18:19 ERROR]: #!#!     at ch.njol.skript.conditions.CondContains.lambda$0(CondContains.java:118)
[10:18:19 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:173)
[10:18:19 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:161)
[10:18:19 ERROR]: #!#!     at ch.njol.skript.conditions.CondContains.check(CondContains.java:103)
[10:18:19 ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
[10:18:19 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:51)
[10:18:19 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[10:18:19 ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[10:18:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[10:18:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[10:18:19 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[10:18:19 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[10:18:19 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[10:18:19 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[10:18:19 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[10:18:19 ERROR]: #!#! 
[10:18:19 ERROR]: #!#! Version Information:
[10:18:19 ERROR]: #!#!   Skript: 2.3.6 (latest)
[10:18:19 ERROR]: #!#!     Flavor: skriptlang-github
[10:18:19 ERROR]: #!#!     Date: 2019-03-03
[10:18:19 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[10:18:19 ERROR]: #!#!   Minecraft: 1.12.2
[10:18:19 ERROR]: #!#!   Java: 1.8.0_181 (OpenJDK 64-Bit Server VM 25.181-b13)
[10:18:19 ERROR]: #!#!   OS: Linux amd64 4.9.0-8-amd64
[10:18:19 ERROR]: #!#! 
[10:18:19 ERROR]: #!#! Server platform: Paper
[10:18:19 ERROR]: #!#! 
[10:18:19 ERROR]: #!#! Current node: null
[10:18:19 ERROR]: #!#! Current item: inventory of the player contains [[long:1]] of {name}(as java.lang.Object)
[10:18:19 ERROR]: #!#! Current trigger: command /shopfinalsellgrind (simple event) (finalbuygrind.sk, line -1)
[10:18:19 ERROR]: #!#! 
[10:18:19 ERROR]: #!#! Thread: Server thread
[10:18:19 ERROR]: #!#! 
[10:18:19 ERROR]: #!#! Language: english
[10:18:19 ERROR]: #!#! Link parse mode: DISABLED
[10:18:19 ERROR]: #!#! 
[10:18:19 ERROR]: #!#! End of Error.
[10:18:19 ERROR]: #!#! 

### Server Information
* **git-Paper-1598 (MC: 1.12.2)**       
* **Skript version 2.3.6**

**Comment by FranKusmiruk** [comment]
You're trying to give the player a text, you have to either parse the yaml value or store an actual item on it.

Also, when reporting to the Skript repository, you must be sure the issue comes from Skript and not an addon, even though it does in this case, the given code makes use of addons which makes it harder for us to fix it. Closing the issue since there's already another issue open for this.

**Comment by GTSkill** [comment]
Could you tell me how to fix this code

**Comment by GTSkill** [comment]
> You're trying to give the player a text, you have to either parse the yaml value or store an actual item on it.
> 
> Also, when reporting to the Skript repository, you must be sure the issue comes from Skript and not an addon, even though it does in this case, the given code makes use of addons which makes it harder for us to fix it. Closing the issue since there's already another issue open for this.

Where is this thread so i can read it and fix my code because i have no idea whats wrong with it
