### ISSUE TITLE
bug GUI

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#1960]
When I execute command the GUI opens but Internal io while attemping to perform this command.
Console: [13:10:40 ERROR]: Could not pass event PlayerCommandPreprocessEvent to Skript v2.3.6
org.bukkit.event.EventException: null
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.13.2.jar:git-Paper-564]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-564]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-564]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1790) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1606) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-564]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-564]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.NoSuchMethodError: ch.njol.skript.aliases.ItemType.getItemMeta()Ljava/lang/Object;
at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:29) ~[?:?]
at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:1) ~[?:?]
at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75) ~[?:?]
at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[?:?]
at ch.njol.skript.effects.EffChange.execute(EffChange.java:278) ~[?:?]
at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
at ch.njol.skript.lang.Trigger.execute(Trigger.java:57) ~[?:?]
at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:298) ~[?:?]
at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255) ~[?:?]
at ch.njol.skript.command.Commands.handleCommand(Commands.java:254) ~[?:?]
at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:169) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.13.2.jar:git-Paper-564]
... 16 more
[13:10:40 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'block' in plugin Skript v2.3.6
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-564]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-564]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1798) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1606) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-564]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-564]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.NoSuchMethodError: ch.njol.skript.aliases.ItemType.getItemMeta()Ljava/lang/Object;
at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:29) ~[?:?]
at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:1) ~[?:?]
at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75) ~[?:?]
at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[?:?]
at ch.njol.skript.effects.EffChange.execute(EffChange.java:278) ~[?:?]
at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
at ch.njol.skript.lang.Trigger.execute(Trigger.java:57) ~[?:?]
at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:298) ~[?:?]
at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255) ~[?:?]
at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:200) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-564]
... 15 more

Code: command /target [<text>]:
	trigger:
		if arg 1 is set:
			set {block::%arg%} to location of target block
		else:
			send "&7Podaj nazwe"
command /block [<text>]:
	trigger:
		open chest with 6 rows named "&6Blocki" to player
		set {_n} to 0
		loop {block::*}:
			set player's current inventory's slot {_n} to stone named "&6name %loop-index%" with lore "&cloc: %loop-value%"
			add 1 to {_n}
on right click:
	loop {block::*}:
		if loop-value is location of target block:
			send "&7%loop-index%"

Code shall save target blocks save them and open in GUI.
Addons: SkQuery, SkMortaz, Tuske, WolfSK

**Comment by Runakai1** [comment]
Most likely SkQuery fault, not skript. Don't use several Addons to make guis. Stick with TuSKe or Vanilla

**Comment by Blueyescat** [comment]
Please follow the issue templates.

**Comment by Misio12320** [comment]
Working...  command /target [<text>]:
	trigger:
		if arg 1 is set:
			set {block::%arg%} to location of target block
		else:
			send "&7Podaj nazwe"
command /block:
	trigger:
		open virtual chest inventory named "&6Blocki" with size 5 to player
		set {_n} to 0
		loop {block::*}:
			set player's current inventory's slot {_n} to stone named "&6name %loop-index%" with lore "&cloc: %loop-value%"
			add 1 to {_n}
on right click:
	loop {block::*}:
		if loop-value is location of target block:
			send "&7%loop-index%"
good?
