### ISSUE TITLE
[Skript] Severe Error: Could not load... 

### ISSUE THREAD

**Issue by Gohu29** [SkriptLang/Skript#1964]
Pretty similar as #1751 but with the version 2.2

```[Skript] Severe Error:
Could not load questreset.sk

If you're developing an add-on for Skript this likely means that you have done something wrong.
If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
and check whether this error has already been reported.
If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
and describe what you did before it happened and/or what you think caused the error.
If you think that it's a trigger that's causing the error please post the trigger as well.
By following this guide fixing the error should be easy and done fast.

Stack trace:
java.lang.NullPointerException
    at com.mineaurion.EconomyBukkit.classEconomy.VaultConnector.currencyNameSingular(VaultConnector.java:53)
    at ch.njol.skript.hooks.economy.classes.Money.parse(Money.java:146)
    at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:59)
    at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:1)
    at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:400)
    at ch.njol.skript.registrations.Classes.parse(Classes.java:429)
    at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97)
    at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86)
    at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1)
    at ch.njol.skript.effects.EffChange.init(EffChange.java:209)
    at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:244)
    at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:171)
    at ch.njol.skript.lang.Statement.parse(Statement.java:60)
    at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:650)
    at ch.njol.skript.command.Commands.loadCommand(Commands.java:466)
    at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:469)
    at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:245)
    at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:199)
    at ch.njol.skript.Skript$2.run(Skript.java:391)
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
    at java.lang.Thread.run(Thread.java:748)

   
Version Information:
  Skript: 2.2-SNAPSHOT
  Bukkit: 1.7.10-R0.1-SNAPSHOT
  Minecraft: 1.7.10
  Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
  OS: Linux amd64 4.9.0-0.bpo.2-amd64

 
Running CraftBukkit: false

Current node: set {_result} to mysql result of query "SELECT * FROM questreset WHERE `uuid` = '%uuid of player%'" (questreset.sk, line 12)
Current item: null

Thread: Server thread

End of Error.```

**Comment by FranKusmiruk** [comment]
We don't support older versions of Skript nor anything below MC 1.9.
