### ISSUE TITLE
Log Handler not stopped

### ISSUE THREAD

**Issue by CameronRedGem** [SkriptLang/Skript#1984]
Server: 1.13.2

Skript Plugins:
SkAction
Skellett
SkQuery
Skript
skript-mirrior (0.19.1)
Umbaska
Vixio

I am currently getting this error after one of the sk files I made are trying to do "on skript load". During the process it just freezes everything on the server and gives off the errors.

[17:58:18 ERROR]: [Skript] 5 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1602)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[17:58:27 ERROR]: [Skript] 120 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:264)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[17:58:28 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:580)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[17:58:34 ERROR]: [Skript] 177 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1602)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

I can't even do /stop on the server so I would have to kill it every time. All the skript files are updated to the latest version.

**Comment by TrademarkTM** [comment]
That's a known bug for skript-mirror 1.0.0 and Skript 2.3+.
Use 2.0.0 instead: https://www.dropbox.com/s/phulkkullzt16ga/skript-mirror%202.0.0.jar?dl=0

**Comment by FranKusmiruk** [comment]
This is caused by skript-mirror.
