### ISSUE TITLE
Bug report parsing 

### ISSUE THREAD

**Issue by DevilishDante** [SkriptLang/Skript#1994]
### Description
hello i don't know why but i have this at the startup 

### Steps to Reproduce
i don't know :/

### Server Information
* **Server version/platform:**     Lastest 1.13.2
* **Skript version:**                Lastest

### Additional Context

Thanks to read me :)

error in console:
```[02:07:00 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:524)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[02:07:00 ERROR]: [Skript] 249 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1588)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[02:07:00 ERROR]: [Skript] 1146 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:253)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[02:07:00 ERROR]: [Skript] 69 log handlers were not stopped properly! (at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:711)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one] ```

**Comment by ShaneBeee** [comment]
That is caused by Skript-Mirror, it is not a Skript issue.
You should try Skript-Mirror 2.0.0

**Comment by DevilishDante** [comment]
@ShaneBeee hi, i only find v0.19.1 on github :/

**Comment by ShaneBeee** [comment]
You can find it [**here**](https://circleci.com/gh/btk5h/skript-mirror)

**Comment by DevilishDante** [comment]
@ShaneBeee thanks but i cannot download or make any thing on link :/
i'm a noob :c

**Comment by Blueyescat** [comment]
Login with GitHub or Bicbucket to the site,
and you will find the download link of **skript-mirror** 2.0.0-**SNAPSHOT** here: https://circleci.com/gh/btk5h/skript-mirror/3#artifacts/containers/0

Also the **!** requirement at the end of the field names is removed in that version. So you will need to convert things like `Class.FIELD!` -> `Class.FIELD`,  `blabla.field!` -> `blabla.field` if you have any.

**Comment by DevilishDante** [comment]
@ShaneBeee Owh really thanks you i don"t know why whit the other link i have blank page X) but with this kink it worked :) and thnaks you for the indication
