### ISSUE TITLE
No commands working- SUPERGUILDS

### ISSUE THREAD

**Issue by Ekuzen** [SkriptLang/Skript#1997]
### Description
 No working commands i write /guilds, /f, /klan, /g and nothing do. I update a Skript frop 2.3.5 to 2.3.6 and nothing difference.

### Expected Behavior
 I try first on version 2.3.5 and only what i saw is a this view (ss under).

### Errors / Screenshots
 https://imgur.com/a/ZyYsyC2

### Server Information
* **Server version/platform:**        1.13.2/Spigot
* **Skript version:**                 Skript.jar 2.3.6 

### Additional Context
 
[22:13:46] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[22:13:46] [Server thread/ERROR]: #!#! 
[22:13:46] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[22:13:46] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:13:46] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[22:13:46] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[22:13:46] [Server thread/ERROR]: #!#! 
[22:13:46] [Server thread/ERROR]: #!#! Stack trace:
[22:13:46] [Server thread/ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: 0
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultFunctions$24.execute(DefaultFunctions.java:356)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultFunctions$24.execute(DefaultFunctions.java:1)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:119)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:204)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ExprFunctionCall.get(ExprFunctionCall.java:44)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:278)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:93)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:119)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:204)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ExprFunctionCall.get(ExprFunctionCall.java:44)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:278)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:93)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:119)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:204)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:53)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:298)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:254)
[22:13:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:169)
[22:13:46] [Server thread/ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:13:46] [Server thread/ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:13:46] [Server thread/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:13:46] [Server thread/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
[22:13:46] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305)
[22:13:46] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:13:46] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[22:13:46] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[22:13:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1628)
[22:13:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476)
[22:13:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:13:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:13:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[22:13:46] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:13:46] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:13:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[22:13:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[22:13:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[22:13:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[22:13:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[22:13:46] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[22:13:46] [Server thread/ERROR]: #!#! 
[22:13:46] [Server thread/ERROR]: #!#! Version Information:
[22:13:46] [Server thread/ERROR]: #!#!   Skript: 2.3.6 (latest)
[22:13:46] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[22:13:46] [Server thread/ERROR]: #!#!     Date: 2019-03-03
[22:13:46] [Server thread/ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[22:13:46] [Server thread/ERROR]: #!#!   Minecraft: 1.13.2
[22:13:46] [Server thread/ERROR]: #!#!   Java: 1.8.0_161 (Java HotSpot(TM) 64-Bit Server VM 25.161-b12)
[22:13:46] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.16.0-5-amd64
[22:13:46] [Server thread/ERROR]: #!#! 
[22:13:46] [Server thread/ERROR]: #!#! Server platform: Spigot
[22:13:46] [Server thread/ERROR]: #!#! 
[22:13:46] [Server thread/ERROR]: #!#! Current node: null
[22:13:46] [Server thread/ERROR]: #!#! Current item: set {_b}(as java.lang.Object) to date({_g::Year}(as java.lang.Number), {_g::Month}(as java.lang.Number), {_g::Day}(as java.lang.Number), {_g::Hour}(as java.lang.Number), {_g::Minute}(as java.lang.Number), {_g::Second}(as java.lang.Number))
[22:13:46] [Server thread/ERROR]: #!#! Current trigger: function timeChecker (simple event) (SUPERGUILDS_0main.sk, line -1)
[22:13:46] [Server thread/ERROR]: #!#! 
[22:13:46] [Server thread/ERROR]: #!#! Thread: Server thread
[22:13:46] [Server thread/ERROR]: #!#! 
[22:13:46] [Server thread/ERROR]: #!#! Language: english
[22:13:46] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[22:13:46] [Server thread/ERROR]: #!#! 
[22:13:46] [Server thread/ERROR]: #!#! End of Error.

**Comment by ShaneBeee** [comment]
You'll have to take this up with the Dev for SuperGuilds. 
This issue tracker is for the Skript plugin itself, not for scripts you find on SpigotMC

**Comment by TrademarkTM** [comment]
Even though this has to do with SuperGuilds, are functions supposed to throw errors when the arguments are invalid?

**Comment by FranKusmiruk** [comment]
Closed it since it's a duplicate, forgot to comment on it, sorry about that.
