### ISSUE TITLE
set slot bug "with lore"

### ISSUE THREAD

**Issue by Cowio** [SkriptLang/Skript#1998]
### Description

Getting error when using:
`set slot 13 of {_p}'s current inventory to 351:8 named "&7&lSælge område" with lore "&c-&8) &7Høst %{bmadgang::%{_uuid}%::sell}%&f/&725 hvede"`

if i delete:
`with lore "&c-&8) &7Høst %{bmadgang::%{_uuid}%::sell}%&f/&725 hvede"`
it gives no errors.

### Code
function openBagmandGUI(p:player):
	set {_uuid} to {_p}'s uuid
	open chest with 3 row named "&7-&8) &c&lBagmand" to {_p}
#panes
	set slot 0, 8, 18 and 26 of {_p}'s current inventory to white glass pane named "&r"
	set slot 1, 7, 9, 17, 19 and 25 of {_p}'s current inventory to gray glass pane named "&r"
#icons
	set slot 11 of {_p}'s current inventory to 351:10 named "&7&lKøbe område" with lore "&c-&8) &7Dræb %{bmadgang::%{_uuid}%::buy}%&f/&75 spillere"
	set slot 13 of {_p}'s current inventory to 351:8 named "&7&lSælge område" with lore "&c-&8) &7Høst %{bmadgang::%{_uuid}%::sell}%&f/&725 hvede"
	set slot 15 of {_p}'s current inventory to 351:8 named "&7&lVåben område" with lore "&c-&8) &7Dræb %{bmadgang::%{_uuid}%::gear}%&f/&71 vagt"
	if {bmadgang::%{_uuid}%::buy} >= 5:
		set slot 11 of {_p}'s current inventory to 351:10 named "&a&lKøbe område" with lore "&c-&8) &7Du har adgang"
	if {bmadgang::%{_uuid}%::sell} >= 25:
		set slot 13 of {_p}'s current inventory to 351:10 named "&a&lSælge område" with lore "&c-&8) &7Du har adgang"
	if {bmadgang::%{_uuid}%::gear} >= 1:
		set slot 15 of {_p}'s current inventory to 351:10 named "&a&lVåben område" with lore "&c-&8) &7Du har adgang"

### Expected Behavior

I want it to have a lore.

### Errors / Screenshots

Skript reload error:
[15:43:48 INFO]: [Skript] Reloading blackmarket.sk...
[15:43:48 ERROR]: ':10 named "&7&lK°be omrÕde" with lore "&c-&8) &7Drµb %{bmadgang::%{_uuid}%::buy}%&f/&75 spillere"' is not a valid item data (blackmarket.sk, line 25: set slot 11 of {_p}'s current inventory to 351:10 named "&7&lK°be omrÕde" with lore "&c-&8) &7Drµb %{bmadgang::%{_uuid}%::buy}%&f/&75 spillere"')
[15:43:48 ERROR]: ':8 named "&7&lSµlge omrÕde" with lore "&c-&8) &7H°st %{bmadgang::%{_uuid}%::sell}%&f/&725 hvede"' is not a valid item data (blackmarket.sk, line 26: set slot 13 of {_p}'s current inventory to 351:8 named "&7&lSµlge omrÕde" with lore "&c-&8) &7H°st %{bmadgang::%{_uuid}%::sell}%&f/&725 hvede"')
[15:43:48 ERROR]: ':8 named "&7&lVÕben omrÕde" with lore "&c-&8) &7Drµb %{bmadgang::%{_uuid}%::gear}%&f/&71 vagt"' is not a valid item data (blackmarket.sk, line 27: set slot 15 of {_p}'s current inventory to 351:8 named "&7&lVÕben omrÕde" with lore "&c-&8) &7Drµb %{bmadgang::%{_uuid}%::gear}%&f/&71 vagt"')
[15:43:48 ERROR]: ':10 named "&a&lK°be omrÕde" with lore "&c-&8) &7Du har adgang"' is not a valid item data (blackmarket.sk, line 29: set slot 11 of {_p}'s current inventory to 351:10 named "&a&lK°be omrÕde" with lore "&c-&8) &7Du har adgang"')
[15:43:48 ERROR]: ':10 named "&a&lSµlge omrÕde" with lore "&c-&8) &7Du har adgang"' is not a valid item data (blackmarket.sk, line 31: set slot 13 of {_p}'s current inventory to 351:10 named "&a&lSµlge omrÕde" with lore "&c-&8) &7Du har adgang"')
[15:43:48 ERROR]: ':10 named "&a&lVÕben omrÕde" with lore "&c-&8) &7Du har adgang"' is not a valid item data (blackmarket.sk, line 33: set slot 15 of {_p}'s current inventory to 351:10 named "&a&lVÕben omrÕde" with lore "&c-&8) &7Du har adgang"')
[15:43:48 INFO]: [Skript] Encountered 6 errors while reloading blackmarket.sk!

Stack trace:
[15:33:27 ERROR]: #!#! Stack trace:
[15:33:27 ERROR]: #!#! java.lang.NumberFormatException: For input string: "351:10"
[15:33:27 ERROR]: #!#!     at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
[15:33:27 ERROR]: #!#!     at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
[15:33:27 ERROR]: #!#!     at java.lang.Double.parseDouble(Unknown Source)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.util.Timespan.parse(Timespan.java:96)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.classes.data.SkriptClasses$8.parse(SkriptClasses.java:401)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.classes.data.SkriptClasses$8.parse(SkriptClasses.java:1)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:422)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:451)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:95)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:84)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.init(EffChange.java:209)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:253)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:972)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:50)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:143)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:636)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:391)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:403)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:436)
[15:33:27 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:181)
[15:33:27 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:33:27 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:33:27 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[15:33:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[15:33:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[15:33:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:33:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:33:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[15:33:27 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:33:27 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[15:33:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[15:33:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[15:33:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[15:33:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[15:33:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[15:33:27 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)

### Server Information
* **Server version/platform: 1.8.8-R0.1-SNAPSHOT**       
* **Skript version: 2.2-dev37c**                

### Additional Context

i have tried searching in aliases: lime dye, gray dye, light green dye.

**Comment by ShaneBeee** [comment]
""Skript version: 2.2-dev37c"" Dev37c has not been supported in quite some time now, nor is 1.8.8 supported by Skript. 

Bug reports are only accepted for the current version of Skript, the current version is 2.3.6

**Comment by TheBentoBox** [comment]
What Shane said
