### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Tanimsiz** [SkriptLang/Skript#2003]
On startup, skript gives error. And none of the skripts loading.
Server: 1.11.2 / Paper
Skript Version: 2.3.6

 ```[14:00:26]

 [Server thread/INFO]: [Skript] Loading variables...
[14:00:26] [Server thread/WARN]: [Skript] 9404 variables were possibly discarded due to not belonging to any database (SQL databases keep such variables and will continue to generate this warning, while CSV discards them).
[14:00:26] [Server thread/WARN]: [Skript] Task #38 for Skript v2.3.6 generated an exception
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.WHITE_GLAZED_TERRACOTTA
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_191]
	at org.bukkit.Material.valueOf(Material.java:1) ~[paper.jar:git-Paper-1104]
	at ch.njol.skript.bukkitutil.BukkitUnsafe.initIdMappings(BukkitUnsafe.java:212) ~[?:?]
	at ch.njol.skript.bukkitutil.BukkitUnsafe.getMaterialFromId(BukkitUnsafe.java:224) ~[?:?]
	at ch.njol.skript.aliases.ItemType.deserialize(ItemType.java:1033) ~[?:?]
	at ch.njol.skript.classes.YggdrasilSerializer.deserialize(YggdrasilSerializer.java:44) ~[?:?]
	at ch.njol.skript.classes.YggdrasilSerializer.deserialize(YggdrasilSerializer.java:1) ~[?:?]
	at ch.njol.yggdrasil.YggdrasilInputStream.readObject(YggdrasilInputStream.java:203) ~[?:?]
	at ch.njol.yggdrasil.YggdrasilInputStream.readObject(YggdrasilInputStream.java:139) ~[?:?]
	at ch.njol.skript.registrations.Classes.deserialize(Classes.java:759) ~[?:?]
	at ch.njol.skript.registrations.Classes.deserialize(Classes.java:748) ~[?:?]
	at ch.njol.skript.variables.FlatFileStorage.load_i(FlatFileStorage.java:137) ~[?:?]
	at ch.njol.skript.variables.VariablesStorage.load(VariablesStorage.java:165) ~[?:?]
	at ch.njol.skript.variables.Variables.load(Variables.java:193) ~[?:?]
	at ch.njol.skript.Skript$2.run(Skript.java:515) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[paper.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [paper.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829) [paper.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [paper.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [paper.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [paper.jar:git-Paper-1104]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191] ```

**Comment by Blueyescat** [comment]
Ok but still no reason to use 1.11.2 when there is 1.13.2 you know :)
