### ISSUE TITLE
No class found for lambda

### ISSUE THREAD

**Issue by Ethnae** [SkriptLang/Skript#2011]
[18:10:14 ERROR]: #!#!
[18:10:14 ERROR]: #!#! [Skript] Severe Error:
[18:10:14 ERROR]: #!#! Could not load snkModeration.sk
[18:10:14 ERROR]: #!#!
[18:10:14 ERROR]: #!#! Something went horribly wrong with Skript.
[18:10:14 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[18:10:14 ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[18:10:14 ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[18:10:14 ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[18:10:14 ERROR]: #!#! nor it will work, unless you switch to supported platform.
[18:10:14 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[18:10:14 ERROR]: #!#!
[18:10:14 ERROR]: #!#! Stack trace:
[18:10:14 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for lambda
[18:10:14 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1804)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1771)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1519)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:325)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:627)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:241)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.Variable.newInstance(Variable.java:151)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseVariable(SkriptParser.java:281)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:429)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:814)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1535)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:81)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1051)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:621)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:389)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:401)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:434)
[18:10:14 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:181)
[18:10:14 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:10:14 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:10:14 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[18:10:14 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[18:10:14 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[18:10:14 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:10:14 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:10:14 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[18:10:14 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[18:10:14 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[18:10:14 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[18:10:14 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[18:10:14 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:10:14 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:10:14 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:10:14 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[18:10:14 ERROR]: #!#!
[18:10:14 ERROR]: #!#! Version Information:
[18:10:14 ERROR]: #!#!   Skript: 2.2-dev36 (OUTDATED)
[18:10:14 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[18:10:14 ERROR]: #!#!   Minecraft: 1.8.8
[18:10:14 ERROR]: #!#!   Java: 1.8.0_201 (Java HotSpot(TM) 64-Bit Server VM 25.201-b09)
[18:10:14 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[18:10:14 ERROR]: #!#!
[18:10:14 ERROR]: #!#! Server platform: Spigot
[18:10:14 ERROR]: #!#!
[18:10:14 ERROR]: #!#! Current node: if {mod.%uuid of player%} is not set: (snkModeration.sk, line 18)
[18:10:14 ERROR]: #!#! Current item: null
[18:10:14 ERROR]: #!#!
[18:10:14 ERROR]: #!#! Thread: Server thread
[18:10:14 ERROR]: #!#!
[18:10:14 ERROR]: #!#! Language: english
[18:10:14 ERROR]: #!#! Link parse mode: DISABLED
[18:10:14 ERROR]: #!#!
[18:10:14 ERROR]: #!#! End of Error.
[18:10:14 ERROR]: #!#!

**Comment by Efnilite** [comment]
This is a skquery problem so update that

**Comment by FranKusmiruk** [comment]
1.  This is an issue from an addon as said above.
2. We do not support older versions of Skript nor 1.8.
