### ISSUE TITLE
worldguard incompatible?

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#2015]
### Steps to Reproduce
I did
```vbs
loop all blocks in region region at location(-2, 35, 2, world):
```
worked previously

### Expected Behavior
provide loop-block to me like it used to

### Errors / Screenshots
```
java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.regions.ProtectedRegion.getMinimumPoint()Lcom/sk89q/worldedit/BlockVector;
	at ch.njol.skript.module.worldguard7fawe.WorldGuard7FAWEHook$WorldGuardRegion.getBlocks(WorldGuard7FAWEHook.java:172) ~[?:?]
	at ch.njol.skript.hooks.regions.expressions.ExprBlocksInRegion$1.<init>(ExprBlocksInRegion.java:87) ~[?:?]
	at ch.njol.skript.hooks.regions.expressions.ExprBlocksInRegion.iterator(ExprBlocksInRegion.java:86) ~[?:?]
	at ch.njol.skript.lang.Loop.walk(Loop.java:79) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
	at ch.njol.skript.effects.Delay$1.run(Delay.java:109) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-f09662d-51d62de]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot.jar:git-Spigot-f09662d-51d62de]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot.jar:git-Spigot-f09662d-51d62de]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f09662d-51d62de]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-f09662d-51d62de]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-f09662d-
```

### Server Information
* **Server version/platform:**       Spigot <Bukkit 1.13.2-R0.1-SNAPSHOT>
* **Skript version:**  Latest

**Comment by bensku** [comment]
It is possible that WorldGuard has broken their API again. In that case, Skript needs an update to match the changes.

**Comment by Blueyescat** [comment]
@MrScopes are you using FAWE?

**Comment by bensku** [comment]
Something seems to be wrong with FAWE WorldGuard on 1.13. We may have to remove support for it.

**Comment by MrScopes** [comment]
> Something seems to be wrong with FAWE WorldGuard on 1.13. We may have to remove support for it.

yeah removing fawe seemed to fix my issue (however, console can't use the command, so no auto mine reset)
