### ISSUE TITLE
Locate items in chest from pos 1 to pos 2.

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2034]
Hey. I have a issue and code. I want command to research items in all chests in region in arg2 and send location of this chest and in which region is it. I've choosen a location from pos1 to pos 2 and it does not work. code: command /szukaj [<text>]:
	trigger:
		if arg 1 is "1":
			set {p1} to target block
			send "&7Zaznaczono jedna pozycje"
		if arg 1 is "2":
			set {p2} to target block
			send "&7Zaznaczono druga pozycje"
		if arg 1 is "szukaj":
			loop blocks within {p1} to {p2}:
				if inventory of loop-block is set:
					if inventory of loop-block contains type of player's tool:
						send "&7Item: &a%type of player's tool% &7Znajduje sie w: &a%location of loop-block%"
		if arg 1 is "chunk":
			loop blocks within chunk at player:
				if inventory of loop-block is set:
					if inventory of loop-block contains type of player's tool:
						send "&7Item: &a%type of player's tool% &7Znajduje sie w: &a%location of loop-block%".

[22:30:28] [Server thread/INFO]: Sebastian_Z_GTA [5fbae8e4-545f-4934-98d4-75c4baa0ad5a]: /szukaj szukaj
[22:30:28] [Server thread/ERROR]: #!#! 
[22:30:28] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[22:30:28] [Server thread/ERROR]: #!#! 
[22:30:28] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[22:30:28] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:30:28] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:30:28] [Server thread/ERROR]: #!#! Here is full list of them:
[22:30:28] [Server thread/ERROR]: #!#! TuSKe (github.com/Tuke-Nuke/TuSKe) SkQuery 
[22:30:28] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[22:30:28] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:30:28] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:30:28] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:30:28] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:30:28] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[22:30:28] [Server thread/ERROR]: #!#! 
[22:30:28] [Server thread/ERROR]: #!#! Stack trace:
[22:30:28] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[22:30:28] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.util.region.CuboidRegion.min(CuboidRegion.java:74)
[22:30:28] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.util.region.CuboidRegion.<init>(CuboidRegion.java:18)
[22:30:28] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.util.region.CuboidIterator.<init>(CuboidIterator.java:12)
[22:30:28] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.elements.expressions.ExprBlockCube.iterator(ExprBlockCube.java:71)
[22:30:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Loop.walk(Loop.java:79)
[22:30:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[22:30:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[22:30:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:298)
[22:30:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255)
[22:30:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:254)
[22:30:28] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:169)
[22:30:28] [Server thread/ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[22:30:28] [Server thread/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:30:28] [Server thread/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[22:30:28] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305)
[22:30:28] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:30:28] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[22:30:28] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[22:30:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1633)
[22:30:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476)
[22:30:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:30:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:30:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[22:30:28] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:30:28] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[22:30:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[22:30:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895)
[22:30:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[22:30:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830)
[22:30:28] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728)
[22:30:28] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[22:30:28] [Server thread/ERROR]: #!#! 
[22:30:28] [Server thread/ERROR]: #!#! Version Information:
[22:30:28] [Server thread/ERROR]: #!#!   Skript: 2.3.6 (latest)
[22:30:28] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[22:30:28] [Server thread/ERROR]: #!#!     Date: 2019-03-03
[22:30:28] [Server thread/ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[22:30:28] [Server thread/ERROR]: #!#!   Minecraft: 1.13.2
[22:30:28] [Server thread/ERROR]: #!#!   Java: 1.8.0_211 (Java HotSpot(TM) 64-Bit Server VM 25.211-b12)
[22:30:28] [Server thread/ERROR]: #!#!   OS: Windows 7 amd64 6.1
[22:30:28] [Server thread/ERROR]: #!#! 
[22:30:28] [Server thread/ERROR]: #!#! Server platform: Spigot
[22:30:28] [Server thread/ERROR]: #!#! 
[22:30:28] [Server thread/ERROR]: #!#! Current node: null
[22:30:28] [Server thread/ERROR]: #!#! Current item: loop cuboid
[22:30:28] [Server thread/ERROR]: #!#! Current trigger: command /szukaj (simple event) (chest.sk, line -1)
[22:30:28] [Server thread/ERROR]: #!#! 
[22:30:28] [Server thread/ERROR]: #!#! Thread: Server thread
[22:30:28] [Server thread/ERROR]: #!#! 
[22:30:28] [Server thread/ERROR]: #!#! Language: english
[22:30:28] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[22:30:28] [Server thread/ERROR]: #!#! 
[22:30:28] [Server thread/ERROR]: #!#! End of Error.
[22:30:28] [Server thread/ERROR]: #!#! 

Version 1.13.2. This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)[m
[22:35:18] [Server thread/INFO]: Checking version, please wait...[m
[22:35:19] [Thread-12/INFO]: You are 182 version(s) behind[m

**Comment by FranKusmiruk** [comment]
The blocks within expression is part of skQuery.
