### ISSUE TITLE
Skript errors (Essentials doesn't work)

### ISSUE THREAD

**Issue by Dreandor** [SkriptLang/Skript#2061]
### Description
Essential Coomands doesn't work. Example /heal:
Unknown command. Type "/help" for help.

### Steps to Reproduce
Install: SKQuery-3.6.5.jar and Skript.jar. Put Essentials.sk into Skript (not scripts)

### Errors / Screenshots

[20:12:35] [Server thread/INFO]: [Skript] Enabling Skript v2.3.6
[20:12:36] [ForkJoinPool.commonPool-worker-1/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m You're currently running the latest stable version of Skript.[m
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:wall_sign is not valid (decoration.sk, line 251: {waterloggable} {directional} wall sign?s = minecraft:wall_sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:sign is not valid (decoration.sk, line 252: {waterloggable} {rotatable} floor sign?s = minecraft:sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id wall sign is not valid (decoration.sk, line 253: [any] sign?s = wall sign, floor sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id wall sign is not valid (decoration.sk, line 253: [any] sign?s = wall sign, floor sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id floor sign is not valid (decoration.sk, line 253: [any] sign?s = wall sign, floor sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id floor sign is not valid (decoration.sk, line 253: [any] sign?s = wall sign, floor sign')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:rose_red is not valid (misc.sk, line 180: (rose red|red dye)?s = minecraft:rose_red')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:rose_red is not valid (misc.sk, line 180: (rose red|red dye)?s = minecraft:rose_red')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:cactus_green is not valid (misc.sk, line 181: (cactus green|green dye)?s = minecraft:cactus_green')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:cactus_green is not valid (misc.sk, line 181: (cactus green|green dye)?s = minecraft:cactus_green')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:dandelion_yellow is not valid (misc.sk, line 190: (dandelion yellow|yellow dye)?s = minecraft:dandelion_yellow')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id minecraft:dandelion_yellow is not valid (misc.sk, line 190: (dandelion yellow|yellow dye)?s = minecraft:dandelion_yellow')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id red dye is not valid (misc.sk, line 195: any dye = black dye, red dye, green dye, brown dye, blue dye, purple dye, cyan dye, light gray dye, gray dye, pink dye, lime dye, yellow dye, light blue dye, magenta dye, orange dye, white dye')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id green dye is not valid (misc.sk, line 195: any dye = black dye, red dye, green dye, brown dye, blue dye, purple dye, cyan dye, light gray dye, gray dye, pink dye, lime dye, yellow dye, light blue dye, magenta dye, orange dye, white dye')
[20:12:37] [Server thread/ERROR]: [Skript] Minecraft id yellow dye is not valid (misc.sk, line 195: any dye = black dye, red dye, green dye, brown dye, blue dye, purple dye, cyan dye, light gray dye, gray dye, pink dye, lime dye, yellow dye, light blue dye, magenta dye, orange dye, white dye')
[20:12:38] [Server thread/ERROR]: [Skript] Minecraft id any sign is not valid (z-click-events.sk, line 7: usable block = anvil, beacon, any bed, brewing stand, cauldron, any chest, crafting table, enchanting table, furnace, any door, any trapdoor, any fence gate, hopper, dispenser, dropper, lever, any button, command block, item frame item, any sign')
[20:12:38] [Server thread/INFO]: [Skript] Loaded 71350 aliases in 3430ms
[20:12:38] [Server thread/ERROR]: Error occurred while enabling Skript v2.3.6 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.entity.Villager$Profession.isZombie()Z
	at ch.njol.skript.entity.VillagerData.<clinit>(VillagerData.java:64) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
	at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:419) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-8043ebc-02b466c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot.jar:git-Spigot-8043ebc-02b466c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot.jar:git-Spigot-8043ebc-02b466c]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot.jar:git-Spigot-8043ebc-02b466c]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot.jar:git-Spigot-8043ebc-02b466c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot.jar:git-Spigot-8043ebc-02b466c]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

### Server Information
* **Server version/platform:**    1.14.1-R0.1-SNAPSHOT
* **Skript version:**         2.3.6

**Comment by Blueyescat** [comment]
1.14 is not supported yet. https://github.com/SkriptLang/Skript#supported-versions

**Comment by TheBentoBox** [comment]
^
