### ISSUE TITLE
Skript Sound Error

### ISSUE THREAD

**Issue by ProfCube** [SkriptLang/Skript#2062]
### Description

>This is just a skript so that if a player wants to mention someone in the game it will highlight the players name and it will make a specific given in the skript it self.
### Steps to Reproduce

>use this Skript

```script
options:
  perm: sk.mention
  noperm: &4You currently don't have permission to mention someone!

on chat:
    if player does not have permission "{@perm}":
        loop all players:
            if message contains "%loop-player%":
                replace all "%loop-player%" with "%loop-player%&r" in message
                stop
    if player has permission "{@perm}":
        loop all players:
            if message contains "%loop-player%":
                replace all "%loop-player%" with "&6@%loop-player%&r" in message  # If you want to change the chat Color, Change the part that say &6&l@ in this line.
                play sound "entity.experience_orb.pickup" with volume 1 and pitch 1 at loop-player
    else:
        send "{@noperm}"
        cancel event
```
>Then in chat just type a players name

### Expected Behavior

>![](https://proxy.spigotmc.org/152ea2a31cc37ee1bb879c9b9383820f2a265f22?url=https%3A%2F%2Fi.gyazo.com%2F19931f4d6e479318569d3e180c07bd60.gif)

### Errors / Screenshots

>[15:15:55 INFO]: [Skript] Reloading Mention.sk...
[15:15:55 INFO]: [Skript] Successfully reloaded Mention.sk.
[15:15:58 INFO]: <ProfCube> @ProfCube
[15:15:58 WARN]: [Skript] Task #100 for Skript v2.3.6 generated an exception
java.lang.NoSuchMethodError: org.bukkit.World.playSound(Lorg/bukkit/Location;Ljava/lang/String;FF)V
        at ch.njol.skript.effects.EffPlaySound.execute(EffPlaySound.java:113) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:57) ~[?:?]
        at ch.njol.skript.events.EvtChat$1.execute(EvtChat.java:72) ~[?:?]
        at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:91) ~[?:?]
        at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:1) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftFuture.run(CraftFuture.java:89) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

### Server Information
* **Server version/platform:** 1.9      
* **Skript version:** 2.3.6                       

### Additional Context

> * **Skellet version:** 1.9.6b  
>Content to be ran will be listed in the ZIP file.
>[Minecraft   1.9 - 1.14.zip](https://github.com/SkriptLang/Skript/files/3189254/Minecraft.1.9.-.1.14.zip)

**Comment by ShaneBeee** [comment]
1) 1.9 is not supported, but 1.9.4 is. You really should upgrade, as there's absolutely no reason to run 1.9 rather than 1.9.4
2) Try using the correct sound enum `ENTITY_EXPERIENCE_ORB_PICKUP `

**Comment by Blueyescat** [comment]
> 2. Try using the **correct** sound enum `ENTITY_EXPERIENCE_ORB_PICKUP `

He didn't want to use the enum name, and the error says the method doesn't exist so not related to the input. The method seems to be exist in 1.9.4. But here is no any reason to use 1.11.2 or below.

**Comment by bensku** [comment]
1.9.4 is oldest supported version.
