### ISSUE TITLE
error

### ISSUE THREAD

**Issue by noy98** [SkriptLang/Skript#2068]
### Description

console error
### Errors / Screenshots

 [18:44:29] [Server thread/INFO] [ch.njol.skript.Skript]: [Skript] Enabling Skript v2.3.6
[18:44:30] [Server thread/ERROR] [Minecraft]: Error occurred while enabling Skript v2.3.6 (Is it up to date?)
java.lang.AssertionError: java.lang.NoSuchFieldException: HARVESTCRAFT_PAMCOCONUT
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:808) ~[TypeAdapters$EnumTypeAdapter.class:?]
	at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:834) ~[TypeAdapters$30.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[Gson.class:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory.create(MapTypeAdapterFactory.java:126) ~[MapTypeAdapterFactory.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:886) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[Gson.class:?]
	at ch.njol.skript.bukkitutil.BukkitUnsafe.loadMaterialMap(BukkitUnsafe.java:175) ~[?:?]
	at ch.njol.skript.bukkitutil.BukkitUnsafe.initialize(BukkitUnsafe.java:116) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:396) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [JavaPluginLoader.class:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [SimplePluginManager.class:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:433) [CraftServer.class:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:382) [CraftServer.class:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:475) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:430) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:599) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchFieldException: HARVESTCRAFT_PAMCOCONUT
	at java.lang.Class.getField(Unknown Source) ~[?:1.8.0_201]
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:797) ~[TypeAdapters$EnumTypeAdapter.class:?]
	... 21 more

### Server Information
* **Server version/platform:**     1.12.2  
* **Skript version:**                2.3.6

**Comment by TheBentoBox** [comment]
Looks like you're using a modded server, Skript doesn't support that.
