### ISSUE TITLE
Error occurred while enabling Skript v2.4-alpha1 (Is it up to date?)

### ISSUE THREAD

**Issue by comonier** [SkriptLang/Skript#2071]
[08:28:02] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-4f661b2-d06991d (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

[08:28:18] [Server thread/ERROR]: Error occurred while enabling Skript v2.4-alpha1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:143) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:397) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.1.jar:git-Spigot-4f661b2-d06991d]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.1.jar:git-Spigot-4f661b2-d06991d]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.1.jar:git-Spigot-4f661b2-d06991d]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.1.jar:git-Spigot-4f661b2-d06991d]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.1.jar:git-Spigot-4f661b2-d06991d]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot-1.14.1.jar:git-Spigot-4f661b2-d06991d]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.1.jar:git-Spigot-4f661b2-d06991d]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot-1.14.1.jar:git-Spigot-4f661b2-d06991d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 16386 path $
	at com.google.gson.Gson.assertFullConsumption(Gson.java:863) ~[spigot-1.14.1.jar:git-Spigot-4f661b2-d06991d]
	at com.google.gson.Gson.fromJson(Gson.java:853) ~[spigot-1.14.1.jar:git-Spigot-4f661b2-d06991d]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[spigot-1.14.1.jar:git-Spigot-4f661b2-d06991d]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[spigot-1.14.1.jar:git-Spigot-4f661b2-d06991d]
	at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:102) ~[?:?]
	... 11 more

**Comment by TheBentoBox** [comment]
Try regenerating your materials file

**Comment by comonier** [comment]
how i do that ?

**Comment by SiebeDW** [comment]
Delete it

**Comment by comonier** [comment]
and were i can found this file ? if its a file ? what's the files name ?

**Comment by TheBentoBox** [comment]
It's called `materials.json`. It's in your Skript folder.

**Comment by comonier** [comment]
it works ty man

**Comment by FargeonMark** [comment]
It didn't work for me, i deleted material.jason

**Comment by AyhamAl-Ali** [comment]
> It didn't work for me, i deleted material.jason

Use SkUnity discord [help channels](https://discord.gg/0l3WlzBPKX7WNjkf)
