### ISSUE TITLE
Log handling error spam/server stalling.

### ISSUE THREAD

**Issue by pzrc** [SkriptLang/Skript#2075]
### Description
When starting up my server **with a non-functioning script**, Skript spams the console with log handling errors. Sometimes, this leads to the server stalling- leading me to force close the console. Running a *functional* script (like https://pastebin.com/f4kxs62e) leads to a similar issue, but it is less harmful.

### Steps to Reproduce
Start up a server with Skript and a *dysfunctional script* or run commands with a *functional* script made in Skript.

### Expected Behavior
I expected the server to start up properly.

### Errors / Screenshots

**Starting server:**
https://pastebin.com/Cv79E3pc

**Running script:**
```
[21:04:20 INFO]: Enantiomers issued server command: /factions help
[21:04:20 INFO]: Enantiomers [aeeb1d3b-95c2-44e2-b849-7d74524c06a4]: /factions help
[21:04:20 ERROR]: [Skript] 4 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1596)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[21:04:22 INFO]: Enantiomers issued server command: /factions h
[21:04:22 INFO]: Enantiomers [aeeb1d3b-95c2-44e2-b849-7d74524c06a4]: /factions h
[21:04:22 ERROR]: [Skript] 4 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1596)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[21:04:23 INFO]: Enantiomers issued server command: /factions ?
[21:04:23 INFO]: Enantiomers [aeeb1d3b-95c2-44e2-b849-7d74524c06a4]: /factions ?
[21:04:23 ERROR]: [Skript] 4 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1596)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
```

### Server Information
* **Server version/platform:** Paper 1.13.2, git-Paper-624      
* **Skript version:** 2.3.6

**Comment by APickledWalrus** [comment]
Do you have any addons installed?

**Comment by pzrc** [comment]
yes, my bad. removing all of the addons fixes the issue, so I assume this does not have to do with Skript itself. sorry for the inconvenience 😕

**Comment by APickledWalrus** [comment]
okay if you have skript-mirror 1.x, that would be the issue I believe

**Comment by SiebeDW** [comment]
Get the 2.0.0 version of skript mirror on circleci

**Comment by pzrc** [comment]
thank you.
