### ISSUE TITLE
Error with Skript

### ISSUE THREAD

**Issue by Showdown76** [SkriptLang/Skript#2129]
[10:06:38 ERROR]: #!#!
[10:06:38 ERROR]: #!#! Stack trace:
[10:06:38 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for lambda
[10:06:38 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1833)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1800)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1548)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:502)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:836)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1564)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1487)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1560)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1494)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1521)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1006)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1093)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:493)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:651)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:409)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:428)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:350)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:380)
[10:06:38 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:527)
[10:06:38 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[10:06:38 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[10:06:38 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[10:06:38 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[10:06:38 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[10:06:38 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[10:06:38 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[10:06:38 ERROR]: #!#!
[10:06:38 ERROR]: #!#! Version Information:
[10:06:38 ERROR]: #!#!   Skript: 2.4-alpha1 (latest)
[10:06:38 ERROR]: #!#!     Flavor: skriptlang-github
[10:06:38 ERROR]: #!#!     Date: 2019-05-18
[10:06:38 ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[10:06:38 ERROR]: #!#!   Minecraft: 1.13.2
[10:06:38 ERROR]: #!#!   Java: 11.0.3 (OpenJDK 64-Bit Server VM 11.0.3+7-Ubuntu-1ubuntu218.04.1)
[10:06:38 ERROR]: #!#!   OS: Linux amd64 4.15.18-11-pve
[10:06:38 ERROR]: #!#!
[10:06:38 ERROR]: #!#! Server platform: Spigot
[10:06:38 ERROR]: #!#!
[10:06:38 ERROR]: #!#! Current node: send "%player%" to bungeecord server "pvp" (goto.sk, line 4)
[10:06:38 ERROR]: #!#! Current item: null
[10:06:38 ERROR]: #!#!
[10:06:38 ERROR]: #!#! Thread: Server thread
[10:06:38 ERROR]: #!#!
[10:06:38 ERROR]: #!#! Language: english
[10:06:38 ERROR]: #!#! Link parse mode: DISABLED
[10:06:38 ERROR]: #!#!
[10:06:38 ERROR]: #!#! End of Error.
[10:06:38 ERROR]: #!#!
[10:06:39 INFO]: [Skript] All scripts loaded without errors.
[10:06:39 INFO]: [Skript] Loaded 1 script with a total of 0 triggers and 0 commands in 0.88 seconds
[10:06:39 INFO]: [Skript] Finished loading.
>

**Comment by Blueyescat** [comment]
Update your skQuery, not related to Skript

**Comment by ShaneBeee** [comment]
also the effect is `send %players% to server %text%` and you are trying to send a string `"%player%"` to a bungee server

**Comment by Blueyescat** [comment]
He didn't try to use the Skript's effect, but yeah Skript has Connect effect: https://skriptlang.github.io/Skript/effects.html#EffConnect

**Comment by ShaneBeee** [comment]
oh, oopies

**Comment by Showdown76** [comment]
Thanks to @Blueyescat : 

> Update your skQuery, not related to Skript
