### ISSUE TITLE
Crash when Removing Item from Inventory

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2143]
### Description

When removing an item from a player's inventory, sometimes the server will crash with an AssertionError. This issue seems to only occur when it's deleting the last item in the item stack (aka item stack of size 1), and does not crash when there are multiple items in an item stack

### Steps to Reproduce
Script:
`
on right click:
remove 1 of event-item from player's inventory
`

### Expected Behavior

Item to be removed without a crash

### Errors / Screenshots

Description: Exception in server tick loop

`java.lang.AssertionError: TRAP
	at net.minecraft.server.v1_14_R1.ItemStack.checkEmpty(ItemStack.java:82)
	at net.minecraft.server.v1_14_R1.ItemStack.setCount(ItemStack.java:851)
	at net.minecraft.server.v1_14_R1.ItemStack.add(ItemStack.java:855)
	at net.minecraft.server.v1_14_R1.ItemStack.subtract(ItemStack.java:859)
	at net.minecraft.server.v1_14_R1.ItemBlock.a(ItemBlock.java:64)
	at net.minecraft.server.v1_14_R1.ItemBlock.a(ItemBlock.java:24)
	at net.minecraft.server.v1_14_R1.ItemStack.placeItem(ItemStack.java:157)
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:476)
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1267)
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13)
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114)
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895)
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99)
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871)
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805)
	at java.lang.Thread.run(Unknown Source)`
### Server Information
* **Server version/platform:**       Spigot 1.14.2
* **Skript version:**                2.4.1-alpha3

### Additional Context

This crash doesn't occur 100% of the time for whatever reason, so multiple attempts may be needed

**Comment by Blueyescat** [comment]
Try to update your Spigot, not related to Skript. But does this way work?
```vb
remove 1 from item amount of event-item
```
As also said in #2092, this way is better for what you are trying to do.

https://github.com/SkriptLang/Skript/issues/2092
https://github.com/SkriptLang/Skript/issues/2133

**Comment by Wealthyturtle** [comment]
Thank you that effect doesn't crash :)

**Comment by Kinoleon** [comment]
I can remove an item with any variant of "remove" as long as I do it with a /command.

But the server crashes if I do it with "on right click" and the item is player's tool.

Those 3 things have a strange connection between them that causes the bug.

**Comment by ShaneBeee** [comment]
> I can remove an item with any variant of "remove" as long as I do it with a /command.
> 
> But the server crashes if I do it with "on right click" and the item is player's tool.
> 
> Those 3 things have a strange connection between them that causes the bug.

The only workaround I have found for this so far is to add a 1 tick wait before removing the tool
I think it's an issue with removing the tool from the player whilst the Spigot/Bukkit event is still computing.

**Comment by Kinoleon** [comment]
> > I can remove an item with any variant of "remove" as long as I do it with a /command.
> > But the server crashes if I do it with "on right click" and the item is player's tool.
> > Those 3 things have a strange connection between them that causes the bug.
> 
> The only workaround I have found for this so far is to add a 1 tick wait before removing the tool
> I think it's an issue with removing the tool from the player whilst the Spigot/Bukkit event is still computing.

At the moment it seems stable.

But I'm also using "`remove 1 from item amount of event-item`", so I don't know which of the 2 things really works, so I don't wanna touch anything else just in case. ;D
