### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by Redstoner875** [SkriptLang/Skript#2182]
### Description
I don't really understand what happened just that the error told me to post it here.

### Steps to Reproduce
I just installed Skript and opened it in the beginning.
### Expected Behavior

No error?
### Errors / Screenshots

[08:31:01 ERROR]: #!#! 
[08:31:01 ERROR]: #!#! Stack trace:
[08:31:01 ERROR]: #!#! java.lang.NoSuchMethodError: org.bukkit.Effect.getName()Ljava/lang/String;
[08:31:01 ERROR]: #!#!     at ch.njol.skript.util.VisualEffect$Type.<init>(VisualEffect.java:196)
[08:31:01 ERROR]: #!#!     at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:63)
[08:31:01 ERROR]: #!#!     at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:269)
[08:31:01 ERROR]: #!#!     at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:891)
[08:31:01 ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:336)
[08:31:01 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[08:31:01 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[08:31:01 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[08:31:01 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[08:31:01 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[08:31:01 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:465)
[08:31:01 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[08:31:01 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:856)
[08:31:01 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:835)
[08:31:01 ERROR]: #!#! 
[08:31:01 ERROR]: #!#! Version Information:
[08:31:01 ERROR]: #!#!   Skript: 2.2-dev36
[08:31:01 ERROR]: #!#!   Bukkit: 1.14.2-R0.1-SNAPSHOT
[08:31:01 ERROR]: #!#!   Minecraft: 1.14.2
[08:31:01 ERROR]: #!#!   Java: 12.0.1 (Java HotSpot(TM) 64-Bit Server VM 12.0.1+12)
[08:31:01 ERROR]: #!#!   OS: Mac OS X x86_64 10.14.5
[08:31:01 ERROR]: #!#! 
[08:31:01 ERROR]: #!#! Server platform: Paper
[08:31:01 ERROR]: #!#! 
[08:31:01 ERROR]: #!#! Current node: null
[08:31:01 ERROR]: #!#! Current item: null
[08:31:01 ERROR]: #!#! 
[08:31:01 ERROR]: #!#! Thread: Server thread
[08:31:01 ERROR]: #!#! 
[08:31:01 ERROR]: #!#! Language: english
[08:31:01 ERROR]: #!#! Link parse mode: DISABLED
[08:31:01 ERROR]: #!#! 
[08:31:01 ERROR]: #!#! End of Error.
[08:31:01 ERROR]: #!#! 

### Server Information
* **Server version/platform:**       1.14.2 paper
* **Skript version:**                2.2-dev36

**Comment by ShaneBeee** [comment]
Only Skript 2.4+ works on Spigot/Paper 1.14.x
Any version below will not load, and will produce errors like this
