### ISSUE TITLE
Skript doesn't work with Paper 1.14.2

### ISSUE THREAD

**Issue by Chriskraft9** [SkriptLang/Skript#2190]
Enabling Skript v2.4-alpha3
[10:32:44] [Server thread/ERROR]: Error occurred while enabling Skript v2.4-alpha3 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:143) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:402) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.2.jar:git-Paper-105]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.2.jar:git-Paper-105]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464) ~[patched_1.14.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378) ~[patched_1.14.2.jar:git-Paper-105]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:465) ~[patched_1.14.2.jar:git-Paper-105]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.14.2.jar:git-Paper-105]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:856) ~[patched_1.14.2.jar:git-Paper-105]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 16386 path $
	at com.google.gson.Gson.assertFullConsumption(Gson.java:863) ~[patched_1.14.2.jar:git-Paper-105]
	at com.google.gson.Gson.fromJson(Gson.java:853) ~[patched_1.14.2.jar:git-Paper-105]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[patched_1.14.2.jar:git-Paper-105]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[patched_1.14.2.jar:git-Paper-105]
	at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:102) ~[?:?]
	... 11 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 16386 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[patched_1.14.2.jar:git-Paper-105]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[patched_1.14.2.jar:git-Paper-105]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542) ~[patched_1.14.2.jar:git-Paper-105]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[patched_1.14.2.jar:git-Paper-105]
	at com.google.gson.Gson.assertFullConsumption(Gson.java:859) ~[patched_1.14.2.jar:git-Paper-105]
	at com.google.gson.Gson.fromJson(Gson.java:853) ~[patched_1.14.2.jar:git-Paper-105]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[patched_1.14.2.jar:git-Paper-105]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[patched_1.14.2.jar:git-Paper-105]
	at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:102) ~[?:?]
	... 11 more
[10:32:44] [Server thread/INFO]: [Skript] Disabling Skript v2.4-alpha3

**Comment by Chriskraft9** [comment]
Fixed with deleting materials.json
