### ISSUE TITLE
Severe error on 1.14.3

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#2202]
Got while starting server on 1.14.3:
[20:52:49 ERROR]: #!#!
[20:52:49 ERROR]: #!#! [Skript] Severe Error:
[20:52:49 ERROR]: #!#! Version supports setTamed but MethodHandle lookup failed
[20:52:49 ERROR]: #!#!
[20:52:49 ERROR]: #!#! Something went horribly wrong with Skript.
[20:52:49 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:52:49 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:52:49 ERROR]: #!#! Here is full list of them:
[20:52:49 ERROR]: #!#! skUtilities (https://tim740.github.io/)
[20:52:49 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:52:49 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:52:49 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:52:49 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:52:49 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:52:49 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:52:49 ERROR]: #!#!
[20:52:49 ERROR]: #!#! Stack trace:
[20:52:49 ERROR]: #!#! java.lang.IllegalAccessException: no private access for invokespecial: interface org.bukkit.entity.Ocelot, from java.lang.Object/public
[20:52:49 ERROR]: #!#! at java.lang.invoke.MemberName.makeAccessException(MemberName.java:850)
[20:52:49 ERROR]: #!#! at java.lang.invoke.MethodHandles$Lookup.checkSpecialCaller(MethodHandles.java:1572)
[20:52:49 ERROR]: #!#! at java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:1002)
[20:52:49 ERROR]: #!#! at ch.njol.skript.entity.OcelotData.<clinit>(OcelotData.java:46)
[20:52:49 ERROR]: #!#! at java.lang.Class.forName0(Native Method)
[20:52:49 ERROR]: #!#! at java.lang.Class.forName(Class.java:348)
[20:52:49 ERROR]: #!#! at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[20:52:49 ERROR]: #!#! at ch.njol.skript.Skript.onEnable(Skript.java:426)
[20:52:49 ERROR]: #!#! at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[20:52:49 ERROR]: #!#! at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[20:52:49 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[20:52:49 ERROR]: #!#! at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[20:52:49 ERROR]: #!#! at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[20:52:49 ERROR]: #!#! at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[20:52:49 ERROR]: #!#! at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282)
[20:52:49 ERROR]: #!#! at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:859)
[20:52:49 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
[20:52:49 ERROR]: #!#!
[20:52:49 ERROR]: #!#! Version Information:
[20:52:49 ERROR]: #!#! Skript: 2.4-alpha4 (latest)
[20:52:49 ERROR]: #!#! Flavor: skriptlang-github
[20:52:49 ERROR]: #!#! Date: 2019-06-27
[20:52:49 ERROR]: #!#! Bukkit: 1.14.3-R0.1-SNAPSHOT
[20:52:49 ERROR]: #!#! Minecraft: 1.14.3
[20:52:49 ERROR]: #!#! Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b01)
[20:52:49 ERROR]: #!#! OS: Linux amd64 4.4.0-150-generic
[20:52:49 ERROR]: #!#!
[20:52:49 ERROR]: #!#! Server platform: Paper
[20:52:49 ERROR]: #!#!
[20:52:49 ERROR]: #!#! Current node: null
[20:52:49 ERROR]: #!#! Current item: null
[20:52:49 ERROR]: #!#!
[20:52:49 ERROR]: #!#! Thread: Server thread
[20:52:49 ERROR]: #!#!
[20:52:49 ERROR]: #!#! Language: english
[20:52:49 ERROR]: #!#! Link parse mode: DISABLED
[20:52:49 ERROR]: #!#!
[20:52:49 ERROR]: #!#! End of Error.
[20:52:49 ERROR]: #!#!

**Comment by TheBentoBox** [comment]
Closing for #2203 since it uses the issue format.
