### ISSUE TITLE
log handlers freezing server

### ISSUE THREAD

**Issue by melinstagibson** [SkriptLang/Skript#2219]
i get those errors on every startup and in 4 out of 5 cases it freezes the server for a long time or i just try restarting till it works...

```
[05:11:39 ERROR]: [Skript] 490 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:253)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[05:11:39 ERROR]: [Skript] 18 log handlers were not stopped properly! (at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[05:11:56 ERROR]: [Skript] 1661 log handlers were not stopped properly! (at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:350)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
```
i have the latest version of skript, skript-mirror, skript-db and skungee. this error caused issues for me since over a year now throughout every update. any idea how to fix it or disable the logs?

**Comment by Moderocky** [comment]
Are you using skript-mirror 1.0.0, or the 2.0.0 snapshot?

**Comment by melinstagibson** [comment]
im using 1.0.0 could you point me to the 2.0.0 snapshot, didnt find it in 5 minutes :p

**Comment by SiebeDW** [comment]
https://circleci.com/gh/btk5h/skript-mirror

**Comment by Moderocky** [comment]
You will need to sign in to see the download button, by the way. :)

**Comment by TheBentoBox** [comment]
Presumably resolved by the mirror update.
