### ISSUE TITLE
Skript cant load scripts

### ISSUE THREAD

**Issue by DSArtyFixLife** [SkriptLang/Skript#2222]
Hi, my script is not being loaded and after executing the command "/skript reload artysscript" in minecraft I will receive the following error: "An internal error occured while attempting to perform this command" and the console prints the following error:
`
[18:19:34 INFO]: ItzArty_ issued server command: /skript reload artysscript
[18:19:34 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'skript' in plugin Skript v2.2-dev36
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_211]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoSuchMethodError: ch.njol.skript.command.Commands.loadCommand(Lch/njol/skript/config/SectionNode;Z)Lch/njol/skript/command/ScriptCommand;
        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:621) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:389) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:401) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:434) ~[?:?]
        at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:181) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        ... 15 more
`

Here is what the script contains:
`
options:

    vermsg: "&aServer &7» &fNeznámy príkaz"
    unkcmd: "&aServer &7» &fNeznámy príkaz"
    noperm: "&aServer &7» &fNemáš oprávnenie na tento príkaz"

command /clearchat:
    description: Clears chat for all players
    aliases: /chatclear
    trigger:
        if player has permission "as.clearchat":
            loop 175 times:
                broadcast " "
            broadcast "&aServer &7» &f%player% dal vyčistiť chat"
        else:
            message {@noperm}
`

I use Skript v2.2 dev36 on Spigot server version 1.8.8 in offline mode, provided on OS Windows 10 Home with Java 8 x64 (build 1.8.0_211-b12).

**NOTE** I also use Umbaska 3.3 and skQuery

**Comment by DSArtyFixLife** [comment]
**FIXED BY REMOVING SKQUERY**
