### ISSUE TITLE
skQuery breaks Skript command functionality

### ISSUE THREAD

**Issue by DSArtyFixLife** [SkriptLang/Skript#2224]
Hi, my issue is based on that skQuery actually makes  skript not be able to load scripts with the command statement. How I know that it is caused by skQuery? Here is how: After removing skQuery the issue was gone, but I need skQuery since I want to create guis. Here are mine versions: Server: Spigot - 1.8.8, skQuery - v4.0 from bukkit and Skript - 2.2-dev36. What I cant understand is that on my VPS with debian 9 the combination of plugins worked fine but after switching to mine pc with Windows 10 Home, Java 8 x64 the combation was bad. Here is the error printed after executing "/skript enable command with cooldown":
`
[18:57:00 INFO]: [Skript] Enabling command with cooldown.sk...
[18:57:00 WARN]: Unexpected exception while parsing console command "skript enable command with cooldown"
org.bukkit.command.CommandException: Unhandled exception executing command 'skript' in plugin Skript v2.2-dev36
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoSuchMethodError: ch.njol.skript.command.Commands.loadCommand(Lch/njol/skript/config/SectionNode;Z)Lch/njol/skript/command/ScriptCommand;
        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:621) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:389) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:401) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:434) ~[?:?]
        at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:230) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        ... 8 more
`

**Comment by FranKusmiruk** [comment]
Addon issues should be reported to their corresponsing issue trackers and we don't support older versions of Skript.

**Comment by gp-Airee** [comment]
This is the Skript repository, not the SkQuery repository. Are you reporting this in the correct place?

**Comment by DSArtyFixLife** [comment]
But where I have to post this? I was looking for skQuery error report but I found nothing

**Comment by TrademarkTM** [comment]
You shouldn't post this anywhere.
That skQuery version is outdated and is basically an experiment from LimeGlass (the author).

https://www.spigotmc.org/resources/skquery-1-9-1-13.36631/
Use the 3.6.1 version from that link, and the latest one for Skript 2.3+.

Test your scripts without addons before creating an issue. If it is related to an addon, consider not using it or changing the version, because there is no support for them here.

**Comment by DSArtyFixLife** [comment]
But I really want to use 1.8 :((

**Comment by DSArtyFixLife** [comment]
+ I have tested it. Then I wanted to create GUIs, and for that I need skQuery, and this is the real problem.
