### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by Alperenn** [SkriptLang/Skript#2231]
`[00:58:38] [Server thread/INFO]: [TuSKe] Enabling TuSKe v1.8.2
[00:58:38] [Server thread/INFO]: [TuSKe] Enabling Metrics... Done!
[00:58:38] [Server thread/INFO]: [TuSKe] Check for updates enabled. It will check in some seconds.
[00:58:38] [Server thread/INFO]: [TuSKe] Documentation enabled. Some files containing all syntax of all addons will be generated.
[00:58:38] [Server thread/INFO]: [TuSKe]  
[00:58:38] [Server thread/INFO]: [TuSKe]  A special thanks for donators:
[00:58:38] [Server thread/INFO]: [TuSKe]  @X0Freak - 50$
[00:58:38] [Server thread/INFO]: [TuSKe]  @RepublicanSensei - 10$
[00:58:38] [Server thread/INFO]: [TuSKe]  
[00:58:38] [Server thread/ERROR]: #!#! 
[00:58:38] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[00:58:38] [Server thread/ERROR]: #!#! TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception while loading
[00:58:38] [Server thread/ERROR]: #!#! 
[00:58:38] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[00:58:38] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:58:38] [Server thread/ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[00:58:38] [Server thread/ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[00:58:38] [Server thread/ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[00:58:38] [Server thread/ERROR]: #!#! nor it will work, unless you switch to supported platform.
[00:58:38] [Server thread/ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[00:58:38] [Server thread/ERROR]: #!#! 
[00:58:38] [Server thread/ERROR]: #!#! Stack trace:
[00:58:38] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[00:58:38] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
[00:58:38] [Server thread/ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[00:58:38] [Server thread/ERROR]: #!#!     at java.lang.Class.forName(Class.java:348)
[00:58:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[00:58:38] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.TuSKe.onEnable(TuSKe.java:100)
[00:58:38] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[00:58:38] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[00:58:38] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[00:58:38] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[00:58:38] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[00:58:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[00:58:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[00:58:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[00:58:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[00:58:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[00:58:38] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[00:58:38] [Server thread/ERROR]: #!#! 
[00:58:38] [Server thread/ERROR]: #!#! Version Information:
[00:58:38] [Server thread/ERROR]: #!#!   Skript: 2.2-dev36
[00:58:38] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[00:58:38] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[00:58:38] [Server thread/ERROR]: #!#!   Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b04)
[00:58:38] [Server thread/ERROR]: #!#!   OS: Linux amd64 2.6.32-754.15.3.el6.x86_64
[00:58:38] [Server thread/ERROR]: #!#! 
[00:58:38] [Server thread/ERROR]: #!#! Server platform: Paper
[00:58:38] [Server thread/ERROR]: #!#! 
[00:58:38] [Server thread/ERROR]: #!#! Current node: null
[00:58:38] [Server thread/ERROR]: #!#! Current item: null
[00:58:38] [Server thread/ERROR]: #!#! 
[00:58:38] [Server thread/ERROR]: #!#! Thread: Server thread
[00:58:38] [Server thread/ERROR]: #!#! 
[00:58:38] [Server thread/ERROR]: #!#! Language: english
[00:58:38] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[00:58:38] [Server thread/ERROR]: #!#! 
[00:58:38] [Server thread/ERROR]: #!#! End of Error.
[00:58:38] [Server thread/ERROR]: #!#! 
[00:58:38] [Server thread/INFO]: [TuSKe] Loaded 8 events, 12 conditions, 20 effects, 61 expressions and 0 types. Have fun!`

**Comment by Alperenn** [comment]
http://pasted.co/179dd2e2

**Comment by TPGamesNL** [comment]
Not a Skript issue.
Fix it by using Pikachu's TuSKe patch

**Comment by lethalityy** [comment]
Yav kardeşim sen bu gavurları salla, aptalın teki bunlar bak 
skriptin configine gir taammı

**parse links in chat messages** kısmı var onun karşısında disabled yazacaktır onu **lenient** olarak değiştir

Kolay gelsin
aptal gavurlar hiç bişey bilmiyorlar

**Comment by lethalityy** [comment]
If you want to fix this error
First open config.sk in skript folder find **parse links in chat messages** and change **disabled** to **lenient**

Thanks oSoloTurk for helps.

**Comment by NanoDankster** [comment]
> Yav kardeşim sen bu gavurları salla, aptalın teki bunlar bak
> skriptin configine gir taammı
> 
> **parse links in chat messages** kısmı var onun karşısında disabled yazacaktır onu **lenient** olarak değiştir
> 
> Kolay gelsin
> aptal gavurlar hiç bişey bilmiyorlar
> 
> **oSoloTurk'e yardımı için teşekkürler**


> If you want to fix this error
> First open config.sk in skript folder find **parse links in chat messages** and change it **disabled** to **lenient**
> 
> Thanks oSoloTurk for helps.

Please don't post incorrect answers to the question. This question doesn't belong here in the first place.

Also stop swearing. You're an embarrassment to the Turkish community.
