### ISSUE TITLE
Function max throws an error when input is empty

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2258]
### Description

Using the default function max throws an error when using an empty list variable as imput

### Steps to Reproduce

```
command /test:
    trigger:
        send "%max({_h::*})%"
```
Used to throw no error and return nothing, now it does

### Expected Behavior

Should return 0 or do nothing

### Errors / Screenshots

Console stacktrace :
```
[14:50:03] [Server thread/ERROR]: #!#! 
[14:50:03] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[14:50:03] [Server thread/ERROR]: #!#! 
[14:50:03] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[14:50:03] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:50:03] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[14:50:03] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[14:50:03] [Server thread/ERROR]: #!#! 
[14:50:03] [Server thread/ERROR]: #!#! Stack trace:
[14:50:03] [Server thread/ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: 0
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultFunctions$20.execute(DefaultFunctions.java:265)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultFunctions$20.execute(DefaultFunctions.java:1)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:119)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:204)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ExprFunctionCall.get(ExprFunctionCall.java:44)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:459)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:623)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:1)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:66)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[14:50:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:195)
[14:50:03] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:50:03] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[14:50:03] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707)
[14:50:03] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:692)
[14:50:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.lambda$3(DedicatedServer.java:667)
[14:50:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.b(SourceFile:55)
[14:50:03] [Server thread/ERROR]: #!#!     at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
[14:50:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[14:50:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135)
[14:50:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:50:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114)
[14:50:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898)
[14:50:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891)
[14:50:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99)
[14:50:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:874)
[14:50:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808)
[14:50:03] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[14:50:03] [Server thread/ERROR]: #!#! 
[14:50:03] [Server thread/ERROR]: #!#! Version Information:
[14:50:03] [Server thread/ERROR]: #!#!   Skript: 2.4-alpha4 (custom version)
[14:50:03] [Server thread/ERROR]: #!#!     Flavor: selfbuilt-unknown
[14:50:03] [Server thread/ERROR]: #!#!     Date: unknown
[14:50:03] [Server thread/ERROR]: #!#!   Bukkit: 1.14.3-R0.1-SNAPSHOT
[14:50:03] [Server thread/ERROR]: #!#!   Minecraft: 1.14.3
[14:50:03] [Server thread/ERROR]: #!#!   Java: 1.8.0_201 (Java HotSpot(TM) 64-Bit Server VM 25.201-b09)
[14:50:03] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.4.0-141-generic
[14:50:03] [Server thread/ERROR]: #!#! 
[14:50:03] [Server thread/ERROR]: #!#! Server platform: Spigot
[14:50:03] [Server thread/ERROR]: #!#! 
[14:50:03] [Server thread/ERROR]: #!#! Current node: null
[14:50:03] [Server thread/ERROR]: #!#! Current item: broadcast "%max({_h::*}(as java.lang.Number))%"
[14:50:03] [Server thread/ERROR]: #!#! Current trigger: command /test (simple event) (test.sk, line -1)
[14:50:03] [Server thread/ERROR]: #!#! 
[14:50:03] [Server thread/ERROR]: #!#! Thread: Server thread
[14:50:03] [Server thread/ERROR]: #!#! 
[14:50:03] [Server thread/ERROR]: #!#! Language: english
[14:50:03] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[14:50:03] [Server thread/ERROR]: #!#! 
[14:50:03] [Server thread/ERROR]: #!#! End of Error.
[14:50:03] [Server thread/ERROR]: #!#! 
```

### Server Information
* **Server version/platform:** Spigot 1.14.3
* **Skript version:** 2.4-alpha4 (the stacktrace says custom version but i just downloaded the code and additional modules and built them to test something)

**Comment by TPGamesNL** [comment]
Probably related to https://github.com/SkriptLang/Skript/issues/1767. (same cause: function argument not set, ArrayIndexOutOfBoundsException)

**Comment by Matocolotoe** [comment]
Also happens when input is not a complete list of numbers.

**Comment by Matocolotoe** [comment]
Closing in favor of #2384
