### ISSUE TITLE
CAN I USE THIS PLUGIN on pixelmonsever?

### ISSUE THREAD

**Issue by dauchu** [SkriptLang/Skript#2269]
### Question
When I use this plugin on pixelmonserver(cat server) but It dosen't work and bukkit said rror occurred while enabling PluginManagerReloaded v1.0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: org/mcstats/Metrics
        at com.jadeningle.PluginManager.PluginManagerReloaded.onEnable(PluginManagerReloaded.java:75) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [JavaPluginLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [SimplePluginManager.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:433) [CraftServer.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:382) [CraftServer.class:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:475) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:430) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:599) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: org.mcstats.Metrics
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:127) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[PluginClassLoader.class:git-Spigot-dcd1643-e60fc34]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        ... 12 more
so how can I use this plugin on server?

**Comment by Blueyescat** [comment]
This issue tracker is not for issues with any spigot plugin 🤦‍♀ please close the issue.
