### ISSUE TITLE
TRAP

### ISSUE THREAD

**Issue by LoganTheOverlord** [SkriptLang/Skript#2299]
### Description

Server crashes when on rightclick event item is removed during that event
### Steps to Reproduce

Remove item from player when right-click event is fired
### Expected Behavior

You know
### Errors / Screenshots

[Server thread/ERROR]: Encountered an unexpected exception 
java.lang.AssertionError: TRAP 
at net.minecraft.server.v1_14_R1.ItemStack.checkEmpty(ItemStack.java:82) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.ItemStack.setCount(ItemStack.java:851) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:394) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1293) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887) ~[server.jar:git-Spigot-9de398a-9c887d4] 
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820) [server.jar:git-Spigot-9de398a-9c887d4] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171] 
>[2K [15:33:12] [Server thread/ERROR]: This crash report has been saved to: /home/hosting/servers/220892/./crash-reports/crash-2019-07-25_15.33.12-server.txt 

### Server Information
* **Server version/platform:**   1.14.4 Spigot    
* **Skript version:**        Latest

**Comment by Alderheart** [comment]
It seems to work if you use "remove 1 from item amount of event-item." That's what I did and it no longer crashes.

**Comment by infmemory** [comment]
Had a similar error when I was working on a 3x3 planter script. In my case I had a `rightclick on soil` event (which I didn't cancel). If I held too few items I believe it continued the event but freaked out when there were no items to be planted. Here is a "shortened" script which reproduces the same crash:

```
on rightclick on soil using wheat seed:
    remove 1 wheat seed from player
```

Hold 1 wheat seed when attempting to plant on soil to reproduce.

Here is my crash report (Skript 2.4-beta3):
```
--- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/26/19 10:51 AM
Description: Exception in server tick loop

java.lang.AssertionError: TRAP
	at net.minecraft.server.v1_14_R1.ItemStack.checkEmpty(ItemStack.java:109)
	at net.minecraft.server.v1_14_R1.ItemStack.setCount(ItemStack.java:897)
	at net.minecraft.server.v1_14_R1.ItemStack.add(ItemStack.java:901)
	at net.minecraft.server.v1_14_R1.ItemStack.subtract(ItemStack.java:905)
	at net.minecraft.server.v1_14_R1.ItemBlock.a(ItemBlock.java:64)
	at net.minecraft.server.v1_14_R1.ItemBlock.a(ItemBlock.java:24)
	at net.minecraft.server.v1_14_R1.ItemStack.placeItem(ItemStack.java:185)
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:499)
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361)
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1014)
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1007)
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:991)
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:924)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 751963888 bytes (717 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 8
	JVM Flags: 12 total; -Xms3G -Xmx3G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled
	CraftBukkit Information: 
   Running: Paper version git-Paper-138 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT) true
   Plugins: { WorldEdit v7.0.1-rc1;edb2e91 com.sk89q.worldedit.bukkit.WorldEditPlugin [], Skript v2.4-beta3 ch.njol.skript.Skript [Njol, Mirreski, bensku, TheBentoBox, Snow-Pyon, Pikachu920, Nicofisi, tim740, Tuke-Nuke, TheLimeGlass, xXAndrew28Xx, Sashie, RoyCurtis, nfell2009, Syst3ms, Blueyescat], WorldGuard v7.0.1-beta-01;14e7525 com.sk89q.worldguard.bukkit.WorldGuardPlugin [],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { RUNNABLE Log4j2-TF-1-AsyncLogger[AsyncContext@5c647e05]-1: [java.lang.Package.defineSystemPackage(Unknown Source), java.lang.Package.getSystemPackage(Unknown Source), java.lang.Package.getPackage(Unknown Source), java.lang.Class.getPackage(Unknown Source), org.apache.logging.log4j.core.impl.ThrowableProxy.toCacheEntry(ThrowableProxy.java:598), org.apache.logging.log4j.core.impl.ThrowableProxy.toExtendedStackTrace(ThrowableProxy.java:647), org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:138), org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:122), org.apache.logging.log4j.core.async.RingBufferLogEvent.getThrownProxy(RingBufferLogEvent.java:330), org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:61), org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38), org.apache.logging.log4j.core.layout.PatternLayout$PatternSelectorSerializer.toSerializable(PatternLayout.java:455), org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:232), org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:217), org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57), org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:177), org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170), org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161), org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender.append(RollingRandomAccessFileAppender.java:218), org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156), org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129), org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120), org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84), org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448), org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433), org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417), org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:79), org.apache.logging.log4j.core.async.AsyncLogger.actualAsyncLog(AsyncLogger.java:337), org.apache.logging.log4j.core.async.RingBufferLogEvent.execute(RingBufferLogEvent.java:161), org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:45), org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:29), com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168), com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Signal Dispatcher: [], WAITING Paper Async Task Handler Thread - 0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Thread-7: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.ArrayBlockingQueue.take(Unknown Source), ch.njol.skript.ScriptLoader$AsyncLoaderThread.run(ScriptLoader.java:322)], TIMED_WAITING Timer-1: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], RUNNABLE Attach Listener: [], TIMED_WAITING Server console handler: [java.lang.Object.wait(Native Method), org.jline.utils.NonBlockingPumpReader.wait(NonBlockingPumpReader.java:55), org.jline.utils.NonBlockingPumpReader.read(NonBlockingPumpReader.java:101), org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57), org.jline.keymap.BindingReader.readCharacter(BindingReader.java:133), org.jline.keymap.BindingReader.readBinding(BindingReader.java:110), org.jline.keymap.BindingReader.readBinding(BindingReader.java:61), org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:786), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:558), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:404), net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:157), net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:140), net.minecraft.server.v1_14_R1.DedicatedServer$2.run(DedicatedServer.java:89)], TIMED_WAITING Timer-0: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], TIMED_WAITING Timer-2: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], TIMED_WAITING Abandoned connection cleanup thread: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:64), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty Server IO #2: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Unknown Source)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_14_R1.DedicatedServer$1.run(DedicatedServer.java:71)], TIMED_WAITING ObjectCleanerThread: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.lang.Thread.run(Unknown Source)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_14_R1.CraftCrashReport.call(CraftCrashReport.java:33), net.minecraft.server.v1_14_R1.CrashReportSystemDetails.a(SourceFile:79), net.minecraft.server.v1_14_R1.CrashReport.h(CrashReport.java:71), net.minecraft.server.v1_14_R1.CrashReport.<init>(CrashReport.java:35), net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:945), java.lang.Thread.run(Unknown Source)], RUNNABLE WindowsStreamPump: [com.sun.jna.Native.invokeInt(Native Method), com.sun.jna.Function.invoke(Function.java:419), com.sun.jna.Function.invoke(Function.java:354), com.sun.jna.Library$Handler.invoke(Library.java:244), org.jline.terminal.impl.jna.win.$Proxy18.WaitForSingleObject(Unknown Source), org.jline.terminal.impl.jna.win.JnaWinSysTerminal.readConsoleInput(JnaWinSysTerminal.java:176), org.jline.terminal.impl.jna.win.JnaWinSysTerminal.processConsoleInput(JnaWinSysTerminal.java:99), org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:459), org.jline.terminal.impl.AbstractWindowsTerminal$$Lambda$12/416153648.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), java.lang.ref.Reference.tryHandlePending(Unknown Source), java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], WAITING Skript variable save thread: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), ch.njol.skript.variables.Variables$2.run(Variables.java:548), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty Server IO #3: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Unknown Source)], WAITING Resource IO {0}: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Timer-3: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING Skript variable save thread for database 'default': [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), ch.njol.skript.variables.VariablesStorage$1.run(VariablesStorage.java:76), java.lang.Thread.run(Unknown Source)], WAITING Craft Async Scheduler Management Thread: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Paper Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:145)], RUNNABLE Netty Server IO #1: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty Server IO #0: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Unknown Source)], RUNNABLE DestroyJavaVM: [],}
   
   Force Loaded Chunks: { world: {}, world_nether: {}, world_the_end: {},}
	Player Count: 1 / 20; [EntityPlayer['Infinitememory'/416698, uuid='fb2250ca-0f12-467d-b894-fbd8fda2762c', l='world', x=1790.15, y=69.94, z=-2233.22, cx=111, cz=-140, tl=7092849, v=true, d=false](Infinitememory at 1790.1470726903083,69.9375,-2233.21617173328)]
	Data Packs: vanilla, file/bukkit (incompatible), file/crafting_custom_dispenser (incompatible), file/player graves v1.5.1.zip
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Wealthyturtle** [comment]
This is a duplicate issue and is due to Spigot, use the work around provided by @alderheart

**Comment by Blueyescat** [comment]
https://github.com/SkriptLang/Skript/issues/2143#issuecomment-499615192
