### ISSUE TITLE
None skript will load.. 0 commands, 0 triggers... But I have a lot of commands

### ISSUE THREAD

**Issue by 1KleineKuh** [SkriptLang/Skript#2304]
### Description
If I want to reload a skript, there is an error in console, and I dont have any commands

### Steps to Reproduce
on load:
	loop all players:
		if loop-player has permission "group.dev" or "group.admin" or "group.owner":
			wait 2 seconds
			send "&8»" to loop-player
			send "&e&lName &8» &7%{server::*}%-Skript" to loop-player
			send "&e&lVersion &8» &71.4.3" to loop-player
			send "&e&lDeveloper &8» &71KleineKuh" to loop-player
			send "&e&lZeilen &8» &72054" to loop-player
			send "&8»" to loop-player

options:
	prefix: §a§l%{Server::*}% §8>> &7
	Prefix: §a§l%{Server::*}% §8>> &7
	P: §a§l%{Server::*}% §8>> &7
	P1: §a§l%{Server::*}% §8>> &7
	Permission: §7Dazu hast du keine §eBerechtigung§7!
	
Command /setservername [<text>]:
	trigger:
		if player has permission "system.server.set":
			set {Server::*} to arg 1
			send "&8[&eServer&8] &7Der &eServer Name &7wurde auf &e%arg 1% &7gesetzt."

Command /startmoney [<number>]:
	trigger:
		if player has permission "server.config":
			if arg 1 is set:
				set {startmoney::*} to "%arg 1%"
				send "&8[&eConfig&8] &7Du hast das &eStartmoney &7zu &e$%arg 1% &7gesetzt&8."
			else:
				send "&8[&eConfig&8] &7Bitte gebe einen Geldbetrag an! &8/&estartmoney <Geldbetrag> &8(&eOhne $ z.B 2501&8)"
		else:
			send "&8[&eConfig&8] &7Dazu hast du keine &eBerechtigung&7."
Command /dev:
	trigger:
		send "&8[&eEntwickler&8] &7Der Entwickler dieses Servers ist &eKuhlesMuh&7."

Command /event:
	trigger:
		if {event} is set:
			teleport player to {event}
			send "&8[&eEvent&8] &cDu wurdest zum &eEvent &7teleportiert."
			stop
		else:
			send "&8[&eEvent&8] &7Es existiert kein &eEvent&7."

on first join:
	add %{startmoney::*}% to player's balance
	if {maintenance.server} is false:
		set {new.%player%} to false
		send " "
		send " "
		send " "
		send " "
		send " "
		send " "
		send " "
		send " "
		send " "
		send " "
		send " "
		send " "
		send " "
		set {Booster.%player%} to "0"
		send " "
		send " "
		execute console command "/pex user %player% add -*"
		send " "
		send " "
		send " "
		send "&8[&eWilkommen&8] &7Du hast &e$%{startmoney::*}% &7Startgeld erhalten&7! "
		send " "
		send " "
		broadcast " "
		give clock named "§a§lMenu" to player
		set {tutorial.betreten.%player%} to true
		broadcast " "
		broadcast "&8[&eWilkommen&8] &7Aufpassen! &e%player% &7ist neu auf dem Server. Sagt doch mal &eHallo&7!"
		broadcast " "
		broadcast " "
		execute console command "/give %player% golden_shovel 1 0"
		send "&7Hey, &e%player%&7! Herzlich Wilkommen auf &e%{Server::*}%&7. &7Wir wünschen dir viel Spaß!"
		send "&8» &eRegeln&7: &8/&eregeln"
		wait 3 seconds
		execute console command "/minecraft:give @a diamond 2 0"
		broadcast "&8[&eWilkommen&8] &7Alle Spieler haben ein &eGeschenk &7erhalten! Danke &e%player%&7!"

Command /teamchat [<text>]:
	trigger:
		if player has permission "server.team":
			make player execute command "/essentials:amsg %arg 1%"
		else:
			send "&8[&eTeamchat&8] {@Permission}"

Command /setevent:
	trigger:
		if player has permission "event.set":
			set {event} to player's location
			send "&8[&eEvent&8] &7Du hast die Position des Events erfolgreich festgelegt."
			stop
		else:
			send "&8[&eEvent&8] {@Permission}"

Command /delevent:
	trigger:
		if player has permission "event.del":
			if {event} is set:
				delete {event}
				send "&8[&eEvent&8] &7Du hast die Position des Events erfolgreich gelöscht."
				broadcast "&8[&eEvent&8] &7Das &eEvent &7ist nun vorbei."
				stop
			else:
				send "&8[&eEvent&8] &7Es wurde keine &ePosition &7für ein &eEvent &7festgelegt. Das geht mit &8/&esetevent"
		else:
			send "&8[&eEvent&8] {@Permission}"

on join:
	if {new.%player%} is false:
		if player has permission "group.owner":
			send "&8[&eWilkommen&8] &eHey&8. &eWilkommen &7zurück&8, &4Owner &8* &7%player%&8!"
		if player has permission "group.admin" or "group.ppremium":
			send "&8[&eWilkommen&8] &eHey&8. &eWilkommen &7zurück&8, &4Admin &8* &7%player%&8!"
		if player has permission "group.dev":
			send "&8[&eWilkommen&8] &eHey&8. &eWilkommen &7zurück&8, &bDeveloper &8* &7%player%&8!"
		if player has permission "group.mod":
			send "&8[&eWilkommen&8] &eHey&8. &eWilkommen &7zurück&8, &1Moderator &8* &7%player%&8!"
		if player has permission "group.sup":
			send "&8[&eWilkommen&8] &eHey&8. &eWilkommen &7zurück&8, &2Supporter &8* &7%player%&8!"
		if player has permission "group.builder":
			send "&8[&eWilkommen&8] &eHey&8. &eWilkommen &7zurück&8, &aBuilder &8* &7%player%&8!"
		if player has permission "group.yt":
			send "&8[&eWilkommen&8] &eHey&8. &eWilkommen &7zurück&8, &5YouTuber &8* &7%player%&8!"
		if player has permission "group.hero":
			send "&8[&eWilkommen&8] &eHey&8. &eWilkommen &7zurück&8, &cHero &8* &7%player%&8!"
		if player has permission "group.gold":
			send "&8[&eWilkommen&8] &eHey&8. &eWilkommen &7zurück&8, &6Gold &8* &7%player%&8!"
		if player has permission "group.warrior":
			send "&8[&eWilkommen&8] &eHey&8. &eWilkommen &7zurück&8, &9Warrior &8* &7%player%&8!"
		if player has permission "group.premium" or "group.ppremium":
			send "&8[&eWilkommen&8] &eHey&8. &eWilkommen &7zurück&8, &ePremium &8* &7%player%&8!"
			if player has permission "group.ppremium":
				send "&8[&ePremium&8] &7Dein &ePremium-Rang &7gilt noch %{_7tagepremium}%&8."
		if player has permission "group.spieler"
			send "&8[&eWilkommen&8] &eHey&8. &eWilkommen &7zurück&8, &7Spieler &8* &7%player%&8!"
	if {new.%player%} is not set:
		set {new.%player%} to false
		send " "
		set {Booster.%player%} to "0"
		send " "
		send " "
		send " "
		send " "
		send " "
		send " "
		send " "
		send " "
		send " "
		send " "
		send " "
		execute console command "/pex user %player% add -*"
		send " "
		send " "
		send " "
		send " "
		send " "
		send " "
		send "&8[&eWilkommen&8] &7Du hast &e$%{startmoney::*}% &7Startgeld erhalten&7! "
		send " "
		send " "
		broadcast " "
		give clock named "§a§lMenu" to player
		set {tutorial.betreten.%player%} to true
		broadcast " "
		broadcast "&8[&eWilkommen&8] &7Aufpassen! &e%player% &7ist neu auf dem Server. Sagt doch mal &eHallo&7!"
		broadcast " "
		broadcast " "
		execute console command "/give %player% golden_shovel 1 0"
		send "&7Hey, &e%player%&7! Herzlich Wilkommen auf &e%{Server::*}%&7. &7Wir wünschen dir viel Spaß!"
		send "&8» &eRegeln&7: &8/&eregeln"
		wait 3 seconds
		execute console command "/minecraft:give @a diamond 2 0"
		broadcast "&8[&eWilkommen&8] &7Alle Spieler haben ein &eGeschenk &7erhalten! Danke &e%player%&7!"
		execute console command "/deop %player%"
		execute console command "/pex user %player% add -*"
		wait 2 seconds
		send "&8[&eTutorial&8] &7Betrete &eTutorial&8..."
		wait 2 seconds
		Send "&8[&eTutorial&8] &7Erfolgreich zum &eTutorial &7verbunden&8."
		make player execute command "/tutorial"
		if {maintenance.server} is true:
			if player doesn't have permission "server.team":
				wait 1 second
				kick player due to "&cWir befinden uns momentan in Wartungsarbeiten."
		if {maintenance.server} is false:
			execute console command "/playsound minecraft:block.note.pling ambient %player% 0 0 0 1 1 1"
			execute console command "/effect %player% minecraft:blindness 5 10 false"
			execute console command "/effect %player% minecraft:slowness 5 3 false"
		if {maintenance.server} is not set:
			execute console command "/playsound minecraft:block.note.pling ambient %player% 0 0 0 1 1 1"
			execute console command "/effect %player% minecraft:blindness 5 10 false"
			execute console command "/effect %player% minecraft:slowness 5 3 false"
	else:
		execute console command "/deop %player%"
		if {maintenance.server} is true:
			if player doesn't have permission "server.team":
				wait 1 second
				kick player due to "&cWe are in Maintenance. Try again later."
		if {maintenance.server} is false:
			execute console command "/playsound minecraft:block.note.pling ambient %player% 0 0 0 1 1 1"
			execute console command "/effect %player% minecraft:blindness 5 10 false"
			execute console command "/effect %player% minecraft:slowness 5 3 false"
		if {maintenance.server} is not set:
			execute console command "/playsound minecraft:block.note.pling ambient %player% 0 0 0 1 1 1"
			execute console command "/effect %player% minecraft:blindness 5 10 false"
			execute console command "/effect %player% minecraft:slowness 5 3 false"

Command /warps:
	trigger:
		if player has permission "system.warp":
			send "&8)&7&m----------&7&8( &c&lWarps&8 )&7&m----------&8("
			send "&c%{warps::*}%"
			send "&8)&7&m----------&7&8( &c&lWarps &8)&7&m------

(....) There are 2190 lines
But Skript says "0 triggers and 0 commands"
### Expected Behavior
I want, that I can load my skripts.. :/
### Errors / Screenshots
[13:49:27 ERROR]: #!#!
[13:49:27 ERROR]: #!#! [Skript] Severe Error:
[13:49:27 ERROR]: #!#! Could not load MainSkript.sk
[13:49:27 ERROR]: #!#!
[13:49:27 ERROR]: #!#! Something went horribly wrong with Skript.
[13:49:27 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:49:27 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[13:49:27 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[13:49:27 ERROR]: #!#!
[13:49:27 ERROR]: #!#! Stack trace:
[13:49:27 ERROR]: #!#! java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[13:49:27 ERROR]: #!#!     at java.util.ArrayList.rangeCheck(Unknown Source)
[13:49:27 ERROR]: #!#!     at java.util.ArrayList.get(Unknown Source)
[13:49:27 ERROR]: #!#!     at net.milkbowl.vault.economy.plugins.Economy_iConomy6.currencyNameSingular(Economy_iConomy6.java:119)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.hooks.economy.classes.Money.parse(Money.java:158)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:57)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:1)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:421)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:460)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:365)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:638)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:628)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1022)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:690)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:406)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:425)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:347)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:377)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:910)
[13:49:27 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:155)
[13:49:27 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[13:49:27 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[13:49:27 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[13:49:27 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401)
[13:49:27 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236)
[13:49:27 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[13:49:27 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[13:49:27 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[13:49:27 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[13:49:27 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[13:49:27 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[13:49:27 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[13:49:27 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[13:49:27 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[13:49:27 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[13:49:27 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[13:49:27 ERROR]: #!#!
[13:49:27 ERROR]: #!#! Version Information:
[13:49:27 ERROR]: #!#!   Skript: 2.3.7 (latest)
[13:49:27 ERROR]: #!#!     Flavor: skriptlang-github
[13:49:27 ERROR]: #!#!     Date: 2019-06-27
[13:49:27 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[13:49:27 ERROR]: #!#!   Minecraft: 1.12.2
[13:49:27 ERROR]: #!#!   Java: 1.8.0_221 (Java HotSpot(TM) 64-Bit Server VM 25.221-b11)
[13:49:27 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:49:27 ERROR]: #!#!
[13:49:27 ERROR]: #!#! Server platform: Spigot
[13:49:27 ERROR]: #!#!
[13:49:27 ERROR]: #!#! Current node: loop all players: (MainSkript.sk, line 4)
[13:49:27 ERROR]: #!#! Current item: null
[13:49:27 ERROR]: #!#!
[13:49:27 ERROR]: #!#! Thread: Server thread
[13:49:27 ERROR]: #!#!
[13:49:27 ERROR]: #!#! Language: english
[13:49:27 ERROR]: #!#! Link parse mode: DISABLED
[13:49:27 ERROR]: #!#!
[13:49:27 ERROR]: #!#! End of Error.
[13:49:27 ERROR]: #!#!

### Server Information
* **Server version/platform:**       Spigot
* **Skript version:**                Latest (2.3.7)

**Comment by 1KleineKuh** [comment]
And sry if my english is bad.. Im from Germany :)

**Comment by antoinech2** [comment]
It seems that Skript is not compatible with your economy plugin.

The problem is on this line:
`add %{startmoney::}% to player's balance`
maybe try this instead:
`add {startmoney::} to player's balance`

**Comment by 1KleineKuh** [comment]
No, it works yesterday. I didnt changed aqnything, just updated Skript. I tried also to use the old version of skript

**Comment by 1KleineKuh** [comment]
And there is written "Loaded 0 commands with 0 triggers" but if this one line is wrong, then the other commands have to work

**Comment by antoinech2** [comment]
Okay so it's a Skript bug ;)
There are a lot of bugs in the last version

**Comment by Runakai1** [comment]
Oh please just post the code on pastepin or wherever, it's a mess we can't read. Or just use the code boxes! Also, `add %{Startmoney::*% to player's balance` would have never worked. And will never work

**Comment by 1KleineKuh** [comment]
https://pastebin.com/f7PcjVD7
There is the full skript Sry ;)

**Comment by 1KleineKuh** [comment]
But its not my skript.. Bcs on reload of skript, they said "0 Triggers and 0 Commands" But if its an error, they would load the commands but will say that there is an error..

**Comment by Wealthyturtle** [comment]
It may have stopped parsing the skript half-way due to an exception

**Comment by ham1255** [comment]
i think you should try to disable that command then try load the script

**Comment by 1KleineKuh** [comment]
No! It wouldnt work! ITS AN SKRIPT PLUGIN ERROR! Bcs yesterday everything worked well! I didnt changed anything! Just updated the skript version!

**Comment by 1KleineKuh** [comment]
My other skripts are also not loading... Its an skript issue

**Comment by ham1255** [comment]
Try making move Skript folder to another file then readd scripts from old skript dir

**Comment by 1KleineKuh** [comment]
Okay i will try

**Comment by Blueyescat** [comment]
Your economy plugin is broken or you wan't set up it properly.

**Comment by 1KleineKuh** [comment]
You arent a good help.. I will just close the issue.. ITS NOT MY ECONOMY PLUGIN!
