### ISSUE TITLE
skript does not load script file java.util.NoSuchElementException

### ISSUE THREAD

**Issue by ham1255** [SkriptLang/Skript#2333]
### Description
Skript sometimes does not load skript file.
edit: this does happen on server startup only but using /sk reload does work
### Steps to Reproduce
load this code and keep restarting the server
```
on script load:
	broadcast "&c&lServer Loaded successfully &d&l1.0.1-FIX7"
```

### Expected Behavior
it should load skript file without problem

### Errors / Screenshots
```
[10:06:57 ERROR]: #!#!
> [10:06:57 ERROR]: #!#! [Skript] Severe Error:
> [10:06:57 ERROR]: #!#! Could not load NetworkSkript_Main.sk
> [10:06:57 ERROR]: #!#!
> [10:06:57 ERROR]: #!#! Something went horribly wrong with Skript.
> [10:06:57 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
> [10:06:57 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
> [10:06:57 ERROR]: #!#! Here is full list of them:
> [10:06:57 ERROR]: #!#! skRayFall (https://sk.rayfall.net/) skript-mirror (https://github.com/btk5h/skript-mirror) Skungee skUtilities (https://tim740.github.io/) SkQuery Ersatz Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) Skore skript-db
> [10:06:57 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
> [10:06:57 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
> [10:06:57 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
> [10:06:57 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
> [10:06:57 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
> [10:06:57 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
> [10:06:57 ERROR]: #!#!
> [10:06:57 ERROR]: #!#! Stack trace:
> [10:06:57 ERROR]: #!#! java.util.NoSuchElementException
> [10:06:57 ERROR]: #!#! at java.util.LinkedList.removeFirst(LinkedList.java:270)
> [10:06:57 ERROR]: #!#! at java.util.LinkedList.pop(LinkedList.java:801)
> [10:06:57 ERROR]: #!#! at ch.njol.skript.log.HandlerList.remove(HandlerList.java:40)
> [10:06:57 ERROR]: #!#! at ch.njol.skript.log.SkriptLogger.removeHandler(SkriptLogger.java:111)
> [10:06:57 ERROR]: #!#! at ch.njol.skript.log.LogHandler.stop(LogHandler.java:43)
> [10:06:57 ERROR]: #!#! at ch.njol.skript.log.ParseLogHandler.printError(ParseLogHandler.java:98)
> [10:06:57 ERROR]: #!#! at ch.njol.skript.log.ParseLogHandler.printError(ParseLogHandler.java:88)
> [10:06:57 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1496)
> [10:06:57 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1254)
> [10:06:57 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1230)
> [10:06:57 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:681)
> [10:06:57 ERROR]: #!#! at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:406)
> [10:06:57 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:425)
> [10:06:57 ERROR]: #!#! at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:347)
> [10:06:57 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:377)
> [10:06:57 ERROR]: #!#! at ch.njol.skript.Skript$2.run(Skript.java:527)
> [10:06:57 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
> [10:06:57 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
> [10:06:57 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
> [10:06:57 ERROR]: #!#! at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
> [10:06:57 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
> [10:06:57 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
> [10:06:57 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
> [10:06:57 ERROR]: #!#!
> [10:06:57 ERROR]: #!#! Version Information:
> [10:06:57 ERROR]: #!#! Skript: 2.3.7 (latest)
> [10:06:57 ERROR]: #!#! Flavor: skriptlang-github
> [10:06:57 ERROR]: #!#! Date: 2019-06-27
> [10:06:57 ERROR]: #!#! Bukkit: 1.12.2-R0.1-SNAPSHOT
> [10:06:57 ERROR]: #!#! Minecraft: 1.12.2
> [10:06:57 ERROR]: #!#! Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b01)
> [10:06:57 ERROR]: #!#! OS: Linux amd64 4.4.0
> [10:06:57 ERROR]: #!#!
> [10:06:57 ERROR]: #!#! Server platform: Paper
> [10:06:57 ERROR]: #!#!
> [10:06:57 ERROR]: #!#! Current node: on script load: (NetworkSkript_Main.sk, line 2)
> [10:06:57 ERROR]: #!#! Current item: null
> [10:06:57 ERROR]: #!#!
> [10:06:57 ERROR]: #!#! Thread: Server thread
> [10:06:57 ERROR]: #!#!
> [10:06:57 ERROR]: #!#! Language: english
> [10:06:57 ERROR]: #!#! Link parse mode: DISABLED
> [10:06:57 ERROR]: #!#!
> [10:06:57 ERROR]: #!#! End of Error.
> [10:06:57 ERROR]: #!#!
```
--->

### Server Information
* **Server version/platform:**       1.12.2 paperspigot
* **Skript version:**                 2.3.7

**Comment by TheBentoBox** [comment]
1. You're not on the latest Skript version, which is all we accept bug reports for.
2. Are you using using skript-mirror? Try updating to skript-mirror 2.0, found [here](https://circleci.com/gh/btk5h/skript-mirror/3#artifacts/containers/0).

**Comment by ham1255** [comment]
**Skript: 2.3.7 (latest)**

**Comment by SiebeDW** [comment]
2.4-beta5 is newer. You can find it in the releases section.

**Comment by bensku** [comment]
Hmm, we may have an updater bug there. Need to check that.
