### ISSUE TITLE
java.lang.NullPointerException in consol with function

### ISSUE THREAD

**Issue by Askabor** [SkriptLang/Skript#2335]
### Description
Getting an Consol Error wehn runing the following Skript

### Steps to Reproduce
attached the Skript

```
function openGUI(p: player, s: string, n: text, l: string, f: text, z1: string, p1: string, z2: string, p2: string, z3: string, p3: string, z4: string, p4: string, c: text): 
#p = Spieler #s = Size #n = Überschrift #l = Loop Times #f = ConfigFiel 
#z1 = Teil 1 der Config #p1 = Spezfizierter Part 1 der Config # c = command
	open virtual chest with size {_s} named "%{_n}%" to {_p}
	wait 3 ticks
	set {_slot} to 0
	loop {_l} times:
		add 1 to {_slot}
		set {_z1::*} to skutil yaml list "{_p1}" from file "{_f}"
		set {_z2::*} to skutil yaml list "{_p2}" from file "{_f}"
		set {_z3::*} to skutil yaml list "{_p3}" from file "{_f}"
		set {_z4::*} to skutil yaml list "{_p4}" from file "{_f}"
		loop {_z1::*}:
			set {_z1::%loop-index-1%} to loop-value-2 parsed as materials
			loop {_z2::*}:
				set {_z2::%loop-index-2%} to loop-value-3
				loop {_z3::*}:
					set {_z3::%loop-index-3%} to loop-value-4
					loop {_z4::*}:
						set {_z4::%loop-index-4%} to loop-value-5
						wait 2 ticks
						if {_p} has permission "{_c}.%loop-value-5%":
							make a gui slot {_slot} of {_p} with {_z1::%loop-index-1%} named {_z2::%loop-index-2%} with lore {_z3::%loop-index-3%} to close then run {_p} command "/test execute {_c} %loop-value-5%"
						else:
							make a gui slot {_slot} of {_p} with bedrock named "{_not}" to close then run {_p} command "/test execute {_c} %loop-value-5%"
							make a gui slot 8 of {_p} with air named "&4" to run {_p} command ""
							make a gui slot 9 of {_p} with air named "&4" to run {_p} command ""

options:
	prefix: &4Hub &8|
	filehub: /plugins/Skript/scripts/Chriskraft9/GuiHub.yml
	menu-name: &4Hub &8| &2Spiral Selector



command /ga <text> [<text>] [<text>]:
	trigger:
		if arg-1 is "Test":
			openGUI(player,"3","Test","3","{@filehub}","HPGUIi","GuiHub.%arg-1%.%{_slot}%.item","HPGUIn","GuiHub.%arg-1%.%{_slot}%.name","HPGUIl","GuiHub.%arg-1%.%{_slot}%.lore","HPGUIc","GuiHub.%arg-1%.%{_slot}%.command","Spiral")
```
### Expected Behavior
open anInventory with some Items to execute commands

### Errors / Screenshots

``` [13:24:46 INFO]: Chriskraft9 [980b1b1d-cfb6-42fb-bcaf-e8728fdedfc4]: /ga test
[13:24:46 ERROR]: #!#!
[13:24:46 ERROR]: #!#! [Skript] Severe Error:
[13:24:46 ERROR]: #!#!
[13:24:46 ERROR]: #!#! Something went horribly wrong with Skript.
[13:24:46 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:24:46 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[13:24:46 ERROR]: #!#! Here is full list of them:
[13:24:46 ERROR]: #!#! skRayFall (https://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) skDragon skUtilities (https://tim740.github.io/) SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) SharpSK
[13:24:46 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[13:24:46 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[13:24:46 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[13:24:46 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[13:24:46 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[13:24:46 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[13:24:46 ERROR]: #!#!
[13:24:46 ERROR]: #!#! Stack trace:
[13:24:46 ERROR]: #!#! java.lang.NullPointerException
[13:24:46 ERROR]: #!#!     at com.github.tukenuke.tuske.expressions.gui.ExprVirtualInv.get(ExprVirtualInv.java:80)
[13:24:46 ERROR]: #!#!     at com.github.tukenuke.tuske.expressions.gui.ExprVirtualInv.get(ExprVirtualInv.java:23)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:60)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.effects.EffOpenInventory.execute(EffOpenInventory.java:104)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:93)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:119)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:217)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:53)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:252)
[13:24:46 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:169)
[13:24:46 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[13:24:46 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:24:46 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:24:46 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
[13:24:46 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1792)
[13:24:46 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608)
[13:24:46 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[13:24:46 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[13:24:46 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[13:24:46 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[13:24:46 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[13:24:46 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[13:24:46 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[13:24:46 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012)
[13:24:46 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005)
[13:24:46 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[13:24:46 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989)
[13:24:46 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922)
[13:24:46 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
```

### Server Information
* **Server version/platform:**       Paper 157
* **Skript version:**                2.4-beta5

**Comment by Runakai1** [comment]
This is not a skript issue. Seems like it's a TuSKe issue

**Comment by TheBentoBox** [comment]
We don't accept reports for add-on issues here. We don't maintain those plugins.
