### ISSUE TITLE
Skript enable issue. > java.lang.NoSuchFieldException

### ISSUE THREAD

**Issue by TUCAOEVER** [SkriptLang/Skript#2339]
### Description
I am using CatServer which combined with both spigot and forge
And i am using HARVESTCRAFT mod.
Skript disable when i start server

### Expected Behavior
2.2 dev36 is fine but 2.3.7 doesn't work well
plz add support for this.

### Errors / Screenshots
[22:06:32] [Server thread/ERROR] [Minecraft]: Error occurred while enabling Skript v2.3.7 (Is it up to date?)
java.lang.AssertionError: java.lang.NoSuchFieldException: HARVESTCRAFT_PAMCOCONUT
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:808) ~[TypeAdapters$EnumTypeAdapter.class:?]
	at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:834) ~[TypeAdapters$30.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[Gson.class:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory.create(MapTypeAdapterFactory.java:126) ~[MapTypeAdapterFactory.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:886) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[Gson.class:?]
	at ch.njol.skript.bukkitutil.BukkitUnsafe.loadMaterialMap(BukkitUnsafe.java:175) ~[?:?]
	at ch.njol.skript.bukkitutil.BukkitUnsafe.initialize(BukkitUnsafe.java:116) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:396) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:Personal-4685e5b3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:Personal-4685e5b3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [SimplePluginManager.class:Personal-4685e5b3]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:433) [CraftServer.class:Personal-4685e5b3]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:382) [CraftServer.class:Personal-4685e5b3]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:473) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:428) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:385) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:597) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoSuchFieldException: HARVESTCRAFT_PAMCOCONUT
	at java.lang.Class.getField(Unknown Source) ~[?:1.8.0_181]
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:797) ~[TypeAdapters$EnumTypeAdapter.class:?]
	... 21 more

### Server Information
* **Server version/platform:**       1.12.2 CatServer
* **Skript version:**                2.3.7

**Comment by bensku** [comment]
Skript does not support your server software. See below for technical explanation.

The error occurs, because Material enum values are different from fields it actually has. Skript assumes this is not the case, because according to Java spec, that never happens. However, it is possible to "corrupt" an enum using reflection or bytecode manipulation. I assume this is what is happening here.

**Comment by TUCAOEVER** [comment]
But skript 2.2dev36 works very well on my server

**Comment by bensku** [comment]
It is probably possible, but I'm not interested in working on that.

**Comment by TUCAOEVER** [comment]
Alright... What a pity.

**Comment by SiebeDW** [comment]
You could try to use [Kettle](https://github.com/KettleFoundation/Kettle)
It can run spigot & forge mods like Catserver. I tried Skript on Kettle and it started up without any errors.
I tested some basic scripts and they work. So its maybe better that you use Kettle.

**Comment by Wealthyturtle** [comment]
Similar issue to #2020

**Comment by FranKusmiruk** [comment]
Closing since we don't have any interest in supporting modded servers yet.
