### ISSUE TITLE
"on chat:" not working in 2.4-beta4

### ISSUE THREAD

**Issue by awaffle1** [SkriptLang/Skript#2363]
Just put `on chat:` into a skript on 2.4-beta4 and it doesn't work.

This worked in previous versions, so why doesn't it work now?

**Comment by TPGamesNL** [comment]
As far as I know, that is not from vanilla Skript. Do you mean `on chat`?

**Comment by bluelhf** [comment]
@TPGamesNL That's correct. `on send:` doesn't seem to be syntax from any addon, and it certainly isn't syntax from Skript.

**Comment by awaffle1** [comment]
Oh yes, I meant ``on chat:``

My error. Still doesn't work

**Comment by TPGamesNL** [comment]
Take a look at console, there are probably some errors there (you might have to scroll up a bit for them).

**Comment by awaffle1** [comment]
I did, I accidentally enabled all skripts which caused Skript to flip, so I removed all of the skripts I didn't need and it still didn't work.

Here's the code near the `on chat:`

`on chat:
	if {whitetext::%uuid of player%} is true:
		cancel event 
		broadcast "%{rank::%uuid of player%}% %player% &8» &f%coloured message%"
	else:
		cancel event
		broadcast "%{rank::%uuid of player%}% %player% &8» &7%message%"`

**Comment by awaffle1** [comment]
(Github didn't register the line breaks for some reason.)

**Comment by TPGamesNL** [comment]
You should send the errors your getting, also the exceptions (they have a stack trace).
Also take a look at [GitHub code formatting](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Comment by awaffle1** [comment]
```
10.08 12:35:58 [Server] ERROR can't understand this event: 'on chat' (chat.sk, line 1: on chat:')
10.08 12:35:58 [Server] ERROR can't understand this event: 'every second' (chat.sk, line 9: every second:')
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! [Skript] Severe Error:
10.08 12:35:58 [Server] ERROR #!#! Could not load chat.sk
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Something went horribly wrong with Skript.
10.08 12:35:58 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
10.08 12:35:58 [Server] ERROR #!#! You are running an outdated Minecraft version not supported by Skript.
10.08 12:35:58 [Server] ERROR #!#! Please update to Minecraft 1.9.4 or later or fix this yourself and send us a pull request.
10.08 12:35:58 [Server] ERROR #!#! Alternatively, use an older Skript version; do note that those are also unsupported by us.
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Again, we do not support Minecraft versions this old.
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Stack trace:
10.08 12:35:58 [Server] ERROR #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:241)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:336)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:359)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:648)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:406)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:425)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:347)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:377)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.Skript.reloadScripts(Skript.java:926)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:160)
10.08 12:35:58 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
10.08 12:35:58 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
10.08 12:35:58 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
10.08 12:35:58 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
10.08 12:35:58 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
10.08 12:35:58 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
10.08 12:35:58 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
10.08 12:35:58 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
10.08 12:35:58 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Version Information:
10.08 12:35:58 [Server] ERROR #!#!   Skript: 2.4-beta4 (OUTDATED)
10.08 12:35:58 [Server] ERROR #!#!     Flavor: skriptlang-github
10.08 12:35:58 [Server] ERROR #!#!     Date: 2019-07-28
10.08 12:35:58 [Server] ERROR #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
10.08 12:35:58 [Server] ERROR #!#!   Minecraft: 1.8.8
10.08 12:35:58 [Server] ERROR #!#!   Java: 1.8.0_222 (OpenJDK 64-Bit Server VM 25.222-b10)
10.08 12:35:58 [Server] ERROR #!#!   OS: Linux amd64 5.2.6-1.el7.elrepo.x86_64
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Server platform: Spigot
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Current node: command /grant [<offline player>]: (chat.sk, line 13)
10.08 12:35:58 [Server] ERROR #!#! Current item: null
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Thread: Server thread
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Language: english
10.08 12:35:58 [Server] ERROR #!#! Link parse mode: DISABLED
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! End of Error.
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! [Skript] Severe Error:
10.08 12:35:58 [Server] ERROR #!#! Could not load core.sk
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Something went horribly wrong with Skript.
10.08 12:35:58 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
10.08 12:35:58 [Server] ERROR #!#! You are running an outdated Minecraft version not supported by Skript.
10.08 12:35:58 [Server] ERROR #!#! Please update to Minecraft 1.9.4 or later or fix this yourself and send us a pull request.
10.08 12:35:58 [Server] ERROR #!#! Alternatively, use an older Skript version; do note that those are also unsupported by us.
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Again, we do not support Minecraft versions this old.
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Stack trace:
10.08 12:35:58 [Server] ERROR #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:241)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.getClassInfos(Classes.java:246)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:415)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:450)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:574)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:836)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1564)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1003)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:491)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:648)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:406)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:425)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:347)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:377)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.Skript.reloadScripts(Skript.java:926)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:160)
10.08 12:35:58 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
10.08 12:35:58 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
10.08 12:35:58 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
10.08 12:35:58 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
10.08 12:35:58 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
10.08 12:35:58 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
10.08 12:35:58 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
10.08 12:35:58 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
10.08 12:35:58 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Version Information:
10.08 12:35:58 [Server] ERROR #!#!   Skript: 2.4-beta4 (OUTDATED)
10.08 12:35:58 [Server] ERROR #!#!     Flavor: skriptlang-github
10.08 12:35:58 [Server] ERROR #!#!     Date: 2019-07-28
10.08 12:35:58 [Server] ERROR #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
10.08 12:35:58 [Server] ERROR #!#!   Minecraft: 1.8.8
10.08 12:35:58 [Server] ERROR #!#!   Java: 1.8.0_222 (OpenJDK 64-Bit Server VM 25.222-b10)
10.08 12:35:58 [Server] ERROR #!#!   OS: Linux amd64 5.2.6-1.el7.elrepo.x86_64
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Server platform: Spigot
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Current node: teleport player to {worldspawn} (core.sk, line 7)
10.08 12:35:58 [Server] ERROR #!#! Current item: null
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Thread: Server thread
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Language: english
10.08 12:35:58 [Server] ERROR #!#! Link parse mode: DISABLED
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! End of Error.
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! [Skript] Severe Error:
10.08 12:35:58 [Server] ERROR #!#! Could not load flight.sk
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Something went horribly wrong with Skript.
10.08 12:35:58 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
10.08 12:35:58 [Server] ERROR #!#! You are running an outdated Minecraft version not supported by Skript.
10.08 12:35:58 [Server] ERROR #!#! Please update to Minecraft 1.9.4 or later or fix this yourself and send us a pull request.
10.08 12:35:58 [Server] ERROR #!#! Alternatively, use an older Skript version; do note that those are also unsupported by us.
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Again, we do not support Minecraft versions this old.
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Stack trace:
10.08 12:35:58 [Server] ERROR #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:241)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.getClassInfos(Classes.java:246)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:415)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:450)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:574)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:836)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1564)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:81)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1083)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:690)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:406)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:425)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:347)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:377)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.Skript.reloadScripts(Skript.java:926)
10.08 12:35:58 [Server] ERROR #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:160)
10.08 12:35:58 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
10.08 12:35:58 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
10.08 12:35:58 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
10.08 12:35:58 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
10.08 12:35:58 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
10.08 12:35:58 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
10.08 12:35:58 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
10.08 12:35:58 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
10.08 12:35:58 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Version Information:
10.08 12:35:58 [Server] ERROR #!#!   Skript: 2.4-beta4 (OUTDATED)
10.08 12:35:58 [Server] ERROR #!#!     Flavor: skriptlang-github
10.08 12:35:58 [Server] ERROR #!#!     Date: 2019-07-28
10.08 12:35:58 [Server] ERROR #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
10.08 12:35:58 [Server] ERROR #!#!   Minecraft: 1.8.8
10.08 12:35:58 [Server] ERROR #!#!   Java: 1.8.0_222 (OpenJDK 64-Bit Server VM 25.222-b10)
10.08 12:35:58 [Server] ERROR #!#!   OS: Linux amd64 5.2.6-1.el7.elrepo.x86_64
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Server platform: Spigot
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Current node: if player's world is "mainlobby": (flight.sk, line 2)
10.08 12:35:58 [Server] ERROR #!#! Current item: null
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Thread: Server thread
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! Language: english
10.08 12:35:58 [Server] ERROR #!#! Link parse mode: DISABLED
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] ERROR #!#! End of Error.
10.08 12:35:58 [Server] ERROR #!#! 
10.08 12:35:58 [Server] INFO Loaded 3 scripts with a total of 0 triggers and 0 commands in 0.02 seconds
10.08 12:35:58 [Server] INFO [Skript] Encountered 2 errors while reloading all scripts!```

I think I found the problem

**Comment by awaffle1** [comment]
Wait
Oh. I know. I'm running 1.8.8 :man_facepalming:

**Comment by awaffle1** [comment]
Ok I can fix this.

**Comment by awaffle1** [comment]
working fine now, switched to 1.12.2
