### ISSUE TITLE
Error in Skript

### ISSUE THREAD

**Issue by onlyyDomi** [SkriptLang/Skript#2366]
Hey, im lately trying to make a simple Backpack Skript for my server, I'm pretty new to scripting so I dont know where the error is, so I would be thankful for any suggestion.

Here's the Error in the Console:

[00:41:00 ERROR]: #!#! [Skript] Severe Error:
[00:41:00 ERROR]: #!#! Could not load BP.sk
[00:41:00 ERROR]: #!#!
[00:41:00 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[00:41:00 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[00:41:00 ERROR]: #!#! and check whether this error has already been reported.
[00:41:00 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[00:41:00 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[00:41:00 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[00:41:00 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[00:41:00 ERROR]: #!#!
[00:41:00 ERROR]: #!#! Stack trace:
[00:41:00 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for player'
[00:41:00 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:242)
[00:41:00 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1247)
[00:41:00 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:969)
[00:41:00 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:209)
[00:41:00 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:164)
[00:41:00 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:42)
[00:41:00 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:615)
[00:41:00 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:55)
[00:41:00 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[00:41:00 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:701)
[00:41:00 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:489)
[00:41:00 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:239)
[00:41:00 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:193)
[00:41:00 ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:548)
[00:41:00 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:130)
[00:41:00 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:41:00 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:41:00 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[00:41:00 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[00:41:00 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[00:41:00 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[00:41:00 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:41:00 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[00:41:00 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[00:41:00 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[00:41:00 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[00:41:00 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[00:41:00 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[00:41:00 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[00:41:00 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[00:41:00 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[00:41:00 ERROR]: #!#!
[00:41:00 ERROR]: #!#! Version Information:
[00:41:00 ERROR]: #!#!   Skript: 2.1.2
[00:41:00 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[00:41:00 ERROR]: #!#!   Minecraft: 1.8.8
[00:41:00 ERROR]: #!#!   Java: 1.8.0_211
[00:41:00 ERROR]: #!#!
[00:41:00 ERROR]: #!#! Running CraftBukkit: false
[00:41:00 ERROR]: #!#!
[00:41:00 ERROR]: #!#! Current node: set {backpack.level1.%player's uuid%} to players current inventory (BP.sk, line 24)
[00:41:00 ERROR]: #!#! Current item: null
[00:41:00 ERROR]: #!#!
[00:41:00 ERROR]: #!#! Thread: Server thread
[00:41:00 ERROR]: #!#!
[00:41:00 ERROR]: #!#! End of Error.

Thanks !

**Comment by TheBentoBox** [comment]
You are using an insanely old version of Skript and are on 1.8. We don't support 1.8 here and we only support the latest release from [our releases page](https://github.com/SkriptLang/Skript/releases).

**Comment by onlyyDomi** [comment]
Ok
