### ISSUE TITLE
Skript not working when used on hexxit server

### ISSUE THREAD

**Issue by ItzArty** [SkriptLang/Skript#2391]
Hello, I've tried to install skript plugin on my mcpc+ 1.5.2 server with mods from hexxit modpack. I have tried all skript with 1.5.2 server support but everytime it resulted this error in console:
`14:09:58 [SEVERE] Could not load 'plugins\Skript.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassNotFoundException: Failed to remap class ch.njol.skript.Skript
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:164)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:307)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:231)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:256)
        at cpw.mods.fml.common.event.FMLServerAboutToStartEvent.<init>(FMLServerAboutToStartEvent.java:30)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at cpw.mods.fml.common.LoaderState.getEvent(LoaderState.java:84)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:103)
        at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:807)
        at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:309)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:588)
        at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
Caused by: java.lang.ClassNotFoundException: Failed to remap class ch.njol.skript.Skript
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:448)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:362)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:338)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153)
        ... 15 more
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:436)
        at net.md_5.specialsource.repo.RuntimeRepo.findClass0(RuntimeRepo.java:48)
        at net.md_5.specialsource.repo.CachingRepo.findClass(CachingRepo.java:46)
        at net.md_5.specialsource.UnsortedRemappingMethodAdapter.findAccess(UnsortedRemappingMethodAdapter.java:128)
        at net.md_5.specialsource.UnsortedRemappingMethodAdapter.findAccess(UnsortedRemappingMethodAdapter.java:156)
        at net.md_5.specialsource.UnsortedRemappingMethodAdapter.visitMethodInsn(UnsortedRemappingMethodAdapter.java:168)
        at org.objectweb.asm.MethodVisitor.visitMethodInsn(MethodVisitor.java:382)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1320)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:938)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:669)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:241)
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:227)
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:413)
        ... 22 more`
please do not leave this issue because of an old version, since Im really NOT about moving from my hexxit server to other modpack/server version.
thanks

**Comment by DavidVioMC** [comment]
You should've asked for help on Discord, this is not an issue with this version of Skript. Skript, staff and community no longer provide support for 1.8 let alone 1.5.2.

**Comment by ItzArty** [comment]
Okay, I switched to mcpc+ r1.1 and it finally works.
