### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by NeonSignalJS** [SkriptLang/Skript#2398]
```
[08:51:04] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[08:51:05] [Server thread/ERROR]: #!#! Could not load kick.sk
[08:51:05] [Server thread/ERROR]: #!#!
[08:51:05] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[08:51:05] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[08:51:05] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[08:51:05] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[08:51:05] [Server thread/ERROR]: #!#!
[08:51:05] [Server thread/ERROR]: #!#! Stack trace:
[08:51:05] [Server thread/ERROR]: #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
[08:51:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:241)
[08:51:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:336)
[08:51:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:361)
[08:51:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:648)
[08:51:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:406)
[08:51:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:425)
[08:51:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:347)
[08:51:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:377)
[08:51:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:910)
[08:51:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:155)
[08:51:05] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[08:51:05] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[08:51:05] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710)
[08:51:05] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:695)
[08:51:05] [Server thread/ERROR]: #!#!     at
```

**Comment by Matocolotoe** [comment]
Okay, code used ? Skript version ? Server version ? Software ?

**Comment by FranKusmiruk** [comment]
Please fill the issue template properly when reporting to the issue tracker.
