### ISSUE TITLE
within error

### ISSUE THREAD

**Issue by TheLucXas** [SkriptLang/Skript#2410]
Sorry for not explaining but i don't speak english. I hope someone can help me please.
[21:25:55 ERROR]: #!#! [Skript] Severe Error:
[21:25:55 ERROR]: #!#!
[21:25:55 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[21:25:55 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[21:25:55 ERROR]: #!#! and check whether this error has already been reported.
[21:25:55 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[21:25:55 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[21:25:55 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[21:25:55 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[21:25:55 ERROR]: #!#!
[21:25:55 ERROR]: #!#! Stack trace:
[21:25:55 ERROR]: #!#! java.lang.NullPointerException
[21:25:55 ERROR]: #!#!     at com.w00tmast3r.skquery.util.region.CuboidRegion.min(CuboidRegion.java:74)
[21:25:55 ERROR]: #!#!     at com.w00tmast3r.skquery.util.region.CuboidRegion.<init>(CuboidRegion.java:18)
[21:25:55 ERROR]: #!#!     at com.w00tmast3r.skquery.util.region.CuboidIterator.<init>(CuboidIterator.java:12)
[21:25:55 ERROR]: #!#!     at com.w00tmast3r.skquery.elements.expressions.ExprBlockCube.iterator(ExprBlockCube.java:71)
[21:25:55 ERROR]: #!#!     at ch.njol.skript.lang.Loop.walk(Loop.java:81)
[21:25:55 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[21:25:55 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[21:25:55 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
[21:25:55 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
[21:25:55 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
[21:25:55 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
[21:25:55 ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
[21:25:55 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:25:55 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[21:25:55 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[21:25:55 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:25:55 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[21:25:55 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[21:25:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)
[21:25:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[21:25:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:25:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:25:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[21:25:55 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:25:55 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[21:25:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[21:25:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[21:25:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[21:25:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[21:25:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[21:25:55 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[21:25:55 ERROR]: #!#!
[21:25:55 ERROR]: #!#! Version Information:
[21:25:55 ERROR]: #!#!   Skript: 2.2-dev25
[21:25:55 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[21:25:55 ERROR]: #!#!   Minecraft: 1.8.8
[21:25:55 ERROR]: #!#!   Java: 1.8.0_221 (Java HotSpot(TM) 64-Bit Server VM 25.221-b11)
[21:25:55 ERROR]: #!#!   OS: Windows Server 2019 amd64 10.0
[21:25:55 ERROR]: #!#!
[21:25:55 ERROR]: #!#! Running CraftBukkit: false
[21:25:55 ERROR]: #!#!
[21:25:55 ERROR]: #!#! Current node: null
[21:25:55 ERROR]: #!#! Current item: loop cuboid
[21:25:55 ERROR]: #!#!
[21:25:55 ERROR]: #!#! Thread: Server thread
[21:25:55 ERROR]: #!#!
[21:25:55 ERROR]: #!#! End of Error.
[21:25:55 ERROR]: #!#!
![image](https://user-images.githubusercontent.com/36708279/64069279-c94e1900-cc1c-11e9-9a79-6fa121355a03.png)
![image](https://user-images.githubusercontent.com/36708279/64069284-fd293e80-cc1c-11e9-98f1-da877b1fbc28.png)

**Comment by TheBentoBox** [comment]
You're using a really old Skript version and this error is with an skQuery expression. Add-ons are maintained by their respective developers.

**Comment by TheLucXas** [comment]
> You're using a really old Skript version and this error is with an skQuery expression. Add-ons are maintained by their respective developers.

which is the last version for 1.8.8?

**Comment by bluelhf** [comment]
@TheLucXas Anything pre-1.9 is not supported, and this issue tracker isn't mean to be used for addon issues. Contact the developer of the addon instead, and upgrade to a newer version for a higher likelihood of actually getting support.

**Comment by Matocolotoe** [comment]
@TheLucXas You can use my fork if you want : https://github.com/Matocolotoe/Skript-1.8

**Comment by TheLucXas** [comment]
> @TheLucXas Anything pre-1.9 is not supported, and this issue tracker isn't mean to be used for addon issues. Contact the developer of the addon instead, and upgrade to a newer version for a higher likelihood of actually getting support.

Thx solved
