### ISSUE TITLE
Bug???

### ISSUE THREAD

**Issue by ajh123** [SkriptLang/Skript#2470]
Edit: Its the newest release (not beta/alpha) for 1.14 from bukkit.org

**server.sk**

```
command /addMoney <number>:
	trigger:
		set {%arg 1%%uuid of player%} to balance of player
```

[17:02:17] [Server thread/INFO]: samuelh2005 issued server command: /skript reload server
[17:02:17] [Server thread/ERROR]: #!#! 
[17:02:17] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[17:02:17] [Server thread/ERROR]: #!#! Could not load server.sk
[17:02:17] [Server thread/ERROR]: #!#! 
[17:02:17] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[17:02:17] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:02:17] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[17:02:17] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[17:02:17] [Server thread/ERROR]: #!#! 
[17:02:17] [Server thread/ERROR]: #!#! Stack trace:
[17:02:17] [Server thread/ERROR]: #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
[17:02:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:241)
[17:02:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:336)
[17:02:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:361)
[17:02:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:648)
[17:02:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:406)
[17:02:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:425)
[17:02:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[17:02:17] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:182)
[17:02:17] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:02:17] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[17:02:17] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710)
[17:02:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641)
[17:02:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481)
[17:02:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[17:02:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:02:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[17:02:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[17:02:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[17:02:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:02:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[17:02:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910)
[17:02:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903)
[17:02:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103)
[17:02:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886)
[17:02:17] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820)
[17:02:17] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:844)
[17:02:17] [Server thread/ERROR]: #!#! 
[17:02:17] [Server thread/ERROR]: #!#! Version Information:
[17:02:17] [Server thread/ERROR]: #!#!   Skript: 2.3.7 (latest)
[17:02:17] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[17:02:17] [Server thread/ERROR]: #!#!     Date: 2019-06-27
[17:02:17] [Server thread/ERROR]: #!#!   Bukkit: 1.14.4-R0.1-SNAPSHOT
[17:02:17] [Server thread/ERROR]: #!#!   Minecraft: 1.14.4
[17:02:17] [Server thread/ERROR]: #!#!   Java: 10 (Java HotSpot(TM) 64-Bit Server VM 10+46)
[17:02:17] [Server thread/ERROR]: #!#!   OS: Mac OS X x86_64 10.14.2
[17:02:17] [Server thread/ERROR]: #!#! 
[17:02:17] [Server thread/ERROR]: #!#! Server platform: Spigot
[17:02:17] [Server thread/ERROR]: #!#! 
[17:02:17] [Server thread/ERROR]: #!#! Current node: command /addMoney <number>: (server.sk, line 1)
[17:02:17] [Server thread/ERROR]: #!#! Current item: null
[17:02:17] [Server thread/ERROR]: #!#! 
[17:02:17] [Server thread/ERROR]: #!#! Thread: Server thread
[17:02:17] [Server thread/ERROR]: #!#! 
[17:02:17] [Server thread/ERROR]: #!#! Language: english
[17:02:17] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[17:02:17] [Server thread/ERROR]: #!#! 
[17:02:17] [Server thread/ERROR]: #!#! End of Error.
[17:02:17] [Server thread/ERROR]: #!#!

**Comment by Wealthyturtle** [comment]
Bukkit is not supported, you have to use Spigot/Paper

**Comment by ilsubyeega** [comment]
> 
> 
> Bukkit is not supported, you have to use Spigot/Paper

He used spigot```
[17:02:17] [Server thread/ERROR]: #!#!
[17:02:17] [Server thread/ERROR]: #!#! Server platform: Spigot
[17:02:17] [Server thread/ERROR]: #!#!```

**Comment by APickledWalrus** [comment]
Skript 2.3.7 does not support 1.14. Use the latest 2.4 builds for 1.14.
