### ISSUE TITLE
Console error when starting

### ISSUE THREAD

**Issue by Anoniempje1234** [SkriptLang/Skript#2530]
### Description
I got a console error when starting the server,
but I can use the plugin and the server without problems.

### Steps to Reproduce
Actually, I don't know...

### Expected Behavior
I don't want to get the error :)

### Errors / Screenshots
`>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! [Skript] Severe Error:
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! Something went horribly wrong with Skript.
>.... [15:03:46 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
>.... [15:03:46 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
>.... [15:03:46 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! Stack trace:
>.... [15:03:46 ERROR]: #!#! java.lang.NullPointerException
>.... [15:03:46 ERROR]: #!#! at ch.njol.skript.entity.SheepData.init(SheepData.java:64)
>.... [15:03:46 ERROR]: #!#! at ch.njol.skript.entity.SheepData.init(SheepData.java:1)
>.... [15:03:46 ERROR]: #!#! at ch.njol.skript.entity.EntityData.getData(EntityData.java:507)
>.... [15:03:46 ERROR]: #!#! at ch.njol.skript.entity.EntityData.fromClass(EntityData.java:523)
>.... [15:03:46 ERROR]: #!#! at ch.njol.skript.expressions.ExprSpawnerType.<clinit>(ExprSpawnerType.java:63)
>.... [15:03:46 ERROR]: #!#! at java.lang.Class.forName0(Native Method)
>.... [15:03:46 ERROR]: #!#! at java.lang.Class.forName(Class.java:348)
>.... [15:03:46 ERROR]: #!#! at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
>.... [15:03:46 ERROR]: #!#! at ch.njol.skript.Skript.onEnable(Skript.java:426)
>.... [15:03:46 ERROR]: #!#! at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
>.... [15:03:46 ERROR]: #!#! at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
>.... [15:03:46 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
>.... [15:03:46 ERROR]: #!#! at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
>.... [15:03:46 ERROR]: #!#! at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
>.... [15:03:46 ERROR]: #!#! at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
>.... [15:03:46 ERROR]: #!#! at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
>.... [15:03:46 ERROR]: #!#! at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
>.... [15:03:46 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! Version Information:
>.... [15:03:46 ERROR]: #!#! Skript: 2.4-beta8 (latest)
>.... [15:03:46 ERROR]: #!#! Flavor: skriptlang-github
>.... [15:03:46 ERROR]: #!#! Date: 2019-09-29
>.... [15:03:46 ERROR]: #!#! Bukkit: 1.14.4-R0.1-SNAPSHOT
>.... [15:03:46 ERROR]: #!#! Minecraft: 1.14.4
>.... [15:03:46 ERROR]: #!#! Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b01)
>.... [15:03:46 ERROR]: #!#! OS: Linux amd64 4.15.0-46-generic
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! Server platform: Paper
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! Current node: null
>.... [15:03:46 ERROR]: #!#! Current item: null
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! Thread: Server thread
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! Language: english
>.... [15:03:46 ERROR]: #!#! Link parse mode: DISABLED
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! End of Error.
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! [Skript] Severe Error:
>.... [15:03:46 ERROR]: #!#! Skript's class ch.njol.skript.expressions.ExprSpawnerType generated an exception while loading
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! Something went horribly wrong with Skript.
>.... [15:03:46 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
>.... [15:03:46 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
>.... [15:03:46 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! Stack trace:
>.... [15:03:46 ERROR]: #!#! warning: no/empty exception given, dumping current stack trace instead
>.... [15:03:46 ERROR]: #!#! java.lang.Exception: ch.njol.skript.util.EmptyStacktraceException
>.... [15:03:46 ERROR]: #!#! at ch.njol.skript.Skript.exception(Skript.java:1546)
>.... [15:03:46 ERROR]: #!#! at ch.njol.skript.Skript.exception(Skript.java:1414)
>.... [15:03:46 ERROR]: #!#! at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:112)
>.... [15:03:46 ERROR]: #!#! at ch.njol.skript.Skript.onEnable(Skript.java:426)
>.... [15:03:46 ERROR]: #!#! at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
>.... [15:03:46 ERROR]: #!#! at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
>.... [15:03:46 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
>.... [15:03:46 ERROR]: #!#! at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
>.... [15:03:46 ERROR]: #!#! at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
>.... [15:03:46 ERROR]: #!#! at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
>.... [15:03:46 ERROR]: #!#! at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
>.... [15:03:46 ERROR]: #!#! at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
>.... [15:03:46 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
>.... [15:03:46 ERROR]: #!#! Caused by: ch.njol.skript.util.EmptyStacktraceException
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! Version Information:
>.... [15:03:46 ERROR]: #!#! Skript: 2.4-beta8 (latest)
>.... [15:03:46 ERROR]: #!#! Flavor: skriptlang-github
>.... [15:03:46 ERROR]: #!#! Date: 2019-09-29
>.... [15:03:46 ERROR]: #!#! Bukkit: 1.14.4-R0.1-SNAPSHOT
>.... [15:03:46 ERROR]: #!#! Minecraft: 1.14.4
>.... [15:03:46 ERROR]: #!#! Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b01)
>.... [15:03:46 ERROR]: #!#! OS: Linux amd64 4.15.0-46-generic
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! Server platform: Paper
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! Current node: null
>.... [15:03:46 ERROR]: #!#! Current item: null
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! Thread: Server thread
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! Language: english
>.... [15:03:46 ERROR]: #!#! Link parse mode: DISABLED
>.... [15:03:46 ERROR]: #!#!
>.... [15:03:46 ERROR]: #!#! End of Error.
>.... [15:03:46 ERROR]: #!#!`
### Server Information
* **Server version/platform:**       Paper 1.14.4
* **Skript version:**                Skript2.4-beta8? The newest version

### Additional Context
/

**Comment by Anoniempje1234** [comment]
It's a duplicate of #2487.
