### ISSUE TITLE
 Problem with the plugin. Server version 1.14.4. Plugin version 2.4-beta8

### ISSUE THREAD

**Issue by Blox61** [SkriptLang/Skript#2540]
[16:58:48] [Server thread/ERROR]: Error occurred while enabling Skript v2.4-beta8 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:142) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:402) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-195]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-195]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-195]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-195]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-195]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-195]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-195]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870) ~[patched_1.14.4.jar:git-Paper-195]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 865
	at ch.njol.skript.aliases.MaterialRegistry.<init>(MaterialRegistry.java:102) ~[?:?]
	at ch.njol.skript.aliases.MaterialRegistry.load(MaterialRegistry.java:79) ~[?:?]
	at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:105) ~[?:?]
	... 11 more
[16:58:48] [Server thread/INFO]: [Skript] Disabling Skript v2.4-beta8

**Comment by Wealthyturtle** [comment]
More information would be helpful, what specific Paper version are you using? Any Skript addons?

**Comment by Blox61** [comment]
I have version paper-210

**Comment by TPGamesNL** [comment]
Delete `materials.json`

**Comment by bensku** [comment]
That will probably do the trick. This issue is often caused by people downgrading their server, which is unsafe.
