### ISSUE TITLE
Error in server console

### ISSUE THREAD

**Issue by xGlenor** [SkriptLang/Skript#2542]
Hi i have a problem :/ 

Server Version: Paper 1.14.4
Skript: v2.4-beta8
SkQuery: 4.1.1
Problem:
```
[17:35:08] [Server thread/INFO]: [Skript] Enabling Skript v2.4-beta8
[17:35:08] [Thread-14/INFO]: [Skript] You're currently running the latest stable version of Skript.
[17:35:11] [Server thread/INFO]: [Skript] Loaded 114161 aliases in 3770ms
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[17:35:12] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:35:12] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[17:35:12] [Server thread/ERROR]: #!#! Here is full list of them:
[17:35:12] [Server thread/ERROR]: #!#! SkQuery 
[17:35:12] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[17:35:12] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[17:35:12] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[17:35:12] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[17:35:12] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[17:35:12] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! Stack trace:
[17:35:12] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[17:35:12] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.SheepData.init(SheepData.java:64)
[17:35:12] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.SheepData.init(SheepData.java:1)
[17:35:12] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.EntityData.getData(EntityData.java:507)
[17:35:12] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.EntityData.fromClass(EntityData.java:523)
[17:35:12] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprSpawnerType.<clinit>(ExprSpawnerType.java:63)
[17:35:12] [Server thread/ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[17:35:12] [Server thread/ERROR]: #!#!     at java.lang.Class.forName(Class.java:348)
[17:35:12] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[17:35:12] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:426)
[17:35:12] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:35:12] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[17:35:12] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[17:35:12] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[17:35:12] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[17:35:12] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[17:35:12] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[17:35:12] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
[17:35:12] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! Version Information:
[17:35:12] [Server thread/ERROR]: #!#!   Skript: 2.4-beta8 (latest)
[17:35:12] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[17:35:12] [Server thread/ERROR]: #!#!     Date: 2019-09-29
[17:35:12] [Server thread/ERROR]: #!#!   Bukkit: 1.14.4-R0.1-SNAPSHOT
[17:35:12] [Server thread/ERROR]: #!#!   Minecraft: 1.14.4
[17:35:12] [Server thread/ERROR]: #!#!   Java: 1.8.0_222 (OpenJDK 64-Bit Server VM 25.222-b10)
[17:35:12] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.15.0-65-generic
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! Server platform: Paper
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! Current node: null
[17:35:12] [Server thread/ERROR]: #!#! Current item: null
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! Thread: Server thread
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! Language: english
[17:35:12] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! End of Error.
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[17:35:12] [Server thread/ERROR]: #!#! Skript's class ch.njol.skript.expressions.ExprSpawnerType generated an exception while loading
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[17:35:12] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:35:12] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[17:35:12] [Server thread/ERROR]: #!#! Here is full list of them:
[17:35:12] [Server thread/ERROR]: #!#! SkQuery 
[17:35:12] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[17:35:12] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[17:35:12] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[17:35:12] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[17:35:12] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[17:35:12] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! Stack trace:
[17:35:12] [Server thread/ERROR]: #!#!   warning: no/empty exception given, dumping current stack trace instead
[17:35:12] [Server thread/ERROR]: #!#! java.lang.Exception: ch.njol.skript.util.EmptyStacktraceException
[17:35:12] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1546)
[17:35:12] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1414)
[17:35:12] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:112)
[17:35:12] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:426)
[17:35:12] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:35:12] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[17:35:12] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[17:35:12] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[17:35:12] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[17:35:12] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[17:35:12] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[17:35:12] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
[17:35:12] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[17:35:12] [Server thread/ERROR]: #!#! Caused by: ch.njol.skript.util.EmptyStacktraceException
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! Version Information:
[17:35:12] [Server thread/ERROR]: #!#!   Skript: 2.4-beta8 (latest)
[17:35:12] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[17:35:12] [Server thread/ERROR]: #!#!     Date: 2019-09-29
[17:35:12] [Server thread/ERROR]: #!#!   Bukkit: 1.14.4-R0.1-SNAPSHOT
[17:35:12] [Server thread/ERROR]: #!#!   Minecraft: 1.14.4
[17:35:12] [Server thread/ERROR]: #!#!   Java: 1.8.0_222 (OpenJDK 64-Bit Server VM 25.222-b10)
[17:35:12] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.15.0-65-generic
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! Server platform: Paper
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! Current node: null
[17:35:12] [Server thread/ERROR]: #!#! Current item: null
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! Thread: Server thread
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! Language: english
[17:35:12] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/ERROR]: #!#! End of Error.
[17:35:12] [Server thread/ERROR]: #!#! 
[17:35:12] [Server thread/INFO]: [Skript]  ~ created by & © Peter Güttinger aka Njol ~
```

**Comment by TheBentoBox** [comment]
Duplicates #2487.
