### ISSUE TITLE
An internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by SolidRampage** [SkriptLang/Skript#2576]
When I try to use any commands it just says that an internal error has occurred and then nothing happens. 

Here's the error it give in the console:

[12:11:54] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'skript' in plugin Skript v2.4-alpha4 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[minecraft_server.jar:git-Bukkit-e5e8eec]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[minecraft_server.jar:git-Bukkit-e5e8eec]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:689) ~[minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1590) ~[minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1444) ~[minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:37) ~[minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:9) ~[minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:867) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:860) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:844) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:784) [minecraft_server.jar:git-Bukkit-e5e8eec]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

### Server Information
* **Server version/platform:**       1.14.4 spigot 
* **Skript version:**                2.4

I co-own the server, but my co-owner was the original person that set up the server. I'm also slightly illiterate when it comes to code.

**Comment by Wealthyturtle** [comment]
Please test this on 2.4-beta9. Also, full server logs would be helpful.

**Comment by SolidRampage** [comment]
As far as I'm aware we're using 2.4-beta9

Here's the log, hope it's the right thing...
[latest.log](https://github.com/SkriptLang/Skript/files/3745106/latest.log)

**Comment by ShaneBeee** [comment]
`Cannot execute command 'skript' in plugin Skript v2.4-alpha4 - plugin is disabled.`
It appears you are not running beta 9

Also, are you running Spigot or Craftbukkit?

**Comment by SolidRampage** [comment]
My bad then, I'll instal beta 9 then. Just asked Salty (Original owner) and we're using CraftBukkit not spigot.

**Comment by ShaneBeee** [comment]
This fork of Skript will not work on Craftbukkit, it requires at least Spigot (or Paper) to run.

**Comment by SolidRampage** [comment]
Ok thank you.
