### ISSUE TITLE
Error while trying to enable Skript in 1.12.2 (2.4-beta9 - Skript Version)

### ISSUE THREAD

**Issue by DeagoTheDoggo** [SkriptLang/Skript#2578]
This error happens when I try to load up my server:

`[17:09:43 INFO]: [Skript] Enabling Skript v2.4-beta9
[17:09:44 ERROR]: Error occurred while enabling Skript v2.4-beta9 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:142) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:402) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.ACACIA_BOAT
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.Material.valueOf(Material.java:1) ~[Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at ch.njol.skript.aliases.MaterialRegistry.load(MaterialRegistry.java:61) ~[?:?]
        at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:105) ~[?:?]
        ... 13 more`

After this happens when I try to use the command "/sk" or "/skript" it replys with "/skript help".

**Comment by ShaneBeee** [comment]
I can not replicate this error.
Can you try these steps:
- Stop your server
- Delete the file `plugins/Skript/Materials.json`
- Start your server
- Observe to see if this error still persists

**Comment by DeagoTheDoggo** [comment]
Thanks for your help that was the fix :).

**Comment by Blueyescat** [comment]
fyi it happens when you downgrade your mc version
