### ISSUE TITLE
Skript Task #781 Error

### ISSUE THREAD

**Issue by Agadolrim** [SkriptLang/Skript#2583]
[Skript] Task #781 for Skript v2.4-beta9 generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.LivingEntity.getMaxHealth()I
	at com.marquez.marsk.Expressions.ExprMaxHealth.get(ExprMaxHealth.java:39) ~[?:?]
	at com.marquez.marsk.Expressions.ExprMaxHealth.get(ExprMaxHealth.java:1) ~[?:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[?:?]
	at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:60) ~[?:?]
	at ch.njol.skript.expressions.ExprArithmetic.get(ExprArithmetic.java:172) ~[?:?]
	at ch.njol.skript.expressions.ExprArithmetic.get(ExprArithmetic.java:1) ~[?:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[?:?]
	at ch.njol.skript.lang.VariableString.toString(VariableString.java:477) ~[?:?]
	at ch.njol.skript.lang.VariableString.getArray(VariableString.java:726) ~[?:?]
	at ch.njol.skript.lang.VariableString.getArray(VariableString.java:1) ~[?:?]
	at ch.njol.skript.effects.EffChange.execute(EffChange.java:278) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
	at ch.njol.skript.effects.Delay$1.run(Delay.java:109) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1237]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1237]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1237]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1237]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1237]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1237]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

i used Express "max health of victim"

**Comment by ShaneBeee** [comment]
This error is not from Skript
```
at com.marquez.marsk.Expressions.ExprMaxHealth.get(ExprMaxHealth.java:39) ~[?:?]
at com.marquez.marsk.Expressions.ExprMaxHealth.get(ExprMaxHealth.java:1) ~[?:?]
```
