### ISSUE TITLE
Dye Effect

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#2623]
### Description
When using the dye effect it errors

### Steps to Reproduce
```
command /dyetest:
	trigger:
		set player's helmet to leather helmet
		set player's chestplate to leather chestplate
		set player's leggings to leather leggings
		set player's boots to leather boots
		dye player's helmet yellow
		dye player's chestplate yellow
		dye player's leggings yellow
		dye player's boots yellow
```

### Expected Behavior
It should dye the player's armor yellow and not throw errors in console, however it only dyes the first item and throws errors

### Errors / Screenshots
```
[21:13:29] [Server thread/ERROR]: #!#! 
[21:13:29] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[21:13:29] [Server thread/ERROR]: #!#! 
[21:13:29] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[21:13:29] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[21:13:29] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[21:13:29] [Server thread/ERROR]: #!#! Here is full list of them:
[21:13:29] [Server thread/ERROR]: #!#! skRayFall (https://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) Kosmos (tlatoani.us/kosmos) ThatPacketAddon (tlatoani.us/thatpacketaddon) Tablisknu (tlatoani.us/tablisknu) Skellett (https://forums.skunity.com/resources/skellett.24/) Skope (tlatoani.us/skope) Skent skript-mirror (https://github.com/btk5h/skript-mirror) SkVault skript-yaml SkQuery HolographicDisplaysAddon 
[21:13:29] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[21:13:29] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[21:13:29] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[21:13:29] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[21:13:29] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[21:13:29] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[21:13:29] [Server thread/ERROR]: #!#! 
[21:13:29] [Server thread/ERROR]: #!#! Stack trace:
[21:13:29] [Server thread/ERROR]: #!#! java.lang.UnsupportedOperationException
[21:13:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.change(SimpleExpression.java:239)
[21:13:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.ConvertedExpression.change(ConvertedExpression.java:153)
[21:13:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffColorItems.execute(EffColorItems.java:154)
[21:13:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[21:13:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[21:13:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[21:13:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[21:13:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
[21:13:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[21:13:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:251)
[21:13:29] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:168)
[21:13:29] [Server thread/ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[21:13:29] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:13:29] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[21:13:29] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520)
[21:13:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1775)
[21:13:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591)
[21:13:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:13:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[21:13:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[21:13:29] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:13:29] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:13:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[21:13:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
[21:13:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[21:13:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[21:13:29] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[21:13:29] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[21:13:29] [Server thread/ERROR]: #!#! 
[21:13:29] [Server thread/ERROR]: #!#! Version Information:
[21:13:29] [Server thread/ERROR]: #!#!   Skript: 2.4-beta9 (latest)
[21:13:29] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[21:13:29] [Server thread/ERROR]: #!#!     Date: 2019-10-15
[21:13:29] [Server thread/ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[21:13:29] [Server thread/ERROR]: #!#!   Minecraft: 1.13.2
[21:13:29] [Server thread/ERROR]: #!#!   Java: 1.8.0_66 (Java HotSpot(TM) 64-Bit Server VM 25.66-b17)
[21:13:29] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.10.0-957.12.2.vz7.96.21
[21:13:29] [Server thread/ERROR]: #!#! 
[21:13:29] [Server thread/ERROR]: #!#! Server platform: Paper
[21:13:29] [Server thread/ERROR]: #!#! 
[21:13:29] [Server thread/ERROR]: #!#! Current node: null
[21:13:29] [Server thread/ERROR]: #!#! Current item: dye (the helmet of the player >> ChainedConverter{first=ch.njol.skript.classes.data.DefaultConverters$17@141e074,second=ch.njol.skript.classes.data.DefaultConverters$14@16e595cb}: slot -> itemstack -> itemstack -> itemtype) [[color:yellow]]
[21:13:29] [Server thread/ERROR]: #!#! Current trigger: command /dyetest (simple event) (NewUpdate.sk, line -1)
[21:13:29] [Server thread/ERROR]: #!#! 
[21:13:29] [Server thread/ERROR]: #!#! Thread: Server thread
[21:13:29] [Server thread/ERROR]: #!#! 
[21:13:29] [Server thread/ERROR]: #!#! Language: english
[21:13:29] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[21:13:29] [Server thread/ERROR]: #!#! 
[21:13:29] [Server thread/ERROR]: #!#! End of Error.
[21:13:29] [Server thread/ERROR]: #!#! 
```

**Comment by APickledWalrus** [comment]
The return type info seems to be null. https://github.com/SkriptLang/Skript/blob/94851efc352fce5770f2dcb2a963e0b0cc95ea6a/src/main/java/ch/njol/skript/lang/util/SimpleExpression.java#L238

Not sure why though.
