### ISSUE TITLE
set level progress error

### ISSUE THREAD

**Issue by qtt509** [SkriptLang/Skript#2680]
why is this??

Minecraft: 1.12.2 paper
Skript - 2.4

![1](https://user-images.githubusercontent.com/58448722/70421471-26bff480-1aad-11ea-9e73-86a4151df1a4.PNG)

This is Function
![2](https://user-images.githubusercontent.com/58448722/70421477-29224e80-1aad-11ea-91e2-a5a48b5b872d.PNG)

**Comment by qtt509** [comment]
> why is this??
> 
> Minecraft: 1.12.2 paper
> Skript - 2.4
> 
> ![1](https://user-images.githubusercontent.com/58448722/70421471-26bff480-1aad-11ea-9e73-86a4151df1a4.PNG)
> 
> this is Function
> ![2](https://user-images.githubusercontent.com/58448722/70421477-29224e80-1aad-11ea-91e2-a5a48b5b872d.PNG)

**Comment by FranKusmiruk** [comment]
You've cut a part of the error in that image, please use a paste service such as pastebin or gist and send the error here.

**Comment by qtt509** [comment]
https://pastebin.com/1kMucCuK

here !!

**Comment by TPGamesNL** [comment]
> https://pastebin.com/1kMucCuK
> 
> here !!

That's the code, not the error

**Comment by qtt509** [comment]
> > https://pastebin.com/1kMucCuK
> > here !!
> 
> That's the code, not the error

Thank you for answer. I'll look for it

**Comment by Wealthyturtle** [comment]
Was able to replicate this issue. Code:
```
command /t:
    trigger:
        set player's level progress to {_x} / 0
```

Note:
```
command /t:
    trigger:
        set player's level progress to {_x}
```
Doesn't throw an error.

Error:
``` [Server thread/ERROR]: #!#! Stack trace:
 [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: Experience progress must be between 0.0 and 1.0 (NaN)
 [Server thread/ERROR]: #!#!     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
 [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.setExp(CraftPlayer.java:951)
 [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprLevelProgress.change(ExprLevelProgress.java:104)
 [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
 [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
 [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
 [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
 [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
 [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
 [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
 [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:251)
 [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:168)
 [Server thread/ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 [Server thread/ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 [Server thread/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 [Server thread/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
 [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
 [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
 [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
 [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
 [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1633)
 [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481)
 [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
 [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
 [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
 [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
 [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
 [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
 [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
 [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910)
 [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903)
 [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
 [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887)
 [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820)
 [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)```
