### ISSUE TITLE
1.15.1/2.4.1 - No such file or directory and many error

### ISSUE THREAD

**Issue by Zzheyd** [SkriptLang/Skript#2729]
Hi here i was try last version : 2.4.1 with last paper :  Paper version git-Paper-31 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

And i have this :

```
#!#! Only if the author tells you to do so, report it to Skript's issue tracker.
#!#!
#!#! Stack trace:
#!#! java.io.FileNotFoundException: plugins/Skript.jar (No such file or directory)
#!#! at java.util.zip.ZipFile.open(Native Method)
#!#! at java.util.zip.ZipFile.<init>(ZipFile.java:225)
#!#! at java.util.zip.ZipFile.<init>(ZipFile.java:155)
#!#! at java.util.jar.JarFile.<init>(JarFile.java:166)
#!#! at java.util.jar.JarFile.<init>(JarFile.java:130)
#!#! at ch.njol.skript.Skript$2.run(Skript.java:449)
#!#! at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
#!#! at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
#!#! at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179)
#!#! at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417)
#!#! at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106)
#!#! at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933)
#!#! at java.lang.Thread.run(Thread.java:748)
#!#!
#!#! Version Information:
#!#! Skript: 2.4.1 (latest)
#!#! Flavor: skriptlang-github
#!#! Date: 2019-12-22
#!#! Bukkit: 1.15.1-R0.1-SNAPSHOT
#!#! Minecraft: 1.15.1
#!#! Java: 1.8.0_222 (OpenJDK 64-Bit Server VM 25.222-b10)
#!#! OS: Linux amd64 4.9.133-xxxx-std-ipv6-64
#!#!
#!#! Server platform: Paper
#!#!
#!#! Current node: null
#!#! Current item: null
#!#!
#!#! Thread: Server thread
#!#!
#!#! Language: english
#!#! Link parse mode: DISABLED
#!#!
#!#! End of Error.
#!#!
```

And many errors : 

```
[Skript]: can't understand this condition: 'player's money is greater or equal to {_xpprice}' (BankXP.sk, line 205: if player's money is greater or equal to {_xpprice}:')


[Skript]: Can't understand this expression: region at player (Command.sk, line 688: if "%region at player%" contains "shop":')

[Skript]: can't understand this event: 'on region exit' (FreakFoire.sk, line 270: on region exit:')

[Skript]: can't understand this event: 'on region enter' (FreakFoire.sk, line 370: on region enter:')
```

If you have any idea :/

Thank you !

**Comment by bluelhf** [comment]
Update WorldGuard and Vault, reinstall Skript 2.4.1

**Comment by nopeless** [comment]
reinstall?

**Comment by Zzheyd** [comment]
Hum after restart, its fine ... strangly ?

Thanks.
