### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Perdume** [SkriptLang/Skript#2786]
1 log handler was not stopped properly! (at ch.njol.skript.lang.Statement.parse(Statement.java:54)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

` [Skript] Task #113 for Skript v2.4.1 generated an exception
java.lang.NullPointerException: null
        at ch.njol.skript.log.LogEntry.<init>(LogEntry.java:60) ~[?:?]
        at ch.njol.skript.log.SkriptLogger.log(SkriptLogger.java:164) ~[?:?]
        at ch.njol.skript.Skript.info(Skript.java:1370) ~[?:?]
        at ch.njol.skript.log.ErrorDescLogHandler.onSuccess(ErrorDescLogHandler.java:70) ~[?:?]
        at ch.njol.skript.log.ErrorDescLogHandler.onStop(ErrorDescLogHandler.java:76) ~[?:?]
        at ch.njol.skript.log.LogHandler.stop(LogHandler.java:44) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:350) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:380) ~[?:?]
        at ch.njol.skript.Skript$2.run(Skript.java:534) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.1.jar:git-Spigo
t-2ee05fe-d31f05f]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [s
pigot-1.15.1.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1030) [spigot-1.15.1.jar:git-Spigot
-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.1.jar:git-Spigot-
2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.1.jar:git-Spigot-
2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.1.jar:git-Spigo
t-2ee05fe-d31f05f]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]`

**Comment by bluelhf** [comment]
Do you have a pre-2.0.0-SNAPSHOT version of skript-mirror?

**Comment by Wealthyturtle** [comment]
Duplicate https://github.com/SkriptLang/Skript/issues/2671
