### ISSUE TITLE
bug...

### ISSUE THREAD

**Issue by Perdume** [SkriptLang/Skript#2787]
```[19:34:02] [Server thread/WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[19:34:02] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137)
[19:34:02] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:333)
[19:34:02] [Server thread/WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:356)
[19:34:02] [Server thread/WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318)
[19:34:02] [Server thread/WARN]:        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380)
[19:34:02] [Server thread/WARN]:        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[19:34:02] [Server thread/WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[19:34:02] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:34:02] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148)
[19:34:02] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:690)
[19:34:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1606)
[19:34:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1460)
[19:34:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(SourceFile:36)
[19:34:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(SourceFile:9)
[19:34:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[19:34:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[19:34:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[19:34:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[19:34:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[19:34:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:875)
[19:34:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:868)
[19:34:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[19:34:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:852)
[19:34:02] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:792)
[19:34:02] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
[19:34:02] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[19:34:02] [Server thread/WARN]:        at ch.njol.skript.Skript.<init>(Skript.java:205)
[19:34:02] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:34:02] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:34:02] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:34:02] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[19:34:02] [Server thread/WARN]:        at java.lang.Class.newInstance(Class.java:442)
[19:34:02] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71)
[19:34:02] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)
[19:34:02] [Server thread/WARN]:        ... 24 more```



Version:  2.4.1

**Comment by ShaneBeee** [comment]
```
[19:34:02] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137)
[19:34:02] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:333)
[19:34:02] [Server thread/WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:356)
[19:34:02] [Server thread/WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318)
```
Looks like you are using Plugman to load/unload Skript, which is causing issues. 
This is not a Skript issue, this is an issue with Plugman.
