### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by hyungjun-kim-creator** [SkriptLang/Skript#2788]
### Question
```
<!--- A clear description of your question --->
[19:47:51] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[19:47:51] [Server thread/ERROR]: #!#! Could not load OpSayHello.sk
[19:47:51] [Server thread/ERROR]: #!#!
[19:47:51] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[19:47:51] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[19:47:51] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[19:47:51] [Server thread/ERROR]: #!#! Here is full list of them:
[19:47:51] [Server thread/ERROR]: #!#! Skript-Paper v1.3.0 (https://github.com/ShaneBeee/Skript-Paper) Skuared v1.1 Conquer v1.3.1 skRayFall v1.9.18 (https://sk.rayfall.net/) Vixio v2.0.4 (http://vixio.space) TuSKe v1.8.2 (github.com/Tuke-Nuke/TuSKe) SK-NBeeT v2.9.3 (https://github.com/ShaneBeee/Sk-NBeeT) GameAPI v2.0.3 Kosmos v1.0-BETA.4 (tlatoani.us/kosmos) NpcAddon v1.0.0 Ticker v1.0.0 TwitterSK v1.0.3 Quarsk v1.3 Skungee v1.0.11 skLib v1.1.0 (https://github.com/WheezyGold7931/skLib/) skDragon v0.16 skript-yaml v1.3.2 Skematic v2.2b (https://forums.skunity.com/resources/skematic.671/) Umbaska v3.3 IdkSk v1.2.1 TeamSkript v1.0.0 HyperSK v0.0.1 (https://hypermc.dk) MundoSK v1.8.5 (https://forums.skunity.com/resources/mundosk.69/) Skellett v1.9.8 (https://forums.skunity.com/resources/skellett.24/) SharpSK v1.6.3 skript-hack v0.1 TranSKator v0.1.2 (https://discord.gg/G6ca9S5) Khoryl v1.0.1 BunchSk v1.8 SkStuff v1.6.4.1 skUtilities v0.9.2 (https://tim740.github.io/) SkQuery v4.1.1 WebSKT v1.0-BETA.2 (tlatoani.us/webskt)
[19:47:51] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[19:47:51] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[19:47:51] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[19:47:51] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[19:47:51] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[19:47:51] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[19:47:51] [Server thread/ERROR]: #!#!
[19:47:51] [Server thread/ERROR]: #!#! Stack trace:
[19:47:51] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for citizen
[19:47:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[19:47:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1838)
[19:47:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1805)
[19:47:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1553)
[19:47:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1499)
[19:47:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[19:47:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[19:47:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:81)
[19:47:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1090)
[19:47:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:490)
[19:47:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:652)
[19:47:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:410)
[19:47:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:429)
[19:47:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:473)
[19:47:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:192)
[19:47:51] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:47:51] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[19:47:51] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711)
[19:47:51] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:696)
[19:47:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:436)
[19:47:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:400)
[19:47:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
[19:47:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
[19:47:51] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[19:47:51] [Server thread/ERROR]: #!#!
[19:47:51] [Server thread/ERROR]: #!#! Version Information:
[19:47:51] [Server thread/ERROR]: #!#!   Skript: 2.5-alpha1 (latest)
[19:47:51] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[19:47:51] [Server thread/ERROR]: #!#!     Date: 2020-01-11
[19:47:51] [Server thread/ERROR]: #!#!   Bukkit: 1.15.2-R0.1-SNAPSHOT
[19:47:51] [Server thread/ERROR]: #!#!   Minecraft: 1.15.2
[19:47:51] [Server thread/ERROR]: #!#!   Java: 1.8.0_231 (Java HotSpot(TM) 64-Bit Server VM 25.231-b11)
[19:47:51] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[19:47:51] [Server thread/ERROR]: #!#!
[19:47:51] [Server thread/ERROR]: #!#! Server platform: Spigot
[19:47:51] [Server thread/ERROR]: #!#!
[19:47:51] [Server thread/ERROR]: #!#! Current node: if player is op: (OpSayHello.sk, line 3)
[19:47:51] [Server thread/ERROR]: #!#! Current item: null
[19:47:51] [Server thread/ERROR]: #!#!
[19:47:51] [Server thread/ERROR]: #!#! Thread: Server thread
[19:47:51] [Server thread/ERROR]: #!#!
[19:47:51] [Server thread/ERROR]: #!#! Language: english
[19:47:51] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[19:47:51] [Server thread/ERROR]: #!#!
[19:47:51] [Server thread/ERROR]: #!#! End of Error.
[19:47:51] [Server thread/ERROR]: #!#!
```
what`s the matter?

**Comment by ShaneBeee** [comment]
1) This appears to be an issue with an addon:
` No class info found for citizen`

2) You seem to be running a few extremely outdated addons:
`Skript-Paper v1.3.0 (https://github.com/ShaneBeee/Skript-Paper) Skuared v1.1 Conquer v1.3.1 skRayFall v1.9.18 (https://sk.rayfall.net/) Vixio v2.0.4 (http://vixio.space) TuSKe v1.8.2 (github.com/Tuke-Nuke/TuSKe) SK-NBeeT v2.9.3 (https://github.com/ShaneBeee/Sk-NBeeT) GameAPI v2.0.3 Kosmos v1.0-BETA.4 (tlatoani.us/kosmos) NpcAddon v1.0.0 Ticker v1.0.0 TwitterSK v1.0.3 Quarsk v1.3 Skungee v1.0.11 skLib v1.1.0 (https://github.com/WheezyGold7931/skLib/) skDragon v0.16 skript-yaml v1.3.2 Skematic v2.2b (https://forums.skunity.com/resources/skematic.671/) Umbaska v3.3 IdkSk v1.2.1 TeamSkript v1.0.0 HyperSK v0.0.1 (https://hypermc.dk) MundoSK v1.8.5 (https://forums.skunity.com/resources/mundosk.69/) Skellett v1.9.8 (https://forums.skunity.com/resources/skellett.24/) SharpSK v1.6.3 skript-hack v0.1 TranSKator v0.1.2 (https://discord.gg/G6ca9S5) Khoryl v1.0.1 BunchSk v1.8 SkStuff v1.6.4.1 skUtilities v0.9.2 (https://tim740.github.io/) SkQuery v4.1.1 WebSKT v1.0-BETA.2 (tlatoani.us/webskt) `
I know for a fact that SkUtilities, SkStuff and Umbaska do not work on recent versions of MC.

I recommend removing some of these outdated addons and see if that resolves your issue.

Im closing this due to the fact that this is not a Skript issue.
