### ISSUE TITLE
1.12.2 Spigot issue: java.lang.NoSuchMethodError: ch.njol.skript.util.Color.byName

### ISSUE THREAD

**Issue by LastDIce** [SkriptLang/Skript#2800]
here is crash log:

[04:08:42 WARN]: [Skript] Task #6 for Skript v2.4.1 generated an exception
java.lang.NoSuchMethodError: ch.njol.skript.util.Color.byName(Ljava/lang/String;)Lch/njol/skript/util/Color;
        at com.w00tmast3r.skquery.elements.Types$5.parse(Types.java:178) ~[?:?]
        at com.w00tmast3r.skquery.elements.Types$5.parse(Types.java:1) ~[?:?]
        at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:421) ~[?:?]
        at ch.njol.skript.registrations.Classes.parse(Classes.java:450) ~[?:?]
        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:95) ~[?:?]
        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:84) ~[?:?]
        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) ~[?:?]
        at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:173) ~[?:?]
        at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:124) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179) ~[?:?]
        at ch.njol.skript.lang.Condition.parse(Condition.java:81) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1086) ~[?:?]
        at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54) ~[?:?]
        at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1093) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:693) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:409) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:428) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:347) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:380) ~[?:?]
        at ch.njol.skript.Skript$2.run(Skript.java:534) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]

spigot version: final build for 1.12.2

**Comment by ShaneBeee** [comment]
```
ch.njol.skript.util.Color.byName(Ljava/lang/String;)Lch/njol/skript/util/Color;
at com.w00tmast3r.skquery.elements.Types$5.parse(Types.java:178) ~[?:?]
at com.w00tmast3r.skquery.elements.Types$5.parse(Types.java:1) ~[?:?]
```
Which version of SkQuery are you running? My guess is something not compatible.

**Comment by Wealthyturtle** [comment]
I think this happens because the Skript color update broke compatibility with SkQuery.
