### ISSUE TITLE
Error in 1.12.2 Paper or Spigot (paper-1618.jar or spigot-1.12.2.jar)

### ISSUE THREAD

**Issue by Tyberhertz** [SkriptLang/Skript#2817]
### Description
With this version of script, none of my scripts go anymore ..

### Errors / Screenshots

#Paper
`[00:37:36 WARN]: [Skript] Task #36 for Skript v2.4.1 generated an exception
java.lang.NoSuchMethodError: ch.njol.skript.util.Color.byName(Ljava/lang/String;)Lch/njol/skript/util/Color;
        at com.w00tmast3r.skquery.elements.Types$5.parse(Types.java:178) ~[?:?]
        at com.w00tmast3r.skquery.elements.Types$5.parse(Types.java:1) ~[?:?]
        at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:421) ~[?:?]
        at ch.njol.skript.registrations.Classes.parse(Classes.java:450) ~[?:?]
        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:95) ~[?:?]
        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:84) ~[?:?]
        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) ~[?:?]
        at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:173) ~[?:?]
        at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:124) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179) ~[?:?]
        at ch.njol.skript.lang.Condition.parse(Condition.java:81) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1086) ~[?:?]
        at ch.njol.skript.lang.Loop.<init>(Loop.java:66) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1043) ~[?:?]
        at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:48) ~[?:?]
        at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:153) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:665) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:409) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:428) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:347) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:380) ~[?:?]
        at ch.njol.skript.Skript$2.run(Skript.java:534) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
`

#Spigot
`[00:44:11 WARN]: [Skript] Task #33 for Skript v2.4.1 generated an exception
java.lang.NoSuchMethodError: ch.njol.skript.util.Color.byName(Ljava/lang/String;)Lch/njol/skript/util/Color;
        at com.w00tmast3r.skquery.elements.Types$5.parse(Types.java:178) ~[?:?]
        at com.w00tmast3r.skquery.elements.Types$5.parse(Types.java:1) ~[?:?]
        at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:421) ~[?:?]
        at ch.njol.skript.registrations.Classes.parse(Classes.java:450) ~[?:?]
        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:95) ~[?:?]
        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:84) ~[?:?]
        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) ~[?:?]
        at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:173) ~[?:?]
        at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:124) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179) ~[?:?]
        at ch.njol.skript.lang.Condition.parse(Condition.java:81) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1086) ~[?:?]
        at ch.njol.skript.lang.Loop.<init>(Loop.java:66) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1043) ~[?:?]
        at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:48) ~[?:?]
        at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:153) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:665) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:409) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:428) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:347) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:380) ~[?:?]
        at ch.njol.skript.Skript$2.run(Skript.java:534) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
`

### Server Information
* **Server version/platform: paper-1618 and spigot-1.12.2**
* **Skript version: Skript v2.4.1**

**Comment by ShaneBeee** [comment]
That error is from SkQuery not Skript. 
My guess is you are using an outdated version of SkQuery.
