### ISSUE TITLE
Severe Error

### ISSUE THREAD

**Issue by Johtomies** [SkriptLang/Skript#2827]
When I restart, or reload the server, my scripts doesnt work until I reload them one by one. When I do /sk reload all, the console gives me this:

21.02 19:10:16 [Server] ERROR #!#! 
21.02 19:10:16 [Server] ERROR #!#! [Skript] Severe Error:
21.02 19:10:16 [Server] ERROR #!#! Exception occurred in Skript's main command
21.02 19:10:16 [Server] ERROR #!#! Used command: /sk reload all
21.02 19:10:16 [Server] ERROR #!#! 
21.02 19:10:16 [Server] ERROR #!#! Something went horribly wrong with Skript.
21.02 19:10:16 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
21.02 19:10:16 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
21.02 19:10:16 [Server] ERROR #!#! Here is full list of them:
21.02 19:10:16 [Server] ERROR #!#! skRayFall (https://sk.rayfall.net/) 
21.02 19:10:16 [Server] ERROR #!#! We could not identify which of those are specially related, so this might also be Skript issue.
21.02 19:10:16 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
21.02 19:10:16 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
21.02 19:10:16 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
21.02 19:10:16 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
21.02 19:10:16 [Server] ERROR #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
21.02 19:10:16 [Server] ERROR #!#! 
21.02 19:10:16 [Server] ERROR #!#! Stack trace:
21.02 19:10:16 [Server] ERROR #!#! java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: plugins/Skript/scripts/kirvesjaj????.sk
21.02 19:10:16 [Server] ERROR #!#!     at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
21.02 19:10:16 [Server] ERROR #!#!     at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
21.02 19:10:16 [Server] ERROR #!#!     at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
21.02 19:10:16 [Server] ERROR #!#!     at java.io.File.toPath(File.java:2234)
21.02 19:10:16 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:948)
21.02 19:10:16 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadStructure(ScriptLoader.java:828)
21.02 19:10:16 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadStructures(ScriptLoader.java:814)
21.02 19:10:16 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:346)
21.02 19:10:16 [Server] ERROR #!#!     at 

Server version/platform: Minecraft 1.13.2      
Skript version: 2.4.1

**Comment by Johtomies** [comment]
Edit: Found the problem, it was in one of my scripts (I dont know how), but I deleted it.

**Comment by Johtomies** [comment]
Found the error. The error was in the name of the script.
