### ISSUE TITLE
Cant reload Skript

### ISSUE THREAD

**Issue by Mlandbo** [SkriptLang/Skript#2853]
I really need help. I tried to make a Skript for the server that I'm admin on. But when I try to reload to Skript this happens: 
[15:01:20] [Server thread/ERROR]: #!#! 
[15:01:20] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[15:01:20] [Server thread/ERROR]: #!#! Exception occurred in Skript's main command
[15:01:20] [Server thread/ERROR]: #!#! Used command: /sk reload market
[15:01:20] [Server thread/ERROR]: #!#! 
[15:01:20] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[15:01:20] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[15:01:20] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[15:01:20] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[15:01:20] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[15:01:20] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[15:01:20] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[15:01:20] [Server thread/ERROR]: #!#! 
[15:01:20] [Server thread/ERROR]: #!#! Stack trace:
[15:01:20] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[15:01:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.clearFunctions(Functions.java:269)
[15:01:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.removeTriggers(SkriptEventHandler.java:240)
[15:01:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript_(ScriptLoader.java:712)
[15:01:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:705)
[15:01:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:183)
[15:01:20] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:01:20] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:01:20] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[15:01:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[15:01:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[15:01:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:01:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:01:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[15:01:20] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:01:20] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:01:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[15:01:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[15:01:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[15:01:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[15:01:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[15:01:20] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[15:01:20] [Server thread/ERROR]: #!#! 
[15:01:20] [Server thread/ERROR]: #!#! Version Information:
[15:01:20] [Server thread/ERROR]: #!#!   Skript: 2.2-dev27
[15:01:20] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[15:01:20] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[15:01:20] [Server thread/ERROR]: #!#!   Java: 1.8.0_222 (OpenJDK 64-Bit Server VM 25.222-b10)
[15:01:20] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.0.0-20-generic
[15:01:20] [Server thread/ERROR]: #!#! 
[15:01:20] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[15:01:20] [Server thread/ERROR]: #!#! 
[15:01:20] [Server thread/ERROR]: #!#! Current node: null
[15:01:20] [Server thread/ERROR]: #!#! Current item: null
[15:01:20] [Server thread/ERROR]: #!#! 
[15:01:20] [Server thread/ERROR]: #!#! Thread: Server thread
[15:01:20] [Server thread/ERROR]: #!#! 
[15:01:20] [Server thread/ERROR]: #!#! End of Error.

Can anyone help me?

**Comment by TheBentoBox** [comment]
You are using an old version of Skript and we don't support 1.8.

You can try updating to the latest [release](https://github.com/SkriptLang/Skript/releases/) but other than that we cannot help you if you are using an unsupported server version.
