### ISSUE TITLE
on break ClassCastException

### ISSUE THREAD

**Issue by yhdev7935** [SkriptLang/Skript#2861]
### Errors / Screenshots
```[18:39:42] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[18:39:42] [Server thread/ERROR]: #!#! 
[18:39:42] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[18:39:42] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[18:39:42] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[18:39:42] [Server thread/ERROR]: #!#! Here is full list of them:
[18:39:42] [Server thread/ERROR]: #!#! skRayFall (http://sk.rayfall.net/) skript-mirror (https://github.com/btk5h/skript-mirror) Vixio (http://vixio.space) skUtilities (https://tim740.github.io/) skript-yaml SkQuery Skellett (https://forums.skunity.com/resources/skellett.24/) WildSkript (http://www.dzikoysk.net/) 
[18:39:42] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[18:39:42] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[18:39:42] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[18:39:42] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[18:39:42] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[18:39:42] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[18:39:42] [Server thread/ERROR]: #!#! 
[18:39:42] [Server thread/ERROR]: #!#! Stack trace:
[18:39:42] [Server thread/ERROR]: #!#! java.lang.ClassCastException: org.bukkit.event.hanging.HangingBreakEvent cannot be cast to org.bukkit.event.hanging.HangingBreakByEntityEvent
[18:39:42] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.Register$46.get(Register.java:566)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.EventValues$2.get(EventValues.java:193)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.EventValues$2.get(EventValues.java:1)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.EventValueExpression.getValue(EventValueExpression.java:104)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.EventValueExpression.get(EventValueExpression.java:90)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:113)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:1)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:161)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:253)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:51)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:156)
[18:39:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:114)
[18:39:42] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[18:39:42] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:39:42] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[18:39:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.EntityHanging.B_(EntityHanging.java:118)
[18:39:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1797)
[18:39:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.World.h(World.java:1767)
[18:39:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1574)
[18:39:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:682)
[18:39:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921)
[18:39:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[18:39:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[18:39:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[18:39:42] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[18:39:42] [Server thread/ERROR]: #!#! 
[18:39:42] [Server thread/ERROR]: #!#! Version Information:
[18:39:42] [Server thread/ERROR]: #!#!   Skript: 2.4
[18:39:42] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[18:39:42] [Server thread/ERROR]: #!#!     Date: 2019-11-30
[18:39:42] [Server thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[18:39:42] [Server thread/ERROR]: #!#!   Minecraft: 1.12.2
[18:39:42] [Server thread/ERROR]: #!#!   Java: 1.8.0_112 (Java HotSpot(TM) 64-Bit Server VM 25.112-b15)
[18:39:42] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[18:39:42] [Server thread/ERROR]: #!#! 
[18:39:42] [Server thread/ERROR]: #!#! Server platform: Paper
[18:39:42] [Server thread/ERROR]: #!#! 
[18:39:42] [Server thread/ERROR]: #!#! Current node: null
[18:39:42] [Server thread/ERROR]: #!#! Current item: the world of the player is equal to ("추석", "던전", "world", "Unknown", "PVP1", "어린이날던전" or "신던전")[class java.lang.String] (comparator: ch.njol.skript.classes.data.DefaultComparators$15@3fdf71de)
[18:39:42] [Server thread/ERROR]: #!#! Current trigger: break (break/place/burn/fade/form of <none>) (블럭보호.sk, line 8)
[18:39:42] [Server thread/ERROR]: #!#! 
[18:39:42] [Server thread/ERROR]: #!#! Thread: Server thread
[18:39:42] [Server thread/ERROR]: #!#! 
[18:39:42] [Server thread/ERROR]: #!#! Language: english
[18:39:42] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[18:39:42] [Server thread/ERROR]: #!#! 
[18:39:42] [Server thread/ERROR]: #!#! End of Error.

```

### Server Information
* **Server version/platform:**       1.12.2
* **Skript version:**                2.4

### Skript Code
```
on break:
	if player's world is "추석" or "던전" or "world" or "Unknown" or "PVP1" or "어린이날던전" or "신던전":
		if player is op:
			stop
		else:
			cancel event
			stop

```

**Comment by ShaneBeee** [comment]
2.4 is an outdated version, please try this at least on the latest version (2.4.1), and better yet, try on the latest alpha release (2.5-alpha2)

**Comment by yhdev7935** [comment]
```
[14:33:01] [Server thread/ERROR]: #!#! 
[14:33:01] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[14:33:01] [Server thread/ERROR]: #!#! 
[14:33:01] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[14:33:01] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:33:01] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[14:33:01] [Server thread/ERROR]: #!#! Here is full list of them:
[14:33:01] [Server thread/ERROR]: #!#! skRayFall (http://sk.rayfall.net/) skript-mirror (https://github.com/btk5h/skript-mirror) Vixio (http://vixio.space) skUtilities (https://tim740.github.io/) skript-yaml SkQuery Skellett (https://forums.skunity.com/resources/skellett.24/) WildSkript (http://www.dzikoysk.net/) 
[14:33:01] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[14:33:01] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[14:33:01] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[14:33:01] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[14:33:01] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[14:33:01] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[14:33:01] [Server thread/ERROR]: #!#! 
[14:33:01] [Server thread/ERROR]: #!#! Stack trace:
[14:33:01] [Server thread/ERROR]: #!#! java.lang.ClassCastException: org.bukkit.event.hanging.HangingBreakEvent cannot be cast to org.bukkit.event.hanging.HangingBreakByEntityEvent
[14:33:01] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.Register$46.get(Register.java:566)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.EventValues$2.get(EventValues.java:193)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.EventValues$2.get(EventValues.java:1)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.EventValueExpression.getValue(EventValueExpression.java:104)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.EventValueExpression.get(EventValueExpression.java:90)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:113)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:1)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:161)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:253)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:51)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:156)
[14:33:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:114)
[14:33:01] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[14:33:01] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[14:33:01] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[14:33:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.EntityHanging.B_(EntityHanging.java:118)
[14:33:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1797)
[14:33:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.World.h(World.java:1767)
[14:33:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1574)
[14:33:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:682)
[14:33:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921)
[14:33:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[14:33:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[14:33:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[14:33:01] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[14:33:01] [Server thread/ERROR]: #!#! 
[14:33:01] [Server thread/ERROR]: #!#! Version Information:
[14:33:01] [Server thread/ERROR]: #!#!   Skript: 2.4.1
[14:33:01] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[14:33:01] [Server thread/ERROR]: #!#!     Date: 2019-12-22
[14:33:01] [Server thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[14:33:01] [Server thread/ERROR]: #!#!   Minecraft: 1.12.2
[14:33:01] [Server thread/ERROR]: #!#!   Java: 1.8.0_112 (Java HotSpot(TM) 64-Bit Server VM 25.112-b15)
[14:33:01] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[14:33:01] [Server thread/ERROR]: #!#! 
[14:33:01] [Server thread/ERROR]: #!#! Server platform: Paper
[14:33:01] [Server thread/ERROR]: #!#! 
[14:33:01] [Server thread/ERROR]: #!#! Current node: null
[14:33:01] [Server thread/ERROR]: #!#! Current item: the world of the player is equal to ("추석", "던전", "world", "Unknown", "PVP1", "어린이날던전" or "신던전")[class java.lang.String] (comparator: ch.njol.skript.classes.data.DefaultComparators$15@ab7314e)
[14:33:01] [Server thread/ERROR]: #!#! Current trigger: break (break/place/burn/fade/form of <none>) (블럭보호.sk, line 8)
[14:33:01] [Server thread/ERROR]: #!#! 
[14:33:01] [Server thread/ERROR]: #!#! Thread: Server thread
[14:33:01] [Server thread/ERROR]: #!#! 
[14:33:01] [Server thread/ERROR]: #!#! Language: english
[14:33:01] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[14:33:01] [Server thread/ERROR]: #!#! 
[14:33:01] [Server thread/ERROR]: #!#! End of Error.
[14:33:01] [Server thread/ERROR]: #!#! 
```

Skript Version: 2.4.1

**Comment by ShaneBeee** [comment]
This error is caused from I believe Skellett:
```
[14:33:01] [Server thread/ERROR]: #!#! Stack trace:
[14:33:01] [Server thread/ERROR]: #!#! java.lang.ClassCastException: org.bukkit.event.hanging.HangingBreakEvent cannot be cast to org.bukkit.event.hanging.HangingBreakByEntityEvent
[14:33:01] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.Register$46.get(Register.java:566)
```

**Comment by yhdev7935** [comment]
How can i fix this error?

**Comment by ShaneBeee** [comment]
Im not sure, it doesn't appear to be a Skript error. You'll have to talk to the dev of the plugin that is causing this issue.
