### ISSUE TITLE
[Skript] Severe Error

### ISSUE THREAD

**Issue by fimtow** [SkriptLang/Skript#2880]
### Description

i get this error in the console but the server don't crash.

### Steps to Reproduce

it is caused by this skript
```
on death of player:
    ban player due to "&cYou died!"
    kick the player due to "&cYou died!"
```
it happens when killed by an entity.

### Errors / Screenshots

```
[17:04:30 ERROR]: #!#!
[17:04:30 ERROR]: #!#! [Skript] Severe Error:
[17:04:30 ERROR]: #!#!
[17:04:30 ERROR]: #!#! Something went horribly wrong with Skript.
[17:04:30 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:04:30 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[17:04:30 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[17:04:30 ERROR]: #!#!
[17:04:30 ERROR]: #!#! Stack trace:
[17:04:30 ERROR]: #!#! java.lang.IllegalStateException: Removing entity while ticking!
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.WorldServer.removeEntity(WorldServer.java:1449)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.WorldServer.removePlayer(WorldServer.java:1469)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerList.disconnect(PlayerList.java:447)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1506)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnection.disconnect(PlayerConnection.java:282)
[17:04:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.kickPlayer(CraftPlayer.java:433)
[17:04:30 ERROR]: #!#!     at ch.njol.skript.effects.EffKick.execute(EffKick.java:82)
[17:04:30 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[17:04:30 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:04:30 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:04:30 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[17:04:30 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:156)
[17:04:30 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:114)
[17:04:30 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:04:30 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:04:30 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559)
[17:04:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:784)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityPlayer.die(EntityPlayer.java:592)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity(EntityHuman.java:801)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityPlayer.damageEntity(EntityPlayer.java:748)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityInsentient.B(EntityInsentient.java:1327)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityZombie.B(EntityZombie.java:359)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PathfinderGoalMeleeAttack.a(SourceFile:139)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PathfinderGoalMeleeAttack.e(SourceFile:131)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PathfinderGoalZombieAttack.e(SourceFile:28)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:54)
[17:04:30 ERROR]: #!#!     at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[17:04:30 ERROR]: #!#!     at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[17:04:30 ERROR]: #!#!     at java.util.Iterator.forEachRemaining(Unknown Source)
[17:04:30 ERROR]: #!#!     at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
[17:04:30 ERROR]: #!#!     at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[17:04:30 ERROR]: #!#!     at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[17:04:30 ERROR]: #!#!     at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[17:04:30 ERROR]: #!#!     at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[17:04:30 ERROR]: #!#!     at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[17:04:30 ERROR]: #!#!     at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:119)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityInsentient.doTick(EntityInsentient.java:686)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2596)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityInsentient.movementTick(EntityInsentient.java:525)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityMonster.movementTick(EntityMonster.java:23)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityZombie.movementTick(EntityZombie.java:209)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2383)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityZombie.tick(EntityZombie.java:180)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:768)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.World.a(World.java:862)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:504)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[17:04:30 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[17:04:30 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[17:04:30 ERROR]: #!#!
[17:04:30 ERROR]: #!#! Version Information:
[17:04:30 ERROR]: #!#!   Skript: 2.4.1 (latest)
[17:04:30 ERROR]: #!#!     Flavor: skriptlang-github
[17:04:30 ERROR]: #!#!     Date: 2019-12-22
[17:04:30 ERROR]: #!#!   Bukkit: 1.15.2-R0.1-SNAPSHOT
[17:04:30 ERROR]: #!#!   Minecraft: 1.15.2
[17:04:30 ERROR]: #!#!   Java: 1.8.0_221 (Java HotSpot(TM) 64-Bit Server VM 25.221-b11)
[17:04:30 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[17:04:30 ERROR]: #!#!
[17:04:30 ERROR]: #!#! Server platform: Paper
[17:04:30 ERROR]: #!#!
[17:04:30 ERROR]: #!#! Current node: null
[17:04:30 ERROR]: #!#! Current item: kick the player on account of "You died!"
[17:04:30 ERROR]: #!#! Current trigger: death of player (death/spawn of player) (hardcore.sk, line 1)
[17:04:30 ERROR]: #!#!
[17:04:30 ERROR]: #!#! Thread: Server thread
[17:04:30 ERROR]: #!#!
[17:04:30 ERROR]: #!#! Language: english
[17:04:30 ERROR]: #!#! Link parse mode: DISABLED
[17:04:30 ERROR]: #!#!
[17:04:30 ERROR]: #!#! End of Error.
```

### Server Information
* **Server version/platform:** Paper 143      
* **Skript version:** 2.4.1 (latest)

**Comment by Jayderp** [comment]
There is no player in an on damage event.
Try:
`on death of player:
    ban victim due to "&cYou died!"
    kick the victim due to "&cYou died!"`

**Comment by fimtow** [comment]
@Jayderp didn't work. I am having the same issue.

**Comment by bensku** [comment]
This is probably a Spigot bug, but we need to double-check.

**Comment by fimtow** [comment]
@bensku do you know how to get the same results using another skript without getting this error ?

**Comment by ShaneBeee** [comment]
I believe this is a Spigot bug. I've had many issues in my plugins regarding "entity is ticking" stuff.
To alleviate the issue, add a 1 tick wait before performing said tasks.

**Comment by TPGamesNL** [comment]
I cannot replicate this anymore on 1.16.5, meaning it's probably fixed, so I'm closing this
