### ISSUE TITLE
Can't use SkQuery add-on (Loaded 12 skripts 0 triggers loaded and 0 commands)...

### ISSUE THREAD

**Issue by danielzinh** [SkriptLang/Skript#2898]
Hi, when i put SkQuery (3+), my scripts won't load... huh, load, but won't load the commands and triggers... (same issue when put SkStuff)

Check the console error:

[02:56:52] [Server thread/ERROR]: #!#! 
[02:56:52] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[02:56:52] [Server thread/ERROR]: #!#! Could not load json.sk
[02:56:52] [Server thread/ERROR]: #!#! 
[02:56:52] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[02:56:52] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[02:56:52] [Server thread/ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[02:56:52] [Server thread/ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[02:56:52] [Server thread/ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[02:56:52] [Server thread/ERROR]: #!#! nor it will work, unless you switch to supported platform.
[02:56:52] [Server thread/ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[02:56:52] [Server thread/ERROR]: #!#! 
[02:56:52] [Server thread/ERROR]: #!#! Stack trace:
[02:56:52] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for lambda
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1804)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1771)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1519)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:495)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:814)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1535)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1531)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:972)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1058)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:66)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1008)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1058)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:66)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1008)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:50)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:143)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:634)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:389)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:401)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:331)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:361)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:786)
[02:56:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:154)
[02:56:52] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[02:56:52] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[02:56:52] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[02:56:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[02:56:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[02:56:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[02:56:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[02:56:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[02:56:52] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[02:56:52] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[02:56:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[02:56:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[02:56:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[02:56:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[02:56:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[02:56:52] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[02:56:52] [Server thread/ERROR]: #!#! 
[02:56:52] [Server thread/ERROR]: #!#! Version Information:
[02:56:52] [Server thread/ERROR]: #!#!   Skript: 2.2-dev36 (custom version)
[02:56:52] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[02:56:52] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[02:56:52] [Server thread/ERROR]: #!#!   Java: 1.8.0_241 (Java HotSpot(TM) 64-Bit Server VM 25.241-b07)
[02:56:52] [Server thread/ERROR]: #!#!   OS: Windows 7 amd64 6.1
[02:56:52] [Server thread/ERROR]: #!#! 
[02:56:52] [Server thread/ERROR]: #!#! Server platform: Spigot
[02:56:52] [Server thread/ERROR]: #!#! 
[02:56:52] [Server thread/ERROR]: #!#! Current node: set {_skip} to true (json.sk, line 108)
[02:56:52] [Server thread/ERROR]: #!#! Current item: null
[02:56:52] [Server thread/ERROR]: #!#! 
[02:56:52] [Server thread/ERROR]: #!#! Thread: Server thread
[02:56:52] [Server thread/ERROR]: #!#! 
[02:56:52] [Server thread/ERROR]: #!#! Language: english
[02:56:52] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[02:56:52] [Server thread/ERROR]: #!#! 
[02:56:52] [Server thread/ERROR]: #!#! End of Error.
[02:56:52] [Server thread/ERROR]: #!#! 

Can someone help-me plis?

**Comment by ShaneBeee** [comment]
1) `Skript: 2.2-dev36 (custom version)` <-- this version has been outdated for about 2 years.
When reporting issues, please make sure to be using recent software, as we will not be fixing old versions.

2) If you are having an issue with an addon, please report the issue to the respective addon. This issue tracker is strictly for the Strict software itself.

**Comment by danielzinh** [comment]
i have running Skript 2.2-dev36 in Spigot 1.8 SkQuery 3+ (i tried with latest and lowers versions), Vault, iConomy, WorldGuard and WorldEdit, and others plugins, if you need see ALL plugins, here is a print: https://imgur.com/a/3j7mREM

**Comment by danielzinh** [comment]
yeah @ShaneBeee but my friend say me that Skript 2.3 or upper versions dont work in 1.8, only in 1.9+, i just wanted to know if SOMEONE could help me...

**Comment by ShaneBeee** [comment]
> yeah @ShaneBeee but my friend say me that Skript 2.3 or upper versions dont work in 1.8, only in 1.9+, i just wanted to know if SOMEONE could help me...

This issue tracker is for ISSUES in the latest versions of Skript. If you require support for outdated software, please use one of the Skript discords and/or forums. You can find links for this in the readme/main page of this repo.

**Comment by danielzinh** [comment]
have you saying that you, ShaneBee, most famous skripter, won't help me? :( i... i'm an :,(

**Comment by ShaneBeee** [comment]
> have you saying that you, ShaneBee, most famous skripter, won't help me? :( i... i'm an :,(

Famous or not, allow me to repeat a few things:
1) this is an issue tracker for **ISSUES** in **SKRIPT**'s **LATEST** versions of the software.
We do not provide personal support on this issue tracker. If you require support please use the support mediums listed on the main page of the repo (the readme)

2) You are running 1.8.x, this fork has never supported 1.8.x and probably never will.
