### ISSUE TITLE
Problem Scoreboard

### ISSUE THREAD

**Issue by TheMrPro** [SkriptLang/Skript#2906]
Can Any one help me in this error
```
[01:57:47 ERROR]: #!#! Stack trace:
[01:57:47 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for player'
[01:57:47 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:262)
[01:57:47 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1417)
[01:57:47 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1138)
[01:57:47 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
[01:57:47 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[01:57:47 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[01:57:47 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:753)
[01:57:47 ERROR]: #!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:66)
[01:57:47 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:789)
[01:57:47 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:510)
[01:57:47 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:269)
[01:57:47 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:185)
[01:57:47 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[01:57:47 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[01:57:47 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[01:57:47 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[01:57:47 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[01:57:47 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[01:57:47 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[01:57:47 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[01:57:47 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[01:57:47 ERROR]: #!#!
[01:57:47 ERROR]: #!#! Version Information:
[01:57:47 ERROR]: #!#!   Skript: 2.2-dev27
[01:57:47 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[01:57:47 ERROR]: #!#!   Minecraft: 1.8.8
[01:57:47 ERROR]: #!#!   Java: 1.8.0_211 (Java HotSpot(TM) 64-Bit Server VM 25.211-b12)
[01:57:47 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[01:57:47 ERROR]: #!#!
[01:57:47 ERROR]: #!#! Running CraftBukkit: false
[01:57:47 ERROR]: #!#!
[01:57:47 ERROR]: #!#! Current node: set name of sidebar of loop-player to " {@ScoreboardTitle} " (scoreboard.sk, line 7)
[01:57:47 ERROR]: #!#! Current item: null
[01:57:47 ERROR]: #!#!
[01:57:47 ERROR]: #!#! Thread: Server thread
[01:57:47 ERROR]: #!#!
[01:57:47 ERROR]: #!#! End of Error.
```

**Comment by ShaneBeee** [comment]
Skript does not have a scoreboard system. Based on your code, I believe the would be an issue with SkRayFall.

This issue tracker is for the Skript software itself. Please report any issues you have with an addon to the respective addon developer.
