### ISSUE TITLE
Prevent users from deleting event-block in the BlockPlaceEvent

### ISSUE THREAD

**Issue by bonjourkemal** [SkriptLang/Skript#2910]
```
on place with chest:
	yaml list "icerik.%name of tool of player%" of "kutu" is set
	set {_random} to random element out of yaml list "icerik.%name of tool of player%" of "kutu"
	add {_random} to player's inventory
	launch ball large coloured red, purple and white fading to light green and black at (targeted block of player)'s location with duration 0
	delete event-block
```
When I reload, it does not errors. But when I put the chest, the chest is not removed and starts to errors on the console. But if I set the diamond block as an example instead of the chest, it does not give an errors, but the diamond block is not removed again.

Error:
```
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.Chunk.setTileEntity(Chunk.java:593)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.World.setTileEntity(World.java:1101)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.ItemStack.placeItem(ItemStack.java:262)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:506)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1378)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015)
[16:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938)
[16:55:15] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:55:15] [Server thread/ERROR]: POI data mismatch: never registered at BlockPosition{x=3, y=125, z=801}
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.Chunk.setTileEntity(Chunk.java:593)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.World.setTileEntity(World.java:1101)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.ItemStack.placeItem(ItemStack.java:262)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:506)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1378)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015)
[16:55:16] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938)
[16:55:16] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:55:16] [Server thread/ERROR]: POI data mismatch: never registered at BlockPosition{x=3, y=125, z=801}
```

Skript ver: 2.4.1
Server ver: 1.15.2

This is why I use Skript 2.4.1: #2908

**Comment by bonjourkemal** [comment]
It was also valid for Skript 2.5-alpha3

**Comment by Wealthyturtle** [comment]
The code above is invalid and doesn't parse. But your original code
```
on place:
	event-block is chest
	delete event-block
```
Is valid, and causes Minecraft to throw an error due to the player attempting to place a TileEntity when there is no TileEntity to be placed because the script deleted the event-block entirely.

A workaround for this (which you should have done before), is just to simply cancel the event, as per
```
on place:
	event-block is chest
	cancel event
```

**Comment by bonjourkemal** [comment]
What I want is the deletion of the chest that was placed.

**Comment by Wealthyturtle** [comment]
> What I want is the deletion of the chest that was placed.

As I mentioned above, ``cancel event`` will achieve that effect.

**Comment by bonjourkemal** [comment]
There is something I forgot to write. I fixed it. Sorry.
