### ISSUE TITLE
config.sk, line 188: databases error

### ISSUE THREAD

**Issue by SzlugPL** [SkriptLang/Skript#2933]
[spoiler] [02:51:57] [Server thread/WARN]: [Skript] No scripts were found, maybe you should write some ;) (config.sk, line 188: databases:')
[02:51:57] [Server thread/INFO]: [Skript] Finished loading.
[02:51:57] [Craft Scheduler Thread - 367/INFO]: [Vault] Checking for Updates ...
[02:51:57] [Craft Scheduler Thread - 367/INFO]: [Vault] No new version available
[02:52:19] [Thread-41/ERROR]: [Skript] Checking for updates failed. Do you have Internet connection? (config.sk, line 188: databases:')
[02:52:19] [Thread-41/WARN]: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.net.ConnectException: Connection timed out
[02:52:19] [Thread-41/WARN]: at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
[02:52:19] [Thread-41/WARN]: at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
[02:52:19] [Thread-41/WARN]: at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
[02:52:19] [Thread-41/WARN]: at java.base/java.lang.Thread.run(Thread.java:830)
[02:52:19] [Thread-41/WARN]: Caused by: java.lang.RuntimeException: java.net.ConnectException: Connection timed out
[02:52:19] [Thread-41/WARN]: at ch.njol.skript.update.GithubChecker.lambda$0(GithubChecker.java:115)
[02:52:19] [Thread-41/WARN]: at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1771)
[02:52:19] [Thread-41/WARN]: ... 1 more
[02:52:19] [Thread-41/WARN]: Caused by: java.net.ConnectException: Connection timed out
[02:52:19] [Thread-41/WARN]: at java.base/sun.nio.ch.Net.connect0(Native Method)
[02:52:19] [Thread-41/WARN]: at java.base/sun.nio.ch.Net.connect(Net.java:493)
[02:52:19] [Thread-41/WARN]: at java.base/sun.nio.ch.Net.connect(Net.java:482)
[02:52:19] [Thread-41/WARN]: at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[02:52:19] [Thread-41/WARN]: at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:339)
[02:52:19] [Thread-41/WARN]: at java.base/java.net.Socket.connect(Socket.java:585)
[02:52:19] [Thread-41/WARN]: at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290)
[02:52:19] [Thread-41/WARN]: at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[02:52:19] [Thread-41/WARN]: at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[02:52:19] [Thread-41/WARN]: at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
[02:52:19] [Thread-41/WARN]: at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
[02:52:19] [Thread-41/WARN]: at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[02:52:19] [Thread-41/WARN]: at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
[02:52:19] [Thread-41/WARN]: at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:177)
[02:52:19] [Thread-41/WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
[02:52:19] [Thread-41/WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
[02:52:19] [Thread-41/WARN]: at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:163)
[02:52:19] [Thread-41/WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
[02:52:19] [Thread-41/WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
[02:52:19] [Thread-41/WARN]: at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[02:52:19] [Thread-41/WARN]: at java.base/java.net.URL.openStream(URL.java:1152)
[02:52:19] [Thread-41/WARN]: at ch.njol.skript.update.GithubChecker.lambda$0(GithubChecker.java:109)
[02:52:19] [Thread-41/WARN]: ... 2 more [/spoiler] 
how to fix it?

**Comment by ShaneBeee** [comment]
No substantial information here, also you deleted the template, so we have no information what so ever.
