### ISSUE TITLE
Skript error

### ISSUE THREAD

**Issue by rooyrooy** [SkriptLang/Skript#2934]
Description
i got this error in the console.

it is caused by this skript

1. every 0.5 second:
2.     loop all players:
3.         wipe loop-player's sidebar
4.         set name of sidebar of loop-player to "&8» &c&lParkourserver &8«"
5.         set score "&6--------------------" in sidebar of loop-player to 13
6.         set score "&7%now%" in sidebar of loop-player to 12
7.         set score "&6Parkour:%{%region at loop-player%}%" in sidebar of loop-player to 11
8.         set score "&1" in sidebar of loop-player to 10
9.         set score "&cName:&r%loop-player%" in sidebar of loop-player to 9
10.         set score "&6TAG:&b<%{tag.%loop-player%}%&b>" in sidebar of loop-player to 8
11.         set score "&eRank:&f<%{rank.%loop-player%}%&f>" in sidebar of loop-player to 7
12.         set score "&aJump:&e<%{jump.%loop-player%}%>" in sidebar of loop-player to 6
13.         set score "&bPlaytimes:&8<&c%{playtimehour.%loop-player%}% hour&8>" in sidebar of loop-player to 5
14.         set score "&6Money:%{money.%loop-player%}% yen" in sidebar of loop-player to 4
15.         set score "" in sidebar of loop-player to 3
16.         set score "&7/server-link" in sidebar of loop-player to 2
17.         set score "&6--------------------" in sidebar of loop-player to 1
18.         

error LOG
[19:20:11] [Server thread/ERROR]: #!#! 
[19:20:11] [Server thread/ERROR]: #!#! 
[19:20:11] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[19:20:11] [Server thread/ERROR]: #!#! 
[19:20:11] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[19:20:11] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[19:20:11] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[19:20:11] [Server thread/ERROR]: #!#! Here is full list of them:
[19:20:11] [Server thread/ERROR]: #!#! skRayFall (http://sk.rayfall.net/) skDragon SkQuery 
[19:20:11] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[19:20:11] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[19:20:11] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[19:20:11] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[19:20:11] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[19:20:11] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[19:20:11] [Server thread/ERROR]: #!#! 
[19:20:11] [Server thread/ERROR]: #!#! Stack trace:
[19:20:11] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: Entry cannot be longer than 40 characters!
[19:20:11] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftObjective.getScore(CraftObjective.java:96)
[19:20:11] [Server thread/ERROR]: #!#!     at net.rayfall.eyesniper2.skrayfall.scoreboard.EffSetScore.execute(EffSetScore.java:46)
[19:20:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[19:20:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[19:20:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[19:20:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[19:20:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:96)
[19:20:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:110)
[19:20:11] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[19:20:11] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[19:20:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[19:20:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[19:20:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[19:20:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[19:20:11] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[19:20:11] [Server thread/ERROR]: #!#! 
[19:20:11] [Server thread/ERROR]: #!#! Version Information:
[19:20:11] [Server thread/ERROR]: #!#!   Skript: 2.4.1 (latest)
[19:20:11] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[19:20:11] [Server thread/ERROR]: #!#!     Date: 2019-12-22
[19:20:11] [Server thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[19:20:11] [Server thread/ERROR]: #!#!   Minecraft: 1.12.2
[19:20:11] [Server thread/ERROR]: #!#!   Java: 1.8.0_221 (Java HotSpot(TM) 64-Bit Server VM 25.221-b11)
[19:20:11] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[19:20:11] [Server thread/ERROR]: #!#! 
[19:20:11] [Server thread/ERROR]: #!#! Server platform: Paper
[19:20:11] [Server thread/ERROR]: #!#! 
[19:20:11] [Server thread/ERROR]: #!#! Current node: null
[19:20:11] [Server thread/ERROR]: #!#! Current item: null
[19:20:11] [Server thread/ERROR]: #!#! Current trigger: every 0.5 second (every 0.5 seconds) (scoreboard.sk, line 1)
[19:20:11] [Server thread/ERROR]: #!#! 
[19:20:11] [Server thread/ERROR]: #!#! Thread: Server thread
[19:20:11] [Server thread/ERROR]: #!#! 
[19:20:11] [Server thread/ERROR]: #!#! Language: english
[19:20:11] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[19:20:11] [Server thread/ERROR]: #!#! 
[19:20:11] [Server thread/ERROR]: #!#! End of Error.
[19:20:11] [Server thread/ERROR]: #!#! 

Information

Skript version: 2.4.1
SkQuery-4.1.2
skRayFall+v1.9.12
skDragon

**Comment by ShaneBeee** [comment]
This error has nothing to do with Skript, its an error from skRayFall in regards to your scoreboard value being too long.
