### ISSUE TITLE
Error when trying to calculate percentage

### ISSUE THREAD

**Issue by CyberedCake** [SkriptLang/Skript#2940]
(First time writing here)

Code:
```
                set {total.players.%player%} to 0
                loop all players:
                    add 1 to {total.players.%player%}
                set {level.point.%sender%} to {xp.%sender%} / {xp.total.%sender%}
                set {level.point.%sender%} to {level.point.%sender%} * 100
                set {level.next.%sender%} to {level.%player%} + 1
                wipe player's sidebar
                set name of sidebar of player to "&ecybercake.zapto.org &6[1.8.8]"
                set score "&a&l" in sidebar of player to 8
                set score "&a&lServer: &f%player's world%" in sidebar of player to 7
                set score "&a&lTotal Players: &f%{total.players.%player%}%" in sidebar of player to 6
                if {pre.%sender%} is "&7":
                    set score "&a&lRank: &7[DEFAULT]" in sidebar of player to 5
                else:
                    set score "&a&lRank: &f%{pre.%sender%}%" in sidebar of player to 5
                set score "&a&lLevel: &f%{level.%sender%}% &3(%{xp.%sender%}%&3/%{xp.total.%sender%}%&3)" in sidebar of player to 4
                set score "&f &f &f &f &e(%{level.point.%sender%}%%% &eto &3Level %{level.next.%sender%}%&e)" in sidebar of player to 3
                set score "&a&lGold: &f%{gold.%sender%}%" in sidebar of player to 2
                set score "&a" in sidebar of player to 1
                wait 10 ticks
                set {yw.players.%player%} to 0
                stop
```

The Error:
```
[13:07:43] [Server thread/ERROR]: #!#! 
[13:07:43] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[13:07:43] [Server thread/ERROR]: #!#! 
[13:07:43] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[13:07:43] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[13:07:43] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[13:07:43] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[13:07:43] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[13:07:43] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[13:07:43] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[13:07:43] [Server thread/ERROR]: #!#! 
[13:07:43] [Server thread/ERROR]: #!#! Stack trace:
[13:07:43] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: Entry cannot be longer than 40 characters!
[13:07:43] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scoreboard.CraftObjective.getScore(CraftObjective.java:96)
[13:07:43] [Server thread/ERROR]: #!#!     at net.rayfall.eyesniper2.skrayfall.scoreboard.EffSetScore.execute(EffSetScore.java:63)
[13:07:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[13:07:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[13:07:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[13:07:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[13:07:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
[13:07:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
[13:07:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
[13:07:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
[13:07:43] [Server thread/ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)
[13:07:43] [Server thread/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:07:43] [Server thread/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[13:07:43] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[13:07:43] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:07:43] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[13:07:43] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[13:07:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.dispatchCommand(Skript.java:1078)
[13:07:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:86)
[13:07:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[13:07:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[13:07:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[13:07:43] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:84)
[13:07:43] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[13:07:43] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[13:07:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[13:07:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[13:07:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[13:07:43] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[13:07:43] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[13:07:43] [Server thread/ERROR]: #!#! 
[13:07:43] [Server thread/ERROR]: #!#! Version Information:
[13:07:43] [Server thread/ERROR]: #!#!   Skript: 2.2-dev25
[13:07:43] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[13:07:43] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[13:07:43] [Server thread/ERROR]: #!#!   Java: 1.8.0_251 (Java HotSpot(TM) 64-Bit Server VM 25.251-b08)
[13:07:43] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:07:43] [Server thread/ERROR]: #!#! 
[13:07:43] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[13:07:43] [Server thread/ERROR]: #!#! 
[13:07:43] [Server thread/ERROR]: #!#! Current node: null
[13:07:43] [Server thread/ERROR]: #!#! Current item: null
[13:07:43] [Server thread/ERROR]: #!#! 
[13:07:43] [Server thread/ERROR]: #!#! Thread: Server thread
[13:07:43] [Server thread/ERROR]: #!#! 
[13:07:43] [Server thread/ERROR]: #!#! End of Error.
[13:07:43] [Server thread/ERROR]: #!#! 
```

I believe the issue is these two lines: 
```
                set {level.point.%sender%} to {xp.%sender%} / {xp.total.%sender%}
                set {level.point.%sender%} to {level.point.%sender%} * 100
```

Variables:
{xp.%sender%} is the amount of xp the player has based on a forumla in another script
{xp.total.%sender%} is the amount of xp the player needs to level up, which is also in another script
{level.%sender%} is the current level of the player

**Comment by Matocolotoe** [comment]
Skript doesn't support 1.8
If you really need the recent versions, you can use this : https://github.com/Matocolotoe/Skript-1.8

**Comment by TheBentoBox** [comment]
Many issues here:
1. Your formatting was messed up, you must use three tick marks on SEPARATE lines above and below your code when pasting in multiple lines of code for it to format properly, like this:
\`\`\`
code
\`\`\`
2. Don't delete the issue report template. We need the info that it asks you to fill in.
3. You're using 1.8, which we don't support.
4. You're using an old version of Skript. We only accept bugs logged against the latest release.
5. The error is written right there for you: "Entry cannot be longer than 40 characters!". You're adding a scoreboard entry that is longer than 40 characters, which the game doesn't allow.
