### ISSUE TITLE
Skript severe Error

### ISSUE THREAD

**Issue by IceGameGG** [SkriptLang/Skript#2973]
Hello, When i start my server and load just on script, it took this error 
```
[09:08:52] [Server thread/ERROR]: #!#! 
[09:08:52] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[09:08:52] [Server thread/ERROR]: #!#! Could not load Ankaria.sk
[09:08:52] [Server thread/ERROR]: #!#! 
[09:08:52] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[09:08:52] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[09:08:52] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[09:08:52] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[09:08:52] [Server thread/ERROR]: #!#! 
[09:08:52] [Server thread/ERROR]: #!#! Stack trace:
[09:08:52] [Server thread/ERROR]: #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:241)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfos(Classes.java:246)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:415)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:450)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:365)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:641)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:828)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1569)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1565)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1006)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:490)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:651)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:409)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:428)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:347)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:380)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:917)
[09:08:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:156)
[09:08:52] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[09:08:52] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[09:08:52] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[09:08:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350)
[09:08:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185)
[09:08:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[09:08:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[09:08:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[09:08:52] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[09:08:52] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09:08:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[09:08:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
[09:08:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[09:08:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[09:08:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[09:08:52] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[09:08:52] [Server thread/ERROR]: #!#! 
[09:08:52] [Server thread/ERROR]: #!#! Version Information:
[09:08:52] [Server thread/ERROR]: #!#!   Skript: 2.4.1 (latest)
[09:08:52] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[09:08:52] [Server thread/ERROR]: #!#!     Date: 2019-12-22
[09:08:52] [Server thread/ERROR]: #!#!   Bukkit: 1.9-R0.1-SNAPSHOT
[09:08:52] [Server thread/ERROR]: #!#!   Minecraft: 1.9
[09:08:52] [Server thread/ERROR]: #!#!   Java: 1.8.0_202 (Java HotSpot(TM) 64-Bit Server VM 25.202-b08)
[09:08:52] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.9.0-12-amd64
[09:08:52] [Server thread/ERROR]: #!#! 
[09:08:52] [Server thread/ERROR]: #!#! Server platform: Spigot
[09:08:52] [Server thread/ERROR]: #!#! 
[09:08:52] [Server thread/ERROR]: #!#! Current node: set {warp.class} to location of player (Ankaria.sk, line 11)
[09:08:52] [Server thread/ERROR]: #!#! Current item: null
[09:08:52] [Server thread/ERROR]: #!#! 
[09:08:52] [Server thread/ERROR]: #!#! Thread: Server thread
[09:08:52] [Server thread/ERROR]: #!#! 
[09:08:52] [Server thread/ERROR]: #!#! Language: english
[09:08:52] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[09:08:52] [Server thread/ERROR]: #!#! 
[09:08:52] [Server thread/ERROR]: #!#! End of Error.
[09:08:52] [Server thread/ERROR]: #!#! 
``

**Comment by ShaneBeee** [comment]
1) When creating issues, please fill out the template provided rather than deleting it, to help us better triage your issue.
2) 1.9 is not supported by our team. We only support the latest minor release of every major release since 1.9, that means 1.9.4, 1.10.2, 1.11.2, 1.12.2, 1.13.2, 1.14.4 and 1.15.2... 1.9 is not supported.
