### ISSUE TITLE
 [Skript] Severe Error:

### ISSUE THREAD

**Issue by HaYRog** [SkriptLang/Skript#2980]
ERROR

### Description
Fr : J'ai pris un skript sur internet et j'ai cette erreur quand je fais une certaine commande .
En (google translate) : 
I took a skript on the internet and I get this error when I make a certain command

### Steps to Reproduce
Command

### Errors / Screenshots
[13:24:42 INFO]: HayRog issued server command: /bwadm setnpc
[13:24:42 INFO]: HayRog [3eb562b5-f01c-39cd-9952-8d14bf3c79ba]: /bwadm setnpc
[13:24:42 ERROR]: #!#!
[13:24:42 ERROR]: #!#! [Skript] Severe Error:
[13:24:42 ERROR]: #!#!
[13:24:42 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[13:24:42 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[13:24:42 ERROR]: #!#! and check whether this error has already been reported.
[13:24:42 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[13:24:42 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[13:24:42 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[13:24:42 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[13:24:42 ERROR]: #!#!
[13:24:42 ERROR]: #!#! Stack trace:
[13:24:42 ERROR]: #!#! java.lang.IllegalStateException: No API implementation set. Is Holographic Displays enabled?
[13:24:42 ERROR]: #!#!     at com.gmail.filoghost.holographicdisplays.api.internal.BackendAPI.getImplementation(BackendAPI.java:36)
[13:24:42 ERROR]: #!#!     at com.gmail.filoghost.holographicdisplays.api.HologramsAPI.createHologram(HologramsAPI.java:46)
[13:24:42 ERROR]: #!#!     at net.rayfall.eyesniper2.skrayfall.holograms.EffCreateStaticHoloObject.execute(EffCreateStaticHoloObject.java:50)
[13:24:42 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[13:24:42 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[13:24:42 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[13:24:42 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[13:24:42 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
[13:24:42 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
[13:24:42 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
[13:24:42 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
[13:24:42 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:24:42 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:24:42 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:24:42 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[13:24:42 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
[13:24:42 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:24:42 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[13:24:42 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[13:24:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1107)
[13:24:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[13:24:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[13:24:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[13:24:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[13:24:42 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[13:24:42 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[13:24:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
[13:24:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[13:24:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[13:24:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[13:24:42 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[13:24:42 ERROR]: #!#!
[13:24:42 ERROR]: #!#! Version Information:
[13:24:42 ERROR]: #!#!   Skript: 2.2-dev25
[13:24:42 ERROR]: #!#!   Bukkit: 1.8-R0.1-SNAPSHOT
[13:24:42 ERROR]: #!#!   Minecraft: 1.8
[13:24:42 ERROR]: #!#!   Java: 1.8.0_251 (Java HotSpot(TM) 64-Bit Server VM 25.251-b08)
[13:24:42 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:24:42 ERROR]: #!#!
[13:24:42 ERROR]: #!#! Running CraftBukkit: false
[13:24:42 ERROR]: #!#!
[13:24:42 ERROR]: #!#! Current node: null
[13:24:42 ERROR]: #!#! Current item: null
[13:24:42 ERROR]: #!#!
[13:24:42 ERROR]: #!#! Thread: Server thread
[13:24:42 ERROR]: #!#!
[13:24:42 ERROR]: #!#! End of Error.
[13:24:42 ERROR]: #!#!

### Server Information
* **Server version/platform: 1.8 Viaversion
* **Skript version:2.2

**Comment by ShaneBeee** [comment]
Non supported version.
