### ISSUE TITLE
Issue with a script

### ISSUE THREAD

**Issue by Ch4rryBomB** [SkriptLang/Skript#2986]
I' very inexperienced when it comes to coding and I would Appreciate it a ton if I could get some help. Also if I'm doing anything wrong via posting a thread please tell me the correct method of doing so. Thanks for all the help :) 

Problem:
So I installed a quiet lengthy minecraft script called RevEnchantments for 1.8. Due to the lengthy-ness of the script I had to download multiple other plugins for skript to help run and configure it (so I dont even know where to begin. MY MAIN PROBLEM is that when i try and do a command it just says "unknown command" and i dont know how to fix it.

When i do /sk reload RevEnchantments this appear in console :
[00:50:58 ERROR]: #!#!
[00:50:58 ERROR]: #!#! [Skript] Severe Error:
[00:50:58 ERROR]: #!#! Could not load RevEnchantments.sk
[00:50:58 ERROR]: #!#!
[00:50:58 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[00:50:58 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[00:50:58 ERROR]: #!#! and check whether this error has already been reported.
[00:50:58 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[00:50:58 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[00:50:58 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[00:50:58 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[00:50:58 ERROR]: #!#!
[00:50:58 ERROR]: #!#! Stack trace:
[00:50:58 ERROR]: #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
[00:50:58 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:240)
[00:50:58 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:335)
[00:50:58 ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadSignature(Functions.java:172)
[00:50:58 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadStructure(ScriptLoader.java:555)
[00:50:58 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:186)
[00:50:58 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:50:58 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:50:58 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[00:50:58 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[00:50:58 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[00:50:58 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[00:50:58 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[00:50:58 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[00:50:58 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[00:50:58 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[00:50:58 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
[00:50:58 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[00:50:58 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[00:50:58 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[00:50:58 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[00:50:58 ERROR]: #!#!
[00:50:58 ERROR]: #!#! Version Information:
[00:50:58 ERROR]: #!#!   Skript: 2.2-dev29
[00:50:58 ERROR]: #!#!   Bukkit: 1.8-R0.1-SNAPSHOT
[00:50:58 ERROR]: #!#!   Minecraft: 1.8
[00:50:58 ERROR]: #!#!   Java: 1.8.0_231 (Java HotSpot(TM) Client VM 25.231-b11)
[00:50:58 ERROR]: #!#!   OS: Windows 10 x86 10.0
[00:50:58 ERROR]: #!#!
[00:50:58 ERROR]: #!#! Running CraftBukkit: false
[00:50:58 ERROR]: #!#!
[00:50:58 ERROR]: #!#! Current node: function revreload(i: number): (RevEnchantments.sk, line 8)
[00:50:58 ERROR]: #!#! Current item: null
[00:50:58 ERROR]: #!#!
[00:50:58 ERROR]: #!#! Thread: Server thread
[00:50:58 ERROR]: #!#!
[00:50:58 ERROR]: #!#! End of Error.

**Comment by ShaneBeee** [comment]
The version of Skript you are using is extremely outdated and no longer supported.
Also your server version is not supported by us, we only support 1.9.4+
