### ISSUE TITLE
[BUG] use skDargon particle have null bug

### ISSUE THREAD

**Issue by Command1264** [SkriptLang/Skript#3005]
### Description
null bug

### Steps to Reproduce
1.
write in .sk:

on damage:
	attacker is player
	draw 70 blockcrack particle made of redstone block at location of player, speed 1, offset 0.25, 0.5, 0.25, visibleTo attacker, visibleRange 20
2.
reload .sk
3.
attack any entity
4.
see error
### Expected Behavior
have redstone block particle

### Errors / Screenshots
[16:10:24] [Server thread/ERROR]: #!#!
[16:10:24] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[16:10:24] [Server thread/ERROR]: #!#!
[16:10:24] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[16:10:24] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:10:24] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[16:10:24] [Server thread/ERROR]: #!#! Here is full list of them:
[16:10:24] [Server thread/ERROR]: #!#! skRayFall v1.9.20 (https://sk.rayfall.net/) skript-mirror v2.0.0-SNAPSHOT (https://github.com/btk5h/skript-mirror) TuSKe v1.8.2-Pikachu-Patch-3 (github.com/Tuke-Nuke/TuSKe) ItemsAdder v2.0.24 (matteodev.it) skDragon v0.16 SkBee v1.3.3 skript-yaml v1.2.5 SkQuery v3.6.5 Ersatz v1.0 Skellett v1.9.8 (https://forums.skunity.com/resources/skellett.24/) Skent v1.10
[16:10:24] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[16:10:24] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[16:10:24] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[16:10:24] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[16:10:24] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[16:10:24] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[16:10:24] [Server thread/ERROR]: #!#!
[16:10:24] [Server thread/ERROR]: #!#! Stack trace:
[16:10:24] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: UnparsedLiterals must be converted before use
[16:10:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.invalidAccessException(UnparsedLiteral.java:273)
[16:10:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getAll(UnparsedLiteral.java:283)
[16:10:24] [Server thread/ERROR]: #!#!     at ud.skript.sashie.skDragon.particleEngine.effects.spawns.EffSpawnParticleMaterial.execute(EffSpawnParticleMaterial.java:113)
[16:10:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[16:10:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[16:10:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[16:10:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[16:10:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:156)
[16:10:24] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:114)
[16:10:24] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:10:24] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[16:10:24] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[16:10:24] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:238)
[16:10:24] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:931)
[16:10:24] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:818)
[16:10:24] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:774)
[16:10:24] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:963)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1624)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1028)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(SourceFile:69)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:300)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1085)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1547)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1879)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:68)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:13)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895)
[16:10:24] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
[16:10:24] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[16:10:24] [Server thread/ERROR]: #!#!
[16:10:24] [Server thread/ERROR]: #!#! Version Information:
[16:10:24] [Server thread/ERROR]: #!#!   Skript: 2.5-alpha3 (latest)
[16:10:24] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[16:10:24] [Server thread/ERROR]: #!#!     Date: 2020-03-28
[16:10:24] [Server thread/ERROR]: #!#!   Bukkit: 1.15.2-R0.1-SNAPSHOT
[16:10:24] [Server thread/ERROR]: #!#!   Minecraft: 1.15.2
[16:10:24] [Server thread/ERROR]: #!#!   Java: 1.8.0_251 (Java HotSpot(TM) 64-Bit Server VM 25.251-b08)
[16:10:24] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[16:10:24] [Server thread/ERROR]: #!#!
[16:10:24] [Server thread/ERROR]: #!#! Server platform: Spigot
[16:10:24] [Server thread/ERROR]: #!#!
[16:10:24] [Server thread/ERROR]: #!#! Current node: null
[16:10:24] [Server thread/ERROR]: #!#! Current item: Material Based Particles
[16:10:24] [Server thread/ERROR]: #!#! Current trigger: damage (damage) (噴血系統.sk, line 21)
[16:10:24] [Server thread/ERROR]: #!#!
[16:10:24] [Server thread/ERROR]: #!#! Thread: Server thread
[16:10:24] [Server thread/ERROR]: #!#!
[16:10:24] [Server thread/ERROR]: #!#! Language: english
[16:10:24] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[16:10:24] [Server thread/ERROR]: #!#!
[16:10:24] [Server thread/ERROR]: #!#! End of Error.
[16:10:24] [Server thread/ERROR]: #!#!

### Server Information
* **Server version/platform:**       Spigot 1.15.2
* **Skript version:**                Skript: 2.5-alpha3

**Comment by Wealthyturtle** [comment]
Please do not report Skript addon bugs here, report them to their respective repos.
