### ISSUE TITLE
The errors while startup the server

### ISSUE THREAD

**Issue by AhmedFathey2008** [SkriptLang/Skript#3010]
Hello
when i startup my server it show some errors
server version: 1.15.2
server type: spigot 1.15.2
skript version: 2.4.1
errors:
[23:24:23 INFO]: [Skript] Enabling Skript v2.4.1
[23:24:26 INFO]: [Skript] Successfully generated the config and the example scripts.
[23:24:36 INFO]: [Skript] You're currently running the latest stable version of Skript.
[23:24:47 ERROR]: Error occurred while enabling Skript v2.4.1 (Is it up to date?)
java.lang.StackOverflowError: null
	at java.lang.Character.codePointAt(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]

...
so can you tell me how to fix that?
Thank you.

**Comment by bc-365** [comment]
I have been having the same problem for months. [https://pastebin.com/Skz2QXhV](url)

**Comment by FranKusmiruk** [comment]
Can you upgrade Java to at least 11 and see if that fixes the issue?

**Comment by Wealthyturtle** [comment]
Duplicate #2752... this is a issue that has been reported before, try and upgrade your Java to 64bit, it might help.

**Comment by AhmedFathey2008** [comment]
ok thanks guys
