### ISSUE TITLE
Something, something, i don't know

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#3036]
This happened. I don't know what it's related to, nothing seems broken (i was shutting down the server anyway). Was able to grab a quick screenshot before the log would be lost.

### Errors / Screenshots
https://i.gyazo.com/5fc6ad6945b95769660f178fa8bf824c.png

### Server Information
* **Server version/platform:**       paper-322 (1_15_R1)
* **Skript version:**                2.5-alpha3

Plugins: skript-mirror
Loaded scripts: Just some small custom commands i use as worldedit aliases

**Comment by Govindass** [comment]
just got this too!
```
 [14:31:34 WARN]: Exception in thread "Skript offline player resolver thread (fetches UUIDs from the minecraft servers)" java.lang.NoClassDefFoundError: Could not initialize class ch.njol.skript.bukkitutil.UnresolvedOfflinePlayer
[14:31:34 WARN]: at ch.njol.skript.bukkitutil.UnresolvedOfflinePlayer$1.run(UnresolvedOfflinePlayer.java:58)
[14:31:34 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
```
I never get this usually, what I did different today than other days is that I deleted a lot of variables that contain player skulls in them, so that's a way to reproduce it I guess

**Comment by Govindass** [comment]
these skulls I deleted seems to have been player name-based skulls and not UUID based, so they were doing requests to mojang servers every startup for each variable with the skull, slowing down my server's startup by a lot
