### ISSUE TITLE
Big error Script

### ISSUE THREAD

**Issue by Tweitzyt** [SkriptLang/Skript#3037]
Hello !

When i start my server, i have this error for all of my scripts ! Someone have an idea ? Thanks !

[21:43:03 ERROR]: #!#! [Skript] Severe Error:
[21:43:03 ERROR]: #!#! Could not load warp.sk
[21:43:03 ERROR]: #!#! 
[21:43:03 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[21:43:03 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[21:43:03 ERROR]: #!#! and check whether this error has already been reported.
[21:43:03 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[21:43:03 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[21:43:03 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[21:43:03 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[21:43:03 ERROR]: #!#! 
[21:43:03 ERROR]: #!#! Stack trace:
[21:43:03 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for particle
[21:43:03 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:262)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1417)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1138)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:319)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:445)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1159)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1111)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:753)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:465)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:469)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:245)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:199)
[21:43:03 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:405)
[21:43:03 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[21:43:03 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[21:43:03 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[21:43:03 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[21:43:03 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[21:43:03 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[21:43:03 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[21:43:03 ERROR]: #!#! 
[21:43:03 ERROR]: #!#! Version Information:
[21:43:03 ERROR]: #!#!   Skript: 2.2-dev27
[21:43:03 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[21:43:03 ERROR]: #!#!   Minecraft: 1.8.8
[21:43:03 ERROR]: #!#!   Java: 1.8.0_252 (OpenJDK 64-Bit Server VM 25.252-b09)
[21:43:03 ERROR]: #!#!   OS: Linux amd64 4.19.0-8-amd64
[21:43:03 ERROR]: #!#! 
[21:43:03 ERROR]: #!#! Running CraftBukkit: false
[21:43:03 ERROR]: #!#! 
[21:43:03 ERROR]: #!#! Current node: wait 3 tick (warp.sk, line 3)
[21:43:03 ERROR]: #!#! Current item: null
[21:43:03 ERROR]: #!#! 
[21:43:03 ERROR]: #!#! Thread: Server thread
[21:43:03 ERROR]: #!#! 
[21:43:03 ERROR]: #!#! End of Error.
[21:43:03 ERROR]: #!#!

**Comment by ShaneBeee** [comment]
Neither 1.8.x nor Skript 2.2 is supported.

If you can replicate the issue on a server version that is supported, and a more recent version of Skript, we can look at the issue then.
