### ISSUE TITLE
on fishing event has bug

### ISSUE THREAD

**Issue by jihun-kor** [SkriptLang/Skript#3039]
### Description

on fishing event has bug
### Steps to Reproduce

on fishing:
	set {_loc} to location of fishing hook
	set yaw of {_loc} to player's yaw
	set pitch of {_loc} to player's pitch
	teleport player to {_loc}

### Errors / Screenshots

[21:49:55 ERROR]: Could not pass event PlayerFishEvent to Skript v2.5-alpha3
java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerFishEvent.getHook()Lorg/bukkit/entity/FishHook;
        at com.gmail.thelimeglass.Expressions.ExprFishingGetHook.get(ExprFishingGetHook.java:46) ~[Skellett-Legacy.jar:?]
        at com.gmail.thelimeglass.Expressions.ExprFishingGetHook.get(ExprFishingGetHook.java:22) ~[Skellett-Legacy.jar:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[Skript.jar:?]
        at ch.njol.skript.lang.util.ConvertedExpression.getArray(ConvertedExpression.java:168) ~[Skript.jar:?]
        at ch.njol.skript.expressions.base.WrapperExpression.get(WrapperExpression.java:93) ~[Skript.jar:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[Skript.jar:?]
        at ch.njol.skript.effects.EffChange.execute(EffChange.java:278) ~[Skript.jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[Skript.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[Skript.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[Skript.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:57) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:156) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:114) ~[Skript.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.ItemFishingRod.a(ItemFishingRod.java:42) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.ItemStack.a(ItemStack.java:293) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:403) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1006) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_241]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[21:49:55 ERROR]: Could not pass event PlayerFishEvent to Skript v2.5-alpha3
java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerFishEvent.getHook()Lorg/bukkit/entity/FishHook;
        at com.gmail.thelimeglass.Expressions.ExprFishingGetHook.get(ExprFishingGetHook.java:46) ~[Skellett-Legacy.jar:?]
        at com.gmail.thelimeglass.Expressions.ExprFishingGetHook.get(ExprFishingGetHook.java:22) ~[Skellett-Legacy.jar:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[Skript.jar:?]
        at ch.njol.skript.lang.util.ConvertedExpression.getArray(ConvertedExpression.java:168) ~[Skript.jar:?]
        at ch.njol.skript.expressions.base.WrapperExpression.get(WrapperExpression.java:93) ~[Skript.jar:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[Skript.jar:?]
        at ch.njol.skript.effects.EffChange.execute(EffChange.java:278) ~[Skript.jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[Skript.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[Skript.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[Skript.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:57) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:156) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:114) ~[Skript.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.EntityFishingHook.j(EntityFishingHook.java:472) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.ItemFishingRod.a(ItemFishingRod.java:19) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.ItemStack.a(ItemStack.java:293) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:403) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1006) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_241]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

### Server Information
* **Server version/platform:**1.12.2(spigot)       
* **Skript version:**2.5 alpha3

**Comment by Runakai1** [comment]
That's not the event but rather the expressions from skellett. Also please post your stack trace on pastepin or similar
