### ISSUE TITLE
SkillAPI not found, prevents scripts from loading

### ISSUE THREAD

**Issue by Govindass** [SkriptLang/Skript#3051]
### Description
worked earlier on the same skript version, now something appears..
```
[13:55:42] [Server thread/WARN]: [Skript] Task #38 for Skript v2.5-alpha3 generated an exception
java.lang.NoClassDefFoundError: com/sucy/skill/SkillAPI
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[?:?]
	at java.lang.Class.privateGetPublicMethods(Class.java:3191) ~[?:?]
	at java.lang.Class.getMethods(Class.java:1904) ~[?:?]
	at com.btk5h.skriptmirror.util.JavaUtil.methods(JavaUtil.java:53) ~[?:?]
	at com.btk5h.skriptmirror.skript.reflect.ExprJavaCall.createCallSite(ExprJavaCall.java:386) ~[?:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1133) ~[?:?]
	at com.btk5h.skriptmirror.skript.reflect.ExprJavaCall.getCallSite(ExprJavaCall.java:346) ~[?:?]
	at com.btk5h.skriptmirror.skript.reflect.ExprJavaCall.findCompatibleMethod(ExprJavaCall.java:524) ~[?:?]
	at com.btk5h.skriptmirror.skript.reflect.ExprJavaCall.invoke(ExprJavaCall.java:435) ~[?:?]
	at com.btk5h.skriptmirror.skript.reflect.ExprJavaCall.getSingle(ExprJavaCall.java:137) ~[?:?]
	at com.btk5h.skriptmirror.skript.reflect.ExprJavaCall.getArray(ExprJavaCall.java:143) ~[?:?]
	at ch.njol.skript.effects.EffChange.execute(EffChange.java:278) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:57) ~[?:?]
	at ch.njol.skript.events.EvtScript.register(EvtScript.java:61) ~[?:?]
	at ch.njol.skript.ScriptLoader$3.call(ScriptLoader.java:753) ~[?:?]
	at ch.njol.skript.ScriptLoader$3.call(ScriptLoader.java:1) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:772) ~[?:?]
	at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:410) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:429) ~[?:?]
	at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:348) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:381) ~[?:?]
	at ch.njol.skript.Skript$2.run(Skript.java:592) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[server.jar:git-Paper-33d42c8e]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[server.jar:git-Paper-33d42c8e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:852) ~[server.jar:git-Paper-33d42c8e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[server.jar:git-Paper-33d42c8e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:786) ~[server.jar:git-Paper-33d42c8e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:678) ~[server.jar:git-Paper-33d42c8e]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sucy.skill.SkillAPI
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[server.jar:git-Paper-33d42c8e]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[server.jar:git-Paper-33d42c8e]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 33 more
```

### Steps to Reproduce
no idea.
### Expected Behavior
to just startup normally?
### Errors / Screenshots
included above

### Server Information
* **Server version/platform:**       1.12.2 paper
* **Skript version:**                2.5 alpha3

**Comment by Runakai1** [comment]
Do you have any addons/scripts? That never occurred to me

**Comment by Govindass** [comment]
> 
> 
> Do you have any addons/scripts? That never occurred to me

I definitely have many, but it never occurred to me until today, it's a complete mystery, I can't find any SkillAPI relations in my plugins / addons

**Comment by Runakai1** [comment]
> > Do you have any addons/scripts? That never occurred to me
> 
> I definitely have many, but it never occurred to me until today, it's a complete mystery, I can't find any SkillAPI relations in my plugins / addons

Well, I guess use the same jar on a different server but without addons

**Comment by Govindass** [comment]
> 
> 
> > > Do you have any addons/scripts? That never occurred to me
> > 
> > 
> > I definitely have many, but it never occurred to me until today, it's a complete mystery, I can't find any SkillAPI relations in my plugins / addons
> 
> Well, I guess use the same jar on a different server but without addons

I used the same jar yesterday on the same server, it worked well, but since today it started

**Comment by Pikachu920** [comment]
it appears you have something trying to access `com.sucy.skill.SkillAPI` via skript-mirror, within a change effect. you could go to your scripts folder and run `grep -r SkillAPI` to find the offending script.

**Comment by Govindass** [comment]
> 
> 
> it appears you have something trying to access `com.sucy.skill.SkillAPI` via skript-mirror, within a change effect. you could go to your scripts folder and run `grep -r SkillAPI` to find the offending script.

that wasn't the issue, but TPGamesNL has helped me fix it now.
it was due to:
```
on script load:
set {_plugins::*} to ...Bukkit.getServer().getPluginManager().getPlugins()
```
super weird that it throwed such error, as I don't use SkillAPI, but yup seems like it was skript-mirror issue and not Skript

**Comment by Pikachu920** [comment]
if I had to guess it's because you are calling getPlugins on load which is before other plugins have finished loading, and all their classes have yet to be loaded

**Comment by Govindass** [comment]
> 
> 
> if I had to guess it's because you are calling getPlugins on load which is before other plugins have finished loading, and all their classes have yet to be loaded

but don't Skript load after other plugins hm.. or do I have to add like wait 1sec delay in "on script load"?
