### ISSUE TITLE
Errors upon startup

### ISSUE THREAD

**Issue by CzechFrog** [SkriptLang/Skript#3053]
### Description
I start my server and Skript loads fine, it's just spamming me with errors about a parser?

### Steps to Reproduce
Console output (where applicable) added below

### Errors / Screenshots
[18:51:36 ERROR]: [Skript] 73 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:253)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[18:52:02 ERROR]: [Skript] 2886 log handlers were not stopped properly! (at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:711)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

### Server Information
* **Server version/platform:**       Paper-350 MC: 1.15.2
* **Skript version:**                2.4.1

### Additional Context
It hangs up my server and reduces TPS for a while

**Comment by ShaneBeee** [comment]
This error is caused by using an outdated version of Skript-mirror, you will need to update to Skript-mirror 2.0.0
