### ISSUE TITLE
Idk what error is this

### ISSUE THREAD

**Issue by CalebKim0826** [SkriptLang/Skript#3054]
### Description
I was playing with my friends with some script and this happend

### Steps to Reproduce
I did it again and this error didn't happen

### Expected Behavior
I was using portminer. I hoped for a server that is port forwarded and have some scripts going on.

### Errors / Screenshots
console 

[15:26:24 ERROR]: #!#! [Skript] Severe Error:
[15:26:24 ERROR]: #!#!
[15:26:24 ERROR]: #!#! Something went horribly wrong with Skript.
[15:26:24 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:26:24 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[15:26:24 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[15:26:24 ERROR]: #!#!
[15:26:24 ERROR]: #!#! Stack trace:
[15:26:24 ERROR]: #!#! java.nio.file.FileSystemException: C:\Users\kimju\OneDrive\바탕 화면\마크서버\plugins\zipfstmp4717469182360694117.tmp: 다른 프로세스가 파일을 사용 중이기 때문에 프로 세스가 액세스 할 수 없습니다.

[15:26:24 ERROR]: #!#!     at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
[15:26:24 ERROR]: #!#!     at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[15:26:24 ERROR]: #!#!     at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[15:26:24 ERROR]: #!#!     at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
[15:26:24 ERROR]: #!#!     at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
[15:26:24 ERROR]: #!#!     at java.nio.file.Files.delete(Unknown Source)
[15:26:24 ERROR]: #!#!     at com.sun.nio.zipfs.ZipFileSystem.removeTempPathForEntry(ZipFileSystem.java:852)
[15:26:24 ERROR]: #!#!     at com.sun.nio.zipfs.ZipFileSystem.access$100(ZipFileSystem.java:80)
[15:26:24 ERROR]: #!#!     at com.sun.nio.zipfs.ZipFileSystem$4.implCloseChannel(ZipFileSystem.java:820)
[15:26:24 ERROR]: #!#!     at java.nio.channels.spi.AbstractInterruptibleChannel.close(Unknown Source)
[15:26:24 ERROR]: #!#!     at sun.nio.ch.ChannelInputStream.close(Unknown Source)
[15:26:24 ERROR]: #!#!     at sun.nio.cs.StreamDecoder.implClose(Unknown Source)
[15:26:24 ERROR]: #!#!     at sun.nio.cs.StreamDecoder.close(Unknown Source)
[15:26:24 ERROR]: #!#!     at java.io.InputStreamReader.close(Unknown Source)
[15:26:24 ERROR]: #!#!     at java.io.BufferedReader.close(Unknown Source)
[15:26:24 ERROR]: #!#!     at ch.njol.skript.config.Config.<init>(Config.java:99)
[15:26:24 ERROR]: #!#!     at ch.njol.skript.config.Config.<init>(Config.java:107)
[15:26:24 ERROR]: #!#!     at ch.njol.skript.config.Config.<init>(Config.java:118)
[15:26:24 ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.load(Aliases.java:489)
[15:26:24 ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:473)
[15:26:24 ERROR]: #!#!     at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[15:26:24 ERROR]: #!#!     at java.util.ArrayList.forEach(Unknown Source)
[15:26:24 ERROR]: #!#!     at java.util.stream.SortedOps$RefSortingSink.end(Unknown Source)
[15:26:24 ERROR]: #!#!     at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[15:26:24 ERROR]: #!#!     at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[15:26:24 ERROR]: #!#!     at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[15:26:24 ERROR]: #!#!     at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[15:26:24 ERROR]: #!#!     at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[15:26:24 ERROR]: #!#!     at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[15:26:24 ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:466)
[15:26:24 ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:432)
[15:26:24 ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.load(Aliases.java:404)
[15:26:24 ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:405)
[15:26:24 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:26:24 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[15:26:24 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[15:26:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[15:26:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[15:26:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:752)
[15:26:24 ERROR]: #!#!     at org.bukkit.Bukkit.reload(Bukkit.java:525)
[15:26:24 ERROR]: #!#!     at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[15:26:24 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:26:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[15:26:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634)
[15:26:24 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444)
[15:26:24 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407)
[15:26:24 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[15:26:24 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[15:26:24 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[15:26:24 ERROR]: #!#!
[15:26:24 ERROR]: #!#! Version Information:
[15:26:24 ERROR]: #!#!   Skript: 2.5-alpha3 (latest)
[15:26:24 ERROR]: #!#!     Flavor: skriptlang-github
[15:26:24 ERROR]: #!#!     Date: 2020-03-28
[15:26:24 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[15:26:24 ERROR]: #!#!   Minecraft: 1.12.2
[15:26:24 ERROR]: #!#!   Java: 1.8.0_251 (Java HotSpot(TM) 64-Bit Server VM 25.251-b08)
[15:26:24 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[15:26:24 ERROR]: #!#!
[15:26:24 ERROR]: #!#! Server platform: Spigot
[15:26:24 ERROR]: #!#!
[15:26:24 ERROR]: #!#! Current node: null
[15:26:24 ERROR]: #!#! Current item: null
[15:26:24 ERROR]: #!#!
[15:26:24 ERROR]: #!#! Thread: Server thread
[15:26:24 ERROR]: #!#!
[15:26:24 ERROR]: #!#! Language: english
[15:26:24 ERROR]: #!#! Link parse mode: DISABLED
[15:26:24 ERROR]: #!#!
[15:26:24 ERROR]: #!#! End of Error.
--->

### Server Information
* **1.12.2/spigot:**       
* **Skript version:**   the newest version (exclude alpha,beta)

**Comment by ShaneBeee** [comment]
```
 java.nio.file.FileSystemException: C:\Users\kimju\OneDrive\바탕 화면\마크서버\plugins\zipfstmp4717469182360694117.tmp: 다른 프로세스가 파일을 사용 중이기 때문에 프로 세스가 액세스 할 수 없습니다.
```
seems to me the issue is because you're running your server in a OneDrive folder, which you should NOT be doing.

Please try replicate the issue on a server that is not running in a folder such as OneDrive

**Comment by Pikachu920** [comment]
`다른 프로세스가 파일을 사용 중이기 때문에 프로 세스가 액세스 할 수 없습니다` translates to `The process cannot access it because another process is using the file`. Onedrive/another program probably has you file open.

**Comment by Misio12320** [comment]
1 month and 10 days still no answer. Might time to close

**Comment by ShaneBeee** [comment]
Closing due to no response from reporter
