### ISSUE TITLE
Weird Error in Console?

### ISSUE THREAD

**Issue by LoLTonyJ** [SkriptLang/Skript#3055]
So, Im doing a private server, to practice my Skript Knoledge, but having some errors with the plugin.
I've provided some screenshots, along with the error that comes in the Console upon trying to do a command, and starting the Plugin.

"" In game Commands Don't work vvvv"
https://gyazo.com/d959699fe4877422b5f02995ba790327

"" Console Error "" 
(Latest Skript, from SkUntiy Website / Downloads)

Error occurred while enabling Skript v2.5-alpha3 (Is it up to date?)

(I've downloaded the latest version of TuSKe)

[15:31:07] [Server thread/INFO]: [TuSKe]  
[15:31:07] [Server thread/ERROR]: #!#! 
[15:31:07] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[15:31:07] [Server thread/ERROR]: #!#! TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception while loading
[15:31:07] [Server thread/ERROR]: #!#! 
[15:31:07] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[15:31:07] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:31:07] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:31:07] [Server thread/ERROR]: #!#! Following plugins are probably related to this error in some way:
[15:31:07] [Server thread/ERROR]: #!#! TuSKe (github.com/Tuke-Nuke/TuSKe) 
[15:31:07] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:31:07] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:31:07] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:31:07] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:31:07] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:31:07] [Server thread/ERROR]: #!#! 
[15:31:07] [Server thread/ERROR]: #!#! Stack trace:
[15:31:07] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[15:31:07] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
[15:31:07] [Server thread/ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[15:31:07] [Server thread/ERROR]: #!#!     at java.lang.Class.forName(Unknown Source)
[15:31:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[15:31:07] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.TuSKe.onEnable(TuSKe.java:100)
[15:31:07] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[15:31:07] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[15:31:07] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[15:31:07] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462)
[15:31:07] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376)
[15:31:07] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
[15:31:07] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:267)
[15:31:07] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
[15:31:07] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[15:31:07] [Server thread/ERROR]: #!#! 
[15:31:07] [Server thread/ERROR]: #!#! Version Information:
[15:31:07] [Server thread/ERROR]: #!#!   Skript: 2.5-alpha3
[15:31:07] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[15:31:07] [Server thread/ERROR]: #!#!     Date: 2020-03-28
[15:31:07] [Server thread/ERROR]: #!#!   Bukkit: 1.15.2-R0.1-SNAPSHOT
[15:31:07] [Server thread/ERROR]: #!#!   Minecraft: 1.15.2
[15:31:07] [Server thread/ERROR]: #!#!   Java: 1.8.0_241 (Java HotSpot(TM) Client VM 25.241-b07)
[15:31:07] [Server thread/ERROR]: #!#!   OS: Windows 10 x86 10.0
[15:31:07] [Server thread/ERROR]: #!#! 
[15:31:07] [Server thread/ERROR]: #!#! Server platform: Spigot
[15:31:07] [Server thread/ERROR]: #!#! 
[15:31:07] [Server thread/ERROR]: #!#! Current node: null
[15:31:07] [Server thread/ERROR]: #!#! Current item: null
[15:31:07] [Server thread/ERROR]: #!#! 
[15:31:07] [Server thread/ERROR]: #!#! Thread: Server thread
[15:31:07] [Server thread/ERROR]: #!#! 
[15:31:07] [Server thread/ERROR]: #!#! Language: english
[15:31:07] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[15:31:07] [Server thread/ERROR]: #!#! 
[15:31:07] [Server thread/ERROR]: #!#! End of Error.
[15:31:07] [Server thread/ERROR]: #!#! 
[15:31:08] [Server thread/INFO]: [TuSKe] Loaded 8 events, 12 conditions, 20 effects, 61 expressions and 0 types. Have fun!

**Comment by HYPExMon5ter** [comment]
This is a TuSKe error, TuSKe’s dev no longer maintains the addon, however,
Pikachu has a fixed version. I do not have the link on hand, but I’m sure
someone can provide it either here or if you ask in one of the skript help
discords.

**Comment by ShaneBeee** [comment]
As explained, this issue is not from Skript.
