### ISSUE TITLE
bug skript "ch.njol.skript.SkriptAPIException: No class info found for lambda"

### ISSUE THREAD

**Issue by OriginalCoca** [SkriptLang/Skript#3057]
Hi, can u help me ? I have this error, can you help me to resolve it ?

```
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! [Skript] Severe Error:
[15:57:50 ERROR]: #!#! Could not load Lobby.sk
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! Something went horribly wrong with Skript.
[15:57:50 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:57:50 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:57:50 ERROR]: #!#! Here is full list of them:
[15:57:50 ERROR]: #!#! skRayFall v1.9.20 (https://sk.rayfall.net/) TuSKe v1.8.2-Pikachu-Patch-3 (github.com/Tuke-Nuke/TuSKe) SkRambled v2.1 WolvSK v1.7.0 Skore v1.0.2 MundoSK v1.8.6-BETA.58 (https://forums.skunity.com/resources/mundosk.69/) Skellett v1.9.8 (https://forums.skunity.com/resources/skellett.24/) Skraper v1.2 Skent v1.9 WebAddon v1.0 SkriptJSON v1.0.0 skDragon v0.16 SkBee v1.3.3 SkQuery v3.21.4 SkExtras v3.9.1
[15:57:50 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[15:57:50 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:57:50 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:57:50 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:57:50 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:57:50 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! Stack trace:
[15:57:50 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for lambda
[15:57:50 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1838)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1805)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1553)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:502)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:840)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1569)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1499)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1526)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1526)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1565)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1526)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:81)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1121)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:490)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:652)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:410)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:429)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:348)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:381)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:584)
[15:57:50 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[15:57:50 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[15:57:50 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[15:57:50 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[15:57:50 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[15:57:50 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[15:57:50 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! Version Information:
[15:57:50 ERROR]: #!#!   Skript: 2.5-alpha3 (custom version)
[15:57:50 ERROR]: #!#!     Flavor: selfbuilt-unknown
[15:57:50 ERROR]: #!#!     Date: unknown
[15:57:50 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[15:57:50 ERROR]: #!#!   Minecraft: 1.8.8
[15:57:50 ERROR]: #!#!   Java: 1.8.0_251 (Java HotSpot(TM) 64-Bit Server VM 25.251-b08)
[15:57:50 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! Server platform: Spigot
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! Current node: if arg 1 isn't set: (Lobby.sk, line 26)
[15:57:50 ERROR]: #!#! Current item: null
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! Thread: Server thread
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! Language: english
[15:57:50 ERROR]: #!#! Link parse mode: DISABLED
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! End of Error.
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! [Skript] Severe Error:
[15:57:50 ERROR]: #!#! Could not load Mod.sk
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! Something went horribly wrong with Skript.
[15:57:50 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:57:50 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:57:50 ERROR]: #!#! Here is full list of them:
[15:57:50 ERROR]: #!#! skRayFall v1.9.20 (https://sk.rayfall.net/) TuSKe v1.8.2-Pikachu-Patch-3 (github.com/Tuke-Nuke/TuSKe) SkRambled v2.1 WolvSK v1.7.0 Skore v1.0.2 MundoSK v1.8.6-BETA.58 (https://forums.skunity.com/resources/mundosk.69/) Skellett v1.9.8 (https://forums.skunity.com/resources/skellett.24/) Skraper v1.2 Skent v1.9 WebAddon v1.0 SkriptJSON v1.0.0 skDragon v0.16 SkBee v1.3.3 SkQuery v3.21.4 SkExtras v3.9.1
[15:57:50 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[15:57:50 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:57:50 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:57:50 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:57:50 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:57:50 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! Stack trace:
[15:57:50 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for lambda
[15:57:50 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1838)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1805)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1553)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:502)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:840)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1569)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1499)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1526)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1565)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1526)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:81)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1121)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:490)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:652)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:410)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:429)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:348)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:381)
[15:57:50 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:584)
[15:57:50 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[15:57:50 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[15:57:50 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[15:57:50 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[15:57:50 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[15:57:50 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[15:57:50 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! Version Information:
[15:57:50 ERROR]: #!#!   Skript: 2.5-alpha3 (custom version)
[15:57:50 ERROR]: #!#!     Flavor: selfbuilt-unknown
[15:57:50 ERROR]: #!#!     Date: unknown
[15:57:50 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[15:57:50 ERROR]: #!#!   Minecraft: 1.8.8
[15:57:50 ERROR]: #!#!   Java: 1.8.0_251 (Java HotSpot(TM) 64-Bit Server VM 25.251-b08)
[15:57:50 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! Server platform: Spigot
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! Current node: if {mod.%player's uuid%} is true: (Mod.sk, line 27)
[15:57:50 ERROR]: #!#! Current item: null
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! Thread: Server thread
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! Language: english
[15:57:50 ERROR]: #!#! Link parse mode: DISABLED
[15:57:50 ERROR]: #!#!
[15:57:50 ERROR]: #!#! End of Error.
[15:57:50 ERROR]: #!#!
[15:57:50 INFO]: [Skript] All scripts loaded without errors.
```

**Comment by ShaneBeee** [comment]
Skript 2.3+ does not run on any MC version before 1.9
