### ISSUE TITLE
Health Utils null pointer

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#3095]
Running effect `heal player` throws null pointer exception. This is only present in 1.16.1 where I have seen this error, and I use this syntax frequently.

Does not heal the player, so this is critical, but it's also an alpha version.

### Errors / Screenshots
```
[Server thread/ERROR]: #!#! Stack trace:
[Server thread/ERROR]: #!#! java.lang.NullPointerException
[Server thread/ERROR]: #!#!     at ch.njol.skript.bukkitutil.HealthUtils.getMaxHealth(HealthUtils.java:66)
[Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffHealth.execute(EffHealth.java:120)
[Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:277)
[Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:210)
[Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:1)
[Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
[Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1059)
[Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354)
[Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1007)
[Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:846)
[Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
[Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
```

It's also present when changing anything related to the player's health
```
[Server thread/ERROR]: #!#! Stack trace:
[Server thread/ERROR]: #!#! java.lang.NullPointerException
[Server thread/ERROR]: #!#!     at ch.njol.skript.bukkitutil.HealthUtils.getMaxHealth(HealthUtils.java:66)
[Server thread/ERROR]: #!#!     at ch.njol.skript.bukkitutil.HealthUtils.setHealth(HealthUtils.java:56)
[Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprHealth.change(ExprHealth.java:117)
[Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
```

**Suggestions**
Can we get a test script that handles health so this doesn't become prominent again.

### Server Information
* **Server version/platform:** 1.16.1
* **Skript version:** 2.5-Alpha-5

**Comment by ShaneBeee** [comment]
I can not replicate this issue:
<img width="978" alt="Screen Shot 2020-07-02 at 7 28 26 PM" src="https://user-images.githubusercontent.com/20008482/86425506-3a75b700-bc9a-11ea-87ef-ccebac8f7e38.png">

I recommend updating your server jar if you haven't already. Maybe this was a Spigot/Paper issue, that's potentially been solved already.

**Comment by TheBentoBox** [comment]
I believe this was caused due to an outdated server jar as I was also having this issue at one point and fixed it by updating.
