### ISSUE TITLE
Minecraft prison cell error

### ISSUE THREAD

**Issue by ChR1st0J** [SkriptLang/Skript#3157]
I got this prison skript from a friend but every 1 minute it spams my console with this error. In the code it should remove a player as owner if the time is under 1 minute. I´ve put the skript on my server and bought a region for a couple days, now when there is 1m 26.45s left on the sign, the error comes up, and the region is still mine.
[Error.zip](https://github.com/SkriptLang/Skript/files/4934911/Error.zip)

[01:21:00 ERROR]: #!#!
[01:21:00 ERROR]: #!#! Thread: Server thread
[01:21:00 ERROR]: #!#!
[01:21:00 ERROR]: #!#! End of Error.
[01:21:00 ERROR]: #!#!
[01:26:01 ERROR]: #!#!
[01:26:01 ERROR]: #!#! [Skript] Severe Error:
[01:26:01 ERROR]: #!#!
[01:26:01 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[01:26:01 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[01:26:01 ERROR]: #!#! and check whether this error has already been reported.
[01:26:01 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[01:26:01 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[01:26:01 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[01:26:01 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[01:26:01 ERROR]: #!#!
[01:26:01 ERROR]: #!#! Stack trace:
[01:26:01 ERROR]: #!#! java.lang.NullPointerException
[01:26:01 ERROR]: #!#!     at com.gmail.thelimeglass.Expressions.ExprWorldOfLocation.get(ExprWorldOfLocation.java:49)
[01:26:01 ERROR]: #!#!     at com.gmail.thelimeglass.Expressions.ExprWorldOfLocation.get(ExprWorldOfLocation.java:1)
[01:26:01 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103)
[01:26:01 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:404)
[01:26:01 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:606)
[01:26:01 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:1)
[01:26:01 ERROR]: #!#!     at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:77)
[01:26:01 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[01:26:01 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[01:26:01 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[01:26:01 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[01:26:01 ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:90)
[01:26:01 ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:104)
[01:26:01 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[01:26:01 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[01:26:01 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[01:26:01 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[01:26:01 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[01:26:01 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[01:26:01 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[01:26:01 ERROR]: #!#!
[01:26:01 ERROR]: #!#! Version Information:
[01:26:01 ERROR]: #!#!   Skript: 2.2-dev27
[01:26:01 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[01:26:01 ERROR]: #!#!   Minecraft: 1.8.8
[01:26:01 ERROR]: #!#!   Java: 1.8.0_251 (Java HotSpot(TM) Client VM 25.251-b08)
[01:26:01 ERROR]: #!#!   OS: Windows 10 x86 10.0
[01:26:01 ERROR]: #!#!
[01:26:01 ERROR]: #!#! Running CraftBukkit: false
[01:26:01 ERROR]: #!#!
[01:26:01 ERROR]: #!#! Current node: null
[01:26:01 ERROR]: #!#! Current item: make the console execute the command "/rg removeowner %loop-value% -w %[skellett] world (of|from) [location] %location%% %{cell.%loop-value%.owner}(as java.lang.Object)%"
[01:26:01 ERROR]: #!#!
[01:26:01 ERROR]: #!#! Thread: Server thread
[01:26:01 ERROR]: #!#!
[01:26:01 ERROR]: #!#! End of Error.
[01:26:01 ERROR]: #!#!

**Comment by ShaneBeee** [comment]
2.2dev27 is extremely outdated and no longer supported, nor is any Minecraft version prior to 1.9.4
