### ISSUE TITLE
A crash happened when remove items of the player's tool

### ISSUE THREAD

**Issue by lnelg10** [SkriptLang/Skript#3160]
### Description
When I removed an item from the player's tool , a crash happened. 

### Steps to Reproduce
`on rightclick:`
	`if player is holding a chest with name "&aTEST":`
		`set {_money} to "%random integer between 100 and 150%" parsed as number`
		`remove 1 chest with name "&aTEST" from the player's tool`
		`increase the player's balance by {_money}`

### Expected Behavior
When player rightclicks with the chest ,the player will get money and consume a chest.

### Errors / Screenshots
The server suddenly crashed and shutdown.
When player has more chests in his hand , the server doesn't crash , the crash only happened when only 1 chest in the player's hand.

java.lang.AssertionError: TRAP
	at net.minecraft.server.v1_16_R1.ItemStack.checkEmpty(ItemStack.java:99)
	at net.minecraft.server.v1_16_R1.ItemStack.setCount(ItemStack.java:884)
	at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:407)
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1353)
	at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28)
	at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943)
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936)
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920)
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852)
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
	at java.lang.Thread.run(Unknown Source)

### Server Information
* **Server version/platform:1.16.1 spigot**       
* **Skript version:2.5-alpha5**

**Comment by Romitou** [comment]
This answer might help you : https://github.com/SkriptLang/Skript/issues/2143#issuecomment-499615192

**Comment by lnelg10** [comment]
Thank you ! The problem has been solved .
