### ISSUE TITLE
error in paper 1.16.1 by 2.5 beta 1

### ISSUE THREAD

**Issue by chlwlghks78** [SkriptLang/Skript#3275]
### Description
After applying the skript to the server, I reloaded the server, but skript showed several errors, making skript unusable.

### Errors / Screenshots
When I command "/sk"
+No Edditing config

org.bukkit.command.CommandException: Cannot execute command 'sk' in plugin Skript v2.5-beta1 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

When I reloading the server
+Edditing config
(enable effect commands: true)
(allow ops to use effect commands: true)

error occurred while enabling Skript v2.5-beta1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at ch.njol.skript.Skript.onEnable(Skript.java:435) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.reload(CraftServer.java:932) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.Bukkit.reload(Bukkit.java:688) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.IllegalArgumentException: type stationary water not found
	at ch.njol.skript.aliases.Aliases.javaItemType(Aliases.java:558) ~[?:?]
	at ch.njol.skript.classes.data.BukkitEventValues.<clinit>(BukkitEventValues.java:309) ~[?:?]
	... 18 more

When I command "/sk"
+Edditing config
(enable effect commands: true)
(allow ops to use effect commands: true)

Unexpected exception while parsing console command "sk"
org.bukkit.command.CommandException: Cannot execute command 'sk' in plugin Skript v2.5-beta1 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

### Server Information
* **Server version/platform:1.16.1**
* **Skript version: 2.5 beta 1**

### Additional Context
this is just report..
Please don't try to give me an answer.
I'd appreciate it if you solved it.
thx!

**Comment by Wealthyturtle** [comment]
Reload or restart?

**Comment by ShaneBeee** [comment]
1) In general `/reload` is not supported by plugins, and should only be used by plugin developers, not server owners. This command notably is bad-news-bears.

2)
```
Caused by: java.lang.IllegalArgumentException: type stationary water not found
at ch.njol.skript.aliases.Aliases.javaItemType(Aliases.java:558) ~[?:?]
at ch.njol.skript.classes.data.BukkitEventValues.(BukkitEventValues.java:309) ~[?:?]
```
This is usually an alias issue, which is often fixed by:
- stop your server
- delete the materials file `plugins/Skript/materials.json`
- start your server

Hopefully that solves your issue. 
In the future, dont run `/reload`

**Comment by chlwlghks78** [comment]
okay
I tested it.
and It was Successful.
Thanks for the reply
