### ISSUE TITLE
Error on load on 1.8.8

### ISSUE THREAD

**Issue by DarkBoy2005** [SkriptLang/Skript#3287]
### Description

The plugin wont load

### Steps to Reproduce

Just installed the plugin

### Expected Behavior

Load the plugin

### Errors / Screenshots

[07:40:15 ERROR]: Error occurred while enabling Skript v2.5-beta1 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.inventory.meta.PotionMeta.getBasePotionData()Lorg/bukkit/potion/PotionData;
        at ch.njol.skript.aliases.ItemData.compareItemMetas(ItemData.java:434) ~[?:?]
        at ch.njol.skript.aliases.ItemData.matchAlias(ItemData.java:365) ~[?:?]
        at ch.njol.skript.aliases.AliasesMap.exactMatch(AliasesMap.java:216) ~[?:?]
        at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:285) ~[?:?]
        at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:703) ~[?:?]
        at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:603) ~[?:?]
        at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:121) ~[?:?]
        at ch.njol.skript.aliases.Aliases.load(Aliases.java:496) ~[?:?]
        at ch.njol.skript.aliases.Aliases.load(Aliases.java:482) ~[?:?]
        at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:465) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_252]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_252]
        at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_252]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_252]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_252]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_252]
        at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:458) ~[?:?]
        at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:424) ~[?:?]
        at ch.njol.skript.aliases.Aliases.load(Aliases.java:396) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:409) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Auth.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

[07:40:15 ERROR]: Error occurred while enabling Skript v2.5-beta1 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.inventory.meta.PotionMeta.getBasePotionData()Lorg/bukkit/potion/PotionData;
        at ch.njol.skript.aliases.ItemData.compareItemMetas(ItemData.java:434) ~[?:?]
        at ch.njol.skript.aliases.ItemData.matchAlias(ItemData.java:365) ~[?:?]
        at ch.njol.skript.aliases.AliasesMap.exactMatch(AliasesMap.java:216) ~[?:?]
        at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:285) ~[?:?]
        at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:703) ~[?:?]
        at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:603) ~[?:?]
        at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:121) ~[?:?]
        at ch.njol.skript.aliases.Aliases.load(Aliases.java:496) ~[?:?]
        at ch.njol.skript.aliases.Aliases.load(Aliases.java:482) ~[?:?]
        at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:465) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_252]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_252]
        at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_252]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_252]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_252]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_252]
        at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:458) ~[?:?]
        at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:424) ~[?:?]
        at ch.njol.skript.aliases.Aliases.load(Aliases.java:396) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:409) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Auth.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [Auth.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

![kép](https://user-images.githubusercontent.com/68329594/89725854-898ad680-da14-11ea-848a-7dfd98592fb3.png)

![kép](https://user-images.githubusercontent.com/68329594/89725858-8f80b780-da14-11ea-8716-4d005966033b.png)

### Server Information
* **Server version/platform:** 
* **Skript version:** 

Server: 1.8.8
Skript: 2.5-beta1

### Additional Context

If the plugin dont have add 1.8 support pls

**Comment by ShaneBeee** [comment]
1.8.8 is not supported.
Skript 2.3+ will only work on 1.9.4+
