### ISSUE TITLE
Anvil Inventory

### ISSUE THREAD

**Issue by Creeper1841** [SkriptLang/Skript#3341]
### Description

When clicking a slot in an anvil opened by Skript, it will cause a "packet processing error"

### Steps to Reproduce

Execute this code:
'open anvil inventory to player'
The first two slots are compromised, you can peacefully click the last slot

### Expected Behavior

You shouldn't get kicked. Code can peacefully be executed, but you'll get kicked when clicking the two first slots.

### Errors / Screenshots

[17:23:31] [Server thread/ERROR]: Error whilst processing packet net.minecraft.server.v1_16_R1.PacketPlayInWindowClick@173a907f for AWorthySon[/33.172.206.195:57522]
net.minecraft.server.v1_16_R1.ReportedException: Container click
	at net.minecraft.server.v1_16_R1.Container.a(Container.java:198) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2433) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[spigot.jar:git-Paper-129]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.UnsupportedOperationException: Not supported yet.
	at net.minecraft.server.v1_16_R1.ContainerAccess.getWorld(ContainerAccess.java:11) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.ContainerAccess.getLocation(ContainerAccess.java:19) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.ContainerAnvil.getBukkitView(ContainerAnvil.java:308) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.ContainerAnvil.e(ContainerAnvil.java:275) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:67) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.ContainerAnvilAbstract$1.update(ContainerAnvilAbstract.java:12) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.InventorySubcontainer.setItem(InventorySubcontainer.java:183) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.Slot.set(SourceFile:82) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.Container.a(Container.java:637) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.ContainerAnvilAbstract.shiftClick(ContainerAnvilAbstract.java:112) ~[spigot.jar:git-Paper-129]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftContainer.shiftClick(CraftContainer.java:300) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.Container.b(Container.java:334) ~[spigot.jar:git-Paper-129]
	at net.minecraft.server.v1_16_R1.Container.a(Container.java:183) ~[spigot.jar:git-Paper-129]
	... 15 more

### Server Information
* **Server version/platform: Paper git-paper-129 1.16.1** 
* **Skript version: 2.5-beta2**

**Comment by ShaneBeee** [comment]
Looking at that error, I think this is a CB/Spigot/Paper issue. I dont think custom anvil inventories are properly supported.
