### ISSUE TITLE
sk reload with add-on

### ISSUE THREAD

**Issue by daveston** [SkriptLang/Skript#3373]
[12:00:10] [Server thread/ERROR]: #!#!
[12:00:10] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[12:00:10] [Server thread/ERROR]: #!#! Could not load discord.sk
[12:00:10] [Server thread/ERROR]: #!#!
[12:00:10] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[12:00:10] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[12:00:10] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[12:00:10] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[12:00:10] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[12:00:10] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[12:00:10] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[12:00:10] [Server thread/ERROR]: #!#!
[12:00:10] [Server thread/ERROR]: #!#! Stack trace:
[12:00:10] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for worldborder
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:264)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1390)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1111)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:221)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:321)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:418)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1132)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1057)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1123)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:221)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.Condition.parse(Condition.java:83)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:833)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:513)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:271)
[12:00:10] [Server thread/ERROR]: #!#! at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:167)
[12:00:10] [Server thread/ERROR]: #!#! at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:00:10] [Server thread/ERROR]: #!#! at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[12:00:10] [Server thread/ERROR]: #!#! at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[12:00:10] [Server thread/ERROR]: #!#! at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[12:00:10] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[12:00:10] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[12:00:10] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[12:00:10] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[12:00:10] [Server thread/ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
[12:00:10] [Server thread/ERROR]: #!#!
[12:00:10] [Server thread/ERROR]: #!#! Version Information:
[12:00:10] [Server thread/ERROR]: #!#! Skript: 2.2-dev25
[12:00:10] [Server thread/ERROR]: #!#! Bukkit: 1.8.8-R0.1-SNAPSHOT
[12:00:10] [Server thread/ERROR]: #!#! Minecraft: 1.8.8
[12:00:10] [Server thread/ERROR]: #!#! Java: 1.8.0_201 (Java HotSpot(TM) 64-Bit Server VM 25.201-b09)
[12:00:10] [Server thread/ERROR]: #!#! OS: Linux amd64 3.16.0-7-amd64
[12:00:10] [Server thread/ERROR]: #!#!
[12:00:10] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[12:00:10] [Server thread/ERROR]: #!#!
[12:00:10] [Server thread/ERROR]: #!#! Current node: if attacker is a player: (discord.sk, line 7)
[12:00:10] [Server thread/ERROR]: #!#! Current item: null
[12:00:10] [Server thread/ERROR]: #!#!
[12:00:10] [Server thread/ERROR]: #!#! Thread: Server thread
[12:00:10] [Server thread/ERROR]: #!#!
[12:00:10] [Server thread/ERROR]: #!#! End of Error.
[12:00:10] [Server thread/ERROR]: #!#!
[12:00:10] [Server thread/INFO]: [Skript] Successfully reloaded discord.sk.

**Comment by ShaneBeee** [comment]
2.2-dev25 is severely outdated and no longer supported.
1.8.8 never has been supported either.
