### ISSUE TITLE
why i can't use TuSKe

### ISSUE THREAD

**Issue by chuxia1123** [SkriptLang/Skript#3376]
TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception while loading
[14:20:33] [Server thread/ERROR]: #!#!
[14:20:33] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[14:20:33] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:20:33] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[14:20:33] [Server thread/ERROR]: #!#! Following plugins are probably related to this error in some way:
[14:20:33] [Server thread/ERROR]: #!#! TuSKe (github.com/Tuke-Nuke/TuSKe)
[14:20:33] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[14:20:33] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[14:20:33] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[14:20:33] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[14:20:33] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[14:20:33] [Server thread/ERROR]: #!#!
[14:20:33] [Server thread/ERROR]: #!#! Stack trace:
[14:20:33] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[14:20:33] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
[14:20:33] [Server thread/ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[14:20:33] [Server thread/ERROR]: #!#!     at java.lang.Class.forName(Unknown Source)
[14:20:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[14:20:33] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.TuSKe.onEnable(TuSKe.java:100)
[14:20:33] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:20:33] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[14:20:33] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[14:20:33] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492)
[14:20:33] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406)
[14:20:33] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R2.CraftServer.reload(CraftServer.java:874)
[14:20:33] [Server thread/ERROR]: #!#!     at org.bukkit.Bukkit.reload(Bukkit.java:642)
[14:20:33] [Server thread/ERROR]: #!#!     at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[14:20:33] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[14:20:33] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:756)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PlayerConnectionUtils$$Lambda$3987/239764785.run(Unknown Source)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[14:20:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3218/2008009697.run(Unknown Source)
[14:20:33] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[14:20:33] [Server thread/ERROR]: #!#!
[14:20:33] [Server thread/ERROR]: #!#! Version Information:
[14:20:33] [Server thread/ERROR]: #!#!   Skript: 2.4.1 (latest)
[14:20:33] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[14:20:33] [Server thread/ERROR]: #!#!     Date: 2019-12-22
[14:20:33] [Server thread/ERROR]: #!#!   Bukkit: 1.16.2-R0.1-SNAPSHOT
[14:20:33] [Server thread/ERROR]: #!#!   Minecraft: 1.16.2
[14:20:33] [Server thread/ERROR]: #!#!   Java: 1.8.0_51 (Java HotSpot(TM) 64-Bit Server VM 25.51-b03)
[14:20:33] [Server thread/ERROR]: #!#!   OS: Windows 8.1 amd64 6.3
[14:20:33] [Server thread/ERROR]: #!#!
[14:20:33] [Server thread/ERROR]: #!#! Server platform: Spigot
[14:20:33] [Server thread/ERROR]: #!#!
[14:20:33] [Server thread/ERROR]: #!#! Current node: null
[14:20:33] [Server thread/ERROR]: #!#! Current item: null
[14:20:33] [Server thread/ERROR]: #!#!
[14:20:33] [Server thread/ERROR]: #!#! Thread: Server thread
[14:20:33] [Server thread/ERROR]: #!#!
[14:20:33] [Server thread/ERROR]: #!#! Language: english
[14:20:33] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[14:20:33] [Server thread/ERROR]: #!#!
[14:20:33] [Server thread/ERROR]: #!#! End of Error.
[14:20:33] [Server thread/ERROR]: #!#!
[14:20:33] [Server thread/INFO]: [TuSKe] Loaded 8 events, 12 conditions, 20 effects, 61 expression

**Comment by ShaneBeee** [comment]
This is an issue tracker for SKRIPT not TUSKE
