### ISSUE TITLE
how to fix it

### ISSUE THREAD

**Issue by chuxia1123** [SkriptLang/Skript#3384]
[17:07:49] [ForkJoinPool.commonPool-worker-9/INFO]: [Skript] You're currently running the latest stable version of Skript.
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[17:07:53] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:07:53] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[17:07:53] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! Stack trace:
[17:07:53] [Server thread/ERROR]: #!#! java.nio.file.FileSystemException: C:\Users\60164\Desktop\chuxia server\plugins\zipfstmp156510896930034266.tmp: ????????????????????

[17:07:53] [Server thread/ERROR]: #!#!     at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at java.nio.file.Files.deleteIfExists(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at java.nio.file.Files.copy(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at com.sun.nio.zipfs.ZipFileSystem.getTempPathForEntry(ZipFileSystem.java:844)
[17:07:53] [Server thread/ERROR]: #!#!     at com.sun.nio.zipfs.ZipFileSystem.newFileChannel(ZipFileSystem.java:723)
[17:07:53] [Server thread/ERROR]: #!#!     at com.sun.nio.zipfs.ZipPath.newFileChannel(ZipPath.java:747)
[17:07:53] [Server thread/ERROR]: #!#!     at com.sun.nio.zipfs.ZipFileSystemProvider.newFileChannel(ZipFileSystemProvider.java:271)
[17:07:53] [Server thread/ERROR]: #!#!     at java.nio.channels.FileChannel.open(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at java.nio.channels.FileChannel.open(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.config.Config.<init>(Config.java:118)
[17:07:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.load(Aliases.java:481)
[17:07:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:465)
[17:07:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.aliases.Aliases$$Lambda$4157/1456479758.accept(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at java.util.stream.SortedOps$RefSortingSink$$Lambda$151/113411247.accept(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at java.util.ArrayList.forEach(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at java.util.stream.SortedOps$RefSortingSink.end(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:458)
[17:07:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:424)
[17:07:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.load(Aliases.java:396)
[17:07:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:409)
[17:07:53] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:07:53] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[17:07:53] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[17:07:53] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494)
[17:07:53] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408)
[17:07:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435)
[17:07:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:216)
[17:07:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808)
[17:07:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[17:07:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3228/882695706.run(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! Version Information:
[17:07:53] [Server thread/ERROR]: #!#!   Skript: 2.5-beta3 (latest)
[17:07:53] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[17:07:53] [Server thread/ERROR]: #!#!     Date: 2020-08-28
[17:07:53] [Server thread/ERROR]: #!#!   Bukkit: 1.16.3-R0.1-SNAPSHOT
[17:07:53] [Server thread/ERROR]: #!#!   Minecraft: 1.16.3
[17:07:53] [Server thread/ERROR]: #!#!   Java: 1.8.0_51 (Java HotSpot(TM) 64-Bit Server VM 25.51-b03)
[17:07:53] [Server thread/ERROR]: #!#!   OS: Windows 8.1 amd64 6.3
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! Server platform: Spigot
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! Current node: null
[17:07:53] [Server thread/ERROR]: #!#! Current item: null
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! Thread: Server thread
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! Language: english
[17:07:53] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! End of Error.
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[17:07:53] [Server thread/ERROR]: #!#! Skript's class ch.njol.skript.entity.BoatData generated an exception while loading
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[17:07:53] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:07:53] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[17:07:53] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! Stack trace:
[17:07:53] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: type oak boat not found
[17:07:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.javaItemType(Aliases.java:558)
[17:07:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.BoatData.<clinit>(BoatData.java:112)
[17:07:53] [Server thread/ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[17:07:53] [Server thread/ERROR]: #!#!     at java.lang.Class.forName(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[17:07:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:444)
[17:07:53] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:07:53] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[17:07:53] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[17:07:53] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494)
[17:07:53] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408)
[17:07:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435)
[17:07:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:216)
[17:07:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808)
[17:07:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[17:07:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3228/882695706.run(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! Version Information:
[17:07:53] [Server thread/ERROR]: #!#!   Skript: 2.5-beta3 (latest)
[17:07:53] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[17:07:53] [Server thread/ERROR]: #!#!     Date: 2020-08-28
[17:07:53] [Server thread/ERROR]: #!#!   Bukkit: 1.16.3-R0.1-SNAPSHOT
[17:07:53] [Server thread/ERROR]: #!#!   Minecraft: 1.16.3
[17:07:53] [Server thread/ERROR]: #!#!   Java: 1.8.0_51 (Java HotSpot(TM) 64-Bit Server VM 25.51-b03)
[17:07:53] [Server thread/ERROR]: #!#!   OS: Windows 8.1 amd64 6.3
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! Server platform: Spigot
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! Current node: null
[17:07:53] [Server thread/ERROR]: #!#! Current item: null
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! Thread: Server thread
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! Language: english
[17:07:53] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: #!#! End of Error.
[17:07:53] [Server thread/ERROR]: #!#!
[17:07:53] [Server thread/ERROR]: Error occurred while enabling Skript v2.5-beta3 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class ch.njol.skript.entity.BoatData
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_51]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_51]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_51]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_51]
        at ch.njol.skript.entity.EntityData.getData(EntityData.java:514) ~[?:?]
        at ch.njol.skript.entity.EntityData.fromClass(EntityData.java:531) ~[?:?]
        at ch.njol.skript.expressions.ExprSpawnerType.<clinit>(ExprSpawnerType.java:58) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_51]
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:444) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494) [spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408) [spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435) [spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:216) [spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) [spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) [spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3228/882695706.run(Unknown Source) [spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]

**Comment by ShaneBeee** [comment]
Looks to be a file permission issue, on your end.

**Comment by Wealthyturtle** [comment]
The first error you provided looks to be some file issue on your end.

The second error:
```
[17:07:53] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: type oak boat not found
[17:07:53] [Server thread/ERROR]: #!#! at ch.njol.skript.aliases.Aliases.javaItemType(Aliases.java:558)
[17:07:53] [Server thread/ERROR]: #!#! at ch.njol.skript.entity.BoatData.(BoatData.java:112)
```

Looks like an alias issue, see #3275 for some steps that should resolve it

**Comment by TPGamesNL** [comment]
Closing due to lack of response
