### ISSUE TITLE
Adding pages to books

### ISSUE THREAD

**Issue by FreakyHD** [SkriptLang/Skript#3406]
### Description
I'm getting an error when I try to add a page to a book.

### Steps to Reproduce
        set {_book} to a new written book
        add "Test" to page 1 of {_book}
        give {_book} to player
### Expected Behavior
Adding a page to a book.

### Errors / Screenshots
Error:
https://gist.github.com/FreakyHD/6df73a47b312b27db3dce977bc782f83

### Server Information
* **Server version/platform:** 1.12.2
* **Skript version:** 
![image](https://user-images.githubusercontent.com/71927791/94339396-08a29100-fffa-11ea-8c95-1d26fa6ca01d.png)

**Comment by ShaneBeee** [comment]
Seems to be an issue with an addon:
```
[13:07:08 ERROR]: #!#! Stack trace:
[13:07:08 ERROR]: #!#! java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
[13:07:08 ERROR]: #!#! at com.pie.tlatoani.Book.TransBookPages.set(TransBookPages.java:42)
[13:07:08 ERROR]: #!#! at com.pie.tlatoani.ListUtil.ExprElement.change(ExprElement.java:71)
```
