### ISSUE TITLE
Log Handlers error

### ISSUE THREAD

**Issue by JerryTheSlime16** [SkriptLang/Skript#3411]
### Description
This spams my console on startup.  Will sometimes not happen, but mainly does.

### Steps to Reproduce
No idea

### Expected Behavior
No errors

### Errors / Screenshots
```
[Mon, 28. Sep 2020 17:30:24 EDT ERROR] [Skript] 2 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1601)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[Mon, 28. Sep 2020 17:30:24 EDT ERROR] [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:371)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[Mon, 28. Sep 2020 17:30:24 EDT ERROR] [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:371)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[Mon, 28. Sep 2020 17:30:24 EDT ERROR] [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:371)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[Mon, 28. Sep 2020 17:30:24 EDT ERROR] [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:371)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[Mon, 28. Sep 2020 17:30:24 EDT ERROR] [Skript] 3 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1601)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
```

### Server Information
* **Server version/platform:** 1.16.1
* **Skript version:** 2.5

### Additional Context
Each ones seems to be different let me know if you need anything else.

**Comment by ShaneBeee** [comment]
This error is generally caused by using an outdated version of Skript-mirror.
If you are using a version older than 2.0.0 then update Skript-mirror to 2.0.0 or consider using the more updated fork, Skript-reflect.
