### ISSUE TITLE
Something went horribly wrong with skript

### ISSUE THREAD

**Issue by Fyriiee** [SkriptLang/Skript#3455]
### Steps to Reproduce
I wrote a script which I'm trying to use to teleport players to a specific spot. The location part didn't work though, and said that there was an internal error when I ran it. So, I made a little script testing if it just didn't work at all. Turns out I was right.

### Expected Behavior
I should be teleported correctly when I use /testtest.

### Errors / Screenshots
```vb
[01:03:06] [Server thread/INFO]: Fyriiee issued server command: /testtest
[01:03:06] [Server thread/INFO]: Fyriiee [3eb51d90-dc59-426a-b7fe-19dcf787c77f]: /testtest
[01:03:06] [Server thread/ERROR]: #!#! 
[01:03:06] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[01:03:06] [Server thread/ERROR]: #!#! 
[01:03:06] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[01:03:06] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[01:03:06] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[01:03:06] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[01:03:06] [Server thread/ERROR]: #!#! 
[01:03:06] [Server thread/ERROR]: #!#! Stack trace:
[01:03:06] [Server thread/ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: 0
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultFunctions$23.execute(DefaultFunctions.java:316)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultFunctions$23.execute(DefaultFunctions.java:1)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:136)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:266)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ExprFunctionCall.get(ExprFunctionCall.java:44)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.Direction$1.get(Direction.java:381)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.Direction$1.get(Direction.java:1)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:59)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffTeleport.execute(EffTeleport.java:68)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:249)
[01:03:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:166)
[01:03:06] [Server thread/ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[01:03:06] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[01:03:06] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:03:06] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[01:03:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1900)
[01:03:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1719)
[01:03:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
[01:03:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[01:03:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[01:03:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[01:03:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[01:03:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[01:03:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[01:03:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
[01:03:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
[01:03:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[01:03:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089)
[01:03:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003)
[01:03:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[01:03:06] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[01:03:06] [Server thread/ERROR]: #!#! 
[01:03:06] [Server thread/ERROR]: #!#! Version Information:
[01:03:06] [Server thread/ERROR]: #!#!   Skript: 2.5-beta2-MH (custom version)
[01:03:06] [Server thread/ERROR]: #!#!     Flavor: selfbuilt-unknown
[01:03:06] [Server thread/ERROR]: #!#!     Date: unknown
[01:03:06] [Server thread/ERROR]: #!#!   Bukkit: 1.16.3-R0.1-SNAPSHOT
[01:03:06] [Server thread/ERROR]: #!#!   Minecraft: 1.16.3
[01:03:06] [Server thread/ERROR]: #!#!   Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b04)
[01:03:06] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.4.0-48-generic
[01:03:06] [Server thread/ERROR]: #!#! 
[01:03:06] [Server thread/ERROR]: #!#! Server platform: Paper
[01:03:06] [Server thread/ERROR]: #!#! 
[01:03:06] [Server thread/ERROR]: #!#! Current node: null
[01:03:06] [Server thread/ERROR]: #!#! Current item: teleport the player to [[direction:at]] location([[long:1010]], [[long:62]], [[long:1010]])
[01:03:06] [Server thread/ERROR]: #!#! Current trigger: command /testtest (simple event) (Threes.sk, line -1)
[01:03:06] [Server thread/ERROR]: #!#! 
[01:03:06] [Server thread/ERROR]: #!#! Thread: Server thread
[01:03:06] [Server thread/ERROR]: #!#! 
[01:03:06] [Server thread/ERROR]: #!#! Language: english
[01:03:06] [Server thread/ERROR]: #!#! Link parse mode: STRICT
[01:03:06] [Server thread/ERROR]: #!#! 
[01:03:06] [Server thread/ERROR]: #!#! End of Error.
[01:03:06] [Server thread/ERROR]: #!#! 
```

### Server Information
http://prntscr.com/uv3y4t
http://prntscr.com/uv3ybj

**Comment by ShaneBeee** [comment]
`Skript: 2.5-beta2-MH (custom version)`
Forks are not supported by us. Please either report this to Minehut, or test on an official version from us.

**Comment by Fyriiee** [comment]
> `Skript: 2.5-beta2-MH (custom version)`
> Forks are not supported by us. Please either report this to Minehut, or test on an official version from us.
> 
> Also, make sure to add a world to your location function

I assumed so.
