### ISSUE TITLE
 An error I don't understand

### ISSUE THREAD

**Issue by OverBrave** [SkriptLang/Skript#3466]
### Expected Behavior
I don't know. Everything was working fine until the last version.

### Errors / Screenshots
```
[20:25:47] [Server thread/WARN]: Entity threw exception at world:-946.3970676102742,111.21910711822636,2023.6288189805473
[20:25:47] [Server thread/WARN]: java.lang.NullPointerException
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.Explosion.a(Explosion.java:141)
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.World.createExplosion(World.java:933)
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.WorldServer.createExplosion(WorldServer.java:2084)
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.World.createExplosion(World.java:927)
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.EntityTNTPrimed.explode(EntityTNTPrimed.java:114)
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.EntityTNTPrimed.tick(EntityTNTPrimed.java:73)
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.WorldServer.entityJoinedWorld(WorldServer.java:1300)
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.WorldServer$$Lambda$5426/0000000000000000.accept(Unknown Source)
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.World.a(World.java:900)
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:959)
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1429)
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:381)
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1280)
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1006)
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[20:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3137/0000000000000000.run(Unknown Source)
[20:25:47] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)

[20:26:15] [Server thread/ERROR]: #!#! 
[20:26:15] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[20:26:15] [Server thread/ERROR]: #!#! 
[20:26:15] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[20:26:15] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:26:15] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:26:15] [Server thread/ERROR]: #!#! Here is full list of them:
[20:26:15] [Server thread/ERROR]: #!#! RollbackCore v3.4.3-BETA skript-mirror v2.0.0-SNAPSHOT (https://github.com/btk5h/skript-mirror) Vixio v2.0.7 (http://vixio.space) skDragon v0.16 SkQuery v4.1.3 Skellett v1.9.9 (https://forums.skunity.com/resources/skellett.24/) skript-placeholders v1.4 (https://github.com/APickledWalrus/skript-placeholders) 
[20:26:15] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:26:15] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:26:15] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:26:15] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:26:15] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:26:15] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:26:15] [Server thread/ERROR]: #!#! 
[20:26:15] [Server thread/ERROR]: #!#! Stack trace:
[20:26:15] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: x not finite
[20:26:15] [Server thread/ERROR]: #!#!     at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118)
[20:26:15] [Server thread/ERROR]: #!#!     at org.bukkit.util.Vector.checkFinite(Vector.java:814)
[20:26:15] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R2.entity.CraftEntity.setVelocity(CraftEntity.java:424)
[20:26:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffPush.execute(EffPush.java:81)
[20:26:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[20:26:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:26:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[20:26:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[20:26:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:154)
[20:26:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112)
[20:26:15] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:26:15] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:26:15] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1217)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PacketPlayInFlying.a(SourceFile:122)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PlayerConnectionUtils$$Lambda$6175/0000000000000000.run(Unknown Source)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1203)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1196)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1172)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1016)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[20:26:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3137/0000000000000000.run(Unknown Source)
[20:26:15] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Unknown Source)
[20:26:15] [Server thread/ERROR]: #!#! 
[20:26:15] [Server thread/ERROR]: #!#! Version Information:
[20:26:15] [Server thread/ERROR]: #!#!   Skript: 2.5 (latest)
[20:26:15] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[20:26:15] [Server thread/ERROR]: #!#!     Date: 2020-09-24
[20:26:15] [Server thread/ERROR]: #!#!   Bukkit: 1.16.3-R0.1-SNAPSHOT
[20:26:15] [Server thread/ERROR]: #!#!   Minecraft: 1.16.3
[20:26:15] [Server thread/ERROR]: #!#!   Java: 11.0.8 (Eclipse OpenJ9 VM openj9-0.21.0)
[20:26:15] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.10.0-1127.19.1.el7.x86_64
[20:26:15] [Server thread/ERROR]: #!#! 
[20:26:15] [Server thread/ERROR]: #!#! Server platform: Paper
[20:26:15] [Server thread/ERROR]: #!#! 
[20:26:15] [Server thread/ERROR]: #!#! Current node: null
[20:26:15] [Server thread/ERROR]: #!#! Current item: push loop-player dir fr to at speed {smashdamage::%loop-player%}(as java.lang.Number) / [[long:13]]
[20:26:15] [Server thread/ERROR]: #!#! Current trigger: any move (simple event) (scsmash.sk, line 162)
[20:26:15] [Server thread/ERROR]: #!#! 
[20:26:15] [Server thread/ERROR]: #!#! Thread: Server thread
[20:26:15] [Server thread/ERROR]: #!#! 
[20:26:15] [Server thread/ERROR]: #!#! Language: english
[20:26:15] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[20:26:15] [Server thread/ERROR]: #!#! 
[20:26:15] [Server thread/ERROR]: #!#! End of Error.
[20:26:15] [Server thread/ERROR]: #!#! 

[20:27:24] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Purpur-786 (MC: 1.16.3) ---
[20:27:24] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[20:27:24] [Paper Watchdog Thread/ERROR]: ------------------------------
[20:27:24] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[20:27:24] [Paper Watchdog Thread/ERROR]: Ticking entity: minecraft:tnt
[20:27:24] [Paper Watchdog Thread/ERROR]: Position: world: 'world' at location (-918.1334685996301, 80.20014524847923, 1985.901501170954)
[20:27:24] [Paper Watchdog Thread/ERROR]: Velocity: (-0.002491778649839282, 0.1568000029206276, 0.019440962917515306) (in blocks per tick)
[20:27:24] [Paper Watchdog Thread/ERROR]: UUID: 998b664e-9520-49b4-85f2-39c00c68c85d
[20:27:24] [Paper Watchdog Thread/ERROR]: ------------------------------
[20:27:24] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[20:27:24] [Paper Watchdog Thread/ERROR]: 	PID: 33 | Suspended: false | Native: false | State: RUNNABLE
[20:27:24] [Paper Watchdog Thread/ERROR]: 	Stack:
[20:27:24] [Paper Watchdog Thread/ERROR]: 		java.base/java.lang.String.valueOf(Unknown Source)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.Variable.getRaw(Variable.java:281)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.Variable.get(Variable.java:288)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.Variable.getConverted(Variable.java:432)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.Variable.getAll(Variable.java:661)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.Variable.getArray(Variable.java:653)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.VariableString.toString(VariableString.java:465)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.Variable.getRaw(Variable.java:276)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.Variable.get(Variable.java:288)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.Variable.getConverted(Variable.java:432)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.Variable.getAll(Variable.java:661)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.conditions.CondIsSet.check(CondIsSet.java:75)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.conditions.CondIsSet.check(CondIsSet.java:81)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.While.walk(While.java:48)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:90)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.function.Function.execute(Function.java:136)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:266)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:53)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.Effect.run(Effect.java:52)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:154)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.Explosion.a(Explosion.java:260)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.World.createExplosion(World.java:934)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldServer.createExplosion(WorldServer.java:2084)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.World.createExplosion(World.java:927)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.EntityTNTPrimed.explode(EntityTNTPrimed.java:114)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.EntityTNTPrimed.tick(EntityTNTPrimed.java:73)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldServer.entityJoinedWorld(WorldServer.java:1300)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldServer$$Lambda$5426/0000000000000000.accept(Unknown Source)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.World.a(World.java:900)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:959)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1429)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:381)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1280)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1006)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3137/0000000000000000.run(Unknown Source)
[20:27:24] [Paper Watchdog Thread/ERROR]: 		java.base/java.lang.Thread.run(Unknown Source)
[20:27:24] [Paper Watchdog Thread/ERROR]: ------------------------------
[20:27:24] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[20:27:24] [Paper Watchdog Thread/ERROR]: ------------------------------
```

After this error, server crashed.

### Server Information
* **Server version/platform:** 
![image](https://user-images.githubusercontent.com/47111280/95779943-b210a480-0cd3-11eb-892b-2bacc16e60f0.png)

* **Skript version:** 
![image](https://user-images.githubusercontent.com/47111280/95779916-a4f3b580-0cd3-11eb-9a1d-d7827fead419.png)

Code:
````
on any move:
	"%region at player%" contains "scsmash"
	metadata value "scdouble" of player is true:
		player is sneaking:
			player's gamemode is survival
			block 2 below player is air
			play sound "entity_ender_dragon_flap" with volume 10 at player
			push player downwards at speed 0.3
			set metadata value "scsmash" of player to true
		player is on the ground:
			if metadata value "scsmash" of player is true:
				scsmash(player)
				set metadata value "scdouble" of player to false
				loop players in radius 5 of the player:
					loop-player is not player:
						if {smashdamage::%loop-player%} >= 125:
							push loop-player (direction from player to loop-player) at speed 10
							push loop-player upward at speed 10
						else:
							push loop-player (direction from player to loop-player) at speed ({smashdamage::%loop-player%} / 13)
							push loop-player upward at speed ({smashdamage::%loop-player%} / 13)
```

**Comment by ShaneBeee** [comment]
Im not really sure what is going on here, but it seems like you're maybe trying to execute your code too often.
Possibly creating an excessive loop.
Based on the error:
```
java.lang.IllegalArgumentException: x not finite
at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118)
```
It appears a vector is not properly being created.

This is one of the many reasons SkQuery's `on any movement` event is highly discouraged. 

My guess is this is a combination of poorly executed code (ie: user error), and excessive looping/executing of tasks.

**Comment by OverBrave** [comment]
Yes, I made a lot of improvement in the overall code yesterday, I made a special change in this issue.
I hope it doesn't get the same error, if the problem is not due to skript you can close the thread.
