### ISSUE TITLE
Skript Errror Spam at random times

### ISSUE THREAD

**Issue by torisetDev** [SkriptLang/Skript#3468]
Server Version: 1.16.3
Skript Version: 2.5
Error:
[05:01:19] [Craft Scheduler Thread - 159/WARN]: [Skript] Plugin Skript v2.5 generated an exception while executing task 8857
java.lang.IllegalArgumentException: World unloaded
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.3.jar:git-Paper-206]
	at org.bukkit.Location.getWorld(Location.java:112) ~[patched_1.16.3.jar:git-Paper-206]
	at ch.njol.skript.classes.data.BukkitClasses$7.serialize(BukkitClasses.java:416) ~[?:?]
	at ch.njol.skript.classes.data.BukkitClasses$7.serialize(BukkitClasses.java:1) ~[?:?]
	at ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:179) ~[?:?]
	at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:250) ~[?:?]
	at ch.njol.skript.registrations.Classes.serialize(Classes.java:707) ~[?:?]
	at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:439) ~[?:?]
	at ch.njol.skript.variables.FlatFileStorage.saveVariables(FlatFileStorage.java:387) ~[?:?]
	at ch.njol.skript.variables.FlatFileStorage$1.run(FlatFileStorage.java:199) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-206]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-206]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-206]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_265]

Likely cause: Multiverse-Core plugin
Can someone help me how to fix or know what this error means?

**Comment by ShaneBeee** [comment]
It appears the world you're trying to access is currently unloaded:
```
java.lang.IllegalArgumentException: World unloaded
```

**Comment by ShaneBeee** [comment]
Closing due to lack of information and lack of response
