### ISSUE TITLE
I keep getting errors all of a sudden.

### ISSUE THREAD

**Issue by Mooner510** [SkriptLang/Skript#3469]
#**Sorry,,, I am not good at English.. because I am Korean... :(**

### Description
At some point, I reloaded it back and it keeps printing this error.

### Steps to Reproduce
I did reload,,..

### Errors / Screenshots
```
[22:26:32 ERROR]: #!#!
[22:26:32 ERROR]: #!#! [Skript] Severe Error:
[22:26:32 ERROR]: #!#!
[22:26:32 ERROR]: #!#! Something went horribly wrong with Skript.
[22:26:32 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:26:32 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:26:32 ERROR]: #!#! Here is full list of them:
[22:26:32 ERROR]: #!#! skRayFall v1.9.20 (https://sk.rayfall.net/) Vixio v2.0.4 (http://vixio.space) TuSKe v1.8.2 (github.com/Tuke-Nuke/TuSKe) SK-NBeeT v2.11.1 (https://github.com/ShaneBeee/Sk-NBeeT) skDragon v0.16 SkStuff v1.6.4.1-fork-1.12 SkBee v1.6.0 (https://github.com/ShaneBeee/SkBee) skUtilities v0.9.2 (https://tim740.github.io/) skript-yaml v1.3.2 SkQuery v4.1.1 Skellett v1.9.8 (https://forums.skunity.com/resources/skellett.24/) SkChoke v1.1
[22:26:32 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[22:26:32 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:26:32 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:26:32 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:26:32 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:26:32 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[22:26:32 ERROR]: #!#!
[22:26:32 ERROR]: #!#! Stack trace:
[22:26:32 ERROR]: #!#! java.lang.ClassCastException: org.bukkit.event.hanging.HangingBreakEvent cannot be cast to org.bukkit.event.hanging.HangingBreakByEntityEvent
[22:26:32 ERROR]: #!#!     at com.morkaz.morkazsk.events.EvtHangingBreakByEntity$3.get(EvtHangingBreakByEntity.java:50)
[22:26:32 ERROR]: #!#!     at ch.njol.skript.registrations.EventValues$3.get(EventValues.java:259)
[22:26:32 ERROR]: #!#!     at ch.njol.skript.registrations.EventValues$3.get(EventValues.java:1)
[22:26:32 ERROR]: #!#!     at ch.njol.skript.expressions.base.EventValueExpression.getValue(EventValueExpression.java:101)
[22:26:32 ERROR]: #!#!     at ch.njol.skript.expressions.base.EventValueExpression.get(EventValueExpression.java:87)
[22:26:32 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101)
[22:26:32 ERROR]: #!#!     at ch.njol.skript.expressions.base.WrapperExpression.get(WrapperExpression.java:91)
[22:26:32 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:160)
[22:26:32 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:309)
[22:26:32 ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
[22:26:32 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:51)
[22:26:32 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[22:26:32 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[22:26:32 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:154)
[22:26:32 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112)
[22:26:32 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[22:26:32 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:26:32 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[22:26:32 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.EntityHanging.B_(EntityHanging.java:118)
[22:26:32 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1797)
[22:26:32 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.World.h(World.java:1767)
[22:26:32 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1574)
[22:26:32 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:682)
[22:26:32 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921)
[22:26:32 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[22:26:32 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[22:26:32 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[22:26:32 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[22:26:32 ERROR]: #!#!
[22:26:32 ERROR]: #!#! Version Information:
[22:26:32 ERROR]: #!#!   Skript: 2.5 (latest)
[22:26:32 ERROR]: #!#!     Flavor: skriptlang-github
[22:26:32 ERROR]: #!#!     Date: 2020-09-24
[22:26:32 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[22:26:32 ERROR]: #!#!   Minecraft: 1.12.2
[22:26:32 ERROR]: #!#!   Java: 1.8.0_261 (Java HotSpot(TM) 64-Bit Server VM 25.261-b12)
[22:26:32 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[22:26:32 ERROR]: #!#!
[22:26:32 ERROR]: #!#! Server platform: Paper
[22:26:32 ERROR]: #!#!
[22:26:32 ERROR]: #!#! Current node: null
[22:26:32 ERROR]: #!#! Current item: the block is equal to [[itemtype:wheat plant]] (comparator: ch.njol.skript.classes.data.DefaultComparators$6@5b7584ef)
[22:26:32 ERROR]: #!#! Current trigger: break (break/place/burn/fade/form of <none>) (farm.sk, line 67)
[22:26:32 ERROR]: #!#!
[22:26:32 ERROR]: #!#! Thread: Server thread
[22:26:32 ERROR]: #!#!
[22:26:32 ERROR]: #!#! Language: english
[22:26:32 ERROR]: #!#! Link parse mode: DISABLED
[22:26:32 ERROR]: #!#![22:26:32 ERROR]: #!#! End of Error.
[22:26:32 ERROR]: #!#!
```

### Server Informationre
Minecraft 1.12.2 paper bukkit

Use: Skript 2.5
Addons: SK-NBeeT 2.11.1, SkBee 1.6.0, SkChoke 1.1, SkQuery 4.1.1, SkStuff 1.6.4.1-fork-1.12, Skellett 1.9.8, skDragon 0.16, skRayFall 1.9.20, skript-npc 0.1.2, skript-yaml 1.3.2, TuSKe 1.8.2, Vixio 2.0.4, MorkazSk 1.2

**Comment by ShaneBeee** [comment]
Closing as this is not a Skript issue.
