### ISSUE TITLE
I cant open my mc server 

### ISSUE THREAD

**Issue by DM5748444** [SkriptLang/Skript#3503]
### Errors / Screenshots
[15:52:28 INFO]: [Skript] Enabling Skript v2.5.1
[15:52:28 ERROR]: [Skript] Could not load the new config from the jar file: plugins/Skript/config.sk (Permission denied)
[15:52:29 ERROR]: #!#!
[15:52:29 ERROR]: #!#! [Skript] Severe Error:
[15:52:29 ERROR]: #!#! Saving material registry failed!
[15:52:29 ERROR]: #!#!
[15:52:29 ERROR]: #!#! Something went horribly wrong with Skript.
[15:52:29 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:52:29 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[15:52:29 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[15:52:29 ERROR]: #!#!
[15:52:29 ERROR]: #!#! Stack trace:
[15:52:29 ERROR]: #!#! java.nio.file.AccessDeniedException: /home/onepiece/onepiece/plugins/Skript/materials.json
[15:52:29 ERROR]: #!#!     at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
[15:52:29 ERROR]: #!#!     at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[15:52:29 ERROR]: #!#!     at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[15:52:29 ERROR]: #!#!     at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
[15:52:29 ERROR]: #!#!     at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
[15:52:29 ERROR]: #!#!     at java.nio.file.Files.newOutputStream(Files.java:216)
[15:52:29 ERROR]: #!#!     at java.nio.file.Files.write(Files.java:3292)
[15:52:29 ERROR]: #!#!     at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:111)
[15:52:29 ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:140)
[15:52:29 ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:408)
[15:52:29 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:52:29 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[15:52:29 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[15:52:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[15:52:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[15:52:29 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[15:52:29 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[15:52:29 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[15:52:29 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[15:52:29 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[15:52:29 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[15:52:29 ERROR]: #!#!
[15:52:29 ERROR]: #!#! Version Information:
[15:52:29 ERROR]: #!#!   Skript: 2.5.1
[15:52:29 ERROR]: #!#!     Flavor: skriptlang-github
[15:52:29 ERROR]: #!#!     Date: 2020-10-22
[15:52:29 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[15:52:29 ERROR]: #!#!   Minecraft: 1.12.2
[15:52:29 ERROR]: #!#!   Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b03)
[15:52:29 ERROR]: #!#!   OS: Linux amd64 4.18.0-18-generic
[15:52:29 ERROR]: #!#!
[15:52:29 ERROR]: #!#! Server platform: Spigot
[15:52:29 ERROR]: #!#!
[15:52:29 ERROR]: #!#! Current node: null
[15:52:29 ERROR]: #!#! Current item: null
[15:52:29 ERROR]: #!#!
[15:52:29 ERROR]: #!#! Thread: Server thread
[15:52:29 ERROR]: #!#!
[15:52:29 ERROR]: #!#! Language: english
[15:52:29 ERROR]: #!#! Link parse mode: DISABLED
[15:52:29 ERROR]: #!#!
[15:52:29 ERROR]: #!#! End of Error.
[15:52:29 ERROR]: #!#!
[15:52:29 INFO]: [Skript] You're currently running the latest stable version of Skript.

**Comment by Romitou** [comment]
There seems to be a problem with the permission of your files. Check that they are correct.

**Comment by ShaneBeee** [comment]
As Romitou stated its a file issue on your machine.
Try deleting the materials file (as you can see in the error)
```
 java.nio.file.AccessDeniedException: /home/onepiece/onepiece/plugins/Skript/materials.json
```
Other than that, not much we can do.
