### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Perdume** [SkriptLang/Skript#3508]
[02:30:34 ERROR]: [Skript] 3 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1606)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[02:30:49 ERROR]: [Skript] 664 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

**Comment by ShaneBeee** [comment]
Closing due to lack of information.

When reporting issues, please fill in the issue template rather than deleting it.

Also, this is 99% an issue with running an outdated version of skript-mirror
