### ISSUE TITLE
first character expression doesn't work

### ISSUE THREAD

**Issue by rudde0** [SkriptLang/Skript#3585]
### Description
I couldn't use `first character of %text%` after the 2.5.2 update.

### Steps to Reproduce
```
command /mystring <text>:
	trigger:
		set {_f} to first character of arg 1
		send {_f}
```
try parse this code.

### Errors
```
[11:06:44 ERROR]: #!#!
[11:06:44 ERROR]: #!#! [Skript] Severe Error:
[11:06:44 ERROR]: #!#! Could not load ds.sk
[11:06:44 ERROR]: #!#!
[11:06:44 ERROR]: #!#! Something went horribly wrong with Skript.
[11:06:44 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:06:44 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[11:06:44 ERROR]: #!#! Here is full list of them:
[11:06:44 ERROR]: #!#! skRayFall v1.9.23 (https://sk.rayfall.net/) skript-reflect v2.1.0 (https://github.com/TPGamesNL/skript-reflect) TuSKe v1.8.2-Pikachu-Patch-3 (github.com/Tuke-Nuke/TuSKe) skript-gui v1.1.0 (https://github.com/APickledWalrus/skript-gui) MundoSK-Async v0.1.0 skDragon v0.17 ThatPacketAddon v1.0-BETA.3 (tlatoani.us/thatpacketaddon) SkBee v1.8.1 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.3.3 SkQuery v4.1.4 skript-placeholders v1.3.1 (https://github.com/APickledWalrus/skript-placeholders) AuctionMaster v3.4.0.0
[11:06:44 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[11:06:44 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[11:06:44 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[11:06:44 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[11:06:44 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[11:06:44 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[11:06:44 ERROR]: #!#!
[11:06:44 ERROR]: #!#! Stack trace:
[11:06:44 ERROR]: #!#! java.lang.NullPointerException
[11:06:44 ERROR]: #!#!     at ch.njol.skript.expressions.ExprSubstring.isSingle(ExprSubstring.java:108)
[11:06:44 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.init(EffChange.java:249)
[11:06:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:251)
[11:06:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[11:06:44 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:58)
[11:06:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1030)
[11:06:44 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:486)
[11:06:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:636)
[11:06:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[11:06:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[11:06:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:464)
[11:06:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:976)
[11:06:44 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:185)
[11:06:44 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:06:44 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[11:06:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802)
[11:06:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:764)
[11:06:44 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:421)
[11:06:44 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:388)
[11:06:44 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1280)
[11:06:44 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006)
[11:06:44 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[11:06:44 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[11:06:44 ERROR]: #!#!
[11:06:44 ERROR]: #!#! Version Information:
[11:06:44 ERROR]: #!#!   Skript: 2.5.2
[11:06:44 ERROR]: #!#!     Flavor: skriptlang-github
[11:06:44 ERROR]: #!#!     Date: 2020-11-28
[11:06:44 ERROR]: #!#!   Bukkit: 1.16.4-R0.1-SNAPSHOT
[11:06:44 ERROR]: #!#!   Minecraft: 1.16.4
[11:06:44 ERROR]: #!#!   Java: 1.8.0_271 (Java HotSpot(TM) 64-Bit Server VM 25.271-b09)
[11:06:44 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[11:06:44 ERROR]: #!#!
[11:06:44 ERROR]: #!#! Server platform: Paper
[11:06:44 ERROR]: #!#!
[11:06:44 ERROR]: #!#! Current node: set {_f} to first character of arg 1 (ds.sk, line 48)
[11:06:44 ERROR]: #!#! Current item: null
[11:06:44 ERROR]: #!#!
[11:06:44 ERROR]: #!#! Thread: Server thread
[11:06:44 ERROR]: #!#!
[11:06:44 ERROR]: #!#! Language: english
[11:06:44 ERROR]: #!#! Link parse mode: STRICT
[11:06:44 ERROR]: #!#!
[11:06:44 ERROR]: #!#! End of Error.
[11:06:44 ERROR]: #!#!
```

### Server Information
* **Server version/platform:** git-Purpur-817 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT) (Paper fork)
* **Skript version:** 2.5.2

### Additional Context
`(first 2 characters of {_t})` is throwing same error too

**Comment by Govindass** [comment]
I am getting the same error, however if I remove all addons, it works

**Comment by Govindass** [comment]
also what's MundoSK-Async v0.1.0?

**Comment by ShaneBeee** [comment]
can confirm

**Comment by bloggy** [comment]
Same error here since this version. Hope for a quick fix ...

**Comment by Govindass** [comment]
> Same error here since this version. Hope for a quick fix ...

ShaneBee has sent a fixed jarfile in Skript Chat discord

**Comment by Mikimoka** [comment]
I need that fixed jar file too

**Comment by ShaneBeee** [comment]
here is the nightly:
https://github.com/SkriptLang/Skript/actions/runs/394155965

Just a heads up, these builds are NOT supported, use with caution

**Comment by Romitou** [comment]
You can download the Nightly Build of the fix here: https://github.com/SkriptLang/Skript/actions/runs/389888430
