### ISSUE TITLE
 "Do you have an Internet connection?" v2.5.2 (latest)

### ISSUE THREAD

**Issue by NameIsCam** [SkriptLang/Skript#3592]
### Description
I don't know how to describe besides "Do you have an Internet connection?" Sorry, that's the best I can describe it as.

### Steps to Reproduce
Startup your server with Skript installed (the only plugin installed), start server, the error is produced (right after script says enabled). Please, note that I've tried this with plugins, without plugins, redownloaded Skript, less I'm getting something wrong.

### Expected Behavior
No error? I guess.

### Errors / Screenshots
[Skript] Checking for updates failed. Do you have Internet connection? (brewing.sk, line 3: (bottle[s] of water|water bottleªs) = minecraft:potion {"Potion": "minecraft:water"}')
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/SkriptLang/Skript/releases
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]: Caused by: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/SkriptLang/Skript/releases
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]:     at ch.njol.skript.update.GithubChecker.lambda$0(GithubChecker.java:114)
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]:     ... 6 more
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]: Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/SkriptLang/Skript/releases
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]:     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]:     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]:     at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.net.URL.openStream(Unknown Source)
[17:07:52] [ForkJoinPool.commonPool-worker-1/WARN]:     at ch.njol.skript.update.GithubChecker.lambda$0(GithubChecker.java:108)

### Server Information
* **Server version/platform:** spigot-1.16.2
* **Skript version:** v2.5.2

### Additional Context
If I did not fill out anything properly, please let me know and I'll fix it, or if this is a waste of your time and it's a problem that I'm causing.

**Comment by ShaneBeee** [comment]
I can not replicate this issue.
Are you still having this issue?

It appears your server is having an issue connecting to the GitHub API to check for updates.
If the problem persists, you can disable update checks in the Skript config.

**Comment by TPGamesNL** [comment]
Closing due to lack of response
