### ISSUE TITLE
error

### ISSUE THREAD

**Issue by haveadooday** [SkriptLang/Skript#3598]
13:57:45] [Server thread/ERROR]: #!#! 
[13:57:45] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[13:57:45] [Server thread/ERROR]: #!#! 
[13:57:45] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[13:57:45] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:57:45] [Server thread/ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[13:57:45] [Server thread/ERROR]: #!#! Run /sk update check to get a download link to latest Skript!
[13:57:45] [Server thread/ERROR]: #!#! You will be given instructions how to report this error if it persists after update.
[13:57:45] [Server thread/ERROR]: #!#! 
[13:57:45] [Server thread/ERROR]: #!#! Stack trace:
[13:57:45] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: Serializer of region must override newInstance(), canBeInstantiated() or mustSyncDeserialization() if its class does not have a nullary constructor
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.Serializer.newInstance(Serializer.java:80)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.yggdrasil.Yggdrasil.newInstance(Yggdrasil.java:340)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.yggdrasil.Yggdrasil.isSerializable(Yggdrasil.java:155)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:167)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:247)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.serialize(Classes.java:708)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.Variables.serialize(Variables.java:531)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.Variables.serialize(Variables.java:524)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.Variables.saveVariableChange(Variables.java:535)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.Variables.setVariable(Variables.java:367)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.Variables.setVariable(Variables.java:358)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Variable.set(Variable.java:419)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Variable.change(Variable.java:479)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.hooks.regions.events.EvtRegionBorder.callEvent(EvtRegionBorder.java:137)
[13:57:45] [Server thread/ERROR]: #!#!     at ch.njol.skript.hooks.regions.events.EvtRegionBorder$3.execute(EvtRegionBorder.java:166)
[13:57:45] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[13:57:45] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:57:45] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[13:57:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:711)
[13:57:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126)
[13:57:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57)
[13:57:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[13:57:45] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[13:57:45] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[13:57:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[13:57:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[13:57:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[13:57:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[13:57:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[13:57:45] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[13:57:45] [Server thread/ERROR]: #!#! 
[13:57:45] [Server thread/ERROR]: #!#! Version Information:
[13:57:45] [Server thread/ERROR]: #!#!   Skript: 2.4.1 (OUTDATED)
[13:57:45] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[13:57:45] [Server thread/ERROR]: #!#!     Date: 2019-12-22
[13:57:45] [Server thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[13:57:45] [Server thread/ERROR]: #!#!   Minecraft: 1.12.2
[13:57:45] [Server thread/ERROR]: #!#!   Java: 1.8.0_271 (Java HotSpot(TM) 64-Bit Server VM 25.271-b09)
[13:57:45] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:57:45] [Server thread/ERROR]: #!#! 
[13:57:45] [Server thread/ERROR]: #!#! Server platform: Paper
[13:57:45] [Server thread/ERROR]: #!#! 
[13:57:45] [Server thread/ERROR]: #!#! Current node: null
[13:57:45] [Server thread/ERROR]: #!#! Current item: set {Region::%the UUID of the player%}(as java.lang.Object) to the region
[13:57:45] [Server thread/ERROR]: #!#! Current trigger: region enter (enter of a region) (지역 채팅.sk, line 8)
[13:57:45] [Server thread/ERROR]: #!#! 
[13:57:45] [Server thread/ERROR]: #!#! Thread: Server thread
[13:57:45] [Server thread/ERROR]: #!#! 
[13:57:45] [Server thread/ERROR]: #!#! Language: english
[13:57:45] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[13:57:45] [Server thread/ERROR]: #!#! 
[13:57:45] [Server thread/ERROR]: #!#! End of Error.
[13:57:45] [Server thread/ERROR]: #!#!

**Comment by ShaneBeee** [comment]
` Skript: 2.4.1 (OUTDATED)` <-- we do not support outdated versions.
