### ISSUE TITLE
The Skript Plugin is not loading for me | Please Help

### ISSUE THREAD

**Issue by Williampayr** [SkriptLang/Skript#3604]
[Skript] Enabling Skript v2.5.2
[Server thread/ERROR]: Error occurred while enabling Skript v2.5.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
at ch.njol.skript.util.Utils.<clinit>(Utils.java:477) ~[?:?]
at ch.njol.skript.util.Version.<init>(Version.java:64) ~[?:?]
at ch.njol.skript.Skript.onEnable(Skript.java:300) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[craftbukkit.jar:git-Bukkit-3eb7236]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343) ~[craftbukkit.jar:git-Bukkit-3eb7236]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[craftbukkit.jar:git-Bukkit-3eb7236]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:480) ~[craftbukkit.jar:git-Bukkit-3eb7236]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[craftbukkit.jar:git-Bukkit-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:426) ~[craftbukkit.jar:git-Bukkit-3eb7236]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:205) ~[craftbukkit.jar:git-Bukkit-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:786) ~[craftbukkit.jar:git-Bukkit-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:155) ~[craftbukkit.jar:git-Bukkit-3eb7236]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

Someone please help

**Comment by ShaneBeee** [comment]
Craftbukkit is not supported.
