### ISSUE TITLE
Skript bugs in tuinity bukkit

### ISSUE THREAD

**Issue by strawcream** [SkriptLang/Skript#3653]
### Description

skript plugin fails with reduced TPS.

### Steps to Reproduce

Replacement from spigot to durity-paperclip succeeded.

### Expected Behavior

It had to be done without error.
### Errors / Screenshots

[04:41:08 ERROR]: [Skript] Checking for updates failed. Do you have Internet connection?
[04:41:08 WARN]: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.net.ConnectException: Connection timed out (
Connection timed out)
[04:41:08 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
[04:41:08 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
[04:41:08 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
[04:41:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[04:41:08 WARN]: Caused by: java.lang.RuntimeException: java.net.ConnectException: Connection timed out (Connection timed out)
[04:41:08 WARN]:        at ch.njol.skript.update.GithubChecker.lambda$0(GithubChecker.java:114)
[04:41:08 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
[04:41:08 WARN]:        ... 1 more
[04:41:08 WARN]: Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
[04:41:08 WARN]:        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
[04:41:08 WARN]:        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
[04:41:08 WARN]:        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
[04:41:08 WARN]:        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
[04:41:08 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
[04:41:08 WARN]:        at java.base/java.net.Socket.connect(Socket.java:609)
[04:41:08 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
[04:41:08 WARN]:        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[04:41:08 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[04:41:08 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
[04:41:08 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
[04:41:08 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[04:41:08 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
[04:41:08 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttp
sURLConnection.java:191)
[04:41:08 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
[04:41:08 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
[04:41:08 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[04:41:08 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
[04:41:08 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[04:41:08 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[04:41:08 WARN]:        at java.base/java.net.URL.openStream(URL.java:1140)
[04:41:08 WARN]:        at ch.njol.skript.update.GithubChecker.lambda$0(GithubChecker.java:108)
[04:41:08 WARN]:        ... 2 more
[04:41:17 ERROR]: [Skript] Checking for updates failed. Do you have Internet connection?
[04:41:17 WARN]: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.net.ConnectException: Connection timed out (Connection timed out)
[04:41:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
[04:41:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
[04:41:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
[04:41:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[04:41:17 WARN]: Caused by: java.lang.RuntimeException: java.net.ConnectException: Connection timed out (Connection timed out)
[04:41:17 WARN]:        at ch.njol.skript.update.GithubChecker.lambda$0(GithubChecker.java:114)
[04:41:17 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
[04:41:17 WARN]:        ... 1 more
[04:41:17 WARN]: Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
[04:41:17 WARN]:        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
[04:41:17 WARN]:        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
[04:41:17 WARN]:        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
[04:41:17 WARN]:        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
[04:41:17 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
[04:41:17 WARN]:        at java.base/java.net.Socket.connect(Socket.java:609)
[04:41:17 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
[04:41:17 WARN]:        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[04:41:17 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[04:41:17 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
[04:41:17 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
[04:41:17 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[04:41:17 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
[04:41:17 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[04:41:17 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
[04:41:17 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
[04:41:17 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[04:41:17 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
[04:41:17 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[04:41:17 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[04:41:17 WARN]:        at java.base/java.net.URL.openStream(URL.java:1140)
[04:41:17 WARN]:        at ch.njol.skript.update.GithubChecker.lambda$0(GithubChecker.java:108)
[04:41:17 WARN]:        ... 2 more

### Server Information
* **Server version/platform:**  tuinity-paperclip 1.16.4
* **Skript version:**  2.5.3

### Additional Context

system info:
OS: Debian
bukkit: tuinity-paperclip 1.16.4
skript version: 2.5.3
I use GCP(Google Cloud Platform
RAM: 8GB
Internet connection status: Yes

**Comment by ham1255** [comment]
this connection issue to github? like is like unable to get version check

**Comment by TPGamesNL** [comment]
Are you still having this issue?

**Comment by TPGamesNL** [comment]
Closing due to lack of response
