### ISSUE TITLE
on right click event.

### ISSUE THREAD

**Issue by Silverless** [SkriptLang/Skript#3655]
### Description
I just clicked grind stone and I got no gravity

### Steps to Reproduce
```vb
This is my skript.
on right click on grindstone:
    if facing of block is north:
        cancel event
        spawn a snowball 2.2 meters below the event-block
        add "{NoGravity:1b,Rotation:[0F,-180F]}" to entity-nbt of event-entity
        push event-entity forwards at speed 0.5
        make the player ride event-entity
        wait 3 seconds
        push event-entity forwards at speed 0.5
    if facing of block is south:
        cancel event
        spawn a snowball 2.2 meters below the event-block
        add "{NoGravity:1b,Rotation:[0F,180F]}" to entity-nbt of event-entity
        push event-entity backwards at speed 0.5
        make the player ride event-entity
        wait 3 seconds
        push event-entity forwards at speed 0.5
    if facing of block is east:
        cancel event
        spawn a snowball 2.2 meters below the event-block
        add "{NoGravity:1b,Rotation:[-90F,0F]}" to entity-nbt of event-entity
        push event-entity forwards at speed 0.5
        make the player ride event-entity
        wait 3 seconds
        push event-entity forwards at speed 0.5
    if facing of block is west:
        cancel event
        spawn a snowball 2.2 meters below the event-block
        add "{NoGravity:1b,Rotation:[90F,0F]}" to entity-nbt of event-entity
        push event-entity forwards at speed 0.5
        make the player ride event-entity
        wait 3 seconds
        push event-entity forwards at speed 0.5
```

### Expected Behavior
spawn no gravity snow ball and player sit on event entity(snowball). after spawn, snowball will push to forward.

### Errors / Screenshots
[18:48:27 ERROR]: #!#!
[18:48:27 ERROR]: #!#! [Skript] Severe Error:
[18:48:27 ERROR]: #!#!
[18:48:27 ERROR]: #!#! Something went horribly wrong with Skript.
[18:48:27 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[18:48:27 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[18:48:27 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[18:48:27 ERROR]: #!#!
[18:48:27 ERROR]: #!#! Stack trace:
[18:48:27 ERROR]: #!#! java.lang.IllegalArgumentException: Entities cannot become a passenger of themselves
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.Entity.addPassenger(Entity.java:2046)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.Entity.a(Entity.java:2008)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.EntityPlayer.a(EntityPlayer.java:1188)
[18:48:27 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.addPassenger(CraftEntity.java:670)
[18:48:27 ERROR]: #!#!     at ch.njol.skript.bukkitutil.PassengerUtils.addPassenger(PassengerUtils.java:74)
[18:48:27 ERROR]: #!#!     at ch.njol.skript.effects.EffVehicle.execute(EffVehicle.java:96)
[18:48:27 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[18:48:27 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[18:48:27 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[18:48:27 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[18:48:27 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:153)
[18:48:27 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:111)
[18:48:27 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[18:48:27 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:48:27 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[18:48:27 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:464)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1536)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004)
[18:48:27 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[18:48:27 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[18:48:27 ERROR]: #!#!
[18:48:27 ERROR]: #!#! Version Information:
[18:48:27 ERROR]: #!#!   Skript: 2.5.3 (latest)
[18:48:27 ERROR]: #!#!     Flavor: skriptlang-github
[18:48:27 ERROR]: #!#!     Date: 2020-12-11
[18:48:27 ERROR]: #!#!   Bukkit: 1.16.4-R0.1-SNAPSHOT
[18:48:27 ERROR]: #!#!   Minecraft: 1.16.4
[18:48:27 ERROR]: #!#!   Java: 1.8.0_271 (Java HotSpot(TM) 64-Bit Server VM 25.271-b09)
[18:48:27 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[18:48:27 ERROR]: #!#!
[18:48:27 ERROR]: #!#! Server platform: Paper
[18:48:27 ERROR]: #!#!
[18:48:27 ERROR]: #!#! Current node: null
[18:48:27 ERROR]: #!#! Current item: make the player ride event-entity
[18:48:27 ERROR]: #!#! Current trigger: right click on grindstone (rightclick on [[itemtype:grindstone]]) (짚라인.sk, line 1)
[18:48:27 ERROR]: #!#!
[18:48:27 ERROR]: #!#! Thread: Server thread
[18:48:27 ERROR]: #!#!
[18:48:27 ERROR]: #!#! Language: english
[18:48:27 ERROR]: #!#! Link parse mode: DISABLED
[18:48:27 ERROR]: #!#!
[18:48:27 ERROR]: #!#! End of Error.
[18:48:27 ERROR]: #!#!
If you have console errors, copy them to a paste service which won't delete them.
DON'T use Hastebin!

sry man

### Server Information
* **Server version/platform: Paper, 1.16.4
* **Skript version:  2.5.3

**Comment by ShaneBeee** [comment]
Your code:
```vb
make the player ride event-entity
```
Error:
```
Entities cannot become a passenger of themselves
```

You are trying to make the player ride themselves
