### ISSUE TITLE
Skript Error

### ISSUE THREAD

**Issue by xAwice** [SkriptLang/Skript#3682]
### Description
im not sure but skript isnt working

### Steps to Reproduce
It happened out of nowhere when I restarted the server

### Expected Behavior
worked normally

### Errors / Screenshots
[12:15:29 ERROR]: #!#! Stack trace:
[12:15:29 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for lambda
[12:15:29 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:262)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1837)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1804)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1552)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:323)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:640)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:259)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:163)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:499)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:839)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1568)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:58)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1030)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:678)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$3(ScriptLoader.java:337)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:370)
[12:15:29 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:601)
[12:15:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[12:15:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[12:15:29 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:945)
[12:15:29 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[12:15:29 ERROR]: #!#! 
[12:15:29 ERROR]: #!#! Version Information:
[12:15:29 ERROR]: #!#!   Skript: 2.5.3 (latest)
[12:15:29 ERROR]: #!#!     Flavor: skriptlang-github
[12:15:29 ERROR]: #!#!     Date: 2020-12-11
[12:15:29 ERROR]: #!#!   Bukkit: 1.16.4-R0.1-SNAPSHOT
[12:15:29 ERROR]: #!#!   Minecraft: 1.16.4
[12:15:29 ERROR]: #!#!   Java: 1.8.0_252 (OpenJDK 64-Bit Server VM 25.252-b09)
[12:15:29 ERROR]: #!#!   OS: Linux amd64 5.4.0-52-generic
[12:15:29 ERROR]: #!#! 
[12:15:29 ERROR]: #!#! Server platform: Paper
[12:15:29 ERROR]: #!#! 
[12:15:29 ERROR]: #!#! Current node: broadcast "&c%player% activated a black hole!" (Bomb.sk, line 2)
[12:15:29 ERROR]: #!#! Current item: null
[12:15:29 ERROR]: #!#! 
[12:15:29 ERROR]: #!#! Thread: Server thread
[12:15:29 ERROR]: #!#! 
[12:15:29 ERROR]: #!#! Language: english
[12:15:29 ERROR]: #!#! Link parse mode: DISABLED
[12:15:29 ERROR]: #!#! 
[12:15:29 ERROR]: #!#! End of Error.

**Comment by ShaneBeee** [comment]
Please try replicating this issue without any addons installed.
From what I've seen in the past, this issue is caused by SkQuery.

**Comment by JosheSalazar** [comment]
It helps, I don't know why this comes out



[WARNING] [Skript] Task #25 for Skript v2.2-dev25 generated an exception
java.lang.NoSuchMethodError: com/sk89q/worldguard/bukkit/WorldGuardPlugin.getFlagRegistry()Lcom/sk89q/worldguard/protection/flags/registry/FlagRegistry; (loaded from file:/home/gs-40843/plugins/WorldGuard.jar by org.bukkit.plugin.java.PluginClassLoader@c49fc17) called from class me.TheBukor.SkStuff.SkStuff$4 (loaded from file:/home/gs-40843/plugins/SkStuff.jar by org.bukkit.plugin.java.PluginClassLoader@69109ae5).

at me.TheBukor.SkStuff.SkStuff$4.parse(SkStuff.java:244) ~[?:?]

at me.TheBukor.SkStuff.SkStuff$4.parse(SkStuff.java:1) ~[?:?]

at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:422) ~[?:?]

at ch.njol.skript.registrations.Classes.parse(Classes.java:451) ~[?:?]

at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97) ~[?:?]

at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86) ~[?:?]

at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) ~[?:?]

at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:181) ~[?:?]

at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:132) ~[?:?]

at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249) ~[?:?]

at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176) ~[?:?]

at ch.njol.skript.lang.Condition.parse(Condition.java:83) ~[?:?]

at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:833) ~[?:?]

at ch.njol.skript.lang.Loop.<init>(Loop.java:68) ~[?:?]

at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:790) ~[?:?]

at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:53) ~[?:?]

at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:129) ~[?:?]

at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:485) ~[?:?]

at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247) ~[?:?]

at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201) ~[?:?]

at ch.njol.skript.Skript$2.run(Skript.java:406) ~[?:?]

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]

**Comment by ShaneBeee** [comment]
That error is from a super outdated version of Skript (which we no longer support) on a super outdated server versions... which we do not support.

**Comment by ShaneBeee** [comment]
Closing due to lack of response (the last response was not even using a version of Skript from the last year), and this issue is most likely from SkQuery
