### ISSUE TITLE
Item in loop-value not work.

### ISSUE THREAD

**Issue by knugi** [SkriptLang/Skript#3695]
### Description
If I wanted returned value with expression loop-value then returned value is null.
I set the loop-value in variable then returned value is correct.

### Steps to Reproduce
This code:
```vb
set {_x} to chest with 1 rows named "GUI Test"
set slot 0 of {_x} to stone named "Item Test"
open {_x} to player
wait 5 tick
set {_it::*} to all items out of current inventory
loop {_it::*}:
	send "%name of loop-value%"
	send "%item amount of loop-value%"
```
Returned errors in console.

### Expected Behavior
It will got me normal name of item and amount of it. When i replace this code to
```vb
set {_x} to chest with 1 rows named "GUI Test"
set slot 0 of {_x} to stone named "Item Test"
open {_x} to player
wait 5 tick
set {_it::*} to all items out of current inventory
loop {_it::*}:
	set {_loopValue} to loop-value
	send "%name of {_loopValue}%"
	send "%item amount of {_loopValue}%"
```
All is corrent and not receive error.
### Errors / Screenshots
'[21:03:32] [Server thread/ERROR]: #!#!
[21:03:32] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[21:03:32] [Server thread/ERROR]: #!#!
[21:03:32] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[21:03:32] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[21:03:32] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[21:03:32] [Server thread/ERROR]: #!#! Here is full list of them:
[21:03:32] [Server thread/ERROR]: #!#! skript-mirror v0.9.0 SkQuery v4.1.4
[21:03:32] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[21:03:32] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[21:03:32] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[21:03:32] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[21:03:32] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[21:03:32] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[21:03:32] [Server thread/ERROR]: #!#!
[21:03:32] [Server thread/ERROR]: #!#! Stack trace:
[21:03:32] [Server thread/ERROR]: #!#! java.lang.ClassCastException: org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemStack cannot be cast to ch.njol.skript.util.slot.Slot
[21:03:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprItemAmount.convert(ExprItemAmount.java:57)
[21:03:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprItemAmount.convert(ExprItemAmount.java:1)
[21:03:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:390)
[21:03:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:381)
[21:03:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:102)
[21:03:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.SimplePropertyExpression.get(SimplePropertyExpression.java:53)
[21:03:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:73)
[21:03:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:100)
[21:03:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getMessageComponents(VariableString.java:583)
[21:03:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:108)
[21:03:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[21:03:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[21:03:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[21:03:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:108)
[21:03:32] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
[21:03:32] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[21:03:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1059)
[21:03:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355)
[21:03:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1007)
[21:03:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:846)
[21:03:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[21:03:32] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[21:03:32] [Server thread/ERROR]: #!#!
[21:03:32] [Server thread/ERROR]: #!#! Version Information:
[21:03:32] [Server thread/ERROR]: #!#!   Skript: 2.5.3 (latest)
[21:03:32] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[21:03:32] [Server thread/ERROR]: #!#!     Date: 2020-12-11
[21:03:32] [Server thread/ERROR]: #!#!   Bukkit: 1.16.4-R0.1-SNAPSHOT
[21:03:32] [Server thread/ERROR]: #!#!   Minecraft: 1.16.4
[21:03:32] [Server thread/ERROR]: #!#!   Java: 1.8.0_201 (Java HotSpot(TM) 64-Bit Server VM 25.201-b09)
[21:03:32] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[21:03:32] [Server thread/ERROR]: #!#!
[21:03:32] [Server thread/ERROR]: #!#! Server platform: Spigot
[21:03:32] [Server thread/ERROR]: #!#!
[21:03:32] [Server thread/ERROR]: #!#! Current node: null
[21:03:32] [Server thread/ERROR]: #!#! Current item: send "%the item[[ ]stack] (amount|size|number) of loop-value%" to event-player/console
[21:03:32] [Server thread/ERROR]: #!#! Current trigger: command /s (simple event) (test.sk, line -1)
[21:03:32] [Server thread/ERROR]: #!#!
[21:03:32] [Server thread/ERROR]: #!#! Thread: Server thread
[21:03:32] [Server thread/ERROR]: #!#!
[21:03:32] [Server thread/ERROR]: #!#! Language: english
[21:03:32] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[21:03:32] [Server thread/ERROR]: #!#!
[21:03:32] [Server thread/ERROR]: #!#! End of Error.
[21:03:32] [Server thread/ERROR]: #!#!'

### Server Information
* **Server version/platform:**      git-Spigot-37d799b-3eb7236 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT) 
* **Skript version:** Skript version 2.5.3

**Comment by TPGamesNL** [comment]
Can confirm. I'll mark this as priority: low, since the workaround is quite easy.
