### ISSUE TITLE
So, Skript seems to sometimes crash my server with no error but sometimes gives me an error

### ISSUE THREAD

**Issue by StupidRepo** [SkriptLang/Skript#3702]
So, sometimes when I am playing, my server just crashes with no error.

Skript gives me this error sometimes:

```
[20:31:28 ERROR]: #!#! 
[20:31:28 ERROR]: #!#! [Skript] Severe Error:
[20:31:28 ERROR]: #!#! 
[20:31:28 ERROR]: #!#! Something went horribly wrong with Skript.
[20:31:28 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:31:28 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[20:31:28 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[20:31:28 ERROR]: #!#! 
[20:31:28 ERROR]: #!#! Stack trace:
[20:31:28 ERROR]: #!#! org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[20:31:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:537)
[20:31:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212)
[20:31:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:197)
[20:31:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:192)
[20:31:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:156)
[20:31:28 ERROR]: #!#!     at ch.njol.skript.effects.Delay.walk(Delay.java:90)
[20:31:28 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[20:31:28 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[20:31:28 ERROR]: #!#!     at ch.njol.skript.events.EvtScript.unregisterAll(EvtScript.java:74)
[20:31:28 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.removeAllTriggers(SkriptEventHandler.java:248)
[20:31:28 ERROR]: #!#!     at ch.njol.skript.Skript.disableScripts(Skript.java:972)
[20:31:28 ERROR]: #!#!     at ch.njol.skript.Skript.onDisable(Skript.java:1034)
[20:31:28 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[20:31:28 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415)
[20:31:28 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516)
[20:31:28 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502)
[20:31:28 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495)
[20:31:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:435)
[20:31:28 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:769)
[20:31:28 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:704)
[20:31:28 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1043)
[20:31:28 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
[20:31:28 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:832)
[20:31:28 ERROR]: #!#! 
[20:31:28 ERROR]: #!#! Version Information:
[20:31:28 ERROR]: #!#!   Skript: 2.5.3 (latest)
[20:31:28 ERROR]: #!#!     Flavor: skriptlang-github
[20:31:28 ERROR]: #!#!     Date: 2020-12-11
[20:31:28 ERROR]: #!#!   Bukkit: 1.16.4-R0.1-SNAPSHOT
[20:31:28 ERROR]: #!#!   Minecraft: 1.16.4
[20:31:28 ERROR]: #!#!   Java: 15.0.1 (Java HotSpot(TM) 64-Bit Server VM 15.0.1+9-18)
[20:31:28 ERROR]: #!#!   OS: Mac OS X x86_64 10.16
[20:31:28 ERROR]: #!#! 
[20:31:28 ERROR]: #!#! Server platform: Paper
[20:31:28 ERROR]: #!#! 
[20:31:28 ERROR]: #!#! Current node: null
[20:31:28 ERROR]: #!#! Current item: wait for [[timespan:0.05 seconds]]
[20:31:28 ERROR]: #!#! Current trigger: unload (script unload) (ScriptManager.sk, line 31)
[20:31:28 ERROR]: #!#! 
[20:31:28 ERROR]: #!#! Thread: Server thread
[20:31:28 ERROR]: #!#! 
[20:31:28 ERROR]: #!#! Language: english
[20:31:28 ERROR]: #!#! Link parse mode: DISABLED
[20:31:28 ERROR]: #!#! 
[20:31:28 ERROR]: #!#! End of Error.
[20:31:28 ERROR]: #!#! 

```

It seems Skript is crashing my server. Why is this happening?

It seems a Skript file is doing this so I will delete it and see if it makes a difference.

**Comment by StupidRepo** [comment]
No it doesn't make a difference, I gave it 6GB of ram and it insta-crashes

**Comment by ShaneBeee** [comment]
` org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled`
Looks to me that you are attempting to run a delay when the server is shutting down.

ie:
```vb
on unload:
    wait 1 tick
    send "CLOSING" to console
```
something like this will throw an error.

This has already been reported a few times already, the only issue i can find right now is #993 
Im going to close this as a duplicate as we are already aware of said issue.

But thank you for taking the time to report.
