### ISSUE TITLE
Error after skript 2.5.3 uploaded

### ISSUE THREAD

**Issue by TheGunTerminator** [SkriptLang/Skript#3718]
### Description
So I wanted to update my previous skript (still using 1.8), but when I uploaded the skript 2.5.3 it gave me a huge error 

### Steps to Reproduce
Just uploaded the .jar file to my plugin folder and then after the restart this happend

### Errors / Screenshots
`[22:15:55 ERROR]: #!#!
[22:15:55 ERROR]: #!#! [Skript] Severe Error:
[22:15:55 ERROR]: #!#! Skript's class ch.njol.skript.expressions.ExprSpawnerType generated an exception while loading
[22:15:55 ERROR]: #!#!
[22:15:55 ERROR]: #!#! Something went horribly wrong with Skript.
[22:15:55 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:15:55 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:15:55 ERROR]: #!#! Here is full list of them:
[22:15:55 ERROR]: #!#! Factions v1.6.9.5-2.6.2-STABLE
[22:15:55 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[22:15:55 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:15:55 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:15:55 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:15:55 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:15:55 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[22:15:55 ERROR]: #!#!
[22:15:55 ERROR]: #!#! Stack trace:
[22:15:55 ERROR]: #!#! java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[22:15:55 ERROR]: #!#!     at java.util.ArrayList.rangeCheck(Unknown Source)
[22:15:55 ERROR]: #!#!     at java.util.ArrayList.get(Unknown Source)
[22:15:55 ERROR]: #!#!     at ch.njol.skript.aliases.ItemType.getMaterial(ItemType.java:1243)
[22:15:55 ERROR]: #!#!     at ch.njol.skript.expressions.ExprSpawnerType.<clinit>(ExprSpawnerType.java:49)
[22:15:55 ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[22:15:55 ERROR]: #!#!     at java.lang.Class.forName(Unknown Source)
[22:15:55 ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107)
[22:15:55 ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:435)
[22:15:55 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[22:15:55 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[22:15:55 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411)
[22:15:55 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:352)
[22:15:55 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:311)
[22:15:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:428)
[22:15:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:392)
[22:15:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:347)
[22:15:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:276)
[22:15:55 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:594)
[22:15:55 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[22:15:55 ERROR]: #!#!
[22:15:55 ERROR]: #!#! Version Information:
[22:15:55 ERROR]: #!#!   Skript: 2.5.3 (latest)
[22:15:55 ERROR]: #!#!     Flavor: github-matocolotoe-1.8
[22:15:55 ERROR]: #!#!     Date: 2020-12-22
[22:15:55 ERROR]: #!#!   Bukkit: 1.8.8-R0.2-SNAPSHOT
[22:15:55 ERROR]: #!#!   Minecraft: 1.8.8
[22:15:55 ERROR]: #!#!   Java: 1.8.0_261 (Java HotSpot(TM) Client VM 25.261-b12)
[22:15:55 ERROR]: #!#!   OS: Windows 10 x86 10.0
[22:15:55 ERROR]: #!#!
[22:15:55 ERROR]: #!#! Server platform: Paper
[22:15:55 ERROR]: #!#!
[22:15:55 ERROR]: #!#! Current node: splash potions: (brewing.sk, line 51)
[22:15:55 ERROR]: #!#! Current item: null
[22:15:55 ERROR]: #!#!
[22:15:55 ERROR]: #!#! Thread: Server thread
[22:15:55 ERROR]: #!#!
[22:15:55 ERROR]: #!#! Language: english
[22:15:55 ERROR]: #!#! Link parse mode: DISABLED
[22:15:55 ERROR]: #!#!
[22:15:55 ERROR]: #!#! End of Error.
[22:15:55 ERROR]: #!#!`

### Server Information
* **Server version/platform:** Minecraft 1.8.8
* **Skript version:** 2.5.3

**Comment by ShaneBeee** [comment]
`Flavor: github-matocolotoe-1.8` <--
this isn't even our fork. Please report issues to the developer of said fork
