### ISSUE TITLE
Unable to install Skript, won't create final folder

### ISSUE THREAD

**Issue by JamesBakerHewitt** [SkriptLang/Skript#3723]
I've followed all the steps as I've been installing this for use with Skoice Proximity Chat. For some reason, it just won't install skript fully regardless of what I've tried. Any help would be greatful 

https://cdn.discordapp.com/attachments/741385977850757141/804023810944532550/19dc8c35d0c2393f71382d1e5285c1bc.png
https://cdn.discordapp.com/attachments/741385977850757141/804023834067861514/c9cf37e2b1bc59ffc99c61f52d2fbec3.png

Error given - https://cdn.discordapp.com/attachments/741385977850757141/804022339402334208/3e6b09af047fbf621a5c021e5584aa89.png

[17:15:14 ERROR]: Error occurred while enabling Skript v2.5.3 (Is it up to date?)
java.lang.AssertionError: java.lang.NoSuchFieldException: CREATE_ACACIA_WINDOW
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:808) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
        at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:834) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
        at com.google.gson.Gson.getAdapter(Gson.java:423) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
        at com.google.gson.internal.bind.ArrayTypeAdapter$1.create(ArrayTypeAdapter.java:48) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
        at com.google.gson.Gson.getAdapter(Gson.java:423) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
        at com.google.gson.Gson.toJson(Gson.java:661) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
        at com.google.gson.Gson.toJson(Gson.java:648) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
        at com.google.gson.Gson.toJson(Gson.java:603) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
        at com.google.gson.Gson.toJson(Gson.java:583) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
        at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:109) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:140) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at ch.njol.skript.Skript.onEnable(Skript.java:403) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:401) ~[forge:1.16.4-299] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:315) ~[forge:1.16.4-299] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:444) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:363) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:731) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:?] {}
Caused by: java.lang.NoSuchFieldException: CREATE_ACACIA_WINDOW
        at java.lang.Class.getField(Unknown Source) ~[?:?] {}
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:797) ~[server-1.16.4-20201102.104115-extra.jar:?] {}
        ... 22 more

**Comment by Romitou** [comment]
Try delete your `materials.json`, and retry.

**Comment by JamesBakerHewitt** [comment]
> Try delete your `materials.json`, and retry.

Where do I find that @Romitou ?

**Comment by TheDGOfficial** [comment]
> Try delete your `materials.json`, and retry.

^^ This, and also remove -ea or -enableassertions JVM argument if you have it on your startup script.



> > Try delete your `materials.json`, and retry.
> 
> Where do I find that @Romitou ?

It should be on plugins/Skript folder as far as I know.

**Comment by JamesBakerHewitt** [comment]
> > Try delete your `materials.json`, and retry.
> 
> ^^ This, and also remove -ea or -enableassertions JVM argument if you have it on your startup script.
> 
> > > Try delete your `materials.json`, and retry.
> > 
> > 
> > Where do I find that @Romitou ?
> 
> It should be on plugins/Skript folder as far as I know.

I'm not seeing the Materials.Json file anywhere; what is the default location for it?

**Comment by JamesBakerHewitt** [comment]
> enableassertions

**Comment by JamesBakerHewitt** [comment]
Didn't mean to close this oof

**Comment by JamesBakerHewitt** [comment]
Accidently closed; I can't find the materials.Json nor can i find the -ea -eneableassertions @TheDGOfficial @Romitou

**Comment by Romitou** [comment]
Do you use a modded server?

**Comment by TheDGOfficial** [comment]
> Accidently closed; I can't find the materials.Json nor can i find the -ea -eneableassertions @TheDGOfficial @Romitou

It should be on the location I mentioned, but if it does not exist then the error mentioned probably happened during the creation of materials.json file.

Re-looking at the error, you are using forge. Forge is not supported currently. Only Spigot/Paper is.

**Comment by JamesBakerHewitt** [comment]
> Do you use a modded server?

Yes it is. Only a few small mods / create. Wondering if that could break skript installing though?

**Comment by JamesBakerHewitt** [comment]
> > Accidently closed; I can't find the materials.Json nor can i find the -ea -eneableassertions @TheDGOfficial @Romitou
> 
> It should be on the location I mentioned, but if it does not exist then the error mentioned probably happened during the creation of materials.json file.
> 
> Re-looking at the error, you are using forge. Forge is not supported currently. Only Spigot/Paper is.

Ah that would do it. Thanks for the help I'll swap the stuff out for paper and redo it all!

**Comment by Romitou** [comment]
As TheDGOfficial said, Skript doesn't support Forge or other modded servers.
