### ISSUE TITLE
Status of async script loading

### ISSUE THREAD

**Issue by TheDGOfficial** [SkriptLang/Skript#3743]
The `asynchronous script loading` config entry seems to be hidden and has to be manually added to the config to make it work. But, trying on a fresh 1.16.5 server with Skript v2.5.3 using only example scripts, it currently gives this error:

```
[05:15:04 WARN]: Exception in thread "Thread-5" java.lang.IllegalStateException: PreScriptLoadEvent may only be triggered synchronously.
[05:15:04 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:599)
[05:15:04 WARN]:        at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:397)
[05:15:04 WARN]:        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[05:15:04 WARN]:        at ch.njol.skript.ScriptLoader.lambda$3(ScriptLoader.java:337)
[05:15:04 WARN]:        at ch.njol.skript.ScriptLoader$AsyncLoaderThread.run(ScriptLoader.java:310)
```

Few things there:

- The "Thread-5" is not meaningful, it should be changed to something like "Skript async script loader" or such.

- Events should have correct async calls to super constructor. (Cause of error)

- Maybe re-add to the config with a warning in full caps that this may break things.

- The loader thread is currently started even when this config option is disabled (or non-existent), and loops `while (true)` forever (it uses queues, which uses LockSupport#park, so it is performance friendly, but an useless thread drains thread stack, still.), so this line should be changed to only start the thread when `isAsync` method returns true: https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/ScriptLoader.java#L299

**Comment by TPGamesNL** [comment]
See https://github.com/SkriptLang/Skript/pull/3324

**Comment by TPGamesNL** [comment]
#1780 
More things:
- Log handler errors when reloading, due to #3453 and what's mentioned below
- Skript gives the message that the script was reloaded before the reloading is done and removes the `RedirectingLogHandler`, so if a player reloading a script, they won't see any of the errors (they might if they're lucky, it's a race condition), as those will go to console.
