### ISSUE TITLE
Skript erroe

### ISSUE THREAD

**Issue by dhavk4** [SkriptLang/Skript#3748]
### Description

i dont no but Skrit said should tell you this 

[20:08:00] [Server thread/ERROR]: #!#!
[20:08:00] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[20:08:00] [Server thread/ERROR]: #!#!
[20:08:00] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[20:08:00] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:08:00] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[20:08:00] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[20:08:00] [Server thread/ERROR]: #!#!
[20:08:00] [Server thread/ERROR]: #!#! Stack trace:
[20:08:00] [Server thread/ERROR]: #!#! java.lang.NoSuchMethodError: org.bukkit.Effect.getName()Ljava/lang/String;
[20:08:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.VisualEffect$Type.<init>(VisualEffect.java:197)
[20:08:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:64)
[20:08:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:270)
[20:08:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:891)
[20:08:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:324)
[20:08:00] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[20:08:00] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[20:08:00] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[20:08:00] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494)
[20:08:00] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408)
[20:08:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435)
[20:08:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218)
[20:08:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809)
[20:08:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[20:08:00] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[20:08:00] [Server thread/ERROR]: #!#!
[20:08:00] [Server thread/ERROR]: #!#! Version Information:
[20:08:00] [Server thread/ERROR]: #!#!   Skript: 2.2-dev37c
[20:08:00] [Server thread/ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[20:08:00] [Server thread/ERROR]: #!#!   Minecraft: 1.16.5
[20:08:00] [Server thread/ERROR]: #!#!   Java: 1.8.0_251 (Java HotSpot(TM) Client VM 25.251-b08)
[20:08:00] [Server thread/ERROR]: #!#!   OS: Windows 10 x86 10.0
[20:08:00] [Server thread/ERROR]: #!#!
[20:08:00] [Server thread/ERROR]: #!#! Server platform: Spigot
[20:08:00] [Server thread/ERROR]: #!#!
[20:08:00] [Server thread/ERROR]: #!#! Current node: null
[20:08:00] [Server thread/ERROR]: #!#! Current item: null
[20:08:00] [Server thread/ERROR]: #!#!
[20:08:00] [Server thread/ERROR]: #!#! Thread: Server thread
[20:08:00] [Server thread/ERROR]: #!#!
[20:08:00] [Server thread/ERROR]: #!#! Language: english
[20:08:00] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[20:08:00] [Server thread/ERROR]: #!#!
[20:08:00] [Server thread/ERROR]: #!#! End of Error.
[20:08:00] [Server thread/ERROR]: #!#!

**Comment by Romitou** [comment]
You are using a version of Skript totally incompatible with 1.16.5. Use 2.5.3.

**Comment by ShaneBeee** [comment]
Closing due to outdated Skript version
