### ISSUE TITLE
Adding "name" and "lore" to nbt in aliases

### ISSUE THREAD

**Issue by vhone** [SkriptLang/Skript#3776]
### Description

Adding "name" and "lore" to nbt in aliases results in an error.

### Steps to Reproduce

```
aliases:
	test_item1 = minecraft:stick {display:{Name:'{"text":"test_name","italic":false}'}}
	test_item2 = minecraft:stick {display:{Lore:['[{"text":"test_lore"}]']}}
	test_item3 = minecraft:stick {display:{Name:'{"text":"test_name","italic":false}',Lore:['[{"text":"test_lore"}]']}}
```
test_item1 and test_item2 work well.
test_item3 generates an error.

```/give @a minecraft:stick{display:{Name:'[{"text":"test_name","italic":false}]',Lore:['[{"text":"test_lore"}]']}}```
The command works well.

### Errors / Screenshots

```
[22:57:31 ERROR]: #!#!
[22:57:31 ERROR]: #!#! [Skript] Severe Error:
[22:57:31 ERROR]: #!#! Could not load test.sk
[22:57:31 ERROR]: #!#!
[22:57:31 ERROR]: #!#! Something went horribly wrong with Skript.
[22:57:31 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:57:31 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[22:57:31 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[22:57:31 ERROR]: #!#!
[22:57:31 ERROR]: #!#! Stack trace:
[22:57:31 ERROR]: #!#! com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 54 path $.display
[22:57:31 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:897)
[22:57:31 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:852)
[22:57:31 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:801)
[22:57:31 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:773)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.aliases.AliasesProvider.parseMojangson(AliasesProvider.java:180)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.aliases.AliasesParser.parseVariation(AliasesParser.java:222)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:678)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:620)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:120)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:548)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:464)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:976)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:185)
[22:57:31 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:57:31 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[22:57:31 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)
[22:57:31 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:769)
[22:57:31 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[22:57:31 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378)
[22:57:31 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209)
[22:57:31 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997)
[22:57:31 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[22:57:31 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:832)
[22:57:31 ERROR]: #!#! Caused by: java.io.EOFException: End of input at line 1 column 54 path $.display
[22:57:31 ERROR]: #!#!     at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393)
[22:57:31 ERROR]: #!#!     at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:482)
[22:57:31 ERROR]: #!#!     at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
[22:57:31 ERROR]: #!#!     at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:69)
[22:57:31 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:887)
[22:57:31 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:852)
[22:57:31 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:801)
[22:57:31 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:773)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.aliases.AliasesProvider.parseMojangson(AliasesProvider.java:180)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.aliases.AliasesParser.parseVariation(AliasesParser.java:222)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:678)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:620)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:120)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:548)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:464)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:976)
[22:57:31 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:185)
[22:57:31 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:57:31 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[22:57:31 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)
[22:57:31 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:769)
[22:57:31 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[22:57:31 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378)
[22:57:31 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209)
[22:57:31 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997)
[22:57:31 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[22:57:31 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:832)
[22:57:31 ERROR]: #!#!
[22:57:31 ERROR]: #!#! Version Information:
[22:57:31 ERROR]: #!#!   Skript: 2.5.3 (latest)
[22:57:31 ERROR]: #!#!     Flavor: skriptlang-github
[22:57:31 ERROR]: #!#!     Date: 2020-12-11
[22:57:31 ERROR]: #!#!   Bukkit: 1.16.4-R0.1-SNAPSHOT
[22:57:31 ERROR]: #!#!   Minecraft: 1.16.4
[22:57:31 ERROR]: #!#!   Java: 15.0.1 (Java HotSpot(TM) 64-Bit Server VM 15.0.1+9-18)
[22:57:31 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[22:57:31 ERROR]: #!#!
[22:57:31 ERROR]: #!#! Server platform: Paper
[22:57:31 ERROR]: #!#!
[22:57:31 ERROR]: #!#! Current node: test_item3: minecraft:stick {display:{Name:'{"text":"test_name","italic":false}'},display:{Lore:['[{"text":"test_lore"}]']}} (test.sk, line 12)
[22:57:31 ERROR]: #!#! Current item: null
[22:57:31 ERROR]: #!#!
[22:57:31 ERROR]: #!#! Thread: Server thread
[22:57:31 ERROR]: #!#!
[22:57:31 ERROR]: #!#! Language: english
[22:57:31 ERROR]: #!#! Link parse mode: DISABLED
[22:57:31 ERROR]: #!#!
[22:57:31 ERROR]: #!#! End of Error.
[22:57:31 ERROR]: #!#!
```

### Server Information
* **Server version/platform:**  git-Paper-345 (MC: 1.16.4)
* **Skript version:**  2.5.3

**Comment by TPGamesNL** [comment]
Can confirm. Caused by `AliasesParser#loadAlias` trying to split the alias line at its commas (so you can have a list), but it doesn't properly take JSON into account
