### ISSUE TITLE
Torch Position

### ISSUE THREAD

**Issue by SebyHas** [SkriptLang/Skript#3778]
### Description
https://youtu.be/aB3-jE97iPY

### Steps to Reproduce
When i hit a item frame, the arrow pass beyond the entity and place the torch, but in theory it shouldn't, in theory need to "kill projectile" but not make it, and when place the torch give this error.

### Skript content:
on shoot:
	if projectile is an arrow:
		if lore of held item of shooter contain "&7Torch":
			set name of last shot projectile to "torchbow_projectile_%shooter%"
			set {torchbow.%shooter%} to true

on projectile hit:
	if event-projectile is arrow:
		wait 5 ticks
		if {torchbow.%shooter%} is true:
			wait 2 ticks
			if block at event-location is air or cave air or short grass or double tall grass:
				send "%block at event-location%" to shooter
				set the block at event-location to torch
				delete {torchbow.%shooter%}
				kill projectile
			else if block at event-location is floor torch or wall torch:
				stop
			else:
				send "&4Error: &cSorry, but target block need to be air, not %block at event-location%." to shooter

on damage:
	if projectile is arrow:
		if {torchbow.%attacker%} is true:
			cancel event
			send "You can't hit entitis with TorchBow!" to attacker
			delete {torchbow.%shooter%}
			kill projectile
		if name of projectile is "torchbow_projectile_%attacker%":
			cancel event
			delete {torchbow.%shooter%}
			kill projectile
			broadcast "%name of projectile% - %attacker%"

### Errors / Screenshots
[17:46:24 ERROR]: #!#!
[17:46:24 ERROR]: #!#! [Skript] Severe Error:
[17:46:24 ERROR]: #!#!
[17:46:24 ERROR]: #!#! Something went horribly wrong with Skript.
[17:46:24 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:46:24 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[17:46:24 ERROR]: #!#! Here is full list of them:
[17:46:24 ERROR]: #!#! SkBee v1.10.1 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.3.2 SkQuery v4.1.3
[17:46:24 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[17:46:24 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[17:46:24 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[17:46:24 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[17:46:24 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[17:46:24 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[17:46:24 ERROR]: #!#!
[17:46:24 ERROR]: #!#! Stack trace:
[17:46:24 ERROR]: #!#! java.lang.IllegalArgumentException: Cannot set property BlockStateDirection{name=facing, clazz=class net.minecraft.server.v1_16_R3.EnumDirection, values=[north, south, west, east]} to null on Block{minecraft:wall_torch}, it is not an allowed value
[17:46:24 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IBlockDataHolder.set(IBlockDataHolder.java:118)
[17:46:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.block.data.CraftBlockData.set(CraftBlockData.java:96)
[17:46:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.block.impl.CraftTorchWall.setFacing(CraftTorchWall.java:27)
[17:46:24 ERROR]: #!#!     at ch.njol.skript.bukkitutil.block.NewBlockCompat$NewBlockSetter.setBlock(NewBlockCompat.java:169)
[17:46:24 ERROR]: #!#!     at ch.njol.skript.util.BlockUtils.set(BlockUtils.java:56)
[17:46:24 ERROR]: #!#!     at ch.njol.skript.aliases.ItemType.setBlock(ItemType.java:359)
[17:46:24 ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultChangers$6.change(DefaultChangers.java:305)
[17:46:24 ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultChangers$6.change(DefaultChangers.java:1)
[17:46:24 ERROR]: #!#!     at ch.njol.skript.lang.util.ConvertedExpression.change(ConvertedExpression.java:148)
[17:46:24 ERROR]: #!#!     at ch.njol.skript.expressions.base.WrapperExpression.change(WrapperExpression.java:122)
[17:46:24 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[17:46:24 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[17:46:24 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[17:46:24 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[17:46:24 ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:108)
[17:46:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[17:46:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[17:46:24 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1293)
[17:46:24 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
[17:46:24 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208)
[17:46:24 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996)
[17:46:24 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
[17:46:24 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:832)
[17:46:24 ERROR]: #!#!
[17:46:24 ERROR]: #!#! Version Information:
[17:46:24 ERROR]: #!#!   Skript: 2.5.3 (latest)
[17:46:24 ERROR]: #!#!     Flavor: skriptlang-github
[17:46:24 ERROR]: #!#!     Date: 2020-12-11
[17:46:24 ERROR]: #!#!   Bukkit: 1.16.4-R0.1-SNAPSHOT
[17:46:24 ERROR]: #!#!   Minecraft: 1.16.4
[17:46:24 ERROR]: #!#!   Java: 15.0.2 (OpenJDK 64-Bit Server VM 15.0.2+7)
[17:46:24 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[17:46:24 ERROR]: #!#!
[17:46:24 ERROR]: #!#! Server platform: Paper
[17:46:24 ERROR]: #!#!
[17:46:24 ERROR]: #!#! Current node: null
[17:46:24 ERROR]: #!#! Current item: set the block (at the location >> ch.njol.skript.expressions.ExprBlock$1@7179309b: location -> block) to [[itemtype:floor torch]]
[17:46:24 ERROR]: #!#! Current trigger: projectile hit (simple event) (torchbow.sk, line 8)
[17:46:24 ERROR]: #!#!
[17:46:24 ERROR]: #!#! Thread: Server thread
[17:46:24 ERROR]: #!#!
[17:46:24 ERROR]: #!#! Language: english
[17:46:24 ERROR]: #!#! Link parse mode: DISABLED
[17:46:24 ERROR]: #!#!
[17:46:24 ERROR]: #!#! End of Error.
[17:46:24 ERROR]: #!#!

### Server Information
Paper-416 (MC: 1.16.4)
2.5.3

**Comment by TPGamesNL** [comment]
Can confirm. Code:
```
on projectile hit:
	set {_b} to block at event-location
	broadcast "LOC %location of {_b}%"
	set block at {_b} to stone
	set block at {_b} to torch
	broadcast "TWO"
```
Probably caused by `NewBlockCompat.NewBlockSetter#findWallTorchSide` not always returning cardinal directions (north, east, south or west), but other `BlockFace`s (e.g. `BlockFace.SELF`)
