### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by AnetaKrychowiak** [SkriptLang/Skript#3830]
### Description

error
### Steps to Reproduce

On server start
### Expected Behavior

idk
### Errors / Screenshots

[09:59:13 INFO]: [Skript] Loading variables...
[09:59:13 ERROR]: [Skript] 61 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:263)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[09:59:13 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:579)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[09:59:13 ERROR]: [Skript] 102 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1539)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[09:59:13 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1500)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[09:59:13 ERROR]: [Skript] 235 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:263)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[09:59:13 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:579)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[09:59:13 ERROR]: [Skript] 2 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1606)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[09:59:13 ERROR]: [Skript] 1114 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[09:59:13 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:523)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[09:59:13 ERROR]: [Skript] 34 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:841)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[09:59:13 ERROR]: [Skript] 42 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1592)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[09:59:13 ERROR]: [Skript] 1211 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[09:59:14 ERROR]: [Skript] 75 log handlers were not stopped properly! (at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:696)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

### Server Information
* **Server version/platform:** 
* **Skript version:** 
Spigot 1.12.2
Skript 2.5.3 
Skript mirror v0.19.1
Tuske v1.8.2
Sk-perm v2.3.0

**Comment by Romitou** [comment]
Try updating skript-mirror to skript-reflect. https://github.com/TPGamesNL/skript-reflect

**Comment by TPGamesNL** [comment]
As said above, this issue is caused by old versions of skript-mirror
