### ISSUE TITLE
skript error

### ISSUE THREAD

**Issue by AnetaKrychowiak** [SkriptLang/Skript#3843]
### Description

I was starting server and this error jumped into my console
### Steps to Reproduce

I switch spigot 1.12.2 to paperspigot 1.12.2
### Errors / Screenshots

[18:48:04 ERROR]: #!#! [Skript] Severe Error:
[18:48:04 ERROR]: #!#! TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception while loading
[18:48:04 ERROR]: #!#!
[18:48:04 ERROR]: #!#! Something went horribly wrong with Skript.
[18:48:04 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[18:48:04 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[18:48:04 ERROR]: #!#! Following plugins are probably related to this error in some way:
[18:48:04 ERROR]: #!#! TuSKe (github.com/Tuke-Nuke/TuSKe)
[18:48:04 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[18:48:04 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[18:48:04 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[18:48:04 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[18:48:04 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[18:48:04 ERROR]: #!#!
[18:48:04 ERROR]: #!#! Stack trace:
[18:48:04 ERROR]: #!#! java.lang.NullPointerException
[18:48:04 ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
[18:48:04 ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[18:48:04 ERROR]: #!#!     at java.lang.Class.forName(Unknown Source)
[18:48:04 ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107)
[18:48:04 ERROR]: #!#!     at com.github.tukenuke.tuske.TuSKe.onEnable(TuSKe.java:100)
[18:48:04 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:48:04 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[18:48:04 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[18:48:04 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[18:48:04 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[18:48:04 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[18:48:04 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[18:48:04 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[18:48:04 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[18:48:04 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[18:48:04 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[18:48:04 ERROR]: #!#!
[18:48:04 ERROR]: #!#! Version Information:
[18:48:04 ERROR]: #!#!   Skript: 2.5.3 (latest)
[18:48:04 ERROR]: #!#!     Flavor: skriptlang-github
[18:48:04 ERROR]: #!#!     Date: 2020-12-11
[18:48:04 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[18:48:04 ERROR]: #!#!   Minecraft: 1.12.2
[18:48:04 ERROR]: #!#!   Java: 1.8.0_281 (Java HotSpot(TM) 64-Bit Server VM 25.281-b09)
[18:48:04 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[18:48:04 ERROR]: #!#!
[18:48:04 ERROR]: #!#! Server platform: Paper
[18:48:04 ERROR]: #!#!
[18:48:04 ERROR]: #!#! Current node: null
[18:48:04 ERROR]: #!#! Current item: null
[18:48:04 ERROR]: #!#!
[18:48:04 ERROR]: #!#! Thread: Server thread
[18:48:04 ERROR]: #!#!
[18:48:04 ERROR]: #!#! Language: english
[18:48:04 ERROR]: #!#! Link parse mode: DISABLED
[18:48:04 ERROR]: #!#!
[18:48:04 ERROR]: #!#! End of Error.
[18:48:04 ERROR]: #!#!

### Server Information
* **Server version/platform:** Before , spigot 1.12.2 after, paper 1.12.21.12.2
* **Skript version:** 2.5.3 , TuSke 1.8.2

### Additional Context

I tried disabling every plugins but this error i still see everytime when im starting my server

**Comment by TPGamesNL** [comment]
This is an issue you get when using an old version of TuSKe, use this instead: https://github.com/Pikachu920/TuSKe

**Comment by AnetaKrychowiak** [comment]
No, i have just updated TuSke and still the same error

pon., 22 mar 2021 o 19:02 TPGamesNL ***@***.***> napisał(a):

**Comment by TPGamesNL** [comment]
The issue tracker is for reporting bugs with Skript, which this isn't. I recommend you visit the Skript Chat Discord or skUnity Forums / Discord for this issue.
