### ISSUE TITLE
Do not prevent all scripts from loading under file permission exception

### ISSUE THREAD

**Issue by DeletedUsero** [SkriptLang/Skript#3866]
### Description

All scripts stop loading when a single file permission exception appears.
### Steps to Reproduce

Have a file to which the server does not have permission to read in scripts folder
### Expected Behavior

to not stop loading all scripts just because one file failed
### Errors / Screenshots

```
[01:35:58] [Server thread/WARN]: [Skript] Task #41 for Skript v2.5.1 generated an exception
java.io.UncheckedIOException: java.nio.file.AccessDeniedException: plugins/Skript/scripts/.git/refs
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:87) ~[?:?]
	at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:132) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at ch.njol.skript.ScriptLoader.updateDisabledScripts(ScriptLoader.java:290) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:325) ~[?:?]
	at ch.njol.skript.Skript$2.run(Skript.java:606) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.nio.file.AccessDeniedException: plugins/Skript/scripts/.git/refs
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1764) ~[?:?]
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219) ~[?:?]
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276) ~[?:?]
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373) ~[?:?]
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:83) ~[?:?]
	... 19 more
```

### Server Information
* **Server version/platform:**  1.12.2, 1.16.5, purpur and paper (all my servers)
* **Skript version:** 2.5.1 - 2.5.3

**Comment by TheDGOfficial** [comment]
It only loads .sk files and there should be no sk files in .git folder, it is not caused by Skript trying to load anything there - but trying to access it is attributes - you are using linux/*nix like system from stacktrace, check permissions. They are not same as on Windows, and I remember using a Git repository in scripts folder on Windows.

Though it can be enchanced like you said, possibly/probably ignoring unreadable (File#canRead()), hidden (generally any file starting with dot in most operating systems) files/folders or git repositories (.git).

**Comment by Govindass** [comment]
> It only loads .sk files and there should be no sk files in .git folder, it is not caused by Skript trying to load anything there - but trying to access it is attributes - you are using linux/*nix like system from stacktrace, check permissions. They are not same as on Windows, and I remember using a Git repository in scripts folder on Windows.
> 
> Though it can be enchanced like you said, possibly/probably ignoring unreadable (File#canRead()), hidden (generally any file starting with dot in most operating systems) files/folders or git repositories (.git).

I cannot edit file permissions, they're on pterodactyl from a hosting provider

**Comment by Govindass** [comment]
I have solved my issue, it was caused by using SSHFS to access server files which I found to be problematic when it comes to file permissions

however the suggestion to make it not stop loading scripts under this exception still remains
