### ISSUE TITLE
Severe Error on Mohist

### ISSUE THREAD

**Issue by ddbbmkea** [SkriptLang/Skript#3875]
```
[06:48:44 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[06:48:47 WARN]: Legacy plugin Skript v2.2-dev36 does not specify an api-version.
[06:48:47 INFO]: [Skript] Loading Skript v2.2-dev36
[06:48:47 INFO]: Preparing level "world"
[06:48:47 INFO]: [Skript] Enabling Skript v2.2-dev36
[06:48:48 ERROR]: #!#!
[06:48:48 ERROR]: #!#! [Skript] Severe Error:
[06:48:48 ERROR]: #!#!
[06:48:48 ERROR]: #!#! Something went horribly wrong with Skript.
[06:48:48 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[06:48:48 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[06:48:48 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[06:48:48 ERROR]: #!#!
[06:48:48 ERROR]: #!#! Stack trace:
[06:48:48 ERROR]: #!#! java.lang.NoSuchMethodError: org.bukkit.Effect.getName()Ljava/lang/String;
[06:48:48 ERROR]: #!#!     at ch.njol.skript.util.VisualEffect$Type.<init>(VisualEffect.java:196)
[06:48:48 ERROR]: #!#!     at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:63)
[06:48:48 ERROR]: #!#!     at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:269)
[06:48:48 ERROR]: #!#!     at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:891)
[06:48:48 ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:336)
[06:48:48 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[06:48:48 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[06:48:48 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[06:48:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:406)
[06:48:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:320)
[06:48:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:438)
[06:48:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:357)
[06:48:48 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217)
[06:48:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:727)
[06:48:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:277)
[06:48:48 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[06:48:48 ERROR]: #!#!
[06:48:48 ERROR]: #!#! Version Information:
[06:48:48 ERROR]: #!#!   Skript: 2.2-dev36
[06:48:48 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[06:48:48 ERROR]: #!#!   Minecraft: 1.16.5
[06:48:48 ERROR]: #!#!   Java: 1.8.0_281 (Java HotSpot(TM) 64-Bit Server VM 25.281-b09)
[06:48:48 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[06:48:48 ERROR]: #!#!
[06:48:48 ERROR]: #!#! Server platform: Spigot
[06:48:48 ERROR]: #!#!
[06:48:48 ERROR]: #!#! Current node: null
[06:48:48 ERROR]: #!#! Current item: null
[06:48:48 ERROR]: #!#!
[06:48:48 ERROR]: #!#! Thread: Server thread
[06:48:48 ERROR]: #!#!
[06:48:48 ERROR]: #!#! Language: english
[06:48:48 ERROR]: #!#! Link parse mode: DISABLED
[06:48:48 ERROR]: #!#!
[06:48:48 ERROR]: #!#! End of Error.
[06:48:48 ERROR]: #!#!
```

Skript: 2.2-dev36
Bukkit: 1.16.5-R0.1-SNAPSHOT
Minecraft: 1.16.5
Java: 1.8.0_281 (Java HotSpot(TM) 64-Bit Server VM 25.281-b09)
OS: Windows 10 amd64 10.0

I don't know what is wrong.
I can't **start** Skript.
Please help me.

**Comment by bluelhf** [comment]
Update Skript.
