### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Brazem3** [SkriptLang/Skript#3904]
[10:13:31] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[10:13:31] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[10:13:31] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[10:13:31] [Server thread/ERROR]: #!#! Here is full list of them:
[10:13:31] [Server thread/ERROR]: #!#! skRayFall v1.9.24 (https://sk.rayfall.net/) Vixio v2.0.7 (http://vixio.space) TuSKe v1.8.2 (github.com/Tuke-Nuke/TuSKe) Skacket v1.0.5 Tablisknu v1.0 (tlatoani.us/tablisknu) Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/) SharpSK v1.6.3 skript-reflect v2.2.1 (https://github.com/TPGamesNL/skript-reflect) SkJade v1.2.0 (https://www.github.com/Ankoki-Dev/SkJade) SkMorkaz v0.21 skDragon v0.14.999 SkStuff v1.6.4.1 SkQuery v4.1.4 Ersatz v1.0 DiSky v1.7 (https://disky.itsthesky.info/)
[10:13:31] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[10:13:31] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[10:13:32] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[10:13:32] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[10:13:32] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[10:13:32] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[10:13:32] [Server thread/ERROR]: #!#!
[10:13:32] [Server thread/ERROR]: #!#! Stack trace:
[10:13:32] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for embedbuilder
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:262)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1837)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1804)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1552)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:501)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:839)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1568)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:58)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1030)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:486)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:636)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$3(ScriptLoader.java:337)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:370)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:985)
[10:13:32] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:161)
[10:13:32] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[10:13:32] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[10:13:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
[10:13:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[10:13:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[10:13:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[10:13:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144)
[10:13:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[10:13:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118)
[10:13:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:942)
[10:13:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935)
[10:13:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[10:13:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:919)
[10:13:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851)
[10:13:32] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[10:13:32] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[10:13:32] [Server thread/ERROR]: #!#!
[10:13:32] [Server thread/ERROR]: #!#! Version Information:
[10:13:32] [Server thread/ERROR]: #!#!   Skript: 2.5.3 (latest)
[10:13:32] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[10:13:32] [Server thread/ERROR]: #!#!     Date: 2020-12-11
[10:13:32] [Server thread/ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[10:13:32] [Server thread/ERROR]: #!#!   Minecraft: 1.16.5
[10:13:32] [Server thread/ERROR]: #!#!   Java: 1.8.0_281 (Java HotSpot(TM) 64-Bit Server VM 25.281-b09)
[10:13:32] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[10:13:32] [Server thread/ERROR]: #!#!
[10:13:32] [Server thread/ERROR]: #!#! Server platform: Spigot
[10:13:32] [Server thread/ERROR]: #!#!
[10:13:32] [Server thread/ERROR]: #!#! Current node: set held offhand item of player to stone pickaxe (te.sk, line 4)
[10:13:32] [Server thread/ERROR]: #!#! Current item: null
[10:13:32] [Server thread/ERROR]: #!#!
[10:13:32] [Server thread/ERROR]: #!#! Thread: Server thread
[10:13:32] [Server thread/ERROR]: #!#!
[10:13:32] [Server thread/ERROR]: #!#! Language: english
[10:13:32] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[10:13:32] [Server thread/ERROR]: #!#!
[10:13:32] [Server thread/ERROR]: #!#! End of Error.
[10:13:32] [Server thread/ERROR]: #!#!
[10:13:32] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5482ms or 109 ticks behind

**Comment by TPGamesNL** [comment]
Caused by an addon, probably Vixio/DiSky

**Comment by SkyCraft78** [comment]
Hi, you're using both Vixio and DiSky at the same time.
However, you can't use them like that, choose DiSky or Vixio in order your server to load fine.
