### ISSUE TITLE
I can't reload my .sk file

### ISSUE THREAD

**Issue by 12yearsoldcoder** [SkriptLang/Skript#4010]
### Description

I was reloading the .sk file and there is an error
### Steps to Reproduce

I don't know
### Expected Behavior

Successfully reloaded file
### Errors / Screenshots

No.

OK

Nothing
### Server Information
* **Server version/platform:*1.16.5, Windows* 
* **Skript version:*2017-10-18* 

### Additional Context #

- [ ] 

- 1. 
- 2. 

08:03:38] [Server thread/INFO]: [Skript] Reloading triggers.sk...
[08:03:38] [Server thread/ERROR]: #!#!
[08:03:38] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[08:03:38] [Server thread/ERROR]: #!#! Could not load triggers.sk
[08:03:38] [Server thread/ERROR]: #!#!
[08:03:38] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[08:03:38] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[08:03:38] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[08:03:38] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[08:03:38] [Server thread/ERROR]: #!#!
[08:03:38] [Server thread/ERROR]: #!#! Stack trace:
[08:03:38] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for citizen
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:262)
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1837)
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1804)
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1552)
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1498)
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:58)
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1030)
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:486)
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:636)
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:464)
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:976)
[08:03:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:185)
[08:03:38] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[08:03:38] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[08:03:38] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:763)
[08:03:38] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:748)
[08:03:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:387)
[08:03:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:356)
[08:03:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008)
[08:03:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847)
[08:03:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[08:03:38] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[08:03:38] [Server thread/ERROR]: #!#!
[08:03:38] [Server thread/ERROR]: #!#! Version Information:
[08:03:38] [Server thread/ERROR]: #!#!   Skript: 2.5.3 (latest)
[08:03:38] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[08:03:38] [Server thread/ERROR]: #!#!     Date: 2020-12-11
[08:03:38] [Server thread/ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[08:03:38] [Server thread/ERROR]: #!#!   Minecraft: 1.16.5
[08:03:38] [Server thread/ERROR]: #!#!   Java: 1.8.0_291 (Java HotSpot(TM) 64-Bit Server VM 25.291-b10)
[08:03:38] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[08:03:38] [Server thread/ERROR]: #!#!
[08:03:38] [Server thread/ERROR]: #!#! Server platform: Spigot
[08:03:38] [Server thread/ERROR]: #!#!
[08:03:38] [Server thread/ERROR]: #!#! Current node: message "bemyfriend" (triggers.sk, line 3)
[08:03:38] [Server thread/ERROR]: #!#! Current item: null
[08:03:38] [Server thread/ERROR]: #!#!
[08:03:38] [Server thread/ERROR]: #!#! Thread: Server thread
[08:03:38] [Server thread/ERROR]: #!#!
[08:03:38] [Server thread/ERROR]: #!#! Language: english
[08:03:38] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[08:03:38] [Server thread/ERROR]: #!#!
[08:03:38] [Server thread/ERROR]: #!#! End of Error.
[08:03:38] [Server thread/ERROR]: #!#!
[08:03:38] [Server thread/INFO]: [Skript] Successfully reloaded triggers.sk.

**Comment by AyhamAl-Ali** [comment]
Regardless of the messy and wrong format of the issue, but this is caused by `#!#! ch.njol.skript.SkriptAPIException: No class info found for citizen`

You're probably using some addon that interacts with Citizens plugin and you're using that Citizens related effect but you don't have the plugin. If not you better provide the code you're using specifically `line 3`.

**Comment by ShaneBeee** [comment]
As Ayham said, this issue is from an addon, and not Skript itself.

When reporting issues, please test first without addons. If its an addon issue, please report to the respective addon.
