### ISSUE TITLE
Start-up failure

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#4023]
### Description
Skript 2.6-alpha1 failed to load on startup

### Steps to Reproduce
- Stop server
- Update from Skiript 2.5.3 to 2.6-alpha1 -- no other changes
- Start server

### Expected Behavior
Clean start-up

### Errors / Screenshots
```
[10:16:04] [Server thread/ERROR]: Could not load 'plugins/Skript-2.6-alpha1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: ch/njol/skript/Skript has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot-1.16.5-3083.jar:3083-Spigot-9fb885e-9c7acb6]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.5-3083.jar:3083-Spigot-9fb885e-9c7acb6]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.5-3083.jar:3083-Spigot-9fb885e-9c7acb6]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:381) ~[spigot-1.16.5-3083.jar:3083-Spigot-9fb885e-9c7acb6]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:224) ~[spigot-1.16.5-3083.jar:3083-Spigot-9fb885e-9c7acb6]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot-1.16.5-3083.jar:3083-Spigot-9fb885e-9c7acb6]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5-3083.jar:3083-Spigot-9fb885e-9c7acb6]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.UnsupportedClassVersionError: ch/njol/skript/Skript has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:184) ~[spigot-1.16.5-3083.jar:3083-Spigot-9fb885e-9c7acb6]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-1.16.5-3083.jar:3083-Spigot-9fb885e-9c7acb6]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.16.5-3083.jar:3083-Spigot-9fb885e-9c7acb6]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-1.16.5-3083.jar:3083-Spigot-9fb885e-9c7acb6]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-1.16.5-3083.jar:3083-Spigot-9fb885e-9c7acb6]
        ... 7 more
```

### Server Information
CentOS Linux release 7.9.2009 (Core)

java version "11.0.11" 2021-04-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)

[10:24:38] [Server thread/INFO]: This server is running CraftBukkit version 3083-Spigot-9fb885e-9c7acb6 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[10:24:38] [Server thread/INFO]: You are running the latest version

Skript 2.6-alpha1

**Comment by ShaneBeee** [comment]
It looks like snow may have built on Java 15
We will need to rebuild Skript

**Comment by SlimeDog** [comment]
Confirmed that Skript 2.6-alpha1 loads on Java 16.0.1
But due to some other plugins, servers are typically running Java 11.0.11.

**Comment by ShaneBeee** [comment]
Ok, I have rebuilt Skript on Java 8 and updated the jar file.
Please redownload.

Closing this as fixed, but if you have issues, please feel free to reopen.

**Comment by SlimeDog** [comment]
Confirmed
```
[10:54:34] [Server thread/INFO]: [Skript] Loading Skript v2.6-alpha1
[10:55:51] [Server thread/INFO]: [Skript] Enabling Skript v2.6-alpha1
[10:55:52] [Server thread/INFO]: [Skript] Your configuration has been updated to the latest version. A backup of your old config file has been created as config_2021-05-23_10-55-52.sk
[10:56:00] [Server thread/INFO]: [Skript] Loaded 128260 aliases in 8253ms
[10:56:00] [Server thread/INFO]: [Skript]  ~ created by & © Peter Güttinger aka Njol ~
[10:56:11] [Server thread/INFO]: [Skript] Loading variables...
[10:56:11] [Server thread/INFO]: [Skript] Loaded 7 variables in 0.0 seconds
[10:56:18] [Server thread/INFO]: [Skript] All scripts loaded without errors.
[10:56:18] [Server thread/INFO]: [Skript] Loaded 32 scripts with a total of 30 triggers and 30 commands in 6.29 seconds
[10:56:18] [Server thread/INFO]: [Skript] Finished loading
```

I do have a procedural nit: This should be 2.6-alpha2. Please do not use the same version string twice. No matter how small the change seems, they are not the same.

**Comment by TPGamesNL** [comment]
We just released a new version after half a year, there's no way we release two versions within an hour

**Comment by ShaneBeee** [comment]
the jar I replaced is the same version, alpha1, just rebuilt on java 8.
Nothing has changed, hence not changing the version number.

**Comment by SlimeDog** [comment]
Java 15 build != Java 8 build. Hence, the second one works on Java<15 while the first one does not. It is a small thing, but it is best practice to never use the same version string twice. It avoids any possible confusion.

Helper: "Which version are you running?"
Helpee: "It says Skript 2.6-alpha1"
Helper: "Yeah, but which one?"
and downhill from there.

**Comment by ShaneBeee** [comment]
Im not really sure why you're pressing this.

There is literally no difference between the 2 jar builds, other than how they were built.
They contain identical code.

We're not going to change the version number, since its the exact same version. Not to mention, the jar file was swapped out within an hour. 
If anyone downloaded it before I changed the jar, we can simply advise them to redownload the jar.

On top of all that, nothing, and I mean NOTHING has changed on the repo to warrant a version number change.
You're basically asking me to do a commit changing 1 -> 2, and literally nothing else.

We are not the first team to do this. Heck, Mojang has done this with Minecraft releases where they actually DID change some code and DIDNT change the version number.

So I repeat, we are NOT going to be changing the version number.
