### ISSUE TITLE
Error On Startup

### ISSUE THREAD

**Issue by ETechTechnologies** [SkriptLang/Skript#4065]
### Description
The error below appeared on startup

### Steps to Reproduce
Started the server with these plugins (see log)

### Expected Behavior
No error

[02:15:55 INFO]: [Skript] Loading variables...
[02:15:55 WARN]: [Skript] Task #27 for Skript v2.6-alpha1 generated an exception
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:166) ~[patched_1.16.5.jar:git-Purpur-1133]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Purpur-1133]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1133]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at me.iblitzkriegi.vixio.registration.Types$14.canParse(Types.java:361) ~[?:?]
        at me.iblitzkriegi.vixio.util.skript.SimpleType$1.canParse(SimpleType.java:73) ~[?:?]
        at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:441) ~[?:?]
        at ch.njol.skript.registrations.Classes.parse(Classes.java:474) ~[?:?]
        at ch.njol.skript.variables.VariablesStorage.getValue(VariablesStorage.java:101) ~[?:?]
        at ch.njol.skript.variables.VariablesStorage.load(VariablesStorage.java:158) ~[?:?]
        at ch.njol.skript.variables.Variables.load(Variables.java:192) ~[?:?]
        at ch.njol.skript.Skript$1.run(Skript.java:533) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1133]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1133]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1082) ~[patched_1.16.5.jar:git-Purpur-1133]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1133]
        at java.lang.Thread.run(Thread.java:831) [?:?]
        
        (Java 15)

**Comment by ShaneBeee** [comment]
Can you please try replicating this error without Vixio

I see Vixio in there, and that could be the route of the issue.

**Comment by TPGamesNL** [comment]
The exception is caused by Vixio
