### ISSUE TITLE
Skript does not work with ViaVersion

### ISSUE THREAD

**Issue by Comstepr** [SkriptLang/Skript#4066]
### Description
Skript does not work with ViaVersion.

### Steps to Reproduce
1. I installed ViaVersion alongside Skript on a ```This server is running Paper version git-Paper-"088fa6f28" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)```
2. I had a long paragraph of issues with Skript. See log below.

### Expected Behavior
If I'm not wrong, Skript used to work with ViaVersion. But ever since, it doesn't work.

### Errors / Screenshots
```
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[08:32:19] [Server thread/ERROR]: #!#! Could not load discord/give.sk
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[08:32:19] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[08:32:19] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[08:32:19] [Server thread/ERROR]: #!#! Here is full list of them:
[08:32:19] [Server thread/ERROR]: #!#! skRayFall v1.9.23 (https://sk.rayfall.net/) Vixio v2.0.7 (http://vixio.space) TuSKe v1.8.2-Pikachu-Patch-3 (github.com/Tuke-Nuke/TuSKe) ThatPacketAddon v1.0-BETA.3 (tlatoani.us/thatpacketaddon) Skellett v1.9.9 (https://forums.skunity.com/resources/skellett.24/) Reqn v1.2.1 skript-votifier-hook v1.1.0 DiscordSRV v1.22.0 (https://github.com/DiscordSRV/DiscordSRV) skript-mirror v2.0.0-SNAPSHOT (https://github.com/btk5h/skript-mirror) Skungee v1.0.15 skUtilities v0.9.2 (https://tim740.github.io/) SkQuery v4.1.5 SkUniversal v2.11.5 
[08:32:19] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[08:32:19] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[08:32:19] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[08:32:19] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[08:32:19] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[08:32:19] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! Stack trace:
[08:32:19] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for customenchantment
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:262)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1837)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1804)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1552)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:501)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:839)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1568)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1525)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1491)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1564)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1525)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1564)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:58)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1030)
[08:32:19] [Server thread/ERROR]: #!#!     at me.iblitzkriegi.vixio.commands.DiscordCommandFactory.add(DiscordCommandFactory.java:263)
[08:32:19] [Server thread/ERROR]: #!#!     at me.iblitzkriegi.vixio.commands.DiscordCommandRegistry.init(DiscordCommandRegistry.java:130)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1263)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1234)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:669)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$3(ScriptLoader.java:337)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:370)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:601)
[08:32:19] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[08:32:19] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[08:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:945)
[08:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[08:32:19] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:832)
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! Version Information:
[08:32:19] [Server thread/ERROR]: #!#!   Skript: 2.5.3 (latest)
[08:32:19] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[08:32:19] [Server thread/ERROR]: #!#!     Date: 2020-12-11
[08:32:19] [Server thread/ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[08:32:19] [Server thread/ERROR]: #!#!   Minecraft: 1.16.5
[08:32:19] [Server thread/ERROR]: #!#!   Java: 15.0.3 (OpenJDK 64-Bit Server VM 15.0.3+3-Ubuntu-120.10)
[08:32:19] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.8.0-55-generic
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! Server platform: Paper
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! Current node: set {discord.lang::role.leader} to role with id "842383464874377247" (discord/give.sk, line 3)
[08:32:19] [Server thread/ERROR]: #!#! Current item: null
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! Thread: Server thread
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! Language: english
[08:32:19] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! End of Error.
```

### Server Information
* **Server version/platform:** Supplied above
* **Skript version:**
Attaching /sk info below
```
[08:45:01 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[08:45:01 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[08:45:01 INFO]: [Skript] Server Version: git-Paper-"088fa6f28" (MC: 1.16.5)
[08:45:01 INFO]: [Skript] Skript Version: 2.5.3
[08:45:01 INFO]: [Skript] Installed Skript Addons:
[08:45:01 INFO]: [Skript]  - Skellett v1.9.9 (https://forums.skunity.com/resources/skellett.24/)
[08:45:01 INFO]: [Skript]  - SkUniversal v2.11.5
[08:45:01 INFO]: [Skript]  - skript-votifier-hook v1.1.0
[08:45:01 INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[08:45:01 INFO]: [Skript]  - Reqn v1.2.1
[08:45:01 INFO]: [Skript]  - Skungee v1.0.15
[08:45:01 INFO]: [Skript]  - Vixio v2.0.7 (http://vixio.space)
[08:45:01 INFO]: [Skript]  - skRayFall v1.9.23 (https://sk.rayfall.net/)
[08:45:01 INFO]: [Skript]  - SkQuery v4.1.5
[08:45:01 INFO]: [Skript]  - skript-mirror v2.0.0-SNAPSHOT (https://github.com/btk5h/skript-mirror)
[08:45:01 INFO]: [Skript]  - ThatPacketAddon v1.0-BETA.3 (tlatoani.us/thatpacketaddon)
[08:45:01 INFO]: [Skript]  - TuSKe v1.8.2-Pikachu-Patch-3 (github.com/Tuke-Nuke/TuSKe)
```

**Comment by Comstepr** [comment]
Turns out it's just one of my plugins. Lol.
