### ISSUE TITLE
Warning message on console

### ISSUE THREAD

**Issue by LowScarlet** [SkriptLang/Skript#4099]
### Description
Warning message spam on console

### Errors / Screenshots
```hs
[16:03:12 WARN]: [Skript] Plugin Skript v2.5.3 generated an exception while executing task 436
ch.njol.skript.SkriptAPIException: Serializer of number must override newInstance(), canBeInstantiated() or mustSyncDeserialization() if its class does not have a nullary constructor
        at ch.njol.skript.classes.Serializer.newInstance(Serializer.java:79) ~[?:?]
        at ch.njol.yggdrasil.Yggdrasil.newInstance(Yggdrasil.java:335) ~[?:?]
        at ch.njol.yggdrasil.Yggdrasil.isSerializable(Yggdrasil.java:154) ~[?:?]
        at ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:173) ~[?:?]
        at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249) ~[?:?]
        at ch.njol.skript.registrations.Classes.serialize(Classes.java:706) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:438) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:432) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:432) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:432) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.saveVariables(FlatFileStorage.java:386) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage$1.run(FlatFileStorage.java:198) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"ce66102"]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-"ce66102"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-"ce66102"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Server Information
* **Server version/platform:**1.17 paper
* **Skript version:** 2.5.3

**Comment by TPGamesNL** [comment]
We don't support 1.17 yet, and definitely not on 2.5.3
