### ISSUE TITLE
Error with 1.17, Cauldron issue

### ISSUE THREAD

**Issue by CowtealM** [SkriptLang/Skript#4103]
Running on PaperSpigot 1.17 build 35 - `[14:28:12] [Server thread/ERROR]: [Skript] Parsing block state [level=0] failed! (brewing.sk, line 80: {cauldron level} cauldron¦s = minecraft:cauldron')
[14:28:12] [Server thread/WARN]: java.lang.IllegalArgumentException: Could not parse data: minecraft:cauldron[level=0]
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.createNewData(CraftBlockData.java:550)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:525)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.newData(CraftBlockData.java:525)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createBlockData(CraftServer.java:2229)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.Bukkit.createBlockData(Bukkit.java:1759)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.bukkitutil.block.NewBlockCompat.createBlockValues(NewBlockCompat.java:357)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:277)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:702)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:602)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:120)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.load(Aliases.java:496)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.load(Aliases.java:482)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:465)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:458)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:424)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.load(Aliases.java:396)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.Skript.onEnable(Skript.java:403)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:304)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[14:28:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:28:12] [Server thread/WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:cauldron does not have property 'level' at position 19: ...:cauldron[<--[HERE]
[14:28:12] [Server thread/ERROR]: [Skript] Parsing block state [level=1] failed! (brewing.sk, line 80: {cauldron level} cauldron¦s = minecraft:cauldron')
[14:28:12] [Server thread/WARN]: java.lang.IllegalArgumentException: Could not parse data: minecraft:cauldron[level=1]
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.createNewData(CraftBlockData.java:550)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:525)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.newData(CraftBlockData.java:525)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createBlockData(CraftServer.java:2229)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.Bukkit.createBlockData(Bukkit.java:1759)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.bukkitutil.block.NewBlockCompat.createBlockValues(NewBlockCompat.java:357)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:277)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:702)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:602)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:120)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.load(Aliases.java:496)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.load(Aliases.java:482)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:465)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:458)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:424)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.load(Aliases.java:396)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.Skript.onEnable(Skript.java:403)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:304)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[14:28:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:28:12] [Server thread/WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:cauldron does not have property 'level' at position 19: ...:cauldron[<--[HERE]
[14:28:12] [Server thread/ERROR]: [Skript] Parsing block state [level=2] failed! (brewing.sk, line 80: {cauldron level} cauldron¦s = minecraft:cauldron')
[14:28:12] [Server thread/WARN]: java.lang.IllegalArgumentException: Could not parse data: minecraft:cauldron[level=2]
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.createNewData(CraftBlockData.java:550)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:525)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.newData(CraftBlockData.java:525)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createBlockData(CraftServer.java:2229)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.Bukkit.createBlockData(Bukkit.java:1759)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.bukkitutil.block.NewBlockCompat.createBlockValues(NewBlockCompat.java:357)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:277)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:702)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:602)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:120)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.load(Aliases.java:496)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.load(Aliases.java:482)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:465)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:458)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:424)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.load(Aliases.java:396)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.Skript.onEnable(Skript.java:403)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:304)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[14:28:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:28:12] [Server thread/WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:cauldron does not have property 'level' at position 19: ...:cauldron[<--[HERE]
[14:28:12] [Server thread/ERROR]: [Skript] Parsing block state [level=3] failed! (brewing.sk, line 80: {cauldron level} cauldron¦s = minecraft:cauldron')
[14:28:12] [Server thread/WARN]: java.lang.IllegalArgumentException: Could not parse data: minecraft:cauldron[level=3]
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.createNewData(CraftBlockData.java:550)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:525)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.newData(CraftBlockData.java:525)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createBlockData(CraftServer.java:2229)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.Bukkit.createBlockData(Bukkit.java:1759)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.bukkitutil.block.NewBlockCompat.createBlockValues(NewBlockCompat.java:357)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:277)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:702)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:602)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:120)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.load(Aliases.java:496)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.load(Aliases.java:482)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:465)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:458)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:424)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.load(Aliases.java:396)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.Skript.onEnable(Skript.java:403)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:304)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[14:28:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:28:12] [Server thread/WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:cauldron does not have property 'level' at position 19: ...:cauldron[<--[HERE]
[14:28:12] [Server thread/ERROR]: [Skript] Parsing block state [level=3] failed! (brewing.sk, line 80: {cauldron level} cauldron¦s = minecraft:cauldron')
[14:28:12] [Server thread/WARN]: java.lang.IllegalArgumentException: Could not parse data: minecraft:cauldron[level=3]
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.createNewData(CraftBlockData.java:550)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:525)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.newData(CraftBlockData.java:525)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createBlockData(CraftServer.java:2229)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.Bukkit.createBlockData(Bukkit.java:1759)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.bukkitutil.block.NewBlockCompat.createBlockValues(NewBlockCompat.java:357)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:277)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:702)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:602)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:120)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.load(Aliases.java:496)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.load(Aliases.java:482)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:465)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[14:28:12] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:458)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:424)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.aliases.Aliases.load(Aliases.java:396)
[14:28:12] [Server thread/WARN]: 	at ch.njol.skript.Skript.onEnable(Skript.java:403)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[14:28:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:304)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
[14:28:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[14:28:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:28:12] [Server thread/WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:cauldron does not have property 'level' at position 19: ...:cauldron[<--[HERE]
[14:28:12] [ForkJoinPool.commonPool-worker-19/INFO]: [Skript] You're currently running the latest stable version of Skript.
[14:28:14] [Server thread/ERROR]: [Skript] Minecraft id minecraft:grass_path is not valid (decoration.sk, line 416: grass path [block]¦s = minecraft:grass_path')
[14:28:14] [Server thread/ERROR]: [Skript] Minecraft id minecraft:grass_path is not valid (decoration.sk, line 416: grass path [block]¦s = minecraft:grass_path')
`

**Comment by Romitou** [comment]
MC 1.17 is not supported yet

**Comment by CowtealM** [comment]
> MC 1.17 is not supported yet.

I understand, just providing the error in case it helps in the updating
