### ISSUE TITLE
Texture pack does not work / Pack de texturas no funciona

### ISSUE THREAD

**Issue by Elmonocucuy** [SkriptLang/Skript#4133]
[Skript] Enabling Skript v2.5.3
[20:01:40 ERROR]: [Skript] Checking for updates failed. Do you have Internet connection? (brewing.sk, line 65: (splash potion[s] of {potion types}|{potion types} splash potion¦s) = minecraft:splash_potion')
[20:01:40 WARN]: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/SkriptLang/Skript/releases
[20:01:40 WARN]:        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
[20:01:40 WARN]:        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
[20:01:40 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
[20:01:40 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
[20:01:40 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[20:01:40 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[20:01:40 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[20:01:40 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[20:01:40 WARN]: Caused by: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/SkriptLang/Skript/releases
[20:01:40 WARN]:        at ch.njol.skript.update.GithubChecker.lambda$0(GithubChecker.java:114)
[20:01:40 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
[20:01:40 WARN]:        ... 5 more
[20:01:40 WARN]: Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/SkriptLang/Skript/releases
[20:01:40 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
[20:01:40 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[20:01:40 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[20:01:40 WARN]:        at java.net.URL.openStream(URL.java:1068)
[20:01:40 WARN]:        at ch.njol.skript.update.GithubChecker.lambda$0(GithubChecker.java:108)
[20:01:40 WARN]:        ... 6 more

how can we witness this bug is really pissing me off xd this happens thanks to put a texture pack in the resource pack box in server properties I have investigated and they say it is a firewall error and I have not found a solution help me out fuck

**Comment by ShaneBeee** [comment]
Closing due to not filling in the provided template, and missing useful info
