### ISSUE TITLE
Updater GitHub connection 403

### ISSUE THREAD

**Issue by Elmonocucuy** [SkriptLang/Skript#4139]
### Description
When I put my texture pack in server properties I get an error in the console that you have no internet connection, and obviously I have internet connection I have tried with plugins to automatically download the resource pack and nothing the same error I do not know what to do help

### Steps to Reproduce
First compress the .zip file and upload it to Dropbox
Second I search for server properties and paste the link to the resource pack 
Third I change the last number of the link to 1 so that it downloads automatically.
Fourth I go to the console and turn on the server.
Fifth when I finish running the server the skript plugin throws internet connection error and a lot of java errors.

### Expected Behavior
what should have happened is that the texture pack should have automatically downloaded the texture pack with the mojant screen loading and the textures should have been displayed on the screen.

### Errors / Screenshots
[10:55:34 INFO]: [Skript] Enabling Skript v2.5.3
[10:55:34 ERROR]: [Skript] Checking for updates failed. Do you have Internet connection? (brewing.sk, line 65: (splash potion[s] of {potion types}|{potion types} splash potion¦s) = minecraft:splash_potion')
[10:55:34 WARN]: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/SkriptLang/Skript/releases
[10:55:34 WARN]:        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
[10:55:34 WARN]:        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
[10:55:34 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
[10:55:34 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
[10:55:34 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[10:55:34 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[10:55:34 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[10:55:34 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[10:55:34 WARN]: Caused by: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/SkriptLang/Skript/releases
[10:55:34 WARN]:        at ch.njol.skript.update.GithubChecker.lambda$0(GithubChecker.java:114)
[10:55:34 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
[10:55:34 WARN]:        ... 5 more
[10:55:34 WARN]: Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/SkriptLang/Skript/releases
[10:55:34 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
[10:55:34 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[10:55:34 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[10:55:34 WARN]:        at java.net.URL.openStream(URL.java:1068)
[10:55:34 WARN]:        at ch.njol.skript.update.GithubChecker.lambda$0(GithubChecker.java:108)
[10:55:34 WARN]:        ... 6 more

Screenshots of bugs visible in-game can also be attached.
![image](https://user-images.githubusercontent.com/86699970/124009428-352d7400-d9a3-11eb-96fe-3ee7e11dc233.png)

Version:1.16.5/ sparkedhots
skript: v2.5.3

**Comment by TPGamesNL** [comment]
My guess would be that you're being rate limited by GitHub, as they only allow 60 requests per hour when unauthenticated. This limit is kept track of by using the originating IP, so if there are multiple servers on the same IP, or if there's other code on the server (or any other application with that IP) that connects to GitHub without authentication, this rate limit isn't hard to reach.

**Comment by Elmonocucuy** [comment]
> Supongo que GitHub te limita la tasa, ya que solo permiten 60 solicitudes por hora cuando no están autenticadas. Se realiza un seguimiento de este límite mediante el uso de la IP de origen, por lo que si hay varios servidores en la misma IP, o si hay otro código en el servidor (o cualquier otra aplicación con esa IP) que se conecta a GitHub sin autenticación, este límite de velocidad no es difícil de alcanzar.

So what do I do xd with my mistake

**Comment by TPGamesNL** [comment]
Are there other servers running on the same IP (so not a dedicated IP)?
Do you have other software running on the server / machine (/ network) that make unauthenticated connections to GitHub? For example, other servers with Skript on the same network, with the same IP.

**Comment by TPGamesNL** [comment]
Closing due to lack of response
