### ISSUE TITLE
resource pack

### ISSUE THREAD

**Issue by Elmonocucuy** [SkriptLang/Skript#4140]
### Server Information
Version:1.16.5/ sparkedhots
skript: v2.5.3

**Comment by TPGamesNL** [comment]
Duplicate of #4139
If you have new information, please edit your original issue

**Comment by Elmonocucuy** [comment]
### Description
When I put my texture pack in server properties I get an error in the console that you have no internet connection, and obviously I have internet connection I have tried with plugins to automatically download the resource pack and nothing the same error I do not know what to do help

### Steps to Reproduce
First compress the .zip file and upload it to Dropbox
Second I search for server properties and paste the link to the resource pack 
Third I change the last number of the link to 1 so that it downloads automatically.
Fourth I go to the console and turn on the server.
Fifth when I finish running the server the skript plugin throws internet connection error and a lot of java errors.

### Expected Behavior
what should have happened is that the texture pack should have automatically downloaded the texture pack with the mojant screen loading and the textures should have been displayed on the screen.

### Errors / Screenshots
[10:55:34 INFO]: [Skript] Enabling Skript v2.5.3
[10:55:34 ERROR]: [Skript] Checking for updates failed. Do you have Internet connection? (brewing.sk, line 65: (splash potion[s] of {potion types}|{potion types} splash potion¦s) = minecraft:splash_potion')
[10:55:34 WARN]: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/SkriptLang/Skript/releases
[10:55:34 WARN]:        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
[10:55:34 WARN]:        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
[10:55:34 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
[10:55:34 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
[10:55:34 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[10:55:34 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[10:55:34 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[10:55:34 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[10:55:34 WARN]: Caused by: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/SkriptLang/Skript/releases
[10:55:34 WARN]:        at ch.njol.skript.update.GithubChecker.lambda$0(GithubChecker.java:114)
[10:55:34 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
[10:55:34 WARN]:        ... 5 more
[10:55:34 WARN]: Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/SkriptLang/Skript/releases
[10:55:34 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
[10:55:34 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[10:55:34 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[10:55:34 WARN]:        at java.net.URL.openStream(URL.java:1068)
[10:55:34 WARN]:        at ch.njol.skript.update.GithubChecker.lambda$0(GithubChecker.java:108)
[10:55:34 WARN]:        ... 6 more




Screenshots of bugs visible in-game can also be attached.
![image](https://user-images.githubusercontent.com/86699970/124009428-352d7400-d9a3-11eb-96fe-3ee7e11dc233.png)




Version:1.16.5/ sparkedhots
skript: v2.5.3


### Additional Context
