### ISSUE TITLE
When I put some plugins that use "ProtocolLib" in the script version 2.6.1, I get an error.

### ISSUE THREAD

**Issue by startree236** [SkriptLang/Skript#4169]
### Skript/Server Version

```
[02:07:44 INFO]: [Skript] Skript의 별명은 여기에서 찾을 수 있습니다: https://github.com/SkriptLang/skript-aliases
[02:07:44 INFO]: [Skript] Skript의 문서는 여기에서 찾을 수 있습니다: https://skriptlang.github.io/Skript
[02:07:44 INFO]: [Skript] 서버 버전: git-Paper-1618 (MC: 1.12.2)
[02:07:44 INFO]: [Skript] Skript 버전: 2.6-beta2
[02:07:44 INFO]: [Skript] 설치된 Skript 애드온:
[02:07:44 INFO]: [Skript]  - Skellett v1.9.6b (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/)
[02:07:44 INFO]: [Skript]  - skript-yaml v1.3.2
[02:07:44 INFO]: [Skript]  - HolographicDisplaysAddon v1.0.0b
[02:07:44 INFO]: [Skript]  - skRayFall v1.9.18 (https://sk.rayfall.net/)
[02:07:44 INFO]: [Skript]  - SkBee v1.5.0 (https://github.com/ShaneBeee/SkBee)
[02:07:44 INFO]: [Skript]  - HiddenHologramSK v1.0
[02:07:44 INFO]: [Skript]  - MundoSK v1.8.6-BETA.57 (https://forums.skunity.com/resources/mundosk.69/)
[02:07:44 INFO]: [Skript]  - SkEtcR v3.1
[02:07:44 INFO]: [Skript]  - MarSkRebirth v1.0.3
[02:07:44 INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[02:07:44 INFO]: [Skript]  - SkQuery v3.6.5
[02:07:44 INFO]: [Skript]  - skript-mirror v2.0.0-SNAPSHOT (https://github.com/btk5h/skript-mirror)
[02:07:44 INFO]: [Skript]  - ThatPacketAddon v1.0-BETA.3 (tlatoani.us/thatpacketaddon)
[02:07:44 INFO]: [Skript]  - skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo)
[02:07:44 INFO]: [Skript]  - SkStuff v1.6.4.1-fork-1.12
```

### Bug Description

Adding a plugin that uses "ProtocolLib" gives an error when reloading the script.
For example, there is a plugin called "TabList".
A plugin called "Tablist" worked fine with the script version 2.4.1.
For reference, the error log below is part of many script files.

https://www.spigotmc.org/resources/animated-tab-tablist.46229/

### Expected Behavior

As the server reloads, there should be no errors and the script should work normally.

### Steps to Reproduce

I put and experimented with several plugins that use "ProtocolLib".
As an example, when I put a plug-in called "TabList", an error occurred.

https://www.spigotmc.org/resources/animated-tab-tablist.46229/

### Errors or Screenshots

```
[02:15:41 ERROR]: #!#!
[02:15:41 ERROR]: #!#! [Skript] Severe Error:
[02:15:41 ERROR]: #!#! Could not load ability.sk
[02:15:41 ERROR]: #!#!
[02:15:41 ERROR]: #!#! Something went horribly wrong with Skript.
[02:15:41 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[02:15:41 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[02:15:41 ERROR]: #!#! Here is full list of them:
[02:15:41 ERROR]: #!#! skRayFall v1.9.18 (https://sk.rayfall.net/) SpellSK v1.0-SNAPSHOT (https://github.com/vjh0107) skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo) ThatPacketAddon v1.0-BETA.3 (tlatoani.us/thatpacketaddon) MundoSK v1.8.6-BETA.57 (https://forums.skunity.com/resources/mundosk.69/) Skellett v1.9.6b (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) HiddenHologramSK v1.0 skript-mirror v2.0.0-SNAPSHOT (https://github.com/btk5h/skript-mirror) MarSkRebirth v1.0.3 SkEtcR v3.1 SkStuff v1.6.4.1-fork-1.12 skUtilities v0.9.2 (https://tim740.github.io/) SkBee v1.5.0 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.3.2 SkQuery v3.6.5 HolographicDisplaysAddon v1.0.0b
[02:15:41 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[02:15:41 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[02:15:41 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[02:15:41 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[02:15:41 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[02:15:41 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[02:15:41 ERROR]: #!#!
[02:15:41 ERROR]: #!#! Stack trace:
[02:15:41 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for hologramline
[02:15:41 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:265)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1683)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1650)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1398)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:518)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:795)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1414)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1410)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:57)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1120)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:46)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:138)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:733)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$5(ScriptLoader.java:533)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:420)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:436)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:532)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1066)
[02:15:41 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:165)
[02:15:41 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[02:15:41 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[02:15:41 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[02:15:41 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[02:15:41 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463)
[02:15:41 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[02:15:41 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[02:15:41 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[02:15:41 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[02:15:41 ERROR]: #!#!
[02:15:41 ERROR]: #!#! Version Information:
[02:15:41 ERROR]: #!#!   Skript: 2.6-beta2 (latest)
[02:15:41 ERROR]: #!#!     Flavor: skriptlang-github
[02:15:41 ERROR]: #!#!     Date: 08:57:41.422360
[02:15:41 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[02:15:41 ERROR]: #!#!   Minecraft: 1.12.2
[02:15:41 ERROR]: #!#!   Java: 1.8.0_291 (Java HotSpot(TM) 64-Bit Server VM 25.291-b10)
[02:15:41 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[02:15:41 ERROR]: #!#!
[02:15:41 ERROR]: #!#! Server platform: Paper
[02:15:41 ERROR]: #!#!
[02:15:41 ERROR]: #!#! Current node: set {_item} to {_p}'s tool (ability.sk, line 5)
[02:15:41 ERROR]: #!#! Current item: null
[02:15:41 ERROR]: #!#!
[02:15:41 ERROR]: #!#! Thread: Server thread
[02:15:41 ERROR]: #!#!
[02:15:41 ERROR]: #!#! Language: english
[02:15:41 ERROR]: #!#! Link parse mode: DISABLED
[02:15:41 ERROR]: #!#!
[02:15:41 ERROR]: #!#! End of Error.
[02:15:41 ERROR]: #!#!
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
That error is caused by an addon, not by Skript
