### ISSUE TITLE
Error saving visual effect

### ISSUE THREAD

**Issue by toonystank** [SkriptLang/Skript#4196]
### Skript/Server Version

[15:58:50 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[15:58:50 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[15:58:50 INFO]: [Skript] Server Version: git-Purpur-1271 (MC: 1.17.1)
[15:58:50 INFO]: [Skript] Skript Version: 2.6-beta2
[15:58:50 INFO]: [Skript] Installed Skript Addons:
[15:58:50 INFO]: [Skript]  - skript-placeholders v1.5 (https://github.com/APickledWalrus/skript-placeholders)
[15:58:50 INFO]: [Skript]  - skRayFall v1.9.26 (https://sk.rayfall.net/)
[15:58:50 INFO]: [Skript]  - SkQuery v4.1.5
[15:58:50 INFO]: [Skript]  - SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee)

### Bug Description

Error on using virtual effect as command argument type 

### Expected Behavior

Argument to work without error

### Steps to Reproduce

command /test [<visual effect>] [<text>]

### Errors or Screenshots

java.lang.NoClassDefFoundError: ch/njol/skript/util/VisualEffect
        at net.rayfall.eyesniper2.skrayfall.effectlibsupport.EffEffectLibText.execute(EffEffectLibText.kt:54) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:51) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:289) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250) ~[?:?]
        at ch.njol.skript.command.Commands.handleCommand(Commands.java:258) ~[?:?]
        at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:175) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1271]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1271]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1271]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2293) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2112) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2093) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1422) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1369) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[patched_1.17.1.jar:git-Purpur-1271]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1271]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! [Skript] Severe Error:
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! Something went horribly wrong with Skript.
[15:54:32 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:54:32 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:54:32 ERROR]: #!#! Here is full list of them:
[15:54:32 ERROR]: #!#! skript-placeholders v1.5 (https://github.com/APickledWalrus/skript-placeholders) skRayFall v1.9.26 (https://sk.rayfall.net/) SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee) SkQuery v4.1.5 DiscordSRV v1.23.0 (https://github.com/DiscordSRV/DiscordSRV) 
[15:54:32 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[15:54:32 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:54:32 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:54:32 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:54:32 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:54:32 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! Stack trace:
[15:54:32 ERROR]: #!#! java.io.NotSerializableException: ch.njol.skript.util.visual.VisualEffectType
[15:54:32 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:174)
[15:54:32 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249)
[15:54:32 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:199)
[15:54:32 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.serialize(Classes.java:730)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.variables.Variables.serialize(Variables.java:527)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.variables.Variables.serialize(Variables.java:521)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.variables.Variables.saveVariableChange(Variables.java:531)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.variables.Variables.setVariable(Variables.java:364)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.variables.Variables.setVariable(Variables.java:355)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.lang.Variable.set(Variable.java:441)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.lang.Variable.change(Variable.java:497)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:289)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250)
[15:54:32 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:194)
[15:54:32 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:54:32 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[15:54:32 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2301)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2112)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2093)
[15:54:32 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[15:54:32 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[15:54:32 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:54:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[15:54:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1422)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[15:54:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1400)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1393)
[15:54:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1369)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1280)
[15:54:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[15:54:32 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! Version Information:
[15:54:32 ERROR]: #!#!   Skript: 2.6-beta2 (latest)
[15:54:32 ERROR]: #!#!     Flavor: skriptlang-github
[15:54:32 ERROR]: #!#!     Date: 08:57:41.422360
[15:54:32 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[15:54:32 ERROR]: #!#!   Minecraft: 1.17.1
[15:54:32 ERROR]: #!#!   Java: 16.0.1 (OpenJDK 64-Bit Server VM 16.0.1+9-24)
[15:54:32 ERROR]: #!#!   OS: Linux amd64 5.8.0-1036-azure
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! Server platform: Paper
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! Current node: null
[15:54:32 ERROR]: #!#! Current item: null
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! Thread: Server thread
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! Language: english
[15:54:32 ERROR]: #!#! Link parse mode: DISABLED
[15:54:32 ERROR]: #!#! 
[15:54:32 ERROR]: #!#! End of Error.
[15:54:32 ERROR]: #!#! 

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Can you send the code that caused this error (the command)?

**Comment by toonystank** [comment]
it works fine on other versions but here you go

`command /particletext [<text>] [<text>] [<text>] [<visual effect>] [<text>]:
    aliases: /pt, /ptext
    permission: ptext.admin
    trigger:
        set {_id} to arg-2
        # create custom effect
        if arg-1 is "create":
            if player has permission "Particletext.create" or "particletext.admin":
                if arg-2 is set:
                    if arg-3 is set:
                        if arg-4 is set:
                            if arg-5 is set:
                                set {v::id::%arg-2%} to arg-4
                                set {s::id::%arg-2%} to arg-3
                                set {t::id::%arg-2%} to arg-5
                                set {l::id::%arg-2%} to player's location
                                if {ids::*} contains arg-2:
                                    message "{@prefix}  {@alreadyexist}"
                                else:
                                    add arg-2 to {ids::*}
                                    set {_text} to 1
                                    loop 4 times:
                                        add 1 to {_text}
                                        message "t%{_text}% id%{_id}%" to all players
                                        create a text effect with text "%{t::id::%arg-2%}%" as arg-4 at {l::id::%arg-2%} with id "%{_text}%%{_id}%" and {s::id::%arg-2%} large
                                        wait 10 ticks
                                    message "{@prefix} {@created}"`

**Comment by TPGamesNL** [comment]
Probably fixed by #4123

**Comment by UsainSrht** [comment]
Continues on 1.18-1.19

**Comment by aRandomMenno** [comment]
Continues in 1.21
