### ISSUE TITLE
WorldGuard 6 module does not build to Java 8

### ISSUE THREAD

**Issue by olgio** [SkriptLang/Skript#4211]
### Skript/Server Version

```
[17:05:57 ERROR]: #!#! Version Information:
[17:05:57 ERROR]: #!#!   Skript: 2.6-beta2 (latest)
[17:05:57 ERROR]: #!#!     Flavor: skriptlang-github
[17:05:57 ERROR]: #!#!     Date: 08:57:41.422360
[17:05:57 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[17:05:57 ERROR]: #!#!   Minecraft: 1.12.2
[17:05:57 ERROR]: #!#!   Java: 11.0.11 (OpenJDK 64-Bit Server VM 11.0.11+9)
[17:05:57 ERROR]: #!#!   OS: Linux amd64 4.4.0-104-generic
```

### Bug Description

I can't start the server on java 11 with the latest version of Script

### Expected Behavior

Everything works correctly on version 2.5.3 and I didn't find any mention of raising the minimum java version to 16 in changelog

### Steps to Reproduce

The problem occurs when starting the server on Java 11 and wg6

### Errors or Screenshots

```
[17:05:57 ERROR]: [Skript] Error while loading plugin hooks
[17:05:57 ERROR]: #!#!
[17:05:57 ERROR]: #!#! [Skript] Severe Error:
[17:05:57 ERROR]: #!#!
[17:05:57 ERROR]: #!#! Something went horribly wrong with Skript.
[17:05:57 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:05:57 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[17:05:57 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[17:05:57 ERROR]: #!#!
[17:05:57 ERROR]: #!#! Stack trace:
[17:05:57 ERROR]: #!#! java.lang.reflect.InvocationTargetException
[17:05:57 ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:05:57 ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[17:05:57 ERROR]: #!#!     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:05:57 ERROR]: #!#!     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[17:05:57 ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:500)
[17:05:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[17:05:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[17:05:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[17:05:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[17:05:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[17:05:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[17:05:57 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:829)
[17:05:57 ERROR]: #!#! Caused by: java.lang.UnsupportedClassVersionError: ch/njol/skript/module/worldguard6/WorldGuard6Hook has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
[17:05:57 ERROR]: #!#!     at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[17:05:57 ERROR]: #!#!     at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
[17:05:57 ERROR]: #!#!     at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
[17:05:57 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152)
[17:05:57 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:189)
[17:05:57 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:115)
[17:05:57 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[17:05:57 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[17:05:57 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[17:05:57 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[17:05:57 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:398)
[17:05:57 ERROR]: #!#!     at ch.njol.skript.hooks.regions.WorldGuardHook.init(WorldGuardHook.java:65)
[17:05:57 ERROR]: #!#!     at ch.njol.skript.hooks.Hook.<init>(Hook.java:50)
[17:05:57 ERROR]: #!#!     at ch.njol.skript.hooks.regions.RegionsPlugin.<init>(RegionsPlugin.java:46)
[17:05:57 ERROR]: #!#!     at ch.njol.skript.hooks.regions.WorldGuardHook.<init>(WorldGuardHook.java:59)
[17:05:57 ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:05:57 ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[17:05:57 ERROR]: #!#!     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:05:57 ERROR]: #!#!     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[17:05:57 ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:500)
[17:05:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[17:05:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[17:05:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[17:05:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[17:05:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[17:05:57 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[17:05:57 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:829)
[17:05:57 ERROR]: #!#!
[17:05:57 ERROR]: #!#! Version Information:
[17:05:57 ERROR]: #!#!   Skript: 2.6-beta2 (latest)
[17:05:57 ERROR]: #!#!     Flavor: skriptlang-github
[17:05:57 ERROR]: #!#!     Date: 08:57:41.422360
[17:05:57 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[17:05:57 ERROR]: #!#!   Minecraft: 1.12.2
[17:05:57 ERROR]: #!#!   Java: 11.0.11 (OpenJDK 64-Bit Server VM 11.0.11+9)
[17:05:57 ERROR]: #!#!   OS: Linux amd64 4.4.0-104-generic
[17:05:57 ERROR]: #!#!
[17:05:57 ERROR]: #!#! Server platform: Paper
[17:05:57 ERROR]: #!#!
[17:05:57 ERROR]: #!#! Current node: null
[17:05:57 ERROR]: #!#! Current item: null
[17:05:57 ERROR]: #!#!
[17:05:57 ERROR]: #!#! Thread: Server thread
[17:05:57 ERROR]: #!#!
[17:05:57 ERROR]: #!#! Language: english
[17:05:57 ERROR]: #!#! Link parse mode: DISABLED
[17:05:57 ERROR]: #!#!
[17:05:57 ERROR]: #!#! End of Error.
[17:05:57 ERROR]: #!#!
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
The worldguard 6 module does not compile to Java 8 in itself, it needs this code:
https://github.com/SkriptLang/Skript/blob/6e7eca0d609fdbc8bbb4b1d3fad484f43a45f612/build.gradle#L14-L16
