### ISSUE TITLE
A Spaming Warning message

### ISSUE THREAD

**Issue by LowScarlet** [SkriptLang/Skript#4224]
### Skript/Server Version

```
[06:04:31 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[06:04:31 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[06:04:31 INFO]: [Skript] Server Version: git-Purpur-1292 (MC: 1.17.1)
[06:04:31 INFO]: [Skript] Skript Version: 2.6-beta2
[06:04:31 INFO]: [Skript] Installed Skript Addons:
[06:04:31 INFO]: [Skript]  - Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/)
[06:04:31 INFO]: [Skript]  - skript-gui v1.3-alpha1 (https://github.com/APickledWalrus/skript-gui)
[06:04:31 INFO]: [Skript]  - skript-yaml v1.4
[06:04:31 INFO]: [Skript]  - HolographicDisplaysAddon v1.0.0b
[06:04:31 INFO]: [Skript]  - skRayFall v1.9.26 (https://sk.rayfall.net/)
[06:04:31 INFO]: [Skript]  - SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee)
[06:04:31 INFO]: [Skript]  - skript-placeholders v1.5.1 (https://github.com/APickledWalrus/skript-placeholders)
[06:04:31 INFO]: [Skript]  - AdvancementsAddon v1.0.0
[06:04:31 INFO]: [Skript]  - DiSky v2.2 (https://disky.itsthesky.info/)
[06:04:31 INFO]: [Skript]  - skDragon v0.17
[06:04:31 INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[06:04:31 INFO]: [Skript]  - skript-reflect v2.2.2-dev (https://github.com/TPGamesNL/skript-reflect)
[06:04:31 INFO]: [Skript]  - Reqn v1.2.4
[06:04:31 INFO]: [Skript]  - SkQuery v4.1.5
[06:04:31 INFO]: [Skript]  - Skript-Paper v1.3.0 (https://github.com/ShaneBeee/Skript-Paper)
```

### Bug Description

Warning that spams the console server

### Expected Behavior

isn't normally the message not there?

### Steps to Reproduce

nothing

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/64282946/126940486-23eb0c09-5b4a-4bf0-b1a4-6d32f7fb7e88.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Can you find out which code causes this exception?

**Comment by LowScarlet** [comment]
> Can you find out which code causes this exception?

Sorry I can't, should i close this issue?

**Comment by LowScarlet** [comment]
or I can give you all the scripts/ if you want to find the cause, of course I can only give you via private message

**Comment by DelayedGaming** [comment]
Instead, disable all scripts and load scripts one by one with an interval between each script load.

**Comment by TPGamesNL** [comment]
I'm not going to go through all your scripts myself, you can try to use the tactic above (load scripts one by one, see when errors appear) to narrow down the issue.

Skript is trying to serialize a value a number type, not natively supported by Yggdrasil (such as `AtomicInteger` or `BigDecimal`) which causes the exception. This is probably an addon's fault, I don't think any Skript expressions return those types.

**Comment by TPGamesNL** [comment]
@LowScarlet you can also use the nightly build from #4243 to test, as the exception from that build will include which variable this is caused by. If you do, please share the full stack trace here as well!

**Comment by LowScarlet** [comment]
> @LowScarlet you can also use the nightly build from #4243 to test, as the exception from that build will include which variable this is caused by. If you do, please share the full stack trace here as well!

Since I've used that build there haven't been any errors like that anymore, but maybe it's just a coincidence because the error time is so random

**Comment by LowScarlet** [comment]
got it
```vb
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! [Skript] Severe Error:
[13:49:00 ERROR]: #!#! Error saving variable named balance_cache::player::aem_michael::collectedhighest
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! You're running a (buggy) nightly version of Skript.
[13:49:00 ERROR]: #!#! If this is not a test server, switch to a more stable release NOW!
[13:49:00 ERROR]: #!#! Your players are unlikely to appreciate crashes and/or data loss due to Skript bugs.
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! Just testing things? Good. Please report this bug, so that we can fix it before a stable release.
[13:49:00 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! Stack trace:
[13:49:00 ERROR]: #!#! ch.njol.skript.SkriptAPIException: Serializer of number must override newInstance(), canBeInstantiated() or mustSyncDeserialization() if its class does not have a nullary constructor
[13:49:00 ERROR]: #!#!     at ch.njol.skript.classes.Serializer.newInstance(Serializer.java:79)
[13:49:00 ERROR]: #!#!     at ch.njol.yggdrasil.Yggdrasil.newInstance(Yggdrasil.java:335)
[13:49:00 ERROR]: #!#!     at ch.njol.yggdrasil.Yggdrasil.isSerializable(Yggdrasil.java:154)
[13:49:00 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:173)
[13:49:00 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249)
[13:49:00 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.serialize(Classes.java:730)
[13:49:00 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:440)
[13:49:00 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:432)
[13:49:00 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:432)
[13:49:00 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:432)
[13:49:00 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.saveVariables(FlatFileStorage.java:386)
[13:49:00 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage$1.run(FlatFileStorage.java:198)
[13:49:00 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:49:00 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:49:00 ERROR]: #!#!     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:49:00 ERROR]: #!#!     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[13:49:00 ERROR]: #!#!     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[13:49:00 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! Version Information:
[13:49:00 ERROR]: #!#!   Skript: 2.6-beta2-nightly-e5a66a2
[13:49:00 ERROR]: #!#!     Flavor: skriptlang-nightly
[13:49:00 ERROR]: #!#!     Date: 17:56:20.536411573
[13:49:00 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[13:49:00 ERROR]: #!#!   Minecraft: 1.17.1
[13:49:00 ERROR]: #!#!   Java: 16.0.2 (OpenJDK 64-Bit Server VM 16.0.2+7-67)
[13:49:00 ERROR]: #!#!   OS: Linux amd64 5.4.0-1045-aws
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! Server platform: Paper
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! Current node: null
[13:49:00 ERROR]: #!#! Current item: null
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! Thread: Craft Scheduler Thread - 316 - Skript
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! Language: english
[13:49:00 ERROR]: #!#! Link parse mode: DISABLED
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! End of Error.
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! [Skript] Severe Error:
[13:49:00 ERROR]: #!#! Error saving variable named balance_cache::player::ranginggod::collectedhighest
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! You're running a (buggy) nightly version of Skript.
[13:49:00 ERROR]: #!#! If this is not a test server, switch to a more stable release NOW!
[13:49:00 ERROR]: #!#! Your players are unlikely to appreciate crashes and/or data loss due to Skript bugs.
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! Just testing things? Good. Please report this bug, so that we can fix it before a stable release.
[13:49:00 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! Stack trace:
[13:49:00 ERROR]: #!#! ch.njol.skript.SkriptAPIException: Serializer of number must override newInstance(), canBeInstantiated() or mustSyncDeserialization() if its class does not have a nullary constructor
[13:49:00 ERROR]: #!#!     at ch.njol.skript.classes.Serializer.newInstance(Serializer.java:79)
[13:49:00 ERROR]: #!#!     at ch.njol.yggdrasil.Yggdrasil.newInstance(Yggdrasil.java:335)
[13:49:00 ERROR]: #!#!     at ch.njol.yggdrasil.Yggdrasil.isSerializable(Yggdrasil.java:154)
[13:49:00 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:173)
[13:49:00 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249)
[13:49:00 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.serialize(Classes.java:730)
[13:49:00 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:440)
[13:49:00 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:432)
[13:49:00 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:432)
[13:49:00 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:432)
[13:49:00 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.saveVariables(FlatFileStorage.java:386)
[13:49:00 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage$1.run(FlatFileStorage.java:198)
[13:49:00 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:49:00 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:49:00 ERROR]: #!#!     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:49:00 ERROR]: #!#!     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[13:49:00 ERROR]: #!#!     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[13:49:00 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! Version Information:
[13:49:00 ERROR]: #!#!   Skript: 2.6-beta2-nightly-e5a66a2
[13:49:00 ERROR]: #!#!     Flavor: skriptlang-nightly
[13:49:00 ERROR]: #!#!     Date: 17:56:20.536411573
[13:49:00 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[13:49:00 ERROR]: #!#!   Minecraft: 1.17.1
[13:49:00 ERROR]: #!#!   Java: 16.0.2 (OpenJDK 64-Bit Server VM 16.0.2+7-67)
[13:49:00 ERROR]: #!#!   OS: Linux amd64 5.4.0-1045-aws
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! Server platform: Paper
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! Current node: null
[13:49:00 ERROR]: #!#! Current item: null
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! Thread: Craft Scheduler Thread - 316 - Skript
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! Language: english
[13:49:00 ERROR]: #!#! Link parse mode: DISABLED
[13:49:00 ERROR]: #!#! 
[13:49:00 ERROR]: #!#! End of Error.
[13:49:00 ERROR]: #!#! 
```

**Comment by TPGamesNL** [comment]
@LowScarlet You can see at the top, the variable is `{balance_cache::player::aem_michael::collectedhighest}`. Can you show the code involving this variable?

**Comment by TPGamesNL** [comment]
Closing due to lack of response
