### ISSUE TITLE
Severe Error: FileNotFoundException

### ISSUE THREAD

**Issue by Brostrod** [SkriptLang/Skript#4231]
### Skript/Server Version

[20:31:52 INFO]: §7[§6Skript§7]§r Skript's aliases can be found here: §3https://github.com/SkriptLang/skript-aliases
[20:31:52 INFO]: §7[§6Skript§7]§r Skript's documentation can be found here: §3https://skriptlang.github.io/Skript
[20:31:52 INFO]: §7[§6Skript§7]§r Server Version: §3git-Paper-136 (MC: 1.17.1)
[20:31:52 INFO]: §7[§6Skript§7]§r Skript Version: §32.6-beta2
[20:31:52 INFO]: §7[§6Skript§7]§r Installed Skript Addons:

### Bug Description

Whenever I load up my Paper server I get a warning about a "FileNotFoundException" at a file in the Skript plugin folder called variables.csv with something like "(Access is denied)" following the file root (As shown in the error.)
It doesn't affect anything, my scripts run fine (Probably because they don't contain any variables.)
It does say "Severe error" though, so I think that might be somewhat problematic.

### Expected Behavior

An error doesn't appear

### Steps to Reproduce

Run paper server (Most recent version) on Windows 10
Use 1.17.1
Use Skript version 2.6-beta2
No Skript addons, only other plugin is WorldEdit

### Errors or Screenshots

Console error:
[20:25:03 ERROR]: #!#! 
[20:25:03 ERROR]: #!#! [Skript] Severe Error:
[20:25:03 ERROR]: #!#! 
[20:25:03 ERROR]: #!#! Something went horribly wrong with Skript.
[20:25:03 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:25:03 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[20:25:03 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[20:25:03 ERROR]: #!#! 
[20:25:03 ERROR]: #!#! Stack trace:
[20:25:03 ERROR]: #!#! java.io.FileNotFoundException: C:\Users\[Removed for privacy]\Desktop\Server\.\plugins\Skript\variables.csv (Access is denied)
[20:25:03 ERROR]: #!#!     at java.base/java.io.FileOutputStream.open0(Native Method)
[20:25:03 ERROR]: #!#!     at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
[20:25:03 ERROR]: #!#!     at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
[20:25:03 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.connect(FlatFileStorage.java:323)
[20:25:03 ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.load_i(FlatFileStorage.java:192)
[20:25:03 ERROR]: #!#!     at ch.njol.skript.variables.VariablesStorage.load(VariablesStorage.java:164)
[20:25:03 ERROR]: #!#!     at ch.njol.skript.variables.Variables.load(Variables.java:192)
[20:25:03 ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:566)
[20:25:03 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:25:03 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[20:25:03 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1135)
[20:25:03 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[20:25:03 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[20:25:03 ERROR]: #!#! 
[20:25:03 ERROR]: #!#! Version Information:
[20:25:03 ERROR]: #!#!   Skript: 2.6-beta2 (latest)
[20:25:03 ERROR]: #!#!     Flavor: skriptlang-github
[20:25:03 ERROR]: #!#!     Date: 08:57:41.422360
[20:25:03 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[20:25:03 ERROR]: #!#!   Minecraft: 1.17.1
[20:25:03 ERROR]: #!#!   Java: 16 (Java HotSpot(TM) 64-Bit Server VM 16+36-2231)
[20:25:03 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[20:25:03 ERROR]: #!#! 
[20:25:03 ERROR]: #!#! Server platform: Paper
[20:25:03 ERROR]: #!#! 
[20:25:03 ERROR]: #!#! Current node: null
[20:25:03 ERROR]: #!#! Current item: null
[20:25:03 ERROR]: #!#! 
[20:25:03 ERROR]: #!#! Thread: Server thread
[20:25:03 ERROR]: #!#! 
[20:25:03 ERROR]: #!#! Language: english
[20:25:03 ERROR]: #!#! Link parse mode: DISABLED
[20:25:03 ERROR]: #!#! 
[20:25:03 ERROR]: #!#! End of Error.
[20:25:03 ERROR]: #!#! 

### Other

The folder named "Server" in the stack trace is the folder the server is in, just if you need to know

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Brostrod** [comment]
Problem resolved: For some reason the variables.csv file was for some reason being opened using Microsoft Excel, converted it to open in notepad and that fixed it.

**Comment by AyhamAl-Ali** [comment]
`[20:25:03 ERROR]: #!#! java.io.FileNotFoundException: C:\Users[Removed for privacy]\Desktop\Server.\plugins\Skript\variables.csv (Access is denied)`
**(Access is denied)** Either there is a permission issue, or that file is opened in another program, can you check the files' permissions and make sure there is no other instances of the server running

**Comment by Brostrod** [comment]
Problem was solved by just letting the server use the .temp file created when the variables.csv file is inaccessible
