### ISSUE TITLE
NPE in BiomeMappings

### ISSUE THREAD

**Issue by olgio** [SkriptLang/Skript#4234]
### Skript/Server Version

```
[19:43:05 ERROR]: #!#! Version Information:
[19:43:05 ERROR]: #!#!   Skript: 2.6-beta2 (latest)
[19:43:05 ERROR]: #!#!     Flavor: skriptlang-github
[19:43:05 ERROR]: #!#!     Date: 08:57:41.422360
[19:43:05 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[19:43:05 ERROR]: #!#!   Minecraft: 1.12.2
[19:43:05 ERROR]: #!#!   Java: 11.0.11 (OpenJDK 64-Bit Server VM 11.0.11+9)
[19:43:05 ERROR]: #!#!   OS: Linux amd64 4.4.0-104-generic
[19:43:05 ERROR]: #!#!
[19:43:05 ERROR]: #!#! Server platform: Paper
```

### Bug Description

The problem occurs when loading various scripts on Paper 1.12.2. For example, for the expression

```
player's balance is less than 2.0
```

### Expected Behavior

Correct loading of scripts

### Steps to Reproduce

Use player-related expressions in scripts on version 2.6-beta2 and Paper 1.12.2

### Errors or Screenshots

```
[19:43:05 ERROR]: #!#!
[19:43:05 ERROR]: #!#! [Skript] Severe Error:
[19:43:05 ERROR]: #!#! Could not load adv2.sk
[19:43:05 ERROR]: #!#!
[19:43:05 ERROR]: #!#! Something went horribly wrong with Skript.
[19:43:05 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[19:43:05 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[19:43:05 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[19:43:05 ERROR]: #!#!
[19:43:05 ERROR]: #!#! Stack trace:
[19:43:05 ERROR]: #!#! java.lang.NullPointerException
[19:43:05 ERROR]: #!#!     at ch.njol.skript.bukkitutil.BiomeMappings.parse(BiomeMappings.java:41)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.util.BiomeUtils.parse(BiomeUtils.java:35)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.classes.data.BukkitClasses$23.parse(BukkitClasses.java:1138)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.classes.data.BukkitClasses$23.parse(BukkitClasses.java:1134)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:445)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:474)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:94)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:83)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:45)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:167)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:126)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:77)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:82)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:42)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:92)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1134)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:497)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:719)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$5(ScriptLoader.java:533)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:420)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:436)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:532)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:473)
[19:43:05 ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:748)
[19:43:05 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[19:43:05 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[19:43:05 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[19:43:05 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[19:43:05 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[19:43:05 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[19:43:05 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:829)
[19:43:05 ERROR]: #!#!
[19:43:05 ERROR]: #!#! Version Information:
[19:43:05 ERROR]: #!#!   Skript: 2.6-beta2 (latest)
[19:43:05 ERROR]: #!#!     Flavor: skriptlang-github
[19:43:05 ERROR]: #!#!     Date: 08:57:41.422360
[19:43:05 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[19:43:05 ERROR]: #!#!   Minecraft: 1.12.2
[19:43:05 ERROR]: #!#!   Java: 11.0.11 (OpenJDK 64-Bit Server VM 11.0.11+9)
[19:43:05 ERROR]: #!#!   OS: Linux amd64 4.4.0-104-generic
[19:43:05 ERROR]: #!#!
[19:43:05 ERROR]: #!#! Server platform: Paper
[19:43:05 ERROR]: #!#!
[19:43:05 ERROR]: #!#! Current node: player's balance is less than 2.0: (adv2.sk, line 4)
[19:43:05 ERROR]: #!#! Current item: null
[19:43:05 ERROR]: #!#!
[19:43:05 ERROR]: #!#! Thread: Server thread
[19:43:05 ERROR]: #!#!
[19:43:05 ERROR]: #!#! Language: english
[19:43:05 ERROR]: #!#! Link parse mode: DISABLED
[19:43:05 ERROR]: #!#!
[19:43:05 ERROR]: #!#! End of Error.
[19:43:05 ERROR]: #!#!
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Did you get any console errors during startup?

**Comment by olgio** [comment]
This problem is combined with the problem described here https://github.com/SkriptLang/Skript/issues/4211

**Comment by TPGamesNL** [comment]
In that case, this error happens only because of that error.

Because of the hook loading:
https://github.com/SkriptLang/Skript/blob/4c4920ab15e3eb00652dc0cf3d1c51ba9f4b4380/src/main/java/ch/njol/skript/Skript.java#L494-L507
an exception thrown by a hook's init method will prevent the remaining hooks from loading. We could add a try-catch around the newInstance method, but we should only capture Exceptions here, not Errors, so it would not have fixed this specific issue.

I'll leave this open for that reason: the newInstance call should be surrounded by a try catch.
