### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by MinecollYT** [SkriptLang/Skript#4266]
### Skript/Server Version

```
[21:46:06] [Server thread/INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[21:46:06] [Server thread/INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[21:46:06] [Server thread/INFO]: [Skript] Server Version: git-Paper-629 (MC: 1.16.5)
[21:46:06] [Server thread/INFO]: [Skript] Skript Version: 2.6-beta2
[21:46:06] [Server thread/INFO]: [Skript] Installed Skript Addons:
[21:46:06] [Server thread/INFO]: [Skript]  - skript-placeholders v1.5 (https://github.com/APickledWalrus/skript-placeholders)
[21:46:06] [Server thread/INFO]: [Skript]  - Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/)
[21:46:06] [Server thread/INFO]: [Skript]  - SkQuery v4.1.5
[21:46:06] [Server thread/INFO]: [Skript]  - ThatPacketAddon v1.0-BETA.3 (tlatoani.us/thatpacketaddon)
```

### Bug Description

Error occurs when trying to set a variable to MySQL query output

### Expected Behavior

Output the value(s)

### Steps to Reproduce

Run this code(or something similar): 
```
command /test:
	trigger:
		set {_SetResult::*} to objects in column "uuid" from result of query "SELECT * FROM `BUILDFFA`"
		broadcast "%{_SetResult::*}%"
```

This is the current table setup, everything else like adding rows, ... works.
![brave_zS4ZcoZMYc](https://user-images.githubusercontent.com/43142792/128765238-1da0d3ab-4deb-4719-a361-df7fc3e56c6d.png)
**update "CREATE TABLE IF NOT EXISTS `BUILDFFA` (`uuid` varchar(255), `kills` int, `tode` int)"**

### Errors or Screenshots

```
[21:43:25] [Server thread/WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
[21:43:25] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[21:43:25] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[21:43:25] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[21:43:25] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[21:43:25] [Server thread/WARN]: 	at com.mysql.cj.jdbc.result.ResultSetImpl.checkClosed(ResultSetImpl.java:464)
[21:43:25] [Server thread/WARN]: 	at com.mysql.cj.jdbc.result.ResultSetImpl.next(ResultSetImpl.java:1744)
[21:43:25] [Server thread/WARN]: 	at com.w00tmast3r.skquery.elements.expressions.ExprSQLQueryObjects.get(ExprSQLQueryObjects.java:35)
[21:43:25] [Server thread/WARN]: 	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[21:43:25] [Server thread/WARN]: 	at ch.njol.skript.effects.EffChange.execute(EffChange.java:274)
[21:43:25] [Server thread/WARN]: 	at ch.njol.skript.lang.Effect.run(Effect.java:51)
[21:43:25] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[21:43:25] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[21:43:25] [Server thread/WARN]: 	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[21:43:25] [Server thread/WARN]: 	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:289)
[21:43:25] [Server thread/WARN]: 	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250)
[21:43:25] [Server thread/WARN]: 	at ch.njol.skript.command.Commands.handleCommand(Commands.java:258)
[21:43:25] [Server thread/WARN]: 	at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:175)
[21:43:25] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:43:25] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:43:25] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:43:25] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[21:43:25] [Server thread/WARN]: 	at org.mcnative.runtime.bukkit.plugin.McNativePluginWrapperLoader.lambda$registerMethods$1(McNativePluginWrapperLoader.java:116)
[21:43:25] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:43:25] [Server thread/WARN]: 	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:38)
[21:43:25] [Server thread/WARN]: 	at org.mcnative.runtime.bukkit.plugin.event.BukkitEventExecutor.execute(BukkitEventExecutor.java:73)
[21:43:25] [Server thread/WARN]: 	at org.mcnative.runtime.bukkit.plugin.event.McNativeHandlerList.callEvents(McNativeHandlerList.java:141)
[21:43:25] [Server thread/WARN]: 	at org.mcnative.runtime.bukkit.event.McNativeBridgeEventHandler.handleCommandEvent(McNativeBridgeEventHandler.java:360)
[21:43:25] [Server thread/WARN]: 	at org.mcnative.runtime.bukkit.plugin.event.McNativeHandlerList.execute(McNativeHandlerList.java:178)
[21:43:25] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:43:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2163)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1986)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1939)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
[21:43:25] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[21:43:25] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Addon issues (SkQuery) should be reported to their addon tracker

**Comment by MinecollYT** [comment]
Oh sorry I didn't read the patch notes correctly
"- Updated to Skript 2.6-alpha1. Please make any bug reports regarding Skript in the SkriptLang issue tracker at https://github.com/SkriptLang/Skript/issues"
