### ISSUE TITLE
Expressions with time do not work in the current master branch

### ISSUE THREAD

**Issue by olgio** [SkriptLang/Skript#4285]
### Skript/Server Version

**The Skript version is compiled from the current master branch**
```
[17:07:35 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[17:07:35 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[17:07:35 INFO]: [Skript] Server Version: git-Paper-1618 (MC: 1.12.2)
[17:07:35 INFO]: [Skript] Skript Version: 2.6-beta2
[17:07:35 INFO]: [Skript] Installed Skript Addons:
```

### Bug Description

Expressions with time stop working
```
[17:06:22 INFO]: [Skript] Enabling Skript v2.6-beta2
[17:06:22 ERROR]: [Skript] '12 hours' is not a time span??s
[17:06:22 INFO]: [Skript] You're currently running a custom Skript version. No updates will be automatically installed.
```

```
[17:06:30 ERROR]: [Skript] can't understand this event: 'every 10 seconds' (adv2.sk, line 31: every 10 seconds:')
[17:06:31 ERROR]: [Skript] Can't understand this loop: 'all players' (newbie.sk, line 3: loop all players:')
[17:06:31 ERROR]: [Skript] Can't understand this loop: 'players in radius 400 of the player' (rp.sk, line 4: loop players in radius 400 of the player:')
```

### Expected Behavior

Correct loading of scripts

### Steps to Reproduce

Build the Skript version from the master branch and use it on the Paper 1.12.2

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Couldn't replicate this with the current master version of commit No. [d9943ea](https://github.com/SkriptLang/Skript/commit/d9943ea8685dbe372006017e34ba22afb61989b9)

**Code**
```v
every 10 seconds:
	broadcast "2"
	loop all players:
		broadcast "3"
	loop all players in radius 400 around "SkriptDev" parsed as player:
		broadcast "4"
```
![image](https://user-images.githubusercontent.com/20037329/129772202-21990930-2ddf-4318-b191-f6bffab796fe.png)
![image](https://user-images.githubusercontent.com/20037329/129772240-323de161-1be0-471b-9c9c-8d48534e9cd6.png)

**Comment by olgio** [comment]
Hmm, there is no problem when using an artifact from GitHub Action. The problem is only with my build, and an error also occurs when the server is turned off:
[17:58:42 ERROR]: Error occurred while disabling Skript v2.6-beta2 (Is it up to date?)
java.lang.NoClassDefFoundError: ch/njol/yggdrasil/YggdrasilOutputStream$1
        at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:232) ~[?:?]
        at ch.njol.skript.registrations.Classes.serialize(Classes.java:730) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:438) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:432) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.saveVariables(FlatFileStorage.java:386) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.close(FlatFileStorage.java:339) ~[?:?]
        at ch.njol.skript.Skript.onDisable(Skript.java:1088) ~[?:?]

Closing it
