### ISSUE TITLE
[Skript] Severe Error:

### ISSUE THREAD

**Issue by condblock** [SkriptLang/Skript#4287]
### Skript/Server Version

[08:51:29 ERROR]: #!#! [Skript] Severe Error:
[08:51:29 ERROR]: #!#!
[08:51:29 ERROR]: #!#! Something went horribly wrong with Skript.
[08:51:29 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[08:51:29 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[08:51:29 ERROR]: #!#! Here is full list of them:
[08:51:29 ERROR]: #!#! skRayFall v1.9.26 (https://sk.rayfall.net/) SkGyulAddon v1.8beta SkQuery v4.1.4 Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/) DiscordSRV v1.23.0 (https://github.com/DiscordSRV/DiscordSRV)
[08:51:29 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[08:51:29 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[08:51:29 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[08:51:29 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[08:51:29 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[08:51:29 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[08:51:29 ERROR]: #!#!
[08:51:29 ERROR]: #!#! Stack trace:
[08:51:29 ERROR]: #!#! java.lang.IllegalArgumentException: Progress must be between 0.0 and 1.0 (NaN)
[08:51:29 ERROR]: #!#!     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
[08:51:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.boss.CraftBossBar.setProgress(CraftBossBar.java:158)
[08:51:29 ERROR]: #!#!     at net.rayfall.eyesniper2.skrayfall.bossbar.EffCreateModernBossBar.execute(EffCreateModernBossBar.java:80)
[08:51:29 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[08:51:29 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[08:51:29 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[08:51:29 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[08:51:29 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:153)
[08:51:29 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:111)
[08:51:29 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[08:51:29 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[08:51:29 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[08:51:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:242)
[08:51:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:983)
[08:51:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1136)
[08:51:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1126)
[08:51:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1122)
[08:51:29 ERROR]: #!#!     at net.minecraft.world.entity.item.EntityItem.damageEntity(EntityItem.java:327)
[08:51:29 ERROR]: #!#!     at net.minecraft.world.entity.Entity.burnFromLava(Entity.java:748)
[08:51:29 ERROR]: #!#!     at net.minecraft.world.entity.Entity.entityBaseTick(Entity.java:682)
[08:51:29 ERROR]: #!#!     at net.minecraft.world.entity.Entity.tick(Entity.java:624)
[08:51:29 ERROR]: #!#!     at net.minecraft.world.entity.item.EntityItem.tick(EntityItem.java:104)
[08:51:29 ERROR]: #!#!     at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:903)
[08:51:29 ERROR]: #!#!     at net.minecraft.world.level.World.a(World.java:869)
[08:51:29 ERROR]: #!#!     at net.minecraft.server.level.WorldServer.lambda$tick$5(WorldServer.java:600)
[08:51:29 ERROR]: #!#!     at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:54)
[08:51:29 ERROR]: #!#!     at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:581)
[08:51:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1553)
[08:51:29 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[08:51:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
[08:51:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[08:51:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[08:51:29 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[08:51:29 ERROR]: #!#!
[08:51:29 ERROR]: #!#! Version Information:
[08:51:29 ERROR]: #!#!   Skript: 2.5.3 (latest)
[08:51:29 ERROR]: #!#!     Flavor: skriptlang-github
[08:51:29 ERROR]: #!#!     Date: 2020-12-11
[08:51:29 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[08:51:29 ERROR]: #!#!   Minecraft: 1.17.1
[08:51:29 ERROR]: #!#!   Java: 16.0.1 (Java HotSpot(TM) 64-Bit Server VM 16.0.1+9-24)
[08:51:29 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[08:51:29 ERROR]: #!#!
[08:51:29 ERROR]: #!#! Server platform: Paper
[08:51:29 ERROR]: #!#!
[08:51:29 ERROR]: #!#! Current node: null
[08:51:29 ERROR]: #!#! Current item: null
[08:51:29 ERROR]: #!#! Current trigger: damage (damage) (bossbarhp.sk, line 1)
[08:51:29 ERROR]: #!#!
[08:51:29 ERROR]: #!#! Thread: Server thread
[08:51:29 ERROR]: #!#!
[08:51:29 ERROR]: #!#! Language: english
[08:51:29 ERROR]: #!#! Link parse mode: DISABLED
[08:51:29 ERROR]: #!#!
[08:51:29 ERROR]: #!#! End of Error.
[08:51:29 ERROR]: #!#!

### Bug Description

lagging...

### Expected Behavior

i'm not sure...

### Steps to Reproduce

i think its plugin crash

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by wallace4BR** [comment]
`Progress must be between 0.0 and 1.0 (NaN)`
`at net.rayfall.eyesniper2.skrayfall.bossbar.EffCreateModernBossBar.execute`
you're probably setting an bossbar wrongly
