### ISSUE TITLE
Dropping 0 of an item throws IllegalArgumentException

### ISSUE THREAD

**Issue by MonkaMaczna** [SkriptLang/Skript#4315]
### Skript/Server Version

[19:34:14 INFO]: §7[§6Skript§7]§r Server Version: §3git-Paper-231 (MC: 1.17.1)
[19:34:14 INFO]: §7[§6Skript§7]§r Skript Version: §32.6-beta3

### Bug Description

I was making custom drop for monsters with random amount of dropped items. I didn't want them to always be more than 1, just to sometimes don't drop. When I set an random integer between 0 and 13 whenever monster was killed it would just cause errors and don't ever drop anything. I have tried bigger max numbers, but it still would spit out errors and no drop.

### Expected Behavior

Don't drop items only sometimes. Random integer is supposed to only sometimes make out 0 items, not always. Without Severe errors on the console would be a pretty good outcome too.

### Steps to Reproduce

Set argument with random integer with minimal of 0 and then assign it to the number of items dropped:
	set {drop.%player%} to a random integer between 0 and 13
		drop {drop.%player%} of iron ingot

### Errors or Screenshots

[17:20:50 ERROR]: #!#! 
[17:20:50 ERROR]: #!#! [Skript] Severe Error:
[17:20:50 ERROR]: #!#! 
[17:20:50 ERROR]: #!#! Something went horribly wrong with Skript.
[17:20:50 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:20:50 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[17:20:50 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[17:20:50 ERROR]: #!#! 
[17:20:50 ERROR]: #!#! Stack trace:
[17:20:50 ERROR]: #!#! java.lang.IllegalArgumentException: Cannot drop air
[17:20:50 ERROR]: #!#!     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[17:20:50 ERROR]: #!#!     at net.minecraft.world.entity.item.EntityItem.setItemStack(EntityItem.java:504)
[17:20:50 ERROR]: #!#!     at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:72)
[17:20:50 ERROR]: #!#!     at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:65)
[17:20:50 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.dropItem(CraftWorld.java:629)
[17:20:50 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.dropItemNaturally(CraftWorld.java:652)
[17:20:50 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.dropItemNaturally(CraftWorld.java:640)
[17:20:50 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffDrop.execute(EffDrop.java:89)
[17:20:50 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:51)
[17:20:50 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[17:20:50 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[17:20:50 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[17:20:50 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[17:20:50 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[17:20:50 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[17:20:50 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:20:50 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:20:50 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[17:20:50 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:858)
[17:20:50 ERROR]: #!#!     at net.minecraft.world.entity.EntityLiving.dropAllDeathLoot(EntityLiving.java:1711)
[17:20:50 ERROR]: #!#!     at net.minecraft.world.entity.EntityLiving.die(EntityLiving.java:1628)
[17:20:50 ERROR]: #!#!     at net.minecraft.world.entity.EntityLiving.damageEntity(EntityLiving.java:1456)
[17:20:50 ERROR]: #!#!     at net.minecraft.world.entity.monster.EntityZombie.damageEntity(EntityZombie.java:315)
[17:20:50 ERROR]: #!#!     at net.minecraft.world.entity.player.EntityHuman.attack(EntityHuman.java:1261)
[17:20:50 ERROR]: #!#!     at net.minecraft.server.level.EntityPlayer.attack(EntityPlayer.java:2021)
[17:20:50 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2412)
[17:20:50 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24)
[17:20:50 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[17:20:50 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2339)
[17:20:50 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[17:20:50 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[17:20:50 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[17:20:50 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:20:50 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[17:20:50 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[17:20:50 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1363)
[17:20:50 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[17:20:50 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[17:20:50 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1342)
[17:20:50 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1335)
[17:20:50 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[17:20:50 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1473)
[17:20:50 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1203)
[17:20:50 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[17:20:50 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[17:20:50 ERROR]: #!#! 
[17:20:50 ERROR]: #!#! Version Information:
[17:20:50 ERROR]: #!#!   Skript: 2.6-beta3 (latest)
[17:20:50 ERROR]: #!#!     Flavor: skriptlang-github
[17:20:50 ERROR]: #!#!     Date: 14:09:29.995077500
[17:20:50 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[17:20:50 ERROR]: #!#!   Minecraft: 1.17.1
[17:20:50 ERROR]: #!#!   Java: 16.0.2 (OpenJDK 64-Bit Server VM 16.0.2+7)
[17:20:50 ERROR]: #!#!   OS: Mac OS X aarch64 11.5.2
[17:20:50 ERROR]: #!#! 
[17:20:50 ERROR]: #!#! Server platform: Paper
[17:20:50 ERROR]: #!#! 
[17:20:50 ERROR]: #!#! Current node: null
[17:20:50 ERROR]: #!#! Current item: drop {drop.%the player%}(as java.lang.Number) of iron ingot [[direction:at]] event-location
[17:20:50 ERROR]: #!#! Current trigger: death of zombie (death of zombie) (creeper.sk, line 6)
[17:20:50 ERROR]: #!#! 
[17:20:50 ERROR]: #!#! Thread: Server thread
[17:20:50 ERROR]: #!#! 
[17:20:50 ERROR]: #!#! Language: english
[17:20:50 ERROR]: #!#! Link parse mode: DISABLED
[17:20:50 ERROR]: #!#! 
[17:20:50 ERROR]: #!#! End of Error.
[17:20:50 ERROR]: #!#! 

### Other

I was using it with an add-on SkQuery, but the outcome was the same without him. 
Full code: 
`on death of creeper:
	chance of 60%:
		drop 1 TNT
	else:
		drop sunflower named "&e&lYeet&f&lCoin" with lore "10$"
on death of zombie:
	chance of 40%:
		set {drop.%player%} to a random integer between 0 and 13
		drop {drop.%player%} of iron ingot
		set {potato.%player%} to a random integer between 0 and 1
		drop {potato.%player%} of potato named "&e&lZiemniak" with lore "Zasadź mnie :D"
		set {sword.%player%} to a random integer between 0 and 1
		drop {sword.%player%} of wooden sword named "&5&lMaster Sword" with lore "It is dangerous to go alone. Take this."
		stop
on death of skeleton:
	chance of 50%:
		set {bone.%player%} to a random integer between 0 and 5
		drop {bone.%player%} of bone named "&f&lKostki"
		set {arrow.%player%} to a random integer between 0 and 15
		drop {arrow.%player%} of arrow named "&7&lStrzały kościotrupa"
		set {yeet.%player%} to a random integer between 0 and 1
		drop {yeet.%player%} of sunflower named "e&lYeet&f&lCoin" with lore "10$"
		stop
`

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Please use this code style
![image](https://user-images.githubusercontent.com/20037329/131893091-61a158c6-af90-4110-a089-f688d6f2c15f.png)


That happens because you're dropping `0 of %itemtype%` which throws that error, not sure if this is a bug but it can be improved for sure by either making a proper error message or simply remove that error.
