### ISSUE TITLE
raw name syntax isn't working

### ISSUE THREAD

**Issue by GTNTAnimations** [SkriptLang/Skript#4336]
### Skript/Server Version

```
[12:15:10 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[12:15:10 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[12:15:10 INFO]: [Skript] Server Version: git-Paper-196 (MC: 1.17.1)
[12:15:10 INFO]: [Skript] Skript Version: 2.5.3
[12:15:10 INFO]: [Skript] Installed Skript Addons:
```

### Bug Description

```
on right click with paper:
    if name of player's tool is "Placeholder":
        broadcast "%raw name of target block%"
```
I was trying to get the raw name of the players target block because for blocks like dirt the Minecraft name is **dirt** but the skript name is **dirt block** however I got an error

### Expected Behavior

I have never used this syntax before however I would assume if the player was looking at a dirt block. it would broadcast **dirt** instead of **dirt block**

### Steps to Reproduce

Just use the code below in 1.17 paper and you'll probably get the same error

### Errors or Screenshots

```
[12:23:12 ERROR]: #!#! 
[12:23:12 ERROR]: #!#! [Skript] Severe Error:
[12:23:12 ERROR]: #!#! Could not load blocks.sk
[12:23:12 ERROR]: #!#! 
[12:23:12 ERROR]: #!#! Something went horribly wrong with Skript.
[12:23:12 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[12:23:12 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[12:23:12 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[12:23:12 ERROR]: #!#! 
[12:23:12 ERROR]: #!#! Stack trace:
[12:23:12 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "e" is null
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.base.EventValueExpression.getValue(EventValueExpression.java:98)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.base.EventValueExpression.get(EventValueExpression.java:86)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.getAll(SimpleExpression.java:74)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.base.PropertyExpression.getAll(PropertyExpression.java:78)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.ConvertedExpression.getAll(ConvertedExpression.java:170)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.ExprRawName.get(ExprRawName.java:62)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.ExprRawName.toString(ExprRawName.java:81)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.VariableString.newInstance(VariableString.java:326)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.VariableString.newInstance(VariableString.java:163)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:499)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:839)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1568)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Statement.parse(Statement.java:58)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1030)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:53)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Conditional.<init>(Conditional.java:43)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1117)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:678)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:464)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:976)
[12:23:12 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:185)
[12:23:12 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:23:12 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:23:12 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832)
[12:23:12 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2169)
[12:23:12 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1980)
[12:23:12 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1961)
[12:23:12 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:23:12 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:23:12 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[12:23:12 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:23:12 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[12:23:12 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[12:23:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[12:23:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[12:23:12 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[12:23:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[12:23:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[12:23:12 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[12:23:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1458)
[12:23:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[12:23:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[12:23:12 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[12:23:12 ERROR]: #!#! 
[12:23:12 ERROR]: #!#! Version Information:
[12:23:12 ERROR]: #!#!   Skript: 2.5.3 (latest)
[12:23:12 ERROR]: #!#!     Flavor: skriptlang-github
[12:23:12 ERROR]: #!#!     Date: 2020-12-11
[12:23:12 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[12:23:12 ERROR]: #!#!   Minecraft: 1.17.1
[12:23:12 ERROR]: #!#!   Java: 16.0.2 (Java HotSpot(TM) 64-Bit Server VM 16.0.2+7-67)
[12:23:12 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[12:23:12 ERROR]: #!#! 
[12:23:12 ERROR]: #!#! Server platform: Paper
[12:23:12 ERROR]: #!#! 
[12:23:12 ERROR]: #!#! Current node: broadcast "%vanilla name of target block%" (blocks.sk, line 10)
[12:23:12 ERROR]: #!#! Current item: null
[12:23:12 ERROR]: #!#! 
[12:23:12 ERROR]: #!#! Thread: Server thread
[12:23:12 ERROR]: #!#! 
[12:23:12 ERROR]: #!#! Language: english
[12:23:12 ERROR]: #!#! Link parse mode: DISABLED
[12:23:12 ERROR]: #!#! 
[12:23:12 ERROR]: #!#! End of Error.
[12:23:12 ERROR]: #!#! 
```

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Try to use Skript 2.6-beta3 since you're using 1.17 and let us know if this still happens

**Comment by GTNTAnimations** [comment]
Seems to be working now that I updated to the beta. Thanks!
