### ISSUE TITLE
java.lang.NoSuchMethodError: 'ch.njol.util.Kleenean ch.njol.skript.ScriptLoader.getHasDelayBefore()

### ISSUE THREAD

**Issue by bananplayss** [SkriptLang/Skript#4344]
### Skript/Server Version

Server version: PaperSpigot 1.16.5

### Bug Description

Console gave me an error at server start.

### Expected Behavior

I did nothing so everything should be all right...

### Steps to Reproduce

Once all skripts stopped working and the console gave me this. I did nothing.

### Errors or Screenshots

```
java.lang.NoSuchMethodError: 'ch.njol.util.Kleenean ch.njol.skript.ScriptLoader.getHasDelayBefore()'
        at com.github.tukenuke.tuske.util.EffectSection.loadSection(EffectSection.java:111) ~[?:?]
        at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.init(EffFormatGUI.java:65) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:251) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178) ~[?:?]
        at ch.njol.skript.lang.Condition.parse(Condition.java:80) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1110) ~[?:?]
        at ch.njol.skript.command.Commands.loadCommand(Commands.java:486) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:636) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$3(ScriptLoader.java:337) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:370) ~[?:?]
        at ch.njol.skript.Skript$2.run(Skript.java:601) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-564]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1064) ~[patched_1.16.5.jar:git-Paper-564]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-564]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
> **NOTICE**: After a lot of discussion, we have decided to drop support for 1.12 and lower, as it stops us from adding a lot of features and focusing on other parts of Skript. 2.6.x will be the last version working with 1.12 and lower. Security patches and other kind of fixes might be ported to this version, but keep in mind that features won't be added.

> **NOTICE** (as per Skript 2.6-alpha1): due to the merge of #3924, many addons might be broken by this release. If you want to make them compatible, you may use SkriptAddonPatcher or its [plugin version](https://github.com/TPGamesNL/RuntimeSkriptAddonPatcher)

**Comment by TPGamesNL** [comment]
It looks like you're using Skript 2.5.3 while also having used the addon patcher, which makes that addon compatible with Skript 2.6, not 2.5.3

**Comment by bananplayss** [comment]
If I put in Skript 2.6 they give me this error message:

[18:44:45 ERROR]: #!#! 
[18:44:45 ERROR]: #!#! [Skript] Severe Error:
[18:44:45 ERROR]: #!#! Could not load Fraki.sk
[18:44:45 ERROR]: #!#! 
[18:44:45 ERROR]: #!#! Something went horribly wrong with Skript.
[18:44:45 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[18:44:45 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[18:44:45 ERROR]: #!#! Here is full list of them:
[18:44:45 ERROR]: #!#! skRayFall v1.9.21 (https://sk.rayfall.net/) skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect) TuSKe v1.8.2-Pikachu-Patch-3 (github.com/Tuke-Nuke/TuSKe) skUtilities v0.9.2 (https://tim740.github.io/) SkQuery v4.1.5 Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/) 
[18:44:45 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[18:44:45 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[18:44:45 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[18:44:45 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[18:44:45 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[18:44:45 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[18:44:45 ERROR]: #!#! 
[18:44:45 ERROR]: #!#! Stack trace:
[18:44:45 ERROR]: #!#! java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')
[18:44:45 ERROR]: #!#!     at com.github.tukenuke.tuske.manager.gui.v2.SkriptGUIEvent.<init>(SkriptGUIEvent.java:28)
[18:44:45 ERROR]: #!#!     at com.github.tukenuke.tuske.manager.gui.v2.SkriptGUIEvent.getInstance(SkriptGUIEvent.java:24)
[18:44:45 ERROR]: #!#!     at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.init(EffFormatGUI.java:106)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:57)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1127)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:55)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:43)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1225)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:55)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:43)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1225)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:71)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1166)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:55)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:43)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1225)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:55)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:43)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1225)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:55)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:43)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1225)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:55)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:43)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.loadElseIf(Conditional.java:93)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1211)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:55)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:43)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1225)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:55)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:43)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.loadElseIf(Conditional.java:93)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1211)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:55)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:43)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.loadElseIf(Conditional.java:93)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.loadElseIf(Conditional.java:90)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1211)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:497)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:723)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$5(ScriptLoader.java:537)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:424)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:440)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:536)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:477)
[18:44:45 ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:715)
[18:44:45 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[18:44:45 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[18:44:45 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1064)
[18:44:45 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[18:44:45 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[18:44:45 ERROR]: #!#! 
[18:44:45 ERROR]: #!#! Version Information:
[18:44:45 ERROR]: #!#!   Skript: 2.6-alpha1 (custom version)
[18:44:45 ERROR]: #!#!     Flavor: selfbuilt-unknown
[18:44:45 ERROR]: #!#!     Date: unknown
[18:44:45 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[18:44:45 ERROR]: #!#!   Minecraft: 1.16.5
[18:44:45 ERROR]: #!#!   Java: 16.0.2 (OpenJDK 64-Bit Server VM 16.0.2+7-67)
[18:44:45 ERROR]: #!#!   OS: Linux amd64 5.4.0-81-generic
[18:44:45 ERROR]: #!#! 
[18:44:45 ERROR]: #!#! Server platform: Paper
[18:44:45 ERROR]: #!#! 
[18:44:45 ERROR]: #!#! Current node: create a gui slot {_s} of player with loop-player's skull named "&6%loop-player%" to run player command "/fk leader tag kirug %loop-player%" (Fraki.sk, line 227)
[18:44:45 ERROR]: #!#! Current item: null
[18:44:45 ERROR]: #!#! 
[18:44:45 ERROR]: #!#! Thread: Server thread
[18:44:45 ERROR]: #!#! 
[18:44:45 ERROR]: #!#! Language: english
[18:44:45 ERROR]: #!#! Link parse mode: DISABLED
[18:44:45 ERROR]: #!#! 
[18:44:45 ERROR]: #!#! End of Error.
[18:44:45 ERROR]: #!#!

**Comment by APickledWalrus** [comment]
TuSKe won't work on 2.6 even with the addon patcher. If you're using it for GUIs, I recommend a supported alternative such as skript-gui, or you can even use normal Skript for GUIs using events.
