### ISSUE TITLE
if null is set??

### ISSUE THREAD

**Issue by pawelkuwa** [SkriptLang/Skript#4482]
### Skript/Server Version

server:
This server is running Paper version git-Paper-792 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 2 version(s) behind
Previous version: git-Purpur-1171 (MC: 1.16.5)

skript: 2.6
addons: funnyskaddon 2.2.1

### Bug Description

problem stopping other exists events in other scripts

[20:17:58 ERROR]: #!#! [Skript] Severe Error:
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! Something went horribly wrong with Skript.
[20:17:58 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:17:58 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:17:58 ERROR]: #!#! Here is full list of them:
[20:17:58 ERROR]: #!#! skript-gui v1.3-beta1 (https://github.com/APickledWalrus/skript-gui) skript-yaml v1.4 FunnySkAddon v2.2.1 (funnyskaddon.pl)
[20:17:58 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:17:58 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:17:58 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:17:58 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:17:58 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:17:58 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! Stack trace:
[20:17:58 ERROR]: #!#! java.lang.NullPointerException: RegionUtils.getAt(this) must not be null
[20:17:58 ERROR]: #!#!     at pl.funnyskaddon.util.GuildUtilKt.getGuildAtLocation(GuildUtil.kt:58)
[20:17:58 ERROR]: #!#!     at pl.funnyskaddon.skript.expressions.guild.GuildAtLocationExpression.get(GuildAtLocationExpression.kt:33)
[20:17:58 ERROR]: #!#!     at pl.funnyskaddon.skript.expressions.guild.GuildAtLocationExpression.get(GuildAtLocationExpression.kt:19)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getAll(SimpleExpression.java:73)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.conditions.CondIsSet.check(CondIsSet.java:74)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.conditions.CondIsSet.check(CondIsSet.java:80)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.walk(SecConditional.java:165)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[20:17:58 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:17:58 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:17:58 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:359)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:318)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:208)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1650)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[20:17:58 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! Version Information:
[20:17:58 ERROR]: #!#!   Skript: 2.6 (latest)
[20:17:58 ERROR]: #!#!     Flavor: skriptlang-github
[20:17:58 ERROR]: #!#!     Date: 17:20:35.482878100
[20:17:58 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[20:17:58 ERROR]: #!#!   Minecraft: 1.16.5
[20:17:58 ERROR]: #!#!   Java: 16.0.2 (Java HotSpot(TM) 64-Bit Server VM 16.0.2+7-67)
[20:17:58 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! Server platform: Paper
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! Current node: null
[20:17:58 ERROR]: #!#! Current item: if null is set
[20:17:58 ERROR]: #!#! Current trigger: break (break/place/burn/fade/form of <none>) (test.sk, line 1)
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! Thread: Server thread
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! Language: english
[20:17:58 ERROR]: #!#! Link parse mode: DISABLED
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! End of Error.
[20:17:58 ERROR]: #!#!

### Expected Behavior

i wanted to create on break event and check guild region (funnyguilds) and variables with privileges and cancel event when execute doesn't have privileges 

full code:
`on break:
    if guild at player's location exists:
        if player has guild:
            set {_guild} to player's guild
            if event-block is in guild {_guild} region:
                if {uprawnienia.%player guild tag%.break.%player%} is not set:
                    cancel event
                    send "&8» &cNie masz uprawnien do niszczenia blokow na terenie gildii!"
                    send "&8» &cSpytaj lidera gildii o pozwolenie do niszczenia."
                    stop`

### Steps to Reproduce

I don't know i detect it on purpur 1.16.5, after switch version of jar server to paperspigot 1.16.5, trouble still exists.

### Errors or Screenshots

[20:17:58 ERROR]: #!#! [Skript] Severe Error:
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! Something went horribly wrong with Skript.
[20:17:58 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:17:58 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:17:58 ERROR]: #!#! Here is full list of them:
[20:17:58 ERROR]: #!#! skript-gui v1.3-beta1 (https://github.com/APickledWalrus/skript-gui) skript-yaml v1.4 FunnySkAddon v2.2.1 (funnyskaddon.pl)
[20:17:58 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:17:58 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:17:58 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:17:58 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:17:58 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:17:58 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! Stack trace:
[20:17:58 ERROR]: #!#! java.lang.NullPointerException: RegionUtils.getAt(this) must not be null
[20:17:58 ERROR]: #!#!     at pl.funnyskaddon.util.GuildUtilKt.getGuildAtLocation(GuildUtil.kt:58)
[20:17:58 ERROR]: #!#!     at pl.funnyskaddon.skript.expressions.guild.GuildAtLocationExpression.get(GuildAtLocationExpression.kt:33)
[20:17:58 ERROR]: #!#!     at pl.funnyskaddon.skript.expressions.guild.GuildAtLocationExpression.get(GuildAtLocationExpression.kt:19)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getAll(SimpleExpression.java:73)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.conditions.CondIsSet.check(CondIsSet.java:74)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.conditions.CondIsSet.check(CondIsSet.java:80)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.walk(SecConditional.java:165)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[20:17:58 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[20:17:58 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:17:58 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:17:58 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:359)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:318)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:208)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1650)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139)
[20:17:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[20:17:58 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! Version Information:
[20:17:58 ERROR]: #!#!   Skript: 2.6 (latest)
[20:17:58 ERROR]: #!#!     Flavor: skriptlang-github
[20:17:58 ERROR]: #!#!     Date: 17:20:35.482878100
[20:17:58 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[20:17:58 ERROR]: #!#!   Minecraft: 1.16.5
[20:17:58 ERROR]: #!#!   Java: 16.0.2 (Java HotSpot(TM) 64-Bit Server VM 16.0.2+7-67)
[20:17:58 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! Server platform: Paper
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! Current node: null
[20:17:58 ERROR]: #!#! Current item: if null is set
[20:17:58 ERROR]: #!#! Current trigger: break (break/place/burn/fade/form of <none>) (test.sk, line 1)
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! Thread: Server thread
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! Language: english
[20:17:58 ERROR]: #!#! Link parse mode: DISABLED
[20:17:58 ERROR]: #!#!
[20:17:58 ERROR]: #!#! End of Error.
[20:17:58 ERROR]: #!#!

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
That's addon issue: `FunnySkAddon` not from Skript
