### ISSUE TITLE
Skript severe error when spigot ends loading

### ISSUE THREAD

**Issue by n00neheregit** [SkriptLang/Skript#4518]
### Skript/Server Version

```
[09:01:31 ERROR]: #!#! 
[09:01:31 ERROR]: #!#! [Skript] Severe Error:
[09:01:31 ERROR]: #!#! 
[09:01:31 ERROR]: #!#! Something went horribly wrong with Skript.
[09:01:31 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[09:01:31 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[09:01:31 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[09:01:31 ERROR]: #!#! 
[09:01:31 ERROR]: #!#! Stack trace:
[09:01:31 ERROR]: #!#! org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[09:01:31 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:552)
[09:01:31 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.callSyncMethod(CraftScheduler.java:265)
[09:01:31 ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:174)
[09:01:31 ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:153)
[09:01:31 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:836)
[09:01:31 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$5(ScriptLoader.java:533)
[09:01:31 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:420)
[09:01:31 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader$AsyncLoaderThread.run(ScriptLoader.java:370)
[09:01:31 ERROR]: #!#! 
[09:01:31 ERROR]: #!#! Version Information:
[09:01:31 ERROR]: #!#!   Skript: 2.6 (latest)
[09:01:31 ERROR]: #!#!     Flavor: skriptlang-github
[09:01:31 ERROR]: #!#!     Date: 17:20:35.482878100
[09:01:31 ERROR]: #!#!   Bukkit: 1.18.1-R0.1-SNAPSHOT
[09:01:31 ERROR]: #!#!   Minecraft: 1.18.1
[09:01:31 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12-Debian-1deb11u2)
[09:01:31 ERROR]: #!#!   OS: Linux amd64 5.10.0-10-cloud-amd64
[09:01:31 ERROR]: #!#! 
[09:01:31 ERROR]: #!#! Server platform: Paper
[09:01:31 ERROR]: #!#! 
[09:01:31 ERROR]: #!#! Current node: null
[09:01:31 ERROR]: #!#! Current item: null
[09:01:31 ERROR]: #!#! 
[09:01:31 ERROR]: #!#! Thread: Thread-12
[09:01:31 ERROR]: #!#! 
[09:01:31 ERROR]: #!#! Language: english
[09:01:31 ERROR]: #!#! Link parse mode: DISABLED
[09:01:31 ERROR]: #!#! 
[09:01:31 ERROR]: #!#! End of Error.
[09:01:31 ERROR]: #!#! 

```

### Bug Description

as soon as my spigot server finish loading it shuts down and skript output the error

### Expected Behavior

skript not dying

### Steps to Reproduce

install skript
install latest paper version
start the server

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by n00neheregit** [comment]
closing the issue, i removed some plugins and it came out that it was authme giving error
