### ISSUE TITLE
Region event

### ISSUE THREAD

**Issue by OverBrave** [SkriptLang/Skript#4568]
### Skript/Server Version

```
[13:41:37 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[13:41:37 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[13:41:37 INFO]: [Skript] Server Version: git-Pufferfish-39 (MC: 1.18.1)
[13:41:37 INFO]: [Skript] Skript Version: 2.6.1-nightly-5fa019e
[13:41:37 INFO]: [Skript] Installed Skript Addons:
[13:41:37 INFO]: [Skript]  - skript-placeholders v1.5.1 (https://github.com/APickledWalrus/skript-placeholders)
[13:41:37 INFO]: [Skript]  - Skacket v1.0.7
[13:41:37 INFO]: [Skript]  - DiSky v2.3 (https://disky.itsthesky.info/)
[13:41:37 INFO]: [Skript]  - skript-yaml v1.4
[13:41:37 INFO]: [Skript]  - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
[13:41:37 INFO]: [Skript]  - skript-db v1.3.3
[13:41:37 INFO]: [Skript]  - SharpSK v1.6.13
[13:41:37 INFO]: [Skript] Installed dependencies:
[13:41:37 INFO]: [Skript]  - Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[13:41:37 INFO]: [Skript]  - WorldGuard v7.0.6+1cff55f
```

### Bug Description

```
on region enter:
    message "Entering %region%."
```

This event does not work in version 2.6.1.  This time I think I'm sure. :D

Also sometimes sending this error on console:
```
[13:21:45] [Server thread/ERROR]: #!#! Stack trace:
[13:21:45] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for sound
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:71)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[13:21:45] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1096)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1067)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:739)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1060)
[13:21:45] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[13:21:45] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[13:21:45] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[13:21:45] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2288)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2099)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2080)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1415)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1393)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1386)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1364)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1270)
[13:21:45] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319)
[13:21:45] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
```

But strangely, it works in some places. I do not understand. Maybe there is something I did wrong.

### Expected Behavior

Region entries/exites should work.

### Steps to Reproduce

```
on region enter:
    message "Entering %region%."
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Skacket is not updated to Skript 2.6.1 yet. Please report issue at https://github.com/TheLimeGlass/Skacket/issues

**Comment by OverBrave** [comment]
Oh, is it due to Skacket? These addons are giving me trouble. :D
