### ISSUE TITLE
NPE when expression with return type String is inside %%

### ISSUE THREAD

**Issue by P3ridot** [SkriptLang/Skript#4577]
### Skript/Server Version

```
[22:01:13 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[22:01:13 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[22:01:13 INFO]: [Skript] Server Version: git-Paper-1618 (MC: 1.12.2)
[22:01:13 INFO]: [Skript] Skript Version: 2.6.1
[22:01:13 INFO]: [Skript] Installed Skript Addons:
[22:01:13 INFO]: [Skript]  - FunnySkAddon v2.2.17-Beta (funnyskaddon.pl)
[22:01:13 INFO]: [Skript] Installed dependencies:
[22:01:13 INFO]: [Skript]  - Vault v1.7.3-b131
[22:01:13 INFO]: [Skript]  - WorldGuard v6.2.2-SNAPSHOT;8eeab68
```

### Bug Description

When expression is used inside %% for eg. `%player's guild name%` and return type of it is String, Skript throws NPE. When expression is used "normally" everything works perfectly

Example of expression [Link](https://github.com/FunnyGuilds/FunnySkAddon/blob/84042a5facafc9ba9eaf708d562c88df7b09f707/src/main/kotlin/pl/funnyskaddon/skript/expression/guild/GuildNameExpression.kt)

### Expected Behavior

To just work properly 

### Steps to Reproduce

For eg. using 
```send "%player's guild name%"```
doesn't work but 
```
set {_name} to player's guild name
send "%{_name}%"
``` 
works perfectly

I don't know what else I could add so...

### Errors or Screenshots

```
[22:15:26 ERROR]: #!#!
[22:15:26 ERROR]: #!#! [Skript] Severe Error:
[22:15:26 ERROR]: #!#! Could not load test.sk
[22:15:26 ERROR]: #!#!
[22:15:26 ERROR]: #!#! Something went horribly wrong with Skript.
[22:15:26 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:15:26 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:15:26 ERROR]: #!#! Here is full list of them:
[22:15:26 ERROR]: #!#! FunnySkAddon v2.2.17-Beta (funnyskaddon.pl)
[22:15:26 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[22:15:26 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:15:26 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:15:26 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:15:26 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:15:26 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[22:15:26 ERROR]: #!#!
[22:15:26 ERROR]: #!#! Stack trace:
[22:15:26 ERROR]: #!#! java.lang.NullPointerException
[22:15:26 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:295)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:131)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:521)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:800)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1302)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:61)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1113)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:489)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:707)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:468)
[22:15:26 ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:778)
[22:15:26 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[22:15:26 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[22:15:26 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[22:15:26 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[22:15:26 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[22:15:26 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[22:15:26 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:829)
[22:15:26 ERROR]: #!#!
[22:15:26 ERROR]: #!#! Version Information:
[22:15:26 ERROR]: #!#!   Skript: 2.6.1 (latest)
[22:15:26 ERROR]: #!#!     Flavor: skriptlang-github
[22:15:26 ERROR]: #!#!     Date: 22:18:42.554713200
[22:15:26 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[22:15:26 ERROR]: #!#!   Minecraft: 1.12.2
[22:15:26 ERROR]: #!#!   Java: 11.0.14 (OpenJDK 64-Bit Server VM 11.0.14+9)
[22:15:26 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[22:15:26 ERROR]: #!#!
[22:15:26 ERROR]: #!#! Server platform: Paper
[22:15:26 ERROR]: #!#!
[22:15:26 ERROR]: #!#! Current node: send "%player's guild name%" (test.sk, line 4)
[22:15:26 ERROR]: #!#! Current item: null
[22:15:26 ERROR]: #!#!
[22:15:26 ERROR]: #!#! Thread: Server thread
[22:15:26 ERROR]: #!#!
[22:15:26 ERROR]: #!#! Language: english
[22:15:26 ERROR]: #!#! Link parse mode: DISABLED
[22:15:26 ERROR]: #!#!
[22:15:26 ERROR]: #!#! End of Error.
[22:15:26 ERROR]: #!#!
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Addon issue (funnyskaddon), report to its issue tracker (check first edit history)

**Comment by P3ridot** [comment]
I'm developer of FunnySkAddon and LimeGlass told me to report it here. I don't know if it's my fault because everything with orher return types works.

This is link to response of LimeGlass on discord [Link](https://discord.com/channels/138464183946575874/213445946543964160/939074523855212594)

**Comment by TPGamesNL** [comment]
It's because your Expression's toString returns null, it's not allowed to do that (see FunnyExpression#toString). A toString method from a syntax element is supposed to return about what the input string was for the element (e.g. `"guild name of player"`), see Skript's syntax elements for examples
