### ISSUE TITLE
Severe Skript error (script loader thread size: 2)

### ISSUE THREAD

**Issue by ImNotStable** [SkriptLang/Skript#4579]
### Skript/Server Version

```
Server Version: git-Paper-184 (MC: 1.18.1)
Skript Version: 2.6.1
Installed Skript Addons: None
Installed dependencies: None
```

### Bug Description

It's just says the error when the server loads but if I reload the Skript it works fine 

I believe it's an issue with 'script loader thread size: 2' because it only appears with that I've tried using 0 and I haven't gotten that error

### Expected Behavior

This error isn't supposed to happen

### Steps to Reproduce

Skript is here: https://pastehub.net/ff8f9be3b1c
Skript Config is here: https://pastehub.net/ff9039a0671

### Errors or Screenshots

```
[03:04:33 ERROR]: #!#!
[03:04:33 ERROR]: #!#! [Skript] Severe Error:
[03:04:33 ERROR]: #!#! Could not load collatz.sk
[03:04:33 ERROR]: #!#!
[03:04:33 ERROR]: #!#! Something went horribly wrong with Skript.
[03:04:33 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[03:04:33 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[03:04:33 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[03:04:33 ERROR]: #!#!
[03:04:33 ERROR]: #!#! Stack trace:
[03:04:33 ERROR]: #!#! java.util.ConcurrentModificationException
[03:04:33 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
[03:04:33 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[03:04:33 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[03:04:33 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[03:04:33 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.lang.EffectSection.lambda$parse$1(EffectSection.java:79)
[03:04:33 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[03:04:33 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.lang.EffectSection.parse(EffectSection.java:78)
[03:04:33 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.lang.Statement.parse(Statement.java:42)
[03:04:33 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1113)
[03:04:33 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:489)
[03:04:33 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:707)
[03:04:33 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[03:04:33 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[03:04:33 ERROR]: #!#!     at Skript-2.6.1.jar//ch.njol.skript.ScriptLoader$AsyncLoaderThread.run(ScriptLoader.java:367)
[03:04:33 ERROR]: #!#!
[03:04:33 ERROR]: #!#! Version Information:
[03:04:33 ERROR]: #!#!   Skript: 2.6.1 (latest)
[03:04:33 ERROR]: #!#!     Flavor: skriptlang-github
[03:04:33 ERROR]: #!#!     Date: 22:18:42.554713200
[03:04:33 ERROR]: #!#!   Bukkit: 1.18.1-R0.1-SNAPSHOT
[03:04:33 ERROR]: #!#!   Minecraft: 1.18.1
[03:04:33 ERROR]: #!#!   Java: 17.0.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39)
[03:04:33 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[03:04:33 ERROR]: #!#!
[03:04:33 ERROR]: #!#! Server platform: Paper
[03:04:33 ERROR]: #!#!
[03:04:33 ERROR]: #!#! Current node: set {_now} to now (collatz.sk, line 6)
[03:04:33 ERROR]: #!#! Current item: null
[03:04:33 ERROR]: #!#!
[03:04:33 ERROR]: #!#! Thread: Thread-6
[03:04:33 ERROR]: #!#!
[03:04:33 ERROR]: #!#! Language: english
[03:04:33 ERROR]: #!#! Link parse mode: DISABLED
[03:04:33 ERROR]: #!#!
[03:04:33 ERROR]: #!#! End of Error.
[03:04:33 ERROR]: #!#!
```

### Other

I just think this is something that could affect things in the future i

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by Moderocky** [comment]
Looks like it should be as simple as using a concurrency-safe collection for patterns.

**Comment by ImNotStable** [comment]
I'm not exactly sure what that means but I'm oddly getting this error too 
[Skript] Line 7: (collatz.sk)
    The expression 'argument' can only be used within a command
    Line: loop integers from arg-1 to arg-2:

**Comment by GStudiosX2** [comment]
for me setting `script loader thread size:` to anything other than default breaks all my scripts and everything i get like a million errors in game

**Comment by TPGamesNL** [comment]
@GStudiosX2 can you share these errors here? It'd help us fix them

**Comment by GStudiosX2** [comment]
> @GStudiosX2 can you share these errors here? It'd help us fix them

idk its mostly errors with functions lol i cant rn it might be the host i was using /shrug

**Comment by APickledWalrus** [comment]
The CME shown here will be fixed in https://github.com/SkriptLang/Skript/pull/4108

After that PR is merged, any severe errors related to async/parallel loading should be gone. It is worth noting that with that PR parallel loading is not really done for 99% of script loading (see [THIS](https://github.com/SkriptLang/Skript/pull/4108/commits/8d521544ac21961869a8d97d765d10bb0de78342#diff-9fbc46f67879bc1d9c8abddc65ecd2e8955edb610a6c786422e21bf9a6801e50R489) commit)
