### ISSUE TITLE
Initializing Legacy Material Support

### ISSUE THREAD

**Issue by SebyHas** [SkriptLang/Skript#4580]
### Skript/Server Version

```
[13:12:58 ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[13:12:58 WARN]: java.lang.Exception
[13:12:58 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.legacy.CraftLegacy.<clinit>(CraftLegacy.java:260)
[13:12:58 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.util.CraftMagicNumbers.getBlock(CraftMagicNumbers.java:106)
[13:12:58 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.block.CraftBlockState.setRawData(CraftBlockState.java:260)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.classes.data.BukkitEventValues$58.get(BukkitEventValues.java:632)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.classes.data.BukkitEventValues$58.get(BukkitEventValues.java:627)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.expressions.base.EventValueExpression.getValue(EventValueExpression.java:99)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.expressions.base.EventValueExpression.get(EventValueExpression.java:85)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.expressions.base.WrapperExpression.get(WrapperExpression.java:90)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.lang.VariableString.toString(VariableString.java:449)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.lang.VariableString.getAll(VariableString.java:672)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.lang.VariableString.getAll(VariableString.java:64)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.conditions.CondContains.check(CondContains.java:100)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.sections.SecConditional.walk(SecConditional.java:165)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[13:12:58 WARN]:        at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[13:12:58 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:12:58 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:12:58 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[13:12:58 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:485)
[13:12:58 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerBucketEmptyEvent(CraftEventFactory.java:457)
[13:12:58 WARN]:        at net.minecraft.world.item.ItemBucket.emptyContents(ItemBucket.java:158)
[13:12:58 WARN]:        at net.minecraft.world.item.ItemBucket.a(ItemBucket.java:106)
[13:12:58 WARN]:        at net.minecraft.world.item.ItemStack.a(ItemStack.java:475)
[13:12:58 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:490)
[13:12:58 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1917)
[13:12:58 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28)
[13:12:58 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8)
[13:12:58 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[13:12:58 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:12:58 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[13:12:58 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[13:12:58 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[13:12:58 WARN]:        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[13:12:58 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[13:12:58 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[13:12:58 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[13:12:58 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[13:12:58 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[13:12:58 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[13:12:58 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[13:12:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Bug Description

Just give random this error.

### Expected Behavior

When give this error, lag the server too.

### Steps to Reproduce

Just appear random.

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
More context needed: output of /skript info and your script code

**Comment by SebyHas** [comment]
Sorry, i forgot.

`[14:25:04 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:25:04 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[14:25:04 INFO]: [Skript] Server Version: git-Paper-187 (MC: 1.18.1)
[14:25:04 INFO]: [Skript] Skript Version: 2.6
[14:25:04 INFO]: [Skript] Installed Skript Addons:
[14:25:04 INFO]: [Skript]  - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
[14:25:04 INFO]: [Skript]  - SkQuery v4.1.5
[14:25:04 INFO]: [Skript]  - SkBee v1.14.2 (https://github.com/ShaneBeee/SkBee)`

**Comment by AyhamAl-Ali** [comment]
Use 2.6.1 for MC 1.18

**Comment by SebyHas** [comment]
The 2.6.1 have problems with hex colors in "send formatted", my server work with a script which use that expresion.

**Comment by AyhamAl-Ali** [comment]
Then use this [unofficial Skript](https://cdn.discordapp.com/attachments/836220485175607306/913842051622244392/Skript.jar) 2.6 made for 1.18

**Comment by TPGamesNL** [comment]
We don't support Skript 2.6. 
The exception is printed because you have `debug` set to `true` in your server.properties.

**Comment by SebyHas** [comment]
the error persists.
i understand but, why the server lag that much when this error appears?

**Comment by TPGamesNL** [comment]
The lag may be because legacy material support is being initialized, but idk if that's normally intensive
