### ISSUE TITLE
Parseerror

### ISSUE THREAD

**Issue by Muury** [SkriptLang/Skript#4583]
Skript: 2.1.2
  Bukkit: 1.8.8-R0.1-SNAPSHOT
  Minecraft: 1.8.8
  Java: 1.8.0_311**

[12:15:31] [Skript update thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m [0;31;22mAn internal error occurred while checking for the latest version of Skript. Please refer to the server log for details.[m
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! [Skript] Severe Error:
[12:15:31] [Skript update thread/ERROR]: #!#! Unexpected error while checking for a new version of Skript
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[12:15:31] [Skript update thread/ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[12:15:31] [Skript update thread/ERROR]: #!#! and check whether this error has already been reported.
[12:15:31] [Skript update thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[12:15:31] [Skript update thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[12:15:31] [Skript update thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[12:15:31] [Skript update thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! Stack trace:
[12:15:31] [Skript update thread/ERROR]: #!#! javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.
[12:15:31] [Skript update thread/ERROR]: #!#!     at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(Unknown Source)
[12:15:31] [Skript update thread/ERROR]: #!#!     at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(Unknown Source)
[12:15:31] [Skript update thread/ERROR]: #!#!     at ch.njol.skript.Updater.getChangelogs(Updater.java:286)
[12:15:31] [Skript update thread/ERROR]: #!#!     at ch.njol.skript.Updater$2.run(Updater.java:210)
[12:15:31] [Skript update thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! Version Information:
[12:15:31] [Skript update thread/ERROR]: #!#!   Skript: 2.1.2
[12:15:31] [Skript update thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[12:15:31] [Skript update thread/ERROR]: #!#!   Minecraft: 1.8.8
[12:15:31] [Skript update thread/ERROR]: #!#!   Java: 1.8.0_311
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! Running CraftBukkit: false
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! Current node: execute player command "money" (Dodatki.sk, line 95)
[12:15:31] [Skript update thread/ERROR]: #!#! Current item: null
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! Thread: Skript update thread
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! End of Error.
[12:15:31] [Skript update thread/ERROR]: #!#! 

### Bug Description

[12:15:31] [Skript update thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m [0;31;22mAn internal error occurred while checking for the latest version of Skript. Please refer to the server log for details.[m
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! [Skript] Severe Error:
[12:15:31] [Skript update thread/ERROR]: #!#! Unexpected error while checking for a new version of Skript
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[12:15:31] [Skript update thread/ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[12:15:31] [Skript update thread/ERROR]: #!#! and check whether this error has already been reported.
[12:15:31] [Skript update thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[12:15:31] [Skript update thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[12:15:31] [Skript update thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[12:15:31] [Skript update thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! Stack trace:
[12:15:31] [Skript update thread/ERROR]: #!#! javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.
[12:15:31] [Skript update thread/ERROR]: #!#!     at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(Unknown Source)
[12:15:31] [Skript update thread/ERROR]: #!#!     at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(Unknown Source)
[12:15:31] [Skript update thread/ERROR]: #!#!     at ch.njol.skript.Updater.getChangelogs(Updater.java:286)
[12:15:31] [Skript update thread/ERROR]: #!#!     at ch.njol.skript.Updater$2.run(Updater.java:210)
[12:15:31] [Skript update thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! Version Information:
[12:15:31] [Skript update thread/ERROR]: #!#!   Skript: 2.1.2
[12:15:31] [Skript update thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[12:15:31] [Skript update thread/ERROR]: #!#!   Minecraft: 1.8.8
[12:15:31] [Skript update thread/ERROR]: #!#!   Java: 1.8.0_311
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! Running CraftBukkit: false
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! Current node: execute player command "money" (Dodatki.sk, line 95)
[12:15:31] [Skript update thread/ERROR]: #!#! Current item: null
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! Thread: Skript update thread
[12:15:31] [Skript update thread/ERROR]: #!#! 
[12:15:31] [Skript update thread/ERROR]: #!#! End of Error.
[12:15:31] [Skript update thread/ERROR]: #!#! 

### Expected Behavior

not showing?

### Steps to Reproduce

Well basically nothing

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment]
We only support the latest version of Skript: 2.6.1, see https://github.com/SkriptLang/Skript/releases
