### ISSUE TITLE
 Can fik my error

### ISSUE THREAD

**Issue by Nangomeni** [SkriptLang/Skript#4635]
### Skript/Server Version

skript2.2-dev36
1.8 minecraft server

### Bug Description

Everytime i reload my skript it says 0 errors but it don't work, and i don't know why

### Expected Behavior

Im not sure what the problem is

### Steps to Reproduce

When i restart my server it says 'error in skript.jar'

### Errors or Screenshots

[16:18:23 ERROR]: #!#! Stack trace:
[16:18:23 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "ch.njol.skript.classes.ClassInfo.getChanger()" because the return value of "ch.njol.skript.registrations.Classes.getExactClassInfo(java.lang.Class)" is null
[16:18:23 ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
[16:18:23 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[16:18:23 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:467)
[16:18:23 ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[16:18:23 ERROR]: #!#!     at com.github.tukenuke.tuske.TuSKe.onEnable(TuSKe.java:100)
[16:18:23 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[16:18:23 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[16:18:23 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[16:18:23 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
[16:18:23 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
[16:18:23 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
[16:18:23 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
[16:18:23 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
[16:18:23 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
[16:18:23 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
[16:18:23 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[16:18:23 ERROR]: #!#! 
[16:18:23 ERROR]: #!#! Version Information:
[16:18:23 ERROR]: #!#!   Skript: 2.2-dev36
[16:18:23 ERROR]: #!#!   Bukkit: 1.8-R0.1-SNAPSHOT
[16:18:23 ERROR]: #!#!   Minecraft: 1.8
[16:18:23 ERROR]: #!#!   Java: 17.0.2 (OpenJDK 64-Bit Server VM 17.0.2+8-86)
[16:18:23 ERROR]: #!#!   OS: Linux amd64 5.4.0-90-generic
[16:18:23 ERROR]: #!#! 
[16:18:23 ERROR]: #!#! Server platform: Spigot
[16:18:23 ERROR]: #!#! 
[16:18:23 ERROR]: #!#! Current node: null
[16:18:23 ERROR]: #!#! Current item: null
[16:18:23 ERROR]: #!#! 
[16:18:23 ERROR]: #!#! Thread: Server thread
[16:18:23 ERROR]: #!#! 
[16:18:23 ERROR]: #!#! Language: english
[16:18:23 ERROR]: #!#! Link parse mode: DISABLED
[16:18:23 ERROR]: #!#! 
[16:18:23 ERROR]: #!#! End of Error.
[16:18:23 ERROR]: #!#! 

### Other

no

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
We only support latest Skript version however, your issue is because of TuSKe, probably using the wrong version. Try this [version](https://skripttools.net/addons?q=TuSKe)

For further help use [SkUnity](https://discord.gg/0l3WlzBPKX7WNjkf) discord server.
