### ISSUE TITLE
All Skellet feutures donst work

### ISSUE THREAD

**Issue by LeckererSandwich** [SkriptLang/Skript#4639]
### Skript/Server Version

>test1
[10:54:42 ERROR]: #!#!
[10:54:42 ERROR]: #!#! [Skript] Severe Error:
[10:54:42 ERROR]: #!#!
[10:54:42 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[10:54:42 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[10:54:42 ERROR]: #!#! and check whether this error has already been reported.
[10:54:42 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[10:54:42 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[10:54:42 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[10:54:42 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[10:54:42 ERROR]: #!#!
[10:54:42 ERROR]: #!#! Stack trace:
[10:54:42 ERROR]: #!#! java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Double (java.lang.Long and java.lang.Double are in module java.base of loader 'bootstrap')
[10:54:42 ERROR]: #!#!     at me.limeglass.skellett.elements.expressions.ExprAbsoluteValue.convert(ExprAbsoluteValue.java:7)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:305)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:296)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:105)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.expressions.base.SimplePropertyExpression.get(SimplePropertyExpression.java:56)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:76)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:383)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:488)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:1)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:69)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:181)
[10:54:42 ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:54:42 ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:54:42 ERROR]: #!#!     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:54:42 ERROR]: #!#!     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[10:54:42 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[10:54:42 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[10:54:42 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[10:54:42 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[10:54:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:407)
[10:54:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[10:54:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[10:54:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[10:54:42 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[10:54:42 ERROR]: #!#!
[10:54:42 ERROR]: #!#! Version Information:
[10:54:42 ERROR]: #!#!   Skript: 2.2-Mineplex-Core-Patch
[10:54:42 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[10:54:42 ERROR]: #!#!   Minecraft: 1.8.8
[10:54:42 ERROR]: #!#!   Java: 11.0.13 (Java HotSpot(TM) 64-Bit Server VM 11.0.13+10-LTS-370)
[10:54:42 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[10:54:42 ERROR]: #!#!
[10:54:42 ERROR]: #!#! Running CraftBukkit: false
[10:54:42 ERROR]: #!#!
[10:54:42 ERROR]: #!#! Current node: null
[10:54:42 ERROR]: #!#! Current item: send "%the absolute value of [[long:-7]]%" to event-player/console
[10:54:42 ERROR]: #!#!
[10:54:42 ERROR]: #!#! Thread: Server thread
[10:54:42 ERROR]: #!#!
[10:54:42 ERROR]: #!#! End of Error.
[10:54:42 ERROR]: #!#!
[10:54:42 INFO]: An internal error occurred while attempting to perform this command.
[11:01:54 WARN]: java.net.UnknownHostException: umbaska.funnygatt.space
[11:01:54 WARN]:        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
[11:01:54 WARN]:        at java.base/java.net.Socket.connect(Socket.java:608)
[11:01:54 WARN]:        at java.base/java.net.Socket.connect(Socket.java:557)
[11:01:54 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[11:01:54 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
[11:01:54 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
[11:01:54 WARN]:        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
[11:01:54 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
[11:01:54 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
[11:01:54 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
[11:01:54 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
[11:01:54 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
[11:01:54 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
[11:01:54 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
[11:01:54 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[11:01:54 WARN]:        at java.base/java.net.URL.openStream(URL.java:1165)
[11:01:54 WARN]:        at uk.co.umbaska.UpdateChecker.runNow(UpdateChecker.java:48)
[11:01:54 WARN]:        at uk.co.umbaska.UpdateChecker$1.run(UpdateChecker.java:74)
[11:01:54 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[11:01:54 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[11:01:54 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[11:01:54 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[11:01:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
>

### Bug Description

All Skellet features doesnt work even the ones given in the dokumentation

### Expected Behavior

I dont know

### Steps to Reproduce

command /test1:
	trigger:
		send "%absolute value of -7%"

### Errors or Screenshots

[10:54:42 ERROR]: #!#! [Skript] Severe Error:
[10:54:42 ERROR]: #!#!
[10:54:42 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[10:54:42 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[10:54:42 ERROR]: #!#! and check whether this error has already been reported.
[10:54:42 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[10:54:42 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[10:54:42 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[10:54:42 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[10:54:42 ERROR]: #!#!
[10:54:42 ERROR]: #!#! Stack trace:
[10:54:42 ERROR]: #!#! java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Double (java.lang.Long and java.lang.Double are in module java.base of loader 'bootstrap')
[10:54:42 ERROR]: #!#!     at me.limeglass.skellett.elements.expressions.ExprAbsoluteValue.convert(ExprAbsoluteValue.java:7)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:305)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:296)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:105)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.expressions.base.SimplePropertyExpression.get(SimplePropertyExpression.java:56)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:76)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:383)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:488)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:1)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:69)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
[10:54:42 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:181)
[10:54:42 ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:54:42 ERROR]: #!#!     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:54:42 ERROR]: #!#!     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:54:42 ERROR]: #!#!     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[10:54:42 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[10:54:42 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[10:54:42 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[10:54:42 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[10:54:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:407)
[10:54:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[10:54:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[10:54:42 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[10:54:42 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[10:54:42 ERROR]: #!#!
[10:54:42 ERROR]: #!#! Version Information:
[10:54:42 ERROR]: #!#!   Skript: 2.2-Mineplex-Core-Patch
[10:54:42 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[10:54:42 ERROR]: #!#!   Minecraft: 1.8.8
[10:54:42 ERROR]: #!#!   Java: 11.0.13 (Java HotSpot(TM) 64-Bit Server VM 11.0.13+10-LTS-370)
[10:54:42 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[10:54:42 ERROR]: #!#!
[10:54:42 ERROR]: #!#! Running CraftBukkit: false
[10:54:42 ERROR]: #!#!
[10:54:42 ERROR]: #!#! Current node: null
[10:54:42 ERROR]: #!#! Current item: send "%the absolute value of [[long:-7]]%" to event-player/console
[10:54:42 ERROR]: #!#!
[10:54:42 ERROR]: #!#! Thread: Server thread
[10:54:42 ERROR]: #!#!
[10:54:42 ERROR]: #!#! End of Error.

### Other

I use minecraft 1.8.8
and Java 11

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Thank you for coming here however,
1. We do not support forked Skript versions
2. We do not support addon issues. (report that to the addon issue tracker)
3. We do not support old MC/Skript versions
4. *You are probably using the wrong addon version*
