### ISSUE TITLE
loop all players error

### ISSUE THREAD

**Issue by Poweringg** [SkriptLang/Skript#4644]
### Skript/Server Version

```markdown
[16:13:40 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[16:13:40 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[16:13:40 INFO]: [Skript] Server Version: git-Paper-220 (MC: 1.18.2)
[16:13:40 INFO]: [Skript] Skript Version: 2.6.1
[16:13:40 INFO]: [Skript] Installed Skript Addons:
[16:13:40 INFO]: [Skript]  - Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/)
[16:13:40 INFO]: [Skript]  - Ersatz v1.0
[16:13:40 INFO]: [Skript] Installed dependencies:
[16:13:40 INFO]: [Skript]  - Vault v1.7.3-b131
[16:13:40 INFO]: [Skript]  - Residence v5.0.1.3
```

### Bug Description

i used this code...
```
every second: 
	loop all players: 
		send "test" to loop-player
```
and got error in console...

### Expected Behavior

no error, and every player got "test" message every second in theirs chat.

### Steps to Reproduce

create new script

type in "every second: ; loop all players: ; etc.."

/script reload nameOfScript

.. error

### Errors or Screenshots

[16:12:37 ERROR]: #!#!
[16:12:37 ERROR]: #!#! [Skript] Severe Error:
[16:12:37 ERROR]: #!#! Could not load loop-check.sk
[16:12:37 ERROR]: #!#!
[16:12:37 ERROR]: #!#! Something went horribly wrong with Skript.
[16:12:37 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:12:37 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[16:12:37 ERROR]: #!#! Here is full list of them:
[16:12:37 ERROR]: #!#! Ersatz v1.0 Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/)
[16:12:37 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[16:12:37 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[16:12:37 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[16:12:37 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[16:12:37 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[16:12:37 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[16:12:37 ERROR]: #!#!
[16:12:37 ERROR]: #!#! Stack trace:
[16:12:37 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for citizen
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[16:12:37 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Condition.parse(Condition.java:77)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.init(Section.java:69)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:257)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.parse(Section.java:156)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1127)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:752)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1060)
[16:12:37 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[16:12:37 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:12:37 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[16:12:37 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
[16:12:37 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2297)
[16:12:37 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2108)
[16:12:37 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2089)
[16:12:37 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[16:12:37 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[16:12:37 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[16:12:37 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:12:37 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[16:12:37 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[16:12:37 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1387)
[16:12:37 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189)
[16:12:37 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[16:12:37 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1364)
[16:12:37 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1357)
[16:12:37 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[16:12:37 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1335)
[16:12:37 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1222)
[16:12:37 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[16:12:37 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[16:12:37 ERROR]: #!#!
[16:12:37 ERROR]: #!#! Version Information:
[16:12:37 ERROR]: #!#!   Skript: 2.6.1 (latest)
[16:12:37 ERROR]: #!#!     Flavor: skriptlang-github
[16:12:37 ERROR]: #!#!     Date: 22:18:42.554713200
[16:12:37 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[16:12:37 ERROR]: #!#!   Minecraft: 1.18.2
[16:12:37 ERROR]: #!#!   Java: 17.0.2 (OpenJDK 64-Bit Server VM 17.0.2+8)
[16:12:37 ERROR]: #!#!   OS: Windows Server 2019 amd64 10.0
[16:12:37 ERROR]: #!#!
[16:12:37 ERROR]: #!#! Server platform: Paper
[16:12:37 ERROR]: #!#!
[16:12:37 ERROR]: #!#! Current node: loop all players: (loop-check.sk, line 2)
[16:12:37 ERROR]: #!#! Current item: null
[16:12:37 ERROR]: #!#!
[16:12:37 ERROR]: #!#! Thread: Server thread
[16:12:37 ERROR]: #!#!
[16:12:37 ERROR]: #!#! Language: english
[16:12:37 ERROR]: #!#! Link parse mode: DISABLED
[16:12:37 ERROR]: #!#!
[16:12:37 ERROR]: #!#! End of Error.
[16:12:37 ERROR]: #!#!

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
This is addon issue however, open Skellett's config and enable npc hook then restart

**Comment by Poweringg** [comment]
works, thanks for reply.
