### ISSUE TITLE
idk what this is please help i have updatad plugins ples help

### ISSUE THREAD

**Issue by aciner** [SkriptLang/Skript#4691]
### Skript/Server Version

```markdown
[23:27:27 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[23:27:27 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[23:27:27 INFO]: [Skript] Server Version: git-Paper-408 (MC: 1.17.1)
[23:27:27 INFO]: [Skript] Skript Version: 2.6.1
[23:27:27 INFO]: [Skript] Installed Skript Addons: 
[23:27:27 INFO]: [Skript]  - Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/)
[23:27:27 INFO]: [Skript]  - SkQuery v4.1.6
[23:27:27 INFO]: [Skript]  - SkBee v1.15.2 (https://github.com/ShaneBeee/SkBee)
[23:27:27 INFO]: [Skript] Installed dependencies: 
[23:27:27 INFO]: [Skript]  - Vault v1.7.3-b131
[23:27:27 INFO]: [Skript]  - WorldGuard v7.0.6-SNAPSHOT+2121-32d16a7
[23:27:27 INFO]: blocksun787 issued server command: /warps
```

### Bug Description

im really not sure on whats happening as I'm not that smart but heres the error thing

error:
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! [Skript] Severe Error:
[23:25:46 ERROR]: #!#! Could not load staff/test.sk
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! Something went horribly wrong with Skript.
[23:25:46 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[23:25:46 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[23:25:46 ERROR]: #!#! Here is full list of them:
[23:25:46 ERROR]: #!#! SkBee v1.15.2 (https://github.com/ShaneBeee/SkBee) Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/) SkQuery v4.1.6 DiscordSRV v1.25.1 (https://github.com/DiscordSRV/DiscordSRV) 
[23:25:46 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[23:25:46 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[23:25:46 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[23:25:46 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[23:25:46 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[23:25:46 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! Stack trace:
[23:25:46 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for citizen
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[23:25:46 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Statement.parse(Statement.java:61)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1113)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:489)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:707)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1060)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[23:25:46 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[23:25:46 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[23:25:46 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2262)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2073)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2054)
[23:25:46 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[23:25:46 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[23:25:46 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:25:46 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[23:25:46 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[23:25:46 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[23:25:46 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[23:25:46 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! Version Information:
[23:25:46 ERROR]: #!#!   Skript: 2.6.1 (latest)
[23:25:46 ERROR]: #!#!     Flavor: skriptlang-github
[23:25:46 ERROR]: #!#!     Date: 22:18:42.554713200
[23:25:46 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[23:25:46 ERROR]: #!#!   Minecraft: 1.17.1
[23:25:46 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[23:25:46 ERROR]: #!#!   OS: Linux amd64 5.13.0-27-generic
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! Server platform: Paper
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! Current node: format slot 0 of player with paper named "&aHelper" with lore "&7Click Me!" to close then run "Helper" (staff/test.sk, line 5)
[23:25:46 ERROR]: #!#! Current item: null
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! Thread: Server thread
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! Language: english
[23:25:46 ERROR]: #!#! Link parse mode: DISABLED
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! End of Error.
[23:25:46 ERROR]: #!#! 

### Expected Behavior

i reloaded a skript and it should have worked and i should be able to open a gui but nothing happened and that error showed in console

### Steps to Reproduce

I was making a skript test gui and it wouldnt work

### Errors or Screenshots

[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! [Skript] Severe Error:
[23:25:46 ERROR]: #!#! Could not load staff/test.sk
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! Something went horribly wrong with Skript.
[23:25:46 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[23:25:46 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[23:25:46 ERROR]: #!#! Here is full list of them:
[23:25:46 ERROR]: #!#! SkBee v1.15.2 (https://github.com/ShaneBeee/SkBee) Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/) SkQuery v4.1.6 DiscordSRV v1.25.1 (https://github.com/DiscordSRV/DiscordSRV) 
[23:25:46 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[23:25:46 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[23:25:46 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[23:25:46 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[23:25:46 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[23:25:46 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! Stack trace:
[23:25:46 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for citizen
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[23:25:46 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Statement.parse(Statement.java:61)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1113)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:489)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:707)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1060)
[23:25:46 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[23:25:46 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[23:25:46 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[23:25:46 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2262)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2073)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2054)
[23:25:46 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[23:25:46 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[23:25:46 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:25:46 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[23:25:46 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[23:25:46 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[23:25:46 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
[23:25:46 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[23:25:46 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! Version Information:
[23:25:46 ERROR]: #!#!   Skript: 2.6.1 (latest)
[23:25:46 ERROR]: #!#!     Flavor: skriptlang-github
[23:25:46 ERROR]: #!#!     Date: 22:18:42.554713200
[23:25:46 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[23:25:46 ERROR]: #!#!   Minecraft: 1.17.1
[23:25:46 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[23:25:46 ERROR]: #!#!   OS: Linux amd64 5.13.0-27-generic
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! Server platform: Paper
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! Current node: format slot 0 of player with paper named "&aHelper" with lore "&7Click Me!" to close then run "Helper" (staff/test.sk, line 5)
[23:25:46 ERROR]: #!#! Current item: null
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! Thread: Server thread
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! Language: english
[23:25:46 ERROR]: #!#! Link parse mode: DISABLED
[23:25:46 ERROR]: #!#! 
[23:25:46 ERROR]: #!#! End of Error.
[23:25:46 ERROR]: #!#! 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by kossnikita** [comment]
Did you enable the npc Skellett hook in config?

**Comment by AyhamAl-Ali** [comment]
Addon issue not Skript, in specific Skellett. Though here is the solution `Skellett -> config.yml -> npc -> true` restart the server
