### ISSUE TITLE
Error With Skript

### ISSUE THREAD

**Issue by runningute72** [SkriptLang/Skript#4713]
### Skript/Server Version

```markdown
> skript info
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[Skript] Server Version: git-Paper-267 (MC: 1.18.2)
[Skript] Skript Version: 2.6.1
[Skript] Installed Skript Addons:
[Skript]  - Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/)
[Skript]  - SkBee v1.15.2 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies:
[Skript]  - Vault v1.7.3-b131
[Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

I get this huge error constantly.

```[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! [Skript] Severe Error:
[00:01:18 ERROR]: #!#! Could not load stuff.sk
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! Something went horribly wrong with Skript.
[00:01:18 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:01:18 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:01:18 ERROR]: #!#! Here is full list of them:
[00:01:18 ERROR]: #!#! SkBee v1.15.2 (https://github.com/ShaneBeee/SkBee) Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/)
[00:01:18 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[00:01:18 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:01:18 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:01:18 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[00:01:18 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:01:18 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! Stack trace:
[00:01:18 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for citizen
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[00:01:18 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Statement.parse(Statement.java:61)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1113)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:489)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:707)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:468)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:778)
[00:01:18 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[00:01:18 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[00:01:18 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1172)
[00:01:18 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[00:01:18 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! Version Information:
[00:01:18 ERROR]: #!#!   Skript: 2.6.1 (latest)
[00:01:18 ERROR]: #!#!     Flavor: skriptlang-github
[00:01:18 ERROR]: #!#!     Date: 22:18:42.554713200
[00:01:18 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[00:01:18 ERROR]: #!#!   Minecraft: 1.18.2
[00:01:18 ERROR]: #!#!   Java: 17.0.2 (Java HotSpot(TM) 64-Bit Server VM 17.0.2+8-LTS-86)
[00:01:18 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! Server platform: Paper
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! Current node: create a new bound with id "portal.wild" between {loc1} and {loc2} (stuff.sk, line 6)
[00:01:18 ERROR]: #!#! Current item: null
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! Thread: Server thread
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! Language: english
[00:01:18 ERROR]: #!#! Link parse mode: DISABLED
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! End of Error.
[00:01:18 ERROR]: #!#!```

### Expected Behavior

It's not supposed to give me this error :P

### Steps to Reproduce

I installed Skellet with SkBee and it appeared to give me this issue. I'm not sure what is causing it.

### Errors or Screenshots

```[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! [Skript] Severe Error:
[00:01:18 ERROR]: #!#! Could not load stuff.sk
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! Something went horribly wrong with Skript.
[00:01:18 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:01:18 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:01:18 ERROR]: #!#! Here is full list of them:
[00:01:18 ERROR]: #!#! SkBee v1.15.2 (https://github.com/ShaneBeee/SkBee) Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/)
[00:01:18 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[00:01:18 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:01:18 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:01:18 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[00:01:18 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:01:18 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! Stack trace:
[00:01:18 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for citizen
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[00:01:18 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Statement.parse(Statement.java:61)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1113)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:489)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:707)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:468)
[00:01:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:778)
[00:01:18 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[00:01:18 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[00:01:18 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1172)
[00:01:18 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[00:01:18 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! Version Information:
[00:01:18 ERROR]: #!#!   Skript: 2.6.1 (latest)
[00:01:18 ERROR]: #!#!     Flavor: skriptlang-github
[00:01:18 ERROR]: #!#!     Date: 22:18:42.554713200
[00:01:18 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[00:01:18 ERROR]: #!#!   Minecraft: 1.18.2
[00:01:18 ERROR]: #!#!   Java: 17.0.2 (Java HotSpot(TM) 64-Bit Server VM 17.0.2+8-LTS-86)
[00:01:18 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! Server platform: Paper
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! Current node: create a new bound with id "portal.wild" between {loc1} and {loc2} (stuff.sk, line 6)
[00:01:18 ERROR]: #!#! Current item: null
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! Thread: Server thread
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! Language: english
[00:01:18 ERROR]: #!#! Link parse mode: DISABLED
[00:01:18 ERROR]: #!#!
[00:01:18 ERROR]: #!#! End of Error.
[00:01:18 ERROR]: #!#!```

### Other

Nope.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by kossnikita** [comment]
https://github.com/SkriptLang/Skript/issues/4691

**Comment by runningute72** [comment]
I am now getting this error: ```[00:17:45 ERROR]: Error occurred while enabling Skellett v2.0.3 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/NPCDamageByEntityEvent
        at com.gmail.thelimeglass.Register.events(Register.java:330) ~[Skellett-Legacy-2.0.3.jar:?]
        at com.gmail.thelimeglass.Skellett.onEnable(Skellett.java:199) ~[Skellett-Legacy-2.0.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.event.NPCDamageByEntityEvent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more
[00:17:45 INFO]: [Skellett] Disabling Skellett v2.0.3```
