### ISSUE TITLE
looping a list

### ISSUE THREAD

**Issue by MineGuy0** [SkriptLang/Skript#4722]
### Skript/Server Version

```markdown
2.6.1
```

### Bug Description

skript version 2.5.3 allowed me to use something like loop {guards::*}
but after updating to 2.6.1 i get critical errors trying to do so.
the skript worked fine before i updated and idk why it broke
example file below
[bosses.txt](https://github.com/SkriptLang/Skript/files/8457247/bosses.txt)

### Expected Behavior

should be allowed to loop lists

### Steps to Reproduce

just reload the skript and check console to see errors

### Errors or Screenshots

[14:17:01] [Server thread/INFO]: Zrollus issued server command: /sk reload bosses.sk
[14:17:01] [Server thread/ERROR]: #!#! 
[14:17:01] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[14:17:01] [Server thread/ERROR]: #!#! Could not load bosses.sk
[14:17:01] [Server thread/ERROR]: #!#! 
[14:17:01] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[14:17:01] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:17:01] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[14:17:01] [Server thread/ERROR]: #!#! Here is full list of them:
[14:17:01] [Server thread/ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) skRayFall v1.9.25 (https://sk.rayfall.net/) Vixio v2.0.7 (http://vixio.space) SkBoard v1.0.2 skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo) GameAPI v2.0.3 WolvSK v1.7.2 Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/) SKNoise v0.1.9 skript-db v1.3.3 skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect) skript-gui v1.2.2 (https://github.com/APickledWalrus/skript-gui) skDragon v0.17 SkBee v1.12.2 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.4 SkQuery v4.1.4 SkUniversal v2.11.5 
[14:17:01] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[14:17:01] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[14:17:01] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[14:17:01] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[14:17:01] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[14:17:01] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[14:17:01] [Server thread/ERROR]: #!#! 
[14:17:01] [Server thread/ERROR]: #!#! Stack trace:
[14:17:01] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for permission
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[14:17:01] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:77)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:69)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:257)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:156)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1127)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:752)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1060)
[14:17:01] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[14:17:01] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:17:01] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[14:17:01] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:761)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1936)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1779)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1732)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970)
[14:17:01] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)
[14:17:01] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:829)
[14:17:01] [Server thread/ERROR]: #!#! 
[14:17:01] [Server thread/ERROR]: #!#! Version Information:
[14:17:01] [Server thread/ERROR]: #!#!   Skript: 2.6.1 (latest)
[14:17:01] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[14:17:01] [Server thread/ERROR]: #!#!     Date: 22:18:42.554713200
[14:17:01] [Server thread/ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[14:17:01] [Server thread/ERROR]: #!#!   Minecraft: 1.16.5
[14:17:01] [Server thread/ERROR]: #!#!   Java: 11.0.13 (OpenJDK 64-Bit Server VM 11.0.13+8)
[14:17:01] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.13.0-27-generic
[14:17:01] [Server thread/ERROR]: #!#! 
[14:17:01] [Server thread/ERROR]: #!#! Server platform: Spigot
[14:17:01] [Server thread/ERROR]: #!#! 
[14:17:01] [Server thread/ERROR]: #!#! Current node: loop {guard::*}: (bosses.sk, line 115)
[14:17:01] [Server thread/ERROR]: #!#! Current item: null
[14:17:01] [Server thread/ERROR]: #!#! 
[14:17:01] [Server thread/ERROR]: #!#! Thread: Server thread
[14:17:01] [Server thread/ERROR]: #!#! 
[14:17:01] [Server thread/ERROR]: #!#! Language: english
[14:17:01] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[14:17:01] [Server thread/ERROR]: #!#! 
[14:17:01] [Server thread/ERROR]: #!#! End of Error.
[14:17:01] [Server thread/ERROR]: #!#! 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
> [14:17:01] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for permission

Probably an addon issue, try removing addons and find which caused it
