### ISSUE TITLE
ava.lang.NoClassDefFoundError: com/iCo6/Constants$Nodes

### ISSUE THREAD

**Issue by TheMaselko** [SkriptLang/Skript#4724]
### Skript/Server Version

```markdown
Version Information:
   Skript: 2.6.1 (latest)
     Flavor: skriptlang-github
     Date: 22:18:42.554713200
   Bukkit: 1.16.5-R0.1-SNAPSHOT
   Minecraft: 1.16.5
   Java: 16 (OpenJDK 64-Bit Server VM 16+36-2231)
   OS: Linux amd64 4.19.0-20-amd64

Server platform: Paper
```

### Bug Description

 Stack trace:
 java.lang.NoClassDefFoundError: com/iCo6/Constants$Nodes
     at net.milkbowl.vault.economy.plugins.Economy_iConomy6.currencyNameSingular(Economy_iConomy6.java:119)
     at ch.njol.skript.hooks.economy.classes.Money.parse(Money.java:152)
     at ch.njol.skript.hooks.economy.classes.Money$2.parse(Money.java:57)
     at ch.njol.skript.hooks.economy.classes.Money$2.parse(Money.java:53)
     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:443)
     at ch.njol.skript.registrations.Classes.parse(Classes.java:482)
     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:386)
     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:651)
     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:788)
     at ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)     at ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
     at ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
     at ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
     at ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
     at ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
     at ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
     at ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1302)
     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
     at ch.njol.skript.lang.Condition.parse(Condition.java:77)
     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
     at ch.njol.skript.lang.Section.init(Section.java:69)
     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:257)
     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
     at ch.njol.skript.lang.Section.parse(Section.java:156)
     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1127)
     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:752)     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:468)
     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:149)
     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)     at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
     at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
     at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
     at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
     at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
     at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
     at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271)
     at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264)
     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338)
     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135)
     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
     at java.base/java.lang.Thread.run(Thread.java:831)

### Expected Behavior

-

### Steps to Reproduce

The plugin simply does not work.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
What version of Vault do you have?

**Comment by TheMaselko** [comment]
v1.7.3-b131

**Comment by TheMaselko** [comment]
> What version of Vault do you have?

v1.7.3-b131

**Comment by AyhamAl-Ali** [comment]
Can you send the output of `/plugins`
and try to redownload [Vault ](https://www.spigotmc.org/resources/vault.34315/)from spigot again

**Comment by TPGamesNL** [comment]
Can you send your server startup log (latest.log)?

**Comment by TheMaselko** [comment]
> Can you send the output of `/plugins` and try to redownload [Vault ](https://www.spigotmc.org/resources/vault.34315/)from spigot again and test using it

![image](https://user-images.githubusercontent.com/73562374/163215136-bdba919c-0c8e-455f-bf36-5822dc9df80d.png)

**Comment by TPGamesNL** [comment]
As you can see in the screenshot, this is a problem with iConomy. The stacktrace confirms this

**Comment by TheMaselko** [comment]
> As you can see in the screenshot, this is a problem with iConomy. The stacktrace confirms this

How could I fix this error? iConomy is not in the plugin folder and yet it still shows up under the /pl command.
