### ISSUE TITLE
Severe Error in Console Skript

### ISSUE THREAD

**Issue by 83y** [SkriptLang/Skript#4736]
### Skript/Server Version

```markdown
[01:58:05 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[01:58:05 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[01:58:05 INFO]: [Skript] Server Version: git-Paper-68 (MC: 1.18.1)
[01:58:05 INFO]: [Skript] Skript Version: 2.6.1
[01:58:05 INFO]: [Skript] Installed Skript Addons: None
[01:58:05 INFO]: [Skript] Installed dependencies:
[01:58:05 INFO]: [Skript]  - GriefPrevention v16.18
```

### Bug Description

[01:51:18 ERROR]: #!#!
[01:51:18 ERROR]: #!#! [Skript] Severe Error:
[01:51:18 ERROR]: #!#!
[01:51:18 ERROR]: #!#! Something went horribly wrong with Skript.
[01:51:18 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[01:51:18 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[01:51:18 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[01:51:18 ERROR]: #!#!
[01:51:18 ERROR]: #!#! Stack trace:
[01:51:18 ERROR]: #!#! java.lang.IllegalArgumentException: Size for custom inventory must be a multiple of 9 between 9 and 54 slots (got 63)
[01:51:18 ERROR]: #!#!     at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[01:51:18 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R1.CraftServer.createInventory(CraftServer.java:2074)
[01:51:18 ERROR]: #!#!     at org.bukkit.Bukkit.createInventory(Bukkit.java:1434)
[01:51:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.ExprChestInventory.get(ExprChestInventory.java:82)
[01:51:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.ExprChestInventory.get(ExprChestInventory.java:37)
[01:51:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[01:51:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:273)
[01:51:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:51)
[01:51:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[01:51:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[01:51:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[01:51:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285)
[01:51:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:250)
[01:51:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255)
[01:51:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands.handleCommand(Commands.java:258)
[01:51:18 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:175)
[01:51:18 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[01:51:18 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[01:51:18 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:51:18 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[01:51:18 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2260)
[01:51:18 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2079)
[01:51:18 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2060)
[01:51:18 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[01:51:18 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[01:51:18 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[01:51:18 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:51:18 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[01:51:18 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)[01:51:18 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[01:51:18 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[01:51:18 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[01:51:18 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[01:51:18 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[01:51:18 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[01:51:18 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[01:51:18 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[01:51:18 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[01:51:18 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[01:51:18 ERROR]: #!#!
[01:51:18 ERROR]: #!#! Version Information:
[01:51:18 ERROR]: #!#!   Skript: 2.6.1 (latest)
[01:51:18 ERROR]: #!#!     Flavor: skriptlang-github
[01:51:18 ERROR]: #!#!     Date: 22:18:42.554713200
[01:51:18 ERROR]: #!#!   Bukkit: 1.18.1-R0.1-SNAPSHOT
[01:51:18 ERROR]: #!#!   Minecraft: 1.18.1
[01:51:18 ERROR]: #!#!   Java: 17.0.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39)
[01:51:18 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[01:51:18 ERROR]: #!#!
[01:51:18 ERROR]: #!#! Server platform: Paper
[01:51:18 ERROR]: #!#!
[01:51:18 ERROR]: #!#! Current node: null
[01:51:18 ERROR]: #!#! Current item: set metadata values "hub" of the player to chest inventory named "Gamemode Selector" with [[long:7]]
[01:51:18 ERROR]: #!#! Current trigger: command /test (simple event) (core.sk, line 5)
[01:51:18 ERROR]: #!#!
[01:51:18 ERROR]: #!#! Thread: Server thread
[01:51:18 ERROR]: #!#!
[01:51:18 ERROR]: #!#! Language: english
[01:51:18 ERROR]: #!#! Link parse mode: DISABLED
[01:51:18 ERROR]: #!#!
[01:51:18 ERROR]: #!#! End of Error.
[01:51:18 ERROR]: #!#!

### Expected Behavior

It was meant to open the GUI but it only did sometimes.

### Steps to Reproduce

run the command /test and reload the skript.

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/55250446/164350550-1e8ca6d7-f634-449f-9540-ceba44fa8a8e.png)

### Other

It told me to report it here. I have no idea why it's not working.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment]
Size validation in ExprChestInventory is not being properly done. It should do as the error message says.

**Comment by ham1255** [comment]
instead of not making it not throw, maybe make skript auto size it to the max inventory size?

**Comment by TPGamesNL** [comment]
That's what the PR does :)
![image](https://user-images.githubusercontent.com/29547183/164518393-0c4aaabb-56af-4558-90ea-32fc11f12d96.png)
