### ISSUE TITLE
error when enabling

### ISSUE THREAD

**Issue by WongIong** [SkriptLang/Skript#4756]
### Skript/Server Version

```markdown
2.6.1
paper 1.16.5
```

### Bug Description

[20:44:57 ERROR]: Error occurred while enabling Skript v2.6.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:142) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:467) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1076 out of bounds for length 1076
        at ch.njol.skript.aliases.MaterialRegistry.<init>(MaterialRegistry.java:101) ~[?:?]
        at ch.njol.skript.aliases.MaterialRegistry.load(MaterialRegistry.java:78) ~[?:?]
        at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:101) ~[?:?]
        ... 12 more
[20:44:57 INFO]: [Skript] Disabling Skript v2.6.1

### Expected Behavior

no error

### Steps to Reproduce

enable the plugin when starting the server 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by DelayedGaming** [comment]
1. Stop server
2. Delete `aliases` file in `Skript` folder
3. Start server

**Comment by WongIong** [comment]
it works
