### ISSUE TITLE
Servere Error 

### ISSUE THREAD

**Issue by Teraofficiql** [SkriptLang/Skript#4762]
### Skript/Server Version

```markdown
[14:45:33 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:45:33 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[14:45:33 INFO]: [Skript] Skript Version: 2.6.1
[14:45:33 INFO]: [Skript] Installed Skript Addons:
[14:45:33 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[14:45:33 INFO]: [Skript]  - Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/)
[14:45:33 INFO]: [Skript]  - skript-yaml v1.4
[14:45:33 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[14:45:33 INFO]: [Skript]  - skRayFall v1.9.27 (https://sk.rayfall.net/)
[14:45:33 INFO]: [Skript]  - SkQuery v4.1.6
[14:45:33 INFO]: [Skript] Installed dependencies:
[14:45:33 INFO]: [Skript]  - Vault v1.7.3-b131
[14:45:33 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
[14:45:33 INFO]: [Skript]  - GriefPrevention v16.18
```

### Bug Description

This issue occurs when the server is opening. or refreshing my scripts. I can't refresh scripts from within the server.  I get the same error when I try from console.

### Expected Behavior

I am not sure. it happened after restarting normally. I have installed no other new plugins

### Steps to Reproduce

I had installed script placeholders. and I recently installed the skellett plugin on my server. I don't remember installing another plugin that could make this happen.

### Errors or Screenshots

[14:41:43 ERROR]: #!#!
[14:41:43 ERROR]: #!#! [Skript] Severe Error:
[14:41:43 ERROR]: #!#! Could not load kripto.sk
[14:41:43 ERROR]: #!#!
[14:41:43 ERROR]: #!#! Something went horribly wrong with Skript.
[14:41:43 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:41:43 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[14:41:43 ERROR]: #!#! Here is full list of them:
[14:41:43 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) skRayFall v1.9.27 (https://sk.rayfall.net/) skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) skript-yaml v1.4 SkQuery v4.1.6 Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/) AuctionMaster v4.1 (https://discord.gg/nchk86TKMT)
[14:41:43 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[14:41:43 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[14:41:43 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[14:41:43 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[14:41:43 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[14:41:43 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[14:41:43 ERROR]: #!#!
[14:41:43 ERROR]: #!#! Stack trace:
[14:41:43 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for citizen
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[14:41:43 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Statement.parse(Statement.java:61)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1113)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:489)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:707)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1060)
[14:41:43 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[14:41:43 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:41:43 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:41:43 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[14:41:43 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869)
[14:41:43 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.be(DedicatedServer.java:513)
[14:41:43 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[14:41:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1457)
[14:41:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1227)
[14:41:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317)
[14:41:43 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[14:41:43 ERROR]: #!#!
[14:41:43 ERROR]: #!#! Version Information:
[14:41:43 ERROR]: #!#!   Skript: 2.6.1 (latest)
[14:41:43 ERROR]: #!#!     Flavor: skriptlang-github
[14:41:43 ERROR]: #!#!     Date: 22:18:42.554713200
[14:41:43 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[14:41:43 ERROR]: #!#!   Minecraft: 1.18.2
[14:41:43 ERROR]: #!#!   Java: 17.0.2 (Java HotSpot(TM) 64-Bit Server VM 17.0.2+8-LTS-86)
[14:41:43 ERROR]: #!#!   OS: Windows Server 2019 amd64 10.0
[14:41:43 ERROR]: #!#!
[14:41:43 ERROR]: #!#! Server platform: Paper
[14:41:43 ERROR]: #!#!
[14:41:43 ERROR]: #!#! Current node: send "&cBozdur" run "/bozdur dolar" tooltip "&8• &aDolar : &7&o%{dolar}% TL" to player (kripto.sk, line 68)
[14:41:43 ERROR]: #!#! Current item: null
[14:41:43 ERROR]: #!#!
[14:41:43 ERROR]: #!#! Thread: Server thread
[14:41:43 ERROR]: #!#!
[14:41:43 ERROR]: #!#! Language: english
[14:41:43 ERROR]: #!#! Link parse mode: DISABLED
[14:41:43 ERROR]: #!#!
[14:41:43 ERROR]: #!#! End of Error.
[14:41:43 ERROR]: #!#!

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Teraofficiql** [comment]
[14:41:43_ ERROR](https://github.com/SkriptLang/Skript/issues/4762#!#!): #!#! Current node: send "&cBozdur" run "/bozdur dolar" tooltip "&8• &aDolar : &7&o%{dolar}% TL" to player (kripto.sk, line 68)

It is an error in my script. not related to the problem

**Comment by Teraofficiql** [comment]
Fixed it. the problem was with the latest version of Skellett. one old version worked perfectly
