### ISSUE TITLE
Skript does not support print of primitive array

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#4770]
### Skript/Server Version

```markdown
Server Version: git-Paper-186 (MC: 1.17.1)
Skript Version: 2.6.2
Installed Skript Addons:
  - Skellett v2.0.1 (https://forums.skunity.com/resources/skellett.24/)
  - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
  - SkQuery v4.1.4
  - SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee)
  - Skript-Packet v2.1.0 (www.github.com/Anarchick/skript-packet)
Installed dependencies: None
```

### Bug Description
```
I'm updating Skript-Packet and I have seen that Skript can't print primitive array.
Skript-packet has the expression : ```
"%numbers% as primitive (0¦int|1¦float|2¦long|3¦double|4¦short|5¦byte) array"
```

Wich works if I use `send class of 1 as primitive int array` (return "[I")
but thrown an error if I use `send 1 as primitive int array`

### Expected Behavior

Print all values like it's possible with Integer[]

### Steps to Reproduce

    @Override
    @Nullable
    protected Object[] get(Event e) {
        return new Object[] {new int[0]};

### Errors or Screenshots

[13:06:51 ERROR]: #!#! Stack trace:
[13:06:51 ERROR]: #!#!   warning: no/empty exception given, dumping current stack trace instead
[13:06:51 ERROR]: #!#! java.lang.Exception: java.lang.NullPointerException
[13:06:51 ERROR]: #!#!     at Skript-2.6.2.jar//ch.njol.skript.Skript.exception(Skript.java:1704)
[13:06:51 ERROR]: #!#!     at Skript-2.6.2.jar//ch.njol.skript.Skript.exception(Skript.java:1551)
[13:06:51 ERROR]: #!#!     at Skript-2.6.2.jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:306)
[13:06:51 ERROR]: #!#!     at Skript-2.6.2.jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:219)
[13:06:51 ERROR]: #!#!     at Skript-2.6.2.jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:216)
[13:06:51 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
[13:06:51 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[13:06:51 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490)
[13:06:51 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[13:06:51 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
[13:06:51 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[13:06:51 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:06:51 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[13:06:51 ERROR]: #!#! Caused by: java.lang.NullPointerException
[13:06:51 ERROR]: #!#!
[13:06:51 ERROR]: #!#! Version Information:
[13:06:51 ERROR]: #!#!   Skript: 2.6.2 (latest)
[13:06:51 ERROR]: #!#!     Flavor: skriptlang-github
[13:06:51 ERROR]: #!#!     Date: 19:12:53.596652600
[13:06:51 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[13:06:51 ERROR]: #!#!   Minecraft: 1.17.1
[13:06:51 ERROR]: #!#!   Java: 17.0.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39)
[13:06:51 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:06:51 ERROR]: #!#!
[13:06:51 ERROR]: #!#! Server platform: Paper
[13:06:51 ERROR]: #!#!
[13:06:51 ERROR]: #!#! Current node: null
[13:06:51 ERROR]: #!#! Current item: null
[13:06:51 ERROR]: #!#!
[13:06:51 ERROR]: #!#! Thread: Server thread
[13:06:51 ERROR]: #!#!
[13:06:51 ERROR]: #!#! Language: english
[13:06:51 ERROR]: #!#! Link parse mode: DISABLED
[13:06:51 ERROR]: #!#!
[13:06:51 ERROR]: #!#! End of Error.
[13:06:51 ERROR]: #!#!

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TPGamesNL** [comment]
When the expression returns a type, that type must be registered, so you need to register the type `int[]`

**Comment by Anarchick** [comment]
I will try this after holidays. But I suppose it's the same issue for Skript-Reflect ? Who need to hundle this : Skript or Addons ?

**Comment by TPGamesNL** [comment]
Addons need to handle this, they need to register the types which they return. skript-reflect has overcome this issue by wrapping every java object in a wrapper class which is registered.
