### ISSUE TITLE
skipt doesnt work

### ISSUE THREAD

**Issue by janosek1111** [SkriptLang/Skript#4783]
### Skript/Server Version

```markdown
down ↓ i dont know how to paste this s
```

### Bug Description

ok first info 
![image](https://user-images.githubusercontent.com/106877221/172008333-28c4ef6e-7d91-46a9-9a27-29414b7e4dc2.png)
skripts dont load i tryed to update still doesnt work all skipts are good and 0 erros 

### Expected Behavior

skiprts shuld load and commands shuld work

### Steps to Reproduce

idk why its happends

### Errors or Screenshots

[14:39:34] [Server thread/ERROR]: #!#! Thread: Server thread
[14:39:34] [Server thread/ERROR]: #!#! 
[14:39:34] [Server thread/ERROR]: #!#! Language: english
[14:39:34] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[14:39:34] [Server thread/ERROR]: #!#! 
[14:39:34] [Server thread/ERROR]: #!#! End of Error.
[14:39:34] [Server thread/ERROR]: #!#! 
[14:39:34] [Server thread/ERROR]: #!#! 
[14:39:34] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[14:39:34] [Server thread/ERROR]: #!#! Could not load witherskeleton.sk
[14:39:34] [Server thread/ERROR]: #!#! 
[14:39:34] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[14:39:34] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:39:34] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[14:39:34] [Server thread/ERROR]: #!#! Here is full list of them:
[14:39:34] [Server thread/ERROR]: #!#! skRayFall v1.9.26 (https://sk.rayfall.net/) skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) SkBee v1.15.2 (https://github.com/ShaneBeee/SkBee) 
[14:39:34] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[14:39:34] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[14:39:34] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[14:39:34] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[14:39:34] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[14:39:34] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[14:39:34] [Server thread/ERROR]: #!#! 
[14:39:34] [Server thread/ERROR]: #!#! Stack trace:
[14:39:34] [Server thread/ERROR]: #!#! java.lang.RuntimeException: pattern compiling exception, element class: com.shanebeestudios.skbee.elements.text.expressions.ExprComponentFormat
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:516)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:741)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1243)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:77)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:69)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:254)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:156)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:140)
[14:39:34] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:39:34] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[14:39:34] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:790)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1770)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1751)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(SourceFile:18)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1125)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[14:39:34] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[14:39:34] [Server thread/ERROR]: #!#! Caused by: ch.njol.skript.patterns.MalformedPatternException: caught exception while compiling pattern [pattern: [the] (color|1?bold|2?italic|3?(obfuscate[d]|magic)|4?strikethrough|5?underline[d]|6?insert[ion]) format of %basecomponents%]
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:54)
[14:39:34] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1242)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:516)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:741)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1243)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:77)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:69)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:254)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:156)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:140)
[14:39:34] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:39:34] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[14:39:34] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:790)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1770)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1751)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(SourceFile:18)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1125)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[14:39:34] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[14:39:34] [Server thread/ERROR]: #!#! Caused by: ch.njol.skript.SkriptAPIException: No class info found for basecomponent
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:138)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:49)
[14:39:34] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1242)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:516)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:741)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1243)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:77)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:69)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:254)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:156)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[14:39:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:140)
[14:39:34] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:39:34] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[14:39:34] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:790)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1770)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1751)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(SourceFile:18)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1125)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054)
[14:39:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[14:39:34] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[14:39:34] [Server thread/ERROR]: #!#! 
[14:39:34] [Server thread/ERROR]: #!#! Version Information:
[14:39:34] [Server thread/ERROR]: #!#!   Skript: 2.6.2 (latest)
[14:39:34] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[14:39:34] [Server thread/ERROR]: #!#!     Date: 19:12:53.596652600
[14:39:34] [Server thread/ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[14:39:34] [Server thread/ERROR]: #!#!   Minecraft: 1.17.1
[14:39:34] [Server thread/ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[14:39:34] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.13.0-27-generic
[14:39:34] [Server thread/ERROR]: #!#! 
[14:39:34] [Server thread/ERROR]: #!#! Server platform: Spigot
[14:39:34] [Server thread/ERROR]: #!#! 
[14:39:34] [Server thread/ERROR]: #!#! Current node: if chance of 50%: (witherskeleton.sk, line 3)
[14:39:34] [Server thread/ERROR]: #!#! Current item: null
[14:39:34] [Server thread/ERROR]: #!#! 
[14:39:34] [Server thread/ERROR]: #!#! Thread: Server thread
[14:39:34] [Server thread/ERROR]: #!#! 
[14:39:34] [Server thread/ERROR]: #!#! Language: english
[14:39:34] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[14:39:34] [Server thread/ERROR]: #!#! 
[14:39:34] [Server thread/ERROR]: #!#! End of Error.
[scripts (1).zip](https://github.com/SkriptLang/Skript/files/8838061/scripts.1.zip)

[14:39:34] [Server thread/ERROR]: #!#! 

### Other

plese help 😢 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TPGamesNL** [comment]
> java.lang.RuntimeException: pattern compiling exception, element class: com.shanebeestudios.skbee.elements.text.expressions.ExprComponentFormat

This is an error from SkBee, please report it to them

**Comment by janosek1111** [comment]
ok i wil i will report ty for fast respond <3

**Comment by TPGamesNL** [comment]
No problem :)
