### ISSUE TITLE
Skripts not enabling on start

### ISSUE THREAD

**Issue by Gavins38** [SkriptLang/Skript#4828]
### Skript/Server Version

```markdown
[19:58:43 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[19:58:43 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[19:58:43 INFO]: [Skript] Server Version: git-Paper-8 (MC: 1.19)
[19:58:43 INFO]: [Skript] Skript Version: 2.6.2-nightly-b89d420
[19:58:43 INFO]: [Skript] Installed Skript Addons: 
[19:58:43 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[19:58:43 INFO]: [Skript]  - SkQuery v4.1.6
[19:58:43 INFO]: [Skript]  - SkBee v1.16.1 (https://github.com/ShaneBeee/SkBee)
[19:58:43 INFO]: [Skript] Installed dependencies: 
[19:58:43 INFO]: [Skript]  - Vault v1.7.3-b131
[19:58:43 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

Skripts do not enable on start you have to reload the skripts manually with /sk reload all

### Expected Behavior

For the skripts to start on server start

### Steps to Reproduce

Restarting the server

### Errors or Screenshots

[19:52:21 ERROR]: #!#! 
[19:52:21 ERROR]: #!#! [Skript] Severe Error:
[19:52:21 ERROR]: #!#! 
[19:52:21 ERROR]: #!#! You're running a (buggy) nightly version of Skript.
[19:52:21 ERROR]: #!#! If this is not a test server, switch to a more stable release NOW!
[19:52:21 ERROR]: #!#! Your players are unlikely to appreciate crashes and/or data loss due to Skript bugs.
[19:52:21 ERROR]: #!#! 
[19:52:21 ERROR]: #!#! Just testing things? Good. Please report this bug, so that we can fix it before a stable release.
[19:52:21 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues
[19:52:21 ERROR]: #!#! 
[19:52:21 ERROR]: #!#! Stack trace:
[19:52:21 ERROR]: #!#! java.lang.NoSuchMethodError: 'ch.njol.skript.config.Config ch.njol.skript.lang.parser.ParserInstance.getCurrentScript()'
[19:52:21 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.util.SkriptUtil.getCurrentScript(SkriptUtil.java:108)
[19:52:21 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomImport$SectionImport.init(CustomImport.java:82)
[19:52:21 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.lang.SkriptEvent.init(SkriptEvent.java:98)
[19:52:21 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.lang.structure.Structure.init(Structure.java:102)
[19:52:21 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:261)
[19:52:21 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:205)
[19:52:21 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.lang.structure.Structure.parse(Structure.java:177)
[19:52:21 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:571)
[19:52:21 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$3(ScriptLoader.java:469)
[19:52:21 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:391)
[19:52:21 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:407)
[19:52:21 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:467)
[19:52:21 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:426)
[19:52:21 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.Skript$1.run(Skript.java:819)
[19:52:21 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:52:21 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[19:52:21 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1134)
[19:52:21 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[19:52:21 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[19:52:21 ERROR]: #!#! 
[19:52:21 ERROR]: #!#! Version Information:
[19:52:21 ERROR]: #!#!   Skript: 2.6.2-nightly-b89d420
[19:52:21 ERROR]: #!#!     Flavor: skriptlang-nightly
[19:52:21 ERROR]: #!#!     Date: 23:42:22.196857554
[19:52:21 ERROR]: #!#!   Bukkit: 1.19-R0.1-SNAPSHOT
[19:52:21 ERROR]: #!#!   Minecraft: 1.19
[19:52:21 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[19:52:21 ERROR]: #!#!   OS: Linux amd64 5.13.0-27-generic
[19:52:21 ERROR]: #!#! 
[19:52:21 ERROR]: #!#! Server platform: Paper
[19:52:21 ERROR]: #!#! 
[19:52:21 ERROR]: #!#! Current node: null
[19:52:21 ERROR]: #!#! Current item: null
[19:52:21 ERROR]: #!#! 
[19:52:21 ERROR]: #!#! Thread: Server thread
[19:52:21 ERROR]: #!#! 
[19:52:21 ERROR]: #!#! Language: english
[19:52:21 ERROR]: #!#! Link parse mode: DISABLED
[19:52:21 ERROR]: #!#! 
[19:52:21 ERROR]: #!#! End of Error.
[19:52:21 ERROR]: #!#! 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Skript doesn't yet support Minecraft 1.19.
There is an unofficial version published by one of the Skript team just so you can use the plugin on 1.19 servers but it doesn't support any 1.19 features, you can find it [here (discord)](https://discord.com/channels/135877399391764480/836220485175607306/983780013268680794)

**Comment by TPGamesNL** [comment]
If you want to download Skript normally (for 1.18), go to [releases](https://github.com/SkriptLang/Skript/releases), not Actions
