### ISSUE TITLE
Stopping server in 1.12 causes error.

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#4862]
### Skript/Server Version

```markdown
Skript 2.6.2
Spigot 1.12.2
```

### Bug Description

When I stop the server, I get an error.

### Expected Behavior

Not error.

### Steps to Reproduce

Stop the server with Skript installed.

### Errors or Screenshots

```
[03:15:32] [Server thread/INFO]: [Skript] Disabling Skript v2.6.2-nightly-d35ada0
[03:15:32] [Server thread/ERROR]: Error occurred while disabling Skript v2.6.2-nightly-d35ada0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at ch.njol.skript.Skript.beforeDisable(Skript.java:1047) ~[?:?]
	at ch.njol.skript.Skript.onDisable(Skript.java:1059) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:349) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:465) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:613) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: ch.njol.skript.SkriptAPIException: Registration can only be done during plugin initialization
	at ch.njol.skript.Skript.checkAcceptRegistrations(Skript.java:1154) ~[?:?]
	at ch.njol.skript.Skript.registerEvent(Skript.java:1360) ~[?:?]
	at ch.njol.skript.events.EvtSkript.<clinit>(EvtSkript.java:41) ~[?:?]
	... 10 more
```

**Comment by TPGamesNL** [comment]
Can you send the full server log?

**Comment by TPGamesNL** [comment]
Can only replicate when there's an error during Skript enabling, therefore full log is needed. Reopen when provided
