### ISSUE TITLE
1.12 Dolphin doesn't exist

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#4863]
### Skript/Server Version

```markdown
Skript 2.6.2-master from commit (July 2nd 2022) https://github.com/SkriptLang/Skript/commit/5e8a5d892d214dddfc878604fd24d56634f45633
Spigot 1.12.2
```

### Bug Description

When you start the server, Skript doesn't load because Dolphin doesn't exist.

### Expected Behavior

Not error.

### Steps to Reproduce

Start a new server on 1.12 with Skript 2.6.2

### Errors or Screenshots

```
[Server thread/ERROR]: Error occurred while enabling Skript v2.6.2-nightly-d35ada0 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/entity/Dolphin
	at ch.njol.skript.entity.SimpleEntityData.<clinit>(SimpleEntityData.java:249) ~[?:?]
	at ch.njol.skript.entity.EntityData.<clinit>(EntityData.java:158) ~[?:?]
	at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:274) ~[?:?]
	at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:694) ~[?:?]
	at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:603) ~[?:?]
	at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:121) ~[?:?]
	at ch.njol.skript.aliases.Aliases.load(Aliases.java:510) ~[?:?]
	at ch.njol.skript.aliases.Aliases.load(Aliases.java:496) ~[?:?]
	at ch.njol.skript.aliases.Aliases.lambda$loadDirectory$1(Aliases.java:479) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_291]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_291]
	at java.util.stream.SortedOps$RefSortingSink.end(Unknown Source) ~[?:1.8.0_291]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_291]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_291]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_291]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_291]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_291]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_291]
	at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:472) ~[?:?]
	at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:437) ~[?:?]
	at ch.njol.skript.aliases.Aliases.load(Aliases.java:393) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:474) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Dolphin
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]
	... 33 more
```
Issue from pull https://github.com/SkriptLang/Skript/pull/4801

**Comment by bluelhf** [comment]
Does this exist in the _real_ 2.6.2 release? I was under the impression this change was made because the next release won't support 1.12.

**Comment by AyhamAl-Ali** [comment]
It should be okay to merge because the next release was supposed to be 2.7 but now we're releasing 2.6.3 for 1.19 support since 2.7 will take sometime for sure, that PR should be just excluded from 2.6.3 branch because it aims for 2.7 (master)
