### ISSUE TITLE
Registration can only be done during plugin initialization

### ISSUE THREAD

**Issue by Weefle** [SkriptLang/Skript#4917]
### Skript/Server Version

```markdown
[14:39:25] [Server thread/INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:39:25] [Server thread/INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[14:39:25] [Server thread/INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[14:39:25] [Server thread/INFO]: [Skript] Server Version: 3545-Spigot-475f600-4230f8f (MC: 1.19)
[14:39:25] [Server thread/INFO]: [Skript] Skript Version: 2.6.3
[14:39:25] [Server thread/INFO]: [Skript] Installed Skript Addons: None
[14:39:25] [Server thread/INFO]: [Skript] Installed dependencies: None
```

### Bug Description

I'm trying to load my addon with the latest version of Skript but I'm getting this error:
```java 
[14:34:45] [ServerMain/INFO]: Building unoptimized datafixer
[14:34:46] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:34:47] [ServerMain/INFO]: Loaded 7 recipes
[14:34:48] [Server thread/INFO]: Starting minecraft server version 1.19
[14:34:48] [Server thread/INFO]: Loading properties
[14:34:48] [Server thread/INFO]: This server is running CraftBukkit version 3545-Spigot-475f600-4230f8f (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT)
[14:34:48] [Server thread/INFO]: Debug logging is disabled
[14:34:48] [Server thread/INFO]: Server Ping Player Sample Count: 12
[14:34:48] [Server thread/INFO]: Using 4 threads for Netty based IO
[14:34:48] [Server thread/INFO]: Default game type: SURVIVAL
[14:34:48] [Server thread/INFO]: Generating keypair
[14:34:49] [Server thread/INFO]: Starting Minecraft server on *:25565
[14:34:49] [Server thread/INFO]: Using default channel type
[14:34:49] [Server thread/INFO]: [SkWaze] Loading SkWaze v3.0.5
[14:34:49] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.30-SNAPSHOT (build 2602)
[14:34:49] [Server thread/INFO]: [Constructor] Loading Constructor v2.1.0
[14:34:49] [Server thread/INFO]: [Skript] Loading Skript v2.6.3
[14:34:49] [Server thread/INFO]: Preparing level "world"
[14:34:49] [Server thread/INFO]: -------- World Settings For [world] --------
[14:34:49] [Server thread/INFO]: Item Merge Radius: 2.5
[14:34:49] [Server thread/INFO]: Item Despawn Rate: 6000
[14:34:49] [Server thread/INFO]: View Distance: 8
[14:34:49] [Server thread/INFO]: Simulation Distance: 10
[14:34:49] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[14:34:49] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[14:34:49] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[14:34:49] [Server thread/INFO]: Mob Spawn Range: 6
[14:34:49] [Server thread/INFO]: Experience Merge Radius: 3.0
[14:34:49] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[14:34:49] [Server thread/INFO]: Cactus Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: Cane Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: Melon Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: Sapling Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: Carrot Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: Potato Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: Wheat Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: Vine Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: Kelp Growth Modifier: 100%
[14:34:49] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[14:34:49] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[14:34:49] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[14:34:49] [Server thread/INFO]: Max TNT Explosions: 100
[14:34:49] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[14:34:49] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[14:34:50] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[14:34:50] [Server thread/INFO]: Item Merge Radius: 2.5
[14:34:50] [Server thread/INFO]: Item Despawn Rate: 6000
[14:34:50] [Server thread/INFO]: View Distance: 8
[14:34:50] [Server thread/INFO]: Simulation Distance: 10
[14:34:50] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[14:34:50] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[14:34:50] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[14:34:50] [Server thread/INFO]: Mob Spawn Range: 6
[14:34:50] [Server thread/INFO]: Experience Merge Radius: 3.0
[14:34:50] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[14:34:50] [Server thread/INFO]: Cactus Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Cane Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Melon Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Sapling Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Carrot Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Potato Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Wheat Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Vine Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Kelp Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[14:34:50] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[14:34:50] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[14:34:50] [Server thread/INFO]: Max TNT Explosions: 100
[14:34:50] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[14:34:50] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[14:34:50] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[14:34:50] [Server thread/INFO]: Item Merge Radius: 2.5
[14:34:50] [Server thread/INFO]: Item Despawn Rate: 6000
[14:34:50] [Server thread/INFO]: View Distance: 8
[14:34:50] [Server thread/INFO]: Simulation Distance: 10
[14:34:50] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[14:34:50] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[14:34:50] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[14:34:50] [Server thread/INFO]: Mob Spawn Range: 6
[14:34:50] [Server thread/INFO]: Experience Merge Radius: 3.0
[14:34:50] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[14:34:50] [Server thread/INFO]: Cactus Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Cane Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Melon Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Sapling Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Carrot Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Potato Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Wheat Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Vine Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Kelp Growth Modifier: 100%
[14:34:50] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[14:34:50] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[14:34:50] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[14:34:50] [Server thread/INFO]: Max TNT Explosions: 100
[14:34:50] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[14:34:50] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[14:34:50] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:34:52] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:34:52] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:34:52] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:34:52] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[14:34:52] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[14:34:52] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[14:34:53] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:34:53] [Worker-Main-5/INFO]: Preparing spawn area: 24%
[14:34:54] [Server thread/INFO]: Time elapsed: 4016 ms
[14:34:54] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[14:34:55] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[14:34:55] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:34:55] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[14:34:55] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[14:34:56] [Worker-Main-7/INFO]: Preparing spawn area: 54%
[14:34:56] [Server thread/INFO]: Time elapsed: 2193 ms
[14:34:56] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[14:34:57] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:34:57] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[14:34:57] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:34:57] [Worker-Main-6/INFO]: Preparing spawn area: 26%
[14:34:58] [Server thread/INFO]: Time elapsed: 1835 ms
[14:34:58] [Server thread/INFO]: [SkWaze] Enabling SkWaze v3.0.5
[14:34:58] [Server thread/WARN]: [SkWaze] Loaded class ch.njol.skript.Skript from Skript v2.6.3 which is not a depend or softdepend of this plugin.
[14:34:58] [Server thread/ERROR]: Error occurred while enabling SkWaze v3.0.5 (Is it up to date?)
ch.njol.skript.SkriptAPIException: Registration can only be done during plugin initialization
	at ch.njol.skript.Skript.checkAcceptRegistrations(Skript.java:1223) ~[?:?]
	at ch.njol.skript.Skript.registerAddon(Skript.java:1245) ~[?:?]
	at fr.weefle.waze.Waze.onEnable(Waze.java:66) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:523) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3545-Spigot-475f600-4230f8f]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:437) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3545-Spigot-475f600-4230f8f]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:582) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3545-Spigot-475f600-4230f8f]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:401) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3545-Spigot-475f600-4230f8f]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3545-Spigot-475f600-4230f8f]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3545-Spigot-475f600-4230f8f]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3545-Spigot-475f600-4230f8f]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[14:34:58] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.30-SNAPSHOT (build 2602)
[14:34:58] [Server thread/INFO]: [Constructor] Enabling Constructor v2.1.0
[14:34:58] [Server thread/INFO]: Your server is running version v1_19_R1
[14:34:58] [Server thread/INFO]: [Constructor] NMS setup was successful!
[14:34:58] [Server thread/INFO]: [Constructor] The plugin setup process is complete!
[14:34:58] [Server thread/INFO]: [Constructor] Metrics setup was successful
[14:34:58] [Server thread/INFO]: [Constructor] Updater setup was successful
[14:34:58] [Thread-8/INFO]: [Constructor] [Updater] Searching for updates.
[14:34:58] [Server thread/INFO]: [Constructor] Citizens is now enabled
[14:34:58] [Server thread/INFO]: [Constructor] Constructor could not register with Denizen
[14:34:58] [Server thread/INFO]: [Skript] Enabling Skript v2.6.3
[14:34:58] [Thread-8/INFO]: [Constructor] [Updater] Plugin is up-to-date.
[14:34:58] [ForkJoinPool.commonPool-worker-1/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m You're currently running the latest stable version of Skript.[m
[14:35:03] [Server thread/INFO]: [Skript] Loaded 153521 aliases in 4484ms[m
[14:35:03] [Server thread/INFO]: [Skript]  ~ created by & � Peter G�ttinger aka Njol ~[m
[14:35:03] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:35:03] [Server thread/WARN]: [Constructor] Loaded class net.citizensnpcs.api.CitizensAPI from Citizens v2.0.30-SNAPSHOT (build 2602) which is not a depend or softdepend of this plugin.
[14:35:03] [Server thread/INFO]: Done (14.089s)! For help, type "help"
[14:35:03] [Server thread/INFO]: [Skript] Loading variables...[m
[14:35:03] [Server thread/INFO]: [Skript] Loaded 43 variables in 0.1 seconds[m
[14:35:03] [Server thread/INFO]: [Skript] [0;31;1m[21mLine 3:[0;37;22m (homes.sk)[m[m
[14:35:03] [Server thread/INFO]: [0;31;1m    Can't understand this condition/effect: autorespawn player[m[m
[14:35:03] [Server thread/INFO]: [0;33;22m    Line: [0;37;22mautorespawn player[m[m
[14:35:03] [Server thread/INFO]:  [m[m
[14:35:03] [Server thread/INFO]: [Skript] Loaded 1 script with a total of 0 triggers and 1 command in 0.02 seconds[m
[14:35:03] [Server thread/INFO]: [Skript] Finished loading.[m
[14:35:04] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[14:35:06] [Server thread/INFO]: [Citizens] 1 PNJs charg�(s).
[14:35:33] [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Skript's aliases can be found here: [0;36;22mhttps://github.com/SkriptLang/skript-aliases[m
[14:35:33] [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Skript's documentation can be found here: [0;36;22mhttps://docs.skriptlang.org/[m
[14:35:33] [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Skript's tutorials can be found here: [0;36;22mhttps://docs.skriptlang.org/tutorials[m
[14:35:33] [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Server Version: [0;36;22m3545-Spigot-475f600-4230f8f (MC: 1.19)[m
[14:35:33] [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Skript Version: [0;36;22m2.6.3[m
[14:35:33] [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Installed Skript Addons: [0;36;22mNone[m
[14:35:33] [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Installed dependencies: [0;36;22mNone[m
[14:35:38] [Server thread/INFO]: Stopping the server
[14:35:38] [Server thread/INFO]: Stopping server
[14:35:38] [Server thread/INFO]: [Skript] Disabling Skript v2.6.3
[14:35:38] [Server thread/INFO]: [Constructor] Disabling Constructor v2.1.0
[14:35:38] [Server thread/INFO]: [Constructor]  v2.1.0 disabled.
[14:35:38] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.30-SNAPSHOT (build 2602)
[14:35:38] [Server thread/INFO]: [SkWaze] Disabling SkWaze v3.0.5
[14:35:38] [Server thread/INFO]: Saving players
[14:35:38] [Server thread/INFO]: Saving worlds
[14:35:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[14:35:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[14:35:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[14:35:40] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[14:35:40] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[14:35:40] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[14:35:40] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
```
What am I doing wrong ? What do you call plugin initialization ? My code is in the onEnable() method at the begining of my plugin.
![image](https://user-images.githubusercontent.com/18496043/179355206-436d2fcb-5706-4010-96eb-47bf17115963.png)

### Expected Behavior

My addon was supposed to load.

### Steps to Reproduce

When you start the server with my addon, you get the following error:
`ch.njol.skript.SkriptAPIException: Registration can only be done during plugin initialization
	at ch.njol.skript.Skript.checkAcceptRegistrations(Skript.java:1223) ~[?:?]
	at ch.njol.skript.Skript.registerAddon(Skript.java:1245) ~[?:?]
	at fr.weefle.waze.Waze.onEnable(Waze.java:66) ~[?:?]`

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
What's your plugin.yml

**Comment by AyhamAl-Ali** [comment]
Take a look at this PR's description #4575 You probably have the same issue

**Comment by Weefle** [comment]
> What's your plugin.yml
Here it is:
`name: SkWaze
author: Weefle
version: 3.0.5
description: The coolest Skript's addon
depends: [Skript]
softdepends: [BossBarAPI, Citizens, Builder, Constructor, LibsDisguises, ProtocolLib, HolographicDisplays]
main: fr.weefle.waze.Waze
api-version: 1.13
commands:
  packetmanager:
    description: Used to manage and monitor packets.
    aliases: [packetman,packetmonitor,packetmon]`
I'll look at it thanks.

**Comment by AyhamAl-Ali** [comment]
Yep I saw that on your github repo SkWaze, just make sure you didn't accidently include Skript.jar in SkWaze.jar, the error says it loaded Skript while it isn't in soft depend on depends but it is, therefore it is probably the issue I just mentioned, if not let us know

**Comment by Weefle** [comment]
Ok I solved the problem, you need to put your registrations in the onLoad() method and check if the Skript plugin is enabled :D
