### ISSUE TITLE
Skript error while enabling on Paper 1.19

### ISSUE THREAD

**Issue by sintclau** [SkriptLang/Skript#4923]
### Skript/Server Version

```markdown
Skript v2.6.3

This server is running Paper version git-Paper-66 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b7faa65)
```

### Bug Description

```
[15:26:42] [Server thread/INFO]: [Skript] Enabling Skript v2.6.3
[15:26:42] [Server thread/INFO]: [Skript] Skript's language file english.lang is outdated, some messages will be english.
[15:26:42] [Server thread/ERROR]: Error occurred while enabling Skript v2.6.3 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:143) ~[Skript (1).jar:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:472) ~[Skript (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-66]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-66]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-66]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-66]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-66]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-66]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-66]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1228 out of bounds for length 1228
	at ch.njol.skript.aliases.MaterialRegistry.<init>(MaterialRegistry.java:101) ~[Skript (1).jar:?]
	at ch.njol.skript.aliases.MaterialRegistry.load(MaterialRegistry.java:78) ~[Skript (1).jar:?]
	at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:101) ~[Skript (1).jar:?]
	... 13 more
[15:26:42] [Server thread/INFO]: [Skript] Disabling Skript v2.6.3
[15:26:43] [Server thread/ERROR]: Error occurred while disabling Skript v2.6.3 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at ch.njol.skript.Skript.beforeDisable(Skript.java:1116) ~[Skript (1).jar:?]
	at ch.njol.skript.Skript.onDisable(Skript.java:1128) ~[Skript (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-66]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-66]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-66]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-66]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-66]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-66]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-66]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: ch.njol.skript.SkriptAPIException: Registration can only be done during plugin initialization
	at ch.njol.skript.Skript.checkAcceptRegistrations(Skript.java:1223) ~[Skript (1).jar:?]
	at ch.njol.skript.Skript.registerEvent(Skript.java:1429) ~[Skript (1).jar:?]
	at ch.njol.skript.events.EvtSkript.<clinit>(EvtSkript.java:41) ~[Skript (1).jar:?]
	... 15 more
```

### Expected Behavior

Skript should have enabled.

### Steps to Reproduce

install skript
install skquery
start server

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Are you reloading the server?

Can you try deleting plugins/Skript/materials.json and restart your server to see if the error still persists.

Did you recently upgrade from an old Skript version to 2.6.3?

**Comment by AyhamAl-Ali** [comment]
That error is as Lime mentioned just delete `plugins/Skript/materials.json` and restart
As for the lang  files if you're using a custom one that's probably the reason for `Skript's language file english.lang is outdated, some messages will be english.`

**Comment by sintclau** [comment]
I deleted plugins/Skript/materials.json and it worked. Thank you! I upgraded Skript from an older version and the Minecraft version too. 1.18.2 to 1.19

**Comment by TheLimeGlass** [comment]
> I deleted plugins/Skript/materials.json and it worked. Thank you! I upgraded Skript from an older version and the Minecraft version too. 1.18.2 to 1.19

What was your existing Skript version if you remember?

Relating to https://github.com/SkriptLang/Skript/issues/4861 except from older to newer.
Potentially deleting the file automatically would be ideal, but also the user could have custom values, so it's an up for debate issue. I'm planning on tackling downgrading, but upgrading is debatable.

**Comment by sintclau** [comment]
The older version of Skript was 2.6.1
I hope this helps!
