### ISSUE TITLE
Falling block expression throws error 

### ISSUE THREAD

**Issue by Soufreur78** [SkriptLang/Skript#4953]
### Skript/Server Version

```markdown
[10:22:11] [Render thread/INFO]: [CHAT] [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[10:22:11] [Render thread/INFO]: [CHAT] [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[10:22:11] [Render thread/INFO]: [CHAT] [Skript] Server Version: git-Spigot-56f8471-56118c6 (MC: 1.14.4)
[10:22:11] [Render thread/INFO]: [CHAT] [Skript] Skript Version: 2.6.2
[10:22:11] [Render thread/INFO]: [CHAT] [Skript] Installed Skript Addons: 
[10:22:11] [Render thread/INFO]: [CHAT] [Skript]  - HydraDB v0.2C
[10:22:11] [Render thread/INFO]: [CHAT] [Skript]  - BungeeSK v1.1.0 (https://github.com/ZorgBtw/BungeeSK)
[10:22:11] [Render thread/INFO]: [CHAT] [Skript]  - skript-gui v1.3-beta2 (https://github.com/APickledWalrus/skript-gui)
[10:22:11] [Render thread/INFO]: [CHAT] [Skript]  - skRayFall v1.9.18 (https://sk.rayfall.net/)
[10:22:11] [Render thread/INFO]: [CHAT] [Skript]  - SkQuery v4.1.5
[10:22:11] [Render thread/INFO]: [CHAT] [Skript] Installed dependencies: None
```

### Bug Description

The falling block expression works but "An internal error occurred while attempting to perform this command".

### Expected Behavior

No internal error 

### Steps to Reproduce

command /falling:
	trigger:
		spawn falling block of dirt at player

### Errors or Screenshots

[10:20:08] [Server thread/INFO]: Perkiss issued server command: /falling
[10:20:08] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to Skript v2.6.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1633) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot.jar:git-Spigot-56f8471-56118c6]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NoClassDefFoundError: ch/njol/skript/effects/EffSpawn
	at com.w00tmast3r.skquery.elements.effects.EffBlockFall.execute(EffBlockFall.java:65) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:250) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255) ~[?:?]
	at ch.njol.skript.command.Commands.handleCommand(Commands.java:260) ~[?:?]
	at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:177) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	... 18 more
[10:20:08] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'falling' in plugin Skript v2.6.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot.jar:git-Spigot-56f8471-56118c6]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot.jar:git-Spigot-56f8471-56118c6]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NoClassDefFoundError: ch/njol/skript/effects/EffSpawn
	at com.w00tmast3r.skquery.elements.effects.EffBlockFall.execute(EffBlockFall.java:65) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:250) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:194) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-56f8471-56118c6]
	... 17 more

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
> Caused by: java.lang.NoClassDefFoundError: ch/njol/skript/effects/EffSpawn
at com.w00tmast3r.skquery.elements.effects.EffBlockFall.execute(EffBlockFall.java:65) ~[?:?]

Addon issue, update skQuery

**Comment by Soufreur78** [comment]
I can't because of spigot's and java's version. 

But ok, i understand that it's not a Skript issue ! 

Have a good day and thank you for your job.

**Comment by AyhamAl-Ali** [comment]
Then downgrade Skript, the EffSpawn has been removed and added as a section (EffSecSpawn)

If you need further help you can join [SkUnity help channels](https://discord.gg/pcbSwAzp) and mention me (`AyhamAlali#0001`)
