### ISSUE TITLE
Skript doesn't start on 1.18.2 MagmaMC

### ISSUE THREAD

**Issue by KostaZx** [SkriptLang/Skript#4998]
### Skript/Server Version

```markdown
/skript info
[23:14:51] [Server thread/INFO] [/]: /skript help←[m
```

### Bug Description

THIS HAPPENS ON SERVER START

[23:13:45] [Server thread/INFO] [ch.nj.sk.Skript/]: [Skript] Enabling Skript v2.6.3
[23:13:45] [Server thread/INFO] [/]: [Skript] Skript's language file english.lang is outdated, some messages will be english.←[m
[23:13:45] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling Skript v2.6.3 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/util/CraftLegacy
        at ch.njol.skript.aliases.AliasesMap.clear(AliasesMap.java:227) ~[?:?] {}
        at ch.njol.skript.aliases.AliasesMap.<init>(AliasesMap.java:140) ~[?:?] {}
        at ch.njol.skript.aliases.AliasesProvider.<init>(AliasesProvider.java:173) ~[?:?] {}
        at ch.njol.skript.aliases.Aliases.createProvider(Aliases.java:88) ~[?:?] {}
        at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:61) ~[?:?] {}
        at ch.njol.skript.Skript.onEnable(Skript.java:472) ~[?:?] {}
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[forge-1.18.2-40.1.54-universal.jar%2363!/:?] {re:classloading}
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[forge-1.18.2-40.1.54-universal.jar%2363!/:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge-1.18.2-40.1.54-universal.jar%2363!/:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[forge-1.18.2-40.1.54-universal.jar%2363!/:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[forge-1.18.2-40.1.54-universal.jar%2363!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:448) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:357) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:244) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:757) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:253) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.util.CraftLegacy
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[forge-1.18.2-40.1.54-universal.jar%2363!/:?] {re:classloading}
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[forge-1.18.2-40.1.54-universal.jar%2363!/:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}

### Expected Behavior

No idea.

### Steps to Reproduce

Nothing, just started the server

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Unfortunately, Skript only supports Spigot and its forks like PaperMC.

**Comment by TheLimeGlass** [comment]
Magma doesn't work with plugins yet. Eventually we'll look into it when it gets working.
