### ISSUE TITLE
Addon registration error in onLoad()

### ISSUE THREAD

**Issue by UeberallGebannt** [SkriptLang/Skript#5014]
### Skript/Server Version

```markdown
> skript info
[22:22:38 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[22:22:38 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[22:22:38 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[22:22:38 INFO]: [Skript] Server Version: git-Purpur-1752 (MC: 1.19.2)
[22:22:38 INFO]: [Skript] Skript Version: 2.6.3
[22:22:38 INFO]: [Skript] Installed Skript Addons: None
[22:22:38 INFO]: [Skript] Installed dependencies:
[22:22:38 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

I use the following code for enabling my Skript addon:

```java
    public void onLoad() {
        if (Objects.requireNonNull(Bukkit.getPluginManager().getPlugin("Skript")).isEnabled()) {
            this.getLogger().info("Loading Skript Addon...");
            this.skriptLangAddon = new SkriptLangAddon(this);
            this.skriptLangAddon.registerAddon();
        } else {
            this.getLogger().info("Skript not found. Skript Addon disabled.");
        }
    }
```
```java
public void registerAddon() {
        this.addon = Skript.registerAddon(this.plugin);
        try {
            this.addon.loadClasses("net.kettlemc.language.spigot.skript", new String[] { "elements" });
        } catch (IOException e) {
            e.printStackTrace();
        }
        plugin.getLogger().info("Skript Addon enabled.");
    }
```

The code can be found here: https://github.com/KettleMC-Network/LanguageAPI/blob/master/src/net/kettlemc/language/spigot/SpigotAdapter.java#L84

If I run the code like this, the addon will not be enabled (but without an error).
If I remove the if statement for the Skript check, I get this error:

```cmd
[22:21:39 ERROR]: [org.bukkit.craftbukkit.v1_19_R1.CraftServer] Registration can only be done during plugin initialization initializing LanguageAPI v1.0 (Is it up to date?)
ch.njol.skript.SkriptAPIException: Registration can only be done during plugin initialization
        at ch.njol.skript.Skript.checkAcceptRegistrations(Skript.java:1223) ~[Skript-2.6.3.jar:?]
        at ch.njol.skript.Skript.registerAddon(Skript.java:1245) ~[Skript-2.6.3.jar:?]
        at net.kettlemc.language.spigot.skript.SkriptLangAddon.registerAddon(SkriptLangAddon.java:23) ~[LanguageAPI.jar:?]
        at net.kettlemc.language.spigot.SpigotAdapter.onLoad(SpigotAdapter.java:89) ~[LanguageAPI.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:458) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1752]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Expected Behavior

The server should start fine without throwing an error.

### Steps to Reproduce

1. Install Skript.
2. Run a plugin with the provided code.
3. See error.

### Errors or Screenshots

(see above)

### Other

I already checked multiple issues and tried their solutions, but none of them worked. I might have missed something, so I hope it is just my mistake.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Ensure you have Skript as a `depend` in your plugin.yml. And you can't reload Skript.

**Comment by UeberallGebannt** [comment]
I will try, thanks. I read an issue by the skWaze author und they used onLoad

**Comment by UeberallGebannt** [comment]
Ok, this fixed it, sorry for bothering and thanks for the help!
