### ISSUE TITLE
Skript issue

### ISSUE THREAD

**Issue by Pcornel13DK** [SkriptLang/Skript#5023]
### Skript/Server Version

```markdown
1.12.2
```

### Bug Description

[11:08:45 ERROR]: #!#! 
[11:08:45 ERROR]: #!#! [Skript] Severe Error:
[11:08:45 ERROR]: #!#! Could not load Spawnerskript.sk
[11:08:45 ERROR]: #!#! 
[11:08:45 ERROR]: #!#! Something went horribly wrong with Skript.
[11:08:45 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:08:45 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[11:08:45 ERROR]: #!#! Here is full list of them:
[11:08:45 ERROR]: #!#! TuSKe (github.com/Tuke-Nuke/TuSKe) SkQuery 
[11:08:45 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[11:08:45 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[11:08:45 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[11:08:45 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[11:08:45 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[11:08:45 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[11:08:45 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[11:08:45 ERROR]: #!#! 
[11:08:45 ERROR]: #!#! Stack trace:
[11:08:45 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for recipe
[11:08:45 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1804)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1771)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1519)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:495)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:814)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1535)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1492)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1531)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:495)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:814)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1535)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1492)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:972)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:621)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:389)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:401)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:331)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:361)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:786)
[11:08:45 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:154)
[11:08:45 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[11:08:45 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[11:08:45 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[11:08:45 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492)
[11:08:45 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)
[11:08:45 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11:08:45 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[11:08:45 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[11:08:45 ERROR]: #!#!     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[11:08:45 ERROR]: #!#!     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[11:08:45 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[11:08:45 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[11:08:45 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[11:08:45 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[11:08:45 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[11:08:45 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[11:08:45 ERROR]: #!#! 
[11:08:45 ERROR]: #!#! Version Information:
[11:08:45 ERROR]: #!#!   Skript: 2.2-dev36 (custom version)
[11:08:45 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[11:08:45 ERROR]: #!#!   Minecraft: 1.12.2
[11:08:45 ERROR]: #!#!   Java: 17.0.2 (OpenJDK 64-Bit Server VM 17.0.2+8-86)
[11:08:45 ERROR]: #!#!   OS: Linux amd64 5.4.0-107-generic
[11:08:45 ERROR]: #!#! 
[11:08:45 ERROR]: #!#! Server platform: Paper
[11:08:45 ERROR]: #!#! 
[11:08:45 ERROR]: #!#! Current node: open chest with 3 rows named "&b&lSpawner Menu" to player (Spawnerskript.sk, line 3)
[11:08:45 ERROR]: #!#! Current item: null
[11:08:45 ERROR]: #!#! 
[11:08:45 ERROR]: #!#! Thread: Server thread
[11:08:45 ERROR]: #!#! 
[11:08:45 ERROR]: #!#! Language: english
[11:08:45 ERROR]: #!#! Link parse mode: DISABLED
[11:08:45 ERROR]: #!#! 
[11:08:45 ERROR]: #!#! End of Error.
[11:08:45 ERROR]: #!#!

### Expected Behavior

open spawner buy menu

### Steps to Reproduce

I think i just change to 1.12.2 from 1.8 and tryed to get the skript thing update also

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Addon related see
> #!#! ch.njol.skript.SkriptAPIException: No class info found for recipe

Update your addons, probably TuSKe

**Comment by Pcornel13DK** [comment]
i use this update of tuske **TuSKe 1.8.3-PikachuPatch-v3.jar**
