### ISSUE TITLE
Entity cannot be cast to class Player unnamed module of loader java.net.URLClassLoader

### ISSUE THREAD

**Issue by sgiteer** [SkriptLang/Skript#5124]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here:
https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here:
https://skriptlang.github.io/Skript
[Skript] Skript's tutorials can be found here:
https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-81 (MC: 1.19)
[Skript] Skript Version: 2.6.3
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies:
[Skript] - WorldGuard v7.0.7-SNAPSHOT+2173-3cb4abd
```

### Bug Description

command /music:
 trigger:
  set {music1} to location (-1693, 5, 1164)
  play sound "minecraft:music_disc.stal" for players in radius 10 of {music1}

i tried playing music in a location but it gave this error

### Expected Behavior

when i used the command music should have started playing in the location

### Steps to Reproduce

  play sound "minecraft:music_disc.stal" for players in radius 10 of {music1}

i just tried playing music in a location but it gave this error and said An internal error has occured while trying to perform this command in chat

### Errors or Screenshots

[17:32:57 ERROR]: #!#! 
[17:32:57 ERROR]: #!#! [Skript] Severe Error:
[17:32:57 ERROR]: #!#! 
[17:32:57 ERROR]: #!#! Something went horribly wrong with Skript.
[17:32:57 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:32:57 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[17:32:57 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[17:32:57 ERROR]: #!#! 
[17:32:57 ERROR]: #!#! Stack trace:
[17:32:57 ERROR]: #!#! java.lang.ClassCastException: class [Lorg.bukkit.entity.Entity; cannot be cast to class [Lorg.bukkit.entity.Player; ([Lorg.bukkit.entity.Entity; and [Lorg.bukkit.entity.Player; are in unnamed module of loader java.net.URLClassLoader @759ebb3d)
[17:32:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffPlaySound.execute(EffPlaySound.java:143)
[17:32:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[17:32:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:32:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:32:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[17:32:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:286)
[17:32:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:251)
[17:32:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:256)
[17:32:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands.handleCommand(Commands.java:261)
[17:32:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:178)
[17:32:57 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[17:32:57 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:32:57 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:32:57 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
[17:32:57 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2374)
[17:32:57 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$18(PlayerConnection.java:2153)
[17:32:57 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:32:57 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[17:32:57 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[17:32:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[17:32:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[17:32:57 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[17:32:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[17:32:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[17:32:57 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[17:32:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1307)
[17:32:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1192)
[17:32:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[17:32:57 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[17:32:57 ERROR]: #!#! 
[17:32:57 ERROR]: #!#! Version Information:
[17:32:57 ERROR]: #!#!   Skript: 2.6.3
[17:32:57 ERROR]: #!#!     Flavor: skriptlang-github
[17:32:57 ERROR]: #!#!     Date: 00:55:22.847925631
[17:32:57 ERROR]: #!#!   Bukkit: 1.19-R0.1-SNAPSHOT
[17:32:57 ERROR]: #!#!   Minecraft: 1.19
[17:32:57 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[17:32:57 ERROR]: #!#!   OS: Linux amd64 5.15.0-46-generic
[17:32:57 ERROR]: #!#! 
[17:32:57 ERROR]: #!#! Server platform: Paper
[17:32:57 ERROR]: #!#! 
[17:32:57 ERROR]: #!#! Current node: null
[17:32:57 ERROR]: #!#! Current item: play sound "minecraft:music_disc.stal" to all entities of type [[entitydata:player]] in radius [[long:10]] around {music1} (as org.bukkit.Location)
[17:32:57 ERROR]: #!#! Current trigger: command /musiikki (simple event) (testi.sk, line 372)
[17:32:57 ERROR]: #!#! 
[17:32:57 ERROR]: #!#! Thread: Server thread
[17:32:57 ERROR]: #!#! 
[17:32:57 ERROR]: #!#! Language: english
[17:32:57 ERROR]: #!#! Link parse mode: DISABLED
[17:32:57 ERROR]: #!#! 
[17:32:57 ERROR]: #!#! End of Error.
[17:32:57 ERROR]: #!#! 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Did you ever reload the server? Skript is not designed to be able to /reload or be used by a plugin manager like PlugMan.

Is there a reason you're using an early version of 1.19? I suggest upgrading to 1.19.2 to see if Paper/Spigot fixes this weird casting issue.

Can you provide your plugin list?
