### ISSUE TITLE
Error when i try loading the skript files with command "load skript" .. 

### ISSUE THREAD

**Issue by cooffeeRequired** [SkriptLang/Skript#5128]
### Skript/Server Version

```markdown
[13:52:33 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[13:52:33 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[13:52:33 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[13:52:33 INFO]: [Skript] Server Version: git-Purpur-1802 (MC: 1.19.2)
[13:52:33 INFO]: [Skript] Skript Version: 2.6.3
[13:52:33 INFO]: [Skript] Installed Skript Addons: 
[13:52:33 INFO]: [Skript]  - skript-yaml v1.4
[13:52:33 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[13:52:33 INFO]: [Skript]  - SkBee v2.4.0-Adventure-Beta (https://github.com/ShaneBeee/SkBee)
[13:52:33 INFO]: [Skript] Installed dependencies: 
[13:52:33 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

i try load the file but with script expression `load script` i getting those strange e. But i rlly dunno why

### Expected Behavior

load the file `init.sk` without errors.

### Steps to Reproduce

```hs
function main(status: integer = 1) :: objects:
    {_status} is 1 or 0:
        {_status} = 1:
            loop getProjects():
                if new File("plugins/Skript/scripts/%loop-value%").isDirectory():
                    script "%loop-value%/-init.sk" are not loaded:
                        load skript "%loop-value%/-init.sk"
        else:
            return loaded scripts
    else:
        return false


on load:
    main()
    send "<green>%enabled scripts%"
    send "<red>%disabled scripts where [input are not "-__main__.sk"]%"

on unload:
    loop main(0):
        script "%loop-value%" are loaded:
            unload skript "%loop-value%" if "%loop-value%" isn't "__main__.sk"
```

### Errors or Screenshots
```markdown
[13:49:48 ERROR]: #!#! 
[13:49:48 ERROR]: #!#! [Skript] Severe Error:
[13:49:48 ERROR]: #!#! Exception occurred in Skript's main command
[13:49:48 ERROR]: #!#! Used command: /sk reload __main__.sk
[13:49:48 ERROR]: #!#! 
[13:49:48 ERROR]: #!#! Something went horribly wrong with Skript.
[13:49:48 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:49:48 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[13:49:48 ERROR]: #!#! Here is full list of them:
[13:49:48 ERROR]: #!#! skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) SkBee v2.4.0-Adventure-Beta (https://github.com/ShaneBeee/SkBee) skript-yaml v1.4 
[13:49:48 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[13:49:48 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[13:49:48 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[13:49:48 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[13:49:48 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[13:49:48 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[13:49:48 ERROR]: #!#! 
[13:49:48 ERROR]: #!#! Stack trace:
[13:49:48 ERROR]: #!#! java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 1
[13:49:48 ERROR]: #!#!     at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
[13:49:48 ERROR]: #!#!     at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[13:49:48 ERROR]: #!#!     at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[13:49:48 ERROR]: #!#!     at java.base/java.util.Objects.checkIndex(Objects.java:359)
[13:49:48 ERROR]: #!#!     at java.base/java.util.ArrayList.remove(ArrayList.java:504)
[13:49:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.removeTriggers(SkriptEventHandler.java:211)
[13:49:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.unloadScript_(ScriptLoader.java:1022)
[13:49:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1055)
[13:49:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[13:49:48 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[13:49:48 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[13:49:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:947)
[13:49:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:910)
[13:49:48 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:540)
[13:49:48 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[13:49:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[13:49:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1194)
[13:49:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[13:49:48 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[13:49:48 ERROR]: #!#! 
[13:49:48 ERROR]: #!#! Version Information:
[13:49:48 ERROR]: #!#!   Skript: 2.6.3 (latest)
[13:49:48 ERROR]: #!#!     Flavor: skriptlang-github
[13:49:48 ERROR]: #!#!     Date: 00:55:22.847925631
[13:49:48 ERROR]: #!#!   Bukkit: 1.19.2-R0.1-SNAPSHOT
[13:49:48 ERROR]: #!#!   Minecraft: 1.19.2
[13:49:48 ERROR]: #!#!   Java: 18.0.2-ea (OpenJDK 64-Bit Server VM 18.0.2-ea+9-Ubuntu-222.04)
[13:49:48 ERROR]: #!#!   OS: Linux amd64 5.15.0-48-generic
[13:49:48 ERROR]: #!#! 
[13:49:48 ERROR]: #!#! Server platform: Paper
[13:49:48 ERROR]: #!#! 
[13:49:48 ERROR]: #!#! Current node: null
[13:49:48 ERROR]: #!#! Current item: null
[13:49:48 ERROR]: #!#! 
[13:49:48 ERROR]: #!#! Thread: Server thread
[13:49:48 ERROR]: #!#! 
[13:49:48 ERROR]: #!#! Language: english
[13:49:48 ERROR]: #!#! Link parse mode: STRICT
[13:49:48 ERROR]: #!#! 
[13:49:48 ERROR]: #!#! End of Error.
[13:49:48 ERROR]: #!#! 
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
An add-on is modifying Skript wrongly to throw this error, add-ons problem, but we can fix it from erroring in Skript by stopping it.

**Comment by cooffeeRequired** [comment]
wich addon?

**Comment by AyhamAl-Ali** [comment]
I doubt it's addon related as the addons used are probably not related to this effect however, can you try [this solution](https://github.com/SkriptLang/Skript/issues/5074#issuecomment-1232594225)

**Comment by cooffeeRequired** [comment]
I tried this, but same result

**Comment by APickledWalrus** [comment]
That effect/condition *was* pretty outdated. We just merged the Structure API which includes of cleanup of the mentioned syntax elements. It might be worth testing with the latest nightly build to see if this is still an issue. I'll try to test soon if no one does before me :)

**Comment by cooffeeRequired** [comment]
So my way is only waiting I guess

**Comment by Fusezion** [comment]
> So my way is only waiting I guess

for right now yes, sadly during my testing skript-reflect is now broken when running the latest build of skript
so most likely won't be sure until skript-reflect is updated to work with 2.7 on release

**Comment by Moderocky** [comment]
This appears to have been fixed sometime before the latest patch version.
