### ISSUE TITLE
Skript giant error in console and basic events stop working

### ISSUE THREAD

**Issue by Evanbeer** [SkriptLang/Skript#5149]
### Skript/Server Version

```markdown
[10:59:49 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[10:59:49 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[10:59:49 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[10:59:49 INFO]: [Skript] Server Version: git-Paper-111 (MC: 1.19.1)
[10:59:49 INFO]: [Skript] Skript Version: 2.6.3
[10:59:49 INFO]: [Skript] Installed Skript Addons: None
[10:59:49 INFO]: [Skript] Installed dependencies: 
[10:59:49 INFO]: [Skript]  - Vault v1.7.3-b131
[10:59:49 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

I really dont know, I just got a huge error and basic events like on rightclick stopped working.

### Expected Behavior

its supposed to open a gui when you rightclick a iron door outside the region "nojail" and are not a member of the region 

### Steps to Reproduce
```v
on right click on iron door:
	send "hi" to player
	if "%region at event-block%" doesn't contain "nojail":
		set {_x} to "%region at event-block%"
		set {_x::*} to all members of the region "test"
		if {_x::*} doesn't contain player:
			set metadata tag "cell" of player to chest inventory with 3 rows named "&6%owners of "%region at event-block%"%'s cell"
			set slot 13 of metadata tag "cell" of player to fishing rod named "&eClick to buy &6&lfishing rod &efor 60$!"
			set slot 14 of metadata tag "cell" of player to 3 raw cod named "&eClick to sell your &6&lfish &efor 20$!"
			open (metadata tag "cell" of player) to player
```
I just used this code and got the error

### Errors or Screenshots

[10:56:19 ERROR]: #!#! 
[10:56:19 ERROR]: #!#! [Skript] Severe Error:
[10:56:19 ERROR]: #!#! Could not load Jail.sk
[10:56:19 ERROR]: #!#! 
[10:56:19 ERROR]: #!#! Something went horribly wrong with Skript.
[10:56:19 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[10:56:19 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[10:56:19 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[10:56:19 ERROR]: #!#! 
[10:56:19 ERROR]: #!#! Stack trace:
[10:56:19 ERROR]: #!#! java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 1
[10:56:19 ERROR]: #!#!     at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
[10:56:19 ERROR]: #!#!     at java.base/java.lang.String.substring(String.java:2704)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.VariableString.unquote(VariableString.java:177)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.hooks.regions.classes.Region$2.parse(Region.java:77)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.hooks.regions.classes.Region$2.parse(Region.java:56)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.registrations.Classes.parseSimple(Classes.java:444)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.registrations.Classes.parse(Classes.java:473)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:584)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:753)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.ParseTagPatternElement.match(ParseTagPatternElement.java:79)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1255)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:344)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:627)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.VariableString.newInstance(VariableString.java:255)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.VariableString.newInstance(VariableString.java:131)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:520)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:753)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1255)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:522)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:753)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1255)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.loadCode(Section.java:90)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:118)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.init(Section.java:69)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:255)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.parse(Section.java:156)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.loadCode(Section.java:90)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:118)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.init(Section.java:69)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:255)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.lang.Section.parse(Section.java:156)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:753)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[10:56:19 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[10:56:19 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[10:56:19 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[10:56:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[10:56:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:59)
[10:56:19 ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[10:56:19 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:306)
[10:56:19 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:290)
[10:56:19 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2295)
[10:56:19 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2249)
[10:56:19 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[10:56:19 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[10:56:19 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[10:56:19 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[10:56:19 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[10:56:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[10:56:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[10:56:19 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[10:56:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[10:56:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[10:56:19 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[10:56:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1307)
[10:56:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1195)
[10:56:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[10:56:19 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[10:56:19 ERROR]: #!#! 
[10:56:19 ERROR]: #!#! Version Information:
[10:56:19 ERROR]: #!#!   Skript: 2.6.3 (latest)
[10:56:19 ERROR]: #!#!     Flavor: skriptlang-github
[10:56:19 ERROR]: #!#!     Date: 00:55:22.847925631
[10:56:19 ERROR]: #!#!   Bukkit: 1.19.1-R0.1-SNAPSHOT
[10:56:19 ERROR]: #!#!   Minecraft: 1.19.1
[10:56:19 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[10:56:19 ERROR]: #!#!   OS: Linux amd64 5.15.0-46-generic
[10:56:19 ERROR]: #!#! 
[10:56:19 ERROR]: #!#! Server platform: Paper
[10:56:19 ERROR]: #!#! 
[10:56:19 ERROR]: #!#! Current node: set metadata tag "cell" of player to chest inventory with 3 rows named "&6%owners of "%region at event-block%"%'s cell" (Jail.sk, line 7)
[10:56:19 ERROR]: #!#! Current item: null
[10:56:19 ERROR]: #!#! 
[10:56:19 ERROR]: #!#! Thread: Server thread
[10:56:19 ERROR]: #!#! 
[10:56:19 ERROR]: #!#! Language: english
[10:56:19 ERROR]: #!#! Link parse mode: DISABLED
[10:56:19 ERROR]: #!#! 
[10:56:19 ERROR]: #!#! End of Error.
[10:56:19 ERROR]: #!#! 

### Other

None

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Evanbeer** [comment]
Is there any way i can fix my skript plugin?

**Comment by TPGamesNL** [comment]
> Is there any way i can fix my skript plugin?

You could first save the owners of the region in a list variable, then use that in the item name string.

**Comment by Evanbeer** [comment]
Thats exactly what i tried doing but then i got this error

**Comment by Evanbeer** [comment]
I would like the event to be fixed as soon as possible, cuz i need it for my server and it says on the docs that it should work.

**Comment by DelayedGaming** [comment]
You may download Skript nightly build [here](https://github.com/SkriptLang/Skript/suites/8665355885/artifacts/390068267) (You must sign in to GitHub first) which has the fix.
**Do note that** nightly builds may not be stable, and you shall replace it with a future stable release jar once it has released.
