### ISSUE TITLE
massive error in console, basic events stopped working

### ISSUE THREAD

**Issue by czychuuu** [SkriptLang/Skript#5161]
### Skript/Server Version

```markdown
[15:11:16 INFO]: [Skript] Server Version: git-Paper-111 (MC: 1.19.1)
[15:11:16 INFO]: [Skript] Skript Version: 2.6.3
[15:11:16 INFO]: [Skript] Installed Skript Addons:
[15:11:16 INFO]: [Skript]  - Skellett v2.0.7 (https://forums.skunity.com/resources/skellett.24/)
[15:11:16 INFO]: [Skript]  - skDragon v0.16
[15:11:16 INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[15:11:16 INFO]: [Skript]  - Skungee v2.0.0-BETA-4
[15:11:16 INFO]: [Skript]  - SkQuery v4.1.7
[15:11:16 INFO]: [Skript]  - SkBee v1.17.3 (https://github.com/ShaneBeee/SkBee)
[15:11:16 INFO]: [Skript]  - MythicSkriptAddon v0.99e-SNAPSHOT
[15:11:16 INFO]: [Skript] Installed dependencies:
[15:11:16 INFO]: [Skript]  - Vault v1.7.3-b131
[15:11:16 INFO]: [Skript]  - WorldGuard v7.0.5+3827266
```

### Bug Description

idk what happend eveyrthing worked normally yesterday

### Expected Behavior

code load normally

### Steps to Reproduce

command /tphere <player>:
  trigger:
    if arg 1 is set:
      teleport arg 1 to player

full command from error line

### Errors or Screenshots

[15:06:39 ERROR]: #!#!
[15:06:39 ERROR]: #!#! [Skript] Severe Error:
[15:06:39 ERROR]: #!#! Could not load core.sk
[15:06:39 ERROR]: #!#!
[15:06:39 ERROR]: #!#! Something went horribly wrong with Skript.
[15:06:39 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:06:39 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:06:39 ERROR]: #!#! Here is full list of them:
[15:06:39 ERROR]: #!#! skDragon v0.16 skUtilities v0.9.2 (https://tim740.github.io/) Skungee v2.0.0-BETA-4 SkBee v1.17.3 (https://github.com/ShaneBeee/SkBee) Skellett v2.0.7 (https://forums.skunity.com/resources/skellett.24/) SkQuery v4.1.7 MythicSkriptAddon v0.99e-SNAPSHOT Skar v1.0
[15:06:39 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[15:06:39 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:06:39 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:06:39 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:06:39 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:06:39 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:06:39 ERROR]: #!#!
[15:06:39 ERROR]: #!#! Stack trace:
[15:06:39 ERROR]: #!#! java.lang.UnsupportedOperationException: Parsing not implemented (remember to override parse method): com.gmail.berndivader.mythicskript.classes.CustomClasses$1
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.classes.Parser.parse(Parser.java:53)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.parseSimple(Classes.java:444)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:573)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:753)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1255)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Condition.parse(Condition.java:77)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.init(Section.java:69)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:255)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.parse(Section.java:156)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[15:06:39 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[15:06:39 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:06:39 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[15:06:39 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[15:06:39 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:59)
[15:06:39 ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[15:06:39 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:306)
[15:06:39 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:290)
[15:06:39 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2295)
[15:06:39 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2249)
[15:06:39 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[15:06:39 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[15:06:39 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:06:39 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[15:06:39 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[15:06:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[15:06:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[15:06:39 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[15:06:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[15:06:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[15:06:39 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[15:06:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1307)
[15:06:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1195)
[15:06:39 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[15:06:39 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[15:06:39 ERROR]: #!#!
[15:06:39 ERROR]: #!#! Version Information:
[15:06:39 ERROR]: #!#!   Skript: 2.6.3 (latest)
[15:06:39 ERROR]: #!#!     Flavor: skriptlang-github
[15:06:39 ERROR]: #!#!     Date: 00:55:22.847925631
[15:06:39 ERROR]: #!#!   Bukkit: 1.19.1-R0.1-SNAPSHOT
[15:06:39 ERROR]: #!#!   Minecraft: 1.19.1
[15:06:39 ERROR]: #!#!   Java: 17.0.3.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.3.1+2-LTS-6)
[15:06:39 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[15:06:39 ERROR]: #!#!
[15:06:39 ERROR]: #!#! Server platform: Paper
[15:06:39 ERROR]: #!#!
[15:06:39 ERROR]: #!#! Current node: if arg 1 is set: (core.sk, line 48)
[15:06:39 ERROR]: #!#! Current item: null
[15:06:39 ERROR]: #!#!
[15:06:39 ERROR]: #!#! Thread: Server thread
[15:06:39 ERROR]: #!#!
[15:06:39 ERROR]: #!#! Language: english
[15:06:39 ERROR]: #!#! Link parse mode: DISABLED
[15:06:39 ERROR]: #!#!
[15:06:39 ERROR]: #!#! End of Error.
[15:06:39 ERROR]: #!#!

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment]
This is an issue with MythicSkriptAddon. You should consult the developer of that addon.
