### ISSUE TITLE
Errors console to auto login.

### ISSUE THREAD

**Issue by BySwiizen** [SkriptLang/Skript#5187]
### Skript/Server Version

```markdown
Server Version: git-Paper-246 (MC: 1.19.2)
Skript Version: 2.6.3 (selfbuilt-unknown)
```

### Bug Description

I have errors in the console but the script still works.

### Expected Behavior

Have no errors in the console.

### Steps to Reproduce

```
on join:
    if player is "BySwiizen":
        if ip of player is "****":
            wait 1 second
            send "MESSAGE" to player
            wait 2.5 seconds
            connect player to "Lobby"
```

I replaced the stars with my IP.

### Errors or Screenshots

```
[21:13:15] [Server thread/ERROR]: #!#! 
[21:13:15] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[21:13:15] [Server thread/ERROR]: #!#! 
[21:13:15] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[21:13:15] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[21:13:15] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[21:13:15] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[21:13:15] [Server thread/ERROR]: #!#! 
[21:13:15] [Server thread/ERROR]: #!#! Stack trace:
[21:13:15] [Server thread/ERROR]: #!#! java.lang.IllegalStateException: There are no players online
[21:13:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Utils.sendPluginMessage(Utils.java:416)
[21:13:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffConnect.execute(EffConnect.java:67)
[21:13:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[21:13:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[21:13:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[21:13:15] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[21:13:15] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[21:13:15] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[21:13:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[21:13:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[21:13:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[21:13:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[21:13:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[21:13:15] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[21:13:15] [Server thread/ERROR]: #!#! 
[21:13:15] [Server thread/ERROR]: #!#! Version Information:
[21:13:15] [Server thread/ERROR]: #!#!   Skript: 2.6.3 (latest)
[21:13:15] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[21:13:15] [Server thread/ERROR]: #!#!     Date: 00:55:22.847925631
[21:13:15] [Server thread/ERROR]: #!#!   Bukkit: 1.19.2-R0.1-SNAPSHOT
[21:13:15] [Server thread/ERROR]: #!#!   Minecraft: 1.19.2
[21:13:15] [Server thread/ERROR]: #!#!   Java: 17.0.4 (OpenJDK 64-Bit Server VM 17.0.4+8-Debian-1deb11u1)
[21:13:15] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.19.0
[21:13:15] [Server thread/ERROR]: #!#! 
[21:13:15] [Server thread/ERROR]: #!#! Server platform: Paper
[21:13:15] [Server thread/ERROR]: #!#! 
[21:13:15] [Server thread/ERROR]: #!#! Current node: null
[21:13:15] [Server thread/ERROR]: #!#! Current item: connect the player to "Lobby"
[21:13:15] [Server thread/ERROR]: #!#! Current trigger: join (simple event) (AutoLogin.sk, line 1)
[21:13:15] [Server thread/ERROR]: #!#! 
[21:13:15] [Server thread/ERROR]: #!#! Thread: Server thread
[21:13:15] [Server thread/ERROR]: #!#! 
[21:13:15] [Server thread/ERROR]: #!#! Language: english
[21:13:15] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[21:13:15] [Server thread/ERROR]: #!#! 
[21:13:15] [Server thread/ERROR]: #!#! End of Error.
[21:13:15] [Server thread/ERROR]: #!#! 
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
So how the connect effect works is that it uses plugin messages. Plugin messages uses an online player to send a message to the bungeecord. Plugin messages are a custom packet Mojang created for Modders to send messages to the server and vice versa. Spigot uses this to achieve this. Either Skript's implementation isn't grabbing the only online player or something.

It's probably due to the fact that they just joined the server.

**Comment by AyhamAl-Ali** [comment]
Can you try wait a tick before that connect effect?

**Comment by BySwiizen** [comment]
> Can you try wait a tick before that connect effect?

I have the same problem.

**Comment by TPGamesNL** [comment]
> Can you try wait a tick before that connect effect?

![image](https://user-images.githubusercontent.com/29547183/199733328-497a7317-a54d-4046-8cba-d8cf8c3d5227.png)
:)

**Comment by AyhamAl-Ali** [comment]
> > Can you try wait a tick before that connect effect?
> 
> ![image](https://user-images.githubusercontent.com/29547183/199733328-497a7317-a54d-4046-8cba-d8cf8c3d5227.png)
> :)

Ops, I didn't see that 😬
