### ISSUE TITLE
Support Magma 1.18.2

### ISSUE THREAD

**Issue by Bright1337** [SkriptLang/Skript#5286]
### Skript/Server Version

```markdown
[21:19:03] [Server thread/INFO] [/]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[21:19:03] [Server thread/INFO] [/]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[21:19:03] [Server thread/INFO] [/]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[21:19:03] [Server thread/INFO] [/]: [Skript] Server Version: git-Magma-1.18.2-ba7f64c2 (MC: 1.18.2)
[21:19:03] [Server thread/INFO] [/]: [Skript] Skript Version: 2.6.4
[21:19:03] [Server thread/INFO] [/]: [Skript] Installed Skript Addons: None
[21:19:03] [Server thread/INFO] [/]: [Skript] Installed dependencies: None
```

### Bug Description

Whenever i try to check if variable is set it errors.

### Expected Behavior

output of 
```
Test = <none>
test not set
```

### Steps to Reproduce

run this as an .sk file and use the /test command on a Magma server
```
command /test:
	trigger:
		message "Test = %{test}%"
		if {test} is not set:
			message "test not set"
```

### Errors or Screenshots

[21:17:33] [Server thread/INFO] [/]: [Skript] Reloading all scripts...
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! 
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! [Skript] Severe Error:
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! 
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! Something went horribly wrong with Skript.
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! 
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! Stack trace:
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! java.lang.NoClassDefFoundError: Could not initialize class ch.njol.skript.bukkitutil.BiomeMappings
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.util.BiomeUtils.parse(BiomeUtils.java:35)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.classes.data.BukkitClasses$23.parse(BukkitClasses.java:1055)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.classes.data.BukkitClasses$23.parse(BukkitClasses.java:1051)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:444)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:573)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:753)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.ParseTagPatternElement.match(ParseTagPatternElement.java:79)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:59)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1255)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:77)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:69)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:255)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:156)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1128)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:500)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     at ch.njol.skript.ScriptLoader$AsyncLoaderThread.run(ScriptLoader.java:368)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! 
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! Version Information:
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!   Skript: 2.6.4
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     Flavor: skriptlang-github
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!     Date: 17:14:25.041218900
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!   Minecraft: 1.18.2
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!   Java: 17.0.2 (OpenJDK 64-Bit Server VM 17.0.2+8-86)
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!   OS: Linux amd64 5.8.0-43-generic
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! 
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! Server platform: Spigot
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! 
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! Current node: null
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! Current item: null
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! 
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! Thread: Thread-17
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! 
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! Language: english
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! Link parse mode: DISABLED
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! 
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#! End of Error.
[21:17:33] [Thread-17/ERROR] [Minecraft/]: #!#!

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Magma server implementation is not support with Skript.

**Comment by Bright1337** [comment]
Oh, alright.

**Comment by Moderocky** [comment]
I'm closing this. We can't build in support for other server platforms unless there is an especially good reason, since it costs a massive amount of our time.

People are welcome to create pull requests that fix server compatibility! We'll typically accept these, provided they don't disrupt Skript in some way. However, it won't become official support since we're still not able to maintain this compatibility going forward.
