### ISSUE TITLE
Name of X of Tool

### ISSUE THREAD

**Issue by hotpocket184** [SkriptLang/Skript#5302]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-350 (MC: 1.19.3)
[Skript] Skript Version: 2.6.4
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies: None
```

### Bug Description

An error occurs when trying to get the name of a certain number of the player's tool.

### Expected Behavior

The name of the player's tool should be returned.

### Steps to Reproduce

Getting the name of 1 of the player's tool.
`broadcast name of 1 of player's tool`

### Errors or Screenshots

 ```Stack trace:
 java.lang.ClassCastException: class ch.njol.skript.expressions.ExprTool$1$2 cannot be cast to class ch.njol.skript.entity.EntityType (ch.njol.skript.expressions.ExprTool$1$2 and ch.njol.skript.entity.EntityType are in unnamed module of loader 'Skript-2.6.4.jar' @6cd1a1c4)
     at Skript-2.6.4.jar//ch.njol.skript.expressions.ExprXOf.lambda$get$0(ExprXOf.java:77)
     at Skript-2.6.4.jar//ch.njol.skript.registrations.Converters.convert(Converters.java:390)
     at Skript-2.6.4.jar//ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:381)
     at Skript-2.6.4.jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:102)
     at Skript-2.6.4.jar//ch.njol.skript.expressions.ExprXOf.get(ExprXOf.java:67)
     at Skript-2.6.4.jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:73)
     at Skript-2.6.4.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
     at Skript-2.6.4.jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:73)
     at Skript-2.6.4.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
     at Skript-2.6.4.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:123)
     at Skript-2.6.4.jar//ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:83)
     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
     at Skript-2.6.4.jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:290)
     at Skript-2.6.4.jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:220)
     at Skript-2.6.4.jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:217)
     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftFuture.run(CraftFuture.java:88)
     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
     at java.base/java.lang.Thread.run(Thread.java:833)

 Version Information:
   Skript: 2.6.4 (latest)
     Flavor: skriptlang-github
     Date: 17:14:25.041218900
   Bukkit: 1.19.3-R0.1-SNAPSHOT
   Minecraft: 1.19.3
   Java: 17.0.4.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.4.1+1-LTS-2)
   OS: Windows 10 amd64 10.0

 Server platform: Paper

 Current node: null
 Current item: broadcast the name of [[long:2]] of  tool of the player
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by DelayedGaming** [comment]
Tested via self-built from Skript's master branch, the assigned PR does not resolve this issue.
