### ISSUE TITLE
Assertion throwing errors when verbose is in debug

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#5323]
### Skript/Server Version

Simply running master as of this commit https://github.com/SkriptLang/Skript/commit/bb6ddc5dc1bf3708a5fe6b08a7029aa62008d167
```markdown
Server Version: git-Paper-368 (MC: 1.19.3)
Skript Version: 2.6.4-nightly-bb6ddc5dc (skriptlang-nightly)
Installed Skript Addons: None
Installed dependencies: None
```

### Bug Description

When running the tests in debug mode there are failures with errors.

### Expected Behavior

To not error and cause the tests to fail.

### Steps to Reproduce

Enable debug verbose in the config.sk and run the quickTest gradle task

### Errors or Screenshots
```
[Skript] test "nearest entity does not allow duplicate entities" (test case):
#!#!
#!#! [Skript] Severe Error:
#!#! An error occurred while trying to load a Structure.
#!#!
#!#! Skript is running with developer command-line options.
#!#! If you are not a developer, consider disabling them.
#!#!
#!#! Stack trace:
#!#! java.lang.NullPointerException: Cannot invoke "ch.njol.skript.lang.Condition.toString(org.bukkit.event.Event, boolean)" because "this.condition" is null
#!#!     at Skript.jar//ch.njol.skript.tests.runner.EffAssert.toString(EffAssert.java:104)
#!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:933)
#!#!     at Skript.jar//ch.njol.skript.lang.SkriptEvent.load(SkriptEvent.java:122)
#!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$8(ScriptLoader.java:559)
#!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
#!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
#!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:555)
#!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
#!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
#!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
#!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:515)
#!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:460)
#!#!     at Skript.jar//ch.njol.skript.Skript$1.lambda$run$2(Skript.java:666)
#!#!     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
#!#!     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
#!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
#!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
#!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
#!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
#!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
#!#!     at java.base/java.lang.Thread.run(Thread.java:833)
#!#!
#!#! Version Information:
#!#!   Skript: 2.6.4-nightly-bb6ddc5dc
#!#!     Flavor: skriptlang-nightly
#!#!     Date: 19:43:22.595806300
#!#!   Bukkit: 1.19.3-R0.1-SNAPSHOT
#!#!   Minecraft: 1.19.3
#!#!   Java: 17.0.3.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.3.1+2-LTS-6)
#!#!   OS: Windows 10 amd64 10.0
#!#!
#!#! Server platform: Paper
#!#!
#!#! Current node: assert nearest cow and cow relative to {_null} to fail with "duplicate entities were allowed in nearest entity expr" (..\..\..\..\..\src\test\skript\tests\syntaxes\expressions\ExprNearestEntity.sk, line 2)
#!#! Current item: null
#!#!
#!#! Thread: Server thread
#!#!
#!#! Language: english
#!#! Link parse mode: DISABLED
#!#!
#!#! End of Error.
#!#!
```

### Other
The issue is caused by event being null in toString when in debug mode.

**Comment by TPGamesNL** [comment]
Can be fixed by adjusting EffAssert#toString to take into account that the condition can be null (and mark condition as Nullable)
