### ISSUE TITLE
Structure: Null value for asserted non-null value

### ISSUE THREAD

**Issue by Mushkrem** [SkriptLang/Skript#5336]
### Skript/Server Version

```markdown
2.6.4-nightly-6f2984b (skriptlang-nightly)
git-Paper-366 (MC: 1.19.3)
```

### Bug Description

Instead of: 
```
create a new http server:
    port: 80
```
i did this:
```
create a new http server:
    port: "80"
```
(i made it a string)

### Expected Behavior

well I don't know

### Steps to Reproduce

```java
EntryValidator.builder().addEntryData(new LiteralEntryData<>("port", null, false, Number.class))
```
```java
@Override
public boolean preLoad() {
    final EntryContainer entryContainer = getEntryContainer();

    final Number port = entryContainer.get("port", Number.class, false);
}
```

### Errors or Screenshots

```java
[01:18:23 ERROR]: #!#! Stack trace:
[01:18:23 ERROR]: #!#! java.lang.RuntimeException: Null value for asserted non-null value
[01:18:23 ERROR]: #!#!     at Skript-nightly.jar//org.skriptlang.skript.lang.entry.EntryContainer.get(EntryContainer.java:95)
[01:18:23 ERROR]: #!#!     at skript-name.jar//lol.mushkrem.skname.elements.structures.http.StructHttpServer.preLoad(StructHttpServer.java:45)
[01:18:23 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$7(ScriptLoader.java:538)
[01:18:23 ERROR]: #!#!     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[01:18:23 ERROR]: #!#!     at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[01:18:23 ERROR]: #!#!     at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[01:18:23 ERROR]: #!#!     at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
[01:18:23 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
[01:18:23 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[01:18:23 ERROR]: #!#!     at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[01:18:23 ERROR]: #!#!     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[01:18:23 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[01:18:23 ERROR]: #!#!     at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[01:18:23 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:529)
[01:18:23 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[01:18:23 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[01:18:23 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
[01:18:23 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:515)
[01:18:23 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:460)
[01:18:23 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.Skript$1.run(Skript.java:763)
[01:18:23 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[01:18:23 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[01:18:23 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1114)
[01:18:23 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[01:18:23 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
```

### Other

If it had already been reported, on my defence:
`Just testing things? Good. Please report this bug, so that we can fix it before a stable release.`

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Mushkrem** [comment]
Ah nevermind, I just realized it works as expected. I might need some sleep
