### ISSUE TITLE
Commands.loadCommand: IllegalStateException: No match found

### ISSUE THREAD

**Issue by nananannna** [SkriptLang/Skript#5414]
### Skript/Server Version

```markdown
[11:00:11] [Server thread/ERROR]: #!#! Version Information:
[11:00:11] [Server thread/ERROR]: #!#!   Skript: 2.6.4 (latest)
[11:00:11] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[11:00:11] [Server thread/ERROR]: #!#!     Date: 17:14:25.041218900
[11:00:11] [Server thread/ERROR]: #!#!   Bukkit: 1.19.3-R0.1-SNAPSHOT
[11:00:11] [Server thread/ERROR]: #!#!   Minecraft: 1.19.3
[11:00:11] [Server thread/ERROR]: #!#!   Java: 19.0.2 (Java HotSpot(TM) 64-Bit Server VM 19.0.2+7-44)
[11:00:11] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[11:00:11] [Server thread/ERROR]: #!#!
[11:00:11] [Server thread/ERROR]: #!#! Server platform: Spigot
```

### Bug Description

노트패드 저장하고 서버 리로드 하고나니 에러가 뜨고 저장한 명령어 실행이 안됍니다
After saving the notepad and reloading the server, an error popped up and the saved command could not be executed.

### Expected Behavior

명령어 실행
command execution

### Steps to Reproduce

*

### Errors or Screenshots

```
[11:00:11] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[11:00:11] [Server thread/ERROR]: #!#! Could not load a.sk
[11:00:11] [Server thread/ERROR]: #!#!
[11:00:11] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[11:00:11] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:00:11] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[11:00:11] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[11:00:11] [Server thread/ERROR]: #!#!
[11:00:11] [Server thread/ERROR]: #!#! Stack trace:
[11:00:11] [Server thread/ERROR]: #!#! java.lang.IllegalStateException: No match found
[11:00:11] [Server thread/ERROR]: #!#!     at java.base/java.util.regex.Matcher.group(Matcher.java:644)
[11:00:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:350)
[11:00:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)
[11:00:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[11:00:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[11:00:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[11:00:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[11:00:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[11:00:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:169)
[11:00:11] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:00:11] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[11:00:11] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:847)
[11:00:11] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[11:00:11] [Server thread/ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:306)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:290)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1957)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1919)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67)
[11:00:11] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(SourceFile:18)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1154)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1133)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1110)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1021)
[11:00:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301)
[11:00:11] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1589)
[11:00:11] [Server thread/ERROR]: #!#!
[11:00:11] [Server thread/ERROR]: #!#! Version Information:
[11:00:11] [Server thread/ERROR]: #!#!   Skript: 2.6.4 (latest)
[11:00:11] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[11:00:11] [Server thread/ERROR]: #!#!     Date: 17:14:25.041218900
[11:00:11] [Server thread/ERROR]: #!#!   Bukkit: 1.19.3-R0.1-SNAPSHOT
[11:00:11] [Server thread/ERROR]: #!#!   Minecraft: 1.19.3
[11:00:11] [Server thread/ERROR]: #!#!   Java: 19.0.2 (Java HotSpot(TM) 64-Bit Server VM 19.0.2+7-44)
[11:00:11] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[11:00:11] [Server thread/ERROR]: #!#!
[11:00:11] [Server thread/ERROR]: #!#! Server platform: Spigot
[11:00:11] [Server thread/ERROR]: #!#!
[11:00:11] [Server thread/ERROR]: #!#! Current node: command  /at: (a.sk, line 1)
[11:00:11] [Server thread/ERROR]: #!#! Current item: null
[11:00:11] [Server thread/ERROR]: #!#!
[11:00:11] [Server thread/ERROR]: #!#! Thread: Server thread
[11:00:11] [Server thread/ERROR]: #!#!
[11:00:11] [Server thread/ERROR]: #!#! Language: english
[11:00:11] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[11:00:11] [Server thread/ERROR]: #!#!
[11:00:11] [Server thread/ERROR]: #!#! End of Error.
```

### Other

*

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TPGamesNL** [comment]
Please send the script you're loading (a.sk).
로드 중인 스크립트(a.sk)를 보내주세요.

**Comment by AyhamAl-Ali** [comment]
I was able to replicate, it's due to double spaces used before the `/`
To replicate try this code:
```v
command  /at:
    trigger:
        broadcast "1"
```
