### ISSUE TITLE
The problem occurs when converting a string to a number and using it.

### ISSUE THREAD

**Issue by Serelue** [SkriptLang/Skript#5446]
### Skript/Server Version

```markdown
Server Version: git-Paper-383 (MC: 1.19.3)
Skript Version: 2.6.4
Installed Skript Addons:
 - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
 - SkQuery v4.1.8
 - SkBee v2.7.5 (https://github.com/ShaneBeee/SkBee)
Installed dependencies: None
```

### Bug Description

The problem occurs when converting a string to a number and using it.

### Expected Behavior

Print some text on the console.
```
[16:14:11 INFO]: rsa512 issued server command: /tester 10
[16:14:11 INFO]: Tester! 10
```

### Steps to Reproduce

Code
```
# /tester
command /tester [<string>]:
    trigger:
        if arg 1 parsed as number is set:
            set {_code} to arg 1 parsed as number
            if {_code} > 100 or {_code} < 0:
                message "Wrong number! (0~100)" to player
                stop
            message "Tester! %{_code}%" to console
        else:
            set {_code} to arg 1
            message "Tester! %{_code}%" to console
        
        message "Success!" to player
```
The problem occurs when this code is run multiple times.

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/71011147/218959471-972fcc93-b21c-4f66-9407-6a58c7a5a2f8.png)
```
[16:14:10 INFO]: rsa512 issued server command: /tester 10
[16:14:11 INFO]: Tester! 10
[16:14:11 INFO]: rsa512 issued server command: /tester 10
[16:14:11 ERROR]: #!#!
[16:14:11 ERROR]: #!#! [Skript] Severe Error:
[16:14:11 ERROR]: #!#!
[16:14:11 ERROR]: #!#! Something went horribly wrong with Skript.
[16:14:11 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:14:11 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[16:14:11 ERROR]: #!#! Here is full list of them:
[16:14:11 ERROR]: #!#! skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) SkBee v2.7.5 (https://github.com/ShaneBeee/SkBee) SkQuery v4.1.8
[16:14:11 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[16:14:11 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[16:14:11 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[16:14:11 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[16:14:11 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[16:14:11 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[16:14:11 ERROR]: #!#!
[16:14:11 ERROR]: #!#! Stack trace:
[16:14:11 ERROR]: #!#! ch.njol.skript.SkriptAPIException: UnparsedLiterals must be converted before use
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.UnparsedLiteral.invalidAccessException(UnparsedLiteral.java:272)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.UnparsedLiteral.getSingle(UnparsedLiteral.java:302)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.ExpressionList.getSingle(ExpressionList.java:85)
[16:14:11 ERROR]: #!#!     at SkQuery-4.1.8.jar//com.w00tmast3r.skquery.elements.expressions.ExprComparisons.get(ExprComparisons.java:30)
[16:14:11 ERROR]: #!#!     at SkQuery-4.1.8.jar//com.w00tmast3r.skquery.elements.expressions.ExprComparisons.get(ExprComparisons.java:17)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:158)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:153)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.conditions.CondCompare.lambda$check$2(CondCompare.java:309)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:170)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Variable.check(Variable.java:702)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.conditions.CondCompare.check(CondCompare.java:308)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.sections.SecConditional.walk(SecConditional.java:165)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:286)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:251)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:256)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands.handleCommand(Commands.java:261)
[16:14:11 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:178)
[16:14:11 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[16:14:11 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[16:14:11 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:14:11 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672)
[16:14:11 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2264)
[16:14:11 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
[16:14:11 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[16:14:11 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[16:14:11 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:14:11 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[16:14:11 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[16:14:11 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[16:14:11 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[16:14:11 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[16:14:11 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[16:14:11 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[16:14:11 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[16:14:11 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[16:14:11 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[16:14:11 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[16:14:11 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1589)
[16:14:11 ERROR]: #!#!
[16:14:11 ERROR]: #!#! Version Information:
[16:14:11 ERROR]: #!#!   Skript: 2.6.4 (latest)
[16:14:11 ERROR]: #!#!     Flavor: skriptlang-github
[16:14:11 ERROR]: #!#!     Date: 17:14:25.041218900
[16:14:11 ERROR]: #!#!   Bukkit: 1.19.3-R0.1-SNAPSHOT
[16:14:11 ERROR]: #!#!   Minecraft: 1.19.3
[16:14:11 ERROR]: #!#!   Java: 19.0.1 (Java HotSpot(TM) 64-Bit Server VM 19.0.1+10-21)
[16:14:11 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[16:14:11 ERROR]: #!#!
[16:14:11 ERROR]: #!#! Server platform: Paper
[16:14:11 ERROR]: #!#!
[16:14:11 ERROR]: #!#! Current node: null
[16:14:11 ERROR]: #!#! Current item: if {_code} (as java.lang.Object) is greater than compare (comparator: null)
[16:14:11 ERROR]: #!#! Current trigger: command /tester (simple event) (tester.sk, line 2)
[16:14:11 ERROR]: #!#!
[16:14:11 ERROR]: #!#! Thread: Server thread
[16:14:11 ERROR]: #!#!
[16:14:11 ERROR]: #!#! Language: english
[16:14:11 ERROR]: #!#! Link parse mode: DISABLED
[16:14:11 ERROR]: #!#!
[16:14:11 ERROR]: #!#! End of Error.
[16:14:11 ERROR]: #!#!
```

### Other

It looks like there is a problem with `arg 1 parsed as number`

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment]
> if {_code} > 100 or {_code} < 0:

this syntax doesn't exist in skript as far as I'm aware

**Comment by boxgames1793** [comment]
> 

Problem Solved :P

**Comment by AyhamAl-Ali** [comment]
_Space for Improvment_ 
Investigating the exception part, as it should not throw an exception.

**Comment by TheLimeGlass** [comment]
SkQuery issue, fixed
