### ISSUE TITLE
On Inventory Click causing error

### ISSUE THREAD

**Issue by SampledPark** [SkriptLang/Skript#5483]
### Skript/Server Version

```markdown
2.6.4
```

### Bug Description

Slot 8114 greater than inventory slot count

Current item: if event-inventory is equal to metadata values "wiki" of the player (comparator: null)
Current trigger: inventory click (dispense/spawn/drop/craft/pickup/consume/break/despawn/merge) (wiki.sk, line 523)

[07:42:27] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[07:42:27] [Server thread/ERROR]: #!#! 
[07:42:27] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[07:42:27] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[07:42:27] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[07:42:27] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[07:42:27] [Server thread/ERROR]: #!#! 
[07:42:27] [Server thread/ERROR]: #!#! Stack trace:
[07:42:27] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: Slot 8114 greater than inventory slot count
[07:42:27] [Server thread/ERROR]: #!#!     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:189)
[07:42:27] [Server thread/ERROR]: #!#!     at org.bukkit.inventory.InventoryView.getInventory(InventoryView.java:241)
[07:42:27] [Server thread/ERROR]: #!#!     at org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory(InventoryClickEvent.java:173)
[07:42:27] [Server thread/ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.classes.data.BukkitEventValues$105.get(BukkitEventValues.java:1027)
[07:42:27] [Server thread/ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.classes.data.BukkitEventValues$105.get(BukkitEventValues.java:1023)
[07:42:27] [Server thread/ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.expressions.base.EventValueExpression.getValue(EventValueExpression.java:99)
[07:42:27] [Server thread/ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.expressions.base.EventValueExpression.get(EventValueExpression.java:85)
[07:42:27] [Server thread/ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[07:42:27] [Server thread/ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.expressions.base.WrapperExpression.get(WrapperExpression.java:90)
[07:42:27] [Server thread/ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:158)
[07:42:27] [Server thread/ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.conditions.CondCompare.check(CondCompare.java:308)
[07:42:27] [Server thread/ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.sections.SecConditional.walk(SecConditional.java:165)
[07:42:27] [Server thread/ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[07:42:27] [Server thread/ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[07:42:27] [Server thread/ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[07:42:27] [Server thread/ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[07:42:27] [Server thread/ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[07:42:27] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[07:42:27] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[07:42:27] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2807)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:55)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:11)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1536)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
[07:42:27] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[07:42:27] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[07:42:27] [Server thread/ERROR]: #!#! 
[07:42:27] [Server thread/ERROR]: #!#! Version Information:
[07:42:27] [Server thread/ERROR]: #!#!   Skript: 2.6.4 (latest)
[07:42:27] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[07:42:27] [Server thread/ERROR]: #!#!     Date: 17:14:25.041218900
[07:42:27] [Server thread/ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[07:42:27] [Server thread/ERROR]: #!#!   Minecraft: 1.17.1
[07:42:27] [Server thread/ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[07:42:27] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.15.0-46-generic
[07:42:27] [Server thread/ERROR]: #!#! 
[07:42:27] [Server thread/ERROR]: #!#! Server platform: Paper
[07:42:27] [Server thread/ERROR]: #!#! 
[07:42:27] [Server thread/ERROR]: #!#! Current node: null
[07:42:27] [Server thread/ERROR]: #!#! Current item: if event-inventory is equal to metadata values "wiki" of the player (comparator: null)
[07:42:27] [Server thread/ERROR]: #!#! Current trigger: inventory click (dispense/spawn/drop/craft/pickup/consume/break/despawn/merge) (wiki.sk, line 523)
[07:42:27] [Server thread/ERROR]: #!#! 
[07:42:27] [Server thread/ERROR]: #!#! Thread: Server thread
[07:42:27] [Server thread/ERROR]: #!#! 
[07:42:27] [Server thread/ERROR]: #!#! Language: english
[07:42:27] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[07:42:27] [Server thread/ERROR]: #!#! 
[07:42:27] [Server thread/ERROR]: #!#! End of Error.

### Expected Behavior

it was supposed to work like normally and cancel the event, so players can see the items but not take them out of the inventory

### Steps to Reproduce

Im sorry, i know this is alot and maybe not the best skript.

[CustomWikiSKript.txt](https://github.com/SkriptLang/Skript/files/10865773/CustomWikiSKript.txt)

### Errors or Screenshots

My Server would crash and send the Error message given in bug description. Due to the Crash it would also cause a rollback using the latest backup.

### Other

nope 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Are you running a modded server?

**Comment by erenkarakal** [comment]
Closing due to 1.5 years of inactivity. You can re-open the issue if you encounter it with the latest Skript version.
