### ISSUE TITLE
Composter Inventory

### ISSUE THREAD

**Issue by JakeGBLP** [SkriptLang/Skript#5495]
### Skript/Server Version

```markdown
[13:10:50 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[13:10:50 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[13:10:50 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[13:10:50 INFO]: [Skript] Server Version: git-Paper-445 (MC: 1.19.3)
[13:10:50 INFO]: [Skript] Skript Version: 2.6.4
[13:10:50 INFO]: [Skript] Installed Skript Addons:
[13:10:50 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[13:10:50 INFO]: [Skript]  - Lusk v1.0.1
[13:10:50 INFO]: [Skript]  - SkBee v2.7.4 (https://github.com/ShaneBeee/SkBee)
[13:10:50 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

attempting to open a composter inventory to a player prints a console error

### Expected Behavior

should be removed

### Steps to Reproduce

`open composter inventory to player`

### Errors or Screenshots

[13:09:44 ERROR]: #!#!
[13:09:44 ERROR]: #!#! [Skript] Severe Error:
[13:09:44 ERROR]: #!#!
[13:09:44 ERROR]: #!#! Something went horribly wrong with Skript.
[13:09:44 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:09:44 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[13:09:44 ERROR]: #!#! Here is full list of them:
[13:09:44 ERROR]: #!#! skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) SkBee v2.7.4 (https://github.com/ShaneBeee/SkBee) Lusk v1.0.1
[13:09:44 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[13:09:44 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[13:09:44 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[13:09:44 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[13:09:44 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[13:09:44 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[13:09:44 ERROR]: #!#!
[13:09:44 ERROR]: #!#! Stack trace:
[13:09:44 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_19_R2.inventory.util.CraftInventoryCreator$InventoryConverter.createInventory(org.bukkit.inventory.InventoryHolder, org.bukkit.event.inventory.InventoryType)" because the return value of "java.util.Map.get(Object)" is null
[13:09:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.inventory.util.CraftInventoryCreator.createInventory(CraftInventoryCreator.java:43)
[13:09:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.CraftServer.createInventory(CraftServer.java:2084)
[13:09:44 ERROR]: #!#!     at org.bukkit.Bukkit.createInventory(Bukkit.java:1517)
[13:09:44 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.EffOpenInventory.execute(EffOpenInventory.java:110)
[13:09:44 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[13:09:44 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[13:09:44 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[13:09:44 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:290)
[13:09:44 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:220)
[13:09:44 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:217)
[13:09:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftFuture.run(CraftFuture.java:88)
[13:09:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[13:09:44 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[13:09:44 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[13:09:44 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[13:09:44 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[13:09:44 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:09:44 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[13:09:44 ERROR]: #!#!
[13:09:44 ERROR]: #!#! Version Information:
[13:09:44 ERROR]: #!#!   Skript: 2.6.4 (latest)
[13:09:44 ERROR]: #!#!     Flavor: skriptlang-github
[13:09:44 ERROR]: #!#!     Date: 17:14:25.041218900
[13:09:44 ERROR]: #!#!   Bukkit: 1.19.3-R0.1-SNAPSHOT
[13:09:44 ERROR]: #!#!   Minecraft: 1.19.3
[13:09:44 ERROR]: #!#!   Java: 17.0.2 (Java HotSpot(TM) 64-Bit Server VM 17.0.2+8-LTS-86)
[13:09:44 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:09:44 ERROR]: #!#!
[13:09:44 ERROR]: #!#! Server platform: Paper
[13:09:44 ERROR]: #!#!
[13:09:44 ERROR]: #!#! Current node: null
[13:09:44 ERROR]: #!#! Current item: open [[inventorytype:composter inventory]] to me
[13:09:44 ERROR]: #!#!
[13:09:44 ERROR]: #!#! Thread: Server thread
[13:09:44 ERROR]: #!#!
[13:09:44 ERROR]: #!#! Language: english
[13:09:44 ERROR]: #!#! Link parse mode: DISABLED
[13:09:44 ERROR]: #!#!
[13:09:44 ERROR]: #!#! End of Error.
[13:09:44 ERROR]: #!#!

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by J-ak-e** [comment]
I'm unsure if this extends to other inventory types

**Comment by TheLimeGlass** [comment]
> Related: #4773

This issue is throwing a stack trace, it's different than conflict.

**Comment by TheLimeGlass** [comment]
Spigot bug. They're missing CHISELED_BOOKSHELF and COMPOSTER in CraftBukkit https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/inventory/util/CraftInventoryCreator.java so it errors. Currently not possible in Skript.

**Comment by APickledWalrus** [comment]
A composter is not an inventory type that may be opened. We need to be checking this using https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryType.html#isCreatable()

**Comment by erenkarakal** [comment]
was fixed

<img width="646" height="47" alt="Image" src="https://github.com/user-attachments/assets/9d814a48-85ce-4566-956b-0d5b9fda111a" />
