### ISSUE TITLE
Unrelated default variables causing error

### ISSUE THREAD

**Issue by zikehalil3535** [SkriptLang/Skript#5510]
### Skript/Server Version

```markdown
[15:39:16 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[15:39:16 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[15:39:16 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[15:39:16 INFO]: [Skript] Server Version: git-Purpur-1919 (MC: 1.19.3)
[15:39:16 INFO]: [Skript] Skript Version: 2.7.0-beta1 (skriptlang-github)
[15:39:16 INFO]: [Skript] Installed Skript Addons: None
[15:39:16 INFO]: [Skript] Installed dependencies:
[15:39:16 INFO]: [Skript]  - Vault v1.7.3-b131
[15:39:16 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

[15:38:37 ERROR]: #!#!
[15:38:37 ERROR]: #!#! [Skript] Severe Error:
[15:38:37 ERROR]: #!#!
[15:38:37 ERROR]: #!#! Something went horribly wrong with Skript.
[15:38:37 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:38:37 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[15:38:37 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[15:38:37 ERROR]: #!#!
[15:38:37 ERROR]: #!#! Stack trace:
[15:38:37 ERROR]: #!#! java.util.NoSuchElementException
[15:38:37 ERROR]: #!#!     at java.base/java.util.ArrayDeque.getFirst(ArrayDeque.java:402)
[15:38:37 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.structures.StructVariables$DefaultVariables.add(StructVariables.java:100)
[15:38:37 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.VariableString.toString(VariableString.java:551)
[15:38:37 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.Variable.set(Variable.java:497)
[15:38:37 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.Variable.change(Variable.java:553)
[15:38:37 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:280)
[15:38:37 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[15:38:37 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[15:38:37 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[15:38:37 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[15:38:37 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146)
[15:38:37 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:47)
[15:38:37 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:60)
[15:38:37 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[15:38:37 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:38:37 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[15:38:37 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[15:38:37 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[15:38:37 ERROR]: #!#!     at net.minecraft.server.players.PlayerList.a(PlayerList.java:319)
[15:38:37 ERROR]: #!#!     at net.minecraft.server.network.LoginListener.a(LoginListener.java:202)
[15:38:37 ERROR]: #!#!     at net.minecraft.server.network.LoginListener.d(LoginListener.java:183)
[15:38:37 ERROR]: #!#!     at net.minecraft.server.network.LoginListener.c(LoginListener.java:85)
[15:38:37 ERROR]: #!#!     at net.minecraft.network.NetworkManager.a(NetworkManager.java:594)
[15:38:37 ERROR]: #!#!     at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:233)
[15:38:37 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1594)
[15:38:37 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:488)
[15:38:37 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[15:38:37 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1194)
[15:38:37 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[15:38:37 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[15:38:37 ERROR]: #!#!
[15:38:37 ERROR]: #!#! Version Information:
[15:38:37 ERROR]: #!#!   Skript: 2.7.0-beta1
[15:38:37 ERROR]: #!#!     Flavor: skriptlang-github
[15:38:37 ERROR]: #!#!     Date: 20:28:50.750636200
[15:38:37 ERROR]: #!#!   Bukkit: 1.19.3-R0.1-SNAPSHOT
[15:38:37 ERROR]: #!#!   Minecraft: 1.19.3
[15:38:37 ERROR]: #!#!   Java: 18.0.2.1 (Java HotSpot(TM) 64-Bit Server VM 18.0.2.1+1-1)
[15:38:37 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[15:38:37 ERROR]: #!#!
[15:38:37 ERROR]: #!#! Server platform: Paper
[15:38:37 ERROR]: #!#!
[15:38:37 ERROR]: #!#! Current node: null
[15:38:37 ERROR]: #!#! Current item: set {rank::%the player%} (as java.lang.Object) to [[long:1]]
[15:38:37 ERROR]: #!#! Current trigger: join (simple event) (rutbe.sk, line 72)
[15:38:37 ERROR]: #!#!
[15:38:37 ERROR]: #!#! Thread: Server thread
[15:38:37 ERROR]: #!#!
[15:38:37 ERROR]: #!#! Language: english
[15:38:37 ERROR]: #!#! Link parse mode: DISABLED
[15:38:37 ERROR]: #!#!
[15:38:37 ERROR]: #!#! End of Error.
[15:38:37 ERROR]: #!#!

### Expected Behavior

The argument was supposed to return from <none> to a positive number.

### Steps to Reproduce

If I change the variables like this; add arg 3 to {quest::%arg 2%}

### Errors or Screenshots

https://paste.gg/p/anonymous/97f452e58bef4e2c98d4b193cf1b1048/files/4cc0b8d600c04f6d9e168fb6c3ad375a/raw

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Send your variables section 
```vb
variables:
    {Var} = 1
```
This

**Comment by zikehalil3535** [comment]
> Send your variables section
> 
> ```vbnet
> variables:
>     {Var} = 1
> ```
> 
> This

Btw for past versions working correctly.

variables:

	lvl2money = 1000
	lvl3money = 2000
	lvl4money = 3000
	lvl5money = 4000
	lvl6money = 5000
	lvl7money = 6000
	lvl8money = 7000
	lvl9money = 8000
	lvl10money = 9000
	lvl11money = 10000
	lvl12money = 11000
	lvl13money = 12000
	lvl14money = 13000
	lvl15money = 14000
	
	
	
	lvl2xp = 5
	lvl3xp = 10
	lvl4xp = 15
	lvl5xp = 20
	lvl6xp = 25
	lvl7xp = 30
	lvl8xp = 35
	lvl9xp = 40
	lvl10xp = 45
	lvl11xp = 50
	lvl12xp = 55
	lvl13xp = 60
	lvl14xp = 65
	lvl15xp = 70
	
	
	
	lvl2gorev = 3
	lvl3gorev = 6
	lvl4gorev = 9
	lvl5gorev = 12
	lvl6gorev = 15
	lvl7gorev = 18
	lvl8gorev = 21
	lvl9gorev = 24
	lvl10gorev = 27
	lvl11gorev = 30
	lvl12gorev = 33
	lvl13gorev = 36
	lvl14gorev = 39
	lvl15gorev = 50

**Comment by TheLimeGlass** [comment]
It has to be in variable format. Meaning you need to be putting brackets around those values.

**Comment by zikehalil3535** [comment]
> It has to be in variable format. Meaning you need to be putting brackets around those values.
> 
> I don't believe those would have worked in past versions.

Same skript working on past versions.
