### ISSUE TITLE
DefaultVariables data is null

### ISSUE THREAD

**Issue by Alafrr** [SkriptLang/Skript#5528]
### Skript/Server Version

```markdown
[14:23:16 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:23:16 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[14:23:16 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[14:23:16 INFO]: [Skript] Server Version: git-Paper-448 (MC: 1.19.3)
[14:23:16 INFO]: [Skript] Skript Version: 2.7.0-beta1 (skriptlang-github)
[14:23:16 INFO]: [Skript] Installed Skript Addons: None
[14:23:16 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

[14:18:19 ERROR]: #!#! Stack trace:
[14:18:19 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "ch.njol.skript.structures.StructVariables$DefaultVariables.getVariables()" because "data" is null
[14:18:19 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.structures.StructVariables.postUnload(StructVariables.java:240)
[14:18:19 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.ScriptLoader.unloadScripts(ScriptLoader.java:825)
[14:18:19 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:844)
[14:18:19 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:189)
[14:18:19 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:18:19 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[14:18:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:911)
[14:18:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:874)
[14:18:19 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:501)
[14:18:19 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:448)
[14:18:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[14:18:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[14:18:19 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:18:19 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[14:18:19 ERROR]: #!#!
[14:18:19 ERROR]: #!#! Version Information:
[14:18:19 ERROR]: #!#!   Skript: 2.7.0-beta1 (latest)
[14:18:19 ERROR]: #!#!     Flavor: skriptlang-github
[14:18:19 ERROR]: #!#!     Date: 20:28:50.750636200
[14:18:19 ERROR]: #!#!   Bukkit: 1.19.3-R0.1-SNAPSHOT
[14:18:19 ERROR]: #!#!   Minecraft: 1.19.3
[14:18:19 ERROR]: #!#!   Java: 17.0.6 (Java HotSpot(TM) 64-Bit Server VM 17.0.6+9-LTS-190)
[14:18:19 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[14:18:19 ERROR]: #!#!
[14:18:19 ERROR]: #!#! Server platform: Paper
[14:18:19 ERROR]: #!#!
[14:18:19 ERROR]: #!#! Current node: null
[14:18:19 ERROR]: #!#! Current item: null
[14:18:19 ERROR]: #!#!
[14:18:19 ERROR]: #!#! Thread: Server thread
[14:18:19 ERROR]: #!#!
[14:18:19 ERROR]: #!#! Language: english
[14:18:19 ERROR]: #!#! Link parse mode: DISABLED
[14:18:19 ERROR]: #!#!
[14:18:19 ERROR]: #!#! End of Error.
[14:18:19 ERROR]: #!#!

### Expected Behavior

the skripts were supposed to reload but instead did this.

### Steps to Reproduce

I dont know. Im guessing its an outdated plugin.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Janimations1** [comment]
I dont know what a "related script code" is, please elaborate

**Comment by Janimations1** [comment]
ill send the file if that helps

**Comment by Janimations1** [comment]
[Custom Commands.zip](https://github.com/SkriptLang/Skript/files/10994849/Custom.Commands.zip)
just rename it from .zip to .sk

**Comment by AyhamAl-Ali** [comment]
```v
options:
    prefix: &d[Uni]

on join:
    send "{@prefix} &6Welcome %player%" to all players

command /jump:
    aliases: /j
    permission: skript.jump
    cooldown: 5 seconds
    cooldown message: You need to wait %remaining time% to use this command again
    cooldown bypass: skript.jump.cooldown
    trigger:
        push player upwards at speed 2
        apply resistance 5 to player for 3 seconds
        message "&6&lYou have jumped!"

command /feed:
    permission: skript.feed
    cooldown: 30 seconds
    cooldown message: You need to wait %remaining time% to use this command again
    cooldown bypass: skript.feed.cooldown
    trigger:
        feed player by 3 beefs

command /heal:
    permission: skript.heal
    cooldown: 5 seconds
    cooldown message: You need to wait %remaining time% to use this command again!
    cooldown bypass: skript.heal.cooldown
    trigger:
        heal player by 4 hearts

command /fly:
    permission: skript.fly
    trigger:
        if {fly::%player%} is set:
            send "&f&lYour Flight Mode Is Deactivated" to player
            make player stop flying
            delete {fly::%player%}
        else:
            set {fly::%player%} to true
            send "&f&lYour Flight Mode Is Activated" to player
            make player fly
command /repair:
    permission: skript.repair
    trigger:
        repair tool by 1000

command /kit:
    permission: skript.kit
    trigger:
        give player 1 of diamond sword
        give player 1 of diamond axe
        give player 1 of diamond pickaxe
        give player 1 of diamond helmet
        give player 1 of diamond chestplate
        give player 1 of diamond leggings
        give player 1 of diamond boots
        give player 64 of golden carrots
        
command /spawn:
    permission: skript.spawn
    trigger:
        teleport player to location (153, 63, -213) in world "world"

command /home <text> [<text>]:
    description: Set, delete or travel to your home.
    usage: /home set/remove <name>, /home <name>
    permission: skript.example.home
    executable by: players
    trigger:
        if arg-1 is "set":
            if arg-2 is set:
                set {homes::%uuid of player%::%arg-2%} to player's location
                send "Set your home <green>%arg-2%<reset> to <grey>%location of player%<reset>" to player
            else:
                send "You must specify a name for this home." to player
        else if arg-1 is "remove":
            if arg-2 is set:
                delete {homes::%uuid of player%::%arg-2%}
                send "Deleted your home <green>%arg-2%<reset>" to player
            else:
                send "You must specify the name of this home." to player
        else if arg-2 is set:
            send "Correct usage: /home set/remove <name>" to player
        else if {homes::%uuid of player%::%arg-1%} is set:
            teleport player to {homes::%uuid of player%::%arg-1%}
        else:
            send "You have no home named <green>%arg-1%<reset>." to player
```

**Comment by Alafrr** [comment]
What am I looking for?

**Comment by AyhamAl-Ali** [comment]
This is just for other devs to help identify the issue, we will comment back for any updates.

**Comment by Alafrr** [comment]
alr

**Comment by TheLimeGlass** [comment]
Not the related script.

Please provide all scripts that utilizes the variables: section.

Example
```vb
variables:
	{testing::variables1::%entity%} = 1337
	{testing::variables2::%object%} = 1337
	{testing::variables3::%entity%::%object%} = 1337
	testing::no brackets::%living entity% = "String"
	testing::variables4 = 1.6900000000001
	{testing::regression::%offlineplayer%} = 1337
```

**Comment by Alafrr** [comment]
this issue was already resolved by one of my friends, sorry for not closing this sooner

**Comment by TheLimeGlass** [comment]
How was it resolved? This is causing a Skript error? it should still be considered.

**Comment by Alafrr** [comment]
it wasnt the code, it was something else i didnt realize at the time.

**Comment by TheLimeGlass** [comment]
Are you using addons? The info states your not? Are you modifying Skript code?

**Comment by Alafrr** [comment]
yeah im coding my own stuff, im not using addons
