### ISSUE TITLE
[BUG] Error when enchanting multiple entities' tools

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5530]
### Skript/Server Version

```markdown
[05:31:06 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[05:31:06 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[05:31:06 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[05:31:06 INFO]: [Skript] Server Version: git-Paper-307 (MC: 1.19.2)
[05:31:06 INFO]: [Skript] Skript Version: 2.7.0-beta1 (skriptlang-github)
[05:31:06 INFO]: [Skript] Installed Skript Addons: 
[05:31:06 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[05:31:06 INFO]: [Skript]  - SkBee v2.7.8 (https://github.com/ShaneBeee/SkBee)
[05:31:06 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

When attempting to enchant more than 1 item at a time skript prints a stack trace

### Expected Behavior

All the entities around myself would end up with a item of quick charge 5

### Steps to Reproduce

All I did for this was run the effect command `!enchant entities' tool with quick charge 5`, tried this again with `all pillagers' tool` , error sent is from that attempt

### Errors or Screenshots

```md
[05:26:16 ERROR]: #!#! 
[05:26:16 ERROR]: #!#! [Skript] Severe Error:
[05:26:16 ERROR]: #!#! 
[05:26:16 ERROR]: #!#! Something went horribly wrong with Skript.
[05:26:16 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[05:26:16 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[05:26:16 ERROR]: #!#! Here is full list of them:
[05:26:16 ERROR]: #!#! skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) SkBee v2.7.8 (https://github.com/ShaneBeee/SkBee) 
[05:26:16 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[05:26:16 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[05:26:16 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[05:26:16 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[05:26:16 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[05:26:16 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[05:26:16 ERROR]: #!#! 
[05:26:16 ERROR]: #!#! Stack trace:
[05:26:16 ERROR]: #!#! ch.njol.skript.SkriptAPIException: Call to getSingle() on a non-single expression
[05:26:16 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:63)
[05:26:16 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.util.ConvertedExpression.getSingle(ConvertedExpression.java:157)
[05:26:16 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.effects.EffEnchant.execute(EffEnchant.java:75)
[05:26:16 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[05:26:16 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[05:26:16 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[05:26:16 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:222)
[05:26:16 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.command.Commands$2$1.call(Commands.java:316)
[05:26:16 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.command.Commands$2$1.call(Commands.java:313)
[05:26:16 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
[05:26:16 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[05:26:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[05:26:16 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[05:26:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[05:26:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[05:26:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[05:26:16 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[05:26:16 ERROR]: #!#! 
[05:26:16 ERROR]: #!#! Version Information:
[05:26:16 ERROR]: #!#!   Skript: 2.7.0-beta1 (latest)
[05:26:16 ERROR]: #!#!     Flavor: skriptlang-github
[05:26:16 ERROR]: #!#!     Date: 20:28:50.750636200
[05:26:16 ERROR]: #!#!   Bukkit: 1.19.2-R0.1-SNAPSHOT
[05:26:16 ERROR]: #!#!   Minecraft: 1.19.2
[05:26:16 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12)
[05:26:16 ERROR]: #!#!   OS: Linux amd64 5.15.0-46-generic
[05:26:16 ERROR]: #!#! 
[05:26:16 ERROR]: #!#! Server platform: Paper
[05:26:16 ERROR]: #!#! 
[05:26:16 ERROR]: #!#! Current node: null
[05:26:16 ERROR]: #!#! Current item: enchant ( tool of all entities of type [[entitydata:pillager]] >> ch.njol.skript.classes.data.DefaultConverters$$Lambda$7533/0x00000008021e6ca8@ffea384: ConverterInfo{from=class ch.njol.skript.util.slot.Slot,to=class ch.njol.skript.aliases.ItemType,converter=ch.njol.skript.classes.data.DefaultConverters$$Lambda$7533/0x00000008021e6ca8@ffea384,flag=0}) with Quick Charge 5
[05:26:16 ERROR]: #!#! 
[05:26:16 ERROR]: #!#! Thread: Server thread
[05:26:16 ERROR]: #!#! 
[05:26:16 ERROR]: #!#! Language: english
[05:26:16 ERROR]: #!#! Link parse mode: STRICT
[05:26:16 ERROR]: #!#! 
[05:26:16 ERROR]: #!#! End of Error.
[05:26:16 ERROR]: #!#!
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment]
EffEnchant accepts multiple items but is only programmed to handle one

**Comment by Fusezion** [comment]
This is fixed in https://github.com/SkriptLang/Skript/pull/4366, thought there was an enchantment related one just never noticed

**Comment by TheLimeGlass** [comment]
Requiring @AyhamAl-Ali to review and add tags if pull request mentioned confines to this issue.

**Comment by AyhamAl-Ali** [comment]
Indeed my PR fixes this issue :ok_hand:
