### ISSUE TITLE
IllegalArgumentException: x not finite

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#5567]
### Skript/Server Version

```markdown
2.7.0-beta2
```

### Bug Description

I can't have any fun without breaking Skript now can I.

I was making a player homing bouncy castle, and I broke Skript.

### Expected Behavior

No IllegalArgumentException, bad

### Steps to Reproduce

```vb
on step on slime block:
	block below event-block is moss block
	push player upwards with speed 2.3
	push player forwards with speed 2
	play sound "entity.generic.explode" to player
	set {block} to event-block

on left click:
	push player in the direction of {block} at speed 1

on damage of player:
	cancel event

on script unload:
	delete {block}
```
This should be using SkQuery's `direction from player to {block}` but Skript throws this error.

### Errors or Screenshots

```
[05:17:07 ERROR]: #!#! java.lang.IllegalArgumentException: x not finite
[05:17:07 ERROR]: #!#!     at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118)
[05:17:07 ERROR]: #!#!     at org.bukkit.util.Vector.checkFinite(Vector.java:823)
[05:17:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.entity.CraftEntity.setVelocity(CraftEntity.java:473)
[05:17:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffPush.execute(EffPush.java:80)
[05:17:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[05:17:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[05:17:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[05:17:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[05:17:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146)
[05:17:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:47)
[05:17:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:60)
[05:17:07 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[05:17:07 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[05:17:07 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[05:17:07 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[05:17:07 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[05:17:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545)
[05:17:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502)
[05:17:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497)
[05:17:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:492)
[05:17:07 ERROR]: #!#!     at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:198)
[05:17:07 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1861)
[05:17:07 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:42)
[05:17:07 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:15)
[05:17:07 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[05:17:07 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[05:17:07 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[05:17:07 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[05:17:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[05:17:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[05:17:07 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[05:17:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1318)
[05:17:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[05:17:07 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[05:17:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[05:17:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[05:17:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[05:17:07 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[05:17:07 ERROR]: #!#!
[05:17:07 ERROR]: #!#! Version Information:
[05:17:07 ERROR]: #!#!   Skript: 2.7.0-beta2-nightly-e10edc1b0
[05:17:07 ERROR]: #!#!     Flavor: skriptlang-nightly
[05:17:07 ERROR]: #!#!     Date: 04:57:06.392382400
[05:17:07 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[05:17:07 ERROR]: #!#!   Minecraft: 1.19.4
[05:17:07 ERROR]: #!#!   Java: 17.0.3.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.3.1+2-LTS-6)
[05:17:07 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[05:17:07 ERROR]: #!#!
[05:17:07 ERROR]: #!#! Server platform: Paper
[05:17:07 ERROR]: #!#!
[05:17:07 ERROR]: #!#! Current node: null
[05:17:07 ERROR]: #!#! Current item: push the player  in direction of {block} (as org.bukkit.metadata.Metadatable) at speed [[long:1]]
[05:17:07 ERROR]: #!#! Current trigger: left click (leftclick) (test.sk, line 8)
```

### Other

debug mode was on

x not finte made me think of x gon give it to ya

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Cannot replicate with or without addons
![image](https://user-images.githubusercontent.com/10354869/230286696-0a187f96-75ba-482a-b55e-07ab06134401.png)
![image](https://user-images.githubusercontent.com/10354869/230287083-1f9d3a32-672a-4bf5-bdb7-491ad8060545.png)
