### ISSUE TITLE
Skript 2.7.0-beta2/latest nightly unable to reload some files

### ISSUE THREAD

**Issue by bJaksa** [SkriptLang/Skript#5615]
### Skript/Server Version

```markdown
[09:40:10 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[09:40:10 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[09:40:10 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[09:40:10 INFO]: [Skript] Server Version: git-Pufferfish-66 (MC: 1.19.4)
[09:40:10 INFO]: [Skript] Skript Version: 2.7.0-beta2-nightly-4397dad (skriptlang-nightly)
[09:40:10 INFO]: [Skript] Installed Skript Addons: 
[09:40:10 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[09:40:10 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[09:40:10 INFO]: [Skript]  - DiSky v4.8.0
[09:40:10 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[09:40:10 INFO]: [Skript]  - MHFriends v1.0.0
[09:40:10 INFO]: [Skript]  - SkJade v1.4.3 (https://www.github.com/Ankoki-Dev/SkJade)
[09:40:10 INFO]: [Skript]  - SkBee v2.8.4 (https://github.com/ShaneBeee/SkBee)
[09:40:10 INFO]: [Skript]  - skript-web v1.0-alpha (ankoki.com)
[09:40:10 INFO]: [Skript]  - skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo)
[09:40:10 INFO]: [Skript]  - Core v1.0-SNAPSHOT
[09:40:10 INFO]: [Skript]  - Skript-Advancements v1.5.5
[09:40:10 INFO]: [Skript] Installed dependencies: 
[09:40:10 INFO]: [Skript]  - Vault v1.7.3-b131
[09:40:10 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

I updated my server to pufferfish 1.19.4 and skript addons to their 1.19.4 compatible versions. At first I had skript 2.7.0-beta2 but now i use skript-nightly (latest), in an attempt to fix the issue.

The issue is upon a server restart, some files are not properly loaded. When I try to reload them, I get sent the "reloading (name).sk..." but it never sends and result and doesnt even freeze the server. When i look into console there's an error (look into the error section)

Worth noting that this happened on multiple files, and I do not know of any specific similarities between them.

### Expected Behavior

I would expect the script to normally reload without errors

### Steps to Reproduce

Update to pufferfish 1.19.4
Update skript, addons and other plugins
Restart the server, try to reload some of the files which weren't loaded upon a restart.

### Errors or Screenshots

[09:33:34 INFO]: iReqen issued server command: /sk reload /machines/power.sk
[09:33:34 ERROR]: #!#! 
[09:33:34 ERROR]: #!#! [Skript] Severe Error:
[09:33:34 ERROR]: #!#! Exception occurred in Skript's main command
[09:33:34 ERROR]: #!#! Used command: /sk reload /machines/power.sk
[09:33:34 ERROR]: #!#! 
[09:33:34 ERROR]: #!#! You're running a (buggy) nightly version of Skript.
[09:33:34 ERROR]: #!#! If this is not a test server, switch to a more stable release NOW!
[09:33:34 ERROR]: #!#! Your players are unlikely to appreciate crashes and/or data loss due to Skript bugs.
[09:33:34 ERROR]: #!#! 
[09:33:34 ERROR]: #!#! Just testing things? Good. Please report this bug, so that we can fix it before a stable release.
[09:33:34 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues
[09:33:34 ERROR]: #!#! 
[09:33:34 ERROR]: #!#! Stack trace:
[09:33:34 ERROR]: #!#! java.lang.NullPointerException: Cannot read the array length because "<local1>" is null
[09:33:34 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.events.EvtPeriodical.unload(EvtPeriodical.java:98)
[09:33:34 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.unloadScripts(ScriptLoader.java:808)
[09:33:34 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:842)
[09:33:34 ERROR]: #!#!     at Skript-nightly.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:189)
[09:33:34 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:33:34 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[09:33:34 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906)
[09:33:34 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[09:33:34 ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[09:33:34 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:322)
[09:33:34 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:306)
[09:33:34 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2290)
[09:33:34 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2250)
[09:33:34 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[09:33:34 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[09:33:34 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[09:33:34 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[09:33:34 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[09:33:34 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1344)
[09:33:34 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[09:33:34 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[09:33:34 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1321)
[09:33:34 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1314)
[09:33:34 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[09:33:34 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1292)
[09:33:34 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1180)
[09:33:34 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[09:33:34 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[09:33:34 ERROR]: #!#! 
[09:33:34 ERROR]: #!#! Version Information:
[09:33:34 ERROR]: #!#!   Skript: 2.7.0-beta2-nightly-4397dad
[09:33:34 ERROR]: #!#!     Flavor: skriptlang-nightly
[09:33:34 ERROR]: #!#!     Date: 06:30:08.704379855
[09:33:34 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[09:33:34 ERROR]: #!#!   Minecraft: 1.19.4
[09:33:34 ERROR]: #!#!   Java: 17.0.6 (OpenJDK 64-Bit Server VM 17.0.6+10)
[09:33:34 ERROR]: #!#!   OS: Linux amd64 5.4.0-139-generic
[09:33:34 ERROR]: #!#! 
[09:33:34 ERROR]: #!#! Server platform: Paper
[09:33:34 ERROR]: #!#! 
[09:33:34 ERROR]: #!#! Current node: null
[09:33:34 ERROR]: #!#! Current item: null
[09:33:34 ERROR]: #!#! 
[09:33:34 ERROR]: #!#! Thread: Server thread
[09:33:34 ERROR]: #!#! 
[09:33:34 ERROR]: #!#! Language: english
[09:33:34 ERROR]: #!#! Link parse mode: DISABLED
[09:33:34 ERROR]: #!#! 
[09:33:34 ERROR]: #!#! End of Error.
[09:33:34 ERROR]: #!#! 

### Other

this only happens on some files, they do not seem to have anything particular in common.
When i try to empty the file and reload it again, the same thing occurs, even tho the file is completely empty.
If i create a new file and paste the code, it works but breaks upon a restart
Tried with skript 2.7.0-beta2 and latest nightly build, same on both
I commented out some code and restarted in order to find out the cause but the cause isnt clear to me

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Can you share the code of that script (`/machines/power.sk`)

**Comment by bJaksa** [comment]
> Can you share the code of that script (`/machines/power.sk`)

its long and has many functions located in other files, also thats not the only file thats causing the error, there's many more

**Comment by bJaksa** [comment]
> > Can you share the code of that script (`/machines/power.sk`)
> 
> its long and has many functions located in other files, also thats not the only file thats causing the error, there's many more power.sk is 400 lines (a lot of comments tho) and most is math

ill share mobs.sk tho which is shorter and doesnt have functions from other files:
`# --------------------------------------------------------------------------------------------------- #

#!!    ██████╗ ███████╗ ██████╗ ██╗ ██████╗████████╗███████╗██████╗ ██╗███╗  ██╗ ██████╗ 
#!!    ██╔══██╗██╔════╝██╔════╝ ██║██╔════╝╚══██╔══╝██╔════╝██╔══██╗██║████╗ ██║██╔════╝ 
#!!    ██████╔╝█████╗  ██║  ██╗ ██║╚█████╗    ██║   █████╗  ██████╔╝██║██╔██╗██║██║  ██╗ 
#!!    ██╔══██╗██╔══╝  ██║  ╚██╗██║ ╚═══██╗   ██║   ██╔══╝  ██╔══██╗██║██║╚████║██║  ╚██╗
#!!    ██║  ██║███████╗╚██████╔╝██║██████╔╝   ██║   ███████╗██║  ██║██║██║ ╚███║╚██████╔╝
#!!    ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝╚═════╝    ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝╚═╝  ╚══╝ ╚═════╝ 

# --------------------------------------------------------------------------------------------------- #

import:
    ch.njol.skript.lang.function.Functions
    java.util.ArrayList

function mobs_spawn(id: integer, l: location):
    Functions.getFunction("mobs_spawn%{_id}%").execute([[{_l}]])

function mobs_damageMob(id: integer, a: entity, v: entity):
    runnable("mobs_damage%{_id}%", ({_a}, {_v}))

function mobs_mobDamage(id: integer, a: entity, v: entity):
    runnable("mobs_%{_id}%damage", ({_a}, {_v}))

function mobs_killMob(id: integer, a: entity, v: entity):
    runnable("mobs_kill%{_id}%", ({_a}, {_v}))
    mobs_deathDrops({_id}, location of {_v})

function mobs_updateName(e: entity, name: text):
    wait 1 tick
    set the name of {_e} to "&c❤%health of {_e}%/%max health of {_e}% &7%{_name}%"

function mobs_deathDrops(id: integer, l: location):
    drop 1 of fragment_get({_id}) at location 0.3 above {_l}
    # push (last dropped item) upwards at speed 0.1
    chance of 7%:
        drop round({_id} / 1.5) of fragment_get(-1) at location 0.3 above {_l}
        set {_l} to location of last dropped item
        # line(({_l} ~ vector(-1, 0.3, 1)), ({_l} ~ vector(1, 0.3, -1)))
        # line(({_l} ~ vector(-1, 0.3, -1)), ({_l} ~ vector(1, 0.3, 1)))
        loop 2 times:
            line(({_l} ~ vector(-1, 0.3, 1)), ({_l} ~ vector(1, 0.3, 1)))
            line(({_l} ~ vector(-1, 0.3, 1)), ({_l} ~ vector(-1, 0.3, -1)))
            line(({_l} ~ vector(-1, 0.3, -1)), ({_l} ~ vector(1, 0.3, -1)))
            line(({_l} ~ vector(1, 0.3, 1)), ({_l} ~ vector(1, 0.3, -1)))
            wait 10 ticks

command /addspawnloc <integer>:
    permission: *
    trigger:
        add location of player to {mining::mobs::spawners::%arg-1%::*}
        send "Added to %arg-1%. Now existing: %size of {mining::mobs::spawners::%arg-1%::*}%"

# --------------------------------------------------------------------------------------------------- #

every 90 seconds:
    amount of players in world "mine" > 0 && amount of mobs in world "mine" < 15
    mobs_spawner()

function mobs_spawner():
    loop indices of {mining::mobs::spawners::*}:
        loop {mining::mobs::spawners::%loop-value%::*}:
            set {_l} to location 0.5 blocks above loop-value-2
            chance of 40%:
                mobs_spawn("%loop-value-1%" parsed as integer, {_l})

# --------------------------------------------------------------------------------------------------- #

on damage:
    world is "mine"
    if victim is not a player:
        set {_id} to (tag "custom;mob_type" of nbt compound of victim)
        {_id} is set
        mobs_damageMob({_id}, attacker, victim)
        stop
    if attacker is not a player:
        set {_id} to (tag "custom;mob_type" of nbt compound of attacker) 
        {_id} is set
        mobs_mobDamage({_id}, attacker, victim)
        stop

on death:
    world is "mine"
    if victim is not a player:
        set {_id} to (tag "custom;mob_type" of nbt compound of victim)
        {_id} is set
        mobs_killMob({_id}, attacker, victim)
        stop

# --------------------------------------------------------------------------------------------------- #`

runnable():
`
function runnable(function: text, args: objects):
    set {_functions::run} to function reference {_function} called with args {_args::*}
    set {_proxy} to new proxy instance of Runnable using {_functions::*}
    {_proxy}.run()
`

**Comment by ducksarecoolest** [comment]
I had the same issue and then i downgraded to 1.19.3 and its fixed.

**Comment by bJaksa** [comment]
still have the issue btw

**Comment by APickledWalrus** [comment]
are there any error messages or warnings when the server initially starts and the scripts don't load as expected? it seems like this is caused by parts of a script not properly loading, and thus Skript runs into issues when attempting to unload it.

**Comment by AyhamAl-Ali** [comment]
Any updates?

**Comment by sovdeeth** [comment]
Going to close due to lack of activity. Feel free to re-open if anyone still encounters this issue.
