### ISSUE TITLE
Skript Plugin Not Loading

### ISSUE THREAD

**Issue by Xqow** [SkriptLang/Skript#5641]
### Skript/Server Version

```markdown
My skript plugin is not starting
```

### Bug Description

When I start up my server I get a long error about skript failing to load.

### Expected Behavior

Skript should start up as usual.

### Steps to Reproduce

I don't think that is possible, it might be something with my server, even tho I do not know what it could be. 

### Errors or Screenshots

[10:26:47 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'Skript-2.6.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.VerifyError: Inconsistent stackmap frames at branch target 27
Exception Details:
  Location:
    ch/njol/skript/Skript.<init>()V @14: ifnull
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @14
    flags: { }
    locals: { 'ch/njol/skript/Skript' }
    stack: { 'ch/njol/skript/bstats/BstatsLoader', 'ch/njol/skript/Skript' }
  Stackmap Frame:
    bci: @27
    flags: { }
    locals: { 'ch/njol/skript/Skript' }
    stack: { }
  Bytecode:
    0000000: bb00 7759 b700 782a b700 79b2 006e c600
    0000010: 0dbb 0070 5912 7bb7 007e bf2a b300 6eb1
    0000020:                                        
  Stackmap Table:
    full_frame(@27,{Object[#2]},{})
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.19.4.jar:git-Paper-466]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.19.4.jar:git-Paper-466]
	at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:150) ~[paper-1.19.4.jar:git-Paper-466]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[paper-1.19.4.jar:git-Paper-466]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-466]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.4.jar:git-Paper-466]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-466]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[paper-1.19.4.jar:git-Paper-466]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-466]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 27
Exception Details:
  Location:
    ch/njol/skript/Skript.<init>()V @14: ifnull
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @14
    flags: { }
    locals: { 'ch/njol/skript/Skript' }
    stack: { 'ch/njol/skript/bstats/BstatsLoader', 'ch/njol/skript/Skript' }
  Stackmap Frame:
    bci: @27
    flags: { }
    locals: { 'ch/njol/skript/Skript' }
    stack: { }
  Bytecode:
    0000000: bb00 7759 b700 782a b700 79b2 006e c600
    0000010: 0dbb 0070 5912 7bb7 007e bf2a b300 6eb1
    0000020:                                        
  Stackmap Table:
    full_frame(@27,{Object[#2]},{})
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-466]
	... 9 more

### Other

I own a minehut server, it used to run 1.17.1 and skript worked fine, a few days ago I updated it to 1.19.4 and it started to no longer worker. 

If I reinstall the plugin and restart the server it works as ususal, after a second restart it goes back to not working again. 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Update Skript to[ 2.7.0-beta2](https://github.com/SkriptLang/Skript/releases/tag/2.7.0-beta2) - **CAUTION IT'S BETA VERSION**

**Comment by Xqow** [comment]
I tried updating, but it still isn't working. 

> Update Skript to[ 2.7.0-beta2](https://github.com/SkriptLang/Skript/releases/tag/2.7.0-beta2) - **CAUTION IT'S BETA VERSION**

I tried updating it, but it still is not loading properly.

**Comment by AyhamAl-Ali** [comment]
Send error after updating, make sure no skript addons are loaded as well because some addons may not work yet

**Comment by Xqow** [comment]
Minehut support said they do not offer plugin support and said I could ask their community support
