### ISSUE TITLE
SKRIPT NOT ENABLED IN 1.19.4 PAPER

### ISSUE THREAD

**Issue by JesseeDev2** [SkriptLang/Skript#5642]
### Skript/Server Version

```markdown
[06:57:00 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[06:57:00 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[06:57:00 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[06:57:00 INFO]: [Skript] Server Version: git-Paper-516 (MC: 1.19.4)
[06:57:00 INFO]: [Skript] Skript Version: 2.6.4
[06:57:00 INFO]: [Skript] Installed Skript Addons: None
[06:57:00 INFO]: [Skript] Installed dependencies: 
[06:57:00 INFO]: [Skript]  - Vault v1.7.3-b131
[06:57:00 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

[06:43:56 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'Skript-2.6.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.VerifyError: Inconsistent stackmap frames at branch target 27
Exception Details:
  Location:
    ch/njol/skript/Skript.<init>()V @14: ifnull
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @14
    flags: { }
    locals: { 'ch/njol/skript/Skript' }
    stack: { 'ch/njol/skript/bstats/BstatsLoader', 'ch/njol/skript/Skript' }
  Stackmap Frame:
    bci: @27
    flags: { }
    locals: { 'ch/njol/skript/Skript' }
    stack: { }
  Bytecode:
    0000000: bb00 7759 b700 782a b700 79b2 006e c600
    0000010: 0dbb 0070 5912 7bb7 007e bf2a b300 6eb1
    0000020:                                        
  Stackmap Table:
    full_frame(@27,{Object[#2]},{})
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.19.4.jar:git-Paper-516]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.19.4.jar:git-Paper-516]
        at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:150) ~[paper-1.19.4.jar:git-Paper-516]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[paper-1.19.4.jar:git-Paper-516]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-516]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.4.jar:git-Paper-516]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-516]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-516]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-516]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 27
Exception Details:
  Location:
    ch/njol/skript/Skript.<init>()V @14: ifnull
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @14
    flags: { }
    locals: { 'ch/njol/skript/Skript' }
    stack: { 'ch/njol/skript/bstats/BstatsLoader', 'ch/njol/skript/Skript' }
  Stackmap Frame:
    bci: @27
    flags: { }
    locals: { 'ch/njol/skript/Skript' }
    stack: { }
  Bytecode:
    0000000: bb00 7759 b700 782a b700 79b2 006e c600
    0000010: 0dbb 0070 5912 7bb7 007e bf2a b300 6eb1
    0000020:                                        
  Stackmap Table:
    full_frame(@27,{Object[#2]},{})
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-516]
        ... 9 more

### Expected Behavior

I don't know

### Steps to Reproduce

Install skript -> upload -> start server = error

### Errors or Screenshots

It just that message in console when startup

### Other

No

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by JesseeDev2** [comment]
Please help!

**Comment by DelayedGaming** [comment]
Duplicate issue of #5641

**Comment by TheLimeGlass** [comment]
Are you using Minehut?

**Comment by TheLimeGlass** [comment]
Cannot replicate

**Comment by APickledWalrus** [comment]
What other plugins do you have installed? Are you using (or have used) the addon patcher tool?

**Comment by JesseeDev2** [comment]
1. I hosted in Pterodactyl VPS
2. All the plugins I used nothing else here:
[09:26:27 INFO]:  - AuthMe, CataMines, ChatFormatter, ChatFormatter-PaperSupport, Citizens, CoreProtect, DecentHolograms, Drop2InventoryPlus, DupeProtect, Essentials
[09:26:27 INFO]:  EssentialsChat, EssentialsSpawn, ExcellentCrates, FastAsyncWorldEdit, FastLogin, floodgate, Geyser-Spigot, GSit, ItemEdit, LagAssist
[09:26:27 INFO]:  LiteBans, LuckPerms, Multiverse-Core, Multiverse-Inventories, nAntiBot, NexEngine, *PebbleAntiVPN, Pl-Hide-Pro, PlaceholderAPI, PlayerKits
[09:26:27 INFO]:  PlugManX, ProtocolLib, PvPManager, Shopkeepers, SkinsRestorer, (It red) Skript, spark, SuperVanish, TAB, Vault
[09:26:27 INFO]:  ViaBackwards, ViaVersion, Vulcan, WorldGuard

**Comment by JesseeDev2** [comment]
> Duplicate issue of #5641

I'm not using minehut

**Comment by APickledWalrus** [comment]
Have you tried reinstalling Skript and updating paper to the latest version? Testing without other plugins too?

**Comment by JesseeDev2** [comment]
Yes I did

**Comment by AyhamAl-Ali** [comment]
bear with us a little bit as this is never reported before and just got reported twice in a row.
Can you try using only Skript without any other plugins?
Can you try on latest spigot jar?

**Comment by JesseeDev2** [comment]
> bear with us a little bit as this is never reported before and just got reported twice in a row. Can you try using only Skript without any other plugins? Can you try on latest spigot jar?

Yes I did use it without any other plugins and it still not work!

**Comment by AyhamAl-Ali** [comment]
Is this still happening? if yes, what's your server machine Java version?
