### ISSUE TITLE
Asynchronous command dispatch on chat

### ISSUE THREAD

**Issue by joshwenke** [SkriptLang/Skript#5689]
### Skript/Server Version

```markdown
[14:46:00 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:46:00 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[14:46:00 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[14:46:00 INFO]: [Skript] Server Version: git-Paper-521 (MC: 1.19.4)
[14:46:00 INFO]: [Skript] Skript Version: 2.7.0-beta2 (skriptlang-github)
[14:46:00 INFO]: [Skript] Installed Skript Addons: 
[14:46:00 INFO]: [Skript]  - MongoSK v2.3.1 (https://github.com/Romitou/MongoSK)
[14:46:00 INFO]: [Skript]  - skript-reflect v2.3.1-for-skript-beta (https://github.com/TPGamesNL/skript-reflect)
[14:46:00 INFO]: [Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[14:46:00 INFO]: [Skript]  - SkBee v2.8.4 (https://github.com/ShaneBeee/SkBee)
[14:46:00 INFO]: [Skript] Installed dependencies: 
[14:46:00 INFO]: [Skript]  - Vault v1.7.3-b131
[14:46:00 INFO]: [Skript]  - WorldGuard v7.0.8-SNAPSHOT+2200-4a21bf4
```

### Bug Description

Hello, I am using the Skript-2.7.0-beta2 and experiencing an issue when trying to run commands on a chat event. I did not see any similar posts about this error. I know I'm on a beta version

here is my Skript. Very simple:

```
 on chat:
    execute console command "announce testing"
```

And here is the error log:
https://pastebin.com/raw/LHCXDFJK

### Expected Behavior

A command should be run

### Steps to Reproduce

Write a script with a command in the on chat event

```
 on chat:
    execute console command "announce testing"
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
A chat event is asynchronous. Skript should be synchronizing the command. Place the command inside a function to avoid this issue until then.

**Comment by AyhamAl-Ali** [comment]
**Related issue**

Code used
```java
on chat:
    set block at {_loc} to white wool 
```
Exception
```java
[00:25:15 FATAL]: Thread Async Chat Thread - #2 failed main thread check: block remove
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.world.level.block.state.BlockBehaviour.onRemove(BlockBehaviour.java:145) ~[app:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.onRemove(BlockBehaviour.java:913) ~[app:?]
	at net.minecraft.world.level.chunk.LevelChunk.setType(LevelChunk.java:676) ~[app:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:583) ~[app:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:545) ~[app:?]
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:198) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setBlockData(CraftBlock.java:182) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setType(CraftBlock.java:171) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setType(CraftBlock.java:165) ~[patched_1.17.1.jar:git-Paper-411]
	at ch.njol.skript.bukkitutil.block.NewBlockCompat$NewBlockSetter.setBlock(NewBlockCompat.java:292) ~[Skript.jar:?]
	at ch.njol.skript.util.BlockUtils.set(BlockUtils.java:55) ~[Skript.jar:?]
	at ch.njol.skript.aliases.ItemType.setBlock(ItemType.java:362) ~[Skript.jar:?]
	at ch.njol.skript.classes.data.DefaultChangers$6.change(DefaultChangers.java:308) ~[Skript.jar:?]
	at ch.njol.skript.classes.data.DefaultChangers$6.change(DefaultChangers.java:288) ~[Skript.jar:?]
	at ch.njol.skript.lang.util.ConvertedExpression.change(ConvertedExpression.java:148) ~[Skript.jar:?]
	at ch.njol.skript.expressions.base.WrapperExpression.change(WrapperExpression.java:122) ~[Skript.jar:?]
	at ch.njol.skript.effects.EffChange.execute(EffChange.java:280) ~[Skript.jar:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript.jar:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62) ~[Skript.jar:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90) ~[Skript.jar:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[Skript.jar:?]
	at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146) ~[Skript.jar:?]
	at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:47) ~[Skript.jar:?]
	at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:60) ~[Skript.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-411]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230) ~[patched_1.17.1.jar:git-Paper-411]
	at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115) ~[patched_1.17.1.jar:git-Paper-411]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2179) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2090) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2056) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[app:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:25:15 ERROR]: #!#! 
[00:25:15 ERROR]: #!#! [Skript] Severe Error:
[00:25:15 ERROR]: #!#! 
[00:25:15 ERROR]: #!#! Something went horribly wrong with Skript.
[00:25:15 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:25:15 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[00:25:15 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[00:25:15 ERROR]: #!#! 
[00:25:15 ERROR]: #!#! Stack trace:
[00:25:15 ERROR]: #!#! java.lang.IllegalStateException: Asynchronous block remove!
[00:25:15 ERROR]: #!#!     at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)
[00:25:15 ERROR]: #!#!     at net.minecraft.world.level.block.state.BlockBase.remove(BlockBase.java:145)
[00:25:15 ERROR]: #!#!     at net.minecraft.world.level.block.state.BlockBase$BlockData.remove(BlockBase.java:913)
[00:25:15 ERROR]: #!#!     at net.minecraft.world.level.chunk.Chunk.setType(Chunk.java:676)
[00:25:15 ERROR]: #!#!     at net.minecraft.world.level.World.a(World.java:583)
[00:25:15 ERROR]: #!#!     at net.minecraft.world.level.World.setTypeAndData(World.java:545)
[00:25:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setTypeAndData(CraftBlock.java:198)
[00:25:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setBlockData(CraftBlock.java:182)
[00:25:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setType(CraftBlock.java:171)
[00:25:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.setType(CraftBlock.java:165)
[00:25:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.bukkitutil.block.NewBlockCompat$NewBlockSetter.setBlock(NewBlockCompat.java:292)
[00:25:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.BlockUtils.set(BlockUtils.java:55)
[00:25:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.aliases.ItemType.setBlock(ItemType.java:362)
[00:25:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.classes.data.DefaultChangers$6.change(DefaultChangers.java:308)
[00:25:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.classes.data.DefaultChangers$6.change(DefaultChangers.java:288)
[00:25:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.ConvertedExpression.change(ConvertedExpression.java:148)
[00:25:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.base.WrapperExpression.change(WrapperExpression.java:122)
[00:25:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:280)
[00:25:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[00:25:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[00:25:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[00:25:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[00:25:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146)
[00:25:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:47)
[00:25:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:60)
[00:25:15 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[00:25:15 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:25:15 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[00:25:15 ERROR]: #!#!     at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230)
[00:25:15 ERROR]: #!#!     at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115)
[00:25:15 ERROR]: #!#!     at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64)
[00:25:15 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2179)
[00:25:15 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2090)
[00:25:15 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2056)
[00:25:15 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat$1.run(PacketPlayInChat.java:40)
[00:25:15 ERROR]: #!#!     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[00:25:15 ERROR]: #!#!     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[00:25:15 ERROR]: #!#!     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:25:15 ERROR]: #!#!     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:25:15 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[00:25:15 ERROR]: #!#! 
[00:25:15 ERROR]: #!#! Version Information:
[00:25:15 ERROR]: #!#!   Skript: 2.7.0-beta2 (custom version)
[00:25:15 ERROR]: #!#!     Flavor: selfbuilt-unknown
[00:25:15 ERROR]: #!#!     Date: unknown
[00:25:15 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[00:25:15 ERROR]: #!#!   Minecraft: 1.17.1
[00:25:15 ERROR]: #!#!   Java: 17.0.6 (OpenJDK 64-Bit Server VM 17.0.6+10)
[00:25:15 ERROR]: #!#!   OS: Linux amd64 5.15.108-1-MANJARO
[00:25:15 ERROR]: #!#! 
[00:25:15 ERROR]: #!#! Server platform: Paper
[00:25:15 ERROR]: #!#! 
[00:25:15 ERROR]: #!#! Current node: null
[00:25:15 ERROR]: #!#! Current item: set the block (at (the player >> ch.njol.skript.classes.data.DefaultConverters$$Lambda$5746/0x00000001011c6f90@4cedf9e5: ConverterInfo{from=interface org.bukkit.entity.Entity,to=class org.bukkit.Location,converter=ch.njol.skript.classes.data.DefaultConverters$$Lambda$5746/0x00000001011c6f90@4cedf9e5,flag=4}) >> ch.njol.skript.expressions.ExprBlock$1@725ff27b: ConverterInfo{from=class org.bukkit.Location,to=interface org.bukkit.block.Block,converter=ch.njol.skript.expressions.ExprBlock$1@725ff27b,flag=0}) to [[itemtype:white wool block]]
[00:25:15 ERROR]: #!#! Current trigger: chat (simple event) (test3.sk, line 1105)
[00:25:15 ERROR]: #!#! 
[00:25:15 ERROR]: #!#! Thread: Async Chat Thread - #2
[00:25:15 ERROR]: #!#! 
[00:25:15 ERROR]: #!#! Language: english
[00:25:15 ERROR]: #!#! Link parse mode: DISABLED
[00:25:15 ERROR]: #!#! 
[00:25:15 ERROR]: #!#! End of Error.
[00:25:15 ERROR]: #!#! 
[00:25:15 INFO]: [Skript] # chat took 1.696688 milliseconds
[00:25:15 INFO]: [Skript] == took 1.982476 milliseconds ==
[00:25:15 INFO]: <SkriptDev> colors-test
```

**Comment by joshwenke** [comment]
> Also hi @joshwenke nice to see you still using Skript after all these years.

Hi @TheLimeGlass, great to see you too. I do, I love Skript and it is still the backbone of my server. Thanks for doing so much to keep the project maintained and updated.
