### ISSUE TITLE
group of offline player

### ISSUE THREAD

**Issue by ahmadmsaleem** [SkriptLang/Skript#5692]
### Skript/Server Version

```markdown
Skript v2.6.4
luckPerms v5.4.79 (lastest)
Vault (lastest)
```

### Bug Description

It is not possible for me to get the value of offline player groups, the server I tried on has 0 addons with the lastest luckPerms and Vault version

```
command /test <offline player>:
	trigger:
		broadcast group of arg-1
```

### Expected Behavior

It's should give return the group of offline player

### Steps to Reproduce

Trying parsing in another way, such as the uuid, still doesn't work
```
command /what-ever <text>:
    trigger:
        set {_p} to arg-1 parsed as offline player
        broadcast "%{_p}%"
        broadcast "%group of arg-1 parsed as offline player%"
```

### Errors or Screenshots

```
[10:34:48 ERROR]: #!#!
[10:34:48 ERROR]: #!#! [Skript] Severe Error:
[10:34:48 ERROR]: #!#!
[10:34:48 ERROR]: #!#! Something went horribly wrong with Skript.
[10:34:48 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[10:34:48 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[10:34:48 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[10:34:48 ERROR]: #!#!
[10:34:48 ERROR]: #!#! Stack trace:
[10:34:48 ERROR]: #!#! me.lucko.luckperms.bukkit.vault.ServerThreadLookupException: A Vault API request has been made on the main server thread that LuckPerms cannot safely respond to.
This is NOT a bug - please do not report it to LuckPerms.
Instead, please carefully read the information given below.

LuckPerms cannot respond to the request because to do so:
- it needs to lookup user data for '1973aa4d-5bc4-4428-a584-7eb0fff24c03' (an offline player) from the database

Performing this lookup on the main server thread would cause your server to lag.
There are two solutions to this problem:
  a) Ask the author of the plugin making the request to perform Vault calls for
     offline players "asynchronously" (using the scheduler). Additionally, prefer
     using the methods that accept 'Player' or 'OfflinePlayer' instead of usernames.
     You should be able to identify the plugin making the request in the trace below.
  b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups'
     to true in the LuckPerms configuration file. However, please use this only as
     a last resort.
[10:34:48 ERROR]: #!#!     at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUser(LuckPermsVaultPermission.java:153)
[10:34:48 ERROR]: #!#!     at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userGetPrimaryGroup(LuckPermsVaultPermission.java:272)
[10:34:48 ERROR]: #!#!     at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.getPrimaryGroup(AbstractVaultPermission.java:436)
[10:34:48 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.hooks.permission.expressions.ExprGroup.get(ExprGroup.java:80)
[10:34:48 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.hooks.permission.expressions.ExprGroup.get(ExprGroup.java:45)
[10:34:48 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[10:34:48 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:123)
[10:34:48 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:83)
[10:34:48 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[10:34:48 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[10:34:48 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[10:34:48 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[10:34:48 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:286)
[10:34:48 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:251)
[10:34:48 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:256)
[10:34:48 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:195)
[10:34:48 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[10:34:48 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[10:34:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906)
[10:34:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:869)
[10:34:48 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.bh(DedicatedServer.java:501)
[10:34:48 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:448)
[10:34:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[10:34:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[10:34:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[10:34:48 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[10:34:48 ERROR]: #!#!
[10:34:48 ERROR]: #!#! Version Information:
[10:34:48 ERROR]: #!#!   Skript: 2.6.4 (latest)
[10:34:48 ERROR]: #!#!     Flavor: skriptlang-github
[10:34:48 ERROR]: #!#!     Date: 17:14:25.041218900
[10:34:48 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[10:34:48 ERROR]: #!#!   Minecraft: 1.19.4
[10:34:48 ERROR]: #!#!   Java: 17.0.7 (Java HotSpot(TM) 64-Bit Server VM 17.0.7+8-LTS-224)
[10:34:48 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[10:34:48 ERROR]: #!#!
[10:34:48 ERROR]: #!#! Server platform: Paper
[10:34:48 ERROR]: #!#!
[10:34:48 ERROR]: #!#! Current node: null
[10:34:48 ERROR]: #!#! Current item: broadcast group of the 1st argument
[10:34:48 ERROR]: #!#! Current trigger: command /test11 (simple event) (test.sk, line 1)
[10:34:48 ERROR]: #!#!
[10:34:48 ERROR]: #!#! Thread: Server thread
[10:34:48 ERROR]: #!#!
[10:34:48 ERROR]: #!#! Language: english
[10:34:48 ERROR]: #!#! Link parse mode: DISABLED
[10:34:48 ERROR]: #!#!
[10:34:48 ERROR]: #!#! End of Error.
[10:34:48 ERROR]: #!#!
```

### Other

If there is a way to fix this, I would appreciate a discord ping on skunity server (eult#0001) 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
> Performing this lookup on the main server thread would cause your server to lag.
There are two solutions to this problem:
  a) Ask the author of the plugin making the request to perform Vault calls for
     offline players "asynchronously" (using the scheduler). Additionally, prefer
     using the methods that accept 'Player' or 'OfflinePlayer' instead of usernames.
     You should be able to identify the plugin making the request in the trace below.
  b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups'
     to true in the LuckPerms configuration file. However, please use this only as
     a last resort.

Seems like LuckPerms don't like unsafe vault lookups, I think we can fix that to work with LuckPerms
As for now, you can turn on the unsafe vault lookups in LP config to fix this until we implement a solution for it.
