### ISSUE TITLE
Skript 7.0.2beta2 error

### ISSUE THREAD

**Issue by kikike103** [SkriptLang/Skript#5727]
### Skript/Server Version

```markdown
[20:26:13] [Server thread/INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[20:26:13] [Server thread/INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[20:26:13] [Server thread/INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[20:26:13] [Server thread/INFO]: [Skript] Server Version: 3096a-Spigot-9fb885e-af1a232 (MC: 1.16.5)
[20:26:13] [Server thread/INFO]: [Skript] Skript Version: 2.7.0-beta2 (skriptlang-github)
[20:26:13] [Server thread/INFO]: [Skript] Installed Skript Addons: None
[20:26:13] [Server thread/INFO]: [Skript] Installed dependencies: 
[20:26:13] [Server thread/INFO]: [Skript]  - Vault v1.7.3-b131
[20:26:13] [Server thread/INFO]: [Skript]  - WorldGuard v7.0.5+3827266

![image](https://github.com/SkriptLang/Skript/assets/135162483/cfc64e9f-bfef-43ce-bb2f-73d364720d91)

```

### Bug Description

20:21:38] [Server thread/ERROR]: #!#! Stack trace:
[20:21:38] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[20:21:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getDefaultVariableNames(VariableString.java:607)
[20:21:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Variable.getRaw(Variable.java:326)
[20:21:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Variable.get(Variable.java:341)
[20:21:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Variable.getConverted(Variable.java:488)
[20:21:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Variable.getAll(Variable.java:710)
[20:21:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondIsSet.check(CondIsSet.java:74)
[20:21:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondIsSet.check(CondIsSet.java:80)
[20:21:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.lambda$checkConditions$1(SecConditional.java:363)
[20:21:38] [Server thread/ERROR]: #!#!     at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[20:21:38] [Server thread/ERROR]: #!#!     at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
[20:21:38] [Server thread/ERROR]: #!#!     at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[20:21:38] [Server thread/ERROR]: #!#!     at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
[20:21:38] [Server thread/ERROR]: #!#!     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
[20:21:38] [Server thread/ERROR]: #!#!     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[20:21:38] [Server thread/ERROR]: #!#!     at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[20:21:38] [Server thread/ERROR]: #!#!     at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[20:21:38] [Server thread/ERROR]: #!#!     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:21:38] [Server thread/ERROR]: #!#!     at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:521)
[20:21:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.checkConditions(SecConditional.java:363)
[20:21:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.walk(SecConditional.java:272)
[20:21:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[20:21:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[20:21:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146)
[20:21:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:47)
[20:21:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:60)
[20:21:38] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:21:38] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[20:21:38] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[20:21:38] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:494)
[20:21:38] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:461)
[20:21:38] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:457)
[20:21:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1556)
[20:21:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32)
[20:21:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
[20:21:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28)
[20:21:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[20:21:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144)
[20:21:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[20:21:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118)
[20:21:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061)
[20:21:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054)
[20:21:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[20:21:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038)
[20:21:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970)
[20:21:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)
[20:21:38] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[20:21:38] [Server thread/ERROR]: #!#! 
[20:21:38] [Server thread/ERROR]: #!#! Version Information:
[20:21:38] [Server thread/ERROR]: #!#!   Skript: 2.7.0-beta2
[20:21:38] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[20:21:38] [Server thread/ERROR]: #!#!     Date: 23:34:46.821464600
[20:21:38] [Server thread/ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[20:21:38] [Server thread/ERROR]: #!#!   Minecraft: 1.16.5
[20:21:38] [Server thread/ERROR]: #!#!   Java: 1.8.0_282 (OpenJDK 64-Bit Server VM 25.282-b08)
[20:21:38] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.4.0-77-generic
[20:21:38] [Server thread/ERROR]: #!#! 
[20:21:38] [Server thread/ERROR]: #!#! Server platform: Spigot
[20:21:38] [Server thread/ERROR]: #!#! 
[20:21:38] [Server thread/ERROR]: #!#! Current node: null
[20:21:38] [Server thread/ERROR]: #!#! Current item: if {cratemaker.set.loc.%the location of (the targeted block of the player >> ch.njol.skript.classes.data.DefaultConverters$$Lambda$6799/2038890782@1ec0adc3: ConverterInfo{from=interface org.bukkit.block.Block,to=class org.bukkit.Location,converter=ch.njol.skript.classes.data.DefaultConverters$$Lambda$6799/2038890782@1ec0adc3,flag=4})%} (as java.lang.Object) is set
[20:21:38] [Server thread/ERROR]: #!#! Current trigger: rightclick (rightclick) (lada.sk, line 157)
[20:21:38] [Server thread/ERROR]: #!#! 
[20:21:38] [Server thread/ERROR]: #!#! Thread: Server thread
[20:21:38] [Server thread/ERROR]: #!#! 
[20:21:38] [Server thread/ERROR]: #!#! Language: english
[20:21:38] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[20:21:38] [Server thread/ERROR]: #!#! 
[20:21:38] [Server thread/ERROR]: #!#! End of Error.

### Expected Behavior

I don't knor what happened, is said create a report in here.

### Steps to Reproduce

I dont make anything to this error happened.

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/135162483/aa5988aa-f091-463c-9fa8-894de94e95bd)
![image](https://github.com/SkriptLang/Skript/assets/135162483/34af179b-6b1d-467e-8461-faac984945fb)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/SkriptLang/Skript/issues/5647

Fixed and scheduled for 2.7.0-beta3 already.
