### ISSUE TITLE
loop player in radius of player doesn't work on paper 1.19.4 (Asynchronous getNearbyEntities!)

### ISSUE THREAD

**Issue by HC-Emro** [SkriptLang/Skript#5745]
### Skript/Server Version

```markdown
>.... [05:18:27 INFO]: [Skript] Server Version: git-Paper-550 (MC: 1.19.4)
>.... [05:18:27 INFO]: [Skript] Skript Version: 2.7.0-beta3 (skriptlang-github)
>.... [05:18:27 INFO]: [Skript] Installed Skript Addons: None
>.... [05:18:27 INFO]: [Skript] Installed dependencies:
>.... [05:18:27 INFO]: [Skript] - Vault v1.7.3-b131
>.... [05:18:27 INFO]: [Skript] - WorldGuard v7.0.8-beta-01+cbb2ba7
```

### Bug Description

Spaming errors on console and cancelling the code.

### Expected Behavior

Not spaming errors on console and not cancelling the code.

### Steps to Reproduce

The sections of code:

`else if "%all players in radius 15 of player%" contains " ":`

and

```
on chat:
	if first character of message is not "!":
		loop all players in radius 15 of player: # <--- HERE
			add "&9[%heure()%] &3%player% a dit dans le RP: &b%message%" to {logs::%loop-player%::*}
```

### Errors or Screenshots

```
[05:19:48 ERROR]: Thread Async Chat Thread - #2 failed main thread check: getNearbyEntities
java.lang.Throwable: null
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1083) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1073) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1064) ~[paper-1.19.4.jar:git-Paper-550]
at ch.njol.skript.expressions.ExprEntities.iterator(ExprEntities.java:171) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.expressions.ExprEntities.get(ExprEntities.java:136) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.expressions.ExprEntities.get(ExprEntities.java:52) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.lang.VariableString.toString(VariableString.java:540) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.lang.VariableString.getAll(VariableString.java:668) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.lang.VariableString.getAll(VariableString.java:61) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.conditions.CondContains.check(CondContains.java:99) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.sections.SecConditional.lambda$checkConditions$1(SecConditional.java:363) ~[Skript-2.7.0-beta3.jar:?]
at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?]
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?]
at ch.njol.skript.sections.SecConditional.checkConditions(SecConditional.java:363) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.sections.SecConditional.walk(SecConditional.java:272) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:50) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:63) ~[Skript-2.7.0-beta3.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414) ~[paper-1.19.4.jar:git-Paper-550]
at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100) ~[paper-1.19.4.jar:git-Paper-550]
at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2402) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2558) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$17(ServerGamePacketListenerImpl.java:2231) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! [Skript] Severe Error:
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! Something went horribly wrong with Skript.
>.... [05:19:48 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
>.... [05:19:48 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
>.... [05:19:48 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! Stack trace:
>.... [05:19:48 ERROR]: #!#! java.lang.IllegalStateException: Asynchronous getNearbyEntities!
>.... [05:19:48 ERROR]: #!#! at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)
>.... [05:19:48 ERROR]: #!#! at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1083)
>.... [05:19:48 ERROR]: #!#! at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1073)
>.... [05:19:48 ERROR]: #!#! at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1064)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.expressions.ExprEntities.iterator(ExprEntities.java:171)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.expressions.ExprEntities.get(ExprEntities.java:136)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.expressions.ExprEntities.get(ExprEntities.java:52)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.VariableString.toString(VariableString.java:540)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.VariableString.getAll(VariableString.java:668)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.VariableString.getAll(VariableString.java:61)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.conditions.CondContains.check(CondContains.java:99)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.sections.SecConditional.lambda$checkConditions$1(SecConditional.java:363)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.sections.SecConditional.checkConditions(SecConditional.java:363)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.sections.SecConditional.walk(SecConditional.java:272)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:50)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:63)
>.... [05:19:48 ERROR]: #!#! at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
>.... [05:19:48 ERROR]: #!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [05:19:48 ERROR]: #!#! at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
>.... [05:19:48 ERROR]: #!#! at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
>.... [05:19:48 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
>.... [05:19:48 ERROR]: #!#! at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414)
>.... [05:19:48 ERROR]: #!#! at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100)
>.... [05:19:48 ERROR]: #!#! at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2402)
>.... [05:19:48 ERROR]: #!#! at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2558)
>.... [05:19:48 ERROR]: #!#! at net.minecraft.server.network.PlayerConnection.lambda$handleChat$17(PlayerConnection.java:2231)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
>.... [05:19:48 ERROR]: #!#! at java.base/java.lang.Thread.run(Thread.java:833)
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! Version Information:
>.... [05:19:48 ERROR]: #!#! Skript: 2.7.0-beta3 (latest)
>.... [05:19:48 ERROR]: #!#! Flavor: skriptlang-github
>.... [05:19:48 ERROR]: #!#! Date: 03:18:03.366646700
>.... [05:19:48 ERROR]: #!#! Bukkit: 1.19.4-R0.1-SNAPSHOT
>.... [05:19:48 ERROR]: #!#! Minecraft: 1.19.4
>.... [05:19:48 ERROR]: #!#! Java: 17.0.5 (OpenJDK 64-Bit Server VM 17.0.5+8)
>.... [05:19:48 ERROR]: #!#! OS: Linux amd64 4.9.0-16-amd64
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! Server platform: Paper
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! Current node: null
>.... [05:19:48 ERROR]: #!#! Current item: else if "%all entities of type [[entitydata:player]] in radius [[long:15]] around (the player >> ch.njol.skript.classes.data.DefaultConverters$$Lambda$8551/0x0000000802775620@23506a2e: ConverterInfo{from=interface org.bukkit.entity.Entity,to=class org.bukkit.Location,converter=ch.njol.skript.classes.data.DefaultConverters$$Lambda$8551/0x0000000802775620@23506a2e,flag=4})%" contains " "
>.... [05:19:48 ERROR]: #!#! Current trigger: chat (simple event) (alls2.sk, line 951)
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! Thread: Async Chat Thread - #2
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! Language: english
>.... [05:19:48 ERROR]: #!#! Link parse mode: STRICT
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! End of Error.
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: Thread Async Chat Thread - #2 failed main thread check: getNearbyEntities
java.lang.Throwable: null
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1083) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1073) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1064) ~[paper-1.19.4.jar:git-Paper-550]
at ch.njol.skript.expressions.ExprEntities.iterator(ExprEntities.java:171) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.sections.SecLoop.walk(SecLoop.java:134) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:50) ~[Skript-2.7.0-beta3.jar:?]
at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:63) ~[Skript-2.7.0-beta3.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414) ~[paper-1.19.4.jar:git-Paper-550]
at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100) ~[paper-1.19.4.jar:git-Paper-550]
at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2402) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2558) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$17(ServerGamePacketListenerImpl.java:2231) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! [Skript] Severe Error:
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! Something went horribly wrong with Skript.
>.... [05:19:48 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
>.... [05:19:48 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
>.... [05:19:48 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! Stack trace:
>.... [05:19:48 ERROR]: #!#! java.lang.IllegalStateException: Asynchronous getNearbyEntities!
>.... [05:19:48 ERROR]: #!#! at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)
>.... [05:19:48 ERROR]: #!#! at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1083)
>.... [05:19:48 ERROR]: #!#! at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1073)
>.... [05:19:48 ERROR]: #!#! at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1064)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.expressions.ExprEntities.iterator(ExprEntities.java:171)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.sections.SecLoop.walk(SecLoop.java:134)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:50)
>.... [05:19:48 ERROR]: #!#! at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:63)
>.... [05:19:48 ERROR]: #!#! at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
>.... [05:19:48 ERROR]: #!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [05:19:48 ERROR]: #!#! at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
>.... [05:19:48 ERROR]: #!#! at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
>.... [05:19:48 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
>.... [05:19:48 ERROR]: #!#! at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414)
>.... [05:19:48 ERROR]: #!#! at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100)
>.... [05:19:48 ERROR]: #!#! at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2402)
>.... [05:19:48 ERROR]: #!#! at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2558)
>.... [05:19:48 ERROR]: #!#! at net.minecraft.server.network.PlayerConnection.lambda$handleChat$17(PlayerConnection.java:2231)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
>.... [05:19:48 ERROR]: #!#! at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
>.... [05:19:48 ERROR]: #!#! at java.base/java.lang.Thread.run(Thread.java:833)
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! Version Information:
>.... [05:19:48 ERROR]: #!#! Skript: 2.7.0-beta3 (latest)
>.... [05:19:48 ERROR]: #!#! Flavor: skriptlang-github
>.... [05:19:48 ERROR]: #!#! Date: 03:18:03.366646700
>.... [05:19:48 ERROR]: #!#! Bukkit: 1.19.4-R0.1-SNAPSHOT
>.... [05:19:48 ERROR]: #!#! Minecraft: 1.19.4
>.... [05:19:48 ERROR]: #!#! Java: 17.0.5 (OpenJDK 64-Bit Server VM 17.0.5+8)
>.... [05:19:48 ERROR]: #!#! OS: Linux amd64 4.9.0-16-amd64
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! Server platform: Paper
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! Current node: null
>.... [05:19:48 ERROR]: #!#! Current item: loop all entities of type [[entitydata:player]] in radius [[long:15]] around (the player >> ch.njol.skript.classes.data.DefaultConverters$$Lambda$8551/0x0000000802775620@23506a2e: ConverterInfo{from=interface org.bukkit.entity.Entity,to=class org.bukkit.Location,converter=ch.njol.skript.classes.data.DefaultConverters$$Lambda$8551/0x0000000802775620@23506a2e,flag=4})
>.... [05:19:48 ERROR]: #!#! Current trigger: chat (simple event) (zlogs.sk, line 6)
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! Thread: Async Chat Thread - #2
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! Language: english
>.... [05:19:48 ERROR]: #!#! Link parse mode: STRICT
>.... [05:19:48 ERROR]: #!#!
>.... [05:19:48 ERROR]: #!#! End of Error.
>.... [05:19:48 ERROR]: #!#!
```

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
You cannot use world related elements when in an async event such as the chat event. We have an issue to address this by syncing the event.

Duplciate https://github.com/SkriptLang/Skript/issues/5745
