### ISSUE TITLE
[BUG] UnsuportedOperationException when using delete changer on target expression

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5761]
### Skript/Server Version

```markdown
[21:02:48 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[21:02:48 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[21:02:48 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[21:02:48 INFO]: [Skript] Server Version: git-Paper-45 (MC: 1.20.1)
[21:02:48 INFO]: [Skript] Skript Version: 2.7.0-beta3 (skriptlang-github)
[21:02:48 INFO]: [Skript] Installed Skript Addons: None
[21:02:48 INFO]: [Skript] Installed dependencies: 
[21:02:48 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

While I was minding my own business making some tweaks to an addon I realized I got sent a weird exception I don't recall seeing before.  The effect works as i'd expect it to but returns the effected operation. When you attempt to `delete target` or `delete target of player` you'll be send an UnsupportedOperationException

### Expected Behavior

Skript to not send an exception into my console whenever I use the delete effect

### Steps to Reproduce

All you need to do is execute `delete target of player` will send reguardless if you look at an entity

### Errors or Screenshots

```md[21:02:25 ERROR]: #!#! 
[21:02:25 ERROR]: #!#! [Skript] Severe Error:
[21:02:25 ERROR]: #!#! 
[21:02:25 ERROR]: #!#! Something went horribly wrong with Skript.
[21:02:25 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[21:02:25 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[21:02:25 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[21:02:25 ERROR]: #!#! 
[21:02:25 ERROR]: #!#! Stack trace:
[21:02:25 ERROR]: #!#! java.lang.UnsupportedOperationException
[21:02:25 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.util.SimpleExpression.change(SimpleExpression.java:238)
[21:02:25 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.expressions.ExprTarget.change(ExprTarget.java:130)
[21:02:25 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:280)
[21:02:25 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[21:02:25 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[21:02:25 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[21:02:25 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:222)
[21:02:25 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.command.Commands$2$1.call(Commands.java:316)
[21:02:25 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.command.Commands$2$1.call(Commands.java:313)
[21:02:25 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
[21:02:25 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[21:02:25 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1480)
[21:02:25 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[21:02:25 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)
[21:02:25 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[21:02:25 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[21:02:25 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1623)
[21:02:25 ERROR]: #!#! 
[21:02:25 ERROR]: #!#! Version Information:
[21:02:25 ERROR]: #!#!   Skript: 2.7.0-beta3 (latest)
[21:02:25 ERROR]: #!#!     Flavor: skriptlang-github
[21:02:25 ERROR]: #!#!     Date: 03:18:03.366646700
[21:02:25 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[21:02:25 ERROR]: #!#!   Minecraft: 1.20.1
[21:02:25 ERROR]: #!#!   Java: 20.0.1 (OpenJDK 64-Bit Server VM 20.0.1+9-29)
[21:02:25 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[21:02:25 ERROR]: #!#! 
[21:02:25 ERROR]: #!#! Server platform: Paper
[21:02:25 ERROR]: #!#! 
[21:02:25 ERROR]: #!#! Current node: null
[21:02:25 ERROR]: #!#! Current item: delete/clear target
[21:02:25 ERROR]: #!#! 
[21:02:25 ERROR]: #!#! Thread: Server thread
[21:02:25 ERROR]: #!#! 
[21:02:25 ERROR]: #!#! Language: english
[21:02:25 ERROR]: #!#! Link parse mode: STRICT
[21:02:25 ERROR]: #!#! 
[21:02:25 ERROR]: #!#! End of Error.
[21:02:25 ERROR]: #!#! 

```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
There is no `return` in the change method in ExprTarget.
