### ISSUE TITLE
[BUG] NullPointException when using EffActionBar

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5776]
### Skript/Server Version

```markdown
[04:28:31 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[04:28:31 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[04:28:31 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[04:28:31 INFO]: [Skript] Server Version: git-Paper-45 (MC: 1.20.1)
[04:28:31 INFO]: [Skript] Skript Version: 2.7.0-beta3 (skriptlang-github)
[04:28:31 INFO]: [Skript] Installed Skript Addons: 
[04:28:31 INFO]: [Skript]  - SkBee v2.13.0 (https://github.com/ShaneBeee/SkBee)
[04:28:31 INFO]: [Skript] Installed dependencies: 
[04:28:31 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

When using the send action bar effect, if you provide a null value for string it causes an exception to be sent to console

### Expected Behavior

Not to be sent an exception into my console

### Steps to Reproduce

```
send action bar {_null} to players
```

### Errors or Screenshots

```md
[04:18:08 ERROR]: #!#! 
[04:18:08 ERROR]: #!#! [Skript] Severe Error:
[04:18:08 ERROR]: #!#! 
[04:18:08 ERROR]: #!#! Something went horribly wrong with Skript.
[04:18:08 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[04:18:08 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[04:18:08 ERROR]: #!#! Here is full list of them:
[04:18:08 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) SkBee v2.13.0 (https://github.com/ShaneBeee/SkBee) 
[04:18:08 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[04:18:08 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[04:18:08 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[04:18:08 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[04:18:08 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[04:18:08 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[04:18:08 ERROR]: #!#! 
[04:18:08 ERROR]: #!#! Stack trace:
[04:18:08 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "String.toCharArray()" because "msg" is null
[04:18:08 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.util.chat.ChatMessages.parse(ChatMessages.java:191)
[04:18:08 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.util.chat.ChatMessages.parseToArray(ChatMessages.java:417)
[04:18:08 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.effects.EffActionBar.execute(EffActionBar.java:68)
[04:18:08 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[04:18:08 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[04:18:08 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[04:18:08 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:222)
[04:18:08 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:162)
[04:18:08 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[04:18:08 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[04:18:08 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[04:18:08 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[04:18:08 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[04:18:08 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[04:18:08 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:496)
[04:18:08 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:448)
[04:18:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)
[04:18:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[04:18:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[04:18:08 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1623)
[04:18:08 ERROR]: #!#! 
[04:18:08 ERROR]: #!#! Version Information:
[04:18:08 ERROR]: #!#!   Skript: 2.7.0-beta3 (latest)
[04:18:08 ERROR]: #!#!     Flavor: skriptlang-github
[04:18:08 ERROR]: #!#!     Date: 03:18:03.366646700
[04:18:08 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[04:18:08 ERROR]: #!#!   Minecraft: 1.20.1
[04:18:08 ERROR]: #!#!   Java: 20.0.1 (OpenJDK 64-Bit Server VM 20.0.1+9-29)
[04:18:08 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[04:18:08 ERROR]: #!#! 
[04:18:08 ERROR]: #!#! Server platform: Paper
[04:18:08 ERROR]: #!#! 
[04:18:08 ERROR]: #!#! Current node: null
[04:18:08 ERROR]: #!#! Current item: send action bar {_msg} (as java.lang.String) to all entities of type [[entitydata:player]]
[04:18:08 ERROR]: #!#! 
[04:18:08 ERROR]: #!#! Thread: Server thread
[04:18:08 ERROR]: #!#! 
[04:18:08 ERROR]: #!#! Language: english
[04:18:08 ERROR]: #!#! Link parse mode: STRICT
[04:18:08 ERROR]: #!#! 
[04:18:08 ERROR]: #!#! End of Error.
[04:18:08 ERROR]: #!#! 
```

### Other

https://github.com/SkriptLang/Skript/blob/011c91eb06c0fb8d5bfc0df385ee3d5dc9a0ef9c/src/main/java/ch/njol/skript/effects/EffActionBar.java#L65-L71

This should be caused by the assert method.
Didn't find any other issue that brought up this issue

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
The assertion doesn't stop execution on a live server, it's to be caught by the test environment, but we probably don't have any test syntaxes involving actionbar for obvious reasons.

**Comment by Moderocky** [comment]
> we probably don't have any test syntaxes involving actionbar for obvious reasons.
I test messages by making a dummy command sender that stores what its sent and check the output against what I expect to see.
