### ISSUE TITLE
[BUG] ExprBlocks returning NullPointException

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5787]
### Skript/Server Version

```markdown
[19:30:40 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[19:30:40 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[19:30:40 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[19:30:40 INFO]: [Skript] Server Version: git-Paper-45 (MC: 1.20.1)
[19:30:40 INFO]: [Skript] Skript Version: 2.7.0-beta3 (skriptlang-github)
[19:30:40 INFO]: [Skript] Installed Skript Addons: 
[19:30:40 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[19:30:40 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[19:30:40 INFO]: [Skript]  - skript-reflect v2.3.1-for-skript-beta (https://github.com/TPGamesNL/skript-reflect)
[19:30:40 INFO]: [Skript]  - SkBee v2.14.0 (https://github.com/ShaneBeee/SkBee)
[19:30:40 INFO]: [Skript] Installed dependencies: 
[19:30:40 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

When attempting to use `all blocks %direction% [%locations%]` no matter what you type you always are sent an internal exception with a NPE sent into console

### Expected Behavior

All blocks are retrieved and no exceptions are sent into console

### Steps to Reproduce

any of theses
```
blocks above player
blocks below player
blocks south of player
blocks east of player
```

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/81952476/95d186b6-bfc6-4073-b75b-6eb8685c9a72)

```md
[19:32:50 ERROR]: #!#! Stack trace:
[19:32:50 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "ch.njol.skript.lang.Expression.getSingle(org.bukkit.event.Event)" because "numberExpression" is null
[19:32:50 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.expressions.ExprBlocks.iterator(ExprBlocks.java:154)
[19:32:50 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.expressions.ExprBlocks.get(ExprBlocks.java:123)
[19:32:50 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.expressions.ExprBlocks.get(ExprBlocks.java:48)
[19:32:50 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101)
[19:32:50 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.effects.EffMessage.execute(EffMessage.java:123)
[19:32:50 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[19:32:50 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[19:32:50 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[19:32:50 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:222)
[19:32:50 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.command.Commands$2$1.call(Commands.java:316)
[19:32:50 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.command.Commands$2$1.call(Commands.java:313)
[19:32:50 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
[19:32:50 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[19:32:50 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1480)
[19:32:50 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[19:32:50 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)
[19:32:50 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[19:32:50 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[19:32:50 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1623)
[19:32:50 ERROR]: #!#! 
[19:32:50 ERROR]: #!#! Version Information:
[19:32:50 ERROR]: #!#!   Skript: 2.7.0-beta3 (latest)
[19:32:50 ERROR]: #!#!     Flavor: skriptlang-github
[19:32:50 ERROR]: #!#!     Date: 03:18:03.366646700
[19:32:50 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[19:32:50 ERROR]: #!#!   Minecraft: 1.20.1
[19:32:50 ERROR]: #!#!   Java: 20.0.1 (OpenJDK 64-Bit Server VM 20.0.1+9-29)
[19:32:50 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[19:32:50 ERROR]: #!#! 
[19:32:50 ERROR]: #!#! Server platform: Paper
[19:32:50 ERROR]: #!#! 
[19:32:50 ERROR]: #!#! Current node: null
[19:32:50 ERROR]: #!#! Current item: send blocks above (me >> ch.njol.skript.classes.data.DefaultConverters$$Lambda$6630/0x00000008022f0618@2ac4c66b: ConverterInfo{from=interface org.bukkit.entity.Entity,to=class org.bukkit.Location,converter=ch.njol.skript.classes.data.DefaultConverters$$Lambda$6630/0x00000008022f0618@2ac4c66b,flag=4}) to event-player/console
[19:32:50 ERROR]: #!#! 
[19:32:50 ERROR]: #!#! Thread: Server thread
[19:32:50 ERROR]: #!#! 
[19:32:50 ERROR]: #!#! Language: english
[19:32:50 ERROR]: #!#! Link parse mode: STRICT
[19:32:50 ERROR]: #!#! 
[19:32:50 ERROR]: #!#! End of Error.
[19:32:50 ERROR]: #!#! 
```

### Other

This issue seems to have been created by https://github.com/SkriptLang/Skript/pull/5566 and is currently present in at least 2.7.0-beta3

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
To be specific:
Lines 153 and 154 cast the expression to ExprDirection and use the `amount` field:
```java
Expression<Number> numberExpression = ((ExprDirection) this.direction).amount;
Number number = numberExpression.getSingle(event);
```
This field is nullable in ExprDirection and ExprBlocks does not handle this case.
