### ISSUE TITLE
Could not pass event BlockBreakEvent to Skript v2.6.4

### ISSUE THREAD

**Issue by Xqow** [SkriptLang/Skript#5789]
### Skript/Server Version

```markdown
Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
Skript's documentation can be found here: https://docs.skriptlang.org/
Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
Server Version: git-Paper-"483368e" (MC: 1.19.4)
Skript Version: 2.6.4
Installed Skript Addons: 
- Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/)
- skript-yaml v1.4.1
- skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
- skRayFall v1.9.28 (https://sk.rayfall.net/)
- SkBee v2.8.4 (https://github.com/ShaneBeee/SkBee)
Installed dependencies: 
- Vault v1.7.3-b131
- WorldGuard v7.0.6-SNAPSHOT+2121-32d16a7
```

### Bug Description

While my server is running, this error constantly shows up in console (it's a public server):

- [Tue 10:01:02 ERROR Minecraft] Could not pass event BlockBreakEvent to Skript v2.6.4
java.lang.AssertionError: TRAP
    at net.minecraft.world.item.ItemStack.updateEmptyCacheFlag(ItemStack.java:254)
    at net.minecraft.world.item.ItemStack.setCount(ItemStack.java:1321)
    at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.setAmount(CraftItemStack.java:148)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.getRandom(ItemType.java:561)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.addTo(ItemType.java:870)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.addTo(ItemType.java:828)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$1.change(DefaultChangers.java:105)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$1.change(DefaultChangers.java:50)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$2.change(DefaultChangers.java:131)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$2.change(DefaultChangers.java:120)
    at Skript-2.6.4.jar//ch.njol.skript.classes.Changer$ChangerUtils.change(Changer.java:69)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Variable.change(Variable.java:654)
    at Skript-2.6.4.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
    at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
    at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
    at Skript-2.6.4.jar//ch.njol.s

I am not activly noticing any misfunctions, but I expect that not every block break event works properly

### Expected Behavior

The error should not show up.

### Steps to Reproduce

I made a skript which uses the "on break:" event. When mining blocks that error sometimes shows up, I am not sure what exactly has to be done to cause the error, since there are 50 players online and there is no way to check who is doing what exactly. However it is most likely mining. 

### Errors or Screenshots

- [Tue 10:01:08 ERROR Minecraft] Could not pass event BlockBreakEvent to Skript v2.6.4
java.lang.AssertionError: TRAP
    at net.minecraft.world.item.ItemStack.updateEmptyCacheFlag(ItemStack.java:254)
    at net.minecraft.world.item.ItemStack.setCount(ItemStack.java:1321)
    at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.setAmount(CraftItemStack.java:148)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.getRandom(ItemType.java:561)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.addTo(ItemType.java:870)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.addTo(ItemType.java:828)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$1.change(DefaultChangers.java:105)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$1.change(DefaultChangers.java:50)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$2.change(DefaultChangers.java:131)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$2.change(DefaultChangers.java:120)
    at Skript-2.6.4.jar//ch.njol.skript.classes.Changer$ChangerUtils.change(Changer.java:69)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Variable.change(Variable.java:654)
    at Skript-2.6.4.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
    at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
    at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
    at Skript-2.6.4.jar//ch.njol.s
- [Tue 10:01:08 ERROR Minecraft] Could not pass event BlockBreakEvent to Skript v2.6.4
java.lang.AssertionError: TRAP
    at net.minecraft.world.item.ItemStack.updateEmptyCacheFlag(ItemStack.java:254)
    at net.minecraft.world.item.ItemStack.setCount(ItemStack.java:1321)
    at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.setAmount(CraftItemStack.java:148)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.getRandom(ItemType.java:561)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.addTo(ItemType.java:870)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.addTo(ItemType.java:828)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$1.change(DefaultChangers.java:105)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$1.change(DefaultChangers.java:50)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$2.change(DefaultChangers.java:131)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$2.change(DefaultChangers.java:120)
    at Skript-2.6.4.jar//ch.njol.skript.classes.Changer$ChangerUtils.change(Changer.java:69)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Variable.change(Variable.java:654)
    at Skript-2.6.4.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
    at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
    at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
    at Skript-2.6.4.jar//ch.njol.s
- [Tue 10:01:08 ERROR Minecraft] Could not pass event BlockBreakEvent to Skript v2.6.4
java.lang.AssertionError: TRAP
    at net.minecraft.world.item.ItemStack.updateEmptyCacheFlag(ItemStack.java:254)
    at net.minecraft.world.item.ItemStack.setCount(ItemStack.java:1321)
    at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.setAmount(CraftItemStack.java:148)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.getRandom(ItemType.java:561)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.addTo(ItemType.java:870)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.addTo(ItemType.java:828)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$1.change(DefaultChangers.java:105)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$1.change(DefaultChangers.java:50)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$2.change(DefaultChangers.java:131)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$2.change(DefaultChangers.java:120)
    at Skript-2.6.4.jar//ch.njol.skript.classes.Changer$ChangerUtils.change(Changer.java:69)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Variable.change(Variable.java:654)
    at Skript-2.6.4.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
    at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
    at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
    at Skript-2.6.4.jar//ch.njol.s
- [Tue 10:01:08 ERROR Minecraft] Could not pass event BlockBreakEvent to Skript v2.6.4
java.lang.AssertionError: TRAP
    at net.minecraft.world.item.ItemStack.updateEmptyCacheFlag(ItemStack.java:254)
    at net.minecraft.world.item.ItemStack.setCount(ItemStack.java:1321)
    at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.setAmount(CraftItemStack.java:148)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.getRandom(ItemType.java:561)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.addTo(ItemType.java:870)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.addTo(ItemType.java:828)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$1.change(DefaultChangers.java:105)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$1.change(DefaultChangers.java:50)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$2.change(DefaultChangers.java:131)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$2.change(DefaultChangers.java:120)
    at Skript-2.6.4.jar//ch.njol.skript.classes.Changer$ChangerUtils.change(Changer.java:69)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Variable.change(Variable.java:654)
    at Skript-2.6.4.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
    at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
    at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
    at Skript-2.6.4.jar//ch.njol.s
- [Tue 10:01:08 ERROR Minecraft] Could not pass event BlockBreakEvent to Skript v2.6.4
java.lang.AssertionError: TRAP
    at net.minecraft.world.item.ItemStack.updateEmptyCacheFlag(ItemStack.java:254)
    at net.minecraft.world.item.ItemStack.setCount(ItemStack.java:1321)
    at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.setAmount(CraftItemStack.java:148)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.getRandom(ItemType.java:561)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.addTo(ItemType.java:870)
    at Skript-2.6.4.jar//ch.njol.skript.aliases.ItemType.addTo(ItemType.java:828)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$1.change(DefaultChangers.java:105)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$1.change(DefaultChangers.java:50)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$2.change(DefaultChangers.java:131)
    at Skript-2.6.4.jar//ch.njol.skript.classes.data.DefaultChangers$2.change(DefaultChangers.java:120)
    at Skript-2.6.4.jar//ch.njol.skript.classes.Changer$ChangerUtils.change(Changer.java:69)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Variable.change(Variable.java:654)
    at Skript-2.6.4.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
    at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
    at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
    at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
    at Skript-2.6.4.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Send your code where you have a function that is changing a variable to an ItemType

And the point in the on block break event where you're calling that function.

How are you starting your server? You have the server in test development mode, so assertions errors are showing. Sure assertion errors shouldn't happen, but they're designed for the test development, otherwise they wouldn't error.

**Comment by Xqow** [comment]
function compress(p: player, i: text, boolean: boolean):

**Comment by Xqow** [comment]
This is the function: 

function compress(p: player, i: text, boolean: boolean):

	set {_rec} to {_boolean}

	set {_comp} to true if {supercompress::%{_p}'s uuid%} is true
	set {_comp} to true if {_boolean} is true

	set {_rec} to true if {autocompress::%{_p}'s uuid%} is true

	{_rec} is true

	{item::enchanted::%{_i}%} is set
	set {_item} to yaml value "item.%{_i}%" from "items"

	set {_n} to floor(number of {_item} in {_p}'s inventory / 32)
	remove {_n}*32 of {_item} from {_p}'s inventory
	give {_p} {_n} of {item::enchanted::%{_i}%}

the function is used quite often, here is an example: 

		if event-block is stone or chiseled stone bricks:
			if player's offhand tool is conduit named "&b&lAuto Compressor: &7Stone":
				set {_rec} to true
			fortune(player, "stone", player's held item)
			fortune(player, "stone", player's held item) if event-block is chiseled stone bricks
			compress(player, "stone", {_rec})
			stop
	
	
And I am not really sure what you mean by "How am I starting my server", but I am pretty sure I didn't enable the development mode, at least not on purpose.

**Comment by sovdeeth** [comment]
No replication in 2 years indicates it's either been fixed or is was specific to the user's code
