### ISSUE TITLE
Cannot get key of Legacy Material

### ISSUE THREAD

**Issue by mapletav** [SkriptLang/Skript#5805]
### Skript/Server Version

```markdown
Server version: v1_16_R3 - 1.16.5 - spigot
Skript version: v2.7.0-beta3
```

### Bug Description

Every time I start the server I can't load the plugin，and show that **Cannot get key of Legacy Material**，see below for details.

### Expected Behavior

I think the plugin can be enabled normally

### Steps to Reproduce

I tried multiple versions but none of them worked

### Errors or Screenshots

```v
[01:39:39] [Server thread/INFO] [ch.njol.skript.Skript]: [Skript] Enabling Skript v2.7.0-beta1
[01:39:39] [Server thread/INFO] []: [Skript] Successfully generated the config and the example scripts.
[01:39:40] [ForkJoinPool.commonPool-worker-9/INFO] []: [Skript] A new version of Skript is available: 2.7.0-beta3 (you're currently running 2.7.0-beta1)
[01:39:40] [ForkJoinPool.commonPool-worker-9/INFO] []: Download it at: <aqua><u><link:https://github.com/SkriptLang/Skript/releases/download/2.7.0-beta3/Skript-2.7.0-beta3.jar>https://github.com/SkriptLang/Skript/releases/download/2.7.0-beta3/Skript-2.7.0-beta3.jar
[01:39:44] [Server thread/ERROR] [Minecraft]: Error occurred while enabling Skript v2.7.0-beta1 (Is it up to date?)
java.lang.IllegalArgumentException: Cannot get key of Legacy Material
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[commons-lang-2.6.jar:2.6]
	at org.bukkit.Material.getKey(Material.java:3646) ~[forge:?]
	at ch.njol.skript.aliases.Aliases.loadMissingAliases(Aliases.java:402) ~[?:?]
	at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:432) ~[?:?]
	at ch.njol.skript.aliases.Aliases.load(Aliases.java:387) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:503) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:412) ~[forge:1.16.5-1d8d6313]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:323) ~[forge:1.16.5-1d8d6313]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:439) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:345) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:218) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:737) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

```v
[01:49:02] [Server thread/INFO]: [Skript] Enabling Skript v2.7.0-beta3
[01:49:02] [Server thread/INFO]: [Skript]     Missing lang enum constant for 'attribute types.FORGE_SWIM_SPEED'
[01:49:02] [Server thread/INFO]: [Skript]     Missing lang enum constant for 'attribute types.FORGE_NAMETAG_DISTANCE'
[01:49:02] [Server thread/INFO]: [Skript]     Missing lang enum constant for 'attribute types.FORGE_ENTITY_GRAVITY'
[01:49:02] [Server thread/INFO]: [Skript]     Missing lang enum constant for 'attribute types.FORGE_REACH_DISTANCE'
[01:49:02] [Server thread/INFO]: [Skript]     Missing lang enum constant for 'attribute types.FORGE_SWIM_SPEED'
[01:49:02] [Server thread/INFO]: [Skript]     Missing lang enum constant for 'attribute types.FORGE_NAMETAG_DISTANCE'
[01:49:02] [Server thread/INFO]: [Skript]     Missing lang enum constant for 'attribute types.FORGE_ENTITY_GRAVITY'
[01:49:02] [Server thread/INFO]: [Skript]     Missing lang enum constant for 'attribute types.FORGE_REACH_DISTANCE'
[01:49:02] [Server thread/INFO]: [Skript]     Missing lang enum constant for 'environments.MINECRAFT_OVERWORLD_CAVES'
[01:49:02] [Server thread/INFO]: [Skript]     Missing lang enum constant for 'environments.MINECRAFT_OVERWORLD_CAVES'
[01:49:02] [Server thread/INFO]: [Skript]     Missing lang enum constant for 'environments.MINECRAFT_OVERWORLD_CAVES'
[01:49:02] [Server thread/INFO]: [Skript]     Missing lang enum constant for 'attribute types.FORGE_SWIM_SPEED'
[01:49:02] [Server thread/INFO]: [Skript]     Missing lang enum constant for 'attribute types.FORGE_NAMETAG_DISTANCE'
[01:49:02] [Server thread/INFO]: [Skript]     Missing lang enum constant for 'attribute types.FORGE_ENTITY_GRAVITY'
[01:49:02] [Server thread/INFO]: [Skript]     Missing lang enum constant for 'attribute types.FORGE_REACH_DISTANCE'
[01:49:04] [ForkJoinPool.commonPool-worker-19/INFO]: [Skript] You're currently running the latest stable version of Skript.
[01:49:05] [Server thread/ERROR]: Error occurred while enabling Skript v2.7.0-beta3 (Is it up to date?)
 java.lang.IllegalArgumentException: Cannot get key of Legacy Material
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[commons-lang-2.6.jar:2.6]
        at org.bukkit.Material.getKey(Material.java:3646) ~[forge:?]
        at ch.njol.skript.aliases.Aliases.loadMissingAliases(Aliases.java:402) ~[?:?]
        at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:432) ~[?:?]
        at ch.njol.skript.aliases.Aliases.load(Aliases.java:387) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:508) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:412) ~[forge:1.16.5-1d8d6313]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:323) ~[forge:1.16.5-1d8d6313]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:439) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:345) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:218) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:737) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Other

I came into contact with this plugin for the first time, I don't know if it's my own problem, hope to help me, thank you!

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
Can you provide the exact details of `/version` and show `/skript info`

**Comment by mapletav** [comment]
I did download it from github，due to the plugin loading failure, no matter how I enter the skript-related instruction, it always returns a `/skript help`

`> skript info`
`[Server thread/INFO]: /skript help`
`> version`
`[Server thread/INFO]: This server is running CatServer version 1.16.5-1d8d6313 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)`

![info](https://github.com/SkriptLang/Skript/assets/65485712/0c0beccd-be5d-4dd3-8247-dff59b18bdf2)

**Comment by mapletav** [comment]
I did download it from github，Due to the plugin loading failure, no matter how I enter the skript-related instruction, it always returns a /skript help

`> skript info`
`[Server thread/INFO]: /skript help`
`> version`
`[Server thread/INFO]: This server is running CatServer version 1.16.5-1d8d6313 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)`

![info](https://github.com/SkriptLang/Skript/assets/65485712/0c0beccd-be5d-4dd3-8247-dff59b18bdf2)

**Comment by AyhamAl-Ali** [comment]
**CatServer/Forge** is not supported by Skript. I will keep this issue opened to maybe add support for this unless the other members think otherwise.

**Comment by feitntbma** [comment]
> **CatServer/Forge** is not supported by Skript. I will keep this issue opened to maybe add support for this unless the other members think otherwise.

I also faced this problem, can we somehow raise it and solve it. At the moment I have the latest version of the plugin.

**Comment by sovdeeth** [comment]
> > **CatServer/Forge** is not supported by Skript. I will keep this issue opened to maybe add support for this unless the other members think otherwise.
> 
> I also faced this problem, can we somehow raise it and solve it. At the moment I have the latest version of the plugin.

What's your /sk info?

**Comment by feitntbma** [comment]
> What's your /sk info?

```
> skript info
[Server thread/INFO]: /skript help
```

**Comment by sovdeeth** [comment]
> > What's your /sk info?
> 
> ```
> > skript info
> [Server thread/INFO]: /skript help
> ```

You are not using a supported version of Skript. We only provide support and fixes for 2.8.4.

**Comment by feitntbma** [comment]
> You are not using a supported version of Skript. We only provide support and fixes for 2.8.4.

```
[09:51:51] [Server thread/INFO]: [Skript] Enabling Skript v2.8.4
[09:51:52] [Thread-16/INFO]: [Skript] You're currently running the latest stable version of Skript.
[09:51:58] [Server thread/ERROR]: Error occurred while enabling Skript v2.8.4 (Is it up to date?)
 java.lang.IllegalArgumentException: Cannot get key of Legacy Material
```

**Comment by sovdeeth** [comment]
> > You are not using a supported version of Skript. We only provide support and fixes for 2.8.4.
> 
> ```
> [09:51:51] [Server thread/INFO]: [Skript] Enabling Skript v2.8.4
> [09:51:52] [Thread-16/INFO]: [Skript] You're currently running the latest stable version of Skript.
> [09:51:58] [Server thread/ERROR]: Error occurred while enabling Skript v2.8.4 (Is it up to date?)
>  java.lang.IllegalArgumentException: Cannot get key of Legacy Material
> ```

Ah, my bad, I forgot that also occurs when it fails to enable. What server software are you using?

**Comment by feitntbma** [comment]
> Ah, my bad, I forgot that also occurs when it fails to enable. What server software are you using?

I'm using the same as the author of this issue
CatServer 1.18.2, Forge version 40.2.14

**Comment by sovdeeth** [comment]
Ah. As Ayham already mentioned, we do not support Forge or CatServer currently. If you would like to see this issue fixed, your best chance is to submit a PR for it yourself, as this is very much at the bottom of our priorities.

**Comment by feitntbma** [comment]
> Ah. As Ayham already mentioned, we do not support Forge or CatServer currently. If you would like to see this issue fixed, your best chance is to submit a PR for it yourself, as this is very much at the bottom of our priorities.

Maybe you know an analogue of this plugin? I don't have time to wait

**Comment by Moderocky** [comment]
As far as I know there is no special fork or version of Skript that supports CatServer, however you might be able to find an alternative modded server platform that has proper support for Spigot plugins on Forge, for which some version of Skript _might_ work.

Alternatively, you're welcome to contribute to Skript yourself if you can think of some way to create compatibility, but this isn't something we can really supply ourselves because it's a completely unfamiliar platform outside our supported scope.
