### ISSUE TITLE
it no work it send me here

### ISSUE THREAD

**Issue by kindaDumbB** [SkriptLang/Skript#5850]
### Skript/Server Version

```markdown
spigot 1.19.2
```

### Bug Description

it says in console
Something went horribly wrong with Skript.
[02:19:36] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[02:19:36] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).

### Expected Behavior

reload/load

### Steps to Reproduce

restart server & /skript reload

### Errors or Screenshots

[02:19:36] [Server thread/ERROR]: #!#! 
[02:19:36] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[02:19:36] [Server thread/ERROR]: #!#! Exception occurred in Skript's main command
[02:19:36] [Server thread/ERROR]: #!#! Used command: /skript reload testingz.sk
[02:19:36] [Server thread/ERROR]: #!#! 
[02:19:36] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[02:19:36] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[02:19:36] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[02:19:36] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[02:19:36] [Server thread/ERROR]: #!#! 
[02:19:36] [Server thread/ERROR]: #!#! Stack trace:
[02:19:36] [Server thread/ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "ch.njol.skript.structures.StructVariables$DefaultVariables.getVariables()" because "data" is null
[02:19:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.structures.StructVariables.postUnload(StructVariables.java:251)
[02:19:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScripts(ScriptLoader.java:823)
[02:19:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:842)
[02:19:36] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:189)
[02:19:36] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:19:36] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[02:19:36] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:833)
[02:19:36] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[02:19:36] [Server thread/ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:298)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:282)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1940)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1905)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:68)
[02:19:36] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.server.TickTask.run(SourceFile:18)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017)
[02:19:36] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293)
[02:19:36] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[02:19:36] [Server thread/ERROR]: #!#! 
[02:19:36] [Server thread/ERROR]: #!#! Version Information:
[02:19:36] [Server thread/ERROR]: #!#!   Skript: 2.7.0-beta3
[02:19:36] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[02:19:36] [Server thread/ERROR]: #!#!     Date: 03:18:03.366646700
[02:19:36] [Server thread/ERROR]: #!#!   Bukkit: 1.19.2-R0.1-SNAPSHOT
[02:19:36] [Server thread/ERROR]: #!#!   Minecraft: 1.19.2
[02:19:36] [Server thread/ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[02:19:36] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.19.0-43-generic
[02:19:36] [Server thread/ERROR]: #!#! 
[02:19:36] [Server thread/ERROR]: #!#! Server platform: Spigot
[02:19:36] [Server thread/ERROR]: #!#! 
[02:19:36] [Server thread/ERROR]: #!#! Current node: null
[02:19:36] [Server thread/ERROR]: #!#! Current item: null
[02:19:36] [Server thread/ERROR]: #!#! 
[02:19:36] [Server thread/ERROR]: #!#! Thread: Server thread
[02:19:36] [Server thread/ERROR]: #!#! 
[02:19:36] [Server thread/ERROR]: #!#! Language: english
[02:19:36] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[02:19:36] [Server thread/ERROR]: #!#! 
[02:19:36] [Server thread/ERROR]: #!#! End of Error.
[02:19:36] [Server thread/ERROR]: #!#! 

### Other

old plugins SKquery

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by kindaDumbB** [comment]
IF im dumb TELLL ME WHAT TO DO DIFFERENT

**Comment by kindaDumbB** [comment]
PLEASE TELL ME IM SO BOARD

**Comment by kindaDumbB** [comment]
ummmm it work now?

**Comment by kindaDumbB** [comment]
SKquery made it work but it died again

**Comment by kindaDumbB** [comment]
i think i just over loaded it
sorry for report

**Comment by kindaDumbB** [comment]
it works right now if you over load it it breaks skQuery and you have to delete skQuery and get a undamaged one and install that

**Comment by TheLimeGlass** [comment]
There was a similar issue that was fixed in 2.7.0-beta2 but you're on 2.7.0-beta3 so that needs to be looking into.

**Comment by TheLimeGlass** [comment]
Can you send your code where you use `variables:` section?
