### ISSUE TITLE
Potion Effects

### ISSUE THREAD

**Issue by Kakar4ik** [SkriptLang/Skript#5857]
### Skript/Server Version

```markdown
[6Skript7]r Skript's aliases can be found here: 3https://github.com/SkriptLang/skript-aliases
[6Skript7]r Skript's documentation can be found here: 3https://docs.skriptlang.org/
[6Skript7]r Skript's tutorials can be found here: 3https://docs.skriptlang.org/tutorials
[6Skript7]r Server Version: 3git-Paper-550 (MC: 1.19.4)
[6Skript7]r Skript Version: 32.6.4
[6Skript7]r Installed Skript Addons: 3None
[6Skript7]r Installed dependencies: 
[6Skript7]r  - Vault v1.7.3-b131
[6Skript7]r  - WorldGuard v7.0.7+216b061
```

### Bug Description

When you try to get potion effects from a player it returns an error (potion effects of player):

### Expected Behavior

Expected to return a list of potion effects

### Steps to Reproduce

broadcast potion effects of player

### Errors or Screenshots

#!#! Stack trace:
#!#! java.lang.IllegalArgumentException: millis must be >= 0
#!#!     at Skript.jar//ch.njol.skript.util.Timespan.<init>(Timespan.java:145)
#!#!     at Skript.jar//ch.njol.skript.util.Timespan.fromTicks_i(Timespan.java:159)
#!#!     at Skript.jar//ch.njol.skript.util.PotionEffectUtils.toString(PotionEffectUtils.java:124)
#!#!     at Skript.jar//ch.njol.skript.classes.data.BukkitClasses$25.toString(BukkitClasses.java:1085)
#!#!     at Skript.jar//ch.njol.skript.classes.data.BukkitClasses$25.toString(BukkitClasses.java:1076)
#!#!     at Skript.jar//ch.njol.skript.registrations.Classes.toString(Classes.java:619)
#!#!     at Skript.jar//ch.njol.skript.registrations.Classes.toString(Classes.java:587)
#!#!     at Skript.jar//ch.njol.skript.effects.EffMessage.toString(EffMessage.java:165)
#!#!     at Skript.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:137)
#!#!     at Skript.jar//ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:83)
#!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
#!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
#!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
#!#!     at Skript.jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:290)
#!#!     at Skript.jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:220)
#!#!     at Skript.jar//ch.njol.skript.command.Commands$3$1.call(Commands.java:217)
#!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftFuture.run(CraftFuture.java:88)
#!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
#!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
#!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
#!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
#!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
#!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
#!#!     at java.base/java.lang.Thread.run(Thread.java:833)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Moderocky** [comment]
This might be caused by the new infinite duration using `-1` as its value.
