### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by jhqwqmc** [SkriptLang/Skript#5916]
### Skript/Server Version

```markdown
2.7.0-beta2 (skriptlang-github)
git-Paper-550 (MC: 1.19.4)
```

### Bug Description

[23:24:12 ERROR]: #!#!
[23:24:12 ERROR]: #!#! [Skript] Severe Error:
[23:24:12 ERROR]: #!#!
[23:24:12 ERROR]: #!#! Something went horribly wrong with Skript.
[23:24:12 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[23:24:12 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[23:24:12 ERROR]: #!#! Here is full list of them:
[23:24:12 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) Skript-Packet v2.1.2 (www.github.com/Anarchick/skript-packet)
[23:24:12 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[23:24:12 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[23:24:12 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[23:24:12 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[23:24:12 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[23:24:12 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[23:24:12 ERROR]: #!#!
[23:24:12 ERROR]: #!#! Stack trace:
[23:24:12 ERROR]: #!#! java.lang.NoSuchMethodError: 'ch.njol.skript.config.Config ch.njol.skript.lang.parser.ParserInstance.getCurrentScript()'
[23:24:12 ERROR]: #!#!     at [S][前置插件]skript-reflect.jar//com.btk5h.skriptmirror.util.SkriptUtil.getCurrentScript(SkriptUtil.java:108)
[23:24:12 ERROR]: #!#!     at [S][前置插件]skript-reflect.jar//com.btk5h.skriptmirror.skript.Types$3.parse(Types.java:60)
[23:24:12 ERROR]: #!#!     at [S][前置插件]skript-reflect.jar//com.btk5h.skriptmirror.skript.Types$3.parse(Types.java:57)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.registrations.Classes.parseSimple(Classes.java:468)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.registrations.Classes.parse(Classes.java:497)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:593)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:760)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:154)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1273)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:229)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:204)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:185)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:632)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$3(ScriptLoader.java:501)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:422)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:438)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:500)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)
[23:24:12 ERROR]: #!#!     at Skript-2.7.0-beta2.jar//ch.njol.skript.Skript$1.run(Skript.java:813)
[23:24:12 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[23:24:12 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:24:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1115)
[23:24:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[23:24:12 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[23:24:12 ERROR]: #!#!
[23:24:12 ERROR]: #!#! Version Information:
[23:24:12 ERROR]: #!#!   Skript: 2.7.0-beta2
[23:24:12 ERROR]: #!#!     Flavor: skriptlang-github
[23:24:12 ERROR]: #!#!     Date: 23:34:46.821464600
[23:24:12 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[23:24:12 ERROR]: #!#!   Minecraft: 1.19.4
[23:24:12 ERROR]: #!#!   Java: 17.0.5 (Java HotSpot(TM) 64-Bit Server VM 17.0.5+9-LTS-191)
[23:24:12 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[23:24:12 ERROR]: #!#!
[23:24:12 ERROR]: #!#! Server platform: Paper
[23:24:12 ERROR]: #!#!
[23:24:12 ERROR]: #!#! Current node: null
[23:24:12 ERROR]: #!#! Current item: null
[23:24:12 ERROR]: #!#!
[23:24:12 ERROR]: #!#! Thread: Server thread
[23:24:12 ERROR]: #!#!
[23:24:12 ERROR]: #!#! Language: simplifiedchinese
[23:24:12 ERROR]: #!#! Link parse mode: DISABLED
[23:24:12 ERROR]: #!#!
[23:24:12 ERROR]: #!#! End of Error.
[23:24:12 ERROR]: #!#!

### Expected Behavior

Normally, when the player displays the title, the player will be sent a message of xxx

### Steps to Reproduce

on packet event PLAY_SERVER_SET_TITLE_TEXT:
    send "xxx" to player

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Addon issue. Update [skript-reflect](https://github.com/TPGamesNL/skript-reflect/releases).

**Comment by jhqwqmc** [comment]
The update doesn't seem to work

**Comment by jhqwqmc** [comment]
> 插件问题。更新 [skript-reflect](https://github.com/TPGamesNL/skript-reflect/releases)。

The update doesn't seem to work

**Comment by AyhamAl-Ali** [comment]
Try to ask for further help in [skUnity discord server help channels](https://discord.gg/skript) as this is not a Skript issue.
