### ISSUE TITLE
My Personal Skript is doesn't work

### ISSUE THREAD

**Issue by ROOOODE** [SkriptLang/Skript#5938]
### Skript/Server Version

```markdown
[00:41:54 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[00:41:54 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[00:41:54 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[00:41:54 INFO]: [Skript] Server Version: 1.19.2-45 (MC: 1.19.2)
[00:41:54 INFO]: [Skript] Skript Version: 2.6.4
[00:41:54 INFO]: [Skript] Installed Skript Addons: None
[00:41:54 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

An error occurs when activating the script, and activation is not possible.

### Expected Behavior

enable script

### Steps to Reproduce

just type /skript enable <scriptname>

### Errors or Screenshots
```v
2023-08-26 00:37:45,437 ERROR [Server thread] Minecraft.publish(32): #!#! 
2023-08-26 00:37:45,438 ERROR [Server thread] Minecraft.publish(32): #!#! [Skript] Severe Error:
2023-08-26 00:37:45,439 ERROR [Server thread] Minecraft.publish(32): #!#! Could not load kimdonguk.sk
2023-08-26 00:37:45,439 ERROR [Server thread] Minecraft.publish(32): #!#! 
2023-08-26 00:37:45,440 ERROR [Server thread] Minecraft.publish(32): #!#! Something went horribly wrong with Skript.
2023-08-26 00:37:45,441 ERROR [Server thread] Minecraft.publish(32): #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
2023-08-26 00:37:45,441 ERROR [Server thread] Minecraft.publish(32): #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
2023-08-26 00:37:45,442 ERROR [Server thread] Minecraft.publish(32): #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
2023-08-26 00:37:45,442 ERROR [Server thread] Minecraft.publish(32): #!#! 
2023-08-26 00:37:45,443 ERROR [Server thread] Minecraft.publish(32): #!#! Stack trace:
2023-08-26 00:37:45,444 ERROR [Server thread] Minecraft.publish(32): #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
2023-08-26 00:37:45,444 ERROR [Server thread] Minecraft.publish(32): #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:242)
2023-08-26 00:37:45,445 ERROR [Server thread] Minecraft.publish(32): #!#!     at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:337)
2023-08-26 00:37:45,445 ERROR [Server thread] Minecraft.publish(32): #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:373)
2023-08-26 00:37:45,446 ERROR [Server thread] Minecraft.publish(32): #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)
2023-08-26 00:37:45,446 ERROR [Server thread] Minecraft.publish(32): #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
2023-08-26 00:37:45,449 ERROR [Server thread] Minecraft.publish(32): #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
2023-08-26 00:37:45,449 ERROR [Server thread] Minecraft.publish(32): #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
2023-08-26 00:37:45,450 ERROR [Server thread] Minecraft.publish(32): #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
2023-08-26 00:37:45,450 ERROR [Server thread] Minecraft.publish(32): #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:224)
2023-08-26 00:37:45,451 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/forge@43.2.21/org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
2023-08-26 00:37:45,452 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/forge@43.2.21/org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:160)
2023-08-26 00:37:45,452 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/forge@43.2.21/org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:797)
2023-08-26 00:37:45,453 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/forge@43.2.21/org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
2023-08-26 00:37:45,454 ERROR [Server thread] Minecraft.publish(32): #!#!     at MC-BOOTSTRAP/brigadier@1.20.1/com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
2023-08-26 00:37:45,454 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.commands.Commands.performCommand(Commands.java:299)
2023-08-26 00:37:45,455 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.commands.Commands.m_242674_(Commands.java:279)
2023-08-26 00:37:45,456 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_242600_(ServerGamePacketListenerImpl.java:1335)
2023-08-26 00:37:45,456 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$12(ServerGamePacketListenerImpl.java:1313)
2023-08-26 00:37:45,457 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:68)
2023-08-26 00:37:45,457 ERROR [Server thread] Minecraft.publish(32): #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
2023-08-26 00:37:45,458 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.TickTask.run(TickTask.java:18)
2023-08-26 00:37:45,459 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
2023-08-26 00:37:45,459 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
2023-08-26 00:37:45,460 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:901)
2023-08-26 00:37:45,460 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:171)
2023-08-26 00:37:45,461 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
2023-08-26 00:37:45,462 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:884)
2023-08-26 00:37:45,462 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:878)
2023-08-26 00:37:45,463 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140)
2023-08-26 00:37:45,465 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:864)
2023-08-26 00:37:45,466 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:795)
2023-08-26 00:37:45,467 ERROR [Server thread] Minecraft.publish(32): #!#!     at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:278)
2023-08-26 00:37:45,467 ERROR [Server thread] Minecraft.publish(32): #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-26 00:37:45,468 ERROR [Server thread] Minecraft.publish(32): #!#! 
2023-08-26 00:37:45,468 ERROR [Server thread] Minecraft.publish(32): #!#! Version Information:
2023-08-26 00:37:45,469 ERROR [Server thread] Minecraft.publish(32): #!#!   Skript: 2.6.4 (latest)
2023-08-26 00:37:45,470 ERROR [Server thread] Minecraft.publish(32): #!#!     Flavor: skriptlang-github
2023-08-26 00:37:45,470 ERROR [Server thread] Minecraft.publish(32): #!#!     Date: 17:14:25.041218900
2023-08-26 00:37:45,471 ERROR [Server thread] Minecraft.publish(32): #!#!   Bukkit: 1.19.2-R0.1-SNAPSHOT
2023-08-26 00:37:45,471 ERROR [Server thread] Minecraft.publish(32): #!#!   Minecraft: 1.19.2
2023-08-26 00:37:45,472 ERROR [Server thread] Minecraft.publish(32): #!#!   Java: 17.0.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39)
2023-08-26 00:37:45,472 ERROR [Server thread] Minecraft.publish(32): #!#!   OS: Windows 10 amd64 10.0
2023-08-26 00:37:45,473 ERROR [Server thread] Minecraft.publish(32): #!#! 
2023-08-26 00:37:45,473 ERROR [Server thread] Minecraft.publish(32): #!#! Server platform: Spigot
2023-08-26 00:37:45,474 ERROR [Server thread] Minecraft.publish(32): #!#! 
2023-08-26 00:37:45,475 ERROR [Server thread] Minecraft.publish(32): #!#! Current node: command /동욱 [<text>] [<integer>] [<player>]: (kimdonguk.sk, line 2)
2023-08-26 00:37:45,476 ERROR [Server thread] Minecraft.publish(32): #!#! Current item: null
2023-08-26 00:37:45,476 ERROR [Server thread] Minecraft.publish(32): #!#! 
2023-08-26 00:37:45,477 ERROR [Server thread] Minecraft.publish(32): #!#! Thread: Server thread
2023-08-26 00:37:45,478 ERROR [Server thread] Minecraft.publish(32): #!#! 
2023-08-26 00:37:45,478 ERROR [Server thread] Minecraft.publish(32): #!#! Language: english
2023-08-26 00:37:45,479 ERROR [Server thread] Minecraft.publish(32): #!#! Link parse mode: DISABLED
2023-08-26 00:37:45,481 ERROR [Server thread] Minecraft.publish(32): #!#! 
2023-08-26 00:37:45,482 ERROR [Server thread] Minecraft.publish(32): #!#! End of Error.
2023-08-26 00:37:45,482 ERROR [Server thread] Minecraft.publish(32): #!#! 
```
### Other

<full script>
```v
#돈
command /동욱 [<text>] [<integer>] [<player>]:
	trigger:
		if arg-1 is not set:
			stop
			send "&bMy 동욱 : &f&l%{%player%::동욱}%"
			send "&7/동욱 <보내기,수표>"
		if arg-1 is "보내기":
			if arg-3 is not set:
				send "&7/동욱 보내기 <금액> <유저>"
				stop
			if arg-2 > {%player%::동욱}:
				message "&b[ 동욱 ] &f%player% &c님이 가진 소지금보다 더 많은 돈은 보낼 수 없습니다."
				stop
		if arg-1 is "수표":
			if arg-2 is not set:
				message "&7/동욱 수표 <금액>"
			else:
				if arg-2 < 100:
					message "&b[ 동욱 ] &c100동욱 이상 부터 가능합니다."
					stop
				if arg-2 is bigger than {%player%::동욱}:
					message "&b[ 동욱 ] &f%player% &c님이 가진 소지금보다 더 많은 수표로 바꿀 수 없습니다."
				else:
					message "&b[ 동욱 ] &a성공적으로 %arg-2% &a수표를 발급했습니다."
					give paper named "&b%arg-2% &e수표" with lore "&b[ 동욱 ] &a우클릭하면 소지금에 넣는다." to player
					subtract arg-2 from {%player%::동욱}


#수표
on rightclick with paper:
	if name of player's tool contains "수표":
		set {_name} to uncolored name of player's tool
		replace all "수표" and " " with "" in {_name}
		set {_name} to {_name} parsed as integer
		add {_name} to {%player%::동욱}
		message "&b[ 동욱 ] &a소지금에 %{_name}% &a&l수표를 지급받았습니다."
		remove 1 paper from player's tool


#도박
command /ehqkr:
	trigger:
		if name of player's tool contains "수표":
			set {_money} to uncolored name of player's tool
			replace all "수표" and " " with "" in {_money}
			set {_money} to {_money} parsed as integer
			if {_money} < 1000:
				message "&6[ 잭오랜턴 ] : &f최소 도박금은 1000원이다. '이 거지야.'"
				stop
			message "&b[ 동욱 ] &f%{_money}% &a수표를 집어넣었습니다."
			remove 1 paper from player's tool
		else:
			message "&b[ 동욱 ] &f수표를 들고 서주세요!"
			stop
		set {_num} to random integer from 1 to 20
		if {_num} is between 1 and 9:
			send title "&7[  &8&l♠  &7]" with subtitle "&7[ 0 배 ]" to player for 6 second with fade in 0 tick and fade out 10 tick
			play sound "entity.villager.ambient" with volume 2 and pitch 0.7 to player
			add {_money} to {도박금}
		if {_num} is between 10 and 16:
			send title "&7[  &c&l♡  &7]" with subtitle "&7[ 1 배 ]" to player for 6 second with fade in 0 tick and fade out 10 tick
			play sound "entity.villager.yes" with volume 2 and pitch 1 to player
			give paper named "&b%{_money}% &e수표" with lore "&b[ 동욱 ] &a우클릭하면 소지금에 넣는다." to player
		if {_num} is between 17 and 19:
			send title "&7[  &c&l◇  &7]" with subtitle "&7[ 2 배 ] [ %{_money}*2% ] - %player%" to all players for 6 second with fade in 0 tick and fade out 10 tick
			play sound "entity.villager.yes" with volume 2 and pitch 1.2 to all players
			give paper named "&b%{_money}*2% &e수표" with lore "&b[ 동욱 ] &a우클릭하면 소지금에 넣는다." to player
			subtract {_money} from {도박금}
		if {_num} is 20:
			send title "&7[  &8&l♣  &7]" with subtitle "&7[ 4 배 ] [ %{_money}*4% ] - %player%" to all players for 6 second with fade in 0 tick and fade out 10 tick
			play sound "entity.villager.yes" with volume 2 and pitch 1.4 to all players
			play sound "ui.toast.challenge_complete" with volume 0.3 with pitch 1.7 to all players
			give paper named "&b%{_money}*4% &e수표" with lore "&b[ 동욱 ] &a우클릭하면 소지금에 넣는다." to player
			subtract {_money}*3 from {도박금}

command /이름 [<text>]:
	trigger:
		set {%player%::이름} to arg-1

on chat:
	cancel event
	if {%player%::이름} is not set:
		set {_u} to "Gay"
	set {_u} to {%player%::이름}
	send "&f< %{_u}% &f> : %message%" to all players

#탭
every 1 second:
	loop all players:
		set tab header to "&f■ &7■ &f■ &7■ &c〔 &f&l동욱 프로젝트 2023 &c〕 &7■ &f■ &7■ &f■" and footer to "&b동욱 - &f&l%{%loop-player%::동욱}%" for loop-player
```
### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
CraftBukkit/Forge is not supported. Use Paper/Spigot.
