### ISSUE TITLE
ClassCastException when setting metadata of viewers (ExprInventoryInfo)

### ISSUE THREAD

**Issue by cheeezburga** [SkriptLang/Skript#5940]
### Skript/Server Version

```markdown
[13:50:58 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[13:50:58 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[13:50:58 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[13:50:58 INFO]: [Skript] Server Version: git-Paper-84 (MC: 1.20.1)
[13:50:58 INFO]: [Skript] Skript Version: 2.6.4
[13:50:58 INFO]: [Skript] Installed Skript Addons:
[13:50:58 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[13:50:58 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[13:50:58 INFO]: [Skript]  - SkBee v2.16.1 (https://github.com/ShaneBeee/SkBee)
[13:50:58 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

```
function doGameLoop(inv: gui inventory):
	set (metadata tag "wamStart" of (viewers of {_inv})) to unix timestamp of now
```
In the above code, `{_inv}` is a gui inventory created as per the following line (using skript-gui):
`create gui with id "%{_p}%" with virtual chest inventory named "Whack-A-Mole!" with 6 rows:`

It sends the error provided in the **Errors or Screenshots** section of this bug report in console. If it's relevant, when I got the error the only viewer of the inventory was me. Asked about this in the skUnity discord and @Fusezion said that it was persistent on 2.8.0-dev.

### Expected Behavior

It was supposed to change the value of the metadata tag `"wamStart"` of all viewers of the specified inventory.

### Steps to Reproduce

1. To recreate the error with skript-gui, copy paste the following code and use command **/test**
```
command /test:
	trigger:
		create gui with virtual chest inventory named "anything"
		open last gui to player
		set (metadata tag "start" of (viewers of last gui)) to unix timestamp of now
```
2. To recreate the error using just vanilla Skript, copy paste the following code and do the same
```
command /test:
	trigger:
		set {_chest} to chest inventory named "anything"
		open {_chest} to player
		set (metadata tag "start" of (viewers of {_chest})) to unix timestamp of now
```

### Errors or Screenshots

```
[13:46:02 ERROR]: #!#!
[13:46:02 ERROR]: #!#! [Skript] Severe Error:
[13:46:02 ERROR]: #!#!
[13:46:02 ERROR]: #!#! Something went horribly wrong with Skript.
[13:46:02 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:46:02 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[13:46:02 ERROR]: #!#! Here is full list of them:
[13:46:02 ERROR]: #!#! skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) SkBee v2.16.1 (https://github.com/ShaneBeee/SkBee)
[13:46:02 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[13:46:02 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[13:46:02 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[13:46:02 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[13:46:02 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[13:46:02 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[13:46:02 ERROR]: #!#!
[13:46:02 ERROR]: #!#! Stack trace:
[13:46:02 ERROR]: #!#! java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Lorg.bukkit.metadata.Metadatable; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [Lorg.bukkit.metadata.Metadatable; is in unnamed module of loader java.net.URLClassLoader @4e515669)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.expressions.ExprMetadata.change(ExprMetadata.java:121)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:286)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:251)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:256)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.command.Commands.handleCommand(Commands.java:261)
[13:46:02 ERROR]: #!#!     at Skript-2.6.4 (1).jar//ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:178)
[13:46:02 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[13:46:02 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[13:46:02 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:46:02 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[13:46:02 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[13:46:02 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[13:46:02 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2275)
[13:46:02 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2259)
[13:46:02 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[13:46:02 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[13:46:02 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:46:02 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:46:02 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:46:02 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
[13:46:02 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[13:46:02 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[13:46:02 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)
[13:46:02 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)
[13:46:02 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[13:46:02 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1287)
[13:46:02 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1175)
[13:46:02 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[13:46:02 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[13:46:02 ERROR]: #!#!
[13:46:02 ERROR]: #!#! Version Information:
[13:46:02 ERROR]: #!#!   Skript: 2.6.4 (latest)
[13:46:02 ERROR]: #!#!     Flavor: skriptlang-github
[13:46:02 ERROR]: #!#!     Date: 17:14:25.041218900
[13:46:02 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[13:46:02 ERROR]: #!#!   Minecraft: 1.20.1
[13:46:02 ERROR]: #!#!   Java: 17.0.8 (Java HotSpot(TM) 64-Bit Server VM 17.0.8+9-LTS-211)
[13:46:02 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[13:46:02 ERROR]: #!#!
[13:46:02 ERROR]: #!#! Server platform: Paper
[13:46:02 ERROR]: #!#!
[13:46:02 ERROR]: #!#! Current node: null
[13:46:02 ERROR]: #!#! Current item: set metadata values "wamStart" of viewers of {_inv} (as org.bukkit.inventory.Inventory) to the unix timestamp of now
[13:46:02 ERROR]: #!#! Current trigger: function doGameLoop (simple event) (whackamole.sk, line 55)
[13:46:02 ERROR]: #!#!
[13:46:02 ERROR]: #!#! Thread: Server thread
[13:46:02 ERROR]: #!#!
[13:46:02 ERROR]: #!#! Language: english
[13:46:02 ERROR]: #!#! Link parse mode: DISABLED
[13:46:02 ERROR]: #!#!
[13:46:02 ERROR]: #!#! End of Error.
[13:46:02 ERROR]: #!#!
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Marking as low, as `set {_players::*} to (viewers of {_chest})` is a valid workaround

**Comment by sovdeeth** [comment]
I can't change the issue title, can you change it to `ClassCastException when setting metadata of viewers (ExprInventoryInfo)`
