### ISSUE TITLE
plugin skript 1.7.10 loading error

### ISSUE THREAD

**Issue by Yobi855** [SkriptLang/Skript#5951]
### Skript/Server Version

```markdown
server version=1.7.10 spigot
skript version=2.1.2
```

### Bug Description

when I start the server this error happens, only with skript installed without any extension

### Expected Behavior

,

### Steps to Reproduce

anything

### Errors or Screenshots

[16:53:02 ERROR]: #!#!
[16:53:02 ERROR]: #!#! [Skript] Severe Error:
[16:53:02 ERROR]: #!#! Unexpected error while checking for a new version of Skript
[16:53:02 ERROR]: #!#!
[16:53:02 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[16:53:02 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[16:53:02 ERROR]: #!#! and check whether this error has already been reported.
[16:53:02 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[16:53:02 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[16:53:02 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[16:53:02 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[16:53:02 ERROR]: #!#!
[16:53:02 ERROR]: #!#! Stack trace:
[16:53:02 ERROR]: #!#! javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.
[16:53:02 ERROR]: #!#!     at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
[16:53:02 ERROR]: #!#!     at java.xml/com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
[16:53:02 ERROR]: #!#!     at ch.njol.skript.Updater.getChangelogs(Updater.java:286)
[16:53:02 ERROR]: #!#!     at ch.njol.skript.Updater$2.run(Updater.java:210)
[16:53:02 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[16:53:02 ERROR]: #!#!
[16:53:02 ERROR]: #!#! Version Information:
[16:53:02 ERROR]: #!#!   Skript: 2.1.2
[16:53:02 ERROR]: #!#!   Bukkit: 1.7.10-R0.1-SNAPSHOT
[16:53:02 ERROR]: #!#!   Minecraft: 1.7.10
[16:53:02 ERROR]: #!#!   Java: 17.0.8
[16:53:02 ERROR]: #!#!
[16:53:02 ERROR]: #!#! Running CraftBukkit: false
[16:53:02 ERROR]: #!#!
[16:53:02 ERROR]: #!#! Current node: databases: (config.sk, line 141)
[16:53:02 ERROR]: #!#! Current item: null
[16:53:02 ERROR]: #!#!
[16:53:02 ERROR]: #!#! Thread: Skript update thread
[16:53:02 ERROR]: #!#!
[16:53:02 ERROR]: #!#! End of Error.
[16:53:02 ERROR]: #!#!
[16:53:02 INFO]: [Skript] You're currently running the latest stable version of Skript.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
2.1.2 is 8+ years old and is not supported by SkriptLang. SkriptLang is only MC 1.13+.
