### ISSUE TITLE
Placeholders error

### ISSUE THREAD

**Issue by TheThe123** [SkriptLang/Skript#5967]
### Skript/Server Version

```markdown
[18:54:49 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[18:54:49 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[18:54:49 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[18:54:49 INFO]: [Skript] Server Version: git-Paper-387 (MC: 1.18.2)
[18:54:49 INFO]: [Skript] Skript Version: 2.7.0-beta3 (skriptlang-github)
[18:54:49 INFO]: [Skript] Installed Skript Addons:
[18:54:49 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[18:54:49 INFO]: [Skript]  - Skellett v2.0.8 (https://forums.skunity.com/resources/skellett.24/)
[18:54:49 INFO]: [Skript]  - SkQuery v4.1.9
[18:54:49 INFO]: [Skript] Installed dependencies:
[18:54:49 INFO]: [Skript]  - Vault v1.7.3-b131
[18:54:49 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
[18:54:50 INFO]: elviso issued server command: /mc
```

### Bug Description

Error in console, i don't know what it does

### Expected Behavior

idk something with placeholders

### Steps to Reproduce

run server

### Errors or Screenshots

[18:07:51 ERROR]: #!#!
[18:07:51 ERROR]: #!#! [Skript] Severe Error:
[18:07:51 ERROR]: #!#!
[18:07:51 ERROR]: #!#! Something went horribly wrong with Skript.
[18:07:51 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[18:07:51 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[18:07:51 ERROR]: #!#! Following plugins are probably related to this error in some way:
[18:07:51 ERROR]: #!#! skript-placeholders (https://github.com/APickledWalrus/skript-placeholders)
[18:07:51 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[18:07:51 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[18:07:51 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[18:07:51 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[18:07:51 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[18:07:51 ERROR]: #!#!
[18:07:51 ERROR]: #!#! Stack trace:
[18:07:51 ERROR]: #!#! java.util.NoSuchElementException
[18:07:51 ERROR]: #!#!     at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:362)
[18:07:51 ERROR]: #!#!     at java.base/java.util.ArrayDeque.pop(ArrayDeque.java:593)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.structures.StructVariables$DefaultVariables.exitScope(StructVariables.java:112)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Variable.getRaw(Variable.java:333)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Variable.get(Variable.java:341)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Variable.getConverted(Variable.java:488)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Variable.getAll(Variable.java:710)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Variable.getArray(Variable.java:702)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.VariableString.toString(VariableString.java:540)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.VariableString.getArray(VariableString.java:663)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.VariableString.getArray(VariableString.java:61)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:272)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:50)
[18:07:51 ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:63)
[18:07:51 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[18:07:51 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:07:51 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669)
[18:07:51 ERROR]: #!#!     at skript-placeholders-1.5.2.jar//io.github.apickledwalrus.skriptplaceholders.placeholder.placeholderapi.PlaceholderAPIListener.onRequest(PlaceholderAPIListener.java:47)
[18:07:51 ERROR]: #!#!     at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[18:07:51 ERROR]: #!#!     at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[18:07:51 ERROR]: #!#!     at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[18:07:51 ERROR]: #!#!     at TAB v4.0.3.jar//me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.lambda$registerUnknownPlaceholder$2(BukkitPlatform.java:131)
[18:07:51 ERROR]: #!#!     at TAB v4.0.3.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.request(PlayerPlaceholderImpl.java:138)
[18:07:51 ERROR]: #!#!     at TAB v4.0.3.jar//me.neznamy.tab.shared.placeholders.PlayerPlaceholderImpl.update(PlayerPlaceholderImpl.java:57)
[18:07:51 ERROR]: #!#!     at TAB v4.0.3.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.updatePlayerPlaceholder(PlaceholderManagerImpl.java:118)
[18:07:51 ERROR]: #!#!     at TAB v4.0.3.jar//me.neznamy.tab.shared.features.PlaceholderManagerImpl.refresh(PlaceholderManagerImpl.java:69)
[18:07:51 ERROR]: #!#!     at TAB v4.0.3.jar//me.neznamy.tab.shared.CpuManager.lambda$runMeasuredTask$11(CpuManager.java:226)
[18:07:51 ERROR]: #!#!     at TAB v4.0.3.jar//me.neznamy.tab.shared.CpuManager.run(CpuManager.java:252)
[18:07:51 ERROR]: #!#!     at TAB v4.0.3.jar//me.neznamy.tab.shared.CpuManager.lambda$submit$1(CpuManager.java:105)
[18:07:51 ERROR]: #!#!     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[18:07:51 ERROR]: #!#!     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[18:07:51 ERROR]: #!#!     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[18:07:51 ERROR]: #!#!     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:07:51 ERROR]: #!#!     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:07:51 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[18:07:51 ERROR]: #!#!
[18:07:51 ERROR]: #!#! Version Information:
[18:07:51 ERROR]: #!#!   Skript: 2.7.0-beta3 (latest)
[18:07:51 ERROR]: #!#!     Flavor: skriptlang-github
[18:07:51 ERROR]: #!#!     Date: 03:18:03.366646700
[18:07:51 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[18:07:51 ERROR]: #!#!   Minecraft: 1.18.2
[18:07:51 ERROR]: #!#!   Java: 17.0.2 (OpenJDK 64-Bit Server VM 17.0.2+8-86)
[18:07:51 ERROR]: #!#!   OS: Linux amd64 3.10.0-1160.49.1.el7.x86_64
[18:07:51 ERROR]: #!#!
[18:07:51 ERROR]: #!#! Server platform: Paper
[18:07:51 ERROR]: #!#!
[18:07:51 ERROR]: #!#! Current node: null
[18:07:51 ERROR]: #!#! Current item: set the placeholder result to "%{ranga.%the player%} (as java.lang.Object)%"
[18:07:51 ERROR]: #!#! Current trigger: papi request with prefix "ranga" (placeholderapi placeholder request for the prefixes ranga) (postac.sk, line 20)
[18:07:51 ERROR]: #!#!
[18:07:51 ERROR]: #!#! Thread: TAB Processing Thread
[18:07:51 ERROR]: #!#!
[18:07:51 ERROR]: #!#! Language: english
[18:07:51 ERROR]: #!#! Link parse mode: DISABLED
[18:07:51 ERROR]: #!#!
[18:07:51 ERROR]: #!#! End of Error.
[18:07:51 ERROR]: #!#!

### Other

it sometimes spams in my console

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheThe123** [comment]
Also, when I reload the skript file with the variables causing this error, I got these in chat:

[08:31:35 WARN]: [PlaceholderAPI] Failed to load expansion poosta.lvl. Identifier is already in use.
[08:31:35 WARN]: [PlaceholderAPI] Failed to load expansion poost.exp. Identifier is already in use.
[08:31:35 WARN]: [PlaceholderAPI] Failed to load expansion poost.req. Identifier is already in use.
[08:31:35 WARN]: [PlaceholderAPI] Failed to load expansion poost.req.nextlevel. Identifier is already in use.
[08:31:35 WARN]: [PlaceholderAPI] Failed to load expansion poost.expboost. Identifier is already in use.
[08:31:35 WARN]: [PlaceholderAPI] Failed to load expansion raanga. Identifier is already in use.

Maybe it has to do something with the variable names or something?
