### ISSUE TITLE
Huge Error on Start Up

### ISSUE THREAD

**Issue by EquipableMC** [SkriptLang/Skript#5985]
### Skript/Server Version

```markdown
[20:24:29] [Server thread/INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[20:24:29] [Server thread/INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[20:24:29] [Server thread/INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[20:24:29] [Server thread/INFO]: [Skript] Server Version: git-Pufferfish-72 (MC: 1.18.2)
[20:24:29] [Server thread/INFO]: [Skript] Skript Version: 2.7.0 (skriptlang-github)
[20:24:29] [Server thread/INFO]: [Skript] Installed Skript Addons: 
[20:24:29] [Server thread/INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[20:24:29] [Server thread/INFO]: [Skript]  - Skent v3.2.0
[20:24:29] [Server thread/INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[20:24:29] [Server thread/INFO]: [Skript]  - DiSky v4.12.1
[20:24:29] [Server thread/INFO]: [Skript]  - MorkazSk v1.3
[20:24:29] [Server thread/INFO]: [Skript]  - MongoSK v2.3.0 (https://github.com/Romitou/MongoSK)
[20:24:29] [Server thread/INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[20:24:29] [Server thread/INFO]: [Skript]  - SkBee v2.18.0 (https://github.com/ShaneBeee/SkBee)
[20:24:29] [Server thread/INFO]: [Skript]  - skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo)
[20:24:29] [Server thread/INFO]: [Skript] Installed dependencies: 
[20:24:29] [Server thread/INFO]: [Skript]  - Vault v1.7.3-b131
[20:24:29] [Server thread/INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

On server start, there is a huge error, with no information causing it, I don't know exactly what is causing it.

### Expected Behavior

N/A

### Steps to Reproduce

N/A

### Errors or Screenshots

[20:18:36] [Server thread/INFO]: [Skript] Loading variables...
[20:18:36] [Server thread/INFO]: [Skript] Loaded 308 variables in 0.0 seconds
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[20:18:37] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:18:37] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:18:37] [Server thread/ERROR]: #!#! Here is full list of them:
[20:18:37] [Server thread/ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) MongoSK v2.3.0 (https://github.com/Romitou/MongoSK) skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) MorkazSk v1.3 skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) DiSky v4.12.1 skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo) SkBee v2.18.0 (https://github.com/ShaneBeee/SkBee) DiscordSRV v1.26.2 (https://github.com/DiscordSRV/DiscordSRV) Skent v3.2.0 
[20:18:37] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:18:37] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:18:37] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:18:37] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:18:37] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:18:37] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! Stack trace:
[20:18:37] [Server thread/ERROR]: #!#! java.lang.NoSuchMethodError: 'ch.njol.skript.config.Config ch.njol.skript.lang.parser.ParserInstance.getCurrentScript()'
[20:18:37] [Server thread/ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.util.SkriptUtil.getCurrentScript(SkriptUtil.java:108)
[20:18:37] [Server thread/ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.expression.CustomExpressionSection.lambda$init$15(CustomExpressionSection.java:270)
[20:18:37] [Server thread/ERROR]: #!#!     at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[20:18:37] [Server thread/ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.expression.CustomExpressionSection.init(CustomExpressionSection.java:268)
[20:18:37] [Server thread/ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.init(CustomSyntaxSection.java:214)
[20:18:37] [Server thread/ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.init(CustomSyntaxSection.java:182)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptEvent.init(SkriptEvent.java:97)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//org.skriptlang.skript.lang.structure.Structure.init(Structure.java:117)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:266)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:204)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:184)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:654)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$3(ScriptLoader.java:501)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:422)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:438)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:500)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:814)
[20:18:37] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[20:18:37] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[20:18:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1175)
[20:18:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:318)
[20:18:37] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! Version Information:
[20:18:37] [Server thread/ERROR]: #!#!   Skript: 2.7.0 (latest)
[20:18:37] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[20:18:37] [Server thread/ERROR]: #!#!     Date: 08:55:03.744299
[20:18:37] [Server thread/ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[20:18:37] [Server thread/ERROR]: #!#!   Minecraft: 1.18.2
[20:18:37] [Server thread/ERROR]: #!#!   Java: 17.0.8.1 (OpenJDK 64-Bit Server VM 17.0.8.1+1)
[20:18:37] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.15.0-82-generic
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! Server platform: Paper
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! Current node: null
[20:18:37] [Server thread/ERROR]: #!#! Current item: null
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! Thread: Server thread
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! Language: english
[20:18:37] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! End of Error.
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[20:18:37] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:18:37] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:18:37] [Server thread/ERROR]: #!#! Here is full list of them:
[20:18:37] [Server thread/ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) MongoSK v2.3.0 (https://github.com/Romitou/MongoSK) skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) MorkazSk v1.3 skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) DiSky v4.12.1 skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo) SkBee v2.18.0 (https://github.com/ShaneBeee/SkBee) DiscordSRV v1.26.2 (https://github.com/DiscordSRV/DiscordSRV) Skent v3.2.0 
[20:18:37] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:18:37] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:18:37] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:18:37] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:18:37] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:18:37] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! Stack trace:
[20:18:37] [Server thread/ERROR]: #!#! java.lang.NoSuchMethodError: 'ch.njol.skript.config.Config ch.njol.skript.lang.parser.ParserInstance.getCurrentScript()'
[20:18:37] [Server thread/ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.util.SkriptUtil.getCurrentScript(SkriptUtil.java:108)
[20:18:37] [Server thread/ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomImport$SectionImport.init(CustomImport.java:82)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptEvent.init(SkriptEvent.java:97)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//org.skriptlang.skript.lang.structure.Structure.init(Structure.java:117)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:266)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:204)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:184)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:654)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$3(ScriptLoader.java:501)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:422)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:438)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:500)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)
[20:18:37] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:814)
[20:18:37] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[20:18:37] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[20:18:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1175)
[20:18:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:318)
[20:18:37] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! Version Information:
[20:18:37] [Server thread/ERROR]: #!#!   Skript: 2.7.0 (latest)
[20:18:37] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[20:18:37] [Server thread/ERROR]: #!#!     Date: 08:55:03.744299
[20:18:37] [Server thread/ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[20:18:37] [Server thread/ERROR]: #!#!   Minecraft: 1.18.2
[20:18:37] [Server thread/ERROR]: #!#!   Java: 17.0.8.1 (OpenJDK 64-Bit Server VM 17.0.8.1+1)
[20:18:37] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.15.0-82-generic
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! Server platform: Paper
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! Current node: null
[20:18:37] [Server thread/ERROR]: #!#! Current item: null
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! Thread: Server thread
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! Language: english
[20:18:37] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[20:18:37] [Server thread/ERROR]: #!#! 
[20:18:37] [Server thread/ERROR]: #!#! End of Error.
[20:18:37] [Server thread/ERROR]: #!#! 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
You need to update your addons. Specifically, skript-reflect.

**Comment by UnderscoreTud** [comment]
This is due to skript-reflect 2.3 not being compatible with Skript 2.7+. There's currently a dev build of skript-reflect 2.4 - (which should be compatible with Skript 2.7). You can find it [here](https://github.com/TPGamesNL/skript-reflect/releases/tag/v2.4-dev1).
