### ISSUE TITLE
Something broken since 2.7

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [SkriptLang/Skript#5986]
### Skript/Server Version

```markdown
[04:23:11 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[04:23:11 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[04:23:11 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[04:23:11 INFO]: [Skript] Server Version: git-Paper-83 (MC: 1.20.1)
[04:23:11 INFO]: [Skript] Skript Version: 2.7.0 (skriptlang-github)
[04:23:11 INFO]: [Skript] Installed Skript Addons: 
[04:23:11 INFO]: [Skript]  - skript-placeholders v1.5 (https://github.com/APickledWalrus/skript-placeholders)
[04:23:11 INFO]: [Skript]  - skript-yaml v1.4.1-for-MC-1.20
[04:23:11 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[04:23:11 INFO]: [Skript]  - SkBee v2.17.0 (https://github.com/ShaneBeee/SkBee)
[04:23:11 INFO]: [Skript] Installed dependencies: 
[04:23:11 INFO]: [Skript]  - Vault v1.7.3-b131
[04:23:11 INFO]: [Skript]  - WorldGuard v7.0.9-beta1+2249-223b80c
```

### Bug Description

When I reload my scripts, which is just one custom smelting recipe and a allowed command system, it throws an error, however on our other server with the exact same plugins for skript and scripts it doesn't happen.

### Expected Behavior

It to load and work like with 2.6.4.

### Steps to Reproduce

Install the named skript version and addons, put in these two scripts and start the server. But as mentioned it errors on only one out of two servers. 
recipe:
https://pastebin.com/qLFTnL1K
allowed command system:
https://pastebin.com/AZ84BjKp

### Errors or Screenshots

Error upon reloading the scripts:
`[04:26:57 ERROR]: #!#! 
[04:26:57 ERROR]: #!#! [Skript] Severe Error:
[04:26:57 ERROR]: #!#! 
[04:26:57 ERROR]: #!#! Something went horribly wrong with Skript.
[04:26:57 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[04:26:57 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[04:26:57 ERROR]: #!#! Here is full list of them:
[04:26:57 ERROR]: #!#! skript-placeholders v1.5 (https://github.com/APickledWalrus/skript-placeholders) skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) skript-yaml v1.4.1-for-MC-1.20 SkBee v2.17.0 (https://github.com/ShaneBeee/SkBee) BetonQuest v2.0.0-DEV-672 (https://www.betonquest.org) 
[04:26:57 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[04:26:57 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[04:26:57 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[04:26:57 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[04:26:57 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[04:26:57 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[04:26:57 ERROR]: #!#! 
[04:26:57 ERROR]: #!#! Stack trace:
[04:26:57 ERROR]: #!#! java.lang.NoSuchMethodError: 'ch.njol.skript.config.Config ch.njol.skript.lang.parser.ParserInstance.getCurrentScript()'
[04:26:57 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.util.SkriptUtil.getCurrentScript(SkriptUtil.java:108)
[04:26:57 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.custom.CustomImport$SectionImport.init(CustomImport.java:82)
[04:26:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptEvent.init(SkriptEvent.java:97)
[04:26:57 ERROR]: #!#!     at Skript.jar//org.skriptlang.skript.lang.structure.Structure.init(Structure.java:117)
[04:26:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:266)
[04:26:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:204)
[04:26:57 ERROR]: #!#!     at Skript.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:184)
[04:26:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:654)
[04:26:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$3(ScriptLoader.java:501)
[04:26:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:422)
[04:26:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:438)
[04:26:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:500)
[04:26:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)
[04:26:57 ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:814)
[04:26:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[04:26:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[04:26:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1112)
[04:26:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[04:26:57 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[04:26:57 ERROR]: #!#! 
[04:26:57 ERROR]: #!#! Version Information:
[04:26:57 ERROR]: #!#!   Skript: 2.7.0 (latest)
[04:26:57 ERROR]: #!#!     Flavor: skriptlang-github
[04:26:57 ERROR]: #!#!     Date: 08:55:03.744299
[04:26:57 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[04:26:57 ERROR]: #!#!   Minecraft: 1.20.1
[04:26:57 ERROR]: #!#!   Java: 17.0.8.1 (OpenJDK 64-Bit Server VM 17.0.8.1+1)
[04:26:57 ERROR]: #!#!   OS: Linux amd64 5.4.0-52-generic
[04:26:57 ERROR]: #!#! 
[04:26:57 ERROR]: #!#! Server platform: Paper
[04:26:57 ERROR]: #!#! 
[04:26:57 ERROR]: #!#! Current node: null
[04:26:57 ERROR]: #!#! Current item: null
[04:26:57 ERROR]: #!#! 
[04:26:57 ERROR]: #!#! Thread: Server thread
[04:26:57 ERROR]: #!#! 
[04:26:57 ERROR]: #!#! Language: english
[04:26:57 ERROR]: #!#! Link parse mode: DISABLED
[04:26:57 ERROR]: #!#! 
[04:26:57 ERROR]: #!#! End of Error.
[04:26:57 ERROR]: #!#! `

Shutdown error:
`[04:26:00 ERROR]: Could not pass event PluginDisableEvent to Skript v2.7.0
java.lang.NullPointerException: Cannot invoke "ch.njol.skript.command.ScriptCommand.unregisterHelp()" because "scriptCommand" is null
        at ch.njol.skript.command.Commands.unregisterCommand(Commands.java:290) ~[Skript.jar:?]
        at ch.njol.skript.structures.StructCommand.unload(StructCommand.java:325) ~[Skript.jar:?]
        at ch.njol.skript.ScriptLoader.unloadScripts(ScriptLoader.java:830) ~[Skript.jar:?]
        at ch.njol.skript.Skript.beforeDisable(Skript.java:1162) ~[Skript.jar:?]
        at ch.njol.skript.Skript.onPluginDisable(Skript.java:1104) ~[Skript.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor527.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-83]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-83]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-83]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:222) ~[paper-1.20.1.jar:git-Paper-83]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:148) ~[paper-1.20.1.jar:git-Paper-83]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[paper-1.20.1.jar:git-Paper-83]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.disablePlugins(CraftServer.java:570) ~[paper-1.20.1.jar:git-Paper-83]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:943) ~[paper-1.20.1.jar:git-Paper-83]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:806) ~[paper-1.20.1.jar:git-Paper-83]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1210) ~[paper-1.20.1.jar:git-Paper-83]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-83]`

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment]
You need to update reflect to the 2.4-dev release

**Comment by ILikeOrangeJuice** [comment]
Would you happen to have a link for that? While I am at it I will also update skbee. But it still seems weird that it errors on one server, but is fine on the other, while having the same plugins and everything.
