### ISSUE TITLE
New skript

### ISSUE THREAD

**Issue by LohsMC** [SkriptLang/Skript#5988]
### Skript/Server Version

```markdown
server version: git-Paper-550 (MC: 1.19.4)
Skript version: 2.7.0 (skriptlang-github)
```

### Bug Description

Skript 2.7.0 has an error when loading scripts, any script or folder. I have many addons but none of them appear red.

### Expected Behavior

It's supposed to reload the script and allow the server to make commands and functions.

### Steps to Reproduce

Download skript 2.7.0 and reload a script

### Errors or Screenshots

[11:53:48 ERROR]: #!#! 
[11:53:48 ERROR]: #!#! [Skript] Severe Error:
[11:53:48 ERROR]: #!#! Exception occurred in Skript's main command
[11:53:48 ERROR]: #!#! Used command: /sk reload /core/mobs/dummy.sk
[11:53:48 ERROR]: #!#! 
[11:53:48 ERROR]: #!#! Something went horribly wrong with Skript.
[11:53:48 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:53:48 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[11:53:48 ERROR]: #!#! Here is full list of them:
[11:53:48 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) skRayFall v1.9.28 (https://sk.rayfall.net/) skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) MorkazSk v1.3 skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) SkQuery v4.1.10 Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/) 
[11:53:48 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[11:53:48 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[11:53:48 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[11:53:48 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[11:53:48 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[11:53:48 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[11:53:48 ERROR]: #!#! 
[11:53:48 ERROR]: #!#! Stack trace:
[11:53:48 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "ch.njol.skript.command.ScriptCommand.unregisterHelp()" because "scriptCommand" is null
[11:53:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands.unregisterCommand(Commands.java:290)
[11:53:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.structures.StructCommand.unload(StructCommand.java:325)
[11:53:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.unloadScripts(ScriptLoader.java:830)
[11:53:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:864)
[11:53:48 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:189)
[11:53:48 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:53:48 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[11:53:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:929)
[11:53:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[11:53:48 ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[11:53:48 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:322)
[11:53:48 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:306)
[11:53:48 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2297)
[11:53:48 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2257)
[11:53:48 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[11:53:48 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[11:53:48 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:53:48 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[11:53:48 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[11:53:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1342)
[11:53:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[11:53:48 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[11:53:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1319)
[11:53:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1312)
[11:53:48 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[11:53:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1290)
[11:53:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1178)
[11:53:48 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[11:53:48 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[11:53:48 ERROR]: #!#! 
[11:53:48 ERROR]: #!#! Version Information:
[11:53:48 ERROR]: #!#!   Skript: 2.7.0
[11:53:48 ERROR]: #!#!     Flavor: skriptlang-github
[11:53:48 ERROR]: #!#!     Date: 08:55:03.744299
[11:53:48 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[11:53:48 ERROR]: #!#!   Minecraft: 1.19.4
[11:53:48 ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[11:53:48 ERROR]: #!#!   OS: Linux amd64 5.19.0-43-generic
[11:53:48 ERROR]: #!#! 
[11:53:48 ERROR]: #!#! Server platform: Paper
[11:53:48 ERROR]: #!#! 
[11:53:48 ERROR]: #!#! Current node: null
[11:53:48 ERROR]: #!#! Current item: null
[11:53:48 ERROR]: #!#! 
[11:53:48 ERROR]: #!#! Thread: Server thread
[11:53:48 ERROR]: #!#! 
[11:53:48 ERROR]: #!#! Language: english
[11:53:48 ERROR]: #!#! Link parse mode: DISABLED
[11:53:48 ERROR]: #!#! 
[11:53:48 ERROR]: #!#! End of Error.
[11:53:48 ERROR]: #!#! 

### Other

Skript 2.6.4 works fine but 2.7.0 doesn't load or register scripts/folders at all

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AlmanaX-21** [comment]
You have a broken addon, try recreating this error without any addons
@LohsMC

**Comment by AyhamAl-Ali** [comment]
Quoted from release notes:
> ## ⚠ Compatibility Warning
> Due to the major internal changes within this update, some addons may no longer work properly.
> Please be patient as addon developers work to update their addons.
> We have published a new release of our [AddonPatcher](https://github.com/SkriptLang/AddonPatcher/releases/tag/2.7.0-dev1), but be aware that it cannot fix all issues.

Addon issue.  Try updating skript-reflect from github
