### ISSUE TITLE
java.lang.Number Extends Serializble but not implementing it causes exceptions

### ISSUE THREAD

**Issue by Pumkinhead** [SkriptLang/Skript#5989]
### Skript/Server Version

```markdown
[17:02:19 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[17:02:19 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[17:02:19 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[17:02:19 INFO]: [Skript] Server Version: git-Paper-411 (MC: 1.17.1)
[17:02:19 INFO]: [Skript] Skript Version: 2.6.4
[17:02:19 INFO]: [Skript] Installed Skript Addons: 
[17:02:19 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[17:02:19 INFO]: [Skript]  - DiSky v4.11.1
[17:02:19 INFO]: [Skript]  - skJson v2.8.6 (https://github.com/SkJsonTeam/skJson)
[17:02:19 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[17:02:19 INFO]: [Skript]  - SkBee v2.11.0 (https://github.com/ShaneBeee/SkBee)
[17:02:19 INFO]: [Skript] Installed dependencies: 
[17:02:19 INFO]: [Skript]  - Vault v1.7.3-b131
[17:02:19 INFO]: [Skript]  - WorldGuard v7.0.6-SNAPSHOT+2121-32d16a7
```

### Bug Description

No clue, it just gives an error

### Expected Behavior

No clue, it just gives an error

### Steps to Reproduce

No clue, it just gives an error

### Errors or Screenshots

[16:43:00 WARN]: [Skript] Plugin Skript v2.6.4 generated an exception while executing task 103
ch.njol.skript.SkriptAPIException: Serializer of number must override newInstance(), canBeInstantiated() or mustSyncDeserialization() if its class does not have a nullary constructor
    at ch.njol.skript.classes.Serializer.newInstance(Serializer.java:79) ~[Skript-2.6.4.jar:?]
    at ch.njol.yggdrasil.Yggdrasil.newInstance(Yggdrasil.java:335) ~[Skript-2.6.4.jar:?]
    at ch.njol.yggdrasil.Yggdrasil.isSerializable(Yggdrasil.java:154) ~[Skript-2.6.4.jar:?]
    at ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:173) ~[Skript-2.6.4.jar:?]
    at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249) ~[Skript-2.6.4.jar:?]
    at ch.njol.skript.registrations.Classes.serialize(Classes.java:724) ~[Skript-2.6.4.jar:?]
    at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:438) ~[Skript-2.6.4.jar:?]
    at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:432) ~[Skript-2.6.4.jar:?]
    at ch.njol.skript.variables.FlatFileStorage.saveVariables(FlatFileStorage.java:386) ~[Skript-2.6.4.jar:?]
    at ch.njol.skript.variables.FlatFileStorage$1.run(FlatFileStorage.java:198) ~[Skript-2.6.4.jar:?]
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-411]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-411]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Other

I think it might have appeared after messing with skript-json

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
Seems like an addon issue, try disable all addons and see if that still happens.

**Comment by AyhamAl-Ali** [comment]
Related: #4099 #4224
Quoted from @TPGamesNL (Thank you TP)
> The issue is that Skript registers class java.lang.Number, and marks it as serializable. However, it doesn't implement any serializer: instead, it also registers subclasses (Float, Integer, Long, Double, etc) and adds actual serializers for those (technically, they're handled natively by Yggdrasil). But, it doesn't do this for all subclasses (e.g. BigInteger, BigDecimal and AtomicInteger), plus anyone can make a subclass of Number. Any of these unregistered subclasses will fall under Number, so Skript accepts them just fine (justly so), but serialization fails because no serializer is registered for them. I'd recommend adding a serializer to Number (e.g. JavaSerializer) since Number implements Java's Serializable (a interface which specifies that it can be serialized using Object(Input/Output)Stream)

**Comment by Pumkinhead** [comment]
I have no clue what do you mean

**Comment by AyhamAl-Ali** [comment]
It's for the team :D don't worry.
Does the exception keep popping up on your server?

**Comment by Pumkinhead** [comment]
It does

**Comment by Moderocky** [comment]
I think this might still be something we shouldn't fix; it looks like it's an addon returning some non-standard Number that the developer hasn't bothered to provide a serialiser for. If this is the case I think it's dangerous for us to try and handle it because we don't know what's going on.
