### ISSUE TITLE
Simple Send Skript not working

### ISSUE THREAD

**Issue by Minecraftian975** [SkriptLang/Skript#5999]
### Skript/Server Version

```markdown
2.7.0 is the skript version server version is git-Paper-119 MC 1.20.1
```

### Bug Description

My command wont work. it will play audio but not send messages in chat.

### Expected Behavior

My skript should have sent messages and played audio

### Steps to Reproduce

just the send message thing in chat.
send "Whatever i put here."

### Errors or Screenshots

[20:04:25 ERROR]: #!#! 
[20:04:25 ERROR]: #!#! [Skript] Severe Error:
[20:04:25 ERROR]: #!#! 
[20:04:25 ERROR]: #!#! Something went horribly wrong with Skript.
[20:04:25 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:04:25 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[20:04:25 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[20:04:25 ERROR]: #!#! 
[20:04:25 ERROR]: #!#! Stack trace:
[20:04:25 ERROR]: #!#! java.lang.IllegalStateException: zip file closed
[20:04:25 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[20:04:25 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[20:04:25 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[20:04:25 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[20:04:25 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195)
[20:04:25 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[20:04:25 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155)
[20:04:25 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[20:04:25 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[20:04:25 ERROR]: #!#!     at Skript.jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)
[20:04:25 ERROR]: #!#!     at com.google.gson.Gson.getAdapter(Gson.java:546)
[20:04:25 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:817)
[20:04:25 ERROR]: #!#!     at com.google.gson.Gson.toJsonTree(Gson.java:695)
[20:04:25 ERROR]: #!#!     at com.google.gson.Gson.toJsonTree(Gson.java:672)
[20:04:25 ERROR]: #!#!     at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:172)
[20:04:25 ERROR]: #!#!     at net.md_5.bungee.chat.BaseComponentSerializer.serialize(BaseComponentSerializer.java:197)
[20:04:25 ERROR]: #!#!     at net.md_5.bungee.chat.TextComponentSerializer.serialize(TextComponentSerializer.java:34)
[20:04:25 ERROR]: #!#!     at net.md_5.bungee.chat.TextComponentSerializer.serialize(TextComponentSerializer.java:13)
[20:04:25 ERROR]: #!#!     at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:88)
[20:04:25 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:825)
[20:04:25 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:795)
[20:04:25 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:742)
[20:04:25 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:719)
[20:04:25 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:79)
[20:04:25 ERROR]: #!#!     at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.improveBungeeComponentSerialization(ClientboundSystemChatPacket.java:33)
[20:04:25 ERROR]: #!#!     at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:17)
[20:04:25 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3164)
[20:04:25 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3152)
[20:04:25 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3132)
[20:04:25 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:154)
[20:04:25 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffMessage.execute(EffMessage.java:128)
[20:04:25 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[20:04:25 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[20:04:25 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[20:04:25 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[20:04:25 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:312)
[20:04:25 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:277)
[20:04:25 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:282)
[20:04:25 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands.handleCommand(Commands.java:193)
[20:04:25 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:152)
[20:04:25 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[20:04:25 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[20:04:25 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:04:25 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[20:04:25 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[20:04:25 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[20:04:25 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2554)
[20:04:25 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.chat(CraftPlayer.java:697)
[20:04:25 ERROR]: #!#!     at Citizens-2.0.32-b3201.jar//net.citizensnpcs.util.Util.runCommand(Util.java:452)
[20:04:25 ERROR]: #!#!     at Citizens-2.0.32-b3201.jar//net.citizensnpcs.trait.CommandTrait$NPCCommand.run(CommandTrait.java:628)
[20:04:25 ERROR]: #!#!     at Citizens-2.0.32-b3201.jar//net.citizensnpcs.trait.CommandTrait$1.lambda$runCommand$2(CommandTrait.java:342)
[20:04:25 ERROR]: #!#!     at Citizens-2.0.32-b3201.jar//net.citizensnpcs.trait.CommandTrait$1.runCommand(CommandTrait.java:345)
[20:04:25 ERROR]: #!#!     at Citizens-2.0.32-b3201.jar//net.citizensnpcs.trait.CommandTrait$1.run(CommandTrait.java:301)
[20:04:25 ERROR]: #!#!     at Citizens-2.0.32-b3201.jar//net.citizensnpcs.trait.CommandTrait.dispatch(CommandTrait.java:352)
[20:04:25 ERROR]: #!#!     at Citizens-2.0.32-b3201.jar//net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:515)
[20:04:25 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1186.execute(Unknown Source)
[20:04:25 ERROR]: #!#!     at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[20:04:25 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[20:04:25 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:04:25 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[20:04:25 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[20:04:25 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[20:04:25 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection$5.performInteraction(PlayerConnection.java:2857)
[20:04:25 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2905)
[20:04:25 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity$d.a(PacketPlayInUseEntity.java:131)
[20:04:25 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[20:04:25 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2846)
[20:04:25 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[20:04:25 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[20:04:25 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[20:04:25 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:04:25 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[20:04:25 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[20:04:25 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
[20:04:25 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[20:04:25 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[20:04:25 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)
[20:04:25 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)
[20:04:25 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[20:04:25 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1287)
[20:04:25 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1175)
[20:04:25 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[20:04:25 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[20:04:25 ERROR]: #!#! 
[20:04:25 ERROR]: #!#! Version Information:
[20:04:25 ERROR]: #!#!   Skript: 2.7.0
[20:04:25 ERROR]: #!#!     Flavor: skriptlang-github
[20:04:25 ERROR]: #!#!     Date: 08:55:03.744299
[20:04:25 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[20:04:25 ERROR]: #!#!   Minecraft: 1.20.1
[20:04:25 ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[20:04:25 ERROR]: #!#!   OS: Linux amd64 5.19.0-43-generic
[20:04:25 ERROR]: #!#! 
[20:04:25 ERROR]: #!#! Server platform: Paper
[20:04:25 ERROR]: #!#! 
[20:04:25 ERROR]: #!#! Current node: null
[20:04:25 ERROR]: #!#! Current item: send "?e[NPC] Gary?f: Hello." to event-player/console
[20:04:25 ERROR]: #!#! Current trigger: command /garydialogue (simple event) (garydialogue.sk, line 3)
[20:04:25 ERROR]: #!#! 
[20:04:25 ERROR]: #!#! Thread: Server thread
[20:04:25 ERROR]: #!#! 
[20:04:25 ERROR]: #!#! Language: english
[20:04:25 ERROR]: #!#! Link parse mode: DISABLED
[20:04:25 ERROR]: #!#! 
[20:04:25 ERROR]: #!#! End of Error.
[20:04:25 ERROR]: #!#! 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Can't replicate. Does restarting your server fix this, and does the console log indicate any other errors?

**Comment by Minecraftian975** [comment]
yes it does

**Comment by sovdeeth** [comment]
> yes it does

Please clarify, what does?

**Comment by Minecraftian975** [comment]
permission: op
    trigger:
        play sound "entity.villager.trade" at volume 2 at pitch 1 to player
        send "&e[NPC] Gary&f: Hello." to player
        wait 3 second
        play sound "entity.villager.trade" at volume 2 at pitch 1 to player
        send "&e[NPC] Gary&f: You should be wary of the area ahead." to player
        wait 3 second
        play sound "entity.villager.trade" at volume 2 at pitch 1 to player
        send "&e[NPC] Gary&f: I heard that monsters can spawn there." to player
i tried it both with send "" to player and just send "" without to player

**Comment by Minecraftian975** [comment]
the error continues

**Comment by Minecraftian975** [comment]
the top bit is
command: garydialogue

**Comment by Minecraftian975** [comment]
it worked on another server i used it on

**Comment by sovdeeth** [comment]
> Does restarting your server fix this, and does the console log indicate any other errors?

What about these questions?

**Comment by Minecraftian975** [comment]
im not sure
ill restart my server

**Comment by Minecraftian975** [comment]
it works now!

**Comment by Minecraftian975** [comment]
thank you :)
