### ISSUE TITLE
"random integer between x and y" throws error

### ISSUE THREAD

**Issue by Ancienty** [SkriptLang/Skript#6019]
### Skript/Server Version

```markdown
[23:14:16 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[23:14:16 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[23:14:16 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[23:14:16 INFO]: [Skript] Server Version: git-Paper-794 (MC: 1.16.5)
[23:14:16 INFO]: [Skript] Skript Version: 2.7.0 (skriptlang-github)
[23:14:16 INFO]: [Skript] Installed Skript Addons:
[23:14:16 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[23:14:16 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[23:14:16 INFO]: [Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[23:14:16 INFO]: [Skript]  - SkQuery v4.1.10
[23:14:16 INFO]: [Skript]  - ItemsAdder v3.5.0c-r4b (devs.beer)
[23:14:16 INFO]: [Skript] Installed dependencies:
[23:14:16 INFO]: [Skript]  - Vault v1.7.3-b131
[23:14:16 INFO]: [Skript]  - WorldGuard v7.0.5+3827266


Server version: 1.16.5 PaperSpigot
```

### Bug Description

set {_metinRandom} to random integer between 1 and 3

When the code above is executed, it throws an error to the console:
Error:

`[23:15:01] [Server thread/INFO]: Ancienty issued server command: /metintasitest
[23:15:01] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to Skript v2.7.0
java.lang.NoSuchMethodError: 'long java.util.Random.nextLong(long, long)'
	at ch.njol.skript.expressions.ExprRandomNumber.get(ExprRandomNumber.java:91) ~[?:?]
	at ch.njol.skript.expressions.ExprRandomNumber.get(ExprRandomNumber.java:39) ~[?:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101) ~[?:?]
	at ch.njol.skript.effects.EffChange.execute(EffChange.java:272) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[?:?]
	at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:86) ~[?:?]
	at ch.njol.skript.lang.function.Function.execute(Function.java:129) ~[?:?]
	at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:301) ~[?:?]
	at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:312) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:277) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:282) ~[?:?]
	at ch.njol.skript.command.Commands.handleCommand(Commands.java:193) ~[?:?]
	at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:152) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-794]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2177) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:15:01] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'metintasitest' in plugin Skript v2.7.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'long java.util.Random.nextLong(long, long)'
	at ch.njol.skript.expressions.ExprRandomNumber.get(ExprRandomNumber.java:91) ~[?:?]
	at ch.njol.skript.expressions.ExprRandomNumber.get(ExprRandomNumber.java:39) ~[?:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101) ~[?:?]
	at ch.njol.skript.effects.EffChange.execute(EffChange.java:272) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[?:?]
	at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:86) ~[?:?]
	at ch.njol.skript.lang.function.Function.execute(Function.java:129) ~[?:?]
	at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:301) ~[?:?]
	at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:312) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:277) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:282) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:221) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-794]
	... 19 more`

### Expected Behavior

It should give a random integer between x and y lol

### Steps to Reproduce

I don't think I need to specify it very much, just copy & paste this:

`command /metintasitest:
	trigger:
		player is "Ancienty":
			metinTasi()

function metinTasi():
	**set {_metinRandom} to random integer between 1 and 3**
	set block at {dontdelete::metintasi::%{_metinRandom}%::lokasyon} to {dontdelete::metintasi::%{_metinRandom}%::blok}
	set {metintasi::%{dontdelete::metintasi::%{_metinRandom}%::lokasyon}%::can} to {dontdelete::metintasi::%{_metinRandom}%::can}
	set {metintasi::%{dontdelete::metintasi::%{_metinRandom}%::lokasyon}%::seviye} to {_metinRandom}
	metinHoloGuncelle({_metinRandom}, "baslangic")`

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by UnderscoreTud** [comment]
Duplicated #5819
