### ISSUE TITLE
Skript severe error

### ISSUE THREAD

**Issue by DjedenOfficial** [SkriptLang/Skript#6048]
### Skript/Server Version

```markdown
Skript: 2.7.0
Server: Paper 1.20.1
```

### Bug Description

Hey, I'm running into an issue. When running a skript it does not function and I get an error in console. The plugin does function in 1.8.9 but in 1.20.1 it is not working.

The error:
[13:24:29 INFO]: nkp issued server command: /daily
[13:24:29 ERROR]: #!#!
[13:24:29 ERROR]: #!#! [Skript] Severe Error:
[13:24:29 ERROR]: #!#!
[13:24:29 ERROR]: #!#! Something went horribly wrong with Skript.
[13:24:29 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:24:29 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[13:24:29 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[13:24:29 ERROR]: #!#!
[13:24:29 ERROR]: #!#! Stack trace:
[13:24:29 ERROR]: #!#! java.lang.IllegalStateException: zip file closed
[13:24:29 ERROR]: #!#! at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[13:24:29 ERROR]: #!#! at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[13:24:29 ERROR]: #!#! at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[13:24:29 ERROR]: #!#! at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[13:24:29 ERROR]: #!#! at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195)
[13:24:29 ERROR]: #!#! at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[13:24:29 ERROR]: #!#! at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155)
[13:24:29 ERROR]: #!#! at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[13:24:29 ERROR]: #!#! at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[13:24:29 ERROR]: #!#! at Skript.jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)
[13:24:29 ERROR]: #!#! at com.google.gson.Gson.getAdapter(Gson.java:546)
[13:24:29 ERROR]: #!#! at com.google.gson.Gson.toJson(Gson.java:817)
[13:24:29 ERROR]: #!#! at com.google.gson.Gson.toJson(Gson.java:795)
[13:24:29 ERROR]: #!#! at com.google.gson.Gson.toJson(Gson.java:742)
[13:24:29 ERROR]: #!#! at com.google.gson.Gson.toJson(Gson.java:719)
[13:24:29 ERROR]: #!#! at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:79)
[13:24:29 ERROR]: #!#! at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.improveBungeeComponentSerialization(ClientboundSystemChatPacket.java:33)
[13:24:29 ERROR]: #!#! at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:17)
[13:24:29 ERROR]: #!#! at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3159)
[13:24:29 ERROR]: #!#! at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3147)
[13:24:29 ERROR]: #!#! at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3127)
[13:24:29 ERROR]: #!#! at Skript.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:154)
[13:24:29 ERROR]: #!#! at Skript.jar//ch.njol.skript.effects.EffMessage.execute(EffMessage.java:128)
[13:24:29 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[13:24:29 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[13:24:29 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[13:24:29 ERROR]: #!#! at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[13:24:29 ERROR]: #!#! at Skript.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:312)
[13:24:29 ERROR]: #!#! at Skript.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:277)
[13:24:29 ERROR]: #!#! at Skript.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:282)
[13:24:29 ERROR]: #!#! at Skript.jar//ch.njol.skript.command.Commands.handleCommand(Commands.java:193)
[13:24:29 ERROR]: #!#! at Skript.jar//ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:152)
[13:24:29 ERROR]: #!#! at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[13:24:29 ERROR]: #!#! at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[13:24:29 ERROR]: #!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:24:29 ERROR]: #!#! at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[13:24:29 ERROR]: #!#! at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[13:24:29 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[13:24:29 ERROR]: #!#! at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2323)
[13:24:29 ERROR]: #!#! at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2307)
[13:24:29 ERROR]: #!#! at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[13:24:29 ERROR]: #!#! at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[13:24:29 ERROR]: #!#! at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:24:29 ERROR]: #!#! at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:24:29 ERROR]: #!#! at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:24:29 ERROR]: #!#! at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
[13:24:29 ERROR]: #!#! at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[13:24:29 ERROR]: #!#! at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[13:24:29 ERROR]: #!#! at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)
[13:24:29 ERROR]: #!#! at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)
[13:24:29 ERROR]: #!#! at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[13:24:29 ERROR]: #!#! at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1287)
[13:24:29 ERROR]: #!#! at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1175)
[13:24:29 ERROR]: #!#! at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[13:24:29 ERROR]: #!#! at java.base/java.lang.Thread.run(Thread.java:833)
[13:24:29 ERROR]: #!#!
[13:24:29 ERROR]: #!#! Skript: 2.7.0 (latest)
[13:24:29 ERROR]: #!#! Flavor: skriptlang-github
[13:24:29 ERROR]: #!#! Date: 08:55:03.744299
[13:24:29 ERROR]: #!#! Bukkit: 1.20.1-R0.1-SNAPSHOT
[13:24:29 ERROR]: #!#! Minecraft: 1.20.1
[13:24:29 ERROR]: #!#! Java: 17.0.2 (OpenJDK 64-Bit Server VM 17.0.2+8-86)
[13:24:29 ERROR]: #!#! OS: Linux amd64 5.4.0-97-generic
[13:24:29 ERROR]: #!#!
[13:24:29 ERROR]: #!#! Server platform: Paper
[13:24:29 ERROR]: #!#!
[13:24:29 ERROR]: #!#! Current node: null
[13:24:29 ERROR]: #!#! Current item: send "§8[§bFishy§aMC§8] You have to wait %difference between [[timespan:1 day]] and {_waited} (as ch.njol.skript.util.Timespan)% before you can calim another key!" to event-player/console
[13:24:29 ERROR]: #!#! Current trigger: command /daily (simple event) (daily.sk, line 4)
[13:24:29 ERROR]: #!#!
[13:24:29 ERROR]: #!#! Thread: Server thread
[13:24:29 ERROR]: #!#!
[13:24:29 ERROR]: #!#! Language: english
[13:24:29 ERROR]: #!#! Link parse mode: DISABLED
[13:24:29 ERROR]: #!#!
[13:24:29 ERROR]: #!#! End of Error.
[13:24:29 ERROR]: #!#!

### Expected Behavior

To run my scripts.

### Steps to Reproduce

I don't know why this problem occurs.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Restart your server and see if it persists. This kind of error often happens if you use some sort of /reload, which you should never use with Skript.
