### ISSUE TITLE
Unknown

### ISSUE THREAD

**Issue by lafless** [SkriptLang/Skript#6077]
### Skript/Server Version

```markdown
[22:11:39 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[22:11:39 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[22:11:39 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[22:11:39 INFO]: [Skript] Server Version: git-SlimeWorldManager-15255 (MC: 1.20.1)
[22:11:39 INFO]: [Skript] Skript Version: 2.8.0-dev-nightly-690c8b1 (skriptlang-nightly)
[22:11:39 INFO]: [Skript] Installed Skript Addons:
[22:11:39 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[22:11:39 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[22:11:39 INFO]: [Skript]  - skJson v2.8.6 (https://github.com/SkJsonTeam/skJson)
[22:11:39 INFO]: [Skript]  - MorkazSk v1.3
[22:11:39 INFO]: [Skript]  - MongoSK v2.3.1 (https://github.com/Romitou/MongoSK)
[22:11:39 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[22:11:39 INFO]: [Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[22:11:39 INFO]: [Skript]  - SkJade v1.4.3 (https://www.github.com/Ankoki-Dev/SkJade)
[22:11:39 INFO]: [Skript]  - SkBee v2.18.2 (https://github.com/ShaneBeee/SkBee)
[22:11:39 INFO]: [Skript]  - RediSkript v1.3.6-feather
[22:11:39 INFO]: [Skript] Installed dependencies:
[22:11:39 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

Unknown, it seems to be an issue with the bossbar.

### Expected Behavior

The bossbar should update to {_launchValue}

### Steps to Reproduce

Run this code

`command /countdown <number>:
	trigger:
		set {_launchCharging} to arg-1
		set {_x} to location 2, 90, -26
		set {_y} to location -2, 99, -22
		while {_launchCharging} = 1:
			delete {_launchValue}
			broadcast "reset"
			loop all players:
				if player is within {_x} and {_y}:
					add 10 to {_launchValue}
					broadcast "+1"
			set bossbar "launch" value to {_launchValue}
			wait 1 second
		while {_launchCharging} = 0:
			send action bar "&cCountdown finished!!" to player
			stop loop`

### Errors or Screenshots

[22:10:45 ERROR]: #!#! 
[22:10:45 ERROR]: #!#! [Skript] Severe Error:
[22:10:45 ERROR]: #!#! 
[22:10:45 ERROR]: #!#! You're running a (buggy) nightly version of Skript.
[22:10:45 ERROR]: #!#! If this is not a test server, switch to a more stable release NOW!
[22:10:45 ERROR]: #!#! Your players are unlikely to appreciate crashes and/or data loss due to Skript bugs.
[22:10:45 ERROR]: #!#! 
[22:10:45 ERROR]: #!#! Just testing things? Good. Please report this bug, so that we can fix it before a stable release.
[22:10:45 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues
[22:10:45 ERROR]: #!#! 
[22:10:45 ERROR]: #!#! Stack trace:
[22:10:45 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "java.lang.Number.doubleValue()" because the return value of "ch.njol.skript.lang.Expression.getSingle(org.bukkit.event.Event)" is null
[22:10:45 ERROR]: #!#!     at skRayFall+v1.9.28.jar//net.rayfall.eyesniper2.skrayfall.bossbar.EffChangeBossBarValue.execute(EffChangeBossBarValue.java:40)
[22:10:45 ERROR]: #!#!     at skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[22:10:45 ERROR]: #!#!     at skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[22:10:45 ERROR]: #!#!     at skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[22:10:45 ERROR]: #!#!     at skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[22:10:45 ERROR]: #!#!     at skript.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:312)
[22:10:45 ERROR]: #!#!     at skript.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:277)
[22:10:45 ERROR]: #!#!     at skript.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:282)
[22:10:45 ERROR]: #!#!     at skript.jar//ch.njol.skript.command.Commands.handleCommand(Commands.java:193)
[22:10:45 ERROR]: #!#!     at skript.jar//ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:152)
[22:10:45 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[22:10:45 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[22:10:45 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:10:45 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[22:10:45 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[22:10:45 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[22:10:45 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2318)
[22:10:45 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2302)
[22:10:45 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[22:10:45 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[22:10:45 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:10:45 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[22:10:45 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[22:10:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1354)
[22:10:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[22:10:45 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[22:10:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1331)
[22:10:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1324)
[22:10:45 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[22:10:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1302)
[22:10:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1190)
[22:10:45 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[22:10:45 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1623)
[22:10:45 ERROR]: #!#! 
[22:10:45 ERROR]: #!#! Version Information:
[22:10:45 ERROR]: #!#!   Skript: 2.8.0-dev-nightly-690c8b1
[22:10:45 ERROR]: #!#!     Flavor: skriptlang-nightly
[22:10:45 ERROR]: #!#!     Date: 22:19:30.980817786
[22:10:45 ERROR]: #!#!   Bukkit: 1.20-R0.1-SNAPSHOT
[22:10:45 ERROR]: #!#!   Minecraft: 1.20
[22:10:45 ERROR]: #!#!   Java: 20.0.2 (Java HotSpot(TM) 64-Bit Server VM 20.0.2+9-78)
[22:10:45 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[22:10:45 ERROR]: #!#! 
[22:10:45 ERROR]: #!#! Server platform: Paper
[22:10:45 ERROR]: #!#! 
[22:10:45 ERROR]: #!#! Current node: null
[22:10:45 ERROR]: #!#! Current item: null
[22:10:45 ERROR]: #!#! Current trigger: command /countdown (simple event) (testing\testing.sk, line 112)
[22:10:45 ERROR]: #!#! 
[22:10:45 ERROR]: #!#! Thread: Server thread
[22:10:45 ERROR]: #!#! 
[22:10:45 ERROR]: #!#! Language: english
[22:10:45 ERROR]: #!#! Link parse mode: DISABLED
[22:10:45 ERROR]: #!#! 
[22:10:45 ERROR]: #!#! End of Error.
[22:10:45 ERROR]: #!#! 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
This is an issue with SkRayfall, not Skript.
