### ISSUE TITLE
EffScriptFile no longer works with directories as of 2.7

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#6096]
### Skript/Server Version

```markdown
[20:58:11 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[20:58:11 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[20:58:11 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[20:58:11 INFO]: [Skript] Server Version: git-Paper-196 (MC: 1.20.1)
[20:58:11 INFO]: [Skript] Skript Version: 2.7.1 (selfbuilt-unknown)
[20:58:11 INFO]: [Skript] Installed Skript Addons:
[20:58:11 INFO]: [Skript]  - skript-reflect v2.3.1-for-Skript-2.7 (https://github.com/TPGamesNL/skript-reflect)
[20:58:11 INFO]: [Skript]  - SkBee v3.0.0 (https://github.com/ShaneBeee/SkBee)
[20:58:11 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

The EffScriptFile class uses `ScriptLoader#getScript(File)` method which intakes a file expecting just a file, this meant that when using directories skript throws an exception into console.

### Expected Behavior

Skript to properly handle directories within EffScriptFile. Skript should add a directory check into the class and use `ScriptLoader#getScripts(File)` instead when it's true

### Steps to Reproduce

`reload script "blah/"` and/or `reload script "/blah/"`

### Errors or Screenshots

```md

[20:49:55 ERROR]: #!#! Stack trace:
[20:49:55 ERROR]: #!#! java.lang.IllegalArgumentException: Something other than a file was provided.
[20:49:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.getScript(ScriptLoader.java:190)
[20:49:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffScriptFile.execute(EffScriptFile.java:106)
[20:49:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[20:49:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[20:49:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[20:49:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:182)
[20:49:55 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands$2.lambda$onPlayerChat$0(Commands.java:281)
[20:49:55 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
[20:49:55 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[20:49:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
[20:49:55 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[20:49:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
[20:49:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[20:49:55 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[20:49:55 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1623)
```

### Other

Line of code in EffScriptFile that causes this https://github.com/SkriptLang/Skript/blob/8c7fec07d75990eb67b7bf244c81babea4ba2585/src/main/java/ch/njol/skript/effects/EffScriptFile.java#L105-L109

Skript build is based off of latest dev/patch branch

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Moderocky** [comment]
I've added something that fixes the example you gave, but I might look into whether this needs a bit of wider work.
