### ISSUE TITLE
Cannot reload scripts with /sk

### ISSUE THREAD

**Issue by not-3than** [SkriptLang/Skript#6099]
### Skript/Server Version

```markdown
[20:12:32 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[20:12:32 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[20:12:32 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[20:12:32 INFO]: [Skript] Server Version: git-Purpur-2060 (MC: 1.20.1)
[20:12:32 INFO]: [Skript] Skript Version: 2.7.1 (skriptlang-github)
[20:12:32 INFO]: [Skript] Installed Skript Addons: 
[20:12:32 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[20:12:32 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[20:12:32 INFO]: [Skript]  - DiSky v4.12.0
[20:12:32 INFO]: [Skript]  - MorkazSk v1.3
[20:12:32 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[20:12:32 INFO]: [Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[20:12:32 INFO]: [Skript]  - SkBee v2.18.1 (https://github.com/ShaneBeee/SkBee)
[20:12:32 INFO]: [Skript] Installed dependencies: 
[20:12:32 INFO]: [Skript]  - Vault v1.7.3-b131
[20:12:32 INFO]: [Skript]  - WorldGuard v7.0.9+5934e49
```

### Bug Description

Using /sk reload 'file' spits out a huge error. All my scripts on my server don't work when using 2.7.1

### Expected Behavior

The script reloads.

### Steps to Reproduce

Skript 2.7.1, type /sk reload 'file'

### Errors or Screenshots

[20:10:26 INFO]: ethanovich issued server command: /sk reload stats
[20:10:26 ERROR]: #!#! 
[20:10:26 ERROR]: #!#! [Skript] Severe Error:
[20:10:26 ERROR]: #!#! 
[20:10:26 ERROR]: #!#! Something went horribly wrong with Skript.
[20:10:26 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:10:26 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:10:26 ERROR]: #!#! Here is full list of them:
[20:10:26 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) skRayFall v1.9.28 (https://sk.rayfall.net/) skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) MorkazSk v1.3 skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) DiSky v4.12.0 SkBee v2.18.1 (https://github.com/ShaneBeee/SkBee) DiscordSRV v1.26.2 (https://github.com/DiscordSRV/DiscordSRV) 
[20:10:26 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:10:26 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:10:26 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:10:26 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:10:26 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:10:26 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:10:26 ERROR]: #!#! 
[20:10:26 ERROR]: #!#! Stack trace:
[20:10:26 ERROR]: #!#! java.lang.NoSuchMethodError: 'ch.njol.skript.config.Config ch.njol.skript.lang.parser.ParserInstance.getCurrentScript()'
[20:10:26 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.util.SkriptUtil.getCurrentScript(SkriptUtil.java:108)
[20:10:26 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.Types$3.parse(Types.java:60)
[20:10:26 ERROR]: #!#!     at skript-reflect.jar//com.btk5h.skriptmirror.skript.Types$3.parse(Types.java:57)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.registrations.Classes.parseSimple(Classes.java:468)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.registrations.Classes.parse(Classes.java:497)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:593)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:761)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:154)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1275)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:229)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:204)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:184)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:654)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$3(ScriptLoader.java:501)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:422)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:438)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:500)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)
[20:10:26 ERROR]: #!#!     at Skript-2.7.1.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:190)
[20:10:26 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:10:26 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[20:10:26 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:999)
[20:10:26 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[20:10:26 ERROR]: #!#!     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[20:10:26 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:332)
[20:10:26 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:316)
[20:10:26 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2447)
[20:10:26 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$22(PlayerConnection.java:2407)
[20:10:26 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[20:10:26 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[20:10:26 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:10:26 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[20:10:26 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[20:10:26 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1365)
[20:10:26 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[20:10:26 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[20:10:26 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1342)
[20:10:26 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1335)
[20:10:26 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[20:10:26 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1313)
[20:10:26 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1201)
[20:10:26 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[20:10:26 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[20:10:26 ERROR]: #!#! 
[20:10:26 ERROR]: #!#! Version Information:
[20:10:26 ERROR]: #!#!   Skript: 2.7.1 (latest)
[20:10:26 ERROR]: #!#!     Flavor: skriptlang-github
[20:10:26 ERROR]: #!#!     Date: 15:04:11.832253
[20:10:26 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[20:10:26 ERROR]: #!#!   Minecraft: 1.20.1
[20:10:26 ERROR]: #!#!   Java: 17.0.8.1 (OpenJDK 64-Bit Server VM 17.0.8.1+1)
[20:10:26 ERROR]: #!#!   OS: Linux amd64 4.19.0-25-amd64
[20:10:26 ERROR]: #!#! 
[20:10:26 ERROR]: #!#! Server platform: Paper
[20:10:26 ERROR]: #!#! 
[20:10:26 ERROR]: #!#! Current node: null
[20:10:26 ERROR]: #!#! Current item: null
[20:10:26 ERROR]: #!#! 
[20:10:26 ERROR]: #!#! Thread: Server thread
[20:10:26 ERROR]: #!#! 
[20:10:26 ERROR]: #!#! Language: english
[20:10:26 ERROR]: #!#! Link parse mode: STRICT
[20:10:26 ERROR]: #!#! 
[20:10:26 ERROR]: #!#! End of Error.
[20:10:26 ERROR]: #!#!

### Other

Skript is unusable :(

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
> [20:10:26 ERROR]: #!#! at skript-reflect.jar//com.btk5h.skriptmirror.util.SkriptUtil.getCurrentScript(SkriptUtil.java:108)

Seems like addon issue, update skript-reflect.
