### ISSUE TITLE
toString of Inventory is calls Classes#toString on an InventoryHolder

### ISSUE THREAD

**Issue by cheeezburga** [SkriptLang/Skript#6115]
### Skript/Server Version

```markdown
[22:20:20 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[22:20:20 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[22:20:20 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[22:20:20 INFO]: [Skript] Server Version: git-Paper-217 (MC: 1.20.2)
[22:20:20 INFO]: [Skript] Skript Version: 2.7.1 (skriptlang-github)
[22:20:20 INFO]: [Skript] Installed Skript Addons:
[22:20:20 INFO]: [Skript]  - skript-reflect v2.3.1-for-Skript-2.7 (https://github.com/TPGamesNL/skript-reflect)
[22:20:20 INFO]: [Skript]  - SkBee v2.18.3 (https://github.com/ShaneBeee/SkBee)
[22:20:20 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

In an `on inventory click` event, in a grindstone, I tried using `send event-inventory`, which resulted in the following error:
```
[Skript] The script 'test.sk' infinitely (or excessively) repeated itself!
```
With verbosity set to debug in `config.sk`, the following would recurse until met with the error above:
```
[22:09:57 WARN]: java.lang.StackOverflowError
[22:09:57 WARN]:        at java.base/java.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1051)
[22:09:57 WARN]:        at java.base/java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1050)
[22:09:57 WARN]:        at Skript.jar//ch.njol.skript.registrations.Classes.toString(Classes.java:639)
[22:09:57 WARN]:        at Skript.jar//ch.njol.skript.registrations.Classes.toString(Classes.java:611)
```
Trying any of the following syntaxes also resulted in the same problem:
```
send event-inventory
send event-inventory to player
broadcast event-inventory
send "%event-inventory%"
```

### Expected Behavior

It was not supposed to infinitely recurse until met with an error. It was supposed to return the correct inventory.

### Steps to Reproduce

Create a script with this, and then click in a grindstone (I imagine some other inventories would produce the same error but grindstone was what I used to get the error initially):
```
on inventory click:
    send event-inventory
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by moraedu** [comment]
What I assume is happening is that since grindstone is a special kind of inventory, it doesn't have an inventory holder impl and thus it is just recursing onto itself whenever trying to Classes#toString since the toString for the InventoryHolder classinfo is just `Classes.toString(holder)` for any holder of unknown type (I assume they thought there would not be another type of inventory holder that isn't a Player given the other cases)
<https://github.com/SkriptLang/Skript/blob/8c7fec07d75990eb67b7bf244c81babea4ba2585/src/main/java/ch/njol/skript/classes/data/BukkitClasses.java#L877>

**Comment by Moderocky** [comment]
For clarification, this bug was introduced by the server in 1.20.2 and isn't present in 1.20.1 or older from what I can tell, where the holder would be null.

**Comment by Moderocky** [comment]
I've made a partial fix for this but the problem's actually more widespread: anything that is an inventory holder and isn't also another covered classinfo (or null) will produce this error too.

This ought to be fixed properly at some point but I can't see a way of doing that without some big restructuring (maybe a toString that prohibits a certain classinfo?) so I'm leaving it as-is for now.
