### ISSUE TITLE
Items don't save in variables

### ISSUE THREAD

**Issue by gluester** [SkriptLang/Skript#6140]
### Skript/Server Version

```markdown
[23:53:15 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[23:53:15 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[23:53:15 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[23:53:15 INFO]: [Skript] Server Version: git-Purpur-2060 (MC: 1.20.1)
[23:53:15 INFO]: [Skript] Skript Version: 2.7.1 (skriptlang-github)
[23:53:15 INFO]: [Skript] Installed Skript Addons:
[23:53:15 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[23:53:15 INFO]: [Skript]  - Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/)
[23:53:15 INFO]: [Skript]  - skript-yaml v1.5
[23:53:15 INFO]: [Skript]  - skript-reflect v2.3.1-for-Skript-2.7 (https://github.com/TPGamesNL/skript-reflect)
[23:53:15 INFO]: [Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[23:53:15 INFO]: [Skript]  - SkQuery v4.1.10
[23:53:15 INFO]: [Skript]  - SkBee v2.18.3 (https://github.com/ShaneBeee/SkBee)
[23:53:15 INFO]: [Skript]  - Skript-Advancements v1.5.7
[23:53:15 INFO]: [Skript] Installed dependencies:
[23:53:15 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

I have a variable, {item::juicedCrossbow}, and upon restarting the server forgets it. It also returns as <none> if I attempt to print it. The following error also comes up:

```
[23:49:32 ERROR]: #!#!
[23:49:32 ERROR]: #!#! [Skript] Severe Error:
[23:49:32 ERROR]: #!#!
[23:49:32 ERROR]: #!#! Something went horribly wrong with Skript.
[23:49:32 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[23:49:32 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[23:49:32 ERROR]: #!#! Here is full list of them:
[23:49:32 ERROR]: #!#! skRayFall v1.9.28 (https://sk.rayfall.net/) skript-reflect v2.3.1-for-Skript-2.7 (https://github.com/TPGamesNL/skript-reflect) Skript-Advancements v1.5.7 skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) SkBee v2.18.3 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.5 Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/) SkQuery v4.1.10
[23:49:32 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[23:49:32 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[23:49:32 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[23:49:32 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[23:49:32 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[23:49:32 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[23:49:32 ERROR]: #!#!
[23:49:32 ERROR]: #!#! Stack trace:
[23:49:32 ERROR]: #!#! java.io.FileNotFoundException: C:\Users\ethan\Documents\server\.\plugins\Skript\variables.csv (The process cannot access the file because it is being used by another process)
[23:49:32 ERROR]: #!#!     at java.base/java.io.FileOutputStream.open0(Native Method)
[23:49:32 ERROR]: #!#!     at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
[23:49:32 ERROR]: #!#!     at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
[23:49:32 ERROR]: #!#!     at Skript.jar//ch.njol.skript.variables.FlatFileStorage.connect(FlatFileStorage.java:329)
[23:49:32 ERROR]: #!#!     at Skript.jar//ch.njol.skript.variables.FlatFileStorage.load_i(FlatFileStorage.java:271)
[23:49:32 ERROR]: #!#!     at Skript.jar//ch.njol.skript.variables.VariablesStorage.load(VariablesStorage.java:234)
[23:49:32 ERROR]: #!#!     at Skript.jar//ch.njol.skript.variables.Variables.load(Variables.java:261)
[23:49:32 ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:638)
[23:49:32 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:49:32 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[23:49:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1127)
[23:49:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[23:49:32 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[23:49:32 ERROR]: #!#!
[23:49:32 ERROR]: #!#! Version Information:
[23:49:32 ERROR]: #!#!   Skript: 2.7.1 (latest)
[23:49:32 ERROR]: #!#!     Flavor: skriptlang-github
[23:49:32 ERROR]: #!#!     Date: 15:04:11.832253
[23:49:32 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[23:49:32 ERROR]: #!#!   Minecraft: 1.20.1
[23:49:32 ERROR]: #!#!   Java: 17.0.7 (Java HotSpot(TM) 64-Bit Server VM 17.0.7+8-LTS-224)
[23:49:32 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[23:49:32 ERROR]: #!#!
[23:49:32 ERROR]: #!#! Server platform: Paper
[23:49:32 ERROR]: #!#!
[23:49:32 ERROR]: #!#! Current node: null
[23:49:32 ERROR]: #!#! Current item: null
[23:49:32 ERROR]: #!#!
[23:49:32 ERROR]: #!#! Thread: Server thread
[23:49:32 ERROR]: #!#!
[23:49:32 ERROR]: #!#! Language: english
[23:49:32 ERROR]: #!#! Link parse mode: DISABLED
[23:49:32 ERROR]: #!#!
[23:49:32 ERROR]: #!#! End of Error.
[23:49:32 ERROR]: #!#!
```

### Expected Behavior

I expected the variable to save upon restart

### Steps to Reproduce

I'm using Purpur-2060 on 1.20.1, running on Windows 10

The variable was set using effect commands (using `!set {item::juicedCrossbow} to player's tool`) and returns as nothing when you attempt to send the variable in chat via effect commands. Before restarting, it works as normal.

### Other

I don't know if this is related, but the server freezes when shutdown is attempted. The `latest.log` just stops at `[Skript] Disabling Skript v2.7.1`. Closing the server gui won't shut it off either (or ctrl + c in the terminal), the only way to stop it is with task manager or closing the terminal.

Not sure if it helps, but the plugins are `BeeConomy, Chunky, FastAsyncWorldEdit, LuckPerms, SkBee, Skellett, SkQuery, skRayFall, Skript, Skript-Advancements, skript-gui, skript-reflect, skript-yaml, spark, TerraformGenerator, Vault`

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Moderocky** [comment]
The error suggests you don't have a `variables.csv` file in your Skript folder, is this the case?
It sounds like for some reason it is unable to create/save the variables file to disk.
Are you able to replicate this error with no addons?

**Comment by gluester** [comment]
turns out it was an addon, sorry for the inconvenience & thank you for helping
