### ISSUE TITLE
skript cant handle strings properly

### ISSUE THREAD

**Issue by peters-stuff** [SkriptLang/Skript#6165]
### Skript/Server Version

```markdown
[13:47:33 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[13:47:33 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[13:47:33 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[13:47:33 INFO]: [Skript] Server Version: git-Paper-260 (MC: 1.20.2)
[13:47:33 INFO]: [Skript] Skript Version: 2.7.1 (skriptlang-github)
[13:47:33 INFO]: [Skript] Installed Skript Addons: None
[13:47:33 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

this is the skript:
on join:
 teleport player to location(0.5, 69, 0.5, world "world")
 send "&a| &bWelcome to &3KIT-PVP&b!" to player
 send "&a| &bTo play just do &6&l/kit&r&b and jump down" to player
 send "&a| &bto start fighting!" to player
i join and it teleports me but it dosnt say nothing. in console it errors.

### Expected Behavior

it teleports and says the messages

### Steps to Reproduce

on join:
 teleport player to location(0.5, 69, 0.5, world "world")
 send "&a| &bWelcome to &3KIT-PVP&b!" to player
 send "&a| &bTo play just do &6&l/kit&r&b and jump down" to player
 send "&a| &bto start fighting!" to player

### Errors or Screenshots

[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! [Skript] Severe Error:
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! Something went horribly wrong with Skript.
[13:45:54 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:45:54 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[13:45:54 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! Stack trace:
[13:45:54 ERROR]: #!#! java.lang.IllegalStateException: zip file closed
[13:45:54 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:840)
[13:45:54 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:339)
[13:45:54 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:517)
[13:45:54 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:472)
[13:45:54 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[13:45:54 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[13:45:54 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[13:45:54 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[13:45:54 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[13:45:54 ERROR]: #!#!     at Skript.jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)
[13:45:54 ERROR]: #!#!     at com.google.gson.Gson.getAdapter(Gson.java:556)
[13:45:54 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:834)
[13:45:54 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:812)
[13:45:54 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:759)
[13:45:54 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:736)
[13:45:54 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:79)
[13:45:54 ERROR]: #!#!     at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.improveBungeeComponentSerialization(ClientboundSystemChatPacket.java:33)
[13:45:54 ERROR]: #!#!     at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:17)
[13:45:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3222)
[13:45:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3210)
[13:45:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3190)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:154)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffMessage.execute(EffMessage.java:128)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffTeleport.lambda$walk$0(EffTeleport.java:140)
[13:45:54 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
[13:45:54 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
[13:45:54 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffTeleport.walk(EffTeleport.java:120)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:152)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.lambda$check$5(SkriptEventHandler.java:166)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:163)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66)
[13:45:54 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[13:45:54 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:45:54 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[13:45:54 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[13:45:54 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.players.PlayerList.a(PlayerList.java:325)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:130)
[13:45:54 ERROR]: #!#!     at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:18)
[13:45:54 ERROR]: #!#!     at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9)
[13:45:54 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:45:54 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:45:54 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[13:45:54 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[13:45:54 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[13:45:54 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! Version Information:
[13:45:54 ERROR]: #!#!   Skript: 2.7.1 (latest)
[13:45:54 ERROR]: #!#!     Flavor: skriptlang-github
[13:45:54 ERROR]: #!#!     Date: 15:04:11.832253
[13:45:54 ERROR]: #!#!   Bukkit: 1.20.2-R0.1-SNAPSHOT
[13:45:54 ERROR]: #!#!   Minecraft: 1.20.2
[13:45:54 ERROR]: #!#!   Java: 17.0.8.1 (OpenJDK 64-Bit Server VM 17.0.8.1+1)
[13:45:54 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! Server platform: Paper
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! Current node: null
[13:45:54 ERROR]: #!#! Current item: send "§a| §bWelcome to §3KIT-PVP§b!" to the player
[13:45:54 ERROR]: #!#! Current trigger: join (simple event) (sk.sk, line 1)
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! Thread: Server thread
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! Language: english
[13:45:54 ERROR]: #!#! Link parse mode: DISABLED
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! End of Error.
[13:45:54 ERROR]: #!#!

### Other

[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! [Skript] Severe Error:
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! Something went horribly wrong with Skript.
[13:45:54 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:45:54 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[13:45:54 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! Stack trace:
[13:45:54 ERROR]: #!#! java.lang.IllegalStateException: zip file closed
[13:45:54 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:840)
[13:45:54 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:339)
[13:45:54 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:517)
[13:45:54 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:472)
[13:45:54 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[13:45:54 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[13:45:54 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[13:45:54 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[13:45:54 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[13:45:54 ERROR]: #!#!     at Skript.jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)
[13:45:54 ERROR]: #!#!     at com.google.gson.Gson.getAdapter(Gson.java:556)
[13:45:54 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:834)
[13:45:54 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:812)
[13:45:54 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:759)
[13:45:54 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:736)
[13:45:54 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:79)
[13:45:54 ERROR]: #!#!     at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.improveBungeeComponentSerialization(ClientboundSystemChatPacket.java:33)
[13:45:54 ERROR]: #!#!     at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:17)
[13:45:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3222)
[13:45:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3210)
[13:45:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3190)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:154)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffMessage.execute(EffMessage.java:128)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffTeleport.lambda$walk$0(EffTeleport.java:140)
[13:45:54 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
[13:45:54 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
[13:45:54 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffTeleport.walk(EffTeleport.java:120)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:152)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.lambda$check$5(SkriptEventHandler.java:166)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:163)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[13:45:54 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66)
[13:45:54 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[13:45:54 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:45:54 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[13:45:54 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[13:45:54 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.players.PlayerList.a(PlayerList.java:325)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:130)
[13:45:54 ERROR]: #!#!     at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:18)
[13:45:54 ERROR]: #!#!     at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9)
[13:45:54 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:45:54 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:45:54 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[13:45:54 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[13:45:54 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
[13:45:54 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[13:45:54 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! Version Information:
[13:45:54 ERROR]: #!#!   Skript: 2.7.1 (latest)
[13:45:54 ERROR]: #!#!     Flavor: skriptlang-github
[13:45:54 ERROR]: #!#!     Date: 15:04:11.832253
[13:45:54 ERROR]: #!#!   Bukkit: 1.20.2-R0.1-SNAPSHOT
[13:45:54 ERROR]: #!#!   Minecraft: 1.20.2
[13:45:54 ERROR]: #!#!   Java: 17.0.8.1 (OpenJDK 64-Bit Server VM 17.0.8.1+1)
[13:45:54 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! Server platform: Paper
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! Current node: null
[13:45:54 ERROR]: #!#! Current item: send "§a| §bWelcome to §3KIT-PVP§b!" to the player
[13:45:54 ERROR]: #!#! Current trigger: join (simple event) (sk.sk, line 1)
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! Thread: Server thread
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! Language: english
[13:45:54 ERROR]: #!#! Link parse mode: DISABLED
[13:45:54 ERROR]: #!#!
[13:45:54 ERROR]: #!#! End of Error.
[13:45:54 ERROR]: #!#!

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by DelayedGaming** [comment]
Can you try and re-upload Skript jar? This error usually happens due to the jar being corrupted.

**Comment by Moderocky** [comment]
The plugin might have been loaded or modified using something like plug man, which breaks Skript, or the actual Jar file could have been moved or tampered with after the server has started.
