### ISSUE TITLE
Exception in thread Skript database 'database 1' monitor thread

### ISSUE THREAD

**Issue by evolvex3** [SkriptLang/Skript#6182]
### Skript/Server Version

```markdown
Skript: 2.2-dev25
Bukkit: 1.8.8-R0.1-SNAPSHOT
Minecraft: 1.8.8
```

### Bug Description

When the server is turned off, the skript plugin cannot be turned off

### Expected Behavior

.

### Steps to Reproduce

Sometimes the problem appears and sometimes it doesn't

### Errors or Screenshots

[22:01:55] [INFO]: [Skript] Disabling Skript v2.2-dev25
[22:01:55] [INFO]: UUID of player chincyk321 is 2ca6852e-78d9-3831-87fa-30cfdfac7ed1
[22:01:57] [INFO]: UUID of player tactivefive_2 is aeee2de9-ab8c-3298-bac7-a39fbaf667cd
[22:02:26] [INFO]: UUID of player BxngaL is 7baf8e24-f93d-327e-a99b-f291919cad46
[22:02:43] [INFO]: UUID of player LeVyXD is 8a42b688-3047-3f0f-8c9a-381b43c6c6f8
[22:03:00] [INFO]: UUID of player Darkcice is 87d0f948-da67-34fa-9868-1a6f683355f5
[22:03:06] [ERROR]: #!#! 
[22:03:06] [ERROR]: #!#! [Skript] Severe Error:
[22:03:06] [ERROR]: #!#! Exception in thread Skript database 'database 1' monitor thread
[22:03:06] [ERROR]: #!#! 
[22:03:06] [ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[22:03:06] [ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[22:03:06] [ERROR]: #!#! and check whether this error has already been reported.
[22:03:06] [ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[22:03:06] [ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[22:03:06] [ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[22:03:06] [ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[22:03:06] [ERROR]: #!#! 
[22:03:06] [ERROR]: #!#! Stack trace:
[22:03:06] [ERROR]: #!#! org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[22:03:06] [ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.validate(SourceFile:467)
[22:03:06] [ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.callSyncMethod(SourceFile:173)
[22:03:06] [ERROR]: #!#!     at ch.njol.skript.util.Task.callSync(Task.java:153)
[22:03:06] [ERROR]: #!#!     at ch.njol.skript.util.Task.callSync(Task.java:132)
[22:03:06] [ERROR]: #!#!     at ch.njol.skript.variables.DatabaseStorage.loadVariables(DatabaseStorage.java:590)
[22:03:06] [ERROR]: #!#!     at ch.njol.skript.variables.DatabaseStorage.checkDatabase(DatabaseStorage.java:539)
[22:03:06] [ERROR]: #!#!     at ch.njol.skript.variables.DatabaseStorage$3.run(DatabaseStorage.java:327)
[22:03:06] [ERROR]: #!#!     at java.lang.Thread.run(Thread.java:750)
[22:03:06] [ERROR]: #!#! 
[22:03:06] [ERROR]: #!#! Version Information:
[22:03:06] [ERROR]: #!#!   Skript: 2.2-dev25
[22:03:06] [ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[22:03:06] [ERROR]: #!#!   Minecraft: 1.8.8
[22:03:06] [ERROR]: #!#!   Java: 1.8.0_382 (OpenJDK 64-Bit Server VM 25.382-b05)
[22:03:06] [ERROR]: #!#!   OS: Linux amd64 6.1.9-060109-generic
[22:03:06] [ERROR]: #!#! 
[22:03:06] [ERROR]: #!#! Running CraftBukkit: false
[22:03:06] [ERROR]: #!#! 
[22:03:06] [ERROR]: #!#! Current node: null
[22:03:06] [ERROR]: #!#! Current item: null
[22:03:06] [ERROR]: #!#! 
[22:03:06] [ERROR]: #!#! Thread: Skript database 'database 1' monitor thread
[22:03:06] [ERROR]: #!#! 
[22:03:06] [ERROR]: #!#! End of Error.
[22:03:06] [ERROR]: #!#! 

### Other

I tried updating the script to a newer version, but saving the ItemStack is different there.
I read that it is a problem with writing to mySQL. How can I transfer the MYSQL database to plain CSV?

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
We do not give support for your version of Skript. If you can reproduce it on 2.7.2, please make a new report.
