### ISSUE TITLE
Console Warnings

### ISSUE THREAD

**Issue by MagneBossen** [SkriptLang/Skript#6200]
### Skript/Server Version

```markdown
Server Vers: git-paper-262 (MC 1.20.2)
Skript Vers: 2.7.2
Installed Skript Addons:
Skript-placeholders v.1.5.2 https://github.com/APickledWalrus/skript-placeholders)
DiSky v4.12.0-beta3
skript-reflect v2.4-dev1 https://github.com/TPGamesNL/skript-reflect)
skRayFall v1.9.28 https://sk.rayfall.net/)
SkQuery v4.1.10
SkBee v2.18.4 https://github.com/ShaneBeee/SkBee)
Installed dependencies:
Vault v1.7.3-b131
WordlGuard v7.0.9+5934e49
```

### Bug Description

Console Warnings

### Expected Behavior

No idea

### Steps to Reproduce

Started up the server

### Errors or Screenshots

[22:54:45 INFO]: [Skript] Enabling Skript v2.7.2
[22:54:45 INFO]: [Skript]     Checking for updates failed. Do you have Internet connection?
[22:54:45 WARN]: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/SkriptLang/Skript/releases
[22:54:45 WARN]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[22:54:45 WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[22:54:45 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[22:54:45 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[22:54:45 WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[22:54:45 WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[22:54:45 WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[22:54:45 WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[22:54:45 WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[22:54:45 WARN]: Caused by: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/SkriptLang/Skript/releases
[22:54:45 WARN]: 	at Skript.jar//ch.njol.skript.update.GithubChecker.lambda$check$0(GithubChecker.java:111)
[22:54:45 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[22:54:45 WARN]: 	... 6 more
[22:54:45 WARN]: Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/SkriptLang/Skript/releases
[22:54:45 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2000)
[22:54:45 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[22:54:45 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[22:54:45 WARN]: 	at java.base/java.net.URL.openStream(URL.java:1161)
[22:54:45 WARN]: 	at Skript.jar//ch.njol.skript.update.GithubChecker.lambda$check$0(GithubChecker.java:105)
[22:54:45 WARN]: 	... 7 more
[22:54:50 INFO]: [Skript] Loaded 232530 aliases in 5139ms
[22:54:50 INFO]: [Skript]  ~ created by & ? Peter G?ttinger aka Njol ~

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by skDuckx** [comment]
From what I know,

This could be a result of having no internet connection if that's on localhost

Or

Could just be that your IP cannot access the github api url

**Comment by AyhamAl-Ali** [comment]
Either client didn't have an Internet connection or github API was down at that time which is rarely to happen. Nothing to worry about as it's not an issue.
