### ISSUE TITLE
skript not working

### ISSUE THREAD

**Issue by W-i-n-7** [SkriptLang/Skript#6214]
### Skript/Server Version

```markdown
> sk info
[20:51:32 INFO]: [Skript] Skript's aliases can be found here: https://github.com
/SkriptLang/skript-aliases
[20:51:32 INFO]: [Skript] Skript's documentation can be found here: https://docs
.skriptlang.org/
[20:51:32 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skr
iptlang.org/tutorials
[20:51:32 INFO]: [Skript] Server Version: git-Paper-297 (MC: 1.20.2)
[20:51:32 INFO]: [Skript] Skript Version: 2.7.3 (skriptlang-github)
[20:51:32 INFO]: [Skript] Installed Skript Addons:
[20:51:32 INFO]: [Skript]  - TuSKe v1.8.2 (github.com/Tuke-Nuke/TuSKe)
[20:51:32 INFO]: [Skript] Installed dependencies:
[20:51:32 INFO]: [Skript]  - Vault v1.7.3-b131
[20:51:32 INFO]: [Skript]  - WorldGuard v7.0.9+5934e49
```

### Bug Description

skript throws all these errors after i installed tuske

### Expected Behavior

it would work

### Steps to Reproduce

i installed TuSKe and then i get all of these in the console

### Errors or Screenshots

User
[20.42.05 ERROR] [Minecraft] #!#!
[20.42.05 ERROR] [Minecraft] #!#! [Skript] Severe Error:
[20.42.05 ERROR] [Minecraft] #!#! An error occurred while trying to load a Structure.
[20.42.05 ERROR] [Minecraft] #!#!
[20.42.05 ERROR] [Minecraft] #!#! Something went horribly wrong with Skript.
[20.42.05 ERROR] [Minecraft] #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20.42.05 ERROR] [Minecraft] #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20.42.05 ERROR] [Minecraft] #!#! Here is full list of them:
[20.42.05 ERROR] [Minecraft] #!#! TuSKe v1.8.2 (github.com/Tuke-Nuke/TuSKe)
[20.42.05 ERROR] [Minecraft] #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20.42.05 ERROR] [Minecraft] #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20.42.05 ERROR] [Minecraft] #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20.42.05 ERROR] [Minecraft] #!#! In that case, you will be given instruction on how should you report it.
[20.42.05 ERROR] [Minecraft] #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20.42.05 ERROR] [Minecraft] #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20.42.05 ERROR] [Minecraft] #!#!
[20.42.05 ERROR] [Minecraft] #!#! Stack trace:
[20.42.05 ERROR] [Minecraft] #!#! java.lang.RuntimeException: pattern compiling exception, element class: com.github.tukenuke.tuske.expressions.ExprEvaluateFunction (provided by TuSKe)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:236)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:531)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:761)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:154)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:149)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1275)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:229)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:945)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.<init>(ScriptCommand.java:190)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.structures.StructCommand.load(StructCommand.java:300)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$8(ScriptLoader.java:566)
[20.42.05 ERROR] [Minecraft] #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
[20.42.05 ERROR] [Minecraft] #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:558)
[20.42.05 ERROR] [Minecraft] #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[20.42.05 ERROR] [Minecraft] #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[20.42.05 ERROR] [Minecraft] #!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:511)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:813)
[20.42.05 ERROR] [Minecraft] #!#!     at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[20.42.05 ERROR] [Minecraft] #!#!     at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[20.42.05 ERROR] [Minecraft] #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1097)
[20.42.05 ERROR] [Minecraft] #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[20.42.05 ERROR] [Minecraft] #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[20.42.05 ERROR] [Minecraft] #!#! Caused by: ch.njol.skript.patterns.MalformedPatternException: single percentage sign at 19 [pattern: result of function %string(<.+?>)]
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:138)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:51)
[20.42.05 ERROR] [Minecraft] #!#!     at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1274)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:229)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:531)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:761)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:154)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:149)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1275)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:229)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:945)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.<init>(ScriptCommand.java:190)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.structures.StructCommand.load(StructCommand.java:300)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$8(ScriptLoader.java:566)
[20.42.05 ERROR] [Minecraft] #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
[20.42.05 ERROR] [Minecraft] #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:558)
[20.42.05 ERROR] [Minecraft] #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[20.42.05 ERROR] [Minecraft] #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[20.42.05 ERROR] [Minecraft] #!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:511)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)
[20.42.05 ERROR] [Minecraft] #!#!     at Skript.jar//ch.njol.skript.Skript$1.run(Skript.java:813)
[20.42.05 ERROR] [Minecraft] #!#!     at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[20.42.05 ERROR] [Minecraft] #!#!     at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[20.42.05 ERROR] [Minecraft] #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1097)
[20.42.05 ERROR] [Minecraft] #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[20.42.05 ERROR] [Minecraft] #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[20.42.05 ERROR] [Minecraft] #!#!
[20.42.05 ERROR] [Minecraft] #!#! Version Information:
[20.42.05 ERROR] [Minecraft] #!#!   Skript: 2.7.3 (latest)
[20.42.05 ERROR] [Minecraft] #!#!     Flavor: skriptlang-github
[20.42.05 ERROR] [Minecraft] #!#!     Date: 15:29:36.833117400
[20.42.05 ERROR] [Minecraft] #!#!   Bukkit: 1.20.2-R0.1-SNAPSHOT
[20.42.05 ERROR] [Minecraft] #!#!   Minecraft: 1.20.2
[20.42.05 ERROR] [Minecraft] #!#!   Java: 17.0.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39)
[20.42.05 ERROR] [Minecraft] #!#!   OS: Windows 7 amd64 6.1
[20.42.05 ERROR] [Minecraft] #!#!
[20.42.05 ERROR] [Minecraft] #!#! Server platform: Paper
[20.42.05 ERROR] [Minecraft] #!#!
[20.42.05 ERROR] [Minecraft] #!#! Current node: send "&8[&aServer&8] &fJoin the &bDiscord <tooltip:&6Click to open the &bDiscord><link:https://discord.gg/beEW7xDgrE/>&ehere." to player (discord.sk, line 4)
[20.42.05 ERROR] [Minecraft] #!#! Current item: null
[20.42.05 ERROR] [Minecraft] #!#!
[20.42.05 ERROR] [Minecraft] #!#! Thread: Server thread
[20.42.05 ERROR] [Minecraft] #!#!
[20.42.05 ERROR] [Minecraft] #!#! Language: english
[20.42.05 ERROR] [Minecraft] #!#! Link parse mode: DISABLED
[20.42.05 ERROR] [Minecraft] #!#!
[20.42.05 ERROR] [Minecraft] #!#! End of Error.
[20.42.05 ERROR] [Minecraft] #!#!
[20.42.05 INFO] [Skript] All scripts loaded without errors.
[20.42.05 INFO] [Skript] Loaded 1 script with a total of 1 structure in 0.07 seconds
[20.42.05 INFO] [Skript] Finished loading.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Ferrlix** [comment]
does it work without tuske

**Comment by Ferrlix** [comment]
i mean i use vanilla expressions in a function, with some skbee and that works fantastically. I dont see a need for tuske personally

**Comment by W-i-n-7** [comment]
thank you both i tried tuske because i didnt know of anything else
