### ISSUE TITLE
Error retrieving Anvil Rename Text Input

### ISSUE THREAD

**Issue by YodaZen** [SkriptLang/Skript#6228]
### Skript/Server Version

```markdown
[21:29:41 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[21:29:41 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[21:29:41 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[21:29:41 INFO]: [Skript] Server Version: git-Paper-388 (MC: 1.18.2)
[21:29:41 INFO]: [Skript] Skript Version: 2.7.3 (skriptlang-github)
[21:29:41 INFO]: [Skript] Installed Skript Addons: 
[21:29:41 INFO]: [Skript]  - skript-reflect v2.3.1-for-Skript-2.7 (https://github.com/TPGamesNL/skript-reflect)
[21:29:41 INFO]: [Skript]  - SkBee v3.0.1 (https://github.com/ShaneBeee/SkBee)
[21:29:41 INFO]: [Skript] Installed dependencies: 
[21:29:41 INFO]: [Skript]  - Vault v1.7.3-b131
[21:29:41 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

Sends stack trace in console from expression usage.

### Expected Behavior

For it to return the text input of the anvil.

### Steps to Reproduce

On inventory click:
    type of event-inventory is anvil inventory
    set {_input} to anvil text input of the event-inventory

### Errors or Screenshots

```
[16:38:13 ERROR]: #!#! 
[16:38:13 ERROR]: #!#! [Skript] Severe Error:
[16:38:13 ERROR]: #!#! An error occurred while trying to load a Structure.
[16:38:13 ERROR]: #!#! 
[16:38:13 ERROR]: #!#! Something went horribly wrong with Skript.
[16:38:13 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:38:13 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[16:38:13 ERROR]: #!#! Here is full list of them:
[16:38:13 ERROR]: #!#! SkBee v3.0.1 (https://github.com/ShaneBeee/SkBee) 
[16:38:13 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[16:38:13 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[16:38:13 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[16:38:13 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[16:38:13 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[16:38:13 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[16:38:13 ERROR]: #!#! 
[16:38:13 ERROR]: #!#! Stack trace:
[16:38:13 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "ch.njol.skript.lang.Expression.isSingle()" because "this.expr" is null
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.base.PropertyExpression.isSingle(PropertyExpression.java:124)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffChange.init(EffChange.java:250)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:266)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:945)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.loadCode(Section.java:90)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:237)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.init(Section.java:69)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:266)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:179)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:212)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.parse(Section.java:178)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:965)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.loadCode(Section.java:90)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:237)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.init(Section.java:69)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:266)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:179)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:212)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Section.parse(Section.java:178)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:965)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptEvent.load(SkriptEvent.java:133)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$8(ScriptLoader.java:566)
[16:38:13 ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
[16:38:13 ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:558)
[16:38:13 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[16:38:13 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[16:38:13 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:511)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)
[16:38:13 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:153)
[16:38:13 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:38:13 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[16:38:13 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[16:38:13 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2307)
[16:38:13 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2118)
[16:38:13 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2099)
[16:38:13 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[16:38:13 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[16:38:13 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[16:38:13 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:38:13 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[16:38:13 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[16:38:13 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1400)
[16:38:13 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[16:38:13 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[16:38:13 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1377)
[16:38:13 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1370)
[16:38:13 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[16:38:13 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1348)
[16:38:13 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1230)
[16:38:13 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[16:38:13 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[16:38:13 ERROR]: #!#! 
[16:38:13 ERROR]: #!#! Version Information:
[16:38:13 ERROR]: #!#!   Skript: 2.7.3 (latest)
[16:38:13 ERROR]: #!#!     Flavor: skriptlang-github
[16:38:13 ERROR]: #!#!     Date: 15:29:36.833117400
[16:38:13 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[16:38:13 ERROR]: #!#!   Minecraft: 1.18.2
[16:38:13 ERROR]: #!#!   Java: 17.0.9 (OpenJDK 64-Bit Server VM 17.0.9+9)
[16:38:13 ERROR]: #!#!   OS: Linux amd64 6.1.0-13-amd64
[16:38:13 ERROR]: #!#! 
[16:38:13 ERROR]: #!#! Server platform: Paper
[16:38:13 ERROR]: #!#! 
[16:38:13 ERROR]: #!#! Current node: set {_input} to (anvil text input of event-inventory) (Casino/games/mines.sk, line 96)
[16:38:13 ERROR]: #!#! Current item: null
[16:38:13 ERROR]: #!#! 
[16:38:13 ERROR]: #!#! Thread: Server thread
[16:38:13 ERROR]: #!#! 
[16:38:13 ERROR]: #!#! Language: english
[16:38:13 ERROR]: #!#! Link parse mode: DISABLED
[16:38:13 ERROR]: #!#! 
[16:38:13 ERROR]: #!#! End of Error.
[16:38:13 ERROR]: #!#! 
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Moderocky** [comment]
I've removed the init override, please check nothing else needs tweaking with the class as well :)

**Comment by Saanjuk** [comment]
`on inventory click:
    type of event-inventory is anvil inventory
    cancel event
    set {_input} to anvil text input of the event-inventory
    send "%{_input}%"`
    
   sending <none>

**Comment by Saanjuk** [comment]
`on inventory click:`
`    type of event-inventory is anvil inventory`
`    cancel event`
`    send the anvil text input of the event-inventory to player`
does nothing
