### ISSUE TITLE
IllegalArgumentExpression when getting shoes of entity introduced by #5456 

### ISSUE THREAD

**Issue by sovdeeth** [SkriptLang/Skript#6273]
### Skript/Server Version

```markdown
[14:01:25 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:01:25 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[14:01:25 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[14:01:25 INFO]: [Skript] Server Version: git-Paper-550 (MC: 1.19.4)
[14:01:25 INFO]: [Skript] Skript Version: 2.8.0-dev (selfbuilt-unknown)
[14:01:25 INFO]: [Skript] Installed Skript Addons: None
[14:01:25 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

using ``shoes of %entity%`` causes an IllegalArgumentExpression because it tries to get `EquipSlot.valueOf("SHOES")`, when `EquipSlot` only has `BOOTS`. This can be fixed with a simple syntax change, rearranging the parse tags.

### Expected Behavior

No error, act the same as `boots of %entity%`.

### Steps to Reproduce

`!send shoes of all entities`

### Errors or Screenshots

```
[14:00:22 ERROR]: #!#!
[14:00:22 ERROR]: #!#! [Skript] Severe Error:
[14:00:22 ERROR]: #!#! Unexpected error while executing effect command 'send shoes of all entities' by 'CONSOLE'
[14:00:22 ERROR]: #!#!
[14:00:22 ERROR]: #!#! Something went horribly wrong with Skript.
[14:00:22 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:00:22 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[14:00:22 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[14:00:22 ERROR]: #!#!
[14:00:22 ERROR]: #!#! Stack trace:
[14:00:22 ERROR]: #!#! java.lang.IllegalArgumentException: No enum constant ch.njol.skript.util.slot.EquipmentSlot.EquipSlot.SHOES
[14:00:22 ERROR]: #!#!     at java.base/java.lang.Enum.valueOf(Enum.java:273)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.slot.EquipmentSlot$EquipSlot.valueOf(EquipmentSlot.java:38)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.ExprArmorSlot.init(ExprArmorSlot.java:64)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:266)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:537)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:767)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:154)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:58)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1282)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:229)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.parse(Effect.java:76)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:190)
[14:00:22 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:171)
[14:00:22 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[14:00:22 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[14:00:22 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:00:22 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[14:00:22 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[14:00:22 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[14:00:22 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.bh(DedicatedServer.java:496)
[14:00:22 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:448)
[14:00:22 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[14:00:22 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[14:00:22 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[14:00:22 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[14:00:22 ERROR]: #!#!
[14:00:22 ERROR]: #!#! Version Information:
[14:00:22 ERROR]: #!#!   Skript: 2.8.0-dev (custom version)
[14:00:22 ERROR]: #!#!     Flavor: selfbuilt-unknown
[14:00:22 ERROR]: #!#!     Date: unknown
[14:00:22 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[14:00:22 ERROR]: #!#!   Minecraft: 1.19.4
[14:00:22 ERROR]: #!#!   Java: 17.0.4 (OpenJDK 64-Bit Server VM 17.0.4+8-LTS)
[14:00:22 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[14:00:22 ERROR]: #!#!
[14:00:22 ERROR]: #!#! Server platform: Paper
[14:00:22 ERROR]: #!#!
[14:00:22 ERROR]: #!#! Current node: null
[14:00:22 ERROR]: #!#! Current item: null
[14:00:22 ERROR]: #!#!
[14:00:22 ERROR]: #!#! Thread: Server thread
[14:00:22 ERROR]: #!#!
[14:00:22 ERROR]: #!#! Language: english
[14:00:22 ERROR]: #!#! Link parse mode: DISABLED
[14:00:22 ERROR]: #!#!
[14:00:22 ERROR]: #!#! End of Error.
[14:00:22 ERROR]: #!#!
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment]
https://github.com/SkriptLang/Skript/pull/5614

**Comment by sovdeeth** [comment]
> #5614

Related, but it wouldn't solve this issue, unless I'm missing something?
