### ISSUE TITLE
[Skript] Severe Error

### ISSUE THREAD

**Issue by XviEpe** [SkriptLang/Skript#6277]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-365 (MC: 1.20.4)
[Skript] Skript Version: 2.6.4
[Skript] Installed Skript Addons: 
[Skript]  - Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/)
[Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[Skript]  - SkBee v2.18.4 (https://github.com/ShaneBeee/SkBee)
[Skript]  - SharpSK v1.6.3
[Skript] Installed dependencies: 
[Skript]  - Vault v1.7.3-b131
[Skript]  - WorldGuard v7.0.9-beta1+2249-223b80c
```

### Bug Description

What this mean?

```
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! [Skript] Severe Error:
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[17:57:17 ERROR]: #!#! Run /sk update check to get a download link to latest Skript!
[17:57:17 ERROR]: #!#! You will be given instructions how to report this error if it persists after update.
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! Stack trace:
[17:57:17 ERROR]: #!#! java.lang.RuntimeException: Unable to update scoreboard lines
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.fastboard.FastBoardBase.updateLines(FastBoardBase.java:350)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.scoreboard.FastBoardWrapper.updateLines(FastBoardWrapper.java:104)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.scoreboard.FastBoardWrapper.setLine(FastBoardWrapper.java:45)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.elements.scoreboard.expressions.ExprScoreboardLine.change(ExprScoreboardLine.java:93)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[17:57:17 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[17:57:17 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1639)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1518)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1214)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[17:57:17 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[17:57:17 ERROR]: #!#! Caused by: java.lang.IllegalAccessException: Can not set final java.lang.String field net.minecraft.network.protocol.game.PacketPlayOutScoreboardScore.a to java.lang.String
[17:57:17 ERROR]: #!#!     at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
[17:57:17 ERROR]: #!#!     at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
[17:57:17 ERROR]: #!#!     at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:79)
[17:57:17 ERROR]: #!#!     at java.base/java.lang.reflect.Field.set(Field.java:799)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.fastboard.FastBoardBase.setField(FastBoardBase.java:559)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.fastboard.FastBoardBase.sendScorePacket(FastBoardBase.java:475)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.fastboard.FastBoardBase.updateLines(FastBoardBase.java:338)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.scoreboard.FastBoardWrapper.updateLines(FastBoardWrapper.java:104)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.api.scoreboard.FastBoardWrapper.setLine(FastBoardWrapper.java:45)
[17:57:17 ERROR]: #!#!     at SkBee-2.18.4.jar//com.shanebeestudios.skbee.elements.scoreboard.expressions.ExprScoreboardLine.change(ExprScoreboardLine.java:93)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:299)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:57:17 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[17:57:17 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[17:57:17 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1639)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1518)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1214)
[17:57:17 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[17:57:17 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! Version Information:
[17:57:17 ERROR]: #!#!   Skript: 2.6.4 (OUTDATED)
[17:57:17 ERROR]: #!#!     Flavor: skriptlang-github
[17:57:17 ERROR]: #!#!     Date: 17:14:25.041218900
[17:57:17 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[17:57:17 ERROR]: #!#!   Minecraft: 1.20.4
[17:57:17 ERROR]: #!#!   Java: 17.0.9 (OpenJDK 64-Bit Server VM 17.0.9+9)
[17:57:17 ERROR]: #!#!   OS: Linux amd64 4.19.0-24-amd64
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! Server platform: Paper
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! Current node: null
[17:57:17 ERROR]: #!#! Current item: set line [[long:15]] of scoreboard[s] of {_P} (as org.bukkit.entity.Player) to " "
[17:57:17 ERROR]: #!#! Current trigger: function SB (simple event) (scoreboard.sk, line 10)
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! Thread: Server thread
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! Language: english
[17:57:17 ERROR]: #!#! Link parse mode: DISABLED
[17:57:17 ERROR]: #!#! 
[17:57:17 ERROR]: #!#! End of Error.
[17:57:17 ERROR]: #!#!
 ```

### Expected Behavior

I don't know what to do

### Steps to Reproduce

I joined my server

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
This is an SkBee issue, please report it there: https://github.com/ShaneBeee/SkBee/issues

**Comment by XviEpe** [comment]
@sovdeeth Thanks
