### ISSUE TITLE
When I open the anvil gui, an error occurs and it does not open.

### ISSUE THREAD

**Issue by cyclsunmark** [SkriptLang/Skript#6344]
### Skript/Server Version

```markdown
[09:49:51 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[09:49:51 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[09:49:51 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[09:49:51 INFO]: [Skript] Server Version: git-Purpur-2127 (MC: 1.20.4)
[09:49:51 INFO]: [Skript] Skript Version: 2.8.0 (skriptlang-github)
[09:49:51 INFO]: [Skript] Installed Skript Addons:
[09:49:51 INFO]: [Skript]  - PermSk v1.1.1 (https://iplexy.de)
[09:49:51 INFO]: [Skript]  - Skacket v1.1.0
[09:49:51 INFO]: [Skript]  - Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/)
[09:49:51 INFO]: [Skript]  - skript-yaml v1.5
[09:49:51 INFO]: [Skript]  - skript-votifier-hook v1.1.0
[09:49:51 INFO]: [Skript]  - MorkazSk v1.3
[09:49:51 INFO]: [Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[09:49:51 INFO]: [Skript]  - SkBee v3.1.0 (https://github.com/ShaneBeee/SkBee)
[09:49:51 INFO]: [Skript]  - SharpSK v1.6.13
[09:49:51 INFO]: [Skript]  - Skream v2.1 (https://github.com/hapily04/Skream)
[09:49:51 INFO]: [Skript]  - Skript-Packet v2.1.2 (www.github.com/Anarchick/skript-packet)
[09:49:51 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[09:49:51 INFO]: [Skript]  - SkEtcR v4.0
[09:49:51 INFO]: [Skript]  - DiSky v4.12.2-beta1
[09:49:51 INFO]: [Skript]  - skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect)
[09:49:51 INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[09:49:51 INFO]: [Skript]  - SkQuery v4.1.10
[09:49:51 INFO]: [Skript]  - Skript-Paper v1.3.0 (https://github.com/ShaneBeee/Skript-Paper)
[09:49:51 INFO]: [Skript]  - ItemsAdder v3.6.3-beta-9 (devs.beer)
[09:49:51 INFO]: [Skript] Installed dependencies:
[09:49:51 INFO]: [Skript]  - Vault v1.6.1
[09:49:51 INFO]: [Skript]  - WorldGuard v7.0.9+5934e49
```

### Bug Description

1.20.4 server
When I open the anvil gui, an error occurs and it does not open.

### Expected Behavior

error

### Steps to Reproduce

open an anvil with title "상품을 검색해주세요!" to player with left item paper named "검색":

### Errors or Screenshots

[09:46:42 ERROR]: Could not pass event InventoryClickEvent to Skript v2.8.0
java.lang.NoClassDefFoundError: Could not initialize class net.wesjd.anvilgui.AnvilGUI
        at net.wesjd.anvilgui.AnvilGUI$Builder.<init>(AnvilGUI.java:385) ~[Skacket-1.1.0.jar:?]
        at me.limeglass.skacket.elements.sections.SecOpenAnvil.walk(SecOpenAnvil.java:98) ~[Skacket-1.1.0.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[Skript.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:155) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler.lambda$check$4(SkriptEventHandler.java:166) ~[Skript.jar:?]
        at ch.njol.skript.util.Task.callSync(Task.java:164) ~[Skript.jar:?]
        at ch.njol.skript.util.Task.callSync(Task.java:148) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:164) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66) ~[Skript.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2127]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3193) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1486) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1463) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1386) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1364) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1254) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: AnvilGUI does not support server version "1_20_R3" [in thread "Server thread"]
        at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:32) ~[Skacket-1.1.0.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:43) ~[Skacket-1.1.0.jar:?]
        ... 33 more
[09:46:42 ERROR]: Could not pass event InventoryClickEvent to Skript v2.8.0
java.lang.NoClassDefFoundError: Could not initialize class net.wesjd.anvilgui.AnvilGUI
        at net.wesjd.anvilgui.AnvilGUI$Builder.<init>(AnvilGUI.java:385) ~[Skacket-1.1.0.jar:?]
        at me.limeglass.skacket.elements.sections.SecOpenAnvil.walk(SecOpenAnvil.java:98) ~[Skacket-1.1.0.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[Skript.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:155) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler.lambda$check$4(SkriptEventHandler.java:166) ~[Skript.jar:?]
        at ch.njol.skript.util.Task.callSync(Task.java:164) ~[Skript.jar:?]
        at ch.njol.skript.util.Task.callSync(Task.java:148) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:164) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53) ~[Skript.jar:?]
        at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66) ~[Skript.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2127]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3193) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1486) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1463) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1386) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1364) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1254) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: AnvilGUI does not support server version "1_20_R3" [in thread "Server thread"]
        at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:32) ~[Skacket-1.1.0.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:43) ~[Skacket-1.1.0.jar:?]
        ... 33 more

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by cyclsunmark** [comment]
Could this be a skript error?

**Comment by DelayedGaming** [comment]
The error comes from one of the addon you use, which is Skacket. You should report it in Skacket's issue tracker.
