### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by rafalpro1209** [SkriptLang/Skript#6350]
### Skript/Server Version

```markdown
[22:28:34 INFO]: [Skript] Aliasy Skripta mogą zostać znalezione tutaj: https://github.com/SkriptLang/skript-aliases
[22:28:34 INFO]: [Skript] Dokumentację Skripta można znaleźć tutaj: https://skriptlang.github.io/Skript
[22:28:34 INFO]: [Skript] Poradniki do Skripta można znaleźć tutaj: https://docs.skriptlang.org/tutorials
[22:28:34 INFO]: [Skript] Wersja serwera: git-Paper-389 (MC: 1.20.4)
[22:28:34 INFO]: [Skript] Wersja Skripta: 2.8.0 (skriptlang-github)
[22:28:34 INFO]: [Skript] Zainstalowane dodatki do Skripta: None
[22:28:34 INFO]: [Skript] Zainstalowane zależności: 
[22:28:34 INFO]: [Skript]  - WorldGuard v7.0.9+5934e49

EN

[22:28:34 INFO]: [Skript] Skript aliases can be found here: https://github.com/SkriptLang/skript-aliases
[22:28:34 INFO]: [Skript] Skript documentation can be found here: https://skriptlang.github.io/Skript
[22:28:34 INFO]: [Skript] Skript tutorials can be found here: https://docs.skriptlang.org/tutorials
[22:28:34 INFO]: [Skript] Server version: git-Paper-389 (MC: 1.20.4)
[22:28:34 INFO]: [Skript] Skript version: 2.8.0 (skriptlang-github)
[22:28:34 INFO]: [Skript] Installed Skript add-ons: None
[22:28:34 INFO]: [Skript] Installed dependencies:
[22:28:34 INFO]: [Skript] - WorldGuard v7.0.9+5934e49
```

### Bug Description

[22:24:15 ERROR]: #!#!
[22:24:15 ERROR]: #!#! [Skript] Severe Error:
[22:24:15 ERROR]: #!#!
[22:24:15 ERROR]: #!#! Something went horribly wrong with Skript.
[22:24:15 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:24:15 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[22:24:15 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[22:24:15 ERROR]: #!#!
[22:24:15 ERROR]: #!#! Stack trace:
[22:24:15 ERROR]: #!#! java.lang.IllegalStateException: zip file closed
[22:24:15 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:840)
[22:24:15 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:339)
[22:24:15 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:517)
[22:24:15 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:472)
[22:24:15 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[22:24:15 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[22:24:15 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[22:24:15 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[22:24:15 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[22:24:15 ERROR]: #!#!     at Skript.jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)
[22:24:15 ERROR]: #!#!     at com.google.gson.Gson.getAdapter(Gson.java:556)
[22:24:15 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:834)
[22:24:15 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:812)
[22:24:15 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:759)
[22:24:15 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:736)
[22:24:15 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:79)
[22:24:15 ERROR]: #!#!     at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:12)
[22:24:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3298)
[22:24:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3286)
[22:24:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3266)
[22:24:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:154)
[22:24:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffMessage.execute(EffMessage.java:128)
[22:24:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[22:24:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[22:24:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[22:24:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[22:24:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:316)
[22:24:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:275)
[22:24:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:286)
[22:24:15 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:221)
[22:24:15 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:24:15 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[22:24:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987)
[22:24:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[22:24:15 ERROR]: #!#!     at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[22:24:15 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:32)
[22:24:15 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[22:24:15 ERROR]: #!#!     at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)
[22:24:15 ERROR]: #!#!     at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
[22:24:15 ERROR]: #!#!     at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:101)
[22:24:15 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:435)
[22:24:15 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336)
[22:24:15 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323)
[22:24:15 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2236)
[22:24:15 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$16(PlayerConnection.java:2196)
[22:24:15 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[22:24:15 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[22:24:15 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:24:15 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[22:24:15 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[22:24:15 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1452)
[22:24:15 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[22:24:15 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[22:24:15 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1429)
[22:24:15 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1352)
[22:24:15 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[22:24:15 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1330)
[22:24:15 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1220)
[22:24:15 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[22:24:15 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[22:24:15 ERROR]: #!#!
[22:24:15 ERROR]: #!#! Version Information:
[22:24:15 ERROR]: #!#!   Skript: 2.8.0 (latest)
[22:24:15 ERROR]: #!#!     Flavor: skriptlang-github
[22:24:15 ERROR]: #!#!     Date: 18:20:11.223179900
[22:24:15 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[22:24:15 ERROR]: #!#!   Minecraft: 1.20.4
[22:24:15 ERROR]: #!#!   Java: 17.0.9 (OpenJDK 64-Bit Server VM 17.0.9+9)
[22:24:15 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[22:24:15 ERROR]: #!#!
[22:24:15 ERROR]: #!#! Server platform: Paper
[22:24:15 ERROR]: #!#!
[22:24:15 ERROR]: #!#! Current node: null
[22:24:15 ERROR]: #!#! Current item: send "§8[§4AC§8]§r §7%the player%§8: §f%the 1st argument%" to loop-player
[22:24:15 ERROR]: #!#! Current trigger: command /ac (simple event) (adminchat.sk, line 14)
[22:24:15 ERROR]: #!#!
[22:24:15 ERROR]: #!#! Thread: Server thread
[22:24:15 ERROR]: #!#!
[22:24:15 ERROR]: #!#! Language: polish
[22:24:15 ERROR]: #!#! Link parse mode: DISABLED
[22:24:15 ERROR]: #!#!
[22:24:15 ERROR]: #!#! End of Error.
[22:24:15 ERROR]: #!#!

### Expected Behavior

should write to admin chat

### Steps to Reproduce

it happened immediately after uploading

### Agreement

- [ ] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Have you used /reload or plugman at any time recently?
Does this error persist after a restart?

**Comment by rafalpro1209** [comment]
once with reload and 2nd time with plugman

**Comment by rafalpro1209** [comment]
after a full restart it works

**Comment by sovdeeth** [comment]
> once with reload and 2nd time with plugman

These break Skript and should never be used.
