### ISSUE TITLE
Skript-Reflect having issues

### ISSUE THREAD

**Issue by C0D3-M4513R** [SkriptLang/Skript#6353]
### Skript/Server Version

Ketting is on a dev branch. This exact version is unreleased.
The exact commit is: https://github.com/kettingpowered/Ketting-1-20-x/pull/62/commits/12c6a0ec6a0e6c87265de6b3502e2bb6fa23d8f8

```
[23:10:17] [Server thread/INFO] [/]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[23:10:17] [Server thread/INFO] [/]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[23:10:17] [Server thread/INFO] [/]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[23:10:17] [Server thread/INFO] [/]: [Skript] Server Version: git-ketting-1.20.1-0.0.1 (MC: 1.20.1)
[23:10:17] [Server thread/INFO] [/]: [Skript] Skript Version: 2.8.0 (skriptlang-github)
[23:10:17] [Server thread/INFO] [/]: [Skript] Installed Skript Addons: 
[23:10:17] [Server thread/INFO] [/]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[23:10:17] [Server thread/INFO] [/]: [Skript]  - SkArclight v1.0.0 (https://github.com/ShaneBeee/SkArclight)
[23:10:17] [Server thread/INFO] [/]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[23:10:17] [Server thread/INFO] [/]: [Skript]  - skript-db v1.3.9
[23:10:17] [Server thread/INFO] [/]: [Skript]  - SkBee v3.0.1 (https://github.com/ShaneBeee/SkBee)
[23:10:17] [Server thread/INFO] [/]: [Skript] Installed dependencies: 
[23:10:17] [Server thread/INFO] [/]: [Skript]  - Vault v1.7.3-b131
[23:10:17] [Server thread/INFO] [/]: [Skript]  - WorldGuard v7.0.9+5934e49
```

### Bug Description

```
[23:09:19] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling skript-reflect v2.3 (Is it up to date?)
java.lang.NoSuchFieldError: c
        at com.btk5h.skriptmirror.skript.custom.condition.CustomConditionSection.lambda$static$0(CustomConditionSection.java:54) ~[?:?] {}
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {}
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) ~[?:?] {}
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:?] {}
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:?] {}
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:?] {}
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:?] {}
        at com.btk5h.skriptmirror.skript.custom.condition.CustomConditionSection.<clinit>(CustomConditionSection.java:55) ~[?:?] {}
        at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
        at java.lang.Class.forName(Unknown Source) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
        at org.kettingpowered.ketting.remapper.generated.KettingReflectionHandler_24.redirectClassForName(KettingReflectionHandler.java:236) ~[forge-1.20.1-47.2.0-0.0.1-universal.jar!/:?] {}
        at ch.njol.skript.util.Utils.getClasses(Utils.java:201) ~[?:?] {}
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:82) ~[?:?] {}
        at com.btk5h.skriptmirror.SkriptMirror.onEnable(SkriptMirror.java:60) ~[?:?] {}
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[forge-1.20.1-47.2.0-0.0.1-universal.jar!/:?] {re:mixin,re:classloading,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[forge-1.20.1-47.2.0-0.0.1-universal.jar!/:?] {re:classloading,re:mixin}
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:481) ~[forge-1.20.1-47.2.0-0.0.1-universal.jar!/:?] {re:classloading,re:mixin}
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:572) ~[forge-1.20.1-47.2.0-0.0.1-universal.jar!/:?] {re:classloading,re:mixin,re:mixin,re:mixin,re:mixin}
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:440) ~[forge-1.20.1-47.2.0-0.0.1-universal.jar!/:?] {re:classloading,re:mixin,re:mixin,re:mixin,re:mixin}
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:369) ~[forge-1.20.1-47.2.0-0.0.1-server.jar!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:243) ~[forge-1.20.1-47.2.0-0.0.1-server.jar!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:811) ~[forge-1.20.1-47.2.0-0.0.1-server.jar!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:269) ~[forge-1.20.1-47.2.0-0.0.1-server.jar!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}

```

### Expected Behavior

no exception

### Steps to Reproduce

Install listed plugins and start under Ketting 1.20.1.

### Other

![image](https://github.com/SkriptLang/Skript/assets/28912031/43643175-5ad2-406b-a3dc-b9b1da579870)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Please use the latest version of skript-reflect.

**Comment by C0D3-M4513R** [comment]
This is the latest on Spigot

**Comment by C0D3-M4513R** [comment]
![image](https://github.com/SkriptLang/Skript/assets/28912031/eeb09eaf-0f26-44b2-84a1-84dbe85fad64)

**Comment by sovdeeth** [comment]
> This is the latest on Spigot

Download it from the skript-reflect github, the Spigot version is not currently updated due to the recent ownership changes.
