### ISSUE TITLE
Error when closing server

### ISSUE THREAD

**Issue by ffddf111** [SkriptLang/Skript#6409]
### Skript/Server Version

```markdown
[17:07:16 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[17:07:16 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[17:07:16 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[17:07:16 INFO]: [Skript] Server Version: git-Purpur-2136 (MC: 1.20.4)
[17:07:16 INFO]: [Skript] Skript Version: 2.8.1 (skriptlang-github)
[17:07:16 INFO]: [Skript] Installed Skript Addons:
[17:07:16 INFO]: [Skript]  - PermSk v1.1.1 (https://iplexy.de)
[17:07:16 INFO]: [Skript]  - Skellett v2.0.9 (https://forums.skunity.com/resources/skellett.24/)
[17:07:16 INFO]: [Skript]  - skript-yaml v1.5
[17:07:16 INFO]: [Skript]  - skript-votifier-hook v1.1.0
[17:07:16 INFO]: [Skript]  - MorkazSk v1.3
[17:07:16 INFO]: [Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[17:07:16 INFO]: [Skript]  - SkBee v3.2.1 (https://github.com/ShaneBeee/SkBee)
[17:07:16 INFO]: [Skript]  - SharpSK v1.6.13
[17:07:16 INFO]: [Skript]  - Skream v2.1 (https://github.com/hapily04/Skream)
[17:07:16 INFO]: [Skript]  - Skript-Packet v2.1.2 (www.github.com/Anarchick/skript-packet)
[17:07:16 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[17:07:16 INFO]: [Skript]  - SkEtcR v4.0
[17:07:16 INFO]: [Skript]  - DiSky v4.12.2-beta1
[17:07:16 INFO]: [Skript]  - skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect)
[17:07:16 INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[17:07:16 INFO]: [Skript]  - SkQuery v4.1.10
[17:07:16 INFO]: [Skript]  - Skript-Paper v1.3.0 (https://github.com/ShaneBeee/Skript-Paper)
[17:07:16 INFO]: [Skript]  - ItemsAdder v3.6.3-beta-12 (devs.beer)
[17:07:16 INFO]: [Skript] Installed dependencies:
[17:07:16 INFO]: [Skript]  - Vault v1.6.1
[17:07:16 INFO]: [Skript]  - WorldGuard v7.0.9+5934e49
```

### Bug Description

This is what appears when you close the server.

### Expected Behavior

There should be no errors

### Steps to Reproduce

Enter skript-reflect, open the server, then close the server.

### Errors or Screenshots

[16:59:00] [Server thread/INFO]: [skript-reflect] Disabling skript-reflect v2.4
[16:59:00] [Server thread/ERROR]: Could not pass event PluginDisableEvent to Skript v2.8.1
java.lang.NullPointerException: Cannot invoke "java.util.Map.remove(Object)" because "syntaxes" is null
	at org.skriptlang.reflect.syntax.CustomSyntaxStructure.lambda$unload$1(CustomSyntaxStructure.java:158) ~[skript-reflect.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.skriptlang.reflect.syntax.CustomSyntaxStructure.unload(CustomSyntaxStructure.java:153) ~[skript-reflect.jar:?]
	at ch.njol.skript.ScriptLoader.unloadScripts(ScriptLoader.java:830) ~[Skript.jar:?]
	at ch.njol.skript.Skript.beforeDisable(Skript.java:1192) ~[Skript.jar:?]
	at ch.njol.skript.Skript.onPluginDisable(Skript.java:1126) ~[Skript.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor313.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2136]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2136]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2136]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:221) ~[purpur-1.20.4.jar:git-Purpur-2136]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:147) ~[purpur-1.20.4.jar:git-Purpur-2136]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[purpur-1.20.4.jar:git-Purpur-2136]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.disablePlugins(CraftServer.java:582) ~[purpur-1.20.4.jar:git-Purpur-2136]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:986) ~[purpur-1.20.4.jar:git-Purpur-2136]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:861) ~[purpur-1.20.4.jar:git-Purpur-2136]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1288) ~[purpur-1.20.4.jar:git-Purpur-2136]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2136]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

### Other

Besides that, there are other addons that do that.
What could be the problem?

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Please always make sure this is actually a Skript bug by testing without addons. I believe this is a skript-reflect bug. See https://github.com/SkriptLang/skript-reflect/issues/86. 
Let us know if it persists without addons.

**Comment by sovdeeth** [comment]
Closing due to no response.
