### ISSUE TITLE
my ram is running out very quick, i don't know if this is why but it might be

### ISSUE THREAD

**Issue by s3vens** [SkriptLang/Skript#6458]
### Skript/Server Version

```markdown
[13:58:21 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[13:58:21 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[13:58:21 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[13:58:21 INFO]: [Skript] Server Version: git-Paper-550 (MC: 1.19.4)
[13:58:21 INFO]: [Skript] Skript Version: 2.8.2 (skriptlang-github)
[13:58:21 INFO]: [Skript] Installed Skript Addons: None
[13:58:21 INFO]: [Skript] Installed dependencies: 
[13:58:21 INFO]: [Skript]  - Vault v1.7.3-b131
[13:58:21 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

[13:53:07 ERROR]: #!#! [Skript] Severe Error:
[13:53:07 ERROR]: #!#! 
[13:53:07 ERROR]: #!#! Something went horribly wrong with Skript.
[13:53:07 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:53:07 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[13:53:07 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[13:53:07 ERROR]: #!#! 
[13:53:07 ERROR]: #!#! Stack trace:
[13:53:07 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.Inventory.getItem(int)" because "this.invi" is null
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.slot.InventorySlot.getItem(InventorySlot.java:79)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.classes.data.DefaultComparators$4.compare(DefaultComparators.java:143)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.classes.data.DefaultComparators$4.compare(DefaultComparators.java:140)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.conditions.CondCompare.lambda$check$1(CondCompare.java:351)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:162)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:150)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:145)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.conditions.CondCompare.lambda$check$2(CondCompare.java:349)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:162)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:150)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.conditions.CondCompare.check(CondCompare.java:348)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecConditional.lambda$checkConditions$1(SecConditional.java:384)
[13:53:07 ERROR]: #!#!     at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[13:53:07 ERROR]: #!#!     at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
[13:53:07 ERROR]: #!#!     at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[13:53:07 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[13:53:07 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[13:53:07 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[13:53:07 ERROR]: #!#!     at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[13:53:07 ERROR]: #!#!     at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[13:53:07 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[13:53:07 ERROR]: #!#!     at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecConditional.checkConditions(SecConditional.java:384)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.sections.SecConditional.walk(SecConditional.java:286)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:155)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.lambda$check$4(SkriptEventHandler.java:166)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:164)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[13:53:07 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66)
[13:53:07 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[13:53:07 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:53:07 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[13:53:07 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[13:53:07 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[13:53:07 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3196)
[13:53:07 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[13:53:07 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[13:53:07 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[13:53:07 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:53:07 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:53:07 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:53:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1342)
[13:53:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[13:53:07 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[13:53:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1319)
[13:53:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1312)
[13:53:07 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[13:53:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1290)
[13:53:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1178)
[13:53:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[13:53:07 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[13:53:07 ERROR]: #!#! 
[13:53:07 ERROR]: #!#! Version Information:
[13:53:07 ERROR]: #!#!   Skript: 2.8.2
[13:53:07 ERROR]: #!#!     Flavor: skriptlang-github
[13:53:07 ERROR]: #!#!     Date: 12:36:18.989662200
[13:53:07 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[13:53:07 ERROR]: #!#!   Minecraft: 1.19.4
[13:53:07 ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[13:53:07 ERROR]: #!#!   OS: Linux amd64 6.2.0-36-generic
[13:53:07 ERROR]: #!#! 
[13:53:07 ERROR]: #!#! Server platform: Paper
[13:53:07 ERROR]: #!#! 
[13:53:07 ERROR]: #!#! Current node: null
[13:53:07 ERROR]: #!#! Current item: if event-slot is equal to [[itemtype:nether star]] named "?c?lNether" (comparator: ch.njol.skript.classes.data.DefaultComparators$4@1a4cc87d)
[13:53:07 ERROR]: #!#! Current trigger: inventory click (dispense/spawn/drop/craft/pickup/consume/break/despawn/merge/move/stonecutting) (warp.sk, line 13)
[13:53:07 ERROR]: #!#! 
[13:53:07 ERROR]: #!#! Thread: Server thread
[13:53:07 ERROR]: #!#! 
[13:53:07 ERROR]: #!#! Language: english
[13:53:07 ERROR]: #!#! Link parse mode: DISABLED
[13:53:07 ERROR]: #!#! 
[13:53:07 ERROR]: #!#! End of Error.
[13:53:07 ERROR]: #!#! 

### Expected Behavior

i dont know

### Steps to Reproduce

nothing, it just happened

### Errors or Screenshots

nope

### Other

nope

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
As @Romitou mentioned in #6554, this is due to getClickedInventory returning null when clicking outside the inventory
https://github.com/SkriptLang/Skript/blob/4d4094486fd0fc21771f86e30b20104262f6b5f1/src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java#L1124-L1133

**Comment by Blizzmond** [comment]
What would the fix be to fix the error?

**Comment by sovdeeth** [comment]
Adding a check for null

**Comment by Blizzmond** [comment]
im not sure where in my code this error is occuring though

> Adding a check for null

**Comment by sovdeeth** [comment]
It's not something you can fix in your scripts, afaik.

**Comment by Blizzmond** [comment]
will it be fixed?

**Comment by sovdeeth** [comment]
Sure, when someone makes a PR, it's open to anyone who wants to fix it!
