### ISSUE TITLE
BUg report

### ISSUE THREAD

**Issue by Itzgamer5454** [SkriptLang/Skript#6509]
### Skript/Server Version

```markdown
N/A
```

### Bug Description

[20:20:15 ERROR]: #!#! 
[20:20:15 ERROR]: #!#! [Skript] Severe Error:
[20:20:15 ERROR]: #!#! 
[20:20:15 ERROR]: #!#! Something went horribly wrong with Skript.
[20:20:15 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:20:15 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[20:20:15 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[20:20:15 ERROR]: #!#! 
[20:20:15 ERROR]: #!#! Stack trace:
[20:20:15 ERROR]: #!#! java.lang.NullPointerException: Profile name must not be null
[20:20:15 ERROR]: #!#!     at java.base/java.util.Objects.requireNonNull(Objects.java:233)
[20:20:15 ERROR]: #!#!     at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31)
[20:20:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaSkull.setOwningPlayer(CraftMetaSkull.java:246)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.expressions.ExprSkull.convert(ExprSkull.java:70)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.expressions.ExprSkull.convert(ExprSkull.java:40)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//org.skriptlang.skript.lang.converter.Converters.convert(Converters.java:501)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//org.skriptlang.skript.lang.converter.Converters.convertUnsafe(Converters.java:565)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:203)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:119)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.expressions.base.SimplePropertyExpression.get(SimplePropertyExpression.java:56)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:88)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:94)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:88)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:94)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:88)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:94)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[20:20:15 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.effects.Delay.lambda$walk$0(Delay.java:107)
[20:20:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[20:20:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[20:20:15 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1679)
[20:20:15 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[20:20:15 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1558)
[20:20:15 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1246)
[20:20:15 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[20:20:15 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[20:20:15 ERROR]: #!#! 
[20:20:15 ERROR]: #!#! Version Information:
[20:20:15 ERROR]: #!#!   Skript: 2.8.3 (latest)
[20:20:15 ERROR]: #!#!     Flavor: skriptlang-github
[20:20:15 ERROR]: #!#!     Date: 16:23:04.254419600
[20:20:15 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[20:20:15 ERROR]: #!#!   Minecraft: 1.20.4
[20:20:15 ERROR]: #!#!   Java: 17.0.7 (Java HotSpot(TM) 64-Bit Server VM 17.0.7+8-LTS-jvmci-22.3-b15)
[20:20:15 ERROR]: #!#!   OS: Linux amd64 5.15.0-25-generic
[20:20:15 ERROR]: #!#! 
[20:20:15 ERROR]: #!#! Server platform: Paper
[20:20:15 ERROR]: #!#! 
[20:20:15 ERROR]: #!#! Current node: null
[20:20:15 ERROR]: #!#! Current item: set slots {_a} (as java.lang.Number) of {_gui} (as org.bukkit.inventory.Inventory) to skull of "%{_player} (as java.lang.Object)%" parsed as a offline player named "§f%{_player}%" with lore "§x§9§6§f§8§1§1Bounty: §x§f§8§3§e§1§1$%regex({bounty::%{_u} (as java.lang.Object)%} (as java.lang.Object))%"
[20:20:15 ERROR]: #!#! Current trigger: function page (simple event) (Bounty.sk, line 76)
[20:20:15 ERROR]: #!#! 
[20:20:15 ERROR]: #!#! Thread: Server thread
[20:20:15 ERROR]: #!#! 
[20:20:15 ERROR]: #!#! Language: english
[20:20:15 ERROR]: #!#! Link parse mode: DISABLED
[20:20:15 ERROR]: #!#! 
[20:20:15 ERROR]: #!#! End of Error.
[20:20:15 ERROR]: #!#! 
[20:20:16 INFO]: MIDPlayer2000 issued server command: /bounties
[20:20:16 ERROR]: #!#! 
[20:20:16 ERROR]: #!#! [Skript] Severe Error:
[20:20:16 ERROR]: #!#! 
[20:20:16 ERROR]: #!#! Something went horribly wrong with Skript.
[20:20:16 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:20:16 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[20:20:16 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[20:20:16 ERROR]: #!#! 
[20:20:16 ERROR]: #!#! Stack trace:
[20:20:16 ERROR]: #!#! java.lang.NullPointerException: Profile name must not be null
[20:20:16 ERROR]: #!#!     at java.base/java.util.Objects.requireNonNull(Objects.java:233)
[20:20:16 ERROR]: #!#!     at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31)
[20:20:16 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaSkull.setOwningPlayer(CraftMetaSkull.java:246)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.expressions.ExprSkull.convert(ExprSkull.java:70)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.expressions.ExprSkull.convert(ExprSkull.java:40)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//org.skriptlang.skript.lang.converter.Converters.convert(Converters.java:501)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//org.skriptlang.skript.lang.converter.Converters.convertUnsafe(Converters.java:565)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:203)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:119)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.expressions.base.SimplePropertyExpression.get(SimplePropertyExpression.java:56)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:88)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:94)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:88)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:94)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:88)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:94)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[20:20:16 ERROR]: #!#!     at Skript (1).jar//ch.njol.skript.effects.Delay.lambda$walk$0(Delay.java:107)
[20:20:16 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[20:20:16 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[20:20:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1679)
[20:20:16 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[20:20:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1558)
[20:20:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1246)
[20:20:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[20:20:16 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[20:20:16 ERROR]: #!#! 
[20:20:16 ERROR]: #!#! Version Information:
[20:20:16 ERROR]: #!#!   Skript: 2.8.3 (latest)
[20:20:16 ERROR]: #!#!     Flavor: skriptlang-github
[20:20:16 ERROR]: #!#!     Date: 16:23:04.254419600
[20:20:16 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[20:20:16 ERROR]: #!#!   Minecraft: 1.20.4
[20:20:16 ERROR]: #!#!   Java: 17.0.7 (Java HotSpot(TM) 64-Bit Server VM 17.0.7+8-LTS-jvmci-22.3-b15)
[20:20:16 ERROR]: #!#!   OS: Linux amd64 5.15.0-25-generic
[20:20:16 ERROR]: #!#! 
[20:20:16 ERROR]: #!#! Server platform: Paper
[20:20:16 ERROR]: #!#! 
[20:20:16 ERROR]: #!#! Current node: null
[20:20:16 ERROR]: #!#! Current item: set slots {_a} (as java.lang.Number) of {_gui} (as org.bukkit.inventory.Inventory) to skull of "%{_player} (as java.lang.Object)%" parsed as a offline player named "§f%{_player}%" with lore "§x§9§6§f§8§1§1Bounty: §x§f§8§3§e§1§1$%regex({bounty::%{_u} (as java.lang.Object)%} (as java.lang.Object))%"
[20:20:16 ERROR]: #!#! Current trigger: function page (simple event) (Bounty.sk, line 76)
[20:20:16 ERROR]: #!#! 
[20:20:16 ERROR]: #!#! Thread: Server thread
[20:20:16 ERROR]: #!#! 
[20:20:16 ERROR]: #!#! Language: english
[20:20:16 ERROR]: #!#! Link parse mode: DISABLED
[20:20:16 ERROR]: #!#! 
[20:20:16 ERROR]: #!#! End of Error.
[20:20:16 ERROR]: #!#! 

### Expected Behavior

N/A

### Steps to Reproduce

N/A

### Errors or Screenshots

N/A

### Other

N/A

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by EquipableMC** [comment]
Would be nice if we had some code to go based off of, along with your /sk info

**Comment by Fusezion** [comment]
Issue stems from ExprSkull, line 70 which is `SkullMeta#setOwningPlayer(OfflinePlayer)` however I'm not sure how it's becoming a null pointer as I don't know anyway a `SimplePropertyExpression#convert()` object can be null the class itself needs recoded tho as it's expecting an Object instead of an Offlineplayer

**Comment by EquipableMC** [comment]
> Issue stems from ExprSkull, line 70 which is `SkullMeta#setOwningPlayer(OfflinePlayer)` however I'm not sure how it's becoming a null pointer as I don't know anyway a `SimplePropertyExpression#convert()` object can be null the class itself needs recoded tho as it's expecting an Object instead of an Offlineplayer 

It would still be nice if we had his /sk info to see if it could potentially be another skript addon causing it, right?

**Comment by sovdeeth** [comment]
Yes, @Itzgamer5454, please provide us with your `/sk info` information as well as the code you used to cause this issue, so we can replicate it.

**Comment by TheLimeGlass** [comment]
Is your server in offline mode? And were you running the server locally with no internet?

**Comment by sovdeeth** [comment]
Closing due to no response.
