### ISSUE TITLE
Internal error when running command. Console

### ISSUE THREAD

**Issue by Valocai** [SkriptLang/Skript#6515]
### Skript/Server Version

```markdown
[01:24:45 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[01:24:45 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[01:24:45 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[01:24:45 INFO]: [Skript] Server Version: git-Paper-462 (MC: 1.20.4)
[01:24:45 INFO]: [Skript] Skript Version: 2.8.3 (skriptlang-github)
[01:24:45 INFO]: [Skript] Installed Skript Addons: None
[01:24:45 INFO]: [Skript] Installed dependencies: 
[01:24:45 INFO]: [Skript]  - Vault v1.7.3-b131
[01:24:45 INFO]: [Skript]  - GriefPrevention v16.18.2
```

### Bug Description

[01:20:49 ERROR]: #!#! 
[01:20:49 ERROR]: #!#! [Skript] Severe Error:
[01:20:49 ERROR]: #!#! 
[01:20:49 ERROR]: #!#! Something went horribly wrong with Skript.
[01:20:49 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[01:20:49 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[01:20:49 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[01:20:49 ERROR]: #!#! 
[01:20:49 ERROR]: #!#! Stack trace:
[01:20:49 ERROR]: #!#! java.lang.IllegalStateException: zip file closed
[01:20:49 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[01:20:49 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[01:20:49 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[01:20:49 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[01:20:49 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[01:20:49 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[01:20:49 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[01:20:49 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[01:20:49 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[01:20:49 ERROR]: #!#!     at Skript.jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)
[01:20:49 ERROR]: #!#!     at com.google.gson.Gson.getAdapter(Gson.java:556)
[01:20:49 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:834)
[01:20:49 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:812)
[01:20:49 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:759)
[01:20:49 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:736)
[01:20:49 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:175)
[01:20:49 ERROR]: #!#!     at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:12)
[01:20:49 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3322)
[01:20:49 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3310)
[01:20:49 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3290)
[01:20:49 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:154)
[01:20:49 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffMessage.execute(EffMessage.java:128)
[01:20:49 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[01:20:49 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[01:20:49 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[01:20:49 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[01:20:49 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:316)
[01:20:49 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:275)
[01:20:49 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:286)
[01:20:49 ERROR]: #!#!     at Skript.jar//ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:221)
[01:20:49 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[01:20:49 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[01:20:49 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999)
[01:20:49 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[01:20:49 ERROR]: #!#!     at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[01:20:49 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:32)
[01:20:49 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[01:20:49 ERROR]: #!#!     at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)
[01:20:49 ERROR]: #!#!     at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
[01:20:49 ERROR]: #!#!     at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:101)
[01:20:49 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:434)
[01:20:49 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336)
[01:20:49 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323)
[01:20:49 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2230)
[01:20:49 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$14(PlayerConnection.java:2190)
[01:20:49 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[01:20:49 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[01:20:49 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:20:49 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[01:20:49 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[01:20:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1465)
[01:20:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[01:20:49 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[01:20:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1442)
[01:20:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1365)
[01:20:49 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[01:20:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1343)
[01:20:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1232)
[01:20:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[01:20:49 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[01:20:49 ERROR]: #!#! 
[01:20:49 ERROR]: #!#! Version Information:
[01:20:49 ERROR]: #!#!   Skript: 2.8.3 (latest)
[01:20:49 ERROR]: #!#!     Flavor: skriptlang-github
[01:20:49 ERROR]: #!#!     Date: 16:23:04.254419600
[01:20:49 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[01:20:49 ERROR]: #!#!   Minecraft: 1.20.4
[01:20:49 ERROR]: #!#!   Java: 18.0.2.1 (OpenJDK 64-Bit Server VM 18.0.2.1+1)
[01:20:49 ERROR]: #!#!   OS: Linux amd64 5.15.0-89-generic
[01:20:49 ERROR]: #!#! 
[01:20:49 ERROR]: #!#! Server platform: Paper
[01:20:49 ERROR]: #!#! 
[01:20:49 ERROR]: #!#! Current node: null
[01:20:49 ERROR]: #!#! Current item: send "Unable to find RTP location" to the player
[01:20:49 ERROR]: #!#! Current trigger: command /wildskript (simple event) (rtp.sk, line 6)
[01:20:49 ERROR]: #!#! 
[01:20:49 ERROR]: #!#! Thread: Server thread
[01:20:49 ERROR]: #!#! 
[01:20:49 ERROR]: #!#! Language: english
[01:20:49 ERROR]: #!#! Link parse mode: DISABLED
[01:20:49 ERROR]: #!#! 
[01:20:49 ERROR]: #!#! End of Error.
[01:20:49 ERROR]: #!#! 

### Expected Behavior

To run the command.

### Steps to Reproduce

Ran this skript `command /wildskript:
	cooldown: 1 seconds
	cooldown message: &4Stop! &cYou can only teleport to a random location every 1 seconds.
	permission: rtp.use
	permission message: &cYou do not have permission to use this command
	trigger:
		set {_x} to round(random number between -5000 and 5000)
		set {_z} to round(random number between -5000 and 5000)
		set {_block} to block at location at ({_x}, 0, {_z}) in world event-world
		loop all blocks above {_block}:
			if loop-block is air:
				block below loop-block is not water
				block below loop-block is not air
				if block above loop-block is air:
					send "&a Attempting teleport"                
					teleport player to loop-block
					send "&aTeleported to a random location" to player
			else:
				send "Unable to find RTP location" to player`

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by bluelhf** [comment]
Skript is breaking because you reloaded it with a plugin manager (like PlugMan) or using `/reload confirm` — please don't!

**Comment by Valocai** [comment]
I done /sk reload

**Comment by AyhamAl-Ali** [comment]
You probably have used `/reload` before that or have used a plugin reloader such as PlugMan, these causes Skript to break. Restarting your server should fix the issue.

**Comment by Valocai** [comment]
Thanks.
