### ISSUE TITLE
NoClassDefFound Error

### ISSUE THREAD

**Issue by TabZz147** [SkriptLang/Skript#6636]
### Skript/Server Version

```markdown
2.8.5
```

### Bug Description

[Skript] Task #120 for Skript v2.8.5 generated an exception
java.lang.NoClassDefFoundError: lib/PatPeter/SQLibrary/Database ...

### Expected Behavior

i dont know

### Steps to Reproduce

i dont know

### Errors or Screenshots

https://paste.gg/p/anonymous/01a7d7acd96b451d8f515ea9dfdbf7b8

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
The paste site seems to be down, can you send the error log here instead.

**Comment by TabZz147** [comment]
09:49:22] [Server thread/WARN]: [Skript] Task #120 for Skript v2.8.5 generated an exception
java.lang.NoClassDefFoundError: lib/PatPeter/SQLibrary/Database
    at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
    at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?]
    at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?]
    at ch.njol.skript.variables.Variables.load(Variables.java:239) ~[Skript-2.8.5.jar:?]
    at ch.njol.skript.Skript$1.run(Skript.java:643) ~[Skript-2.8.5.jar:?]
    at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
    at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-496]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.4.jar:git-Paper-496]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
    at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: lib.PatPeter.SQLibrary.Database
    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
    ... 11 more

**Comment by Moderocky** [comment]
It looks like you're trying to use the old SQL database variables hook without the dependency it says you need.
