### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LeLStudio** [SkriptLang/Skript#6705]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here:
https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here:
https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here:
https://docs.skriptlang.org/tutorials
[
Skript] Server Version: git-Paper-408 (MC: L17.0
[Skript] Skript Version: 2.8.5 (skriptlang-github)
[Skript
] Installed Skript Addons: None
[
Skript] Installed dependencies:
[Skript] Vault v1.7.3-6131
[
Skript] - WorldGuard v7.0.5+3827266
```

### Bug Description

no work

### Expected Behavior

work plugin

### Steps to Reproduce

I`m load the plugin

### Errors or Screenshots

[19:17:29 ERROR]: #!#! 
[19:17:29 ERROR]: #!#! [Skript] Severe Error:
[19:17:29 ERROR]: #!#! 
[19:17:29 ERROR]: #!#! Something went horribly wrong with Skript.
[19:17:29 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[19:17:29 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[19:17:29 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[19:17:29 ERROR]: #!#! 
[19:17:29 ERROR]: #!#! Stack trace:
[19:17:29 ERROR]: #!#! java.lang.IllegalStateException: zip file closed
[19:17:29 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:840)
[19:17:29 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:339)
[19:17:29 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:517)
[19:17:29 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:472)
[19:17:29 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
[19:17:29 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[19:17:29 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[19:17:29 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[19:17:29 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5.jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)
[19:17:29 ERROR]: #!#!     at com.google.gson.Gson.getAdapter(Gson.java:458)
[19:17:29 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:696)
[19:17:29 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:683)
[19:17:29 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:638)
[19:17:29 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:618)
[19:17:29 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:79)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//net.kyori.adventure.text.serializer.bungeecord.BungeeComponentSerializer.deserialize(BungeeComponentSerializer.java:142)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.expressions.ExprChestInventory.get(ExprChestInventory.java:107)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.expressions.ExprChestInventory.get(ExprChestInventory.java:46)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:94)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:316)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:275)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:286)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:221)
[19:17:29 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:17:29 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[19:17:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[19:17:29 ERROR]: #!#!     at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:841)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.Skript.dispatchCommand(Skript.java:1551)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.effects.EffCommand.execute(EffCommand.java:102)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:316)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:275)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:286)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:221)
[19:17:29 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:17:29 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[19:17:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[19:17:29 ERROR]: #!#!     at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:841)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.Skript.dispatchCommand(Skript.java:1551)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.effects.EffCommand.execute(EffCommand.java:102)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:316)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:275)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:286)
[19:17:29 ERROR]: #!#!     at Skript-2.8.5 (1).jar//ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:221)
[19:17:29 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:17:29 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[19:17:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[19:17:29 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2262)
[19:17:29 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2073)
[19:17:29 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2054)
[19:17:29 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[19:17:29 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[19:17:29 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[19:17:29 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:17:29 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[19:17:29 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[19:17:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[19:17:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[19:17:29 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[19:17:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[19:17:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[19:17:29 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[19:17:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
[19:17:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
[19:17:29 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[19:17:29 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[19:17:29 ERROR]: #!#! 
[19:17:29 ERROR]: #!#! Version Information:
[19:17:29 ERROR]: #!#!   Skript: 2.8.5 (latest)
[19:17:29 ERROR]: #!#!     Flavor: skriptlang-github
[19:17:29 ERROR]: #!#!     Date: 16:49:26.326703600
[19:17:29 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[19:17:29 ERROR]: #!#!   Minecraft: 1.17.1
[19:17:29 ERROR]: #!#!   Java: 17.0.11 (OpenJDK 64-Bit Server VM 17.0.11+9)
[19:17:29 ERROR]: #!#!   OS: Linux amd64 5.10.0-26-amd64
[19:17:29 ERROR]: #!#! 
[19:17:29 ERROR]: #!#! Server platform: Paper
[19:17:29 ERROR]: #!#! 
[19:17:29 ERROR]: #!#! Current node: null
[19:17:29 ERROR]: #!#! Current item: set {_inv} (as java.lang.Object) to chest inventory named "Дон-маркет [0/0]" with [[long:5]]
[19:17:29 ERROR]: #!#! Current trigger: command /dm (simple event) (-examples/dmarket_2.sk, line 777)
[19:17:29 ERROR]: #!#! 
[19:17:29 ERROR]: #!#! Thread: Server thread
[19:17:29 ERROR]: #!#! 
[19:17:29 ERROR]: #!#! Language: english
[19:17:29 ERROR]: #!#! Link parse mode: DISABLED
[19:17:29 ERROR]: #!#! 
[19:17:29 ERROR]: #!#! End of Error.
[19:17:29 ERROR]: #!#! 

### Other

no

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Don't use /reload or Plugman to reload Skript.
