### ISSUE TITLE
Skript Error

### ISSUE THREAD

**Issue by ErrorHunter1** [SkriptLang/Skript#6731]
### Skript/Server Version

```markdown
[13:56:04 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[13:56:04 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[13:56:04 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[13:56:04 INFO]: [Skript] Server Version: 1.20.6-112-347bbe3 (MC: 1.20.6)
[13:56:04 INFO]: [Skript] Skript Version: 2.8.5 (skriptlang-github)
[13:56:04 INFO]: [Skript] Installed Skript Addons: None
[13:56:04 INFO]: [Skript] Installed dependencies: 
[13:56:04 INFO]: [Skript]  - Vault v1.7.3-b131
[13:56:04 INFO]: [Skript]  - WorldGuard v7.0.10+d9424b1
```

### Bug Description

[13:52:32 ERROR]: #!#! 
[13:52:32 ERROR]: #!#! [Skript] Severe Error:
[13:52:32 ERROR]: #!#! Exception initializing hook: ch.njol.skript.hooks.VaultHook
[13:52:32 ERROR]: #!#! 
[13:52:32 ERROR]: #!#! Something went horribly wrong with Skript.
[13:52:32 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:52:32 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[13:52:32 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[13:52:32 ERROR]: #!#! 
[13:52:32 ERROR]: #!#! Stack trace:
[13:52:32 ERROR]: #!#! java.lang.reflect.InvocationTargetException
[13:52:32 ERROR]: #!#!     at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
[13:52:32 ERROR]: #!#!     at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[13:52:32 ERROR]: #!#!     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[13:52:32 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.Skript$1.run(Skript.java:574)
[13:52:32 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[13:52:32 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[13:52:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1147)
[13:52:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[13:52:32 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[13:52:32 ERROR]: #!#! Caused by: java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
[13:52:32 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.hooks.VaultHook.init(VaultHook.java:52)
[13:52:32 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.hooks.Hook.<init>(Hook.java:58)
[13:52:32 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.hooks.VaultHook.<init>(VaultHook.java:39)
[13:52:32 ERROR]: #!#!     at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[13:52:32 ERROR]: #!#!     at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[13:52:32 ERROR]: #!#!     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[13:52:32 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.Skript$1.run(Skript.java:574)
[13:52:32 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[13:52:32 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[13:52:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1147)
[13:52:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[13:52:32 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[13:52:32 ERROR]: #!#! Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.economy.Economy
[13:52:32 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[13:52:32 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[13:52:32 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[13:52:32 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.hooks.VaultHook.init(VaultHook.java:52)
[13:52:32 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.hooks.Hook.<init>(Hook.java:58)
[13:52:32 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.hooks.VaultHook.<init>(VaultHook.java:39)
[13:52:32 ERROR]: #!#!     at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[13:52:32 ERROR]: #!#!     at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[13:52:32 ERROR]: #!#!     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[13:52:32 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.Skript$1.run(Skript.java:574)
[13:52:32 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[13:52:32 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[13:52:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1147)
[13:52:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[13:52:32 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[13:52:32 ERROR]: #!#! 
[13:52:32 ERROR]: #!#! Version Information:
[13:52:32 ERROR]: #!#!   Skript: 2.8.5 (latest)
[13:52:32 ERROR]: #!#!     Flavor: skriptlang-github
[13:52:32 ERROR]: #!#!     Date: 16:49:26.326703600
[13:52:32 ERROR]: #!#!   Bukkit: 1.20.6-R0.1-SNAPSHOT
[13:52:32 ERROR]: #!#!   Minecraft: 1.20.6
[13:52:32 ERROR]: #!#!   Java: 21.0.3 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS)
[13:52:32 ERROR]: #!#!   OS: Linux amd64 6.5.11-4-pve
[13:52:32 ERROR]: #!#! 
[13:52:32 ERROR]: #!#! Server platform: Paper
[13:52:32 ERROR]: #!#! 
[13:52:32 ERROR]: #!#! Current node: null
[13:52:32 ERROR]: #!#! Current item: null
[13:52:32 ERROR]: #!#! 
[13:52:32 ERROR]: #!#! Thread: Server thread
[13:52:32 ERROR]: #!#! 
[13:52:32 ERROR]: #!#! Language: english
[13:52:32 ERROR]: #!#! Link parse mode: DISABLED
[13:52:32 ERROR]: #!#! 
[13:52:32 ERROR]: #!#! End of Error.
[13:52:32 ERROR]: #!#!

### Expected Behavior

-

### Steps to Reproduce

-

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by EquipableMC** [comment]
Have you tried this with Skript 2.9.0-beta1?

**Comment by sovdeeth** [comment]
Cannot reproduce on 2.9.x
