### ISSUE TITLE
Skript Error

### ISSUE THREAD

**Issue by LafontaineBray** [SkriptLang/Skript#6732]
### Skript/Server Version

```markdown
[02:55:23 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[02:55:23 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[02:55:23 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[02:55:23 INFO]: [Skript] Server Version: git-Paper-496 (MC: 1.20.4)
[02:55:23 INFO]: [Skript] Skript Version: 2.8.5 (skriptlang-github)
[02:55:23 INFO]: [Skript] Installed Skript Addons: None
[02:55:23 INFO]: [Skript] Installed dependencies: 
[02:55:23 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

I was just adding a spawn skript so when you run the command it does a countdown and teleports you to a location which is spawn.

### Expected Behavior

Its supposed to tp me to spawn.

### Steps to Reproduce

I have no idea but here is the simple code, command /spawn
	trigger:
		send "&cTeleporting To Spawn In 5.." to player
		wait 1 seconds
		send "&cTeleporting To Spawn In 4.." to player
		wait 1 seconds
		send "&cTeleporting To Spawn In 3.." to player
		wait 1 seconds
		send "&cTeleporting To Spawn In 2.." to player
		wait 1 seconds
		send "&cTeleporting To Spawn In 1.." to player
		wait 1 seconds
		teleport player to location(-36, 134, 78)

### Errors or Screenshots

[02:53:28 ERROR]: #!#! 
[02:53:28 ERROR]: #!#! [Skript] Severe Error:
[02:53:28 ERROR]: #!#! 
[02:53:28 ERROR]: #!#! Something went horribly wrong with Skript.
[02:53:28 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[02:53:28 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[02:53:28 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[02:53:28 ERROR]: #!#! 
[02:53:28 ERROR]: #!#! Stack trace:
[02:53:28 ERROR]: #!#! java.lang.IllegalStateException: zip file closed
[02:53:28 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[02:53:28 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[02:53:28 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[02:53:28 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[02:53:28 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[02:53:28 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[02:53:28 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[02:53:28 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[02:53:28 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[02:53:28 ERROR]: #!#!     at Skript-2.8.5.jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)
[02:53:28 ERROR]: #!#!     at com.google.gson.Gson.getAdapter(Gson.java:556)
[02:53:28 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:834)
[02:53:28 ERROR]: #!#!     at com.google.gson.Gson.toJsonTree(Gson.java:712)
[02:53:28 ERROR]: #!#!     at com.google.gson.Gson.toJsonTree(Gson.java:689)
[02:53:28 ERROR]: #!#!     at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:172)
[02:53:28 ERROR]: #!#!     at net.md_5.bungee.chat.BaseComponentSerializer.serialize(BaseComponentSerializer.java:138)
[02:53:28 ERROR]: #!#!     at net.md_5.bungee.chat.TextComponentSerializer.serialize(TextComponentSerializer.java:33)
[02:53:28 ERROR]: #!#!     at net.md_5.bungee.chat.TextComponentSerializer.serialize(TextComponentSerializer.java:13)
[02:53:28 ERROR]: #!#!     at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:88)
[02:53:28 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:842)
[02:53:28 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:812)
[02:53:28 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:759)
[02:53:28 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:736)
[02:53:28 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:178)
[02:53:28 ERROR]: #!#!     at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:12)
[02:53:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3322)
[02:53:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3310)
[02:53:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3290)
[02:53:28 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:154)
[02:53:28 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.effects.EffMessage.execute(EffMessage.java:128)
[02:53:28 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[02:53:28 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[02:53:28 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[02:53:28 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[02:53:28 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:316)
[02:53:28 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:275)
[02:53:28 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:286)
[02:53:28 ERROR]: #!#!     at Skript-2.8.5.jar//ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:221)
[02:53:28 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:53:28 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[02:53:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999)
[02:53:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[02:53:28 ERROR]: #!#!     at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[02:53:28 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:31)
[02:53:28 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[02:53:28 ERROR]: #!#!     at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)
[02:53:28 ERROR]: #!#!     at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
[02:53:28 ERROR]: #!#!     at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:103)
[02:53:28 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:434)
[02:53:28 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336)
[02:53:28 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323)
[02:53:28 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2230)
[02:53:28 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$14(PlayerConnection.java:2190)
[02:53:28 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[02:53:28 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[02:53:28 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[02:53:28 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149)
[02:53:28 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[02:53:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1465)
[02:53:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[02:53:28 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
[02:53:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1442)
[02:53:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1365)
[02:53:28 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133)
[02:53:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1343)
[02:53:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1232)
[02:53:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[02:53:28 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[02:53:28 ERROR]: #!#! 
[02:53:28 ERROR]: #!#! Version Information:
[02:53:28 ERROR]: #!#!   Skript: 2.8.5 (latest)
[02:53:28 ERROR]: #!#!     Flavor: skriptlang-github
[02:53:28 ERROR]: #!#!     Date: 16:49:26.326703600
[02:53:28 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[02:53:28 ERROR]: #!#!   Minecraft: 1.20.4
[02:53:28 ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[02:53:28 ERROR]: #!#!   OS: Linux amd64 6.2.0-36-generic
[02:53:28 ERROR]: #!#! 
[02:53:28 ERROR]: #!#! Server platform: Paper
[02:53:28 ERROR]: #!#! 
[02:53:28 ERROR]: #!#! Current node: null
[02:53:28 ERROR]: #!#! Current item: send "?cTeleporting To Spawn In 5.." to the player
[02:53:28 ERROR]: #!#! Current trigger: command /abd (simple event) (spawn.sk, line 2)
[02:53:28 ERROR]: #!#! 
[02:53:28 ERROR]: #!#! Thread: Server thread
[02:53:28 ERROR]: #!#! 
[02:53:28 ERROR]: #!#! Language: english
[02:53:28 ERROR]: #!#! Link parse mode: DISABLED
[02:53:28 ERROR]: #!#! 
[02:53:28 ERROR]: #!#! End of Error.
[02:53:28 ERROR]: #!#! 

### Other

no

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment]
Have you reloaded your server via `/reload` or some plugin like PlugMan?
Do a proper server restart and see if it persist

**Comment by sovdeeth** [comment]
Closing due to no response.
