### ISSUE TITLE
Reloading Causes Error on 1.20.6

### ISSUE THREAD

**Issue by ExtraSmartMiner** [SkriptLang/Skript#6735]
### Skript/Server Version

```markdown
[11:20:51 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[11:20:51 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[11:20:51 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[11:20:51 INFO]: [Skript] Server Version: 1.20.6-115-9d6f2cc (MC: 1.20.6)
[11:20:51 INFO]: [Skript] Skript Version: 2.8.5 (skriptlang-github)
[11:20:51 INFO]: [Skript] Installed Skript Addons:
[11:20:51 INFO]: [Skript]  - Skellett v2.0.10 (https://forums.skunity.com/resources/skellett.24/)
[11:20:51 INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[11:20:51 INFO]: [Skript]  - SkQuery v4.1.10
[11:20:51 INFO]: [Skript]  - SkBee v3.5.2 (https://github.com/ShaneBeee/SkBee)
[11:20:51 INFO]: [Skript]  - SkJade v1.4.3 (https://www.github.com/Ankoki-Dev/SkJade)
[11:20:51 INFO]: [Skript] Installed dependencies:
[11:20:51 INFO]: [Skript]  - WorldGuard v7.0.10+d9424b1
```

### Bug Description

reloading any skript file gives me the error:

[11:20:01 ERROR]: Caught previously unhandled exception :
[11:20:01 ERROR]: Paper Async Command Builder Thread Pool - 0
java.util.ConcurrentModificationException: null
        at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:1023) ~[?:?]
        at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:1052) ~[?:?]
        at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:536) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.sendAsync(Commands.java:495) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.lambda$sendCommands$6(Commands.java:474) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Expected Behavior

No Error

### Steps to Reproduce

/skript reload <file name>

### Errors or Screenshots

[11:20:01 ERROR]: Caught previously unhandled exception :
[11:20:01 ERROR]: Paper Async Command Builder Thread Pool - 0
java.util.ConcurrentModificationException: null
        at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:1023) ~[?:?]
        at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:1052) ~[?:?]
        at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:536) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.sendAsync(Commands.java:495) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.commands.Commands.lambda$sendCommands$6(Commands.java:474) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Can you recreate this without addons?

**Comment by ShaneBeee** [comment]
1) I can confirm this with no addons

2) this error is something SkBriggy had a while back (do to registering vanilla MC type commands with Command API). 
And it's now something that happens in Paper due to paper doing some internal changes with their command api and how commands are registered internally.
I THINK it's something to do with unregistering then re-registering commands when reloading a script.

**Comment by veeonthewall** [comment]
Happened to me too. Skript 2.8.6, SkBee 3.5.2, skript-reflect 2.4. Paper 1.20.6
<img width="633" alt="Screenshot 2024-06-04 at 8 51 40 PM" src="https://github.com/SkriptLang/Skript/assets/105337781/08a2206c-61f9-4010-9669-0a4c1ea76b01">
