### ISSUE TITLE
The skript plugin dosent load

### ISSUE THREAD

**Issue by perikIis20M** [SkriptLang/Skript#6770]
### Skript/Server Version

```markdown
Skript Version is 2.8.6
And Minecraft Version is Purpur 1.20.4
```

### Bug Description

This is the console its saying to report this so i did
[21:57:38 ERROR]: #!#! 
[21:57:38 ERROR]: #!#! [Skript] Severe Error:
[21:57:38 ERROR]: #!#! 
[21:57:38 ERROR]: #!#! Something went horribly wrong with Skript.
[21:57:38 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[21:57:38 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[21:57:38 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[21:57:38 ERROR]: #!#! 
[21:57:38 ERROR]: #!#! Stack trace:
[21:57:38 ERROR]: #!#! java.nio.file.AccessDeniedException: /crafty/servers/544bf8a4-ec49-4e23-8f75-d3e35380f7eb/plugins/zipfstmp13096143450677486754.tmp
[21:57:38 ERROR]: #!#!     at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
[21:57:38 ERROR]: #!#!     at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[21:57:38 ERROR]: #!#!     at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[21:57:38 ERROR]: #!#!     at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
[21:57:38 ERROR]: #!#!     at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
[21:57:38 ERROR]: #!#!     at java.base/java.nio.file.Files.createFile(Files.java:657)
[21:57:38 ERROR]: #!#!     at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
[21:57:38 ERROR]: #!#!     at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:159)
[21:57:38 ERROR]: #!#!     at java.base/java.nio.file.Files.createTempFile(Files.java:878)
[21:57:38 ERROR]: #!#!     at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.createTempFileInSameDirectoryAs(ZipFileSystem.java:1643)
[21:57:38 ERROR]: #!#!     at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.getTempPathForEntry(ZipFileSystem.java:1137)
[21:57:38 ERROR]: #!#!     at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.newFileChannel(ZipFileSystem.java:1024)
[21:57:38 ERROR]: #!#!     at jdk.zipfs/jdk.nio.zipfs.ZipPath.newFileChannel(ZipPath.java:878)
[21:57:38 ERROR]: #!#!     at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileChannel(ZipFileSystemProvider.java:263)
[21:57:38 ERROR]: #!#!     at java.base/java.nio.channels.FileChannel.open(FileChannel.java:309)
[21:57:38 ERROR]: #!#!     at java.base/java.nio.channels.FileChannel.open(FileChannel.java:369)
[21:57:38 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.config.Config.<init>(Config.java:111)
[21:57:38 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.aliases.Aliases.load(Aliases.java:491)
[21:57:38 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.aliases.Aliases.lambda$loadDirectory$1(Aliases.java:475)
[21:57:38 ERROR]: #!#!     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[21:57:38 ERROR]: #!#!     at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[21:57:38 ERROR]: #!#!     at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[21:57:38 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
[21:57:38 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[21:57:38 ERROR]: #!#!     at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[21:57:38 ERROR]: #!#!     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[21:57:38 ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[21:57:38 ERROR]: #!#!     at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[21:57:38 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:468)
[21:57:38 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:433)
[21:57:38 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.aliases.Aliases.load(Aliases.java:389)
[21:57:38 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.Skript.onEnable(Skript.java:508)
[21:57:38 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[21:57:38 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[21:57:38 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[21:57:38 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[21:57:38 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653)
[21:57:38 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564)
[21:57:38 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675)
[21:57:38 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[21:57:38 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:346)
[21:57:38 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
[21:57:38 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[21:57:38 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[21:57:38 ERROR]: #!#! 
[21:57:38 ERROR]: #!#! Version Information:
[21:57:38 ERROR]: #!#!   Skript: 2.8.6
[21:57:38 ERROR]: #!#!     Flavor: skriptlang-github
[21:57:38 ERROR]: #!#!     Date: 15:29:23.319558700
[21:57:38 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[21:57:38 ERROR]: #!#!   Minecraft: 1.20.4
[21:57:38 ERROR]: #!#!   Java: 21.0.2 (OpenJDK 64-Bit Server VM 21.0.2+13-Ubuntu-122.04.1)
[21:57:38 ERROR]: #!#!   OS: Linux amd64 6.8.0-76060800daily20240311-generic
[21:57:38 ERROR]: #!#! 
[21:57:38 ERROR]: #!#! Server platform: Paper
[21:57:38 ERROR]: #!#! 
[21:57:38 ERROR]: #!#! Current node: null
[21:57:38 ERROR]: #!#! Current item: null
[21:57:38 ERROR]: #!#! 
[21:57:38 ERROR]: #!#! Thread: Server thread
[21:57:38 ERROR]: #!#! 
[21:57:38 ERROR]: #!#! Language: english
[21:57:38 ERROR]: #!#! Link parse mode: DISABLED
[21:57:38 ERROR]: #!#! 
[21:57:38 ERROR]: #!#! End of Error.
[21:57:38 ERROR]: #!#! 
[21:57:38 ERROR]: Error occurred while enabling Skript v2.8.6 (Is it up to date?)

### Expected Behavior

It supposed to load the plugin but it showed an error in the console

### Steps to Reproduce

When i turn on the server it just not work 

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/116967896/93774da8-0262-4a43-9077-b301f0f5d2b5)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Your server host/hardware is denying Skript access to creating or accessing config.sk, it seems.
