### ISSUE TITLE
Script failure after upgrading from 1.19.4 to 1.20.4

### ISSUE THREAD

**Issue by juzijun233** [SkriptLang/Skript#6773]
### Skript/Server Version

```markdown
Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[08.06 10:08:39.150] 信息: [Lobby-1] [10:08:39 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[08.06 10:08:39.151] 信息: [Lobby-1] [10:08:39 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[08.06 10:08:39.151] 信息: [Lobby-1] [10:08:39 INFO]: [Skript] Server Version: git-Purpur-2176 (MC: 1.20.4)
[08.06 10:08:39.152] 信息: [Lobby-1] [10:08:39 INFO]: [Skript] Skript Version: 2.8.6 (skriptlang-github)
[08.06 10:08:39.152] 信息: [Lobby-1] [10:08:39 INFO]: [Skript] Installed Skript Addons:
[08.06 10:08:39.153] 信息: [Lobby-1] [10:08:39 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[08.06 10:08:39.153] 信息: [Lobby-1] [10:08:39 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[08.06 10:08:39.154] 信息: [Lobby-1] [10:08:39 INFO]: [Skript]  - skript-yaml v1.4
[08.06 10:08:39.154] 信息: [Lobby-1] [10:08:39 INFO]: [Skript]  - MongoSK v2.3.0 (https://github.com/Romitou/MongoSK)
[08.06 10:08:39.155] 信息: [Lobby-1] [10:08:39 INFO]: [Skript]  - skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect)
[08.06 10:08:39.155] 信息: [Lobby-1] [10:08:39 INFO]: [Skript]  - SkBee v2.13.0 (https://github.com/ShaneBeee/SkBee)
[08.06 10:08:39.157] 信息: [Lobby-1] [10:08:39 INFO]: [Skript]  - CloudNetSkAddon-4 v1.0
[08.06 10:08:39.158] 信息: [Lobby-1] [10:08:39 INFO]: [Skript]  - Skcrew v3.5 (https://github.com/crewpvp/skcrew)
[08.06 10:08:39.165] 信息: [Lobby-1] [10:08:39 INFO]: [Skript]  - RediSkript v1.3.7-SNAPSHOT
[08.06 10:08:39.165] 信息: [Lobby-1] [10:08:39 INFO]: [Skript]  - ItemsAdder v3.6.3-beta-13 (devs.beer)
[08.06 10:08:39.167] 信息: [Lobby-1] [10:08:39 INFO]: [Skript] Installed dependencies:
[08.06 10:08:39.168] 信息: [Lobby-1] [10:08:39 INFO]: [Skript]  - Vault v1.7.3-b131
[08.06 10:08:39.169] 信息: [Lobby-1] [10:08:39 INFO]: [Skript]  - WorldGuard v7.0.9+5934e49
```

### Bug Description
```
 issued server command: /skript reload ���ܲ˵���.sk
[08.06 09:12:47.283] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!
[08.06 09:12:47.284] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! [Skript] Severe Error:
[08.06 09:12:47.285] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! Exception occurred in Skript's main command
[08.06 09:12:47.286] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! Used command: /skript reload ���ܲ˵���.sk
[08.06 09:12:47.287] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!
[08.06 09:12:47.288] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! Something went horribly wrong with Skript.
[08.06 09:12:47.291] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[08.06 09:12:47.296] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[08.06 09:12:47.297] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! Here is full list of them:
[08.06 09:12:47.298] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! MongoSK v2.3.0 (https://github.com/Romitou/MongoSK) skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect) skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) CloudNetSkAddon-4 v1.0 ItemsAdder v3.6.3-beta-13 (devs.beer) SkBee v2.13.0 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.4 Skcrew v3.5 (https://github.com/crewpvp/skcrew) RediSkript v1.3.7-SNAPSHOT
[08.06 09:12:47.299] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[08.06 09:12:47.305] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[08.06 09:12:47.306] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[08.06 09:12:47.307] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[08.06 09:12:47.308] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[08.06 09:12:47.309] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[08.06 09:12:47.310] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!
[08.06 09:12:47.318] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! Stack trace:
[08.06 09:12:47.319] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "ch.njol.skript.command.ScriptCommand.unregisterHelp()" because "scriptCommand" is null
[08.06 09:12:47.320] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at !Skript-2.8.6.jar//ch.njol.skript.command.Commands.unregisterCommand(Commands.java:277)
[08.06 09:12:47.322] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at !Skript-2.8.6.jar//ch.njol.skript.structures.StructCommand.unload(StructCommand.java:325)
[08.06 09:12:47.324] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at !Skript-2.8.6.jar//ch.njol.skript.ScriptLoader.unloadScripts(ScriptLoader.java:830)
[08.06 09:12:47.327] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at !Skript-2.8.6.jar//ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:864)
[08.06 09:12:47.328] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at !Skript-2.8.6.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:189)
[08.06 09:12:47.329] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[08.06 09:12:47.330] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[08.06 09:12:47.332] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1013)
[08.06 09:12:47.335] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[08.06 09:12:47.340] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[08.06 09:12:47.341] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:30)
[08.06 09:12:47.342] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
[08.06 09:12:47.345] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)
[08.06 09:12:47.346] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
[08.06 09:12:47.348] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:103)
[08.06 09:12:47.349] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:442)
[08.06 09:12:47.350] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:344)
[08.06 09:12:47.351] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:331)
[08.06 09:12:47.353] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2301)
[08.06 09:12:48.284] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$15(PlayerConnection.java:2261)
[08.06 09:12:48.285] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[08.06 09:12:48.286] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[08.06 09:12:48.287] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[08.06 09:12:48.288] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149)
[08.06 09:12:48.289] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[08.06 09:12:48.290] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1498)
[08.06 09:12:48.291] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[08.06 09:12:48.292] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
[08.06 09:12:48.296] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1475)
[08.06 09:12:48.299] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1398)
[08.06 09:12:48.300] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133)
[08.06 09:12:48.302] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1376)
[08.06 09:12:48.303] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1265)
[08.06 09:12:48.304] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[08.06 09:12:48.307] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[08.06 09:12:48.309] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!
[08.06 09:12:48.310] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! Version Information:
[08.06 09:12:48.311] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!   Skript: 2.8.6 (latest)
[08.06 09:12:48.314] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     Flavor: skriptlang-github
[08.06 09:12:48.315] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!     Date: 15:29:23.319558700
[08.06 09:12:48.319] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[08.06 09:12:48.322] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!   Minecraft: 1.20.4
[08.06 09:12:48.323] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!   Java: 21.0.2 (OpenJDK 64-Bit Server VM 21.0.2+13-LTS)
[08.06 09:12:48.324] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!   OS: Windows Server 2022 amd64 10.0
[08.06 09:12:48.325] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!
[08.06 09:12:48.326] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! Server platform: Paper
[08.06 09:12:48.327] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!
[08.06 09:12:48.328] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! Current node: null
[08.06 09:12:48.335] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! Current item: null
[08.06 09:12:48.336] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!
[08.06 09:12:48.339] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! Thread: Server thread
[08.06 09:12:48.341] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!
[08.06 09:12:48.344] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! Language: english
[08.06 09:12:48.345] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! Link parse mode: DISABLED
[08.06 09:12:48.346] 信息: [Lobby-1] [09:12:47 ERROR]: #!#!
[08.06 09:12:48.347] 信息: [Lobby-1] [09:12:47 ERROR]: #!#! End of Error.
```

### Expected Behavior

Reload the script correctly

### Steps to Reproduce

Upgraded from 1.19.4 to 1.20.4
Reload script
Error

```
command /smartmenu:
    aliases: /menu
    trigger:
        if event-player is from floodgate:
            execute player command "/forms open servers"
        else:
            execute console command "/cp 主菜单 %event-player%"
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
Can you replicate without addons?
