### ISSUE TITLE
Skript Error 1.20.6

### ISSUE THREAD

**Issue by ANormalGuys123** [SkriptLang/Skript#6775]
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-550 (MC: 1.19.4) [Skript] Skript Version: 2.8.6 (skriptlang-github) [Skript] Installed Skript Addons: [Skript] - skript-yaml v1.4.1 [Skript] - skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect)
[Skript] - SkBee v3.5.3
(https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies: [Skript] - Vault v1.7.3-b131
```

### Bug Description

SkItemCreator doesn't work

### Expected Behavior

SkItemCreator Doesn't work properly

### Steps to Reproduce

I add all skript files in 1 time.

### Errors or Screenshots

[13:10:28 ERROR]: #!#! 
[13:10:28 ERROR]: #!#! [Skript] Severe Error:
[13:10:28 ERROR]: #!#! 
[13:10:28 ERROR]: #!#! Something went horribly wrong with Skript.
[13:10:28 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:10:28 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[13:10:28 ERROR]: #!#! Here is full list of them:
[13:10:28 ERROR]: #!#! skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect) SkBee v3.5.3 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.4.1 DiscordSRV v1.27.0 (https://github.com/DiscordSRV/DiscordSRV) 
[13:10:28 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[13:10:28 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[13:10:28 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[13:10:28 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[13:10:28 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[13:10:28 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[13:10:28 ERROR]: #!#! 
[13:10:28 ERROR]: #!#! Stack trace:
[13:10:28 ERROR]: #!#! java.lang.IllegalArgumentException: material must not be null
[13:10:28 ERROR]: #!#!     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[13:10:28 ERROR]: #!#!     at org.bukkit.inventory.meta.trim.ArmorTrim.<init>(ArmorTrim.java:32)
[13:10:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftMetaArmor.<init>(CraftMetaArmor.java:74)
[13:10:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftMetaColorableArmor.<init>(CraftMetaColorableArmor.java:32)
[13:10:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:340)
[13:10:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:287)
[13:10:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:279)
[13:10:28 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.api.nbt.NBTCustomItemStack.saveCompound(NBTCustomItemStack.java:42)
[13:10:28 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.api.nbt.NBTCompound.mergeCompound(NBTCompound.java:151)
[13:10:28 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.elements.nbt.types.SkriptTypes$1.change(SkriptTypes.java:40)
[13:10:28 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.elements.nbt.types.SkriptTypes$1.change(SkriptTypes.java:24)
[13:10:28 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.util.SimpleExpression.change(SimpleExpression.java:263)
[13:10:28 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:292)
[13:10:28 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[13:10:28 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[13:10:28 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[13:10:28 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[13:10:28 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:86)
[13:10:28 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[13:10:28 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:311)
[13:10:28 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[13:10:28 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[13:10:28 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[13:10:28 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[13:10:28 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.effects.Delay.lambda$walk$0(Delay.java:107)
[13:10:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[13:10:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[13:10:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[13:10:28 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[13:10:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[13:10:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[13:10:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[13:10:28 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[13:10:28 ERROR]: #!#! 
[13:10:28 ERROR]: #!#! Version Information:
[13:10:28 ERROR]: #!#!   Skript: 2.8.6 (latest)
[13:10:28 ERROR]: #!#!     Flavor: skriptlang-github
[13:10:28 ERROR]: #!#!     Date: 15:29:23.319558700
[13:10:28 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[13:10:28 ERROR]: #!#!   Minecraft: 1.19.4
[13:10:28 ERROR]: #!#!   Java: 17.0.11 (OpenJDK 64-Bit Server VM 17.0.11+9)
[13:10:28 ERROR]: #!#!   OS: Linux amd64 5.15.0-112-generic
[13:10:28 ERROR]: #!#! 
[13:10:28 ERROR]: #!#! Server platform: Paper
[13:10:28 ERROR]: #!#! 
[13:10:28 ERROR]: #!#! Current node: null
[13:10:28 ERROR]: #!#! Current item: add nbt from "{Trim:{material:"minecraft:%lowercase%",pattern:"minecraft:%lowercase%"}}" to nbt from {skitemcreator.items.database::%{_file_name} (as java.lang.Object)%::final-item} (as java.lang.Object)
[13:10:28 ERROR]: #!#! Current trigger: function SKICLoadConfig (simple event) (SkItemCreator/SkItemCreator.sk, line 13)
[13:10:28 ERROR]: #!#! 
[13:10:28 ERROR]: #!#! Thread: Server thread
[13:10:28 ERROR]: #!#! 
[13:10:28 ERROR]: #!#! Language: english
[13:10:28 ERROR]: #!#! Link parse mode: DISABLED
[13:10:28 ERROR]: #!#! 
[13:10:28 ERROR]: #!#! End of Error.
[13:10:28 ERROR]: #!#! 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
This appears to be an error related to SkBee, not Skript. Please report it there, instead.
