### ISSUE TITLE
Skript Error 2.8.6

### ISSUE THREAD

**Issue by ANormalGuys123** [SkriptLang/Skript#6778]
### Skript/Server Version

```markdown
[Skript] Server Version: git-Paper-550 (MC: 1.19.4) [Skript] Skript Version: 2.8.6 (skriptlang-github)
[Skript] Installed Skript Addons:
[Skript] - skript-yaml v1.4.1
[Skript] - skript-reflect v2.4
(https://github.com/SkriptLang/skript-reflect)
[Skript] SkBee v3.5.3 (https://github.com/ShaneBeee/SkBee) [Skript] Installed dependencies:
[Skript] Vault v1.7.3-CMI
```

### Bug Description

I'm bad at scripting but I know it's SkBee bug that required for every Skript plugin

### Expected Behavior

I can't make custom craft recipes as normal ( I don't think it's the problem )

### Steps to Reproduce

I just downloaded the addon and it had these lines

### Errors or Screenshots

[17:16:57 ERROR]: #!#! [Skript] Severe Error:
[17:16:57 ERROR]: #!#! 
[17:16:57 ERROR]: #!#! Something went horribly wrong with Skript.
[17:16:57 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:16:57 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[17:16:57 ERROR]: #!#! Here is full list of them:
[17:16:57 ERROR]: #!#! skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect) SkBee v3.5.3 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.4.1 DiscordSRV v1.27.0 (https://github.com/DiscordSRV/DiscordSRV) 
[17:16:57 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[17:16:57 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[17:16:57 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[17:16:57 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[17:16:57 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[17:16:57 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[17:16:57 ERROR]: #!#! 
[17:16:57 ERROR]: #!#! Stack trace:
[17:16:57 ERROR]: #!#! java.lang.IllegalArgumentException: material must not be null
[17:16:57 ERROR]: #!#!     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[17:16:57 ERROR]: #!#!     at org.bukkit.inventory.meta.trim.ArmorTrim.<init>(ArmorTrim.java:32)
[17:16:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftMetaArmor.<init>(CraftMetaArmor.java:74)
[17:16:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftMetaColorableArmor.<init>(CraftMetaColorableArmor.java:32)
[17:16:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:340)
[17:16:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:287)
[17:16:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:279)
[17:16:57 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.api.nbt.NBTCustomItemStack.saveCompound(NBTCustomItemStack.java:42)
[17:16:57 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.api.nbt.NBTCompound.mergeCompound(NBTCompound.java:151)
[17:16:57 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.elements.nbt.types.SkriptTypes$1.change(SkriptTypes.java:40)
[17:16:57 ERROR]: #!#!     at SkBee-3.5.3.jar//com.shanebeestudios.skbee.elements.nbt.types.SkriptTypes$1.change(SkriptTypes.java:24)
[17:16:57 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.util.SimpleExpression.change(SimpleExpression.java:263)
[17:16:57 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:292)
[17:16:57 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[17:16:57 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:16:57 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[17:16:57 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[17:16:57 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:86)
[17:16:57 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[17:16:57 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:311)
[17:16:57 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[17:16:57 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[17:16:57 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:16:57 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[17:16:57 ERROR]: #!#!     at Skript-2.8.6.jar//ch.njol.skript.effects.Delay.lambda$walk$0(Delay.java:107)
[17:16:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[17:16:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[17:16:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[17:16:57 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[17:16:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[17:16:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[17:16:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[17:16:57 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[17:16:57 ERROR]: #!#! 
[17:16:57 ERROR]: #!#! Version Information:
[17:16:57 ERROR]: #!#!   Skript: 2.8.6 (latest)
[17:16:57 ERROR]: #!#!     Flavor: skriptlang-github
[17:16:57 ERROR]: #!#!     Date: 15:29:23.319558700
[17:16:57 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[17:16:57 ERROR]: #!#!   Minecraft: 1.19.4
[17:16:57 ERROR]: #!#!   Java: 17.0.11 (OpenJDK 64-Bit Server VM 17.0.11+9)
[17:16:57 ERROR]: #!#!   OS: Linux amd64 5.15.0-112-generic
[17:16:57 ERROR]: #!#! 
[17:16:57 ERROR]: #!#! Server platform: Paper
[17:16:57 ERROR]: #!#! 
[17:16:57 ERROR]: #!#! Current node: null
[17:16:57 ERROR]: #!#! Current item: add nbt from "{Trim:{material:"minecraft:%lowercase%",pattern:"minecraft:%lowercase%"}}" to nbt from {skitemcreator.items.database::%{_file_name} (as java.lang.Object)%::final-item} (as java.lang.Object)
[17:16:57 ERROR]: #!#! Current trigger: function SKICLoadConfig (simple event) (SkItemCreator/SkItemCreator.sk, line 13)
[17:16:57 ERROR]: #!#! 
[17:16:57 ERROR]: #!#! Thread: Server thread
[17:16:57 ERROR]: #!#! 
[17:16:57 ERROR]: #!#! Language: english
[17:16:57 ERROR]: #!#! Link parse mode: DISABLED
[17:16:57 ERROR]: #!#! 
[17:16:57 ERROR]: #!#! End of Error.
[17:16:57 ERROR]: #!#! 

### Other

no

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
This is skbee related, please report to skbee's github.
