### ISSUE TITLE
BUG IN PLUGIN START

### ISSUE THREAD

**Issue by Niccolo4646** [SkriptLang/Skript#6785]
### Skript/Server Version

```markdown
Skript: 2.8.6
Server BungeeCord: Latest version
```

### Bug Description

When I start the bugeecord the pl give me this error:
 [WARNING] Error loading plugin Skript
java.lang.NoClassDefFoundError: org/bukkit/event/Listener
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
    at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
    at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:341)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:251)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:284)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.Listener
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
    ... 13 more

### Expected Behavior

When I start the bugeecord the pl give me this error:
 [WARNING] Error loading plugin Skript
java.lang.NoClassDefFoundError: org/bukkit/event/Listener
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
    at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
    at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:341)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:251)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:284)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.Listener
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
    ... 13 more

### Steps to Reproduce

When I start the proxy

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by erenkarakal** [comment]
Skript is not a bungeecord plugin

**Comment by EquipableMC** [comment]
Use skript in a paper/spigot server, not in a bungeecord/velocity server
