### ISSUE TITLE
Error occurred while disabling skript

### ISSUE THREAD

**Issue by 7-Bar** [SkriptLang/Skript#6820]
### Skript/Server Version

```markdown
[Skript] Server Version: 1.206-135-79c1cel
[skript] Skript Version: 2.8.7 skriptlang-github
[skript] Installed Skript Addons: None
[Skript] Installed dependencies:
[Skript] - WorldGuard v7.0.10+d9424b1
```

### Bug Description

Every time i close my server through minehut, this error shows up: (look below at "Errors or screenshots"). And my variables in skript also don't save and this probably has something to do with the error.

### Expected Behavior

The error was not supposed to show up. And my script variables are supposed to save.

### Steps to Reproduce

Just by closing my server, with this as my only skript file: (none of these variables save and carry on into the next session after closing the server)
```
on join:
    set join message to "&9Welcome! %name of player%"


command /setspawn:
    description: set the spawn point (ONLY FOR OP, and is not server spawn for some reason, idk)
    permission: op # only op can use this command
    trigger:
        set {spawn} to location of block at location of player # sets {spawn} to location of player
        send "Set Spawn to: %{spawn}%" # sends a message


command /spawn:
    description: tpa to spawn
    trigger:
        set {_starting_loc} to location of player # sets _starting_loc to location of player
        set {_starting_health} to health of player # sets _starting_health to health of player
        send "&eTeleporting in 5 seconds"
		
        loop 5 times: # 5 seconds
            if distance between {_starting_loc} and player is not 0:
                # if player has moved
                send "&cTeleportation has been canceled: player moved" # in red
                stop
				
            if {_starting_health} - health of player is not 0:
                # if player took damage
                send "&cTeleportation has been canceled: player took damage" # in red
                stop
				
            wait 1 second
			
        teleport player to {spawn}
        send "&aTeleported to spawn"



command /set_home:
    description: sets player home
    trigger:
        # stores home's location
        set {home::%uuid of player%} to location of block at location of player
        send "&aSuccessfully set home to %{home::%uuid of player%}%"


command /home:
    description: teleports player to home
    trigger:
        # if home not set
        if {home::%uuid of player%} is not set:
            send "&cNo home has been set. Set one using /sethome"
            stop
        
        # teleports to home
        set {_starting_loc} to location of player # sets _starting_loc to location of player
        set {_starting_health} to health of player # sets _starting_health to health of player
        send "&eTeleporting in 5 seconds"
		
        loop 5 times: # 5 seconds
            if distance between {_starting_loc} and player is not 0:
                # if player has moved
                send "&cTeleportation has been canceled: player moved" # in red
                stop
				
            if {_starting_health} - health of player is not 0:
                # if player took damage
                send "&cTeleportation has been canceled: player took damage" # in red
                stop
				
            wait 1 second
			
        teleport player to {home::%uuid of player%}
        send "&aTeleported to home"
```

### Errors or Screenshots

the full log:
```
[07:18:06 INFO]: Saving the game (this may take a moment!)
[07:18:06 INFO]: Saved the game
[07:18:06 INFO]: Stopping the server
[07:18:06 INFO]: Stopping server
[07:18:06 INFO]: [SimpleTpa] Disabling SimpleTpa v7.1
[07:18:06 INFO]: [SimpleTpa] If you need support contact me at https://discord.gg/SZUkza9
[07:18:06 INFO]: [SimpleTpa] Simple Tpa has been disabled on version 7.1
[07:18:07 INFO]: [TradePlugin] Disabling TradePlugin v1.4.3
[07:18:07 INFO]: [Skript] Disabling Skript v2.8.7
[07:18:07 ERROR]: Error occurred while disabling Skript v2.8.7
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.validate(CraftScheduler.java:550) ~[paper-1.20.6.jar:1.20.6-135-79c1ce1]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:226) ~[paper-1.20.6.jar:1.20.6-135-79c1ce1]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211) ~[paper-1.20.6.jar:1.20.6-135-79c1ce1]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:175) ~[paper-1.20.6.jar:1.20.6-135-79c1ce1]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTask(CraftScheduler.java:144) ~[paper-1.20.6.jar:1.20.6-135-79c1ce1]
	at Skript-2.8.7.jar/ch.njol.skript.structures.StructCommand.scheduleCommandSync(StructCommand.java:341) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.structures.StructCommand.postUnload(StructCommand.java:334) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.ScriptLoader.unloadScripts(ScriptLoader.java:845) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.Skript.beforeDisable(Skript.java:1194) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.Skript.onDisable(Skript.java:1204) ~[Skript-2.8.7.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.20.6.jar:1.20.6-135-79c1ce1]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161) ~[paper-1.20.6.jar:1.20.6-135-79c1ce1]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[paper-1.20.6.jar:1.20.6-135-79c1ce1]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:540) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:573) ~[paper-1.20.6.jar:1.20.6-135-79c1ce1]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:978) ~[paper-1.20.6.jar:1.20.6-135-79c1ce1]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:842) ~[paper-1.20.6.jar:1.20.6-135-79c1ce1]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[paper-1.20.6.jar:1.20.6-135-79c1ce1]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-135-79c1ce1]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[07:18:07 INFO]: [MinehutPlugin] Disabling MinehutPlugin v0.0.27-SNAPSHOT
[07:18:07 INFO]: [ViaVersion] Disabling ViaVersion v5.0.0
[07:18:07 INFO]: [ViaVersion] ViaVersion is disabling, if this is a reload and you experience issues consider rebooting.
[07:18:07 INFO]: [WorldGuard] Disabling WorldGuard v7.0.10+d9424b1
[07:18:07 INFO]: [WorldGuard] Shutting down executor and cancelling any pending tasks...
[07:18:07 INFO]: [FastAsyncWorldEdit] Disabling FastAsyncWorldEdit v2.10.1-SNAPSHOT-810;6a54c5b
[07:18:07 INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[07:18:07 INFO]: Saving players
[07:18:07 INFO]: smashing_axod lost connection: Server closed
[07:18:07 INFO]: smashing_axod left the game
[07:18:07 INFO]: Coding_Guy lost connection: Server closed
[07:18:07 INFO]: Coding_Guy left the game
[07:18:07 INFO]: Saving worlds
[07:18:07 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[07:18:07 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[07:18:07 INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[07:18:07 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world'
[07:18:07 INFO]: [ChunkHolderManager] Saved 0 block chunks, 101 entity chunks, 0 poi chunks in world 'world' in 0.26s
[07:18:07 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[07:18:07 INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[07:18:07 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[07:18:07 INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[07:18:07 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_nether'
[07:18:07 INFO]: [ChunkHolderManager] Saved 0 block chunks, 33 entity chunks, 0 poi chunks in world 'world_nether' in 0.01s
[07:18:07 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[07:18:07 INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[07:18:07 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[07:18:07 INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[07:18:07 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_the_end'
[07:18:07 INFO]: [ChunkHolderManager] Saved 0 block chunks, 0 entity chunks, 0 poi chunks in world 'world_the_end' in 0.00s
[07:18:07 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[07:18:07 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[07:18:07 INFO]: Flushing Chunk IO
[07:18:07 INFO]: Closing Thread Pool
WARN StatusConsoleListener Advanced terminal features are not available in this environment
[07:18:07 INFO]: Closing Server
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Efnilite** [comment]
can you reproduce on latest?
