### ISSUE TITLE
Can't reload any skript

### ISSUE THREAD

**Issue by Hypocraft** [SkriptLang/Skript#6821]
### Skript/Server Version

```markdown
[13:45:10 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[13:45:10 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[13:45:10 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[13:45:10 INFO]: [Skript] Server Version: 1.20.6-147-e41d44f (MC: 1.20.6)
[13:45:10 INFO]: [Skript] Skript Version: 2.8.7 (skriptlang-github)
[13:45:10 INFO]: [Skript] Installed Skript Addons: None
[13:45:10 INFO]: [Skript] Installed dependencies:
[13:45:10 INFO]: [Skript]  - Vault v1.5.6-b49
[13:45:10 INFO]: [Skript]  - WorldGuard v7.0.10+d9424b1
```

### Bug Description

I can't reload these skripts whenever i try to reload it gives the error to report this on github
It said to remove all of the addons i did that, it still did not work

### Expected Behavior

The skript was working fine yesterday but today i started my server and got this bug

### Steps to Reproduce

[stats - Copy.txt](https://github.com/user-attachments/files/16010767/stats.-.Copy.txt)
[armor - Copy.txt](https://github.com/user-attachments/files/16010772/armor.-.Copy.txt)
Put this into skript folder and reload it gave no error previously but now it just does not reload and give the error (Only for these 2 files other are working)

### Errors or Screenshots

[13:40:57 ERROR]: #!#!
[13:40:57 ERROR]: #!#! [Skript] Severe Error:
[13:40:57 ERROR]: #!#! Exception occurred in Skript's main command
[13:40:57 ERROR]: #!#! Used command: /sk reload stats
[13:40:57 ERROR]: #!#!
[13:40:57 ERROR]: #!#! Something went horribly wrong with Skript.
[13:40:57 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:40:57 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[13:40:57 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[13:40:57 ERROR]: #!#!
[13:40:57 ERROR]: #!#! Stack trace:
[13:40:57 ERROR]: #!#! java.lang.NullPointerException: Cannot read the array length because "<local1>" is null
[13:40:57 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.events.EvtPeriodical.unload(EvtPeriodical.java:98)
[13:40:57 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.structures.StructEvent.unload(StructEvent.java:84)
[13:40:57 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.ScriptLoader.unloadScripts(ScriptLoader.java:830)
[13:40:57 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:864)
[13:40:57 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:189)
[13:40:57 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[13:40:57 ERROR]: #!#!     at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[13:40:57 ERROR]: #!#!     at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[13:40:57 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[13:40:57 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[13:40:57 ERROR]: #!#!     at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[13:40:57 ERROR]: #!#!     at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[13:40:57 ERROR]: #!#!     at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[13:40:57 ERROR]: #!#!     at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448)
[13:40:57 ERROR]: #!#!     at net.minecraft.commands.Commands.performCommand(Commands.java:355)
[13:40:57 ERROR]: #!#!     at net.minecraft.commands.Commands.performCommand(Commands.java:342)
[13:40:57 ERROR]: #!#!     at net.minecraft.commands.Commands.performCommand(Commands.java:337)
[13:40:57 ERROR]: #!#!     at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202)
[13:40:57 ERROR]: #!#!     at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176)
[13:40:57 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:40:57 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[13:40:57 ERROR]: #!#!     at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[13:40:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511)
[13:40:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)
[13:40:57 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[13:40:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488)
[13:40:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411)
[13:40:57 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[13:40:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377)
[13:40:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238)
[13:40:57 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[13:40:57 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[13:40:57 ERROR]: #!#!
[13:40:57 ERROR]: #!#! Version Information:
[13:40:57 ERROR]: #!#!   Skript: 2.8.7 (latest)
[13:40:57 ERROR]: #!#!     Flavor: skriptlang-github
[13:40:57 ERROR]: #!#!     Date: 14:50:13.592363600
[13:40:57 ERROR]: #!#!   Bukkit: 1.20.6-R0.1-SNAPSHOT
[13:40:57 ERROR]: #!#!   Minecraft: 1.20.6
[13:40:57 ERROR]: #!#!   Java: 21.0.2 (Java HotSpot(TM) 64-Bit Server VM 21.0.2+13-LTS-58)
[13:40:57 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:40:57 ERROR]: #!#!
[13:40:57 ERROR]: #!#! Server platform: Paper
[13:40:57 ERROR]: #!#!
[13:40:57 ERROR]: #!#! Current node: null
[13:40:57 ERROR]: #!#! Current item: null
[13:40:57 ERROR]: #!#!
[13:40:57 ERROR]: #!#! Thread: Server thread
[13:40:57 ERROR]: #!#!
[13:40:57 ERROR]: #!#! Language: english
[13:40:57 ERROR]: #!#! Link parse mode: DISABLED
[13:40:57 ERROR]: #!#!
[13:40:57 ERROR]: #!#! End of Error.
[13:40:57 ERROR]: #!#!
>

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Hypocraft** [comment]
and obviously i have .sk in the skript i changed it to .txt so i can upload it here

**Comment by eliavhaganav** [comment]
I've had the same error whille messing with names of items and variables, it's most likely a problem with the new version

**Comment by sovdeeth** [comment]
Cannot replicate with the given files
```
[11:51:08 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[11:51:08 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[11:51:08 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[11:51:08 INFO]: [Skript] Server Version: 1.20.6-147-e41d44f (MC: 1.20.6)
[11:51:08 INFO]: [Skript] Skript Version: 2.8.7 (skriptlang-github)
[11:51:08 INFO]: [Skript] Installed Skript Addons: None
[11:51:08 INFO]: [Skript] Installed dependencies:
[11:51:08 INFO]: [Skript]  - WorldGuard v7.0.9+5934e49
```

```
[11:50:46 INFO]: Done (17.240s)! For help, type "help"
[11:50:46 INFO]: Timings Reset
> sk reload armor.sk
[11:50:49 INFO]: [Skript] Reloading armor.sk...
[11:50:50 INFO]: loaded 15 structures from 'armor.sk'
[11:50:50 INFO]: [Skript] Successfully reloaded armor.sk. (197ms)
> sk reload scripts
[11:50:52 INFO]: [Skript] Reloading all scripts...
[11:50:52 INFO]: loaded 15 structures from 'armor.sk'
[11:50:52 INFO]: loaded 5 structures from 'stats.sk'
[11:50:52 INFO]: Line 80: (stats.sk)
[11:50:52 INFO]:     There's no loop that matches 'loop-player's name'
[11:50:52 INFO]:     Line: send "%{stats.baseehp::%loop-player's name%}%" to player
[11:50:52 INFO]:
[11:50:52 INFO]: [Skript] Encountered 1 error while reloading all scripts! (170ms)
```

**Comment by Hypocraft** [comment]
what version are you using of skript?

**Comment by sovdeeth** [comment]
> what version are you using of skript?

I included the /sk info in the previous message. It says 2.8.7.

**Comment by Moderocky** [comment]
Unable to reproduce and no further input from original reporter.
If more information becomes available please re-open this.
