### ISSUE TITLE
Skript for 1.21 not launching

### ISSUE THREAD

**Issue by Sleaks123** [SkriptLang/Skript#6833]
### Skript/Server Version

```markdown
1.21, Skript version: 2.8.7
```

### Bug Description

Skript isn't loading at all into my server 

### Expected Behavior

supposed to be in my server so i can run the command

### Steps to Reproduce

I just dragged the skreipt jar into plugins and ran it, thats all

### Errors or Screenshots

[09:18:44] [Server thread/INFO]: [Skript] Enabling Skript v2.8.7
[09:18:44] [Server thread/INFO]: [Skript] Successfully generated the config and the example scripts.
[09:18:45] [Server thread/ERROR]: Error occurred while enabling Skript v2.8.7 (Is it up to date?)
java.lang.IllegalArgumentException: LAVA_CAULDRON isn't an item
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.inventory.ItemStack.of(ItemStack.java:58) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:87) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:307) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:705) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:614) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:121) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.load(Aliases.java:506) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.load(Aliases.java:492) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.lambda$loadDirectory$1(Aliases.java:475) ~[Skript-2.8.7.jar:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.base/java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:468) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:433) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.load(Aliases.java:389) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.Skript.onEnable(Skript.java:508) ~[Skript-2.8.7.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-38-1f5db50]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-38-1f5db50]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-38-1f5db50]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-38-1f5db50]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[09:18:45] [Server thread/INFO]: [Skript] Disabling Skript v2.8.7
[09:18:45] [Server thread/ERROR]: Error occurred while disabling Skript v2.8.7
java.lang.ExceptionInInitializerError: null
	at Skript-2.8.7.jar/ch.njol.skript.Skript.beforeDisable(Skript.java:1192) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.Skript.onDisable(Skript.java:1204) ~[Skript-2.8.7.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.jar:1.21-38-1f5db50]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.jar:1.21-38-1f5db50]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.jar:1.21-38-1f5db50]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-38-1f5db50]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-38-1f5db50]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-38-1f5db50]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: ch.njol.skript.SkriptAPIException: Registration can only be done during plugin initialization
	at Skript-2.8.7.jar/ch.njol.skript.Skript.checkAcceptRegistrations(Skript.java:1299) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.Skript.registerEvent(Skript.java:1501) ~[Skript-2.8.7.jar:?]
	at Skript-2.8.7.jar/ch.njol.skript.events.EvtSkript.<clinit>(EvtSkript.java:39) ~[Skript-2.8.7.jar:?]
	... 17 more

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment]
Skript does not currently support 1.21. It will be coming in 2.9 (next month). You can download the nightly build from here: https://github.com/SkriptLang/Skript/actions/runs/9702144977. While others have reported it to be stable, we do not recommend using it on a production server and using it is at your own risk.
