### ISSUE TITLE
SEVERE ERROR

### ISSUE THREAD

**Issue by espectroPlasma** [SkriptLang/Skript#6857]
[18:53:26 ERROR]: #!#! 
[18:53:26 ERROR]: #!#! [Skript] Severe Error:
[18:53:26 ERROR]: #!#! Error saving variable named plot::espectroplasma
[18:53:26 ERROR]: #!#! 
[18:53:26 ERROR]: #!#! Something went horribly wrong with Skript.
[18:53:26 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[18:53:26 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[18:53:26 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[18:53:26 ERROR]: #!#! 
[18:53:26 ERROR]: #!#! Stack trace:
[18:53:26 ERROR]: #!#! ch.njol.skript.SkriptAPIException: Serializer of region must override newInstance(), canBeInstantiated() or mustSyncDeserialization() if its class does not have a nullary constructor
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.classes.Serializer.newInstance(Serializer.java:79)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.yggdrasil.Yggdrasil.newInstance(Yggdrasil.java:304)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.yggdrasil.Yggdrasil.isSerializable(Yggdrasil.java:139)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:153)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:227)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.registrations.Classes.serialize(Classes.java:761)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.variables.Variables.serialize(Variables.java:812)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.variables.Variables.serialize(Variables.java:793)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.variables.Variables.saveVariableChange(Variables.java:822)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.variables.Variables.setVariable(Variables.java:543)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.variables.Variables.setVariable(Variables.java:526)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.lang.Variable.set(Variable.java:494)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.lang.Variable.change(Variable.java:553)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:292)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.SkriptEventHandler.lambda$check$3(SkriptEventHandler.java:155)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.SkriptEventHandler.lambda$check$4(SkriptEventHandler.java:166)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:164)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[18:53:26 ERROR]: #!#!     at Skript-2.8.7.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:66)
[18:53:26 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[18:53:26 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:53:26 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[18:53:26 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[18:53:26 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[18:53:26 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594)
[18:53:26 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:550)
[18:53:26 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545)
[18:53:26 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:541)
[18:53:26 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2064)
[18:53:26 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32)
[18:53:26 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8)
[18:53:26 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[18:53:26 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:53:26 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149)
[18:53:26 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[18:53:26 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1498)
[18:53:26 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[18:53:26 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
[18:53:26 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1475)
[18:53:26 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1398)
[18:53:26 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133)
[18:53:26 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1376)
[18:53:26 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1265)
[18:53:26 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[18:53:26 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[18:53:26 ERROR]: #!#! 
[18:53:26 ERROR]: #!#! Version Information:
[18:53:26 ERROR]: #!#!   Skript: 2.8.7 (latest)
[18:53:26 ERROR]: #!#!     Flavor: skriptlang-github
[18:53:26 ERROR]: #!#!     Date: 14:50:13.592363600
[18:53:26 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[18:53:26 ERROR]: #!#!   Minecraft: 1.20.4
[18:53:26 ERROR]: #!#!   Java: 21.0.3 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS)
[18:53:26 ERROR]: #!#!   OS: Linux amd64 5.4.0-155-generic
[18:53:26 ERROR]: #!#! 
[18:53:26 ERROR]: #!#! Server platform: Paper
[18:53:26 ERROR]: #!#! 
[18:53:26 ERROR]: #!#! Current node: null
[18:53:26 ERROR]: #!#! Current item: null
[18:53:26 ERROR]: #!#! 
[18:53:26 ERROR]: #!#! Thread: Server thread
[18:53:26 ERROR]: #!#! 
[18:53:26 ERROR]: #!#! Language: english
[18:53:26 ERROR]: #!#! Link parse mode: DISABLED
[18:53:26 ERROR]: #!#! 
[18:53:26 ERROR]: #!#! End of Error.
[18:53:26 ERROR]: #!#!

**Comment by sovdeeth** [comment]
duplicate #6539
