### ISSUE TITLE
1.21 Plug-in activation error while running the server

### ISSUE THREAD

**Issue by interacp** [SkriptLang/Skript#6882]
### Skript/Server Version

```markdown
paper 1.21
```

### Bug Description

[17:33:08 ERROR]: #!#!
[17:33:08 ERROR]: #!#! [Skript] Severe Error:
[17:33:08 ERROR]: #!#! Cannot load class ch.njol.skript.expressions.ExprVehicle
[17:33:08 ERROR]: #!#!
[17:33:08 ERROR]: #!#! Something went horribly wrong with Skript.
[17:33:08 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:33:08 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[17:33:08 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[17:33:08 ERROR]: #!#!
[17:33:08 ERROR]: #!#! Stack trace:
[17:33:08 ERROR]: #!#! java.lang.NoClassDefFoundError: org/spigotmc/event/entity/EntityMountEvent (wrong name: org/bukkit/event/entity/EntityMountEvent)
[17:33:08 ERROR]: #!#!     at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[17:33:08 ERROR]: #!#!     at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
[17:33:08 ERROR]: #!#!     at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[17:33:08 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243)
[17:33:08 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[17:33:08 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[17:33:08 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:144)
[17:33:08 ERROR]: #!#!     at io.papermc.paper.plugin.entrypoint.classloader.group.SpigotPluginClassLoaderGroup.lookupClass(SpigotPluginClassLoaderGroup.java:43)
[17:33:08 ERROR]: #!#!     at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37)
[17:33:08 ERROR]: #!#!     at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34)
[17:33:08 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:187)
[17:33:08 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[17:33:08 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[17:33:08 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[17:33:08 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:534)
[17:33:08 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:513)
[17:33:08 ERROR]: #!#!     at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
[17:33:08 ERROR]: #!#!     at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
[17:33:08 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.Skript.classExists(Skript.java:1047)
[17:33:08 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.expressions.ExprVehicle.<clinit>(ExprVehicle.java:71)
[17:33:08 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[17:33:08 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:534)
[17:33:08 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:513)
[17:33:08 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.util.Utils.getClasses(Utils.java:202)
[17:33:08 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:82)
[17:33:08 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.Skript.onEnable(Skript.java:557)
[17:33:08 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[17:33:08 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[17:33:08 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[17:33:08 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[17:33:08 ERROR]: #!#!     at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629)
[17:33:08 ERROR]: #!#!     at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578)
[17:33:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:752)
[17:33:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:514)
[17:33:08 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327)
[17:33:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219)
[17:33:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[17:33:08 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[17:33:08 ERROR]: #!#!
[17:33:08 ERROR]: #!#! Version Information:
[17:33:08 ERROR]: #!#!   Skript: 2.9.0-pre1 (latest)
[17:33:08 ERROR]: #!#!     Flavor: skriptlang-github
[17:33:08 ERROR]: #!#!     Date: 20:43:34.397569300
[17:33:08 ERROR]: #!#!   Bukkit: 1.21-R0.1-SNAPSHOT
[17:33:08 ERROR]: #!#!   Minecraft: 1.21
[17:33:08 ERROR]: #!#!   Java: 21.0.3 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS)
[17:33:08 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[17:33:08 ERROR]: #!#!
[17:33:08 ERROR]: #!#! Server platform: Paper
[17:33:08 ERROR]: #!#!
[17:33:08 ERROR]: #!#! Current node: null
[17:33:08 ERROR]: #!#! Current item: null
[17:33:08 ERROR]: #!#!
[17:33:08 ERROR]: #!#! Thread: Server thread
[17:33:08 ERROR]: #!#!
[17:33:08 ERROR]: #!#! Language: english
[17:33:08 ERROR]: #!#! Link parse mode: DISABLED
[17:33:08 ERROR]: #!#!
[17:33:08 ERROR]: #!#! End of Error.
[17:33:08 ERROR]: #!#!

### Expected Behavior

 none

### Steps to Reproduce

paper 1.21 Use the latest version of the bucket and put Skrypt-2.9.0-pre1 in the plugins folder.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment]
What version of Paper are you using?

**Comment by veeonthewall** [comment]
He said 1.21 experimental

**Comment by interacp** [comment]
@APickledWalrus 
paper-1.21-48

**Comment by APickledWalrus** [comment]
Does this happen every time you try to start the server?

**Comment by interacp** [comment]
Yes, when I run the server, there will be an error unconditionally.

**Comment by APickledWalrus** [comment]
Are you able to try deleting the jar caches? That would be the `cache`, `versions`, `libraries` and `bundler` folders (it's okay if you do not have all of these folders). Additionally, I would recommend deleting the `.paper-remapped` folder in `plugins` so that they can be remapped in case it's an issue there. Are you using any other plugins?

**Comment by interacp** [comment]
@APickledWalrus 
![image](https://github.com/user-attachments/assets/f891e590-cdcf-49a8-ba77-c0e0053f8f07)
I use many plugins, and except for Skript, all of them are working without any conflicts.

**Comment by addpromax** [comment]
Delete Anything is not work

**Comment by belzaaron** [comment]
Can confirm:
```
[INFO]: [Skript] Enabling Skript v2.9.1
[INFO]: [Skript] Loaded 2952 aliases in 28ms
[INFO]: [Skript] You're currently running the latest stable version of Skript.
[ERROR]: #!#! 
[ERROR]: #!#! [Skript] Severe Error:
[ERROR]: #!#! Cannot load class ch.njol.skript.expressions.ExprVehicle
[ERROR]: #!#! 
[ERROR]: #!#! Something went horribly wrong with Skript.
[ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[ERROR]: #!#! 
[ERROR]: #!#! Stack trace:
[ERROR]: #!#! java.lang.NoClassDefFoundError: org/spigotmc/event/entity/EntityMountEvent (wrong name: org/bukkit/event/entity/EntityMountEvent)
[ERROR]: #!#!     at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[ERROR]: #!#!     at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
[ERROR]: #!#!     at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243)
[ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:144)
[ERROR]: #!#!     at io.papermc.paper.plugin.entrypoint.classloader.group.SpigotPluginClassLoaderGroup.lookupClass(SpigotPluginClassLoaderGroup.java:43)
[ERROR]: #!#!     at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37)
[ERROR]: #!#!     at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34)
[ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:187)
[ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:534)
[ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:513)
[ERROR]: #!#!     at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
[ERROR]: #!#!     at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
[ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript.classExists(Skript.java:1047)
[ERROR]: #!#!     at Skript.jar//ch.njol.skript.expressions.ExprVehicle.<clinit>(ExprVehicle.java:71)
[ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:534)
[ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:513)
[ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Utils.getClasses(Utils.java:202)
[ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:82)
[ERROR]: #!#!     at Skript.jar//ch.njol.skript.Skript.onEnable(Skript.java:557)
[ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[ERROR]: #!#!     at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[ERROR]: #!#!     at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754)
[ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516)
[ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
[ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[ERROR]: #!#! 
[ERROR]: #!#! Version Information:
[ERROR]: #!#!   Skript: 2.9.1 (latest)
[ERROR]: #!#!     Flavor: skriptlang-github
[ERROR]: #!#!     Date: 14:17:55.682181900
[ERROR]: #!#!   Bukkit: 1.21.1-R0.1-SNAPSHOT
[ERROR]: #!#!   Minecraft: 1.21.1
[ERROR]: #!#!   Java: 21.0.3 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS)
[ERROR]: #!#!   OS: Linux amd64 5.10.0-27-amd64
[ERROR]: #!#! 
[ERROR]: #!#! Server platform: Paper
[ERROR]: #!#! 
[ERROR]: #!#! Current node: null
[ERROR]: #!#! Current item: null
[ERROR]: #!#! 
[ERROR]: #!#! Thread: Server thread
[ERROR]: #!#! 
[ERROR]: #!#! Language: english
[ERROR]: #!#! Link parse mode: DISABLED
[ERROR]: #!#! 
[ERROR]: #!#! End of Error.
[ERROR]: #!#! 
[INFO]: [Skript]  ~ created by & © Peter Güttinger aka Njol ~
```
