### ISSUE TITLE
java.base@21.0.3/java.util.stream.AbstractPipeline.sourceSpliterator(AbstractPipeline.java:449)

### ISSUE THREAD

**Issue by a302Dev** [SkriptLang/Skript#6889]
### Skript/Server Version

```markdown
2.9.0 pre1
paper 1.20.6
```

### Bug Description

when I type the command /sk reload all i got this error

### Expected Behavior

skript work

### Steps to Reproduce

when I type the command /sk reload all i got this error

### Errors or Screenshots

[21:26:04 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - 1.20.6-148-20f5165 (MC: 1.20.6) ---

[21:26:04 ERROR]: The server has not responded for 10 seconds! Creating thread dump

[21:26:04 ERROR]: ------------------------------

[21:26:04 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):

[21:26:04 ERROR]: ------------------------------

[21:26:04 ERROR]: Current Thread: Server thread

[21:26:04 ERROR]: PID: 65 | Suspended: false | Native: false | State: RUNNABLE

[21:26:04 ERROR]: Stack:

[21:26:04 ERROR]: java.base@21.0.3/java.util.stream.AbstractPipeline.sourceSpliterator(AbstractPipeline.java:449)

[21:26:04 ERROR]: java.base@21.0.3/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

[21:26:04 ERROR]: java.base@21.0.3/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.patterns.Keyword$ChoiceKeyword.lambda$isPresent$1(Keyword.java:161)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.patterns.Keyword$ChoiceKeyword$$Lambda/0x00007f2ced26fad8.test(Unknown Source)

[21:26:04 ERROR]: java.base@21.0.3/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)

[21:26:04 ERROR]: java.base@21.0.3/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1736)

[21:26:04 ERROR]: java.base@21.0.3/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)

[21:26:04 ERROR]: java.base@21.0.3/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)

[21:26:04 ERROR]: java.base@21.0.3/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)

[21:26:04 ERROR]: java.base@21.0.3/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)

[21:26:04 ERROR]: java.base@21.0.3/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)

[21:26:04 ERROR]: java.base@21.0.3/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)

[21:26:04 ERROR]: java.base@21.0.3/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

[21:26:04 ERROR]: java.base@21.0.3/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.patterns.Keyword$ChoiceKeyword.isPresent(Keyword.java:161)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:51)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1323)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:232)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:325)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:369)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:651)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.VariableString.newInstance(VariableString.java:220)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Variable.newInstance(Variable.java:181)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parseVariable(SkriptParser.java:315)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:471)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:781)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:162)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:63)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1323)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:232)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Condition.parse(Condition.java:76)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:209)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section.init(Section.java:67)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:259)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:179)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section$$Lambda/0x00007f2ceda5afc0.get(Unknown Source)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:212)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section.parse(Section.java:178)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:987)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section.loadCode(Section.java:93)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:233)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section.init(Section.java:67)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:259)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:179)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section$$Lambda/0x00007f2ceda5afc0.get(Unknown Source)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:212)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section.parse(Section.java:178)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:987)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section.loadCode(Section.java:93)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:233)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section.init(Section.java:67)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:259)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:179)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section$$Lambda/0x00007f2ceda5afc0.get(Unknown Source)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:212)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Section.parse(Section.java:178)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:987)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.lang.SkriptEvent.load(SkriptEvent.java:144)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.structures.StructEvent.load(StructEvent.java:85)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$8(ScriptLoader.java:570)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader$$Lambda/0x00007f2ceda59ff0.test(Unknown Source)

[21:26:04 ERROR]: java.base@21.0.3/java.util.ArrayList.removeIf(ArrayList.java:1755)

[21:26:04 ERROR]: java.base@21.0.3/java.util.ArrayList.removeIf(ArrayList.java:1743)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:561)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader$$Lambda/0x00007f2ceda58e30.apply(Unknown Source)

[21:26:04 ERROR]: java.base@21.0.3/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)

[21:26:04 ERROR]: java.base@21.0.3/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)

[21:26:04 ERROR]: java.base@21.0.3/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:513)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:459)

[21:26:04 ERROR]: Skript-2.9.0-pre1.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:141)

[21:26:04 ERROR]: org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)

[21:26:04 ERROR]: io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)

[21:26:04 ERROR]: com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)

[21:26:04 ERROR]: net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)

[21:26:04 ERROR]: net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)

[21:26:04 ERROR]: net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)

[21:26:04 ERROR]: net.minecraft.commands.execution.UnboundEntryAction$$Lambda/0x00007f2cea4534e0.execute(Unknown Source)

[21:26:04 ERROR]: net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)

[21:26:04 ERROR]: net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)

[21:26:04 ERROR]: net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448)

[21:26:04 ERROR]: net.minecraft.commands.Commands.performCommand(Commands.java:355)

[21:26:04 ERROR]: net.minecraft.commands.Commands.performCommand(Commands.java:342)

[21:26:04 ERROR]: net.minecraft.commands.Commands.performCommand(Commands.java:337)

[21:26:04 ERROR]: net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202)

[21:26:04 ERROR]: net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176)

[21:26:04 ERROR]: net.minecraft.server.network.ServerGamePacketListenerImpl$$Lambda/0x00007f2cea450220.run(Unknown Source)

[21:26:04 ERROR]: net.minecraft.server.TickTask.run(TickTask.java:18)

[21:26:04 ERROR]: net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)

[21:26:04 ERROR]: net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)

[21:26:04 ERROR]: net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511)

[21:26:04 ERROR]: net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)

[21:26:04 ERROR]: net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)

[21:26:04 ERROR]: net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488)

[21:26:04 ERROR]: net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411)

[21:26:04 ERROR]: net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)

[21:26:04 ERROR]: net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377)

[21:26:04 ERROR]: net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238)

[21:26:04 ERROR]: net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)

[21:26:04 ERROR]: net.minecraft.server.MinecraftServer$$Lambda/0x00007f2ce8d217a8.run(Unknown Source)

[21:26:04 ERROR]: java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596)

[21:26:04 ERROR]: java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)

[21:26:04 ERROR]: ------------------------------

[21:26:04 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---

[21:26:04 ERROR]: ------------------------------

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
This is not an issue, it's just your server warning you that it is taking more than 10 seconds to reload skript.

**Comment by a302Dev** [comment]
> This is not an issue, it's just your server warning you that it is taking more than 10 seconds to reload skript.

how i can fix this:
[11:51:40 ERROR]: #!#!

[11:51:40 ERROR]: #!#! [Skript] Severe Error:

[11:51:40 ERROR]: #!#!

[11:51:40 ERROR]: #!#! Something went horribly wrong with Skript.

[11:51:40 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.

[11:51:40 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).

[11:51:40 ERROR]: #!#! Here is full list of them:

[11:51:40 ERROR]: #!#! DiSky v4.17.2 SkBee v3.5.6 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.5 SkQuery v4.1.10 Skellett v2.0.10 (https://forums.skunity.com/resources/skellett.24/)

[11:51:40 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.

[11:51:40 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.

[11:51:40 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.

[11:51:40 ERROR]: #!#! In that case, you will be given instruction on how should you report it.

[11:51:40 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.

[11:51:40 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.

[11:51:40 ERROR]: #!#!

[11:51:40 ERROR]: #!#! Stack trace:

[11:51:40 ERROR]: #!#! java.lang.IllegalStateException: zip file closed

[11:51:40 ERROR]: #!#! at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846)

[11:51:40 ERROR]: #!#! at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338)

[11:51:40 ERROR]: #!#! at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516)

[11:51:40 ERROR]: #!#! at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)

[11:51:40 ERROR]: #!#! at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)

[11:51:40 ERROR]: #!#! at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)

[11:51:40 ERROR]: #!#! at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)

[11:51:40 ERROR]: #!#! at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)

[11:51:40 ERROR]: #!#! at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)

[11:51:40 ERROR]: #!#! at Skript-2.9.0-pre1.jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)

[11:51:40 ERROR]: #!#! at com.google.gson.Gson.getAdapter(Gson.java:556)

[11:51:40 ERROR]: #!#! at com.google.gson.Gson.toJson(Gson.java:834)

[11:51:40 ERROR]: #!#! at com.google.gson.Gson.toJson(Gson.java:812)

[11:51:40 ERROR]: #!#! at com.google.gson.Gson.toJson(Gson.java:759)

[11:51:40 ERROR]: #!#! at com.google.gson.Gson.toJson(Gson.java:736)

[11:51:40 ERROR]: #!#! at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:178)

[11:51:40 ERROR]: #!#! at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:18)

[11:51:40 ERROR]: #!#! at org.bukkit.craftbukkit.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3395)

[11:51:40 ERROR]: #!#! at org.bukkit.craftbukkit.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3383)

[11:51:40 ERROR]: #!#! at org.bukkit.craftbukkit.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3363)

[11:51:40 ERROR]: #!#! at Skript-2.9.0-pre1.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:154)

[11:51:40 ERROR]: #!#! at Skript-2.9.0-pre1.jar//ch.njol.skript.effects.EffMessage.execute(EffMessage.java:128)

[11:51:40 ERROR]: #!#! at Skript-2.9.0-pre1.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)

[11:51:40 ERROR]: #!#! at Skript-2.9.0-pre1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)

[11:51:40 ERROR]: #!#! at Skript-2.9.0-pre1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)

[11:51:40 ERROR]: #!#! at Skript-2.9.0-pre1.jar//ch.njol.skript.effects.Delay.lambda$walk$0(Delay.java:107)

[11:51:40 ERROR]: #!#! at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)

[11:51:40 ERROR]: #!#! at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)

[11:51:40 ERROR]: #!#! at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699)

[11:51:40 ERROR]: #!#! at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467)

[11:51:40 ERROR]: #!#! at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571)

[11:51:40 ERROR]: #!#! at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231)

[11:51:40 ERROR]: #!#! at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)

[11:51:40 ERROR]: #!#! at java.base/java.lang.Thread.run(Thread.java:1583)

[11:51:40 ERROR]: #!#!

[11:51:40 ERROR]: #!#! Version Information:

[11:51:40 ERROR]: #!#! Skript: 2.9.0-pre1 (latest)

[11:51:40 ERROR]: #!#! Flavor: skriptlang-github

[11:51:40 ERROR]: #!#! Date: 20:43:34.397569300

[11:51:40 ERROR]: #!#! Bukkit: 1.20.6-R0.1-SNAPSHOT

[11:51:40 ERROR]: #!#! Minecraft: 1.20.6

[11:51:40 ERROR]: #!#! Java: 21.0.3 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS)

[11:51:40 ERROR]: #!#! OS: Linux amd64 5.15.0-100-generic

[11:51:40 ERROR]: #!#!

[11:51:40 ERROR]: #!#! Server platform: Paper

[11:51:40 ERROR]: #!#!

[11:51:40 ERROR]: #!#! Current node: null

[11:51:40 ERROR]: #!#! Current item: send "§8[ §bMGSTR §8] §aHunting was successful ✔" to event-player

[11:51:40 ERROR]: #!#! Current trigger: fish (simple event) (fish.sk, line 70)

[11:51:40 ERROR]: #!#!

[11:51:40 ERROR]: #!#! Thread: Server thread

[11:51:40 ERROR]: #!#!

[11:51:40 ERROR]: #!#! Language: english

[11:51:40 ERROR]: #!#! Link parse mode: DISABLED

[11:51:40 ERROR]: #!#!

[11:51:40 ERROR]: #!#! End of Error.

[11:51:40 ERROR]: #!#!

**Comment by EquipableMC** [comment]
Are you using a plugin that reloads plugins or /reload?

**Comment by a302Dev** [comment]
> Are you using a plugin that reloads plugins or /reload?

yes i use /reload

**Comment by APickledWalrus** [comment]
Skript does not currently support /reload, which is why you are encountering issues. You will need to restart the server instead.
