### ISSUE TITLE
error with reload scripts

### ISSUE THREAD

**Issue by juzijun233** [SkriptLang/Skript#6892]
### Skript/Server Version

```markdown
> skript info
[09:18:47 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[09:18:47 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[09:18:47 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[09:18:47 INFO]: [Skript] Server Version: git-Purpur-2176 (MC: 1.20.4)
[09:18:47 INFO]: [Skript] Skript Version: 2.9.0-pre1 (skriptlang-github)
[09:18:47 INFO]: [Skript] Installed Skript Addons:
[09:18:47 INFO]: [Skript]  - skript-placeholders v1.6.0 (https://github.com/APickledWalrus/skript-placeholders)
[09:18:47 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[09:18:47 INFO]: [Skript]  - skript-yaml v1.5
[09:18:47 INFO]: [Skript]  - Diskuise v0.3.4 (https://github.com/UnderscoreTud/diskuise)
[09:18:47 INFO]: [Skript]  - SkBee v3.5.0 (https://github.com/ShaneBeee/SkBee)
[09:18:47 INFO]: [Skript] Installed dependencies:
[09:18:47 INFO]: [Skript]  - Vault v1.7.3-b131
[09:18:47 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

```
> sk reload \VillageDefenseWar\
[09:16:43 INFO]: [Skript] Reloading all scripts in VillageDefenseWar...
[09:16:43 ERROR]: #!#! 
[09:16:43 ERROR]: #!#! [Skript] Severe Error:
[09:16:43 ERROR]: #!#! Exception occurred in Skript's main command
[09:16:43 ERROR]: #!#! Used command: /sk reload \VillageDefenseWar\
[09:16:43 ERROR]: #!#! 
[09:16:43 ERROR]: #!#! Something went horribly wrong with Skript.
[09:16:43 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[09:16:43 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[09:16:43 ERROR]: #!#! Here is full list of them:
[09:16:43 ERROR]: #!#! skript-placeholders v1.6.0 (https://github.com/APickledWalrus/skript-placeholders) Diskuise v0.3.4 (https://github.com/UnderscoreTud/diskuise
) skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) skript-yaml v1.5 SkBee v3.5.0 (https://github.com/ShaneBeee/SkBee) 
[09:16:43 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[09:16:43 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[09:16:43 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[09:16:43 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[09:16:43 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[09:16:43 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[09:16:43 ERROR]: #!#! 
[09:16:43 ERROR]: #!#! Stack trace:
[09:16:43 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "ch.njol.skript.command.ScriptCommand.unregisterHelp()" because "scriptCommand" is null
[09:16:43 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.command.Commands.unregisterCommand(Commands.java:286)
[09:16:43 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.structures.StructCommand.unload(StructCommand.java:331)
[09:16:43 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.ScriptLoader.unloadScripts(ScriptLoader.java:852)
[09:16:43 ERROR]: #!#!     at Skript-2.9.0-pre1.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:197)
[09:16:43 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:16:43 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[09:16:43 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1013)
[09:16:43 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:998)
[09:16:43 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.bk(DedicatedServer.java:541)
[09:16:43 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:488)
[09:16:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1558)
[09:16:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1246)
[09:16:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[09:16:43 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[09:16:43 ERROR]: #!#! 
[09:16:43 ERROR]: #!#! Version Information:
[09:16:43 ERROR]: #!#!   Skript: 2.9.0-pre1 (latest)
[09:16:43 ERROR]: #!#!     Flavor: skriptlang-github
[09:16:43 ERROR]: #!#!     Date: 20:43:34.397569300
[09:16:43 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[09:16:43 ERROR]: #!#!   Minecraft: 1.20.4
[09:16:43 ERROR]: #!#!   Java: 21.0.2 (OpenJDK 64-Bit Server VM 21.0.2+13-LTS)
[09:16:43 ERROR]: #!#!   OS: Windows Server 2022 amd64 10.0
[09:16:43 ERROR]: #!#! 
[09:16:43 ERROR]: #!#! Server platform: Paper
[09:16:43 ERROR]: #!#! 
[09:16:43 ERROR]: #!#! Current node: null
[09:16:43 ERROR]: #!#! Current item: null
[09:16:43 ERROR]: #!#! 
[09:16:43 ERROR]: #!#! Thread: Server thread
[09:16:43 ERROR]: #!#! 
[09:16:43 ERROR]: #!#! Language: english
[09:16:43 ERROR]: #!#! Link parse mode: DISABLED
[09:16:43 ERROR]: #!#! 
[09:16:43 ERROR]: #!#! End of Error.
[09:16:43 ERROR]: #!#! 
```

### Expected Behavior

Reload the script correctly

### Steps to Reproduce

Wrote some code and then reloaded the script

### Other

Everything was working fine until I updated the code once. 2.8.7 didn't work either. Before that I was using 2.8.5

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment]
Are you having any errors during startup?

**Comment by APickledWalrus** [comment]
Can you send your full server startup log?
