### ISSUE TITLE
Exception while using `send` 

### ISSUE THREAD

**Issue by jwdeveloper** [SkriptLang/Skript#6927]
### Skript/Server Version

```markdown
Skript 2.9.0
Paper 1.20.6
```

```
### Bug Description

[22:00:35 ERROR]: #!#!
[22:00:35 ERROR]: #!#! [Skript] Severe Error:
[22:00:35 ERROR]: #!#!
[22:00:35 ERROR]: #!#! Something went horribly wrong with Skript.
[22:00:35 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:00:35 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:00:35 ERROR]: #!#! Following plugins are probably related to this error in some way:
[22:00:35 ERROR]: #!#! TikTokMc
[22:00:35 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:00:35 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:00:35 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:00:35 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:00:35 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[22:00:35 ERROR]: #!#!
[22:00:35 ERROR]: #!#! Stack trace:
[22:00:35 ERROR]: #!#! java.lang.IllegalStateException: zip file closed
[22:00:35 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846)
[22:00:35 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338)
[22:00:35 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516)
[22:00:35 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)
[22:00:35 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[22:00:35 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[22:00:35 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[22:00:35 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[22:00:35 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[22:00:35 ERROR]: #!#!     at Skript-2.9.0.jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)
[22:00:35 ERROR]: #!#!     at com.google.gson.Gson.getAdapter(Gson.java:556)
[22:00:35 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:834)
[22:00:35 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:812)
[22:00:35 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:759)
[22:00:35 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:736)
[22:00:35 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:178)
[22:00:35 ERROR]: #!#!     at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:18)
[22:00:35 ERROR]: #!#!     at org.bukkit.craftbukkit.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3395)
[22:00:35 ERROR]: #!#!     at org.bukkit.craftbukkit.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3383)
[22:00:35 ERROR]: #!#!     at org.bukkit.craftbukkit.entity.CraftPlayer$2.sendMessage(CraftPlayer.java:3363)
[22:00:35 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:154)
[22:00:35 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.effects.EffMessage.execute(EffMessage.java:128)
[22:00:35 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[22:00:35 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[22:00:35 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[22:00:35 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[22:00:35 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.SkriptEventHandler.lambda$execute$2(SkriptEventHandler.java:183)
[22:00:35 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.SkriptEventHandler.lambda$execute$3(SkriptEventHandler.java:194)
[22:00:35 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[22:00:35 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[22:00:35 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.SkriptEventHandler.execute(SkriptEventHandler.java:192)
[22:00:35 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:138)
[22:00:35 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:64)
[22:00:35 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[22:00:35 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:00:35 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[22:00:35 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[22:00:35 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[22:00:35 ERROR]: #!#!     at TikTokLive.jar//io.github.jw.spigot.mc.tiktok.tiktok.TikTokClient.lambda$createClient$6(TikTokClient.java:116)
[22:00:35 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[22:00:35 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[22:00:35 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699)
[22:00:35 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467)
[22:00:35 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571)
[22:00:35 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231)
[22:00:35 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[22:00:35 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1570)
[22:00:35 ERROR]: #!#!
[22:00:35 ERROR]: #!#! Version Information:
[22:00:35 ERROR]: #!#!   Skript: 2.9.0 (latest)
[22:00:35 ERROR]: #!#!     Flavor: skriptlang-github
[22:00:35 ERROR]: #!#!     Date: 16:01:35.354421100
[22:00:35 ERROR]: #!#!   Bukkit: 1.20.6-R0.1-SNAPSHOT
[22:00:35 ERROR]: #!#!   Minecraft: 1.20.6
[22:00:35 ERROR]: #!#!   Java: 22.0.2 (Java HotSpot(TM) 64-Bit Server VM 22.0.2+9-70)
[22:00:35 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[22:00:35 ERROR]: #!#!
[22:00:35 ERROR]: #!#! Server platform: Paper
[22:00:35 ERROR]: #!#!
[22:00:35 ERROR]: #!#! Current node: null
[22:00:35 ERROR]: #!#! Current item: send "§7A §2Creeper §7has been spawned at your location!, total creepers count is" to the player
[22:00:35 ERROR]: #!#! Current trigger: tiktok join (TikTokJoinEvent) (tiktok.sk, line 16)
[22:00:35 ERROR]: #!#!
[22:00:35 ERROR]: #!#! Thread: Server thread
[22:00:35 ERROR]: #!#!
[22:00:35 ERROR]: #!#! Language: english
[22:00:35 ERROR]: #!#! Link parse mode: DISABLED
[22:00:35 ERROR]: #!#!
[22:00:35 ERROR]: #!#! End of Error.
[22:00:35 ERROR]: #!#!
```
### Expected Behavior

I should send message

### Steps to Reproduce

make script:

```
 add 1 to {creeperCount}
 send "&7A &2Creeper &7has been spawned at your location!, total creepers count is" to the player
```

### Errors or Screenshots

![image](https://github.com/user-attachments/assets/40e6541c-5478-4828-bbbc-5fa0f46659be)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment]
This often happens when you reloaded the server instead of restarting it.
