### ISSUE TITLE
Skript server error

### ISSUE THREAD

**Issue by Msyial** [SkriptLang/Skript#6928]
### Skript/Server Version

```markdown
[16:21:29 INFO]: [Skript] Skript的alias可以在这里找到：https://github.com/SkriptLang/skript-aliases
[16:21:29 INFO]: [Skript] Skript的文档可以在这里找到：https://docs.skriptlang.org/
[16:21:29 INFO]: [Skript] Skript的教程可以在这里找到：https://docs.skriptlang.org/tutorials
[16:21:29 INFO]: [Skript] 服务器版本：1.21-65-34a2917 (MC: 1.21)
[16:21:29 INFO]: [Skript] Skript版本：2.9.0 (skriptlang-github)
[16:21:29 INFO]: [Skript] 已安装的Skript插件：None
[16:21:29 INFO]: [Skript] 已安装的依赖：
[16:21:29 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

[16:19:41 ERROR]: #!#!
[16:19:41 ERROR]: #!#! [Skript] Severe Error:
[16:19:41 ERROR]: #!#!
[16:19:41 ERROR]: #!#! Something went horribly wrong with Skript.
[16:19:41 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:19:41 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[16:19:41 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[16:19:41 ERROR]: #!#!
[16:19:41 ERROR]: #!#! Stack trace:
[16:19:41 ERROR]: #!#! java.util.MissingFormatArgumentException: Format specifier '%s'
[16:19:41 ERROR]: #!#!     at java.base/java.util.Formatter.format(Formatter.java:2796)
[16:19:41 ERROR]: #!#!     at java.base/java.util.Formatter.format(Formatter.java:2734)
[16:19:41 ERROR]: #!#!     at java.base/java.lang.String.format(String.java:4432)
[16:19:41 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.localization.PluralizingArgsMessage.toString(PluralizingArgsMessage.java:38)
[16:19:41 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.Skript$1.lambda$run$20(Skript.java:861)
[16:19:41 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
[16:19:41 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
[16:19:41 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2214)
[16:19:41 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.Skript$1.run(Skript.java:854)
[16:19:41 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[16:19:41 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[16:19:41 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231)
[16:19:41 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[16:19:41 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1570)
[16:19:41 ERROR]: #!#!
[16:19:41 ERROR]: #!#! Version Information:
[16:19:41 ERROR]: #!#!   Skript: 2.9.0 (latest)
[16:19:41 ERROR]: #!#!     Flavor: skriptlang-github
[16:19:41 ERROR]: #!#!     Date: 16:01:35.354421100
[16:19:41 ERROR]: #!#!   Bukkit: 1.21-R0.1-SNAPSHOT
[16:19:41 ERROR]: #!#!   Minecraft: 1.21
[16:19:41 ERROR]: #!#!   Java: 22 (Java HotSpot(TM) 64-Bit Server VM 22+36-2370)
[16:19:41 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[16:19:41 ERROR]: #!#!
[16:19:41 ERROR]: #!#! Server platform: Paper
[16:19:41 ERROR]: #!#!
[16:19:41 ERROR]: #!#! Current node: null
[16:19:41 ERROR]: #!#! Current item: null
[16:19:41 ERROR]: #!#!
[16:19:41 ERROR]: #!#! Thread: Server thread
[16:19:41 ERROR]: #!#!
[16:19:41 ERROR]: #!#! Language: simplifiedchinese
[16:19:41 ERROR]: #!#! Link parse mode: DISABLED
[16:19:41 ERROR]: #!#!
[16:19:41 ERROR]: #!#! End of Error.
[16:19:41 ERROR]: #!#!

### Expected Behavior

idk

### Steps to Reproduce

Appears when starting the server

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Msyial** [comment]
> 您使用的是什么语言？是自定义语言吗？启动时是否会出现此错误？

Chinese .This will only report an error when the server is started, and it will work normally at other times, and the script will also

**Comment by APickledWalrus** [comment]
Did you make any changes to it?

**Comment by Msyial** [comment]
![Uploading QQ_1721399188268.png…]()

**Comment by Msyial** [comment]
![QQ20240719-222717](https://github.com/user-attachments/assets/82a94d1d-c1ad-43d4-b74d-00672c3c62ad)

**Comment by APickledWalrus** [comment]
Looking quickly, it appears that the lang entry `skript.scripts loaded` has an extraneous `%s` format specifier. This is caused by the message seemingly referencing commands when that is no longer done.
![image](https://github.com/user-attachments/assets/d1ad307a-015a-43bc-bd72-7aa7f5e5316a)


That translation will need updated in the language file. Would you be able to provide a translation for the following message?
`scripts loaded: Loaded %s scripts with a total of %s structures in %s`
The first `%s` is a number for how many scripts were loaded
The second `%s` is a number for how many structures (code headers such as functions, commands, events) were loaded
The third `%s` is a time (example: 3 seconds)

**Comment by Msyial** [comment]
已加载 %s 个脚本，总共包含 %s 个结构，耗时 %s。

**Comment by Msyial** [comment]
ok thank u

**Comment by APickledWalrus** [comment]
I'll keep this open until we fix it on our end
