### ISSUE TITLE
[Skript] Severe Error:

### ISSUE THREAD

**Issue by xet55** [SkriptLang/Skript#6945]
### Skript/Server Version

```markdown
[20:52:05 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[20:52:05 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[20:52:05 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[20:52:05 INFO]: [Skript] Server Version: git-Paper-496 (MC: 1.20.4)
[20:52:05 INFO]: [Skript] Skript Version: 2.9.0 (skriptlang-github)
[20:52:05 INFO]: [Skript] Installed Skript Addons: None
[20:52:05 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

I am currently working on some skripts for my new gen raiding server, when I kept getting errors with every command I did, then I noticed that no events were working either. And the same error was spamming my console, and saying my addons could be causing the issue, I removed them all and the issue repeated itself. Then I tried a simple hello command, and that was erroring so now I am here.

### Expected Behavior

My commands and events should run as normal.

### Steps to Reproduce

No steps to reproduce, just was skripting as normal and this occurred. 

### Errors or Screenshots

[20:48:49 ERROR]: #!#! 
[20:48:49 ERROR]: #!#! [Skript] Severe Error:
[20:48:49 ERROR]: #!#! 
[20:48:49 ERROR]: #!#! Something went horribly wrong with Skript.
[20:48:49 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:48:49 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[20:48:49 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[20:48:49 ERROR]: #!#! 
[20:48:49 ERROR]: #!#! Stack trace:
[20:48:49 ERROR]: #!#! java.lang.IllegalStateException: zip file closed
[20:48:49 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846)
[20:48:49 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338)
[20:48:49 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516)
[20:48:49 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)
[20:48:49 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[20:48:49 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[20:48:49 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[20:48:49 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[20:48:49 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[20:48:49 ERROR]: #!#!     at Skript-2.9.0.jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)
[20:48:49 ERROR]: #!#!     at com.google.gson.Gson.getAdapter(Gson.java:556)
[20:48:49 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:834)
[20:48:49 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:812)
[20:48:49 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:759)
[20:48:49 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:736)
[20:48:49 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:175)
[20:48:49 ERROR]: #!#!     at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:12)
[20:48:49 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3322)
[20:48:49 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3310)
[20:48:49 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer$3.sendMessage(CraftPlayer.java:3290)
[20:48:49 ERROR]: #!#!     at SkriptNew.jar//ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:154)
[20:48:49 ERROR]: #!#!     at SkriptNew.jar//ch.njol.skript.effects.EffMessage.execute(EffMessage.java:128)
[20:48:49 ERROR]: #!#!     at SkriptNew.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[20:48:49 ERROR]: #!#!     at SkriptNew.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:48:49 ERROR]: #!#!     at SkriptNew.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[20:48:49 ERROR]: #!#!     at SkriptNew.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[20:48:49 ERROR]: #!#!     at SkriptNew.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:345)
[20:48:49 ERROR]: #!#!     at SkriptNew.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:304)
[20:48:49 ERROR]: #!#!     at SkriptNew.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:315)
[20:48:49 ERROR]: #!#!     at SkriptNew.jar//ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:250)
[20:48:49 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:48:49 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[20:48:49 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999)
[20:48:49 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[20:48:49 ERROR]: #!#!     at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[20:48:49 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:31)
[20:48:49 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[20:48:49 ERROR]: #!#!     at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)
[20:48:49 ERROR]: #!#!     at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
[20:48:49 ERROR]: #!#!     at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:103)
[20:48:49 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:434)
[20:48:49 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336)
[20:48:49 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323)
[20:48:49 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2230)
[20:48:49 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$14(PlayerConnection.java:2190)
[20:48:49 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[20:48:49 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[20:48:49 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:48:49 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149)
[20:48:49 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[20:48:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1465)
[20:48:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[20:48:49 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
[20:48:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1442)
[20:48:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1365)
[20:48:49 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133)
[20:48:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1516)
[20:48:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[20:48:49 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[20:48:49 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[20:48:49 ERROR]: #!#! 
[20:48:49 ERROR]: #!#! Version Information:
[20:48:49 ERROR]: #!#!   Skript: 2.9.0
[20:48:49 ERROR]: #!#!     Flavor: skriptlang-github
[20:48:49 ERROR]: #!#!     Date: 16:01:35.354421100
[20:48:49 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[20:48:49 ERROR]: #!#!   Minecraft: 1.20.4
[20:48:49 ERROR]: #!#!   Java: 21.0.3 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS)
[20:48:49 ERROR]: #!#!   OS: Linux amd64 6.2.0-36-generic
[20:48:49 ERROR]: #!#! 
[20:48:49 ERROR]: #!#! Server platform: Paper
[20:48:49 ERROR]: #!#! 
[20:48:49 ERROR]: #!#! Current node: null
[20:48:49 ERROR]: #!#! Current item: send "hello" to the player
[20:48:49 ERROR]: #!#! Current trigger: command /hello (simple event) (Raiding.sk, line 22)
[20:48:49 ERROR]: #!#! 
[20:48:49 ERROR]: #!#! Thread: Server thread
[20:48:49 ERROR]: #!#! 
[20:48:49 ERROR]: #!#! Language: english
[20:48:49 ERROR]: #!#! Link parse mode: DISABLED
[20:48:49 ERROR]: #!#! 
[20:48:49 ERROR]: #!#! End of Error.
[20:48:49 ERROR]: #!#! 

### Other

Nope.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by EquipableMC** [comment]
Have you used the /reload command by any chance or a 3rd party plugin to reload Skript?

**Comment by xet55** [comment]
> Have you used the /reload command by any chance or a 3rd party plugin to reload Skript?

I am a fucking retard.

**Comment by xet55** [comment]
Resolved
