### ISSUE TITLE
Skript modifying hover list not working

### ISSUE THREAD

**Issue by Nitropenda** [SkriptLang/Skript#6974]
### Skript/Server Version

```markdown
[14:42:36 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:42:36 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[14:42:36 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[14:42:36 INFO]: [Skript] Server Version: 1.21-127-4e6a2a1 (MC: 1.21)
[14:42:36 INFO]: [Skript] Skript Version: 2.9.1 (skriptlang-github)
[14:42:36 INFO]: [Skript] Installed Skript Addons: 
[14:42:36 INFO]: [Skript]  - Skellett v2.0.10 (https://forums.skunity.com/resources/skellett.24/)
[14:42:36 INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[14:42:36 INFO]: [Skript]  - skript-reflect v2.5.1 (https://github.com/SkriptLang/skript-reflect)
[14:42:36 INFO]: [Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[14:42:36 INFO]: [Skript]  - SkQuery v4.1.10
[14:42:36 INFO]: [Skript]  - SkBee v3.5.9 (https://github.com/ShaneBeee/SkBee)
[14:42:36 INFO]: [Skript] Installed dependencies: None

I removed the addons earlier but it still gave me the same console Error output. The console output bellow was even after I removed all other plugins including the addons.
```

### Bug Description

Modifying the server hover list on the "on server ping event" doesn't work and gives an Error message

### Expected Behavior

It should have cleared the hover list and added a new line with new text. Most of the skript was from skript lang. This is the full script I used:

on server list ping:
  add "&aWelcome to the &6Minecraft &aserver!" to the hover list
  add "" to the hover list # A blank line
  add "&cThere are online players!" to the hover list

on join:
  if name of player is "Nitropenda":
    add player to {vanished::*}

(Source: https://docs.skriptlang.org/expressions.html#ExprHoverList)

### Steps to Reproduce

I wanted to edit my server hover list because I was making a vanish sckript. Since the "hide {vanished::*} from the server list" didnt hide the player info from the hover list and only lowered the online players count by 1 I knew something was wrong. I removed all other plugins and skript addons from the server and wrote a small skript which should edit the hover list manually but that didnt work either and gave a big output to the console: 

[14:23:12 ERROR]: #!#! 
[14:23:12 ERROR]: #!#! [Skript] Severe Error:
[14:23:12 ERROR]: #!#! 
[14:23:12 ERROR]: #!#! Something went horribly wrong with Skript.
[14:23:12 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:23:12 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[14:23:12 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[14:23:12 ERROR]: #!#! 
[14:23:12 ERROR]: #!#! Stack trace:
[14:23:12 ERROR]: #!#! java.lang.IllegalArgumentException: Name cannot be longer than 16 characters
[14:23:12 ERROR]: #!#!     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[14:23:12 ERROR]: #!#!     at com.destroystokyo.paper.profile.CraftPlayerProfile.createAuthLibProfile(CraftPlayerProfile.java:273)
[14:23:12 ERROR]: #!#!     at com.destroystokyo.paper.profile.CraftPlayerProfile.<init>(CraftPlayerProfile.java:41)
[14:23:12 ERROR]: #!#!     at org.bukkit.craftbukkit.CraftServer.createProfile(CraftServer.java:3176)
[14:23:12 ERROR]: #!#!     at org.bukkit.Bukkit.createProfile(Bukkit.java:2708)
[14:23:12 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.expressions.ExprHoverList.change(ExprHoverList.java:125)
[14:23:12 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:292)
[14:23:12 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[14:23:12 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[14:23:12 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[14:23:12 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[14:23:12 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.SkriptEventHandler.lambda$execute$2(SkriptEventHandler.java:183)
[14:23:12 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.SkriptEventHandler.lambda$execute$3(SkriptEventHandler.java:194)
[14:23:12 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftFuture.run(CraftFuture.java:88)
[14:23:12 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[14:23:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726)
[14:23:12 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473)
[14:23:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598)
[14:23:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[14:23:12 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[14:23:12 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[14:23:12 ERROR]: #!#! 
[14:23:12 ERROR]: #!#! Version Information:
[14:23:12 ERROR]: #!#!   Skript: 2.9.1 (latest)
[14:23:12 ERROR]: #!#!     Flavor: skriptlang-github
[14:23:12 ERROR]: #!#!     Date: 14:17:55.682181900
[14:23:12 ERROR]: #!#!   Bukkit: 1.21-R0.1-SNAPSHOT
[14:23:12 ERROR]: #!#!   Minecraft: 1.21
[14:23:12 ERROR]: #!#!   Java: 21.0.3 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS)
[14:23:12 ERROR]: #!#!   OS: Linux amd64 6.1.0-23-amd64
[14:23:12 ERROR]: #!#! 
[14:23:12 ERROR]: #!#! Server platform: Paper
[14:23:12 ERROR]: #!#! 
[14:23:12 ERROR]: #!#! Current node: null
[14:23:12 ERROR]: #!#! Current item: add "§aWelcome to the §6Minecraft §aserver!" to the hover list
[14:23:12 ERROR]: #!#! Current trigger: server list ping (simple event) (combatlog.sk, line 350)
[14:23:12 ERROR]: #!#! 
[14:23:12 ERROR]: #!#! Thread: Server thread
[14:23:12 ERROR]: #!#! 
[14:23:12 ERROR]: #!#! Language: english
[14:23:12 ERROR]: #!#! Link parse mode: DISABLED
[14:23:12 ERROR]: #!#! 
[14:23:12 ERROR]: #!#! End of Error.

### Errors or Screenshots

![Screenshot (93)](https://github.com/user-attachments/assets/c33df714-4011-46c5-ad97-8eedeabd6b0e)
![Screenshot (94)](https://github.com/user-attachments/assets/043d57ac-133a-4961-be36-d69117ae15ef)
![Screenshot (95)](https://github.com/user-attachments/assets/e896b2f1-0cc1-41ca-bba3-04b9e9a049f0)

### Other

Please fix this bug for the "hover list event" and also for the "hide player from server list event" because if I use hide player from hover list it will also not remove the player from the hover list. This is really important for me so the users dont suspect anything when Im vanished.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment]
It looks like the lines can be no longer than 16 characters (not sure if that's always been the case). Looking at Paper's documentation though, there are new methods for managing the hover list on newer versions that may be worth testing for bypassing this limit.
