### ISSUE TITLE
No clue but help?

### ISSUE THREAD

**Issue by NexusGit-Hub** [SkriptLang/Skript#6999]
### Skript/Server Version

```markdown
[15:00:31 ERROR]: #!#! Version Information:
[15:00:31 ERROR]: #!#!   Skript: 2.9.1 (latest)
[15:00:31 ERROR]: #!#!     Flavor: skriptlang-github
[15:00:31 ERROR]: #!#!     Date: 14:17:55.682181900
[15:00:31 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[15:00:31 ERROR]: #!#!   Minecraft: 1.20.4
[15:00:31 ERROR]: #!#!   Java: 22.0.1 (Java HotSpot(TM) 64-Bit Server VM 22.0.1+8-16)
[15:00:31 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[15:00:31 ERROR]: #!#!
```

### Bug Description

[15:00:31 ERROR]: #!#!
[15:00:31 ERROR]: #!#! [Skript] Severe Error:
[15:00:31 ERROR]: #!#!
[15:00:31 ERROR]: #!#! Something went horribly wrong with Skript.
[15:00:31 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:00:31 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[15:00:31 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[15:00:31 ERROR]: #!#!
[15:00:31 ERROR]: #!#! Stack trace:
[15:00:31 ERROR]: #!#! java.lang.IllegalStateException: zip file closed
[15:00:31 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846)
[15:00:31 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338)
[15:00:31 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516)
[15:00:31 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)
[15:00:31 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[15:00:31 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[15:00:31 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[15:00:31 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[15:00:31 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[15:00:31 ERROR]: #!#!     at Skript-2.9.1.jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)
[15:00:31 ERROR]: #!#!     at com.google.gson.Gson.getAdapter(Gson.java:556)
[15:00:31 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:834)
[15:00:31 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:812)
[15:00:31 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:759)
[15:00:31 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:736)
[15:00:31 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:178)
[15:00:31 ERROR]: #!#!     at Skript-2.9.1.jar//net.kyori.adventure.text.serializer.bungeecord.BungeeComponentSerializer.deserialize(BungeeComponentSerializer.java:142)
[15:00:31 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.expressions.ExprChestInventory.get(ExprChestInventory.java:107)
[15:00:31 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.expressions.ExprChestInventory.get(ExprChestInventory.java:46)
[15:00:31 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:97)
[15:00:31 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[15:00:31 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[15:00:31 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[15:00:31 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[15:00:31 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[15:00:31 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:345)
[15:00:31 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:304)
[15:00:31 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:315)
[15:00:31 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:250)
[15:00:31 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:00:31 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[15:00:31 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999)
[15:00:31 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[15:00:31 ERROR]: #!#!     at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[15:00:31 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:31)
[15:00:31 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[15:00:31 ERROR]: #!#!     at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)
[15:00:31 ERROR]: #!#!     at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
[15:00:31 ERROR]: #!#!     at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:103)
[15:00:31 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:434)
[15:00:31 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336)
[15:00:31 ERROR]: #!#!     at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323)
[15:00:31 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2230)
[15:00:31 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$14(PlayerConnection.java:2190)
[15:00:31 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[15:00:31 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[15:00:31 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:00:31 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149)
[15:00:31 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[15:00:31 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1465)
[15:00:31 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[15:00:31 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
[15:00:31 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1442)
[15:00:31 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1365)
[15:00:31 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133)
[15:00:31 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1343)
[15:00:31 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1232)
[15:00:31 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[15:00:31 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1570)
[15:00:31 ERROR]: #!#!
[15:00:31 ERROR]: #!#! Version Information:
[15:00:31 ERROR]: #!#!   Skript: 2.9.1 (latest)
[15:00:31 ERROR]: #!#!     Flavor: skriptlang-github
[15:00:31 ERROR]: #!#!     Date: 14:17:55.682181900
[15:00:31 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[15:00:31 ERROR]: #!#!   Minecraft: 1.20.4
[15:00:31 ERROR]: #!#!   Java: 22.0.1 (Java HotSpot(TM) 64-Bit Server VM 22.0.1+8-16)
[15:00:31 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[15:00:31 ERROR]: #!#!
[15:00:31 ERROR]: #!#! Server platform: Paper
[15:00:31 ERROR]: #!#!
[15:00:31 ERROR]: #!#! Current node: null
[15:00:31 ERROR]: #!#! Current item: set metadata values "Menu" of the player to chest inventory named "§6Menu" with [[long:6]]
[15:00:31 ERROR]: #!#! Current trigger: command /menu (simple event) (All.sk, line 7)
[15:00:31 ERROR]: #!#!
[15:00:31 ERROR]: #!#! Thread: Server thread
[15:00:31 ERROR]: #!#!
[15:00:31 ERROR]: #!#! Language: english
[15:00:31 ERROR]: #!#! Link parse mode: DISABLED
[15:00:31 ERROR]: #!#!
[15:00:31 ERROR]: #!#! End of Error.
[15:00:31 ERROR]: #!#!

### Expected Behavior

Open Menu

### Steps to Reproduce

I have no clue

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by TenFont** [comment]
Do you use the `/reload confirm` command? The zip file closed exception is common when reloading the server in this way.

**Comment by EquipableMC** [comment]
> Do you use the `/reload confirm` command? The zip file closed exception is common when reloading the server in this way.

To add onto this, if you didn’t use `/reload confirm`, did you use another plugin to reload Skript? This error can also occur when this happens.

**Comment by sovdeeth** [comment]
Closing due to lack of response
