### ISSUE TITLE
Again, same error, different line

### ISSUE THREAD

**Issue by hiimnobody496** [SkriptLang/Skript#7096]
### Skript/Server Version

```markdown
Server version 1.21-130-b1b5d4c
Skript version: 2.9.2 (skriptlang-github)
installed skript addons: none
installed dependencies: none
```

### Bug Description

It says that the output of it is null, I've added the code in steps to reproduce and the error in errors or screenshots

### Expected Behavior

When i click a mangrove button, it should open up a gui, yet it doesn't

### Steps to Reproduce

`on right click on mangrove button:
    {Whitelisted::*} contains player
    set {_GUIt} to a new chest inventory with 1 rows named "Controls"
    set slot 5 of {_GUIt} to fire charge named "&rDematerialize"
    set slot 3 of {_GUIt} to fire charge named "&rDematerialize"
    set slot 0 of {_GUIt} to compass named "&rTarget"
    set slot 4 of {_GUIt} to nether star named "&rMaterialize"
    set slot 1 of {_GUIt} to a clock named "&rTime select"
    set slot 7 of {_GUIt} to a book named "&rInformation"
    set slot 8 of {_GUIt} to paper named "&rWhitelist"
    open {_GUIt} to player`
    
    
    
    Then just restart and then it doesn't work for me

### Errors or Screenshots

[17:01:58 ERROR]: #!#! 
[17:01:58 ERROR]: #!#! [Skript] Severe Error:
[17:01:58 ERROR]: #!#! 
[17:01:58 ERROR]: #!#! Something went horribly wrong with Skript.
[17:01:58 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:01:58 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[17:01:58 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[17:01:58 ERROR]: #!#! 
[17:01:58 ERROR]: #!#! Stack trace:
[17:01:58 ERROR]: #!#! java.lang.IllegalStateException: zip file closed
[17:01:58 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846)
[17:01:58 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338)
[17:01:58 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516)
[17:01:58 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)
[17:01:58 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[17:01:58 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[17:01:58 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[17:01:58 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[17:01:58 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)
[17:01:58 ERROR]: #!#!     at com.google.gson.Gson.getAdapter(Gson.java:556)
[17:01:58 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:834)
[17:01:58 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:812)
[17:01:58 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:759)
[17:01:58 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:736)
[17:01:58 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:175)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//net.kyori.adventure.text.serializer.bungeecord.BungeeComponentSerializer.deserialize(BungeeComponentSerializer.java:142)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//ch.njol.skript.expressions.ExprChestInventory.get(ExprChestInventory.java:107)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//ch.njol.skript.expressions.ExprChestInventory.get(ExprChestInventory.java:46)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:97)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//ch.njol.skript.SkriptEventHandler.lambda$execute$2(SkriptEventHandler.java:183)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//ch.njol.skript.SkriptEventHandler.lambda$execute$3(SkriptEventHandler.java:194)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//ch.njol.skript.SkriptEventHandler.execute(SkriptEventHandler.java:192)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:138)
[17:01:58 ERROR]: #!#!     at Skript-2.9.2 (2).jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:64)
[17:01:58 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:01:58 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:01:58 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[17:01:58 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[17:01:58 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[17:01:58 ERROR]: #!#!     at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:602)
[17:01:58 ERROR]: #!#!     at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536)
[17:01:58 ERROR]: #!#!     at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1871)
[17:01:58 ERROR]: #!#!     at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44)
[17:01:58 ERROR]: #!#!     at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11)
[17:01:58 ERROR]: #!#!     at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[17:01:58 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:01:58 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[17:01:58 ERROR]: #!#!     at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[17:01:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537)
[17:01:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[17:01:58 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[17:01:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514)
[17:01:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507)
[17:01:58 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[17:01:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466)
[17:01:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473)
[17:01:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318)
[17:01:58 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[17:01:58 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[17:01:58 ERROR]: #!#! 
[17:01:58 ERROR]: #!#! Version Information:
[17:01:58 ERROR]: #!#!   Skript: 2.9.2 (latest)
[17:01:58 ERROR]: #!#!     Flavor: skriptlang-github
[17:01:58 ERROR]: #!#!     Date: 14:35:57.106583600
[17:01:58 ERROR]: #!#!   Bukkit: 1.21-R0.1-SNAPSHOT
[17:01:58 ERROR]: #!#!   Minecraft: 1.21
[17:01:58 ERROR]: #!#!   Java: 21.0.3 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS)
[17:01:58 ERROR]: #!#!   OS: Linux amd64 6.8.0-39-generic
[17:01:58 ERROR]: #!#! 
[17:01:58 ERROR]: #!#! Server platform: Paper
[17:01:58 ERROR]: #!#! 
[17:01:58 ERROR]: #!#! Current node: null
[17:01:58 ERROR]: #!#! Current item: set {_GUIt} (as java.lang.Object) to chest inventory named "Controls" with [[long:1]]
[17:01:58 ERROR]: #!#! Current trigger: right click on mangrove button (rightclick on [[itemtype:mangrove wood button]]) (Chronovault.sk, line 380)
[17:01:58 ERROR]: #!#! 
[17:01:58 ERROR]: #!#! Thread: Server thread
[17:01:58 ERROR]: #!#! 
[17:01:58 ERROR]: #!#! Language: english
[17:01:58 ERROR]: #!#! Link parse mode: DISABLED
[17:01:58 ERROR]: #!#! 
[17:01:58 ERROR]: #!#! End of Error.
[17:01:58 ERROR]: #!#! 

### Other

This is the second time i've gotten this exact error, just different line, first one i could fix by slightly changing it but i don't believe i can change it this time

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TenFont** [comment]
The zip file closed exception is usually caused by reloading plugins using the `/reload` command or using a tool like Plugman. Reloading your plugins the correct way (i.e. restarting the server) should fix this issue.

**Comment by hiimnobody496** [comment]
I already tried that but i'll try it again

**Comment by hiimnobody496** [comment]
It works again! thanks alot, guess that's all i had to do

**Comment by TenFont** [comment]
> It works again! thanks alot, guess that's all i had to do

No problem. Just remember not to use the `/reload` command or plugman to reload plugins in the future.
