### ISSUE TITLE
Idk problem with skript

### ISSUE THREAD

**Issue by Racoon-alt** [SkriptLang/Skript#7112]
### Skript/Server Version

```markdown
1.21.1
```

### Bug Description

No idea

### Expected Behavior

No idea

### Steps to Reproduce

No idea

### Errors or Screenshots

[12:39:06 INFO]: [Skript] Loading variables...
[12:39:07 INFO]: [Skript] Loaded 66677 variables in 1.3 seconds
[12:39:07 ERROR]: #!#! 
[12:39:07 ERROR]: #!#! [Skript] Severe Error:
[12:39:07 ERROR]: #!#! 
[12:39:07 ERROR]: #!#! Something went horribly wrong with Skript.
[12:39:07 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[12:39:07 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[12:39:07 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[12:39:07 ERROR]: #!#! 
[12:39:07 ERROR]: #!#! Stack trace:
[12:39:07 ERROR]: #!#! java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.hooks.regions.WorldGuardHook.getRegion_i(WorldGuardHook.java:216)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.hooks.regions.RegionsPlugin.getRegion(RegionsPlugin.java:112)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.hooks.regions.classes.Region.parse(Region.java:106)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.hooks.regions.classes.Region$2.parse(Region.java:80)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.hooks.regions.classes.Region$2.parse(Region.java:57)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.registrations.Classes.parseSimple(Classes.java:481)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.registrations.Classes.parse(Classes.java:510)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:599)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:781)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:162)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.ParseTagPatternElement.match(ParseTagPatternElement.java:89)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:63)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1323)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:232)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:207)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:217)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptEvent.parse(SkriptEvent.java:289)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.structures.StructEvent.init(StructEvent.java:69)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//org.skriptlang.skript.lang.structure.Structure.init(Structure.java:131)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:259)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:207)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:217)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:200)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:675)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$3(ScriptLoader.java:503)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:424)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:440)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:502)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:459)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[12:39:07 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[12:39:07 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[12:39:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226)
[12:39:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[12:39:07 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[12:39:07 ERROR]: #!#! Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
[12:39:07 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[12:39:07 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[12:39:07 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.hooks.regions.WorldGuardHook.getRegion_i(WorldGuardHook.java:216)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.hooks.regions.RegionsPlugin.getRegion(RegionsPlugin.java:112)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.hooks.regions.classes.Region.parse(Region.java:106)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.hooks.regions.classes.Region$2.parse(Region.java:80)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.hooks.regions.classes.Region$2.parse(Region.java:57)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.registrations.Classes.parseSimple(Classes.java:481)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.registrations.Classes.parse(Classes.java:510)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:599)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:781)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:162)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:43)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:65)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.ParseTagPatternElement.match(ParseTagPatternElement.java:89)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:63)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1323)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:232)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:207)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:217)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptEvent.parse(SkriptEvent.java:289)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.structures.StructEvent.init(StructEvent.java:69)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//org.skriptlang.skript.lang.structure.Structure.init(Structure.java:131)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:259)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:207)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:217)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:200)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:675)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$3(ScriptLoader.java:503)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:424)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:440)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:502)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:459)
[12:39:07 ERROR]: #!#!     at Skript-2.9.2.jar//ch.njol.skript.Skript$1.run(Skript.java:786)
[12:39:07 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[12:39:07 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[12:39:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226)
[12:39:07 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[12:39:07 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[12:39:07 ERROR]: #!#! 
[12:39:07 ERROR]: #!#! Version Information:
[12:39:07 ERROR]: #!#!   Skript: 2.9.2 (latest)
[12:39:07 ERROR]: #!#!     Flavor: skriptlang-github
[12:39:07 ERROR]: #!#!     Date: 14:35:57.106583600
[12:39:07 ERROR]: #!#!   Bukkit: 1.21.1-R0.1-SNAPSHOT
[12:39:07 ERROR]: #!#!   Minecraft: 1.21.1
[12:39:07 ERROR]: #!#!   Java: 21.0.3 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS)
[12:39:07 ERROR]: #!#!   OS: Linux amd64 6.2.0-36-generic
[12:39:07 ERROR]: #!#! 
[12:39:07 ERROR]: #!#! Server platform: Paper
[12:39:07 ERROR]: #!#! 
[12:39:07 ERROR]: #!#! Current node: null
[12:39:07 ERROR]: #!#! Current item: null
[12:39:07 ERROR]: #!#! 
[12:39:07 ERROR]: #!#! Thread: Server thread
[12:39:07 ERROR]: #!#! 
[12:39:07 ERROR]: #!#! Language: english
[12:39:07 ERROR]: #!#! Link parse mode: DISABLED
[12:39:07 ERROR]: #!#! 
[12:39:07 ERROR]: #!#! End of Error.
[12:39:07 ERROR]: #!

### Other

No

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment]
What plugins are you using? Do you use WorldGuard?

**Comment by Racoon-alt** [comment]
Yes i am using world guard

**Comment by Racoon-alt** [comment]
Yes i'm using worldguard, what abt it?


Den tis 24 sep. 2024 kl 15:06 skrev Patrick Miller ***@***.***

**Comment by APickledWalrus** [comment]
What version are you using? It looks like it's having trouble loading WorldGuard support

**Comment by Racoon-alt** [comment]
I'm using 1.21.1 Would anything Break if i changed to 1.20.1?


Den tis 24 sep. 2024 kl 17:38 skrev Patrick Miller ***@***.***

**Comment by APickledWalrus** [comment]
Make sure you're using the latest version of WorldGuard for 1.21.1. Does WorldGuard load correctly?

**Comment by Efnilite** [comment]
can you restart the server without worldguard and then send the error that occurs?

**Comment by erenkarakal** [comment]
Closing due to no response
