### ISSUE TITLE
IllegalStateException onEnable

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#7179]
### Skript/Server Version

```markdown
> skript info
[14:34:19 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:34:19 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[14:34:19 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[14:34:19 INFO]: [Skript] Server Version: 1.21.3-9-d19be64 (MC: 1.21.3)
[14:34:19 INFO]: [Skript] Skript Version: 2.9.4 (skriptlang-github)
[14:34:19 INFO]: [Skript] Installed Skript Addons: None
[14:34:19 INFO]: [Skript] Installed dependencies: 
[14:34:19 INFO]: [Skript]  - Vault v1.7.3-b131
[14:34:19 INFO]: [Skript]  - WorldGuard v7.0.13-SNAPSHOT+2311-764d258
```

### Bug Description

See error below

### Expected Behavior

Clean start-up

### Steps to Reproduce

- Install Paper 1.21.3-9
- Install Skript 2.9.4
- Start server
- Read console/log

### Errors or Screenshots

```
[14:29:51] [Server thread/INFO]: [Skript] The updater is disabled, so a check for the latest version of Skript was not performed.
[14:30:18] [Server thread/INFO]: [Skript] Loaded 233164 aliases in 27309ms
[14:30:19] [Server thread/ERROR]: #!#! 
[14:30:19] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[14:30:19] [Server thread/ERROR]: #!#! class ch.njol.skript.effects.EffEquip generated an exception while loading
[14:30:19] [Server thread/ERROR]: #!#!  
[14:30:19] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[14:30:19] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:30:19] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[14:30:19] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[14:30:19] [Server thread/ERROR]: #!#! 
[14:30:19] [Server thread/ERROR]: #!#! Stack trace:
[14:30:19] [Server thread/ERROR]: #!#! java.lang.IllegalStateException: Tags not bound, trying to access TagKey[minecraft:entity_type / minecraft:skeletons]
[14:30:19] [Server thread/ERROR]: #!#!     at net.minecraft.core.MappedRegistry$TagSet$1.get(MappedRegistry.java:479)
[14:30:19] [Server thread/ERROR]: #!#!     at net.minecraft.core.MappedRegistry.get(MappedRegistry.java:345)
[14:30:19] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.CraftServer.getTag(CraftServer.java:2856)
[14:30:19] [Server thread/ERROR]: #!#!     at org.bukkit.Bukkit.getTag(Bukkit.java:2504)
[14:30:19] [Server thread/ERROR]: #!#!     at org.bukkit.Tag.<clinit>(Tag.java:1286)
[14:30:19] [Server thread/ERROR]: #!#!     at Skript-2.9.4.jar//ch.njol.skript.effects.EffEquip.<clinit>(EffEquip.java:93)
[14:30:19] [Server thread/ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[14:30:19] [Server thread/ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:578)
[14:30:19] [Server thread/ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:557)
[14:30:19] [Server thread/ERROR]: #!#!     at Skript-2.9.4.jar//ch.njol.skript.util.Utils.getClasses(Utils.java:241)
[14:30:19] [Server thread/ERROR]: #!#!     at Skript-2.9.4.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:82)
[14:30:19] [Server thread/ERROR]: #!#!     at Skript-2.9.4.jar//ch.njol.skript.Skript.onEnable(Skript.java:539)
[14:30:19] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[14:30:19] [Server thread/ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[14:30:19] [Server thread/ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[14:30:19] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[14:30:19] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643)
[14:30:19] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592)
[14:30:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:767)
[14:30:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:529)
[14:30:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326)
[14:30:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233)
[14:30:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339)
[14:30:19] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1575)
[14:30:19] [Server thread/ERROR]: #!#!
[14:30:19] [Server thread/ERROR]: #!#! Version Information:
[14:30:19] [Server thread/ERROR]: #!#!   Skript: 2.9.4
[14:30:19] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[14:30:19] [Server thread/ERROR]: #!#!     Date: 17:01:27.299101300
[14:30:19] [Server thread/ERROR]: #!#!   Bukkit: 1.21.3-R0.1-SNAPSHOT
[14:30:19] [Server thread/ERROR]: #!#!   Minecraft: 1.21.3
[14:30:19] [Server thread/ERROR]: #!#!   Java: 23.0.1 (Java HotSpot(TM) 64-Bit Server VM 23.0.1+11-39)
[14:30:19] [Server thread/ERROR]: #!#!   OS: Mac OS X x86_64 12.7.6
[14:30:19] [Server thread/ERROR]: #!#!
[14:30:19] [Server thread/ERROR]: #!#! Server platform: Paper
[14:30:19] [Server thread/ERROR]: #!#!
[14:30:19] [Server thread/ERROR]: #!#! Current node: null
[14:30:19] [Server thread/ERROR]: #!#! Current item: null
[14:30:19] [Server thread/ERROR]: #!#!
[14:30:19] [Server thread/ERROR]: #!#! Thread: Server thread
[14:30:19] [Server thread/ERROR]: #!#!
[14:30:19] [Server thread/ERROR]: #!#! Language: english
[14:30:19] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[14:30:19] [Server thread/ERROR]: #!#!
[14:30:19] [Server thread/ERROR]: #!#! End of Error.
[14:30:19] [Server thread/ERROR]: #!#!
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Efnilite** [comment]
cannot reproduce, maybe try updating paper? you seem to be a build behind

**Comment by Romitou** [comment]
Cannot reproduce on latest build with given steps 
```
[22:47:43 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[22:47:43 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[22:47:43 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[22:47:43 INFO]: [Skript] Server Version: 1.21.3-10-92131ad (MC: 1.21.3)
[22:47:43 INFO]: [Skript] Skript Version: 2.9.4 (skriptlang-github)
[22:47:43 INFO]: [Skript] Installed Skript Addons: None
[22:47:43 INFO]: [Skript] Installed dependencies: None
```

**Comment by SlimeDog** [comment]
Error was reported on paper-1.21.3-9, which was current at the time. Error persists on paper-1.21.3-10, which was released a few minutes later. What more information should I provide.

**Comment by EquipableMC** [comment]
> Error was reported on paper-1.21.3-9, which was current at the time. Error persists on paper-1.21.3-10, which was released a few minutes later. What more information should I provide?

Could you send your entire /plugins list please?

**Comment by SlimeDog** [comment]
Plugin list is rather large. I'll do some isolation first.

**Comment by SlimeDog** [comment]
Skript 2.9.4 loaded/enabled successfully on paper-1.21.3-10 with only LuckPerms, PlaceholderAPI, ProtocolLib, and Vault. I will continue to isolate.

**Comment by SlimeDog** [comment]
success continues with added plugins, all latest versions:
- AggressiveAnimals, BiomeRemap, EntityCount, MobColors, NetworkInterceptor, pHD, PluginVersions (my own plugins)
- FancyHolograms (required for pHD to function)
- Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals

Moving on...

**Comment by SlimeDog** [comment]
Success continued with added plugins, development versions:
- WorldEdit bukkit-7.3.9-b6950
- WorldGuard bukkit-7.0.13-b2311

Moving on...

**Comment by sovdeeth** [comment]
You can just tell us when you found which one it is

**Comment by SlimeDog** [comment]
I have been unable to isolate the error to a small set of plugins. I will keep trying. Meanwhile, I'll update to Skript 2.10.0-beta1.

**Comment by SlimeDog** [comment]
What does ch.njol.skript.effects.EffEquip do?

**Comment by EquipableMC** [comment]
> It might help to know: What does ch.njol.skript.effects.EffEquip do?
> 
> UPDATE: Got it: equip or unequip armor. I have a script that equips nether armor, but disabling (ie., removing) it does not resolve the error.

The EffEquip line, it’s the directory to the Equip effect. It’s meant for plugin devs to know exactly what file went wrong and where it’s located

**Comment by SlimeDog** [comment]
So identified, it can be fixed without you having to reproduce it?

**Comment by Efnilite** [comment]
no, for us it runs fine. for us to fix it, you should try to provide a way to reliably replicate it, so we can identify what goes wrong and where

**Comment by SlimeDog** [comment]
Sure, but I have been unable to isolate it. I don't run MC servers anymore.  If no one else is experiencing the issue, I am disinclined to spend any more time on it. Most likely, the interaction with some other plugin will resolve itself as more plugins are updated to support 1.21.3.

**Comment by SlimeDog** [comment]
After the Citizens update (above), I have enjoyed 7 server restarts without encountering the error. I am willing to consider it resolved by external events.
