### ISSUE TITLE
skript 2.9.4 bug

### ISSUE THREAD

**Issue by rqqnz** [SkriptLang/Skript#7182]
### Skript/Server Version

```markdown
[14:45:07 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:45:07 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[14:45:07 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[14:45:07 INFO]: [Skript] Server Version: git-Paper-388 (MC: 1.18.2)
[14:45:07 INFO]: [Skript] Skript Version: 2.9.4 (skriptlang-github)
[14:45:07 INFO]: [Skript] Installed Skript Addons: None
[14:45:07 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

Idk, i just put skript 2.9.4 in the plugin folder and in console was bug

### Expected Behavior

I dont know

### Steps to Reproduce

4:39:09 INFO]: [Skript]     Error while loading plugin hooks: zip END header not found
[14:39:09 ERROR]: #!#! 
[14:39:09 ERROR]: #!#! [Skript] Severe Error:
[14:39:09 ERROR]: #!#! 
[14:39:09 ERROR]: #!#! Something went horribly wrong with Skript.
[14:39:09 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:39:09 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[14:39:09 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[14:39:09 ERROR]: #!#! 
[14:39:09 ERROR]: #!#! Stack trace:
[14:39:09 ERROR]: #!#! java.util.zip.ZipException: zip END header not found
[14:39:09 ERROR]: #!#!     at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1633)
[14:39:09 ERROR]: #!#!     at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1641)
[14:39:09 ERROR]: #!#!     at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1479)
[14:39:09 ERROR]: #!#!     at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1441)
[14:39:09 ERROR]: #!#!     at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718)
[14:39:09 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:252)
[14:39:09 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181)
[14:39:09 ERROR]: #!#!     at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
[14:39:09 ERROR]: #!#!     at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
[14:39:09 ERROR]: #!#!     at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
[14:39:09 ERROR]: #!#!     at Skript-2.9.4.jar//ch.njol.skript.Skript$1.run(Skript.java:561)
[14:39:09 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[14:39:09 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[14:39:09 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[14:39:09 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:39:09 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[14:39:09 ERROR]: #!#! 
[14:39:09 ERROR]: #!#! Version Information:
[14:39:09 ERROR]: #!#!   Skript: 2.9.4 (latest)
[14:39:09 ERROR]: #!#!     Flavor: skriptlang-github
[14:39:09 ERROR]: #!#!     Date: 17:01:27.299101300
[14:39:09 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[14:39:09 ERROR]: #!#!   Minecraft: 1.18.2
[14:39:09 ERROR]: #!#!   Java: 17.0.11 (OpenJDK 64-Bit Server VM 17.0.11+9)
[14:39:09 ERROR]: #!#!   OS: Linux amd64 5.4.0-177-generic
[14:39:09 ERROR]: #!#! 
[14:39:09 ERROR]: #!#! Server platform: Paper
[14:39:09 ERROR]: #!#! 
[14:39:09 ERROR]: #!#! Current node: null
[14:39:09 ERROR]: #!#! Current item: null
[14:39:09 ERROR]: #!#! 
[14:39:09 ERROR]: #!#! Thread: Server thread
[14:39:09 ERROR]: #!#! 
[14:39:09 ERROR]: #!#! Language: english
[14:39:09 ERROR]: #!#! Link parse mode: DISABLED
[14:39:09 ERROR]: #!#! 
[14:39:09 ERROR]: #!#! End of Error.
[14:39:09 ERROR]: #!#! 

### Errors or Screenshots

![image](https://github.com/user-attachments/assets/3513c726-752c-427d-9cbb-7bd275e73092)
![image](https://github.com/user-attachments/assets/e1431cd5-dde2-4651-9d8f-0828e57f328d)

### Other

I think no but the skript is working ig but just the bug 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Efnilite** [comment]
try restarting your server

**Comment by rqqnz** [comment]
ty
